# Teste MT

In [157]:
import pandas as pd
import os
from collections import defaultdict
from datetime import datetime, timedelta
import re
import numpy as np
from pathlib import Path

os.chdir('/home/nobre/Notebooks/RQAR_2025_book/')

In [18]:
funcoes = {
    
    'MT': rectify_MT,
}

lista_estados = ['MT']

tabela_ids = pd.read_csv('/home/nobre/Notebooks/RQAR_2025_book/data/Monitoramento_QAr_BR.csv')
tabela_pols = pd.read_csv('/home/nobre/Notebooks/RQAR_2025_book/data/dicionarios/CODIGO_POLUENTES.csv')

In [72]:

estado = 'DF'
  
path = os.getcwd()+'/data/DADOS_BRUTOS/' + estado + '/'

#df_ids = funcoes[estado](path)
    
#create_df_estacao(estado,df_ids)

In [52]:
dict_pols_stat = defaultdict(list)

files = os.listdir(path)

print(files)

for item in files:
    
    estacao = " ".join(item.split('-')[1].split('.')[0].split('_')[0:2])

    print(estacao)

    df = pd.read_excel(path+item)

    df = df.drop(columns=['Nome da estação'])

    lista_pols = set(df['Poluente'])

    for pol in lista_pols:

        df_pol = df[df["Poluente"] == pol]
        
        if pol in ['no2','so2','o3']:

            df_pol = ppb_to_ug(df_pol,pol)

        df_pol_hora = df_pol.groupby(["Ano", "Mes", "Dia", "Hora", "Unidade"])
        
        df_pol_hora = df_pol_hora.filter(lambda g: len(g) >= 9)
        
        df_pol = (
            df_pol_hora.groupby(["Ano", "Mes", "Dia", "Hora", "Unidade"], as_index=False)
                  .agg({"Valor": "mean"})
        )

        df_pol['QAQC_INTERNO'] = None

        df_pol = df_pol.rename(columns={'Ano':'ANO',
                                        'Mes':'MES',
                                        'Dia':'DIA',
                                        'Hora':'HORA',
                                        'Unidade':'UNIDADE',
                                        'Valor':'VALOR'})

        for col in ["ANO", "MES", "DIA", "HORA"]:
            df_pol[col] = pd.to_numeric(df_pol[col], errors="coerce").astype("Int64")
        
        dict_pols_stat[estacao+'_'+pol].append(df_pol)

['dados_monitoramento-Sema.xlsx', 'dados_monitoramento-BEA_CBA_24-25.xlsx', 'dados_monitoramento-BEA_CBA_22-23.xlsx', 'dados_monitoramento-CBM_VG_22-23.xlsx', 'dados_monitoramento-CBM_VG_24-25.xlsx', 'dados_monitoramento-Mae_Bonifacia_22-23.xlsx', 'dados_monitoramento-Mae_Bonifacia_24-25.xlsx', 'dados_monitoramento-UFMT.xlsx']
Sema
BEA CBA
BEA CBA
CBM VG
CBM VG
Mae Bonifacia
Mae Bonifacia
UFMT

In [46]:
def ppb_to_ug(df,pol):

    if pol == 'so2':

        df.loc[df["Unidade"] != "ug/m3", "Valor"] *= 2661260.49/10**6        

    elif pol == 'no2':

        df.loc[df["Unidade"] != "ug/m3", "Valor"] *= 1911038.92/10**6        

    elif pol == 'o3':

        df.loc[df["Unidade"] != "ug/m3", "Valor"] *= 1993889.17/10**6        
    
    df.loc[:, "Unidade"] = "ug/m3"

    return df

In [60]:
dict_pols_MT = {
    'co':'CO',
    'no2': 'NO2',
    'so2': 'SO2',
    'o3': 'O3',
    'pm2p5':'MP25',
    'pm10': 'MP10'
}

dict_formatado = {}

for chave in dict_pols_stat.keys():
    
    lista_dfs = dict_pols_stat[chave]
    
    df = pd.concat(lista_dfs, ignore_index=True)

    df["DATETIME"] = pd.to_datetime(
        df.apply(lambda r: f"{r.ANO}-{r.MES}-{r.DIA} {r.HORA}:00:00", axis=1)
    )
    df = df.set_index("DATETIME")

    df = df.sort_index()
    
    lista_horas = pd.date_range(
        start=df.index.min(), 
        end=df.index.max(), 
        freq='H').strftime('%Y-%m-%d %H:%M:%S').tolist()
    
    if len(lista_horas) != len(df):
        df = df.reindex(pd.DatetimeIndex(lista_horas))

    df['DATETIME'] = df.index

    df = df[['DATETIME','ANO','MES','DIA','HORA','VALOR','UNIDADE','QAQC_INTERNO']]
    
    dict_formatado[chave] = df

primeiros_valores = {}

for chave, df in dict_formatado.items():
    
    if ~df['VALOR'].isna().all() and (df['VALOR'] > 0).any(): 
        
        linha_valida = df[df["VALOR"].notna() & (df["VALOR"] > 0)].iloc[0]
        primeiros_valores[chave] = linha_valida["DATETIME"]

codigo_estacao_MT = {}

for chave in primeiros_valores.keys():
    
    station = chave.split('_')[0]
    data = primeiros_valores[chave]
    
    if station in codigo_estacao_MT:
        if data <= codigo_estacao_MT[station]:
            codigo_estacao_MT[station] = data
    else:
        codigo_estacao_MT[station] = data

sorted_items = sorted(
    codigo_estacao_MT.items(),
    key=lambda x: (x[1], x[0])
)

codigo_estacao_MT = {}
for i, (nome, ts) in enumerate(sorted_items, start=1):
    codigo = f"MT{i:04d}"
    codigo_estacao_MT[nome] = codigo
    
for chave, df in dict_formatado.items():
    
    estacao = codigo_estacao_MT[chave.split('_')[0]]
    
    cod_pol = tabela_pols.loc[tabela_pols['POLUENTE'] == dict_pols_MT[chave.split('_')[-1]], 'COD_POLUENTE'].values[0]
    
    nome_pasta = tabela_pols.loc[tabela_pols['COD_POLUENTE'] == int(cod_pol), 'NOME_PASTA'].values[0]
    
    df.to_csv('/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/'+nome_pasta+'/'+estacao+'RA'+str(cod_pol).zfill(3)+'.csv',index=False)

df_ids = pd.DataFrame({
    'ID_OEMA': codigo_estacao_MT.keys(),
    'ID_MMA':list(codigo_estacao_MT.values())})

return df_ids

/tmp/ipykernel_564959/2479180702.py:25: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_564959/2479180702.py:25: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_564959/2479180702.py:25: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_564959/2479180702.py:25: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_564959/2479180702.py:25: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_564959/2479180702.py:25: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_564959/2479180702.py:25: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_564959/2479180702.py:25: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_564959/2479180702.py:25: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_564959/2479180702.py:25: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_564959/2479180702.py:25: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_564959/2479180702.py:25: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_564959/2479180702.py:25: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_564959/2479180702.py:25: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_564959/2479180702.py:25: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_564959/2479180702.py:25: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_564959/2479180702.py:25: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_564959/2479180702.py:25: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_564959/2479180702.py:25: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_564959/2479180702.py:25: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_564959/2479180702.py:25: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_564959/2479180702.py:25: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_564959/2479180702.py:25: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_564959/2479180702.py:25: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_564959/2479180702.py:25: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_564959/2479180702.py:25: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_564959/2479180702.py:25: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_564959/2479180702.py:25: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_564959/2479180702.py:25: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_564959/2479180702.py:25: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(

SyntaxError: 'return' outside function (2479180702.py, line 85)

In [61]:
df_ids

         ID_OEMA  ID_MMA
0  Mae Bonifacia  MT0001
1        BEA CBA  MT0002
2         CBM VG  MT0003
3           Sema  MT0004
4           UFMT  MT0005

In [185]:
from datetime import timedelta

def fix_24h(row):
    if isinstance(row, str) and row.startswith("24:"):
        # substitui 24: por 00:
        new_str = row.replace("24:", "00:", 1)
        # converte para datetime
        dt = pd.to_datetime(new_str, errors="coerce")
        # adiciona 1 dia
        if pd.notna(dt):
            dt += timedelta(days=1)
        return dt
    else:
        return pd.to_datetime(row, errors="coerce")

In [70]:
dict_stations_MT = {
        'Sema':'CPA - SEMA - CBA',
        'BEA CBA': 'Dom Aquino - BEA - CBA',
        'CBM VG': 'Água Limpa - CBM - VG',
        'Mae Bonifacia': 'Duque de Caxias - Pq Mãe Bonifácia - CBA',
        'UFMT':'Boa Esperança - UFMT - CBA'
    }
    
df_ids = pd.DataFrame({
    'ID_OEMA': codigo_estacao_MT.keys(),
    'ID_MMA':list(codigo_estacao_MT.values())})


df_ids["ID_OEMA"] = df_ids["ID_OEMA"].replace(dict_stations_MT)


df_ids['ID_OEMA']

0    Duque de Caxias - Pq Mãe Bonifácia - CBA
1                      Dom Aquino - BEA - CBA
2                       Água Limpa - CBM - VG
3                            CPA - SEMA - CBA
4                  Boa Esperança - UFMT - CBA
Name: ID_OEMA, dtype: object

In [71]:
df_ids

                                    ID_OEMA  ID_MMA
0  Duque de Caxias - Pq Mãe Bonifácia - CBA  MT0001
1                    Dom Aquino - BEA - CBA  MT0002
2                     Água Limpa - CBM - VG  MT0003
3                          CPA - SEMA - CBA  MT0004
4                Boa Esperança - UFMT - CBA  MT0005

In [120]:
estado = 'DF'

In [249]:
path = os.getcwd()+'/data/DADOS_BRUTOS/' + estado + '/'

path = path + 'Monitor Report 2024_FINAL.xlsx'

df = pd.read_excel(path)

df.iloc[1] = df.iloc[1].ffill()

poluentes = ['CO_ppm','NO2_ug/m3','NO_ug/m3','NOx_ug/m3','O3_ug/m3','PM10','PM25','PTS','SO2_ug/m3']

dict_pols = {'CO_ppm':'CO',
             'NO2_ug/m3':'NO2',
             'NO_ug/m3':'NO',
             'NOx_ug/m3':'NOX',
             'O3_ug/m3':'O3',
             'PM10':'MP10',
             'PM25':'MP25',
             'PTS':'PTS',
             'SO2_ug/m3':'SO2'}

df.columns = df.iloc[1]

df = df.drop(index=[0, 1]).reset_index(drop=True)

df = df.rename(columns={'Date Time':'DATETIME'})

estacoes = set(df.columns[1:])

dict_pols_stat = defaultdict(list)

for estacao in estacoes:

    df_estacao = df[["DATETIME",estacao]]

    df_estacao.columns = [df_estacao.columns.tolist()[0]] + df_estacao.iloc[0, 1:].tolist()

    df_estacao = df_estacao.drop(index=[0]).reset_index(drop=True)

    for pol in poluentes:

        if pol in df_estacao.columns:
            
            df_pol = df_estacao[["DATETIME",pol]]

            df_pol['UNIDADE'] = df_pol[pol][0]

            df_pol = df_pol.drop(index=[0]).reset_index(drop=True)

            df_pol = df_pol[df_pol["DATETIME"].astype(str).str.contains(r"\d", na=False)].reset_index(drop=True)

            df_pol['DATETIME'] = df_pol['DATETIME'].apply(fix_24h)

            df_pol = df_pol.rename(columns={pol:'VALOR'})

            df_pol.index = df_pol['DATETIME']

            lista_horas = pd.date_range(
                start=df_pol.index.min(), 
                end=df_pol.index.max(), 
                freq='H').strftime('%Y-%m-%d %H:%M:%S').tolist()
            
            if len(lista_horas) != len(df_pol):
                df_pol = df_pol.reindex(pd.DatetimeIndex(lista_horas))
            
            df_pol['QAQC_INTERNO'] = None
            
            df_pol.insert(1, 'ANO', df_pol.index.year)
            df_pol.insert(2, 'MES', df_pol.index.month)
            df_pol.insert(3, 'DIA', df_pol.index.day)
            df_pol.insert(4, 'HORA', df_pol.index.hour)

            pol = dict_pols[pol]

            df_pol['VALOR'] = pd.to_numeric(df_pol['VALOR'], errors='coerce')

            df_pol = df_pol[['DATETIME','ANO','MES','DIA','HORA','VALOR','UNIDADE','QAQC_INTERNO']] 

            dict_pols_stat[estacao+'_'+pol] = df_pol

/tmp/ipykernel_564959/901552261.py:45: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_pol['UNIDADE'] = df_pol[pol][0]
/tmp/ipykernel_564959/1508039512.py:14: UserWarning: Parsing dates in %d:%M %m/%H/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  return pd.to_datetime(row, errors="coerce")
/tmp/ipykernel_564959/901552261.py:57: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_564959/901552261.py:45: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_pol['UNIDADE'] = df_pol[pol][0]
/tmp/ipykernel_564959/1508039512.py:14: UserWarning: Parsing dates in %d:%M %m/%H/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  return pd.to_datetime(row, errors="coerce")
/tmp/ipykernel_564959/901552261.py:57: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_564959/901552261.py:45: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_pol['UNIDADE'] = df_pol[pol][0]
/tmp/ipykernel_564959/1508039512.py:14: UserWarning: Parsing dates in %d:%M %m/%H/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  return pd.to_datetime(row, errors="coerce")
/tmp/ipykernel_564959/901552261.py:57: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_564959/901552261.py:45: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_pol['UNIDADE'] = df_pol[pol][0]
/tmp/ipykernel_564959/1508039512.py:14: UserWarning: Parsing dates in %d:%M %m/%H/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  return pd.to_datetime(row, errors="coerce")
/tmp/ipykernel_564959/901552261.py:57: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_564959/901552261.py:45: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_pol['UNIDADE'] = df_pol[pol][0]
/tmp/ipykernel_564959/1508039512.py:14: UserWarning: Parsing dates in %d:%M %m/%H/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  return pd.to_datetime(row, errors="coerce")
/tmp/ipykernel_564959/901552261.py:57: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_564959/901552261.py:45: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_pol['UNIDADE'] = df_pol[pol][0]
/tmp/ipykernel_564959/1508039512.py:14: UserWarning: Parsing dates in %d:%M %m/%H/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  return pd.to_datetime(row, errors="coerce")
/tmp/ipykernel_564959/901552261.py:57: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_564959/901552261.py:45: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_pol['UNIDADE'] = df_pol[pol][0]
/tmp/ipykernel_564959/1508039512.py:14: UserWarning: Parsing dates in %d:%M %m/%H/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  return pd.to_datetime(row, errors="coerce")
/tmp/ipykernel_564959/901552261.py:57: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_564959/901552261.py:45: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_pol['UNIDADE'] = df_pol[pol][0]
/tmp/ipykernel_564959/1508039512.py:14: UserWarning: Parsing dates in %d:%M %m/%H/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  return pd.to_datetime(row, errors="coerce")
/tmp/ipykernel_564959/901552261.py:57: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_564959/901552261.py:45: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_pol['UNIDADE'] = df_pol[pol][0]
/tmp/ipykernel_564959/1508039512.py:14: UserWarning: Parsing dates in %d:%M %m/%H/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  return pd.to_datetime(row, errors="coerce")
/tmp/ipykernel_564959/901552261.py:57: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_564959/901552261.py:45: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_pol['UNIDADE'] = df_pol[pol][0]
/tmp/ipykernel_564959/1508039512.py:14: UserWarning: Parsing dates in %d:%M %m/%H/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  return pd.to_datetime(row, errors="coerce")
/tmp/ipykernel_564959/901552261.py:57: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_564959/901552261.py:45: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_pol['UNIDADE'] = df_pol[pol][0]
/tmp/ipykernel_564959/1508039512.py:14: UserWarning: Parsing dates in %d:%M %m/%H/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  return pd.to_datetime(row, errors="coerce")
/tmp/ipykernel_564959/901552261.py:57: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(

In [258]:
primeiros_valores = {}

for chave, df in dict_pols_stat.items():  
    
    if ~df['VALOR'].isna().all() and (df['VALOR'] > 0).any(): 
        
        linha_valida = df[df["VALOR"].notna() & (df["VALOR"] > 0)].iloc[0]
        primeiros_valores[chave] = linha_valida["DATETIME"]

codigo_estacao_DF = {}

for chave in primeiros_valores.keys():
    
    station = chave.split('_')[0]
    data = primeiros_valores[chave]
    
    if station in codigo_estacao_DF:
        if data <= codigo_estacao_DF[station]:
            codigo_estacao_DF[station] = data
    else:
        codigo_estacao_DF[station] = data

sorted_items = sorted(
    codigo_estacao_DF.items(),
    key=lambda x: (x[1], x[0])
)

codigo_estacao_DF = {}
for i, (nome, ts) in enumerate(sorted_items, start=1):
    codigo = f"DF{i:04d}"
    codigo_estacao_DF[nome] = codigo
    
for chave, df in dict_pols_stat.items():
    
    estacao = codigo_estacao_DF[chave.split('_')[0]]
    
    cod_pol = tabela_pols.loc[tabela_pols['POLUENTE'] == chave.split('_')[-1], 'COD_POLUENTE'].values[0]
    
    nome_pasta = tabela_pols.loc[tabela_pols['COD_POLUENTE'] == int(cod_pol), 'NOME_PASTA'].values[0]
    
    df.to_csv('/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/'+nome_pasta+'/'+estacao+'RA'+str(cod_pol).zfill(3)+'.csv',index=False)

dict_oemas = {
    'Estação CRAS FERCAL': 'Fercal CRAS',
    'Estação Escola':	   'Fercal Escola'}

df_ids = pd.DataFrame({
    'ID_OEMA': codigo_estacao_DF.keys(),
    'ID_MMA':list(codigo_estacao_DF.values())})

df_ids['ID_OEMA'] = df_ids['ID_OEMA'].replace(dict_oema)

return df_ids

In [275]:
df_ufs = pd.read_csv('/home/nobre/Notebooks/RQAR_2025_book/data/dicionarios/IBGE_UFS_CODIGOS.csv')
    
cod_uf =  df_ufs.loc[df_ufs['UF'] == uf, 'CODIGOS'].values[0]

print(cod_uf)

if os.path.exists('/home/nobre/Notebooks/RQAR_2025_book/data/DADOS_ESTACOES/'+uf+'_estacoes.csv'):

    df_estacao = pd.read_csv('/home/nobre/Notebooks/RQAR_2025_book/data/DADOS_ESTACOES/'+uf+'_estacoes.csv')

    df_estacao['ID_MMA'] = df_estacao['ID_OEMA'].map(df_ids.set_index('ID_OEMA')['ID_MMA'])

else:

    colunas = ['ID_OEMA', 'UF', 'ID_MMA', 'COD_UF_IBGE', 'CIDADE', 'CD_MUN',
               'PROPRIETARIO', 'PROP_ENTIDADE', 'OPERADOR', 'OP_ENTIDADE', 'LATITUDE',
               'LONGITUDE', 'MOBILIDADE', 'REALOCACAO', 'MARCA', 'CATEGORIA',
               'FUNCIONAMENTO', 'METODO', 'FINALIDADE', 'POLUENTE',
               'INICIO', 'STATUS', 'FIM', 'CALIBRACAO', 'OBS_CALIBRACAO', 'MONITORAR',
               'FONTE', 'OBS_GERAIS','DADOS_MONITORAMENTO','RECONHECIDA','REP_ESPACIAL_DECLARADA']
    
    df_estacao = pd.DataFrame(columns=colunas)

df_ids = pol_to_station(df_ids)

mapa = dict(zip(df_ids['ID_MMA'], df_ids['POLUENTE']))

df_estacao['POLUENTE'] = df_estacao['ID_MMA'].map(mapa).fillna(df_estacao['POLUENTE'])

#df_estacao = df_estacao.reindex(df_ids.index)

#df_estacao[["ID_MMA", "ID_OEMA", "POLUENTE"]] = df_ids[["ID_MMA", "ID_OEMA", "POLUENTE"]].values

df_estacao.loc[:, "COD_UF_IBGE"] = cod_uf
df_estacao.loc[:, "UF"] = uf
    
#df_estacao.to_csv('/home/nobre/Notebooks/RQAR_2025_book/data/DADOS_ESTACOES/'+uf+'_estacoes_teste.csv', index=False)

53

In [276]:
df_estacao['POLUENTE']

0                                 PM2,5
1                                  PM10
2                             MP10,MP25
3                                  PM10
4                                  PM10
5                           MP2,5, MP10
6                           MP2,5, MP10
7                           MP2,5, MP10
8    MP10,NO,CO,PTS,O3,SO2,NO2,NOX,MP25
Name: POLUENTE, dtype: object

In [262]:
def pol_to_station(df_ids):

    base_path = Path('/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/')

    id_to_poluentes = {}
    
    for poluente_dir in base_path.iterdir():
        if poluente_dir.is_dir():
            poluente = poluente_dir.name
    
            arquivos = [arq.stem for arq in poluente_dir.glob("*")]
    
            for id_mma in df_ids["ID_MMA"]:
                if any(str(arq).startswith(id_mma) for arq in arquivos):
                    id_to_poluentes.setdefault(id_mma, []).append(poluente)
    
    df_ids["POLUENTE"] = df_ids["ID_MMA"].map(id_to_poluentes).fillna("").apply(lambda x: ",".join(x) if isinstance(x, list) else "")
    
    return(df_ids)

# Paraná

In [4]:
df = pd.read_csv(os.getcwd()+'/data/DADOS_BRUTOS/PR/2017/FOZ2017/2017.xls', sep='\t', engine='python', encoding='latin1', header=2 )

df

,Data/Hora,CHUVA(mm),DV(º),PRESS(hPa),RADG(W/m²),TEMP(°C),TEMP INT(°C),UMID(%),VV(m/s),CH4(ppm),...,HCNM(ppm),HCT(ppm),MP10(µg/m³),NO(ppb),NO2(ppb),NOX(ppb),O3(ppb),PTS(µg/m³),SO2(ppb),Unnamed: 20
0,21/06/2017 00:00,insufic,"47,81",insufic,insufic,insufic,insufic,insufic,insufic,insufic,...,insufic,insufic,insufic,insufic,insufic,insufic,insufic,insufic,insufic,NaN
1,21/06/2017 01:00,insufic,insufic,insufic,insufic,insufic,insufic,insufic,insufic,insufic,...,insufic,insufic,insufic,insufic,insufic,insufic,insufic,insufic,insufic,NaN
2,21/06/2017 02:00,insufic,insufic,insufic,insufic,insufic,insufic,insufic,insufic,insufic,...,insufic,insufic,insufic,insufic,insufic,insufic,insufic,insufic,insufic,NaN
3,21/06/2017 03:00,insufic,insufic,insufic,insufic,insufic,insufic,insufic,insufic,insufic,...,insufic,insufic,insufic,insufic,insufic,insufic,insufic,insufic,insufic,NaN
4,21/06/2017 04:00,insufic,insufic,insufic,insufic,insufic,insufic,insufic,insufic,insufic,...,insufic,insufic,insufic,insufic,insufic,insufic,insufic,insufic,insufic,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4652,31/12/2017 20:00,"0,00","91,25","977,88",insufic,"30,06","30,13","68,28","0,42",insufic,...,insufic,insufic,"54,00","20,56","14,74","35,31","8,72","76,00",insufic,NaN
4653,31/12/2017 21:00,"0,00","50,02","977,78",insufic,"29,45","30,15","73,63","0,47",insufic,...,insufic,insufic,"62,00","0,82","6,98","7,80","10,42","74,00",insufic,NaN
4654,31/12/2017 22:00,"0,00","356,79","978,03",insufic,"28,75","30,16","77,48","0,51",insufic,...,insufic,insufic,"17,00","0,23","6,52","6,75","11,36","13,00",insufic,NaN
4655,31/12/2017 23:00,"0,00","13,49","978,11",insufic,"28,27","30,30","78,45","0,31",insufic,...,insufic,insufic,"41,00","2,15","8,29","10,44","8,64","43,00",insufic,NaN
4656,01/01/2018 00:00,"0,00","116,34","978,15","0,58","27,86","30,30","76,98","0,44",insufic,...,insufic,insufic,"28,00","3,62","6,74","10,36","11,03","27,00",insufic,NaN

In [212]:
caminho = os.getcwd()+'/data/DADOS_BRUTOS/PR/2024/'
    
arquivo = 'CIC2024.xls'

if arquivo.endswith(('.xls', '.xlsx')):
    caminho_arquivo = os.path.join(caminho, arquivo)
    try:
        df = pd.read_excel(caminho_arquivo, header=3)
    except Exception as e:
        print(f"Tentando ler como texto: {arquivo}")
        df = pd.read_csv(caminho_arquivo, sep='\t', engine='python', encoding='latin1', header=2)
        print(len(df))
        
    col_data = next(c for c in df.columns if c.startswith('Data'))

    df = (
    df.replace('-', np.nan)
      .assign(**{
          c: pd.to_numeric(
              df[c].astype(str).str.replace(',', '.', regex=False),
              errors='coerce'
          )
          for c in df.columns if c != col_data
      })
      .groupby(col_data, as_index=False)
      .agg(lambda x: x.dropna().iloc[0] if len(x.dropna()) else np.nan)
    )
    
    if '5MIN' in arquivo:
        estacao = arquivo.split('_')[0]
    else:
        estacao = arquivo.split('2')[0]
    
    if df.columns[0] == 'Data/Hora':

        print(estacao)

Tentando ler como texto: CIC2024.xls
8784

KeyboardInterrupt:

In [ ]:
print(len(df1))
print(len(df2))

In [213]:
def ler_dados_parana_2024(dicionario,ano):
    
    #caminho =  os.getcwd()+'/data/DADOS_BRUTOS/PR/2024/'

    caminho = os.getcwd()+'/data/DADOS_BRUTOS/PR/'+ano+'/'
    
    arquivos = os.listdir(caminho)
    
    for arquivo in arquivos:
    
        if arquivo.endswith(('.xls', '.xlsx')):
            caminho_arquivo = os.path.join(caminho, arquivo)
            try:
                df = pd.read_excel(caminho_arquivo, header=3)
            except Exception as e:
                print(f"Tentando ler como texto: {arquivo}")
                df = pd.read_csv(caminho_arquivo, sep='\t', engine='python', encoding='latin1', header=2)
                print(len(df))
                
            col_data = next(c for c in df.columns if c.startswith('Data'))
        
            df = (
            df.replace('-', np.nan)
              .assign(**{
                  c: pd.to_numeric(
                      df[c].astype(str).str.replace(',', '.', regex=False),
                      errors='coerce'
                  )
                  for c in df.columns if c != col_data
              })
              .groupby(col_data, as_index=False)
              .agg(lambda x: x.dropna().iloc[0] if len(x.dropna()) else np.nan)
            )
            
            if '5MIN' in arquivo:
                estacao = arquivo.split('_')[0]
            else:
                estacao = arquivo.split('2')[0]
            
            if df.columns[0] == 'Data/Hora':
        
                print(estacao)
    
                dicionario[ano][estacao] = df

            print(len(df))

    return dicionario

def adicionar_colunas_unidade(df):
    unidades = df.iloc[0]
    
    df = df.iloc[1:].reset_index(drop=True)
    
    for col, unidade in unidades.items():
        if pd.notna(unidade):
            df[f"{col}_UNIDADE"] = unidade
    
    return df

def num_para_hora(valor):
    try:
        h = int(valor)
        m = "30" if valor % 1 == 0.5 else "00"
        return f"{h}:{m}"
    except:
        return None
        
    return df

def ler_dados_parana_1998_2002(dicionario,ano):
    
    caminho = os.getcwd()+'/data/DADOS_BRUTOS/PR/'+ano+'/'
        
    arquivos = os.listdir(caminho)
    
    for arquivo in arquivos:

        print(arquivo)
    
        if any(Path(caminho+arquivo).iterdir()):
            pasta = os.listdir(caminho+arquivo)[0]
    
            df = pd.read_excel(caminho+arquivo+'/'+pasta,header=1)

            df = adicionar_colunas_unidade(df)

            for hora in ['H', 'HORA', 'Hora']:
                if hora in df.columns:
                    df[hora] = df[hora].astype(float).apply(num_para_hora)
                    break

            estacao = arquivo[:-4]
    
            dicionario[ano][estacao] = df 

            print(len(df))
    
        else:
            print('Não há nada em '+ caminho+arquivo)

    return dicionario

def ler_dados_mes_a_mes(caminho):

    tipos_arquivos_ignorar = ['.zip','.rar','.xls','.xlsx','.7z','testes','2016','.ipynb_checkpoints']

    df = pd.DataFrame()

    #print(caminho)
    #print(sorted(os.listdir(caminho)))

    estacao = caminho.split('/')[-2].split('2')[0]
    
    for arquivo in sorted(os.listdir(caminho)):
        df_mes = pd.DataFrame()
    
        if not any(p in arquivo for p in tipos_arquivos_ignorar) or any(p in arquivo for p in ['txt']):

            if '.txt' in arquivo:
                df_mes = pd.read_csv(caminho+arquivo, sep='\t', engine='python', encoding='latin1')
                #print(df_mes.head())
                #print(arquivo)
                df = pd.concat([df, df_mes], ignore_index=True)
            
            else:
                mes = arquivo[:2]
                base_path = os.path.join(caminho, arquivo)
                
                nomes_possiveis = [
                    [f"{estacao}1H_{mes}_{ano}.txt",0],
                    [f"{estacao}1H.txt",0],
                    [f"{estacao}1H_{mes}_{ano}.xls",3],
                    [f"{estacao}_1H.xls",2]
                ]

                for nome in nomes_possiveis:
                    full_path = os.path.join(base_path, nome[0])
                    
                    try:
                        df_mes = pd.read_csv(full_path, sep='\t', engine='python', encoding='latin1',header=nome[1])
                        break
                    except Exception:
                        try:
                            df_mes = pd.read_excel(full_path, engine='xlrd',header=nome[1])
                            break
                        except Exception:
                            continue

            if len(df_mes) == 0:

                print(caminho)
                #print(sorted(os.listdir(caminho)))
                #print(arquivo)
                print(df_mes.head())
                print('')
                
            df = pd.concat([df, df_mes], ignore_index=True)

            #df = pd.concat([df, df_mes], ignore_index=True)
           
    
    print('')
            
    
    return df

def verifica_numero(num):
    try:
        if num != np.nan:
            float(num)
            return True
    except (ValueError, TypeError):
        return False

def verifica_data(data):
    try:
        pd.to_datetime(data)
        return True
    except (ValueError, TypeError):
        return False

def ler_dados_parana_2003_2019(dicionario,ano):

    pastas_ignorar = ['IQA diário','IQA_IAP','2016','ARAUCARIA2018','ARAUCARIA2019','Thumbs.db','~$Validação_Maio_2014.xlsm','SIX1H_2017.zip','.ipynb_checkpoints']

    caminho = os.getcwd()+'/data/DADOS_BRUTOS/PR/'+ano+'/'
        
    arquivos = os.listdir(caminho)

    print('')
    print(ano)
    
    for arquivo in arquivos:

        if arquivo not in pastas_ignorar:

            print(arquivo)
            
            if any(nome.endswith(('.xls', '.xlsx')) for nome in os.listdir(caminho+arquivo)) and len(os.listdir(caminho+arquivo)) <= 3:
                print(os.listdir(caminho+arquivo))

                xlsx = [f for f in os.listdir(caminho+arquivo) if f.endswith('.xlsx')]
                xls = [f for f in os.listdir(caminho+arquivo) if f.endswith('.xls')]
                
                if xlsx:
                    estacao = xlsx[0] 
                elif xls:
                    estacao = xls[0]

                try:
                    if ano == '2003':
                        df = pd.read_excel(caminho+arquivo+'/'+estacao,header=1)
                    elif estacao == 'CIC2019.xlsx':
                        df = pd.read_excel(caminho+arquivo+'/'+estacao,header=2)
                    else:
                        df = pd.read_excel(caminho+arquivo+'/'+estacao)
                except Exception as e:
                    print(f"Tentando ler como texto: {arquivo}")
                    df = pd.read_csv(caminho+arquivo+'/'+estacao, sep='\t', engine='python', encoding='latin1', header=2)
                
                if not (verifica_numero(df[df.columns[0]].iloc[0]) or verifica_data(df[df.columns[0]].iloc[0])) or arquivo == 'SIX2017':

                    df = adicionar_colunas_unidade(df)

                print(len(df))
                    
                dicionario[ano][arquivo[:-4]] = df 

            elif 'IAP' not in arquivo:

                try:
                        
                    df = ler_dados_mes_a_mes(caminho+arquivo+'/')
                    
                    if not (verifica_numero(df[df.columns[0]].iloc[0]) or verifica_data(df[df.columns[0]].iloc[0])):
    
                        df = adicionar_colunas_unidade(df)
                
                    dicionario[ano][arquivo[:-4]] = df 

                    print(len(df))

                except Exception as e:
                    print(f"A seguinte pasta não existe: {caminho}{arquivo}")
                    
    return(dicionario)

In [214]:
len(pd.DataFrame())

0

In [215]:
estacoes_por_ano = {
    '1998': {},
    '1999': {},
    '2000': {},
    '2001': {},
    '2002': {},
    '2003': {},
    '2004': {},
    '2005': {},
    '2006': {},
    '2007': {},
    '2008': {},
    '2009': {},
    '2010': {},
    '2011': {},
    '2012': {},
    '2013': {},
    '2014': {},
    '2015': {},
    '2016': {},
    '2017': {},
    '2018': {},
    '2019': {},
    '2020': {},
    '2021': {},
    '2022': {},
    '2023': {},
    '2024': {}
}

for ano in ['1998','1999','2000',
            '2001','2002','2003','2004','2005','2006','2007','2008','2009','2010',
            '2011','2012','2013','2014','2015','2016','2017','2018','2019','2020',
            '2021','2022','2023','2024']:

    if ano in ['1998','1999','2000','2001','2002']:
        estacoes_por_ano = ler_dados_parana_1998_2002(estacoes_por_ano,ano)
    elif ano in ['2003','2004','2005','2006','2007','2008','2009','2010','2011','2012','2013','2014','2015','2016','2017','2018','2019']:
        estacoes_por_ano = ler_dados_parana_2003_2019(estacoes_por_ano,ano)
    elif ano in ['2020','2021','2022','2023','2024']:
        estacoes_por_ano = ler_dados_parana_2024(estacoes_por_ano,ano)

STC1998
2969
CIC1998
12067
STC1999
17472
CIC1999
Não há nada em /home/nobre/Notebooks/RQAR_2025_book/data/DADOS_BRUTOS/PR/1999/CIC1999
CIC2000
Não há nada em /home/nobre/Notebooks/RQAR_2025_book/data/DADOS_BRUTOS/PR/2000/CIC2000
STC2000
Não há nada em /home/nobre/Notebooks/RQAR_2025_book/data/DADOS_BRUTOS/PR/2000/STC2000
ASS2000
Não há nada em /home/nobre/Notebooks/RQAR_2025_book/data/DADOS_BRUTOS/PR/2000/ASS2000
ASS2001
Não há nada em /home/nobre/Notebooks/RQAR_2025_book/data/DADOS_BRUTOS/PR/2001/ASS2001
STC2001
Não há nada em /home/nobre/Notebooks/RQAR_2025_book/data/DADOS_BRUTOS/PR/2001/STC2001
CIC2001
17520
CIC2002
8736
BOQ2002
Não há nada em /home/nobre/Notebooks/RQAR_2025_book/data/DADOS_BRUTOS/PR/2002/BOQ2002
ASS2002
8760

2003
CIC2003
['CIC1h-2003.xls']
8760
IAP2003
CSN2003

8771
UEG2003

6608
PAR2003

8771
RPR2003

3676
BOQ2003

8771

2004
UEG2004

8795
CIC2004

5142
RPR2004

8795
PAR2004

8795
BOQ2004

8795
CSN2004

8795
ASS2004

5142
IAP2004
STC2004

5887

2005
PAR2005

8771
STC2005

8771
CIC2005

8771
CSN2005

8771
RPR2005

8770
UEG2005

8770
ASS2005

8771
BOQ2005

8771
IAP2005

2006
PAR2006

8771
ASS2006

8771
CSN2006

8771
CIC2006

4349
BOQ2006

8771
STC2006

8771
UEG2006

8771
IAP2006
RPR2006

8771

2007
ASS2007

8771
BOQ2007

7305
IAP2007
PAR2007

8771
RPR2007

8771
STC2007

8771
CSN2007

8771
UEG2007

8771

2008
PAR2008

8795
UEG2008

8795
CSN2008

8795
ASS2008

8795
IAP2008
RPR2008

8795
STC2008

8795

2009
ASS2009

8771
IAP2009
BOQ2009

3676
PAR2009

8771
RPR2009

8771
UEG2009

8771
CSN2009

8770
STC2009

8771

2010
IAP2010
CIC2010

2979
PAR2010

8771
ASS2010

8771
BOQ2010

8771
UEG2010

8770
RPR2010

8771
CSN2010

8771
STC2010

8771

2011
ASS2011

8771
CIC2011

8829
BOQ2011

8771
STC2011

8770
UEG2011

8771
SIX2011

5142
RPR2011

8771
CSN2011

8771
PAR2011

8771
IAP2011

2012
SIX2012

8795
IAP2012
CSN2012

8795
RPR2012

8795
UEG2012

8795
ASS2012

8795
PAR2012

8795
CIC2012

8867
STC2012

8795
BOQ2012

8795

2013
RPR2013

8770
ASS2013

8771
IAP2013
UEG2013

8771
BOQ2013

8771
CIC2013

8918
PAR2013

8771
SIX2013

8771
CSN2013

8771
STC2013

8771

2014
STC2014

8778
CIC2014

8860
UEG2014

8771
SIX2014

8770
CSN2014

8771
RPR2014

8771
IAP2014
PAR2014

8771
ASS2014

8771
BOQ2014

8771

2015
UEG2015

8771
ASS2015

8771
CSN2015

8771
CIC2015

8771
IAP2015
RPR2015

8771
PAR2015

8771
STC2015

8770
SIX2015

8771
BOQ2015

8771

2016
MRGA2016

10511
ASS2016

8795
CSN2016

8795
PGA2016

5893
UEG2016

8794
CVEL

A seguinte pasta não existe: /home/nobre/Notebooks/RQAR_2025_book/data/DADOS_BRUTOS/PR/2016/CVEL
CIC2016

8798
LON2016

1487
IAP2016
CAS2016
/home/nobre/Notebooks/RQAR_2025_book/data/DADOS_BRUTOS/PR/2016/CAS2016/
Empty DataFrame
Columns: []
Index: []

/home/nobre/Notebooks/RQAR_2025_book/data/DADOS_BRUTOS/PR/2016/CAS2016/
Empty DataFrame
Columns: []
Index: []

/home/nobre/Notebooks/RQAR_2025_book/data/DADOS_BRUTOS/PR/2016/CAS2016/
Empty DataFrame
Columns: []
Index: []

/home/nobre/Notebooks/RQAR_2025_book/data/DADOS_BRUTOS/PR/2016/CAS2016/
Empty DataFrame
Columns: []
Index: []

/home/nobre/Notebooks/RQAR_2025_book/data/DADOS_BRUTOS/PR/2016/CAS2016/
Empty DataFrame
Columns: []
Index: []

/home/nobre/Notebooks/RQAR_2025_book/data/DADOS_BRUTOS/PR/2016/CAS2016/
Empty DataFrame
Columns: []
Index: []

/home/nobre/Notebooks/RQAR_2025_book/data/DADOS_BRUTOS/PR/2016/CAS2016/
Empty DataFrame
Columns: []
Index: []

/home/nobre/Notebooks/RQAR_2025_book/data/DADOS_BRUTOS/PR/2016/CAS2016/
Empty DataFrame
Columns: []
Index: []

/home/nobre/Notebooks/RQAR_2025_book/data/DADOS_BRUTOS/PR/2016/CAS2016/
Empty DataFrame
Columns: []
Index: []

/home/nobre/Notebooks/RQAR_2025_book/data/DADOS_BRUTOS/PR/2016/CAS2016/
Empty DataFrame
Columns: []
Index: []


1440
SIX2016

8794
STC2016

8795
BOQ2016

8795
PAR2016

8795
RPR2016

8795

2017
LON2017

17519
RPR2017
['RPR1H_2017.xls']
8784
FOZ2017
['2017.xls']
Tentando ler como texto: FOZ2017
4657
STC2017

A seguinte pasta não existe: /home/nobre/Notebooks/RQAR_2025_book/data/DADOS_BRUTOS/PR/2017/STC2017
MRGA2017

/tmp/ipykernel_273420/3488112494.py:178: UserWarning: Parsing dates in %d/%m/%Y %H:%M format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  pd.to_datetime(data)

17519
CIC2017

A seguinte pasta não existe: /home/nobre/Notebooks/RQAR_2025_book/data/DADOS_BRUTOS/PR/2017/CIC2017
BOQ2017
['BOQ1H_2017.xlsx']
8760
PGA2017

8129
PAR2017
['PAR1H_2017.xls']
8760
CSN2017
['CSN1H_2017.xls']
8760
SIX2017
['SIX1H_2017.xls']
5832
ASS2017

A seguinte pasta não existe: /home/nobre/Notebooks/RQAR_2025_book/data/DADOS_BRUTOS/PR/2017/ASS2017
UEG

A seguinte pasta não existe: /home/nobre/Notebooks/RQAR_2025_book/data/DADOS_BRUTOS/PR/2017/UEG

2018
PGA2018

8841
LON2018

17517
CIC2018
['CIC2018.xls']
Tentando ler como texto: CIC2018
8761
ASS2018
['.ipynb_checkpoints', 'ASS18.xls']
Tentando ler como texto: ASS2018
8761
CVEL2018
/home/nobre/Notebooks/RQAR_2025_book/data/DADOS_BRUTOS/PR/2018/CVEL2018/
Empty DataFrame
Columns: [Report, Date/Time, 1:Temp, 2:O3, 3:CO, 4:NO, 5:NO2, 6:NOx, 7:SO2, 8:CH4 , 9:NMHC, 10:THC, 11:PM10, 12:PTS, 13:AT , 14:RH , 15:BP, 16:SR , 17:WS, 18:WD, 19:RAIN]
Index: []

[0 rows x 21 columns]


14295
CSN2018
['CSN2018.xls']
Tentando ler como texto: CSN2018

/tmp/ipykernel_273420/3488112494.py:124: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, df_mes], ignore_index=True)
/tmp/ipykernel_273420/3488112494.py:158: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, df_mes], ignore_index=True)

8761
UEG2018
['UEG2018.xls']
Tentando ler como texto: UEG2018
898
FOZ2018

15177
MRGA2018

17519
SIX2018
['.ipynb_checkpoints', 'SIX2018.xls']
Tentando ler como texto: SIX2018
8737

2019
CSN2019
['CSN2019.xls']
Tentando ler como texto: CSN2019
8761
CVEL2019

6783
RPR2019
['RPR2019.xls']
Tentando ler como texto: RPR2019
8761
FOZ2019

/tmp/ipykernel_273420/3488112494.py:124: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, df_mes], ignore_index=True)
/tmp/ipykernel_273420/3488112494.py:158: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, df_mes], ignore_index=True)

/home/nobre/Notebooks/RQAR_2025_book/data/DADOS_BRUTOS/PR/2019/FOZ2019/
Empty DataFrame
Columns: [Report, Date/Time, 1:Temp, 2:O3, 3:CO, 4:NO, 5:NO2, 6:NOx, 7:SO2, 8:CH4 , 9:NMHC, 10:THC, 11:PM10, 12:PTS, 13:AT , 14:RH , 15:BP, 16:SR , 17:WS, 18:WD, 19:RAIN]
Index: []

[0 rows x 21 columns]


9057
LON2019

14457
PGA2019

13341
MRGA2019

17517
ASS2019
['.ipynb_checkpoints', 'ASS2019.xls']
Tentando ler como texto: ASS2019
8761
SIX2019
['SIX2019.xls']
Tentando ler como texto: SIX2019
8737
CIC2019
['CIC2019.xls', 'CIC2019.xlsx']
8761
Tentando ler como texto: RPR2020.xls
8784
RPR
8784
Tentando ler como texto: FIGUACU2020.xls
8784
FIGUACU
8784
Tentando ler como texto: CVEL2020.xls
8784
CVEL
8784
Tentando ler como texto: MRGA2020.xls
8784
MRGA
8784
Tentando ler como texto: SIX2020.xls
8784
SIX
8784
Tentando ler como texto: CSN2020.xls
8784
CSN
8784
Tentando ler como texto: LON2020.xls
8784
LON
8784
Tentando ler como texto: PGA2020.xls
8784
PGA
8784
Tentando ler como texto: CIC2020.xls
8784
CIC
8784
Tentando ler como texto: SIX2021.xls
8760
SIX
8760
Tentando ler como texto: MRGA2021.xls
8760
MRGA
8760
Tentando ler como texto: PGA2021.xls
8760
PGA
8760
Tentando ler como texto: CSN2021.xls
8760
CSN
8760
Tentando ler como texto: RPR2021.xls
8760
RPR
8760
Tentando ler como texto: CIC2021.xls
8760
CIC
8760
Tentando ler como texto: CVEL2021.xls
8760
CVEL
8760
Tentando ler como texto: PARP2022.xls
8760
PARP
8760
Tentando ler como texto: CSN2022.xls
8760
CSN
8760
Tentando ler como texto: SIX2022.xls
8760
SIX
8760
Tentando ler como texto: PGA2022.xls
8760
PGA
8760
Tentando ler como texto: RPR2022.xls
8760
RPR
8760
Tentando ler como texto: CVEL2022.xls
8760
CVEL
8760
Tentando ler como texto: CIC2022.xls
8760
CIC
8760
Tentando ler como texto: PARP2023.xls
8760
PARP
8760
Tentando ler como texto: CIC2023.xls
8760
CIC
8760
Tentando ler como texto: CVEL2023.xls
8760
CVEL
8760
Tentando ler como texto: SIX2023.xls
8760
SIX
8760
Tentando ler como texto: LON2023.xls
8760
LON
8760
Tentando ler como texto: CSN2023.xls
6914
CSN
6914
Tentando ler como texto: PGA2023.xls
8760
PGA
8760
Tentando ler como texto: RPR2023.xls
8760
RPR
8760
Tentando ler como texto: JDA2024.xls
384
JDA
384
Tentando ler como texto: FOSPAR2024.xls
8435
FOSPAR
8435
Tentando ler como texto: FNB.xls
2111
FNB.xls
2111
Tentando ler como texto: LDA2024.xls
2135
LDA
2135
Tentando ler como texto: LON2024.xls
8784
LON
8784
Tentando ler como texto: RPR2024.xls
8784
RPR
8784
Tentando ler como texto: MGA2024.xls
2135
MGA
2135
Tentando ler como texto: GPC2024.xls
6383
GPC
6383
Tentando ler como texto: FOZ2024.xls
8784
FOZ
8784
Tentando ler como texto: PARP2024.xls
8784
PARP
8784
Tentando ler como texto: PGA2024.xls
8784
PGA
8784
Tentando ler como texto: GRP2024.xls
2064
GRP
2064
Tentando ler como texto: MRGA2024.xls
8784
MRGA
8784
Tentando ler como texto: CIC2024.xls
8784
CIC
8784
Tentando ler como texto: SIX2024.xls
8784
SIX
8784
Tentando ler como texto: CVEL2024.xls
8784
CVEL
8784
Tentando ler como texto: CLB2024.xls
1896
CLB
1896

In [218]:
lista = []

def parse_datetime(x):
    for fmt in ('%Y-%m-%d %H:%M:%S', '%d/%m/%Y %H:%M', '%m/%d/%Y %I:%M:%S %p'):
        try:
            return pd.to_datetime(x, format=fmt)
        except:
            continue
    return pd.to_datetime(x, errors='coerce')
                
def criar_datetime(df,tipo):

    if tipo == 'D':

        df['A'] = pd.to_numeric(df['A'], errors='coerce')

        if df['A'].iloc[0] < 2000:

            df['A'] = df['A'] + 2000
                
        df['H'] = df['H'].astype(str).str.split(':').str[0]
        
        df[['A', 'M', 'D', 'H']] = df[['A', 'M', 'D', 'H']].apply(pd.to_numeric, errors='coerce')
        
        df['datetime'] = pd.to_datetime(
            dict(year=df['A'], month=df['M'], day=df['D'], hour=df['H'].clip(upper=23)),
            errors='coerce'
        )
        
        df.loc[df['H'] == 24, 'datetime'] = df.loc[df['H'] == 24, 'datetime'] + pd.Timedelta(hours=1)
    
    elif tipo == 'DATA':

        df['datetime'] = pd.to_datetime(df['DATA']) + pd.to_timedelta(df['HORA'] + ':00')

        df = df.drop(columns=[c for c in ['ANO', 'MES', 'DIA', 'HORA'] if c in df.columns])
    
    elif tipo == 'Data':

        try:
            df['Data'] = pd.to_datetime(df['Data']).dt.date
        except:
            print(1)

        print(df.loc[df['Data'].astype(str).str.contains('--', na=False)])

        df['datetime'] = pd.to_datetime(df['Data']) + pd.to_timedelta(df['Hora'] + ':00')

    elif tipo == 'Data/Hora':
        
        df['Data/Hora'] = df['Data/Hora'].apply(parse_datetime)
        
        df['Data/Hora'] = df['Data/Hora'].dt.strftime('%Y-%m-%d %H:%M:%S')

        df['datetime'] = pd.to_datetime(df['Data/Hora'])

    elif tipo == 'Date/Time':
        
        df['Date/Time'] = df['Date/Time'].apply(parse_datetime)
        
        df['Date/Time'] = df['Date/Time'].dt.strftime('%Y-%m-%d %H:%M:%S')

        df['datetime'] = pd.to_datetime(df['Date/Time'])
        
    df = df.set_index("datetime")

    df = df.sort_index()
    
    df.insert(0, 'DATETIME', df.index)
    df.insert(1, 'ANO', df.index.year)
    df.insert(2, 'MES', df.index.month)
    df.insert(3, 'DIA', df.index.day)
    df.insert(4, 'HORA', df.index.hour)

    return df

lista_colunas = []

for ano in estacoes_por_ano.keys():
    
    print(ano)

    for estacao in estacoes_por_ano[ano].keys():

        #print(estacao)
        
        lista.append(estacao)

        lista_colunas = lista_colunas + list(estacoes_por_ano[ano][estacao].columns)
        
        if any(item in ['D','DATA','Data','Date/Time','Data/Hora'] for item in estacoes_por_ano[ano][estacao].columns):

            if 'D' in estacoes_por_ano[ano][estacao].columns:
                print('D')
                estacoes_por_ano[ano][estacao] = criar_datetime(estacoes_por_ano[ano][estacao], 'D')
                #print(estacoes_por_ano[ano][estacao])
            elif 'DATA' in estacoes_por_ano[ano][estacao].columns:
                print('DATA')
                estacoes_por_ano[ano][estacao] = criar_datetime(estacoes_por_ano[ano][estacao], 'DATA')
                #print(estacoes_por_ano[ano][estacao])
            elif 'Data' in estacoes_por_ano[ano][estacao].columns:
                print('Data')
                estacoes_por_ano[ano][estacao] = criar_datetime(estacoes_por_ano[ano][estacao], 'Data')
                #print(estacoes_por_ano[ano][estacao])
            elif 'Date/Time' in estacoes_por_ano[ano][estacao].columns:
                print('Date/Time')
                estacoes_por_ano[ano][estacao] = criar_datetime(estacoes_por_ano[ano][estacao], 'Date/Time')
                #print(estacoes_por_ano[ano][estacao])
            elif 'Data/Hora' in estacoes_por_ano[ano][estacao].columns:
                print('Data/Hora')
                estacoes_por_ano[ano][estacao] = criar_datetime(estacoes_por_ano[ano][estacao], 'Data/Hora')
                #print(estacoes_por_ano[ano][estacao])
            else:
                print('ERRO')
    print('')

'''
lista1 = sorted(set(lista))

lista_pr = pd.read_csv(os.getcwd() + '/data/DADOS_ESTACOES/PR_estacoes.csv')

lista2 = sorted(lista_pr['ID_OEMA'])

iguais = sorted(set(lista1) & set(lista2))

so_lista1 = [x for x in lista1 if x not in iguais]
so_lista2 = [x for x in lista2 if x not in iguais]

col1 = iguais + so_lista1 + [np.nan] * len(so_lista2)
col2 = iguais + [np.nan] * len(so_lista1) + so_lista2

df = pd.DataFrame({'PR_dados': col1, 'PR_estacao': col2})

df'''

#print(lista_colunas)
print(len(list(set(lista_colunas))))

1998
Data
Empty DataFrame
Columns: [Data, Hora, SO2, NO, NO2, Nox, O3, UVB, Temperatura, Umidade, Rad. Glob.,  UVA, Press, V V, D V, SO2_UNIDADE, NO_UNIDADE, NO2_UNIDADE, Nox_UNIDADE, O3_UNIDADE, UVB_UNIDADE, Temperatura_UNIDADE, Umidade_UNIDADE, Rad. Glob._UNIDADE,  UVA_UNIDADE, Press_UNIDADE, V V_UNIDADE, D V_UNIDADE]
Index: []

[0 rows x 28 columns]
Data
Empty DataFrame
Columns: [Data, Hora, SO2, NO, NO2, Nox, O3, Temperatura, Umidade, Rad. Glob., Rad. UV, Press, V V, D V, SO2_UNIDADE, NO_UNIDADE, NO2_UNIDADE, Nox_UNIDADE, O3_UNIDADE, Temperatura_UNIDADE, Umidade_UNIDADE, Rad. Glob._UNIDADE, Rad. UV_UNIDADE, Press_UNIDADE, V V_UNIDADE, D V_UNIDADE]
Index: []

[0 rows x 26 columns]

1999
Data
Empty DataFrame
Columns: [Data, Hora, SO2, NO, NO2, Nox, O3, UVB, Temperatura, Umidade, Rad. Glob.,  UVA, Press, V V, D V, SO2_UNIDADE, NO_UNIDADE, NO2_UNIDADE, Nox_UNIDADE, O3_UNIDADE, UVB_UNIDADE, Temperatura_UNIDADE, Umidade_UNIDADE, Rad. Glob._UNIDADE,  UVA_UNIDADE, Press_UNIDADE, V V_UNIDADE, D V_UNIDADE]
Index: []

[0 rows x 28 columns]

2000

2001
Data
Empty DataFrame
Columns: [Data, Hora, SO2, NO, NO2, Nox, O3, Temperatura, Umidade, Rad. Glob., Rad. UV, Press, V V, D V, SO2_UNIDADE, NO_UNIDADE, NO2_UNIDADE, Nox_UNIDADE, O3_UNIDADE, Temperatura_UNIDADE, Umidade_UNIDADE, Rad. Glob._UNIDADE, Rad. UV_UNIDADE, Press_UNIDADE, V V_UNIDADE, D V_UNIDADE]
Index: []

[0 rows x 26 columns]

2002
DATA
D

2003
D
D
D
D
D
D

2004
D
D
D
D
D
D
D
D

2005
D
D
D
D
D
D
D
D

2006
D
D
D
D
D
D
D
D

2007
D
D
D
D
D
D
D

2008
D
D
D
D
D
D

2009
D
D
D
D
D
D
D

2010
D
D
D
D
D
D
D
D

2011
D
D
D
D
D
D
D
D
D

2012
D
D
D
D
D
D
D
D
D

2013
D
D
D
D
D
D
D
D
D

2014
D
D
D
D
D
D
D
D
D

2015
D
D
D
D
D
D
D
D
D

2016
Date/Time
D
D
Date/Time
D
D
Date/Time
Data/Hora
D
D
D
D
D

2017
Date/Time
D
Data/Hora
Date/Time
D
Date/Time
D
D
D

2018
Date/Time
Date/Time
Data/Hora
Data/Hora
Date/Time
Data/Hora
Data/Hora
Date/Time
Date/Time
Data/Hora

2019
Data/Hora
Date/Time
Data/Hora
Date/Time
Date/Time
Date/Time
Date/Time
Data/Hora
Data/Hora
Data/Hora

2020
Data/Hora
Data/Hora
Data/Hora
Data/Hora
Data/Hora
Data/Hora
Data/Hora
Data/Hora
Data/Hora

2021
Data/Hora
Data/Hora
Data/Hora
Data/Hora
Data/Hora
Data/Hora
Data/Hora

2022
Data/Hora
Data/Hora
Data/Hora
Data/Hora
Data/Hora
Data/Hora
Data/Hora

2023
Data/Hora
Data/Hora
Data/Hora
Data/Hora
Data/Hora
Data/Hora
Data/Hora
Data/Hora

2024
Data/Hora
Data/Hora
Data/Hora
Data/Hora
Data/Hora
Data/Hora
Data/Hora
Data/Hora
Data/Hora
Data/Hora
Data/Hora
Data/Hora
Data/Hora
Data/Hora
Data/Hora
Data/Hora
Data/Hora

267

In [329]:
pol_estacao_ano['2015']['CIC']['NO']

,DATETIME,ANO,MES,DIA,HORA,VALOR,UNIDADE,QAQC_INTERNO
datetime,,,,,,,,
2015-01-01 01:00:00,2015-01-01 01:00:00,2015.0,1.0,1.0,1.0,"1,29",ppb,NaN
2015-01-01 02:00:00,2015-01-01 02:00:00,2015.0,1.0,1.0,2.0,"0,95",ppb,NaN
2015-01-01 03:00:00,2015-01-01 03:00:00,2015.0,1.0,1.0,3.0,"0,63",ppb,NaN
2015-01-01 04:00:00,2015-01-01 04:00:00,2015.0,1.0,1.0,4.0,"0,78",ppb,NaN
2015-01-01 05:00:00,2015-01-01 05:00:00,2015.0,1.0,1.0,5.0,"1,34",ppb,NaN
...,...,...,...,...,...,...,...,...
NaT,NaT,NaN,NaN,NaN,NaN,ppb,ppb,NaN
NaT,NaT,NaN,NaN,NaN,NaN,ppb,ppb,NaN
NaT,NaT,NaN,NaN,NaN,NaN,ppb,ppb,NaN
NaT,NaT,NaN,NaN,NaN,NaN,ppb,ppb,NaN
NaT,NaT,NaN,NaN,NaN,NaN,ppb,ppb,NaN

    ANO  MES  DIA  HORA UNIDADE  VALOR
0  2023    5   10    12     ppb   41.0
1  2023    5   10    13     ppb   44.0

             ANO   MES   DIA  HORA UNIDADE   VALOR            DATETIME
DATETIME
NaT       1998.0  11.0   1.0   0.0     ppb   1.555 1998-11-01 00:00:00
NaT       1998.0  11.0   1.0   1.0     ppb   1.515 1998-11-01 01:00:00
NaT       1998.0  11.0   1.0   2.0     ppb   1.630 1998-11-01 02:00:00
NaT       1998.0  11.0   1.0   3.0     ppb   1.660 1998-11-01 03:00:00
NaT       1998.0  11.0   1.0   4.0     ppb   1.525 1998-11-01 04:00:00
...          ...   ...   ...   ...     ...     ...                 ...
NaT       2016.0  12.0  31.0  20.0     ppb -99.000 2016-12-31 20:00:00
NaT       2016.0  12.0  31.0  21.0     ppb -99.000 2016-12-31 21:00:00
NaT       2016.0  12.0  31.0  22.0     ppb -99.000 2016-12-31 22:00:00
NaT       2016.0  12.0  31.0  23.0     ppb -99.000 2016-12-31 23:00:00
NaT       2017.0   1.0   1.0   0.0     ppb -99.000 2017-01-01 00:00:00

[121236 rows x 7 columns]

In [219]:
df_col_pols = pd.read_csv('/home/nobre/Notebooks/RQAR_2025_book/data/DADOS_BRUTOS/PR/colunas_pol_PR.csv',encoding='UTF-8')

pol_estacao_ano = {}

print(df_col_pols)

for ano in estacoes_por_ano.keys():

    pol_estacao_ano[ano] = {}

    for estacao in estacoes_por_ano[ano]:
    
        pol_estacao_ano[ano][estacao] = {}
        
        for pol in df_col_pols['col_pr']:

            if pol in estacoes_por_ano[ano][estacao].columns and 'UNIDADE' not in pol:

                poluente_mma = df_col_pols.loc[df_col_pols['col_pr'] == pol, 'col_mma'].iloc[0]

                qaqc_interno = np.nan
                
                if '(' in pol:
                    unidade = pol.split('(')[-1][:-1]
                    print(pol)            
                    #print(unidade)

                    df = estacoes_por_ano[ano][estacao][['DATETIME','ANO','MES','DIA','HORA',pol]]

                    df['UNIDADE'] = unidade
                    df['QAQC_INTERNO'] = qaqc_interno

                    df.rename(columns={pol: 'VALOR'}, inplace=True)
                    
                elif (pol+'_UNIDADE') in estacoes_por_ano[ano][estacao].columns:
                    #print('')
                    #print(pol)
                    #print('')

                    df = estacoes_por_ano[ano][estacao][['DATETIME','ANO','MES','DIA','HORA',pol,pol+'_UNIDADE']]

                    df['QAQC_INTERNO'] = qaqc_interno

                    df.rename(columns={pol: 'VALOR',pol+'_UNIDADE':'UNIDADE'}, inplace=True)
                    
                else:

                    df = estacoes_por_ano[ano][estacao][['DATETIME','ANO','MES','DIA','HORA',pol]]
                    
                    df['UNIDADE'] = np.nan
                    df['QAQC_INTERNO'] = qaqc_interno

                    df.rename(columns={pol: 'VALOR'}, inplace=True)

                pol_estacao_ano[ano][estacao][poluente_mma] = df

            col_pr          col_mma
0           9:NMHC             HCNM
1     2:O3_UNIDADE       O3_UNIDADE
2      TOL_UNIDADE  TOLUENO_UNIDADE
3               PI             MP10
4         SO2(ppb)              SO2
..             ...              ...
71     Nox_UNIDADE      NOX_UNIDADE
72             BEN          BENZENO
73            2:O3               O3
74        NOX(ppb)              NOX
75  12:PTS_UNIDADE              PTS

[76 rows x 2 columns]

/tmp/ipykernel_273420/317706924.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR',pol+'_UNIDADE':'UNIDADE'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR',pol+'_UNIDADE':'UNIDADE'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR',pol+'_UNIDADE':'UNIDADE'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR',pol+'_UNIDADE':'UNIDADE'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR',pol+'_UNIDADE':'UNIDADE'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR',pol+'_UNIDADE':'UNIDADE'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR',pol+'_UNIDADE':'UNIDADE'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR',pol+'_UNIDADE':'UNIDADE'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR',pol+'_UNIDADE':'UNIDADE'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR',pol+'_UNIDADE':'UNIDADE'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR',pol+'_UNIDADE':'UNIDADE'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR',pol+'_UNIDADE':'UNIDADE'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR',pol+'_UNIDADE':'UNIDADE'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR',pol+'_UNIDADE':'UNIDADE'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR',pol+'_UNIDADE':'UNIDADE'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR',pol+'_UNIDADE':'UNIDADE'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR',pol+'_UNIDADE':'UNIDADE'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR',pol+'_UNIDADE':'UNIDADE'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR',pol+'_UNIDADE':'UNIDADE'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR',pol+'_UNIDADE':'UNIDADE'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR',pol+'_UNIDADE':'UNIDADE'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:50: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['UNIDADE'] = np.nan
/tmp/ipykernel_273420/317706924.py:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR',pol+'_UNIDADE':'UNIDADE'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:50: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['UNIDADE'] = np.nan
/tmp/ipykernel_273420/317706924.py:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR',pol+'_UNIDADE':'UNIDADE'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:50: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['UNIDADE'] = np.nan
/tmp/ipykernel_273420/317706924.py:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

SO2(ppb)
MP10(µg/m³)
H2S(ppb)
PTS(µg/m³)
TRS(ppb)
CS(ppb)

/tmp/ipykernel_273420/317706924.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR',pol+'_UNIDADE':'UNIDADE'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR',pol+'_UNIDADE':'UNIDADE'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR',pol+'_UNIDADE':'UNIDADE'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR',pol+'_UNIDADE':'UNIDADE'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR',pol+'_UNIDADE':'UNIDADE'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR',pol+'_UNIDADE':'UNIDADE'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR',pol+'_UNIDADE':'UNIDADE'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR',pol+'_UNIDADE':'UNIDADE'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR',pol+'_UNIDADE':'UNIDADE'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR',pol+'_UNIDADE':'UNIDADE'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR',pol+'_UNIDADE':'UNIDADE'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR',pol+'_UNIDADE':'UNIDADE'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR',pol+'_UNIDADE':'UNIDADE'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR',pol+'_UNIDADE':'UNIDADE'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR',pol+'_UNIDADE':'UNIDADE'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR',pol+'_UNIDADE':'UNIDADE'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR',pol+'_UNIDADE':'UNIDADE'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR',pol+'_UNIDADE':'UNIDADE'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR',pol+'_UNIDADE':'UNIDADE'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR',pol+'_UNIDADE':'UNIDADE'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR',pol+'_UNIDADE':'UNIDADE'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR',pol+'_UNIDADE':'UNIDADE'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:50: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['UNIDADE'] = np.nan
/tmp/ipykernel_273420/317706924.py:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:50: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['UNIDADE'] = np.nan
/tmp/ipykernel_273420/317706924.py:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:50: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['UNIDADE'] = np.nan
/tmp/ipykernel_273420/317706924.py:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:50: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['UNIDADE'] = np.nan
/tmp/ipykernel_273420/317706924.py:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:50: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

SO2(ppb)
CH4(ppm)
O3(ppb)
NO(ppb)
HCNM(ppm)
MP10(µg/m³)
NO2(ppb)
PTS(µg/m³)
CO(ppm)
HCT(ppm)
NOX(ppb)

/tmp/ipykernel_273420/317706924.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR',pol+'_UNIDADE':'UNIDADE'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR',pol+'_UNIDADE':'UNIDADE'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR',pol+'_UNIDADE':'UNIDADE'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR',pol+'_UNIDADE':'UNIDADE'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:50: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['UNIDADE'] = np.nan
/tmp/ipykernel_273420/317706924.py:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR',pol+'_UNIDADE':'UNIDADE'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR',pol+'_UNIDADE':'UNIDADE'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR',pol+'_UNIDADE':'UNIDADE'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR',pol+'_UNIDADE':'UNIDADE'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR',pol+'_UNIDADE':'UNIDADE'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR',pol+'_UNIDADE':'UNIDADE'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR',pol+'_UNIDADE':'UNIDADE'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR',pol+'_UNIDADE':'UNIDADE'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR',pol+'_UNIDADE':'UNIDADE'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR',pol+'_UNIDADE':'UNIDADE'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR',pol+'_UNIDADE':'UNIDADE'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR',pol+'_UNIDADE':'UNIDADE'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR',pol+'_UNIDADE':'UNIDADE'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR',pol+'_UNIDADE':'UNIDADE'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR',pol+'_UNIDADE':'UNIDADE'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR',pol+'_UNIDADE':'UNIDADE'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR',pol+'_UNIDADE':'UNIDADE'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR',pol+'_UNIDADE':'UNIDADE'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR',pol+'_UNIDADE':'UNIDADE'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR',pol+'_UNIDADE':'UNIDADE'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR',pol+'_UNIDADE':'UNIDADE'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR',pol+'_UNIDADE':'UNIDADE'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame


NO(ppb)
NO2(ppb)
CO(ppm)
NOX(ppb)
SO2(ppb)
O3(ppb)
NO(ppb)
NO2(ppb)
SO2(ppb)
O3(ppb)
NO(ppb)
NO2(ppb)
NOX(ppb)
SO2(ppb)
O3(ppb)
CO(ppm)
SO2(ppb)
CH4(ppm)
O3(ppb)
NO(ppb)
NO2(ppb)
CO(ppm)
HCT(ppm)
SO2(ppb)
O3(ppb)
NO(ppb)
NO2(ppb)
NOX(ppb)
SO2(ppb)
O3(ppb)
NO(ppb)
NO2(ppb)
CO(ppm)
NOX(ppb)

/tmp/ipykernel_273420/317706924.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['UNIDADE'] = unidade
/tmp/ipykernel_273420/317706924.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['UNIDADE'] = unidade
/tmp/ipykernel_273420/317706924.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['UNIDADE'] = unidade
/tmp/ipykernel_273420/317706924.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['UNIDADE'] = unidade
/tmp/ipykernel_273420/317706924.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR',pol+'_UNIDADE':'UNIDADE'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR',pol+'_UNIDADE':'UNIDADE'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR',pol+'_UNIDADE':'UNIDADE'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR',pol+'_UNIDADE':'UNIDADE'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR',pol+'_UNIDADE':'UNIDADE'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR',pol+'_UNIDADE':'UNIDADE'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR',pol+'_UNIDADE':'UNIDADE'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR',pol+'_UNIDADE':'UNIDADE'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR',pol+'_UNIDADE':'UNIDADE'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR',pol+'_UNIDADE':'UNIDADE'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR',pol+'_UNIDADE':'UNIDADE'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['UNIDADE'] = unidade
/tmp/ipykernel_273420/317706924.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['UNIDADE'] = unidade
/tmp/ipykernel_273420/317706924.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['UNIDADE'] = unidade
/tmp/ipykernel_273420/317706924.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['UNIDADE'] = unidade
/tmp/ipykernel_273420/317706924.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['UNIDADE'] = unidade
/tmp/ipykernel_273420/317706924.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['UNIDADE'] = unidade
/tmp/ipykernel_273420/317706924.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['UNIDADE'] = unidade
/tmp/ipykernel_273420/317706924.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead


SO2(ppb)
SO2(ppb)
CH4(ppm)
O3(ppb)
NO(ppb)
MP10(µg/m³)
NO2(ppb)
PTS(µg/m³)
CO(ppm)
HCT(ppm)
NO(ppb)
NO2(ppb)
CO(ppm)
NOX(ppb)
SO2(ppb)
O3(ppb)
NO(ppb)
MP10(µg/m³)
NO2(ppb)
PTS(µg/m³)
CO(ppm)
NOX(ppb)
SO2(ppb)
CH4(ppm)
O3(ppb)
NO(ppb)
HCNM(ppm)
MP10(µg/m³)
NO2(ppb)
PTS(µg/m³)
CO(ppm)
HCT(ppm)
NOX(ppb)
SO2(ppb)
CH4(ppm)
O3(ppb)
NO(ppb)
HCNM(ppm)
MP10(µg/m³)
NO2(ppb)
PTS(µg/m³)
CO(ppm)
HCT(ppm)
NOX(ppb)
SO2(ppb)
CH4(ppm)
O3(ppb)
NO(ppb)
HCNM(ppm)
MP10(µg/m³)
NO2(ppb)
PTS(µg/m³)
CO(ppm)
HCT(ppm)
NOX(ppb)
SO2(ppb)
CH4(ppm)
O3(ppb)
NO(ppb)
MP10(µg/m³)
NO2(ppb)
PTS(µg/m³)
CO(ppm)
HCT(ppm)
SO2(ppb)
O3(ppb)
NO(ppb)
NO2(ppb)
PTS(µg/m³)
NOX(ppb)
SO2(ppb)
CH4(ppm)
O3(ppb)

/tmp/ipykernel_273420/317706924.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['UNIDADE'] = unidade
/tmp/ipykernel_273420/317706924.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['UNIDADE'] = unidade
/tmp/ipykernel_273420/317706924.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['UNIDADE'] = unidade
/tmp/ipykernel_273420/317706924.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['UNIDADE'] = unidade
/tmp/ipykernel_273420/317706924.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['UNIDADE'] = unidade
/tmp/ipykernel_273420/317706924.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['UNIDADE'] = unidade
/tmp/ipykernel_273420/317706924.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['UNIDADE'] = unidade
/tmp/ipykernel_273420/317706924.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['UNIDADE'] = unidade
/tmp/ipykernel_273420/317706924.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['UNIDADE'] = unidade
/tmp/ipykernel_273420/317706924.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['UNIDADE'] = unidade
/tmp/ipykernel_273420/317706924.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['UNIDADE'] = unidade
/tmp/ipykernel_273420/317706924.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['UNIDADE'] = unidade
/tmp/ipykernel_273420/317706924.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['UNIDADE'] = unidade
/tmp/ipykernel_273420/317706924.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['UNIDADE'] = unidade
/tmp/ipykernel_273420/317706924.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['UNIDADE'] = unidade
/tmp/ipykernel_273420/317706924.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['UNIDADE'] = unidade
/tmp/ipykernel_273420/317706924.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['UNIDADE'] = unidade
/tmp/ipykernel_273420/317706924.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['UNIDADE'] = unidade
/tmp/ipykernel_273420/317706924.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['UNIDADE'] = unidade
/tmp/ipykernel_273420/317706924.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['UNIDADE'] = unidade

NO(ppb)
HCNM(ppm)
MP10(µg/m³)
NO2(ppb)
PTS(µg/m³)
CO(ppm)
HCT(ppm)
NOX(ppb)
SO2(ppb)
CH4(ppm)
O3(ppb)
NO(ppb)
HCNM(ppm)
MP10(µg/m³)
NO2(ppb)
PTS(µg/m³)
CO(ppm)
HCT(ppm)
NOX(ppb)
NO(ppb)
NO2(ppb)
CO(ppm)
NOX(ppb)
SO2(ppb)
CH4(ppm)
O3(ppb)
NO(ppb)
MP10(µg/m³)
NO2(ppb)
PTS(µg/m³)
CO(ppm)
HCT(ppm)
SO2(ppb)
CH4(ppm)
O3(ppb)
NO(ppb)
HCNM(ppm)
MP10(µg/m³)
NO2(ppb)
PTS(µg/m³)
CO(ppm)
HCT(ppm)
NOX(ppb)
SO2(ppb)
CH4(ppm)
O3(ppb)
NO(ppb)
HCNM(ppm)
MP10(µg/m³)
NO2(ppb)
PTS(µg/m³)
CO(ppm)
HCT(ppm)
NOX(ppb)
SO2(ppb)
O3(ppb)
NO(ppb)
NO2(ppb)
PTS(µg/m³)
NOX(ppb)
SO2(ppb)
O3(ppb)
NO(ppb)
MP10(µg/m³)
NO2(ppb)
PM_2_5(µg/m³)
PTS(µg/m³)
CO(ppm)
NOX(ppb)
CH4(ppm)
NO(ppb)
HCNM(ppm)
NO2(ppb)
CO(ppm)
HCT(ppm)
NOX(ppb)
SO2(ppb)
CH4(ppm)
O3(ppb)
NO(ppb)
HCNM(ppm)
MP10(µg/m³)
NO2(ppb)
PTS(µg/m³)
CO(ppm)
HCT(ppm)
NOX(ppb)
SO2(ppb)
O3(ppb)
NO(ppb)

/tmp/ipykernel_273420/317706924.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['UNIDADE'] = unidade
/tmp/ipykernel_273420/317706924.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['UNIDADE'] = unidade
/tmp/ipykernel_273420/317706924.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['UNIDADE'] = unidade
/tmp/ipykernel_273420/317706924.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['UNIDADE'] = unidade
/tmp/ipykernel_273420/317706924.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['UNIDADE'] = unidade
/tmp/ipykernel_273420/317706924.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['UNIDADE'] = unidade
/tmp/ipykernel_273420/317706924.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['UNIDADE'] = unidade
/tmp/ipykernel_273420/317706924.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['UNIDADE'] = unidade
/tmp/ipykernel_273420/317706924.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['UNIDADE'] = unidade
/tmp/ipykernel_273420/317706924.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['UNIDADE'] = unidade
/tmp/ipykernel_273420/317706924.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['UNIDADE'] = unidade
/tmp/ipykernel_273420/317706924.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['UNIDADE'] = unidade
/tmp/ipykernel_273420/317706924.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['UNIDADE'] = unidade
/tmp/ipykernel_273420/317706924.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['UNIDADE'] = unidade
/tmp/ipykernel_273420/317706924.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['UNIDADE'] = unidade
/tmp/ipykernel_273420/317706924.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['UNIDADE'] = unidade
/tmp/ipykernel_273420/317706924.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['UNIDADE'] = unidade
/tmp/ipykernel_273420/317706924.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['UNIDADE'] = unidade
/tmp/ipykernel_273420/317706924.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['UNIDADE'] = unidade
/tmp/ipykernel_273420/317706924.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['UNIDADE'] = unidade

MP10(µg/m³)
NO2(ppb)
PM_2_5(µg/m³)
CO(ppm)
SO2(ppb)
O3(ppb)
NO(ppb)
NO2(ppb)
PTS(µg/m³)
NOX(ppb)
SO2(ppb)
CH4(ppm)
O3(ppb)
NO(ppb)
MP10(µg/m³)
NO2(ppb)
PTS(µg/m³)
CO(ppm)
HCT(ppm)
CH4(ppm)
O3(ppb)
NO(ppb)
HCNM(ppm)
MP10(µg/m³)
NO2(ppb)
PTS(µg/m³)
CO(ppm)
HCT(ppm)
NOX(ppb)
SO2(ppb)
O3(ppb)
NO(ppb)
MP10(µg/m³)
NO2(ppb)
PM_2_5(µg/m³)
CO(ppm)
NOX(ppb)
SO2(ppb)
CH4(ppm)
O3(ppb)
NO(ppb)
HCNM(ppm)
MP10(µg/m³)
NO2(ppb)
CO(ppm)
HCT(ppm)
NOX(ppb)
CH4(ppm)
NO(ppb)
HCNM(ppm)
MP10(µg/m³)
NO2(ppb)
PM_2_5(µg/m³)
CO(ppm)
HCT(ppm)
NOX(ppb)
SO2(ppb)
O3(ppb)
NO(ppb)
MP10(µg/m³)
NO2(ppb)
PM_2_5(µg/m³)
CO(ppm)
NO(ppb)
MP10(µg/m³)
NO2(ppb)
PM_2_5(µg/m³)
CO(ppm)
HCT(ppm)
NOX(ppb)
SO2(ppb)
CH4(ppm)
NO(ppb)
HCNM(ppm)
NO2(ppb)
CO(ppm)
HCT(ppm)
NOX(ppb)
SO2(ppb)
CH4(ppm)
O3(ppb)
NO(ppb)

/tmp/ipykernel_273420/317706924.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['UNIDADE'] = unidade
/tmp/ipykernel_273420/317706924.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['UNIDADE'] = unidade
/tmp/ipykernel_273420/317706924.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['UNIDADE'] = unidade
/tmp/ipykernel_273420/317706924.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['UNIDADE'] = unidade
/tmp/ipykernel_273420/317706924.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['UNIDADE'] = unidade
/tmp/ipykernel_273420/317706924.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['UNIDADE'] = unidade
/tmp/ipykernel_273420/317706924.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['UNIDADE'] = unidade
/tmp/ipykernel_273420/317706924.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['UNIDADE'] = unidade
/tmp/ipykernel_273420/317706924.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['UNIDADE'] = unidade
/tmp/ipykernel_273420/317706924.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['UNIDADE'] = unidade
/tmp/ipykernel_273420/317706924.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['UNIDADE'] = unidade
/tmp/ipykernel_273420/317706924.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['UNIDADE'] = unidade
/tmp/ipykernel_273420/317706924.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['UNIDADE'] = unidade
/tmp/ipykernel_273420/317706924.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['UNIDADE'] = unidade
/tmp/ipykernel_273420/317706924.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['UNIDADE'] = unidade
/tmp/ipykernel_273420/317706924.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['UNIDADE'] = unidade
/tmp/ipykernel_273420/317706924.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['UNIDADE'] = unidade
/tmp/ipykernel_273420/317706924.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['UNIDADE'] = unidade
/tmp/ipykernel_273420/317706924.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['UNIDADE'] = unidade
/tmp/ipykernel_273420/317706924.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno

MP10(µg/m³)
NO2(ppb)
PTS(µg/m³)
CO(ppm)
HCT(ppm)
SO2(ppb)
CH4(ppm)
O3(ppb)
NO(ppb)
HCNM(ppm)
MP10(µg/m³)
NO2(ppb)
PTS(µg/m³)
CO(ppm)
HCT(ppm)
NOX(ppb)
SO2(ppb)
O3(ppb)
NO(ppb)
NO2(ppb)
PTS(µg/m³)
NOX(ppb)
SO2(ppb)
CH4(ppm)
O3(ppb)
NO(ppb)
HCNM(ppm)
MP10(µg/m³)
NO2(ppb)
PTS(µg/m³)
CO(ppm)
HCT(ppm)
NOX(ppb)
SO2(ppb)
O3(ppb)
NO(ppb)
MP10(µg/m³)
NO2(ppb)
PM_2_5(µg/m³)
CO(ppm)
NOX(ppb)
SO2(ppb)
O3(ppb)
NO(ppb)
MP10(µg/m³)
NO2(ppb)
PM_2_5(µg/m³)
CO(ppm)
SO2(ppb)
MP10(µg/m³)
PM_2_5(µg/m³)
CO(ppm)
TRS(ppb)
PM_2_5(µg/m³)
PM_2_5(µg/m³)
PM_2_5(µg/m³)
PTS(µg/m³)
SO2(ppb)
O3(ppb)
NO(ppb)
MP10(µg/m³)
NO2(ppb)
PM_2_5(µg/m³)
CO(ppm)
NOX(ppb)
PM_2_5(µg/m³)
HCNM(ppm)
MP10(µg/m³)
PM_2_5(µg/m³)
PTS(µg/m³)
HCT(ppm)
CS(ppb)
PM_2_5(µg/m³)
SO2(ppb)
O3(ppb)
NO(ppb)
MP10(µg/m³)
NO2(ppb)
PM_2_5(µg/m³)
CO(ppm)
SO2(ppb)
CH4(ppm)
O3(ppb)
NO(ppb)
HCNM(ppm)
MP10(µg/m³)
NO2(ppb)
PM_2_5(µg/m³)
PTS(µg/m³)
CO(ppm)
HCT(ppm)
NOX(ppb)
PM_2_5(µg/m³)
SO2(ppb)
CH4(ppm)
NO(ppb)
HCNM(ppm)
NO2(ppb)
PTS(µg/m³)
CO(ppm)
HCT(ppm)
NOX(ppb)
NO(ppb)
MP10(µg/m³)
NO2(ppb)
PM_2_5(µg/m³)
CO(ppm)
HCT(ppm)
NOX(ppb)
SO2(ppb)
CH4(ppm)
O3(ppb)
NO(ppb)
MP10(µg/m³)
NO2(ppb)
PTS(µg/m³)
CO(ppm)
HCT(ppm)
SO2(ppb)
CH4(ppm)
HCNM(ppm)
MP10(µg/m³)
PM_2_5(µg/m³)
CO(ppm)
HCT(ppm)
PM_2_5(µg/m³)

/tmp/ipykernel_273420/317706924.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['UNIDADE'] = unidade
/tmp/ipykernel_273420/317706924.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['UNIDADE'] = unidade
/tmp/ipykernel_273420/317706924.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['UNIDADE'] = unidade
/tmp/ipykernel_273420/317706924.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['UNIDADE'] = unidade
/tmp/ipykernel_273420/317706924.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['UNIDADE'] = unidade
/tmp/ipykernel_273420/317706924.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['UNIDADE'] = unidade
/tmp/ipykernel_273420/317706924.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['UNIDADE'] = unidade
/tmp/ipykernel_273420/317706924.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['UNIDADE'] = unidade
/tmp/ipykernel_273420/317706924.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['UNIDADE'] = unidade
/tmp/ipykernel_273420/317706924.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['UNIDADE'] = unidade
/tmp/ipykernel_273420/317706924.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['UNIDADE'] = unidade
/tmp/ipykernel_273420/317706924.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['UNIDADE'] = unidade
/tmp/ipykernel_273420/317706924.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['UNIDADE'] = unidade
/tmp/ipykernel_273420/317706924.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['UNIDADE'] = unidade
/tmp/ipykernel_273420/317706924.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['UNIDADE'] = unidade
/tmp/ipykernel_273420/317706924.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['UNIDADE'] = unidade
/tmp/ipykernel_273420/317706924.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['UNIDADE'] = unidade
/tmp/ipykernel_273420/317706924.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['UNIDADE'] = unidade
/tmp/ipykernel_273420/317706924.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['UNIDADE'] = unidade
/tmp/ipykernel_273420/317706924.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QAQC_INTERNO'] = qaqc_interno
/tmp/ipykernel_273420/317706924.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={pol: 'VALOR'}, inplace=True)
/tmp/ipykernel_273420/317706924.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['UNIDADE'] = unidade

In [231]:
import pandas as pd

pol_estacao = {}

for ano, estacoes in pol_estacao_ano.items():
    for estacao, poluentes in estacoes.items():
        for poluente, df in poluentes.items():
            pol_estacao.setdefault(estacao, {}).setdefault(poluente, [])
            pol_estacao[estacao][poluente].append(df)

estacoes_finais = {}

for estacao, poluentes in pol_estacao.items():
    for poluente, lista_dfs in poluentes.items():
        df_concat = pd.concat(lista_dfs, ignore_index=True)

        df_concat = df_concat[df_concat['DATETIME'].notna()]

        df_concat['VALOR'] = (
            df_concat['VALOR']
            .astype(str)           
            .str.replace(',', '.', regex=False)  
        )

        df_concat['VALOR'] = pd.to_numeric(df_concat['VALOR'], errors='coerce')

        df_media = (
            df_concat.groupby(['ANO', 'MES', 'DIA', 'HORA', 'UNIDADE'], as_index=False)['VALOR']
              .mean()
        )
        
        df_media["DATETIME"] = pd.to_datetime(
            df_media.apply(
                lambda r: f"{int(r.ANO):04d}-{int(r.MES):02d}-{int(r.DIA):02d} {int(r.HORA):02d}:00:00",
                axis=1
            )
        )

        df_media = df_media.drop(columns=['ANO', 'MES', 'DIA', 'HORA'])

        df_media = df_media.set_index("DATETIME")
    
        df_media = df_media.sort_index()

        df_media = df_media[~df_media.index.duplicated(keep='first')]
        
        lista_horas = pd.date_range(
            start=df_media.index.min(), 
            end=df_media.index.max(), 
            freq='H').strftime('%Y-%m-%d %H:%M:%S').tolist()
        
        if len(lista_horas) != len(df):
            df_media = df_media.reindex(pd.DatetimeIndex(lista_horas))

        df_media.insert(1, 'ANO', df_media.index.year)
        df_media.insert(2, 'MES', df_media.index.month)
        df_media.insert(3, 'DIA', df_media.index.day)
        df_media.insert(4, 'HORA', df_media.index.hour)
        
        df_media['DATETIME'] = df_media.index

        df_media['QAQC_INTERNO'] = None
        
        df_media = df_media[['DATETIME', 'ANO', 'MES', 'DIA', 'HORA', 'VALOR', 'UNIDADE', 'QAQC_INTERNO']]

        estacoes_finais[estacao+'_'+poluente] = df_media

/tmp/ipykernel_273420/3105762284.py:47: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3105762284.py:47: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3105762284.py:47: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3105762284.py:47: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3105762284.py:47: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3105762284.py:47: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3105762284.py:47: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3105762284.py:47: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3105762284.py:47: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3105762284.py:47: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3105762284.py:47: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3105762284.py:47: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3105762284.py:47: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3105762284.py:47: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3105762284.py:47: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3105762284.py:47: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3105762284.py:47: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3105762284.py:47: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3105762284.py:47: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3105762284.py:47: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3105762284.py:47: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3105762284.py:47: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3105762284.py:47: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3105762284.py:47: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3105762284.py:47: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3105762284.py:47: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3105762284.py:47: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3105762284.py:47: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3105762284.py:47: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3105762284.py:47: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3105762284.py:47: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3105762284.py:47: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3105762284.py:47: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3105762284.py:47: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3105762284.py:47: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3105762284.py:47: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3105762284.py:47: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3105762284.py:47: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3105762284.py:47: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3105762284.py:47: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3105762284.py:47: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3105762284.py:47: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3105762284.py:47: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3105762284.py:47: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3105762284.py:47: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3105762284.py:47: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3105762284.py:47: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3105762284.py:47: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3105762284.py:47: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3105762284.py:47: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3105762284.py:47: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3105762284.py:47: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3105762284.py:47: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3105762284.py:47: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3105762284.py:47: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3105762284.py:47: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3105762284.py:47: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3105762284.py:47: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3105762284.py:47: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3105762284.py:47: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3105762284.py:47: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3105762284.py:47: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3105762284.py:47: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3105762284.py:47: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3105762284.py:47: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3105762284.py:47: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3105762284.py:47: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3105762284.py:47: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3105762284.py:47: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3105762284.py:47: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3105762284.py:47: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3105762284.py:47: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3105762284.py:47: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3105762284.py:47: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3105762284.py:47: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3105762284.py:47: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3105762284.py:47: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3105762284.py:47: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3105762284.py:47: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3105762284.py:47: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3105762284.py:47: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3105762284.py:47: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3105762284.py:47: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3105762284.py:47: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3105762284.py:47: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3105762284.py:47: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3105762284.py:47: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3105762284.py:47: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3105762284.py:47: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3105762284.py:47: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3105762284.py:47: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3105762284.py:47: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3105762284.py:47: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3105762284.py:47: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3105762284.py:47: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3105762284.py:47: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3105762284.py:47: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3105762284.py:47: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3105762284.py:47: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3105762284.py:47: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3105762284.py:47: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3105762284.py:47: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3105762284.py:47: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3105762284.py:47: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3105762284.py:47: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3105762284.py:47: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3105762284.py:47: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3105762284.py:47: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3105762284.py:47: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3105762284.py:47: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3105762284.py:47: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3105762284.py:47: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3105762284.py:47: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3105762284.py:47: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3105762284.py:47: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3105762284.py:47: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3105762284.py:47: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3105762284.py:47: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(

In [232]:
estacoes_finais.keys()

dict_keys(['STC_NO', 'STC_O3', 'STC_NO2', 'STC_NOX', 'STC_SO2', 'STC_MP10', 'STC_CH4', 'STC_TOLUENO', 'STC_PTS', 'STC_HCT', 'STC_ETILBENZENO', 'STC_NH3', 'STC_CO', 'STC_HCNM', 'STC_BENZENO', 'CIC_NO', 'CIC_O3', 'CIC_NO2', 'CIC_NOX', 'CIC_SO2', 'CIC_PTS', 'CIC_CH4', 'CIC_HCT', 'CIC_HCNM', 'CIC_MP10', 'CIC_TOLUENO', 'CIC_ETILBENZENO', 'CIC_NH3', 'CIC_CO', 'CIC_BENZENO', 'CIC_MP25', 'ASS_NO', 'ASS_PTS', 'ASS_O3', 'ASS_CH4', 'ASS_HCT', 'ASS_NO2', 'ASS_NOX', 'ASS_SO2', 'ASS_HCNM', 'ASS_MP10', 'ASS_TOLUENO', 'ASS_ETILBENZENO', 'ASS_NH3', 'ASS_CO', 'ASS_BENZENO', 'CSN_MP10', 'CSN_NO', 'CSN_O3', 'CSN_CH4', 'CSN_TOLUENO', 'CSN_PTS', 'CSN_HCT', 'CSN_NO2', 'CSN_ETILBENZENO', 'CSN_SO2', 'CSN_NH3', 'CSN_CO', 'CSN_HCNM', 'CSN_BENZENO', 'CSN_NOX', 'UEG_MP10', 'UEG_NO', 'UEG_O3', 'UEG_CH4', 'UEG_TOLUENO', 'UEG_PTS', 'UEG_HCT', 'UEG_NO2', 'UEG_ETILBENZENO', 'UEG_SO2', 'UEG_NH3', 'UEG_CO', 'UEG_HCNM', 'UEG_BENZENO', 'PAR_MP10', 'PAR_NO', 'PAR_O3', 'PAR_CH4', 'PAR_TOLUENO', 'PAR_PTS', 'PAR_HCT', 'PAR_NO2', 'PAR_ETILBENZENO', 'PAR_SO2', 'PAR_NH3', 'PAR_CO', 'PAR_HCNM', 'PAR_BENZENO', 'RPR_MP10', 'RPR_NO', 'RPR_O3', 'RPR_CH4', 'RPR_TOLUENO', 'RPR_PTS', 'RPR_HCT', 'RPR_NO2', 'RPR_ETILBENZENO', 'RPR_SO2', 'RPR_NH3', 'RPR_CO', 'RPR_HCNM', 'RPR_BENZENO', 'RPR_NOX', 'RPR_MP25', 'BOQ_MP10', 'BOQ_NO', 'BOQ_O3', 'BOQ_CH4', 'BOQ_TOLUENO', 'BOQ_PTS', 'BOQ_HCT', 'BOQ_NO2', 'BOQ_ETILBENZENO', 'BOQ_SO2', 'BOQ_NH3', 'BOQ_CO', 'BOQ_HCNM', 'BOQ_BENZENO', 'SIX_MP10', 'SIX_NO', 'SIX_O3', 'SIX_CH4', 'SIX_TOLUENO', 'SIX_PTS', 'SIX_HCT', 'SIX_NO2', 'SIX_ETILBENZENO', 'SIX_SO2', 'SIX_NH3', 'SIX_CO', 'SIX_HCNM', 'SIX_BENZENO', 'MRGA_HCNM', 'MRGA_MP10', 'MRGA_CH4', 'MRGA_NOX', 'MRGA_CO', 'MRGA_NO2', 'MRGA_HCT', 'MRGA_SO2', 'MRGA_PTS', 'MRGA_NO', 'MRGA_O3', 'PGA_HCNM', 'PGA_MP10', 'PGA_CH4', 'PGA_NOX', 'PGA_CO', 'PGA_NO2', 'PGA_HCT', 'PGA_SO2', 'PGA_PTS', 'PGA_NO', 'PGA_O3', 'PGA_MP25', 'LON_HCNM', 'LON_MP10', 'LON_CH4', 'LON_NOX', 'LON_CO', 'LON_NO2', 'LON_HCT', 'LON_SO2', 'LON_PTS', 'LON_NO', 'LON_O3', 'LON_MP25', 'CAS_SO2', 'CAS_MP10', 'CAS_H2S', 'CAS_PTS', 'CAS_ERT', 'CAS_CS', 'FOZ_SO2', 'FOZ_CH4', 'FOZ_O3', 'FOZ_NO', 'FOZ_HCNM', 'FOZ_MP10', 'FOZ_NO2', 'FOZ_PTS', 'FOZ_CO', 'FOZ_HCT', 'FOZ_NOX', 'FOZ_MP25', 'CVEL_HCNM', 'CVEL_MP10', 'CVEL_CH4', 'CVEL_NOX', 'CVEL_CO', 'CVEL_NO2', 'CVEL_HCT', 'CVEL_SO2', 'CVEL_PTS', 'CVEL_NO', 'CVEL_O3', 'CVEL_MP25', 'FIGUACU_SO2', 'FIGUACU_CH4', 'FIGUACU_O3', 'FIGUACU_NO', 'FIGUACU_HCNM', 'FIGUACU_MP10', 'FIGUACU_NO2', 'FIGUACU_PTS', 'FIGUACU_CO', 'FIGUACU_HCT', 'FIGUACU_NOX', 'PARP_SO2', 'PARP_O3', 'PARP_NO', 'PARP_MP10', 'PARP_NO2', 'PARP_MP25', 'PARP_CO', 'JDA_SO2', 'JDA_O3', 'JDA_NO', 'JDA_MP10', 'JDA_NO2', 'JDA_MP25', 'JDA_CO', 'FOSPAR_SO2', 'FOSPAR_MP10', 'FOSPAR_MP25', 'FOSPAR_CO', 'FOSPAR_ERT', 'FNB.xls_MP25', 'LDA_MP25', 'MGA_MP25', 'GPC_HCNM', 'GPC_MP10', 'GPC_MP25', 'GPC_PTS', 'GPC_HCT', 'GPC_CS', 'GRP_MP25', 'CLB_MP25'])

In [233]:

def create_QAQCMMA_VALOR(df,pol):

    df = df.rename(columns={'VALOR':'VALOR_ORIGINAL'})

    flags_invalidos = ['!', 'IF', 'IO', 'IC', 'I%', 'IL', 'IE', 'IS', 'IU', 'IM', 'IP', 'ID', 'IT', 'IR', 
                       'Fora da Faixa de Medição', 'Disabilitada Temporariamente', 'Inválido', 
                       'Insuficientes', 'Inexistente']

    df['QAQC_INTERNO'] = ~df['QAQC_INTERNO'].isin(flags_invalidos)
    
    DEFAULT_RANGE_LIMITS = {
        "O3": (0, 500),
        "CO": (0, 50),
        "NO2": (0, 1000),
        "NOX": (0, 2000),
        "SO2": (0, 1000),
        "MP25": (0, 1000),
        "MP10": (0, 2000),
    }

    df['QAQC_MMA'] = df['QAQC_INTERNO']

    if pol in list(DEFAULT_RANGE_LIMITS.keys()):
        lim_min = DEFAULT_RANGE_LIMITS[pol][0]
        lim_max = DEFAULT_RANGE_LIMITS[pol][1]
    else:
        lim_min = 0
        lim_max = np.inf

    df['VALOR'] = df['VALOR_ORIGINAL']

    df['VALOR'] = pd.to_numeric(df['VALOR'], errors='coerce')
    
    df.loc[df['QAQC_MMA'] & (df['VALOR'].isna() | (df['VALOR'] <= lim_min) | (df['VALOR'] >= lim_max)), 'QAQC_MMA'] = False
    
    df.loc[~df['QAQC_MMA'], 'VALOR'] = np.nan
    
    df = df[['DATETIME', 'ANO', 'MES', 'DIA', 'HORA', 'VALOR', 'VALOR_ORIGINAL', 'UNIDADE', 'QAQC_INTERNO', 'QAQC_MMA']]

    return df


primeiros_valores = {}

for chave, df in estacoes_finais.items():  
    
    if ~df['VALOR'].isna().all() and (df['VALOR'] > 0).any(): 
        
        linha_valida = df[df["VALOR"].notna() & (df["VALOR"] > 0)].iloc[0]
        primeiros_valores[chave] = linha_valida["DATETIME"]

codigo_estacao_PR = {}

for chave in primeiros_valores.keys():
    
    station = chave.split('_')[0]
    data = primeiros_valores[chave]
    
    if station in codigo_estacao_PR:
        if data <= codigo_estacao_PR[station]:
            codigo_estacao_PR[station] = data
    else:
        codigo_estacao_PR[station] = data

sorted_items = sorted(
    codigo_estacao_PR.items(),
    key=lambda x: (x[1], x[0])
)

codigo_estacao_PR = {}
for i, (nome, ts) in enumerate(sorted_items, start=1):
    codigo = f"PR{i:04d}"
    codigo_estacao_PR[nome] = codigo

for chave, df in estacoes_finais.items():
    
    estacao = codigo_estacao_PR[chave.split('_')[0]]

    if chave.split('_')[-1] != 'CS':
        
        cod_pol = tabela_pols.loc[tabela_pols['NOME_PASTA'] == chave.split('_')[-1], 'COD_POLUENTE'].values[0]
        
        nome_pasta = tabela_pols.loc[tabela_pols['COD_POLUENTE'] == int(cod_pol), 'NOME_PASTA'].values[0]
    
        df = create_QAQCMMA_VALOR(df,nome_pasta)

        df.to_csv('/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/'+nome_pasta+'/'+estacao+'RA'+str(int(cod_pol)).zfill(3)+'.csv',index=False)

df_ids = pd.DataFrame({
    'ID_OEMA': codigo_estacao_PR.keys(),
    'ID_MMA':list(codigo_estacao_PR.values())})

print(df_ids)

    ID_OEMA  ID_MMA
0       CIC  PR0001
1       STC  PR0002
2       ASS  PR0003
3       BOQ  PR0004
4       CSN  PR0005
5       PAR  PR0006
6       UEG  PR0007
7       RPR  PR0008
8       SIX  PR0009
9       CAS  PR0010
10      PGA  PR0011
11      LON  PR0012
12     MRGA  PR0013
13      FOZ  PR0014
14     CVEL  PR0015
15  FIGUACU  PR0016
16     PARP  PR0017
17   FOSPAR  PR0018
18      GPC  PR0019
19      MGA  PR0020
20  FNB.xls  PR0021
21      GRP  PR0022
22      LDA  PR0023
23      CLB  PR0024
24      JDA  PR0025

In [234]:
df_ids

    ID_OEMA  ID_MMA
0       CIC  PR0001
1       STC  PR0002
2       ASS  PR0003
3       BOQ  PR0004
4       CSN  PR0005
5       PAR  PR0006
6       UEG  PR0007
7       RPR  PR0008
8       SIX  PR0009
9       CAS  PR0010
10      PGA  PR0011
11      LON  PR0012
12     MRGA  PR0013
13      FOZ  PR0014
14     CVEL  PR0015
15  FIGUACU  PR0016
16     PARP  PR0017
17   FOSPAR  PR0018
18      GPC  PR0019
19      MGA  PR0020
20  FNB.xls  PR0021
21      GRP  PR0022
22      LDA  PR0023
23      CLB  PR0024
24      JDA  PR0025

In [413]:
df_ids

   ID_OEMA  ID_MMA
0      CIC  PR0001
1      STC  PR0002
2      ASS  PR0003
3      BOQ  PR0004
4      CSN  PR0005
5      PAR  PR0006
6      UEG  PR0007
7      RPR  PR0008
8      SIX  PR0009
9      CAS  PR0010
10     PGA  PR0011
11     LON  PR0012
12    MRGA  PR0013
13     FOZ  PR0014
14    CVEL  PR0015

In [225]:
monitoramento_QAr_BR.loc[monitoramento_QAr_BR['ID_OEMA'] == nome, 'ID_MMA']

Series([], Name: ID_MMA, dtype: object)

In [30]:
estacoes_dicionario.keys()

for chave in estacoes_dicionario.keys():

    print(chave)
    print(len(estacoes_dicionario[chave]))
    print(estacoes_dicionario[chave].columns[0])
    print(estacoes_dicionario[chave].iloc[0, 0])
    print(estacoes_dicionario[chave].iloc[-1, 0])
    print("")

    estacoes_por_ano

,D,M,A,H,SO2,NO,NO2,O3,CO,PTS,...,THC,CH4,NMHC,TEMP,UMID,PRESS,VV,DV,RADG,CHUVA
0,NaN,NaN,NaN,NaN,ppb,ppb,ppb,ppb,ppm,µg/m³,...,ppm,ppm,ppm,°C,%,mBar,m/s,graus,W/m2,mm
1,1.0,1.0,17.0,1.0,0,NaN,NaN,7.8,0.46,NaN,...,1.39,1.33,NaN,23.2,99.9,923.3,1.2,232.4,7.7,NaN
2,1.0,1.0,17.0,2.0,0.2,NaN,NaN,15,0.38,NaN,...,1.38,1.26,NaN,22,99.9,922.2,1.2,189.2,6,NaN
3,1.0,1.0,17.0,3.0,0.6,NaN,NaN,10.7,0.37,NaN,...,1.35,1.26,NaN,21.9,99.9,921.5,0.9,274.3,5.3,NaN
4,1.0,1.0,17.0,4.0,0.4,NaN,NaN,11.1,0.41,NaN,...,1.35,1.26,NaN,21.7,99.9,921.1,1.2,275,4,NaN

# Update_MQAr_with_IEMA_MonitorAr

In [427]:
caminho = os.getcwd() + '/data/DADOS_BRUTOS/BRUTO_IEMA/'

estados_iema = os.listdir(caminho)

df_estacao_codigo = pd.DataFrame({
    'Estacao':[],
    'Codigo':[]
})

for estado in estados_iema:

    if '.csv' not in estado and '.ipynb_checkpoints' not in estado:

        lista_anos = os.listdir(caminho+estado)

        print(estado)
    
        print(lista_anos)
    
        df_estado = pd.DataFrame({
            'Data':[], 
            'Hora':[], 
            'Estacao':[], 
            'Codigo':[], 
            'Poluente':[], 
            'Valor':[], 
            'Unidade':[],
            'Tipo':[]})
    
        for ano in lista_anos:

            if '.csv' in ano:

                df = pd.read_csv(caminho+estado+'/'+ano, encoding='ISO-8859-1')
        
                df.columns.values[0] = 'Data'

                if 'Escola CecÃlia Meireles' in df['Estacao']:

                    print(ano)
        
                df_estado = pd.concat([df_estado, df], ignore_index=True)
    
        df_estacao_codigo = pd.concat([df_estacao_codigo,df_estado[['Estacao','Codigo']]], ignore_index=True)

df_estacao_codigo = df_estacao_codigo.drop_duplicates(subset=['Estacao', 'Codigo']).reset_index(drop=True)

DF
['DF2017.csv', 'DF2016.csv', 'DF2020.csv', 'DF2015.csv', 'DF2018.csv', 'DF2022.csv', 'DF2021.csv', 'DF2019.csv']
GO
['GO2015.csv', 'GO2017.csv', 'GO2016.csv']
PR
['PR2016.csv', 'PR2015.csv', 'PR2020.csv', 'PR2018.csv', 'PR2017.csv', 'PR2019.csv']
MG
['MG2016.csv', 'MG2022.csv', 'MG2021.csv', 'MG2018.csv', 'MG2017.csv', 'MG2019.csv', 'MG2015.csv', 'MG2020.csv']
RJ
['RJ202001.csv', 'RJ202201.csv', 'RJ201602.csv', 'RJ201902.csv', 'RJ201804.csv', 'RJ201502.csv', 'RJ201503.csv', 'RJ202101.csv', 'RJ201701.csv', 'RJ202102.csv', 'RJ201802.csv', 'RJ202002.csv', 'RJ201803.csv', 'RJ202202.csv', 'RJ201801.csv', 'RJ201702.csv', 'RJ201501.csv', 'RJ202103.csv', 'RJ201601.csv', 'RJ201901.csv']
SP
['SP201501.csv', 'SP201701.csv', 'SP201502.csv', 'SP202202.csv', 'SP202101.csv', 'SP201802.csv', 'SP201601.csv', 'SP201901.csv', 'SP202001.csv', 'SP201602.csv', 'SP202102.csv', 'SP202002.csv', 'SP201801.csv', 'SP202201.csv', 'SP201902.csv', 'SP201702.csv']
PE
['PE2020.csv', 'PE2021.csv', 'PE2017.csv', 'PE2022.csv', 'PE2018.csv', 'PE2019.csv']
BA
['BA2015.csv', 'BA2017.csv', 'BA2016.csv']
CE
['.ipynb_checkpoints', '2017CE.csv', '2020CE.csv', '2019CE.csv', '2016CE.csv', '2018CE.csv']
ES
['2019ES1.csv', '2020ES1.csv', '2016ES1.csv', '2021ES1.csv', '2017ES1.csv', '2015ES1.csv', '2022ES1.csv', '2018ES1.csv']
RS
['RS2021.csv', 'RS2015.csv', 'RS2017.csv', 'RS2020.csv', 'RS2022.csv', 'RS2016.csv', 'RS2019.csv', 'RS2018.csv']

In [428]:
df_estacao_codigo.to_csv(os.getcwd() + '/data/DADOS_BRUTOS/BRUTO_IEMA/IEMA_codigo_estacao.csv', encoding = 'UTF-8', index = False)

In [439]:
df_estacoes = pd.read_csv(os.getcwd() + '/data/DADOS_BRUTOS/BRUTO_IEMA/IEMA_codigo_estacao.csv', encoding = 'UTF-8')

import pandas as pd
import glob
import os
from unidecode import unidecode

# Caminho da pasta com os arquivos CSV
pasta = os.getcwd() + '/data/DADOS_ESTACOES'

# DataFrame principal
df_principal = df_estacoes.copy()

# Garantir que são strings
df_principal["ID_OEMA"] = df_principal["ID_OEMA"].astype(str)
df_principal["ID_MMA"] = df_principal["ID_MMA"].astype(str)

# Função para remover acentos e padronizar texto
def normalizar(texto):
    if pd.isna(texto):
        return None
    return unidecode(str(texto)).strip().upper()

# Normalizar coluna no DataFrame principal
df_principal["ID_OEMA_norm"] = df_principal["ID_OEMA"].apply(normalizar)

# Criar dicionário de mapeamento OEMA → MMA
mapa_oema_mma = {}

for arquivo in glob.glob(os.path.join(pasta, "*.csv")):
    df = pd.read_csv(arquivo, dtype=str)
    
    if "ID_OEMA" in df.columns and "ID_MMA" in df.columns:
        # Normalizar também nos arquivos
        df["ID_OEMA_norm"] = df["ID_OEMA"].apply(normalizar)
        df["ID_MMA"] = df["ID_MMA"].astype(str)

        pares_validos = df.dropna(subset=["ID_OEMA_norm", "ID_MMA"])
        for _, linha in pares_validos.iterrows():
            mapa_oema_mma[linha["ID_OEMA_norm"]] = linha["ID_MMA"]

# Mapear no DataFrame principal (usando os IDs normalizados)
df_principal["ID_MMA_preenchido"] = df_principal["ID_OEMA_norm"].map(mapa_oema_mma)

# Preencher apenas onde estava vazio
df_principal["ID_MMA"] = df_principal["ID_MMA"].replace("nan", pd.NA)
df_principal["ID_MMA"] = df_principal["ID_MMA"].fillna(df_principal["ID_MMA_preenchido"])

# Remover coluna auxiliar
df_principal = df_principal.drop(columns=["ID_MMA_preenchido", "ID_OEMA_norm"])

df_principal.to_csv(os.getcwd() + '/data/DADOS_BRUTOS/BRUTO_IEMA/IEMA_codigo_estacao_teste.csv', encoding = 'UTF-8', index = False)

In [440]:
df_estacoes = pd.read_csv(os.getcwd() + '/data/DADOS_BRUTOS/BRUTO_IEMA/IEMA_codigo_estacao_teste.csv', encoding = 'UTF-8')

df_estacoes

                                   ID_OEMA ID_IEMA  ID_MMA
0               Rodoviária do Plano Piloto    DF03     NaN
1                                 Fercal I    DF01     NaN
2    CIPLAN (antiga estação Queima Lençol)    DF02     NaN
3                      Setor Comercial Sul    DF05     NaN
4             Jardim Zoológico de Brasília    DF04     NaN
..                                     ...     ...     ...
416                       Triunfo - DEPREC    RS04  RS0009
417             Charqueadas - Arranca Toco    RS06  RS0013
418        Rio Grande Porto - FURG - Movel    RS18  RS0018
419                         Enseada do Suá    ES03  ES0003
420                         Vitória Centro    ES06  ES0008

[421 rows x 3 columns]

In [457]:
caminho = os.getcwd() + '/data/DADOS_BRUTOS/BRUTO_IEMA/'

df_est = pd.DataFrame({'Data':[],
                   'Hora'    :[],	
                   'Estacao' :[],
                   'Codigo'  :[],
                   'Poluente':[],
                   'Valor'   :[],	
                   'Unidade' :[],
                   'Tipo'    :[]})

arquivos = os.listdir(caminho)

for arquivo in arquivos:
    
    if '.csv' not in arquivo and 'checkpoints' not in arquivo:

        print(arquivo)

        anos = os.listdir(caminho+arquivo)

        for ano in anos:

            if '.csv' in ano:

                df = pd.read_csv(caminho+arquivo+'/'+ano, encoding='ISO-8859-1')

                df = df.rename(columns=lambda x: x.replace('ï»¿', ''))

                df = df.replace('MP2.5', 'MP25', regex=False)

                df_est = pd.concat([df, df_est], ignore_index=True)

DF
GO
PR
MG
RJ
SP
PE
BA
CE
ES
RS

In [458]:
df_est = df_est.merge(df_estacoes[['ID_OEMA', 'ID_MMA']], left_on='Estacao', right_on='ID_OEMA', how='left')

In [515]:
list(set(df_est['Unidade']))

['ug/m3', 'ppb', 'µg/m3', 'Âµg/mÂ³', 'ppm', 'µg/m³']

In [475]:
tabela_pols = pd.read_csv('/home/nobre/Notebooks/RQAR_2025_book/data/dicionarios/CODIGO_POLUENTES.csv')

In [204]:
lista_pols = list(set(df_est['Poluente']))


def create_QAQCMMA_VALOR(df,pol):

    df = df.rename(columns={'VALOR':'VALOR_ORIGINAL'})

    flags_invalidos = ['!', 'IF', 'IO', 'IC', 'I%', 'IL', 'IE', 'IS', 'IU', 'IM', 'IP', 'ID', 'IT', 'IR',
                       'IM', 'VU', 'ID', 'IF', 'VE', 'IC', 'IN', 'VR', 'IV', 'IO',
                       'Fora da Faixa de Medição', 'Disabilitada Temporariamente', 'Inválido', 
                       'Insuficientes', 'Inexistente']

    df['QAQC_INTERNO'] = ~df['QAQC_INTERNO'].isin(flags_invalidos)
    
    DEFAULT_RANGE_LIMITS = {
        "O3": (0, 500),
        "CO": (0, 50),
        "NO2": (0, 1000),
        "NOX": (0, 2000),
        "SO2": (0, 1000),
        "MP25": (0, 1000),
        "MP10": (0, 2000),
    }

    df['QAQC_MMA'] = df['QAQC_INTERNO']

    if pol in list(DEFAULT_RANGE_LIMITS.keys()):
        lim_min = DEFAULT_RANGE_LIMITS[pol][0]
        lim_max = DEFAULT_RANGE_LIMITS[pol][1]
    else:
        lim_min = 0
        lim_max = np.inf

    df['VALOR'] = df['VALOR_ORIGINAL']

    df['VALOR'] = pd.to_numeric(df['VALOR'], errors='coerce')
    
    df.loc[df['QAQC_MMA'] & (df['VALOR'].isna() | (df['VALOR'] <= lim_min) | (df['VALOR'] >= lim_max)), 'QAQC_MMA'] = False
    
    df.loc[~df['QAQC_MMA'], 'VALOR'] = np.nan
    
    df = df[['DATETIME', 'ANO', 'MES', 'DIA', 'HORA', 'VALOR', 'VALOR_ORIGINAL', 'UNIDADE', 'QAQC_INTERNO', 'QAQC_MMA']]

    return df

print(lista_pols)

def ajustar_hora24(row):
    if row['Hora'].startswith('24'):
        # passa para o dia seguinte
        nova_data = pd.to_datetime(row['Data']) + pd.Timedelta(days=1)
        return nova_data.strftime('%Y-%m-%d') + ' 00:00:00'
    else:
        return row['Data'] + ' ' + row['Hora']

def ug_to_ppm(df):

    df.loc[df["UNIDADE"] == "ug/m3", "VALOR_ORIGINAL"] *= 868.26/10**6
    df.loc[df["UNIDADE"] == "Âµg/mÂ", "VALOR_ORIGINAL"] *= 868.26/10**6
    df.loc[df["UNIDADE"] == "µg/m³", "VALOR_ORIGINAL"] *= 868.26/10**6
    df.loc[df["UNIDADE"] == "µg/m3", "VALOR_ORIGINAL"] *= 868.26/10**6
    df.loc[df["UNIDADE"] == "ppb", "VALOR_ORIGINAL"] *= 1/1000

    df['UNIDADE'] = "ppm"

    return df

for pol in lista_pols:

    print(pol)

    df_pol = df_est[df_est["Poluente"] == pol]

    lista_estacoes = list(set(df_pol['ID_MMA']))

    print(lista_estacoes)

    for estacao in lista_estacoes:

        if type(estacao) == str:

            cod_poluente = int(tabela_pols.loc[tabela_pols['POLUENTE'] == pol, 'COD_POLUENTE'].values[0])
           
            cod_poluente = f"{cod_poluente:03d}"

            print(cod_poluente)

            df_pol_est = df_pol[df_pol["ID_MMA"] == estacao]

            padrao = os.path.join(os.getcwd() + '/data/MQAr/'+pol+'/', f"{estacao}*.csv")
            arquivos = glob.glob(padrao)

            for arquivo in arquivos:

                print(arquivo)
                
                df_mma = pd.read_csv(arquivo, encoding = 'UTF-8')

                df_iema = df_pol_est[['Data','Hora','Valor','Unidade']]
                
                mask_24 = df_iema['Hora'].str.startswith('24')

                df_iema.loc[mask_24, 'Data'] = pd.to_datetime(df_iema.loc[mask_24, 'Data']) + pd.Timedelta(days=1)
                df_iema.loc[mask_24, 'Hora'] = '00:00:00'
                
                df_iema['Data'] = df_iema['Data'].astype(str)
                
                df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
                
                df_iema.drop(columns=['Data','Hora'], inplace=True)

                df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)

                df_mma['DATETIME'] = pd.to_datetime(df_mma['DATETIME'], errors='coerce')
                df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')
                
                df_mma = df_mma.dropna(subset=['DATETIME'])
                df_iema = df_iema.dropna(subset=['DATETIME'])

                if pol == 'CO':
                    df_iema = ug_to_ppm(df_iema)
                
                df_iema = (
                    df_iema.sort_values('VALOR_ORIGINAL', ascending=False)
                           .drop_duplicates(subset='DATETIME', keep='first')
                )
                
                df_final = df_mma.merge(df_iema, on='DATETIME', how='left', suffixes=('', '_df2'))
                
                df_final['VALOR_ORIGINAL'] = df_final['VALOR_ORIGINAL_df2'].combine_first(df_final['VALOR_ORIGINAL'])
                df_final['UNIDADE'] = df_final['UNIDADE_df2'].combine_first(df_final['UNIDADE'])

                df_final['VALOR'] = df_final['VALOR_ORIGINAL']

                df_final.drop(columns=['VALOR_ORIGINAL'], inplace=True)

                df_final = create_QAQCMMA_VALOR(df_final,pol)
                
                print('iema')
                print(df_iema.head())
                print('mma')
                print(df_mma.head())
                print('final')
                print(df_final.head())

                df_final.to_csv(arquivo, index=False)

['FMC', 'CO', 'NO', 'PM10', 'MP10', 'O3', 'NO2', 'SO2', 'PTS', 'MP25']
FMC
['SP0099', 'SP0083', nan, 'SP0091']
006
006
006
CO
['MG0003', 'RJ0043', 'RJ0022', 'RJ0044', 'PR0009 ', 'MG0001', 'RJ0039', 'BA0011', 'RJ0225', 'SP0120', 'MG0006', 'SP0085', 'MG0008', 'RJ0070', 'RJ0226', 'MG0010', 'MG0017', 'RJ0018', 'RJ0023', 'RJ0038', 'MG0002', 'PR0014 ', 'PR0007 ', 'PR0006 ', 'RJ0079', 'RJ0029', 'PR0004 ', 'RJ0057', 'RJ0048', 'SP0064', 'MG0009', 'MG0057', 'SP0086', 'MG0053', 'RJ0027', 'RJ0036', 'RJ0078', 'SP0280', 'RJ0033', 'RJ0081', 'RJ0037', 'PR0001 ', 'SP0103', 'RJ0030', 'MG0012', 'PR0012 ', 'RJ0026', 'BA0008', 'SP0099', 'SP0263', 'MG0013', 'PR0011 ', 'MG0005', 'MG0004', 'RJ0031', 'BA0007', 'RJ0021', 'PR0015 ', 'RJ0019', 'SP0091', 'SP0073', 'BA0005', 'SP0288', 'RJ0058', 'RJ0071', 'RJ0045', 'CE0001', nan, 'MG0039', 'RJ0069', 'BA0003', 'PR0008 ', 'RJ0215', 'BA0010', 'RJ0055', 'SP0083']
007
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/CO/MG0003RA007.csv

/tmp/ipykernel_273420/1352582357.py:97: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  df_mma = pd.read_csv(arquivo, encoding = 'UTF-8')
/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
37205410           13.52     ppm 2021-01-06 11:30:00
37205568           11.31     ppm 2021-01-06 12:30:00
36610940            8.47     ppm 2018-07-06 09:30:00
32042527            7.78     ppm 2020-04-16 08:30:00
37919342            7.60     ppm 2021-07-14 18:30:00
mma
             DATETIME     ANO  MES  DIA  HORA  VALOR VALOR_ORIGINAL UNIDADE  \
0 2009-01-01 01:00:00  2009.0  1.0  1.0   1.0    0.3            0.3     ppm
1 2009-01-01 02:00:00  2009.0  1.0  1.0   2.0    0.2            0.2     ppm
2 2009-01-01 03:00:00  2009.0  1.0  1.0   3.0    0.2            0.2     ppm
3 2009-01-01 04:00:00  2009.0  1.0  1.0   4.0    0.2            0.2     ppm
4 2009-01-01 05:00:00  2009.0  1.0  1.0   5.0    0.2            0.2     ppm

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME     ANO  MES  DIA  HORA  VALOR VALOR_ORIGINAL UNIDADE  \
0 2009-01-01 01:00:00  2009.0  1.0  1.0   1.0    0.3            0.3     ppm
1 2009-01-01 02:00:00  2009.0  1.0  1.0   2.0    0.2            0.2     ppm
2 2009-01-01 03:00:00  2009.0  1.0  1.0   3.0    0.2            0.2     ppm
3 2009-01-01 04:00:00  2009.0  1.0  1.0   4.0    0.2            0.2     ppm
4 2009-01-01 05:00:00  2009.0  1.0  1.0   5.0    0.2            0.2     ppm

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
007
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/CO/RJ0043RA007.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
28736083     1721.144247     ppm 2019-10-02 05:00:00
28735901     1637.147108     ppm 2019-10-02 04:00:00
28736278      686.684452     ppm 2019-10-02 06:00:00
28735710      553.582357     ppm 2019-10-02 03:00:00
28735522      419.468408     ppm 2019-10-02 02:00:00
mma
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2009-06-06 20:00:00  2009.0  6.0  6.0  20.0   0.24            0.24     ppm
1 2009-06-06 21:00:00  2009.0  6.0  6.0  21.0   0.24            0.24     ppm
2 2009-06-06 22:00:00  2009.0  6.0  6.0  22.0   0.24            0.24     ppm
3 2009-06-06 23:00:00  2009.0  6.0  6.0  23.0   0.24            0.24     ppm
4 2009-06-07 00:00:00  2009.0  6.0  7.0   0.0   0.24            0.24     ppm

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2009-06-06 20:00:00  2009.0  6.0  6.0  20.0   0.24            0.24     ppm
1 2009-06-06 21:00:00  2009.0  6.0  6.0  21.0   0.24            0.24     ppm
2 2009-06-06 22:00:00  2009.0  6.0  6.0  22.0   0.24            0.24     ppm
3 2009-06-06 23:00:00  2009.0  6.0  6.0  23.0   0.24            0.24     ppm
4 2009-06-07 00:00:00  2009.0  6.0  7.0   0.0   0.24            0.24     ppm

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
007
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/CO/RJ0022RA007.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
29529979        3.429653     ppm 2016-07-11 00:30:00
26843035        3.290000     ppm 2015-06-17 20:30:00
23844829        3.090000     ppm 2020-10-02 23:00:00
31552453        3.080000     ppm 2020-06-11 22:00:00
31552675        3.050000     ppm 2020-06-11 23:00:00
mma
             DATETIME     ANO  MES   DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2000-07-26 08:00:00  2000.0  7.0  26.0   8.0   2.15            2.15     ppm
1 2000-07-26 09:00:00  2000.0  7.0  26.0   9.0   2.41            2.41     ppm
2 2000-07-26 10:00:00  2000.0  7.0  26.0  10.0   2.80            2.80     ppm
3 2000-07-26 11:00:00  2000.0  7.0  26.0  11.0   2.28            2.28     ppm
4 2000-07-26 12:00:00  2000.0  7.0  26.0  12.0   1.56            1.56     ppm

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME     ANO  MES   DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2000-07-26 08:00:00  2000.0  7.0  26.0   8.0   2.15            2.15     ppm
1 2000-07-26 09:00:00  2000.0  7.0  26.0   9.0   2.41            2.41     ppm
2 2000-07-26 10:00:00  2000.0  7.0  26.0  10.0   2.80            2.80     ppm
3 2000-07-26 11:00:00  2000.0  7.0  26.0  11.0   2.28            2.28     ppm
4 2000-07-26 12:00:00  2000.0  7.0  26.0  12.0   1.56            1.56     ppm

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
007
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/CO/RJ0044RA007.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
21929073       15.586442     ppm 2017-02-23 11:00:00
21934947       15.374116     ppm 2017-11-29 09:00:00
21935247       12.710295     ppm 2017-12-13 13:00:00
21934390       11.346427     ppm 2017-10-25 10:00:00
21935248       10.229117     ppm 2017-12-13 14:00:00
mma
             DATETIME     ANO  MES   DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2002-02-10 03:00:00  2002.0  2.0  10.0   3.0   0.19            0.19     ppm
1 2002-02-10 04:00:00  2002.0  2.0  10.0   4.0   0.18            0.18     ppm
2 2002-02-10 05:00:00  2002.0  2.0  10.0   5.0   0.17            0.17     ppm
3 2002-02-10 06:00:00  2002.0  2.0  10.0   6.0   0.18            0.18     ppm
4 2002-02-10 07:00:00  2002.0  2.0  10.0   7.0   0.16            0.16     ppm

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME     ANO  MES   DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2002-02-10 03:00:00  2002.0  2.0  10.0   3.0   0.19            0.19     ppm
1 2002-02-10 04:00:00  2002.0  2.0  10.0   4.0   0.18            0.18     ppm
2 2002-02-10 05:00:00  2002.0  2.0  10.0   5.0   0.17            0.17     ppm
3 2002-02-10 06:00:00  2002.0  2.0  10.0   6.0   0.18            0.18     ppm
4 2002-02-10 07:00:00  2002.0  2.0  10.0   7.0   0.16            0.16     ppm

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
007
007
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/CO/MG0001RA007.csv

/tmp/ipykernel_273420/1352582357.py:97: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  df_mma = pd.read_csv(arquivo, encoding = 'UTF-8')
/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
32193684            8.15     ppm 2020-05-29 12:30:00
32963415            6.52     ppm 2020-12-31 16:30:00
38204695            6.45     ppm 2021-09-23 10:30:00
38577607            5.97     ppm 2021-12-31 11:30:00
37384060            5.59     ppm 2021-02-25 14:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR VALOR_ORIGINAL UNIDADE  \
0 2009-01-01 01:00:00  2009    1    1     1    NaN          InVld     ppm
1 2009-01-01 02:00:00  2009    1    1     2    NaN          InVld     ppm
2 2009-01-01 03:00:00  2009    1    1     3    NaN          InVld     ppm
3 2009-01-01 04:00:00  2009    1    1     4    NaN          InVld     ppm
4 2009-01-01 05:00:00  2009    1    1     5    NaN          InVld     ppm

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR VALOR_ORIGINAL UNIDADE  \
0 2009-01-01 01:00:00  2009    1    1     1    NaN          InVld     ppm
1 2009-01-01 02:00:00  2009    1    1     2    NaN          InVld     ppm
2 2009-01-01 03:00:00  2009    1    1     3    NaN          InVld     ppm
3 2009-01-01 04:00:00  2009    1    1     4    NaN          InVld     ppm
4 2009-01-01 05:00:00  2009    1    1     5    NaN          InVld     ppm

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
007
007
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/CO/SP0120RA007.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
14754313        6.174779     ppm 2018-07-16 21:00:00
11630153        5.958120     ppm 2016-07-12 21:00:00
6682172         5.633132     ppm 2017-05-24 21:00:00
14754312        5.524802     ppm 2018-07-16 20:00:00
17198316        5.524802     ppm 2015-07-31 20:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1998-01-05 13:00:00  1998    1    5    13    2.1             2.1     ppm
1 1998-01-05 14:00:00  1998    1    5    14    2.2             2.2     ppm
2 1998-01-05 15:00:00  1998    1    5    15    2.6             2.6     ppm
3 1998-01-05 16:00:00  1998    1    5    16    2.4             2.4     ppm
4 1998-01-05 17:00:00  1998    1    5    17    2.2             2.2     ppm

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1998-01-05 13:00:00  1998    1    5    13    2.1             2.1     ppm
1 1998-01-05 14:00:00  1998    1    5    14    2.2             2.2     ppm
2 1998-01-05 15:00:00  1998    1    5    15    2.6             2.6     ppm
3 1998-01-05 16:00:00  1998    1    5    16    2.4             2.4     ppm
4 1998-01-05 17:00:00  1998    1    5    17    2.2             2.2     ppm

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
001
001
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/MP10/RJ0054RA001.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
23504170        564.3819   µg/m3 2020-07-27 11:00:00
23413573        542.0577   µg/m3 2020-07-09 17:00:00
23505856        536.3644   µg/m3 2020-07-27 19:00:00
24267578        503.4962   µg/m3 2020-12-28 09:00:00
23539726        480.4905   µg/m3 2020-08-03 10:00:00
mma
             DATETIME     ANO   MES   DIA  HORA  VALOR  VALOR_ORIGINAL  \
0 2011-10-18 00:00:00  2011.0  10.0  18.0   0.0   3.13            3.13
1 2011-10-18 01:00:00  2011.0  10.0  18.0   1.0  13.58           13.58
2 2011-10-18 02:00:00  2011.0  10.0  18.0   2.0  12.99           12.99
3 2011-10-18 03:00:00  2011.0  10.0  18.0   3.0  19.67           19.67
4 2011-10-18 04:00:00  2011.0  10.0  18.0   4.0  21.82           21.82

  UNIDADE  QAQC_INTERNO  QAQC_MMA
0   µg/m³          True      True
1   µg/m³          True      True
2   µg/m³          True      True
3   µg/m³          True      True
4   µg/m³          True      True
final
             DATETIME     ANO   MES   DIA  HORA  VALOR  VALOR_ORIGINAL  \
0 2011-10-18 00:00:00  2011.0  10.0  18.0   0.0   3.13            3.13
1 2011-10-18 01:00:00  2011.0  10.0  18.0   1.0  13.58           13.58
2 2011-10-18 02:00:00  2011.0  10.0  18.0   2.0  12.99           12.99
3 2011-10-18 03:00:00  2011.0  10.0  18.0   3.0  19.67           19.67
4 2011-10-18 04:00:00  2011.0  10.0  18.0   4.0  21.82           21.82

  UNIDADE  QAQC_INTERNO  QAQC_MMA
0   µg/m³          True      True
1   µg/m³          True      True
2   µg/m³          True      True
3   µg/m³          True      True
4   µg/m³          True      True
001
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/MP10/RJ0030RA001.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
25045218           598.0   ug/m3 2017-06-03 07:00:00
21647265           594.0   ug/m3 2015-10-15 05:30:00
25045196           570.0   ug/m3 2017-06-01 02:00:00
20970924           564.0   ug/m3 2016-08-07 11:30:00
25045290           564.0   ug/m3 2017-06-11 07:00:00
mma
             DATETIME     ANO   MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2001-11-03 00:00:00  2001.0  11.0  3.0   0.0  47.41           47.41   µg/m³
1 2001-11-03 01:00:00  2001.0  11.0  3.0   1.0  35.74           35.74   µg/m³
2 2001-11-03 02:00:00  2001.0  11.0  3.0   2.0  23.38           23.38   µg/m³
3 2001-11-03 03:00:00  2001.0  11.0  3.0   3.0  32.13           32.13   µg/m³
4 2001-11-03 04:00:00  2001.0  11.0  3.0   4.0  29.36           29.36   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME     ANO   MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2001-11-03 00:00:00  2001.0  11.0  3.0   0.0  47.41           47.41   µg/m³
1 2001-11-03 01:00:00  2001.0  11.0  3.0   1.0  35.74           35.74   µg/m³
2 2001-11-03 02:00:00  2001.0  11.0  3.0   2.0  23.38           23.38   µg/m³
3 2001-11-03 03:00:00  2001.0  11.0  3.0   3.0  32.13           32.13   µg/m³
4 2001-11-03 04:00:00  2001.0  11.0  3.0   4.0  29.36           29.36   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
001
001
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/MP10/RJ0029RA001.csv
iema
          VALOR_ORIGINAL UNIDADE            DATETIME
19778203          99.800   µg/m3 2019-03-06 01:00:00
19777862          99.800   µg/m3 2019-03-05 23:00:00
19777688          99.775   µg/m3 2019-03-05 22:00:00
19778034          99.775   µg/m3 2019-03-06 00:00:00
19778372          99.750   µg/m3 2019-03-06 02:00:00
mma
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2016-03-07 16:00:00  2016.0  3.0  7.0  16.0    NaN             NaN   µg/m³
1 2016-03-07 17:00:00  2016.0  3.0  7.0  17.0    NaN             NaN   µg/m³
2 2016-03-07 18:00:00  2016.0  3.0  7.0  18.0    NaN             NaN   µg/m³
3 2016-03-07 19:00:00  2016.0  3.0  7.0  19.0   47.0            47.0   µg/m³
4 2016-03-07 20:00:00  2016.0  3.0  7.0  20.0   19.0            19.0   µg/m³

   QAQC_INTERNO  QAQC_MMA
0         False     False
1         False     False
2         False     False
3          True      True
4          True      True
final
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2016-03-07 16:00:00  2016.0  3.0  7.0  16.0    NaN             NaN   µg/m³
1 2016-03-07 17:00:00  2016.0  3.0  7.0  17.0    NaN             NaN   µg/m³
2 2016-03-07 18:00:00  2016.0  3.0  7.0  18.0    NaN             NaN   µg/m³
3 2016-03-07 19:00:00  2016.0  3.0  7.0  19.0   47.0            47.0   µg/m³
4 2016-03-07 20:00:00  2016.0  3.0  7.0  20.0   19.0            19.0   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True      True
4          True      True

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

001
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/MP10/SP0113RA001.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
11793813           459.0   ug/m3 2016-09-06 02:00:00
17348343           410.0   ug/m3 2015-10-01 21:00:00
17346980           395.0   ug/m3 2015-08-06 02:00:00
17348629           383.0   ug/m3 2015-10-13 19:00:00
11065624           329.0   ug/m3 2021-09-08 15:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2008-09-02 01:00:00  2008    9    2     1   86.0            86.0   µg/m3
1 2008-09-02 02:00:00  2008    9    2     2   82.0            82.0   µg/m3
2 2008-09-02 03:00:00  2008    9    2     3   94.0            94.0   µg/m3
3 2008-09-02 04:00:00  2008    9    2     4   94.0            94.0   µg/m3
4 2008-09-02 05:00:00  2008    9    2     5   96.0            96.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2008-09-02 01:00:00  2008    9    2     1   86.0            86.0   µg/m3
1 2008-09-02 02:00:00  2008    9    2     2   82.0            82.0   µg/m3
2 2008-09-02 03:00:00  2008    9    2     3   94.0            94.0   µg/m3
3 2008-09-02 04:00:00  2008    9    2     4   94.0            94.0   µg/m3
4 2008-09-02 05:00:00  2008    9    2     5   96.0            96.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
001
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/MP10/SP0107RA001.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
18817427           611.0   ug/m3 2015-06-16 07:00:00
18818113           480.0   ug/m3 2015-07-14 21:00:00
12324589           440.0   ug/m3 2020-10-04 01:00:00
12324707           342.0   ug/m3 2020-10-08 23:00:00
18820505           339.0   ug/m3 2015-10-22 22:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2008-08-20 01:00:00  2008    8   20     1   52.0            52.0   µg/m3
1 2008-08-20 02:00:00  2008    8   20     2   39.0            39.0   µg/m3
2 2008-08-20 03:00:00  2008    8   20     3   36.0            36.0   µg/m3
3 2008-08-20 04:00:00  2008    8   20     4   40.0            40.0   µg/m3
4 2008-08-20 05:00:00  2008    8   20     5   35.0            35.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2008-08-20 01:00:00  2008    8   20     1   52.0            52.0   µg/m3
1 2008-08-20 02:00:00  2008    8   20     2   39.0            39.0   µg/m3
2 2008-08-20 03:00:00  2008    8   20     3   36.0            36.0   µg/m3
3 2008-08-20 04:00:00  2008    8   20     4   40.0            40.0   µg/m3
4 2008-08-20 05:00:00  2008    8   20     5   35.0            35.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
001
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/MP10/RJ0077RA001.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
20149710      535.000026   µg/m3 2019-06-04 21:00:00
31372751      481.999993   µg/m3 2020-05-06 15:00:00
24802372      458.000000   ug/m3 2017-06-22 01:00:00
20142575      449.000001   µg/m3 2019-06-03 05:00:00
21308590      404.000000   ug/m3 2015-08-19 00:30:00
mma
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2004-01-07 00:00:00  2004.0  1.0  7.0   0.0   65.8            65.8   µg/m³
1 2004-01-07 01:00:00  2004.0  1.0  7.0   1.0   90.3            90.3   µg/m³
2 2004-01-07 02:00:00  2004.0  1.0  7.0   2.0  100.8           100.8   µg/m³
3 2004-01-07 03:00:00  2004.0  1.0  7.0   3.0   56.0            56.0   µg/m³
4 2004-01-07 04:00:00  2004.0  1.0  7.0   4.0   58.6            58.6   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2004-01-07 00:00:00  2004.0  1.0  7.0   0.0   65.8            65.8   µg/m³
1 2004-01-07 01:00:00  2004.0  1.0  7.0   1.0   90.3            90.3   µg/m³
2 2004-01-07 02:00:00  2004.0  1.0  7.0   2.0  100.8           100.8   µg/m³
3 2004-01-07 03:00:00  2004.0  1.0  7.0   3.0   56.0            56.0   µg/m³
4 2004-01-07 04:00:00  2004.0  1.0  7.0   4.0   58.6            58.6   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
001
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/MP10/RJ0082RA001.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
24816705           589.0   ug/m3 2017-06-30 02:00:00
24817544           580.0   ug/m3 2017-08-07 18:00:00
24817545           534.0   ug/m3 2017-08-07 19:00:00
20726837           335.0   ug/m3 2016-12-28 08:30:00
24817555           311.0   ug/m3 2017-08-08 06:00:00
mma
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2004-06-08 00:00:00  2004.0  6.0  8.0   0.0    NaN             NaN   µg/m³
1 2004-06-08 01:00:00  2004.0  6.0  8.0   1.0  44.98           44.98   µg/m³
2 2004-06-08 02:00:00  2004.0  6.0  8.0   2.0  17.49           17.49   µg/m³
3 2004-06-08 03:00:00  2004.0  6.0  8.0   3.0  18.56           18.56   µg/m³
4 2004-06-08 04:00:00  2004.0  6.0  8.0   4.0  24.11           24.11   µg/m³

   QAQC_INTERNO  QAQC_MMA
0         False     False
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2004-06-08 00:00:00  2004.0  6.0  8.0   0.0    NaN             NaN   µg/m³
1 2004-06-08 01:00:00  2004.0  6.0  8.0   1.0  44.98           44.98   µg/m³
2 2004-06-08 02:00:00  2004.0  6.0  8.0   2.0  17.49           17.49   µg/m³
3 2004-06-08 03:00:00  2004.0  6.0  8.0   3.0  18.56           18.56   µg/m³
4 2004-06-08 04:00:00  2004.0  6.0  8.0   4.0  24.11           24.11   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True      True
2          True      True
3          True      True
4          True      True
001
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/MP10/MG0003RA001.csv

/tmp/ipykernel_273420/1352582357.py:97: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  df_mma = pd.read_csv(arquivo, encoding = 'UTF-8')
/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
32314348          473.84   µg/m3 2020-07-02 06:30:00
34466949          438.69   µg/m3 2019-07-17 16:30:00
38521322          412.00   µg/m3 2021-12-16 07:30:00
34680689          366.48   µg/m3 2019-09-11 23:30:00
34418762          365.76   µg/m3 2019-07-04 14:30:00
mma
             DATETIME     ANO  MES  DIA  HORA  VALOR VALOR_ORIGINAL UNIDADE  \
0 2009-01-01 01:00:00  2009.0  1.0  1.0   1.0   11.5           11.5   µg/m3
1 2009-01-01 02:00:00  2009.0  1.0  1.0   2.0   52.2           52.2   µg/m3
2 2009-01-01 03:00:00  2009.0  1.0  1.0   3.0   18.0             18   µg/m3
3 2009-01-01 04:00:00  2009.0  1.0  1.0   4.0    NaN              0   µg/m3
4 2009-01-01 05:00:00  2009.0  1.0  1.0   5.0    NaN              0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True     False
4          True     False
final
             DATETIME     ANO  MES  DIA  HORA  VALOR VALOR_ORIGINAL UNIDADE  \
0 2009-01-01 01:00:00  2009.0  1.0  1.0   1.0   11.5           11.5   µg/m3
1 2009-01-01 02:00:00  2009.0  1.0  1.0   2.0   52.2           52.2   µg/m3
2 2009-01-01 03:00:00  2009.0  1.0  1.0   3.0   18.0             18   µg/m3
3 2009-01-01 04:00:00  2009.0  1.0  1.0   4.0    NaN              0   µg/m3
4 2009-01-01 05:00:00  2009.0  1.0  1.0   5.0    NaN              0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True     False
4          True     False
001
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/MP10/RJ0066RA001.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
23844861      160.000000   µg/m3 2020-10-02 23:00:00
23844647      156.000000   µg/m3 2020-10-02 22:00:00
23843412      153.000000   µg/m3 2020-10-02 16:00:00
20183694      142.000005   µg/m3 2019-06-12 17:00:00
20271813      136.000007   µg/m3 2019-07-03 07:00:00
mma
             DATETIME     ANO  MES   DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2014-07-21 00:00:00  2014.0  7.0  21.0   0.0   26.0            26.0   µg/m³
1 2014-07-21 01:00:00  2014.0  7.0  21.0   1.0   34.0            34.0   µg/m³
2 2014-07-21 02:00:00  2014.0  7.0  21.0   2.0   25.0            25.0   µg/m³
3 2014-07-21 03:00:00  2014.0  7.0  21.0   3.0    NaN             NaN   µg/m³
4 2014-07-21 04:00:00  2014.0  7.0  21.0   4.0   13.0            13.0   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3         False     False
4          True      True
final
             DATETIME     ANO  MES   DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2014-07-21 00:00:00  2014.0  7.0  21.0   0.0   26.0            26.0   µg/m³
1 2014-07-21 01:00:00  2014.0  7.0  21.0   1.0   34.0            34.0   µg/m³
2 2014-07-21 02:00:00  2014.0  7.0  21.0   2.0   25.0            25.0   µg/m³
3 2014-07-21 03:00:00  2014.0  7.0  21.0   3.0    NaN             NaN   µg/m³
4 2014-07-21 04:00:00  2014.0  7.0  21.0   4.0   13.0            13.0   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True     False
4          True      True
001
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/MP10/MG0023RA001.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
37974522           880.0   µg/m3 2021-07-28 07:30:00
34851456           737.0   µg/m3 2019-10-26 17:30:00
34461995           657.0   µg/m3 2019-07-16 08:30:00
34461835           649.0   µg/m3 2019-07-16 07:30:00
37382952           646.0   µg/m3 2021-02-25 06:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2015-03-10 17:00:00  2015    3   10    17   64.0            64.0   µg/m3
1 2015-03-10 18:00:00  2015    3   10    18   99.0            99.0   µg/m3
2 2015-03-10 19:00:00  2015    3   10    19   80.0            80.0   µg/m3
3 2015-03-10 20:00:00  2015    3   10    20  122.0           122.0   µg/m3
4 2015-03-10 21:00:00  2015    3   10    21   42.0            42.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2015-03-10 17:00:00  2015    3   10    17   64.0            64.0   µg/m3
1 2015-03-10 18:00:00  2015    3   10    18   99.0            99.0   µg/m3
2 2015-03-10 19:00:00  2015    3   10    19   80.0            80.0   µg/m3
3 2015-03-10 20:00:00  2015    3   10    20  122.0           122.0   µg/m3
4 2015-03-10 21:00:00  2015    3   10    21   42.0            42.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
001
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/MP10/SP0281RA001.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
16176508           457.0   ug/m3 2021-03-19 15:00:00
9957380            427.0   ug/m3 2018-06-24 09:00:00
16180476           398.0   ug/m3 2021-09-08 17:00:00
14610611           369.0   ug/m3 2016-06-17 23:00:00
9959039            358.0   ug/m3 2018-09-01 12:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2016-01-01 01:00:00  2016    1    1     1   18.0            18.0   µg/m3
1 2016-01-01 02:00:00  2016    1    1     2    9.0             9.0   µg/m3
2 2016-01-01 03:00:00  2016    1    1     3   16.0            16.0   µg/m3
3 2016-01-01 04:00:00  2016    1    1     4   15.0            15.0   µg/m3
4 2016-01-01 05:00:00  2016    1    1     5   16.0            16.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2016-01-01 01:00:00  2016    1    1     1   18.0            18.0   ug/m3
1 2016-01-01 02:00:00  2016    1    1     2    9.0             9.0   ug/m3
2 2016-01-01 03:00:00  2016    1    1     3   16.0            16.0   ug/m3
3 2016-01-01 04:00:00  2016    1    1     4   15.0            15.0   ug/m3
4 2016-01-01 05:00:00  2016    1    1     5   16.0            16.0   ug/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
001
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/MP10/RJ0039RA001.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
25276726           995.0   ug/m3 2017-05-10 08:00:00
25276665           995.0   ug/m3 2017-05-07 16:00:00
25276679           995.0   ug/m3 2017-05-08 06:00:00
25276725           995.0   ug/m3 2017-05-10 07:00:00
25276670           995.0   ug/m3 2017-05-07 21:00:00
mma
             DATETIME     ANO  MES   DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2009-02-14 00:00:00  2009.0  2.0  14.0   0.0    NaN             NaN   µg/m³
1 2009-02-14 01:00:00  2009.0  2.0  14.0   1.0    NaN             NaN   µg/m³
2 2009-02-14 02:00:00  2009.0  2.0  14.0   2.0    NaN             NaN   µg/m³
3 2009-02-14 03:00:00  2009.0  2.0  14.0   3.0    NaN             NaN   µg/m³
4 2009-02-14 04:00:00  2009.0  2.0  14.0   4.0    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0         False     False
1         False     False
2         False     False
3         False     False
4         False     False
final
             DATETIME     ANO  MES   DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2009-02-14 00:00:00  2009.0  2.0  14.0   0.0    NaN             NaN   µg/m³
1 2009-02-14 01:00:00  2009.0  2.0  14.0   1.0    NaN             NaN   µg/m³
2 2009-02-14 02:00:00  2009.0  2.0  14.0   2.0    NaN             NaN   µg/m³
3 2009-02-14 03:00:00  2009.0  2.0  14.0   3.0    NaN             NaN   µg/m³
4 2009-02-14 04:00:00  2009.0  2.0  14.0   4.0    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
001
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/MP10/MG0019RA001.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
35761981           566.0   µg/m3 2017-05-10 20:30:00
35761983           529.0   µg/m3 2017-05-10 19:30:00
34718792           394.0   µg/m3 2019-09-21 22:30:00
34719432           375.0   µg/m3 2019-09-22 02:30:00
34718628           373.0   µg/m3 2019-09-21 21:30:00
mma
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2015-01-01 01:00:00  2015.0  1.0  1.0   1.0   17.0            17.0   µg/m3
1 2015-01-01 02:00:00  2015.0  1.0  1.0   2.0   19.0            19.0   µg/m3
2 2015-01-01 03:00:00  2015.0  1.0  1.0   3.0   14.0            14.0   µg/m3
3 2015-01-01 04:00:00  2015.0  1.0  1.0   4.0   19.0            19.0   µg/m3
4 2015-01-01 05:00:00  2015.0  1.0  1.0   5.0   16.0            16.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2015-01-01 01:00:00  2015.0  1.0  1.0   1.0   17.0            17.0   µg/m3
1 2015-01-01 02:00:00  2015.0  1.0  1.0   2.0   19.0            19.0   µg/m3
2 2015-01-01 03:00:00  2015.0  1.0  1.0   3.0   14.0            14.0   µg/m3
3 2015-01-01 04:00:00  2015.0  1.0  1.0   4.0   19.0            19.0   µg/m3
4 2015-01-01 05:00:00  2015.0  1.0  1.0   5.0   16.0            16.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
001
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/MP10/MG0062RA001.csv
iema
          VALOR_ORIGINAL UNIDADE            DATETIME
32586296           761.0   µg/m3 2020-09-17 06:30:00
32640320           716.0   µg/m3 2020-10-02 06:30:00
39377583           691.0   µg/m3 2022-08-16 06:30:00
32617408           617.0   µg/m3 2020-09-26 02:30:00
32635703           598.0   µg/m3 2020-10-01 01:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2020-01-01 01:00:00  2020    1    1     1    NaN             NaN   µg/m3
1 2020-01-01 02:00:00  2020    1    1     2    NaN             NaN   µg/m3
2 2020-01-01 03:00:00  2020    1    1     3    NaN             NaN   µg/m3
3 2020-01-01 04:00:00  2020    1    1     4    NaN             NaN   µg/m3
4 2020-01-01 05:00:00  2020    1    1     5    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2020-01-01 01:00:00  2020    1    1     1    NaN             NaN   µg/m3
1 2020-01-01 02:00:00  2020    1    1     2    NaN             NaN   µg/m3
2 2020-01-01 03:00:00  2020    1    1     3    NaN             NaN   µg/m3
3 2020-01-01 04:00:00  2020    1    1     4    NaN             NaN   µg/m3
4 2020-01-01 05:00:00  2020    1    1     5    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

001
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/MP10/RJ0080RA001.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
23393661      477.999985   µg/m3 2020-07-05 18:00:00
21394107      398.000000   ug/m3 2015-01-18 20:30:00
24915221      342.000000   ug/m3 2017-08-03 15:00:00
21399819      337.000000   ug/m3 2015-09-24 18:30:00
24916089      333.000000   ug/m3 2017-09-17 11:00:00
mma
             DATETIME     ANO   MES   DIA  HORA  VALOR  VALOR_ORIGINAL  \
0 2008-12-10 15:00:00  2008.0  12.0  10.0  15.0    NaN             NaN
1 2008-12-10 16:00:00  2008.0  12.0  10.0  16.0   60.0            60.0
2 2008-12-10 17:00:00  2008.0  12.0  10.0  17.0   35.0            35.0
3 2008-12-10 18:00:00  2008.0  12.0  10.0  18.0   21.0            21.0
4 2008-12-10 19:00:00  2008.0  12.0  10.0  19.0   41.0            41.0

  UNIDADE  QAQC_INTERNO  QAQC_MMA
0   µg/m³         False     False
1   µg/m³          True      True
2   µg/m³          True      True
3   µg/m³          True      True
4   µg/m³          True      True
final
             DATETIME     ANO   MES   DIA  HORA  VALOR  VALOR_ORIGINAL  \
0 2008-12-10 15:00:00  2008.0  12.0  10.0  15.0    NaN             NaN
1 2008-12-10 16:00:00  2008.0  12.0  10.0  16.0   60.0            60.0
2 2008-12-10 17:00:00  2008.0  12.0  10.0  17.0   35.0            35.0
3 2008-12-10 18:00:00  2008.0  12.0  10.0  18.0   21.0            21.0
4 2008-12-10 19:00:00  2008.0  12.0  10.0  19.0   41.0            41.0

  UNIDADE  QAQC_INTERNO  QAQC_MMA
0   µg/m³          True     False
1   µg/m³          True      True
2   µg/m³          True      True
3   µg/m³          True      True
4   µg/m³          True      True
001
001
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/MP10/RJ0023RA001.csv
iema
          VALOR_ORIGINAL UNIDADE            DATETIME
26877207           289.0   ug/m3 2015-01-19 16:30:00
26877111           267.0   ug/m3 2015-01-15 16:30:00
26882728           255.0   ug/m3 2015-10-15 16:30:00
26877208           237.0   ug/m3 2015-01-19 18:30:00
26882248           231.0   ug/m3 2015-09-25 16:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2013-04-12 18:00:00  2013    4   12    18    NaN             NaN   µg/m³
1 2013-04-12 19:00:00  2013    4   12    19    NaN             NaN   µg/m³
2 2013-04-12 20:00:00  2013    4   12    20    NaN             NaN   µg/m³
3 2013-04-12 21:00:00  2013    4   12    21    NaN             NaN   µg/m³
4 2013-04-12 22:00:00  2013    4   12    22    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0         False     False
1         False     False
2         False     False
3         False     False
4         False     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2013-04-12 18:00:00  2013    4   12    18    NaN             NaN   µg/m³
1 2013-04-12 19:00:00  2013    4   12    19    NaN             NaN   µg/m³
2 2013-04-12 20:00:00  2013    4   12    20    NaN             NaN   µg/m³
3 2013-04-12 21:00:00  2013    4   12    21    NaN             NaN   µg/m³
4 2013-04-12 22:00:00  2013    4   12    22    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

001
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/MP10/MG0064RA001.csv
iema
          VALOR_ORIGINAL UNIDADE            DATETIME
39674378           502.0   µg/m3 2022-11-06 07:30:00
39146110           491.0   µg/m3 2022-06-13 15:30:00
39700535           230.0   µg/m3 2022-11-13 10:30:00
39565000           153.0   µg/m3 2022-10-06 18:30:00
39656806           152.0   µg/m3 2022-11-01 07:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2022-01-01 01:00:00  2022    1    1     1    NaN             NaN   µg/m3
1 2022-01-01 02:00:00  2022    1    1     2    NaN             NaN   µg/m3
2 2022-01-01 03:00:00  2022    1    1     3    NaN             NaN   µg/m3
3 2022-01-01 04:00:00  2022    1    1     4    NaN             NaN   µg/m3
4 2022-01-01 05:00:00  2022    1    1     5    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2022-01-01 01:00:00  2022    1    1     1    NaN             NaN   µg/m3
1 2022-01-01 02:00:00  2022    1    1     2    NaN             NaN   µg/m3
2 2022-01-01 03:00:00  2022    1    1     3    NaN             NaN   µg/m3
3 2022-01-01 04:00:00  2022    1    1     4    NaN             NaN   µg/m3
4 2022-01-01 05:00:00  2022    1    1     5    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
001

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/MP10/MG0027RA001.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
39282417          1252.0   µg/m3 2022-07-21 15:30:00
39281653           843.0   µg/m3 2022-07-21 10:30:00
39281498           512.0   µg/m3 2022-07-21 09:30:00
39357187           490.0   µg/m3 2022-08-10 20:30:00
39355911           470.0   µg/m3 2022-08-10 12:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2015-01-01 01:00:00  2015    1    1     1   44.0            44.0   µg/m3
1 2015-01-01 02:00:00  2015    1    1     2   42.7            42.7   µg/m3
2 2015-01-01 03:00:00  2015    1    1     3   20.1            20.1   µg/m3
3 2015-01-01 04:00:00  2015    1    1     4   22.2            22.2   µg/m3
4 2015-01-01 05:00:00  2015    1    1     5   15.4            15.4   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2015-01-01 01:00:00  2015    1    1     1   44.0            44.0   µg/m3
1 2015-01-01 02:00:00  2015    1    1     2   42.7            42.7   µg/m3
2 2015-01-01 03:00:00  2015    1    1     3   20.1            20.1   µg/m3
3 2015-01-01 04:00:00  2015    1    1     4   22.2            22.2   µg/m3
4 2015-01-01 05:00:00  2015    1    1     5   15.4            15.4   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
001
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/MP10/MG0035RA001.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
34376787           854.0   µg/m3 2019-06-22 16:30:00
36596274           844.0   µg/m3 2018-07-01 20:30:00
36596409           834.0   µg/m3 2018-07-01 21:30:00
34377230           804.0   µg/m3 2019-06-22 19:30:00
39209687           714.0   µg/m3 2022-07-01 08:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2017-01-01 01:00:00  2017    1    1     1    NaN             NaN   µg/m3
1 2017-01-01 02:00:00  2017    1    1     2    NaN             NaN   µg/m3
2 2017-01-01 03:00:00  2017    1    1     3    NaN             NaN   µg/m3
3 2017-01-01 04:00:00  2017    1    1     4    NaN             NaN   µg/m3
4 2017-01-01 05:00:00  2017    1    1     5    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2017-01-01 01:00:00  2017    1    1     1    NaN             NaN   µg/m3
1 2017-01-01 02:00:00  2017    1    1     2    NaN             NaN   µg/m3
2 2017-01-01 03:00:00  2017    1    1     3    NaN             NaN   µg/m3
3 2017-01-01 04:00:00  2017    1    1     4    NaN             NaN   µg/m3
4 2017-01-01 05:00:00  2017    1    1     5    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
001
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/MP10/SP0248RA001.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
18992779           555.0   ug/m3 2015-08-24 17:00:00
15672465           544.0   ug/m3 2021-09-21 23:00:00
18992420           542.0   ug/m3 2015-08-09 13:00:00
8533779            512.0   ug/m3 2022-11-11 13:00:00
14124673           502.0   ug/m3 2016-08-16 18:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2009-04-15 01:00:00  2009    4   15     1   15.0            15.0   µg/m3
1 2009-04-15 02:00:00  2009    4   15     2   11.0            11.0   µg/m3
2 2009-04-15 03:00:00  2009    4   15     3    NaN             NaN     NaN
3 2009-04-15 04:00:00  2009    4   15     4    4.0             4.0   µg/m3
4 2009-04-15 05:00:00  2009    4   15     5    4.0             4.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True     False
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2009-04-15 01:00:00  2009    4   15     1   15.0            15.0   µg/m3
1 2009-04-15 02:00:00  2009    4   15     2   11.0            11.0   µg/m3
2 2009-04-15 03:00:00  2009    4   15     3    NaN             NaN     NaN
3 2009-04-15 04:00:00  2009    4   15     4    4.0             4.0   µg/m3
4 2009-04-15 05:00:00  2009    4   15     5    4.0             4.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True     False
3          True      True
4          True      True
001
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/MP10/SP0064RA001.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
         VALOR_ORIGINAL UNIDADE            DATETIME
7309744           209.0   ug/m3 2017-09-15 01:00:00
7309745           208.0   ug/m3 2017-09-15 02:00:00
8074762           207.0   ug/m3 2019-09-18 02:00:00
7309743           203.0   ug/m3 2017-09-14 23:55:00
7310745           195.0   ug/m3 2017-10-30 15:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1998-01-01 01:00:00  1998    1    1     1  155.0           155.0   µg/m3
1 1998-01-01 02:00:00  1998    1    1     2   18.0            18.0   µg/m3
2 1998-01-01 03:00:00  1998    1    1     3   10.0            10.0   µg/m3
3 1998-01-01 04:00:00  1998    1    1     4   28.0            28.0   µg/m3
4 1998-01-01 05:00:00  1998    1    1     5   25.0            25.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1998-01-01 01:00:00  1998    1    1     1  155.0           155.0   µg/m3
1 1998-01-01 02:00:00  1998    1    1     2   18.0            18.0   µg/m3
2 1998-01-01 03:00:00  1998    1    1     3   10.0            10.0   µg/m3
3 1998-01-01 04:00:00  1998    1    1     4   28.0            28.0   µg/m3
4 1998-01-01 05:00:00  1998    1    1     5   25.0            25.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
001
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/MP10/MG0022RA001.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
33294025           299.0   µg/m3 2015-01-28 20:30:00
32284342           276.1   µg/m3 2020-06-23 17:30:00
37975678           268.8   µg/m3 2021-07-28 14:30:00
38248714           266.0   µg/m3 2021-10-04 15:30:00
38672341           265.8   µg/m3 2022-01-29 14:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2015-01-01 01:00:00  2015    1    1     1   33.6            33.6   µg/m3
1 2015-01-01 02:00:00  2015    1    1     2   32.2            32.2   µg/m3
2 2015-01-01 03:00:00  2015    1    1     3   22.3            22.3   µg/m3
3 2015-01-01 04:00:00  2015    1    1     4   21.2            21.2   µg/m3
4 2015-01-01 05:00:00  2015    1    1     5   19.0            19.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2015-01-01 01:00:00  2015    1    1     1   33.6            33.6   µg/m3
1 2015-01-01 02:00:00  2015    1    1     2   32.2            32.2   µg/m3
2 2015-01-01 03:00:00  2015    1    1     3   22.3            22.3   µg/m3
3 2015-01-01 04:00:00  2015    1    1     4   21.2            21.2   µg/m3
4 2015-01-01 05:00:00  2015    1    1     5   19.0            19.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
001
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/MP10/MG0053RA001.csv
iema
          VALOR_ORIGINAL UNIDADE            DATETIME
34475519           563.0   µg/m3 2019-07-19 23:30:00
34356165           402.0   µg/m3 2019-06-16 17:30:00
32624259           357.0   µg/m3 2020-09-27 23:30:00
34707605           306.0   µg/m3 2019-09-18 22:30:00
32590747           298.0   µg/m3 2020-09-18 14:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2018-01-01 01:00:00  2018    1    1     1    8.0             8.0   µg/m3
1 2018-01-01 02:00:00  2018    1    1     2   17.0            17.0   µg/m3
2 2018-01-01 03:00:00  2018    1    1     3   20.0            20.0   µg/m3
3 2018-01-01 04:00:00  2018    1    1     4   22.0            22.0   µg/m3
4 2018-01-01 05:00:00  2018    1    1     5   25.0            25.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2018-01-01 01:00:00  2018    1    1     1    8.0             8.0   µg/m3
1 2018-01-01 02:00:00  2018    1    1     2   17.0            17.0   µg/m3
2 2018-01-01 03:00:00  2018    1    1     3   20.0            20.0   µg/m3
3 2018-01-01 04:00:00  2018    1    1     4   22.0            22.0   µg/m3
4 2018-01-01 05:00:00  2018    1    1     5   25.0            25.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

001
001
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/MP10/SP0117RA001.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
17279776           416.0   ug/m3 2015-07-02 11:00:00
10956963           361.0   ug/m3 2021-04-30 13:00:00
10960002           356.0   ug/m3 2021-09-06 03:00:00
10200846           341.0   ug/m3 2020-06-24 14:00:00
14865431           334.0   ug/m3 2018-10-31 19:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2000-03-01 17:00:00  2000    3    1    17    NaN             0.0   µg/m3
1 2000-03-01 18:00:00  2000    3    1    18    1.0             1.0   µg/m3
2 2000-03-01 19:00:00  2000    3    1    19    1.0             1.0   µg/m3
3 2000-03-01 20:00:00  2000    3    1    20    1.0             1.0   µg/m3
4 2000-03-01 21:00:00  2000    3    1    21    1.0             1.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2000-03-01 17:00:00  2000    3    1    17    NaN             0.0   µg/m3
1 2000-03-01 18:00:00  2000    3    1    18    1.0             1.0   µg/m3
2 2000-03-01 19:00:00  2000    3    1    19    1.0             1.0   µg/m3
3 2000-03-01 20:00:00  2000    3    1    20    1.0             1.0   µg/m3
4 2000-03-01 21:00:00  2000    3    1    21    1.0             1.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True      True
2          True      True
3          True      True
4          True      True
001
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/MP10/SP0280RA001.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
12271984           357.0   ug/m3 2016-08-15 17:00:00
8326687            263.0   ug/m3 2019-07-26 09:00:00
10776666           234.0   ug/m3 2020-10-21 16:00:00
11535259           231.0   ug/m3 2021-07-25 19:00:00
11535235           225.0   ug/m3 2021-07-24 19:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2015-10-01 01:00:00  2015   10    1     1   10.0            10.0   µg/m3
1 2015-10-01 02:00:00  2015   10    1     2    9.0             9.0   µg/m3
2 2015-10-01 03:00:00  2015   10    1     3    5.0             5.0   µg/m3
3 2015-10-01 04:00:00  2015   10    1     4    9.0             9.0   µg/m3
4 2015-10-01 05:00:00  2015   10    1     5   16.0            16.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2015-10-01 01:00:00  2015   10    1     1   10.0            10.0   ug/m3
1 2015-10-01 02:00:00  2015   10    1     2    9.0             9.0   ug/m3
2 2015-10-01 03:00:00  2015   10    1     3    5.0             5.0   ug/m3
3 2015-10-01 04:00:00  2015   10    1     4    9.0             9.0   ug/m3
4 2015-10-01 05:00:00  2015   10    1     5   16.0            16.0   ug/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
001
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/MP10/RJ0075RA001.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
20589734           542.0   ug/m3 2016-10-19 23:30:00
20586427           337.0   ug/m3 2016-05-11 12:30:00
23663914           308.0   µg/m3 2020-08-27 21:00:00
20589346           276.0   ug/m3 2016-10-03 12:30:00
20585525           259.0   ug/m3 2016-04-03 00:30:00
mma
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2004-01-07 00:00:00  2004.0  1.0  7.0   0.0   45.3            45.3   µg/m³
1 2004-01-07 01:00:00  2004.0  1.0  7.0   1.0   51.0            51.0   µg/m³
2 2004-01-07 02:00:00  2004.0  1.0  7.0   2.0   28.1            28.1   µg/m³
3 2004-01-07 03:00:00  2004.0  1.0  7.0   3.0   16.6            16.6   µg/m³
4 2004-01-07 04:00:00  2004.0  1.0  7.0   4.0   10.9            10.9   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2004-01-07 00:00:00  2004.0  1.0  7.0   0.0   45.3            45.3   µg/m³
1 2004-01-07 01:00:00  2004.0  1.0  7.0   1.0   51.0            51.0   µg/m³
2 2004-01-07 02:00:00  2004.0  1.0  7.0   2.0   28.1            28.1   µg/m³
3 2004-01-07 03:00:00  2004.0  1.0  7.0   3.0   16.6            16.6   µg/m³
4 2004-01-07 04:00:00  2004.0  1.0  7.0   4.0   10.9            10.9   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
001
001
001
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/MP10/SP0108RA001.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
18861456           443.0   ug/m3 2015-09-17 20:00:00
18861711           290.0   ug/m3 2015-09-28 11:00:00
15563835           285.0   ug/m3 2021-09-13 13:00:00
18861455           282.0   ug/m3 2015-09-17 19:00:00
12362916           271.0   ug/m3 2020-11-09 19:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2008-05-09 02:00:00  2008    5    9     2   46.0            46.0   µg/m3
1 2008-05-09 03:00:00  2008    5    9     3   34.0            34.0   µg/m3
2 2008-05-09 04:00:00  2008    5    9     4   36.0            36.0   µg/m3
3 2008-05-09 05:00:00  2008    5    9     5   28.0            28.0   µg/m3
4 2008-05-09 06:00:00  2008    5    9     6   32.0            32.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2008-05-09 02:00:00  2008    5    9     2   46.0            46.0   µg/m3
1 2008-05-09 03:00:00  2008    5    9     3   34.0            34.0   µg/m3
2 2008-05-09 04:00:00  2008    5    9     4   36.0            36.0   µg/m3
3 2008-05-09 05:00:00  2008    5    9     5   28.0            28.0   µg/m3
4 2008-05-09 06:00:00  2008    5    9     6   32.0            32.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
001
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/MP10/RJ0026RA001.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
20236770          598.02   µg/m3 2019-06-25 11:00:00
31058451          589.75   µg/m3 2020-03-02 11:00:00
28420310          549.06   µg/m3 2019-07-24 09:00:00
28505285          499.56   µg/m3 2019-08-12 03:00:00
31393574          495.35   µg/m3 2020-05-10 18:00:00
mma
             DATETIME     ANO  MES   DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2006-07-21 00:00:00  2006.0  7.0  21.0   0.0    NaN             NaN   µg/m³
1 2006-07-21 01:00:00  2006.0  7.0  21.0   1.0  37.16           37.16   µg/m³
2 2006-07-21 02:00:00  2006.0  7.0  21.0   2.0  36.08           36.08   µg/m³
3 2006-07-21 03:00:00  2006.0  7.0  21.0   3.0  54.99           54.99   µg/m³
4 2006-07-21 04:00:00  2006.0  7.0  21.0   4.0  29.31           29.31   µg/m³

   QAQC_INTERNO  QAQC_MMA
0         False     False
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME     ANO  MES   DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2006-07-21 00:00:00  2006.0  7.0  21.0   0.0    NaN             NaN   µg/m³
1 2006-07-21 01:00:00  2006.0  7.0  21.0   1.0  37.16           37.16   µg/m³
2 2006-07-21 02:00:00  2006.0  7.0  21.0   2.0  36.08           36.08   µg/m³
3 2006-07-21 03:00:00  2006.0  7.0  21.0   3.0  54.99           54.99   µg/m³
4 2006-07-21 04:00:00  2006.0  7.0  21.0   4.0  29.31           29.31   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True      True
2          True      True
3          True      True
4          True      True
001
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/MP10/MG0031RA001.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
34888020           553.0   µg/m3 2019-11-05 13:30:00
38135893           486.0   µg/m3 2021-09-05 22:30:00
34716373           457.0   µg/m3 2019-09-21 06:30:00
38121605           413.0   µg/m3 2021-09-02 09:30:00
38037581           406.0   µg/m3 2021-08-12 15:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2015-01-01 01:00:00  2015    1    1     1   37.0            37.0   µg/m3
1 2015-01-01 02:00:00  2015    1    1     2   31.0            31.0   µg/m3
2 2015-01-01 03:00:00  2015    1    1     3   25.0            25.0   µg/m3
3 2015-01-01 04:00:00  2015    1    1     4   24.0            24.0   µg/m3
4 2015-01-01 05:00:00  2015    1    1     5   26.0            26.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2015-01-01 01:00:00  2015    1    1     1   37.0            37.0   µg/m3
1 2015-01-01 02:00:00  2015    1    1     2   31.0            31.0   µg/m3
2 2015-01-01 03:00:00  2015    1    1     3   25.0            25.0   µg/m3
3 2015-01-01 04:00:00  2015    1    1     4   24.0            24.0   µg/m3
4 2015-01-01 05:00:00  2015    1    1     5   26.0            26.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
001
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/MP10/SP0099RA001.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
16496222           225.0   ug/m3 2022-02-23 05:00:00
10261588           194.0   ug/m3 2020-10-05 13:00:00
11038279           193.0   ug/m3 2021-11-30 13:00:00
6880800            192.0   ug/m3 2017-03-03 05:00:00
14921190           181.0   ug/m3 2018-06-23 09:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1999-09-05 13:00:00  1999    9    5    13    4.0             4.0   µg/m3
1 1999-09-05 14:00:00  1999    9    5    14    5.0             5.0   µg/m3
2 1999-09-05 15:00:00  1999    9    5    15   11.0            11.0   µg/m3
3 1999-09-05 16:00:00  1999    9    5    16    NaN             NaN     NaN
4 1999-09-05 17:00:00  1999    9    5    17    NaN             NaN     NaN

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True     False
4          True     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1999-09-05 13:00:00  1999    9    5    13    4.0             4.0   µg/m3
1 1999-09-05 14:00:00  1999    9    5    14    5.0             5.0   µg/m3
2 1999-09-05 15:00:00  1999    9    5    15   11.0            11.0   µg/m3
3 1999-09-05 16:00:00  1999    9    5    16    NaN             NaN     NaN
4 1999-09-05 17:00:00  1999    9    5    17    NaN             NaN     NaN

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True     False
4          True     False
001
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/MP10/MG0005RA001.csv

/tmp/ipykernel_273420/1352582357.py:97: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  df_mma = pd.read_csv(arquivo, encoding = 'UTF-8')
/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
34706106          799.88   µg/m3 2019-09-18 13:30:00
33827846          660.65   µg/m3 2019-01-14 16:30:00
33806829          619.94   µg/m3 2019-01-08 15:30:00
40154960          573.27   µg/m3 2016-07-16 18:30:00
40154961          564.37   µg/m3 2016-06-03 23:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR VALOR_ORIGINAL UNIDADE  \
0 2009-01-01 01:00:00  2009    1    1     1    NaN              *   µg/m3
1 2009-01-01 02:00:00  2009    1    1     2    NaN              *   µg/m3
2 2009-01-01 03:00:00  2009    1    1     3    NaN              *   µg/m3
3 2009-01-01 04:00:00  2009    1    1     4    NaN              *   µg/m3
4 2009-01-01 05:00:00  2009    1    1     5    NaN              *   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR VALOR_ORIGINAL UNIDADE  \
0 2009-01-01 01:00:00  2009    1    1     1    NaN              *   µg/m3
1 2009-01-01 02:00:00  2009    1    1     2    NaN              *   µg/m3
2 2009-01-01 03:00:00  2009    1    1     3    NaN              *   µg/m3
3 2009-01-01 04:00:00  2009    1    1     4    NaN              *   µg/m3
4 2009-01-01 05:00:00  2009    1    1     5    NaN              *   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
001
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/MP10/RJ0060RA001.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
25341374      512.397900   ug/m3 2017-05-03 19:00:00
27374360      353.182000   ug/m3 2015-07-01 00:30:00
27374159      293.544000   ug/m3 2015-06-21 19:30:00
29280741      263.844000   ug/m3 2016-04-13 20:30:00
30813782      221.450168   µg/m3 2020-01-08 17:00:00
mma
             DATETIME     ANO   MES   DIA  HORA  VALOR  VALOR_ORIGINAL  \
0 2008-12-15 00:00:00  2008.0  12.0  15.0   0.0  11.56           11.56
1 2008-12-15 01:00:00  2008.0  12.0  15.0   1.0   5.42            5.42
2 2008-12-15 02:00:00  2008.0  12.0  15.0   2.0   9.69            9.69
3 2008-12-15 03:00:00  2008.0  12.0  15.0   3.0   9.62            9.62
4 2008-12-15 04:00:00  2008.0  12.0  15.0   4.0  14.85           14.85

  UNIDADE  QAQC_INTERNO  QAQC_MMA
0   µg/m³          True      True
1   µg/m³          True      True
2   µg/m³          True      True
3   µg/m³          True      True
4   µg/m³          True      True
final
             DATETIME     ANO   MES   DIA  HORA  VALOR  VALOR_ORIGINAL  \
0 2008-12-15 00:00:00  2008.0  12.0  15.0   0.0  11.56           11.56
1 2008-12-15 01:00:00  2008.0  12.0  15.0   1.0   5.42            5.42
2 2008-12-15 02:00:00  2008.0  12.0  15.0   2.0   9.69            9.69
3 2008-12-15 03:00:00  2008.0  12.0  15.0   3.0   9.62            9.62
4 2008-12-15 04:00:00  2008.0  12.0  15.0   4.0  14.85           14.85

  UNIDADE  QAQC_INTERNO  QAQC_MMA
0   µg/m³          True      True
1   µg/m³          True      True
2   µg/m³          True      True
3   µg/m³          True      True
4   µg/m³          True      True
001
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/MP10/MG0045RA001.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
36453861           789.0   µg/m3 2018-05-17 12:30:00
36673032           665.0   µg/m3 2018-07-25 22:30:00
38198481           588.0   µg/m3 2021-09-21 19:30:00
38170416           552.0   µg/m3 2021-09-14 18:30:00
36612371           525.0   µg/m3 2018-07-06 19:30:00
mma
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2017-01-01 01:00:00  2017.0  1.0  1.0   1.0    NaN             NaN   µg/m3
1 2017-01-01 02:00:00  2017.0  1.0  1.0   2.0    NaN             NaN   µg/m3
2 2017-01-01 03:00:00  2017.0  1.0  1.0   3.0    NaN             NaN   µg/m3
3 2017-01-01 04:00:00  2017.0  1.0  1.0   4.0    NaN             NaN   µg/m3
4 2017-01-01 05:00:00  2017.0  1.0  1.0   5.0    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2017-01-01 01:00:00  2017.0  1.0  1.0   1.0    NaN             NaN   µg/m3
1 2017-01-01 02:00:00  2017.0  1.0  1.0   2.0    NaN             NaN   µg/m3
2 2017-01-01 03:00:00  2017.0  1.0  1.0   3.0    NaN             NaN   µg/m3
3 2017-01-01 04:00:00  2017.0  1.0  1.0   4.0    NaN             NaN   µg/m3
4 2017-01-01 05:00:00  2017.0  1.0  1.0   5.0    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
001
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/MP10/MG0029RA001.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
34414918           714.0   µg/m3 2019-07-03 12:30:00
36149850           497.0   µg/m3 2018-02-08 10:30:00
34462682           489.0   µg/m3 2019-07-16 12:30:00
36946723           484.0   µg/m3 2018-10-17 08:30:00
38600172           480.0   µg/m3 2022-01-07 15:30:00
mma
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2015-01-01 01:00:00  2015.0  1.0  1.0   1.0    NaN             NaN   µg/m3
1 2015-01-01 02:00:00  2015.0  1.0  1.0   2.0  41.75           41.75   µg/m3
2 2015-01-01 03:00:00  2015.0  1.0  1.0   3.0  48.10           48.10   µg/m3
3 2015-01-01 04:00:00  2015.0  1.0  1.0   4.0  37.84           37.84   µg/m3
4 2015-01-01 05:00:00  2015.0  1.0  1.0   5.0  68.12           68.12   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2015-01-01 01:00:00  2015.0  1.0  1.0   1.0    NaN             NaN   µg/m3
1 2015-01-01 02:00:00  2015.0  1.0  1.0   2.0  41.75           41.75   µg/m3
2 2015-01-01 03:00:00  2015.0  1.0  1.0   3.0  48.10           48.10   µg/m3
3 2015-01-01 04:00:00  2015.0  1.0  1.0   4.0  37.84           37.84   µg/m3
4 2015-01-01 05:00:00  2015.0  1.0  1.0   5.0  68.12           68.12   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True      True
2          True      True
3          True      True
4          True      True
001
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/MP10/RJ0034RA001.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
25144142           985.0   ug/m3 2017-03-22 13:00:00
25144143           985.0   ug/m3 2017-03-22 14:00:00
19547279           586.0   µg/m3 2019-01-07 10:00:00
19535390           576.0   µg/m3 2019-01-04 09:00:00
19831597           574.0   µg/m3 2019-03-19 04:00:00
mma
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2004-03-01 12:00:00  2004.0  3.0  1.0  12.0    NaN             NaN   µg/m³
1 2004-03-01 13:00:00  2004.0  3.0  1.0  13.0    NaN             NaN   µg/m³
2 2004-03-01 14:00:00  2004.0  3.0  1.0  14.0    NaN             NaN   µg/m³
3 2004-03-01 15:00:00  2004.0  3.0  1.0  15.0    NaN             NaN   µg/m³
4 2004-03-01 16:00:00  2004.0  3.0  1.0  16.0    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0         False     False
1         False     False
2         False     False
3         False     False
4         False     False
final
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2004-03-01 12:00:00  2004.0  3.0  1.0  12.0    NaN             NaN   µg/m³
1 2004-03-01 13:00:00  2004.0  3.0  1.0  13.0    NaN             NaN   µg/m³
2 2004-03-01 14:00:00  2004.0  3.0  1.0  14.0    NaN             NaN   µg/m³
3 2004-03-01 15:00:00  2004.0  3.0  1.0  15.0    NaN             NaN   µg/m³
4 2004-03-01 16:00:00  2004.0  3.0  1.0  16.0    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
001
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/MP10/MG0063RA001.csv
iema
          VALOR_ORIGINAL UNIDADE            DATETIME
39330733           135.0   µg/m3 2022-08-03 18:30:00
39390547           129.0   µg/m3 2022-08-19 18:30:00
39472537           122.0   µg/m3 2022-09-10 18:30:00
39356468           120.0   µg/m3 2022-08-10 16:30:00
39257424           114.0   µg/m3 2022-07-14 19:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2022-01-01 01:00:00  2022    1    1     1    NaN             NaN   µg/m3
1 2022-01-01 02:00:00  2022    1    1     2    NaN             NaN   µg/m3
2 2022-01-01 03:00:00  2022    1    1     3    NaN             NaN   µg/m3
3 2022-01-01 04:00:00  2022    1    1     4    NaN             NaN   µg/m3
4 2022-01-01 05:00:00  2022    1    1     5    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2022-01-01 01:00:00  2022    1    1     1    NaN             NaN   µg/m3
1 2022-01-01 02:00:00  2022    1    1     2    NaN             NaN   µg/m3
2 2022-01-01 03:00:00  2022    1    1     3    NaN             NaN   µg/m3
3 2022-01-01 04:00:00  2022    1    1     4    NaN             NaN   µg/m3
4 2022-01-01 05:00:00  2022    1    1     5    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

001
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/MP10/SP0067RA001.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
7408336            517.0   ug/m3 2017-09-21 16:00:00
12192104           451.0   ug/m3 2016-10-12 23:55:00
12189896           369.0   ug/m3 2016-07-11 06:00:00
11473880           309.0   ug/m3 2021-09-08 16:00:00
12190349           280.0   ug/m3 2016-07-30 05:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2000-01-28 19:00:00  2000    1   28    19   29.0            29.0   µg/m3
1 2000-01-28 20:00:00  2000    1   28    20   26.0            26.0   µg/m3
2 2000-01-28 21:00:00  2000    1   28    21   28.0            28.0   µg/m3
3 2000-01-28 22:00:00  2000    1   28    22   25.0            25.0   µg/m3
4 2000-01-28 23:00:00  2000    1   28    23   30.0            30.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2000-01-28 19:00:00  2000    1   28    19   29.0            29.0   µg/m3
1 2000-01-28 20:00:00  2000    1   28    20   26.0            26.0   µg/m3
2 2000-01-28 21:00:00  2000    1   28    21   28.0            28.0   µg/m3
3 2000-01-28 22:00:00  2000    1   28    22   25.0            25.0   µg/m3
4 2000-01-28 23:00:00  2000    1   28    23   30.0            30.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
001
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/MP10/SP0073RA001.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
14214534           238.0   ug/m3 2016-09-27 11:00:00
19090679           225.0   ug/m3 2015-09-25 14:00:00
9492439            224.0   ug/m3 2018-05-17 15:00:00
12547761           214.0   ug/m3 2020-10-02 20:00:00
15745348           197.0   ug/m3 2021-09-15 12:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1998-01-01 01:00:00  1998    1    1     1   62.0            62.0   µg/m3
1 1998-01-01 02:00:00  1998    1    1     2   83.0            83.0   µg/m3
2 1998-01-01 03:00:00  1998    1    1     3   43.0            43.0   µg/m3
3 1998-01-01 04:00:00  1998    1    1     4   30.0            30.0   µg/m3
4 1998-01-01 05:00:00  1998    1    1     5   23.0            23.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1998-01-01 01:00:00  1998    1    1     1   62.0            62.0   µg/m3
1 1998-01-01 02:00:00  1998    1    1     2   83.0            83.0   µg/m3
2 1998-01-01 03:00:00  1998    1    1     3   43.0            43.0   µg/m3
3 1998-01-01 04:00:00  1998    1    1     4   30.0            30.0   µg/m3
4 1998-01-01 05:00:00  1998    1    1     5   23.0            23.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
001
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/MP10/RJ0058RA001.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
19582751          598.50   µg/m3 2019-01-16 16:00:00
23602272          596.69   µg/m3 2020-08-15 14:00:00
23602055          582.40   µg/m3 2020-08-15 13:00:00
19552264          580.80   µg/m3 2019-01-08 17:00:00
19552104          570.50   µg/m3 2019-01-08 16:00:00
mma
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2008-07-01 00:00:00  2008.0  7.0  1.0   0.0    NaN             0.0   µg/m³
1 2008-07-01 01:00:00  2008.0  7.0  1.0   1.0    NaN             NaN   µg/m³
2 2008-07-01 02:00:00  2008.0  7.0  1.0   2.0    NaN             NaN   µg/m³
3 2008-07-01 03:00:00  2008.0  7.0  1.0   3.0    NaN             NaN   µg/m³
4 2008-07-01 04:00:00  2008.0  7.0  1.0   4.0    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1         False     False
2         False     False
3         False     False
4         False     False
final
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2008-07-01 00:00:00  2008.0  7.0  1.0   0.0    NaN             0.0   µg/m³
1 2008-07-01 01:00:00  2008.0  7.0  1.0   1.0    NaN             NaN   µg/m³
2 2008-07-01 02:00:00  2008.0  7.0  1.0   2.0    NaN             NaN   µg/m³
3 2008-07-01 03:00:00  2008.0  7.0  1.0   3.0    NaN             NaN   µg/m³
4 2008-07-01 04:00:00  2008.0  7.0  1.0   4.0    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
001
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/MP10/RJ0071RA001.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
21547540         575.407   ug/m3 2015-08-15 19:30:00
20031119         410.000   µg/m3 2019-05-07 11:00:00
21547539         319.212   ug/m3 2015-08-15 17:30:00
20168961         313.000   µg/m3 2019-06-09 09:00:00
21547541         300.867   ug/m3 2015-08-15 20:30:00
mma
             DATETIME     ANO   MES   DIA  HORA  VALOR  VALOR_ORIGINAL  \
0 2000-12-21 06:00:00  2000.0  12.0  21.0   6.0  13.68           13.68
1 2000-12-21 07:00:00  2000.0  12.0  21.0   7.0  12.27           12.27
2 2000-12-21 08:00:00  2000.0  12.0  21.0   8.0  14.21           14.21
3 2000-12-21 09:00:00  2000.0  12.0  21.0   9.0  18.20           18.20
4 2000-12-21 10:00:00  2000.0  12.0  21.0  10.0  25.54           25.54

  UNIDADE  QAQC_INTERNO  QAQC_MMA
0   µg/m³          True      True
1   µg/m³          True      True
2   µg/m³          True      True
3   µg/m³          True      True
4   µg/m³          True      True
final
             DATETIME     ANO   MES   DIA  HORA  VALOR  VALOR_ORIGINAL  \
0 2000-12-21 06:00:00  2000.0  12.0  21.0   6.0  13.68           13.68
1 2000-12-21 07:00:00  2000.0  12.0  21.0   7.0  12.27           12.27
2 2000-12-21 08:00:00  2000.0  12.0  21.0   8.0  14.21           14.21
3 2000-12-21 09:00:00  2000.0  12.0  21.0   9.0  18.20           18.20
4 2000-12-21 10:00:00  2000.0  12.0  21.0  10.0  25.54           25.54

  UNIDADE  QAQC_INTERNO  QAQC_MMA
0   µg/m³          True      True
1   µg/m³          True      True
2   µg/m³          True      True
3   µg/m³          True      True
4   µg/m³          True      True
001
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/MP10/RJ0069RA001.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
24857112      584.108900   ug/m3 2017-05-09 20:00:00
31591540      408.796142   µg/m3 2020-06-19 13:00:00
29146425      345.000000   µg/m3 2019-12-30 03:00:00
24857113      325.945100   ug/m3 2017-05-09 21:00:00
24857248      317.301100   ug/m3 2017-05-15 14:00:00
mma
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1999-01-05 12:00:00  1999.0  1.0  5.0  12.0   37.8            37.8   µg/m³
1 1999-01-05 13:00:00  1999.0  1.0  5.0  13.0    NaN             NaN   µg/m³
2 1999-01-05 14:00:00  1999.0  1.0  5.0  14.0    NaN             NaN   µg/m³
3 1999-01-05 15:00:00  1999.0  1.0  5.0  15.0    NaN             NaN   µg/m³
4 1999-01-05 16:00:00  1999.0  1.0  5.0  16.0    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1         False     False
2         False     False
3         False     False
4         False     False
final
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1999-01-05 12:00:00  1999.0  1.0  5.0  12.0   37.8            37.8   µg/m³
1 1999-01-05 13:00:00  1999.0  1.0  5.0  13.0    NaN             NaN   µg/m³
2 1999-01-05 14:00:00  1999.0  1.0  5.0  14.0    NaN             NaN   µg/m³
3 1999-01-05 15:00:00  1999.0  1.0  5.0  15.0    NaN             NaN   µg/m³
4 1999-01-05 16:00:00  1999.0  1.0  5.0  16.0    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True     False
2          True     False
3          True     False
4          True     False
001
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/MP10/BA0003ND001.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
         VALOR_ORIGINAL UNIDADE            DATETIME
5266997           304.2   ug/m3 2017-06-24 01:00:00
5266998           284.3   ug/m3 2017-06-24 02:00:00
5266995           248.9   ug/m3 2017-06-23 23:00:00
5470450           243.9   ug/m3 2015-06-24 00:00:00
5266999           239.5   ug/m3 2017-06-24 03:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1998-01-01 00:00:00  1998    1    1     0    NaN             NaN   ug/m³
1 1998-01-01 01:00:00  1998    1    1     1    NaN             NaN   ug/m³
2 1998-01-01 02:00:00  1998    1    1     2    NaN             NaN   ug/m³
3 1998-01-01 03:00:00  1998    1    1     3    NaN             NaN   ug/m³
4 1998-01-01 04:00:00  1998    1    1     4    NaN             NaN   ug/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1998-01-01 00:00:00  1998    1    1     0    NaN             NaN   ug/m³
1 1998-01-01 01:00:00  1998    1    1     1    NaN             NaN   ug/m³
2 1998-01-01 02:00:00  1998    1    1     2    NaN             NaN   ug/m³
3 1998-01-01 03:00:00  1998    1    1     3    NaN             NaN   ug/m³
4 1998-01-01 04:00:00  1998    1    1     4    NaN             NaN   ug/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
001
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/MP10/MG0026RA001.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
37641192           833.0   µg/m3 2021-05-05 08:30:00
37660200           603.0   µg/m3 2021-05-10 08:30:00
37641034           492.0   µg/m3 2021-05-05 07:30:00
34169099           452.0   µg/m3 2019-04-25 12:30:00
39489478           412.0   µg/m3 2022-09-15 09:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2015-01-01 01:00:00  2015    1    1     1   10.0            10.0   µg/m3
1 2015-01-01 02:00:00  2015    1    1     2   10.0            10.0   µg/m3
2 2015-01-01 03:00:00  2015    1    1     3   17.0            17.0   µg/m3
3 2015-01-01 04:00:00  2015    1    1     4   10.0            10.0   µg/m3
4 2015-01-01 05:00:00  2015    1    1     5   12.0            12.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2015-01-01 01:00:00  2015    1    1     1   10.0            10.0   µg/m3
1 2015-01-01 02:00:00  2015    1    1     2   10.0            10.0   µg/m3
2 2015-01-01 03:00:00  2015    1    1     3   17.0            17.0   µg/m3
3 2015-01-01 04:00:00  2015    1    1     4   10.0            10.0   µg/m3
4 2015-01-01 05:00:00  2015    1    1     5   12.0            12.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
001
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/MP10/MG0030RA001.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
39381494           562.0   µg/m3 2022-08-17 07:30:00
40644877           544.0   µg/m3 2016-10-18 19:30:00
39220741           541.0   µg/m3 2022-07-04 10:30:00
40644879           523.0   µg/m3 2016-10-18 23:30:00
33666606           453.0   µg/m3 2015-10-04 00:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2015-01-01 01:00:00  2015    1    1     1    NaN             NaN   µg/m3
1 2015-01-01 02:00:00  2015    1    1     2   16.0            16.0   µg/m3
2 2015-01-01 03:00:00  2015    1    1     3   20.0            20.0   µg/m3
3 2015-01-01 04:00:00  2015    1    1     4   12.0            12.0   µg/m3
4 2015-01-01 05:00:00  2015    1    1     5   19.0            19.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2015-01-01 01:00:00  2015    1    1     1    NaN             NaN   µg/m3
1 2015-01-01 02:00:00  2015    1    1     2   16.0            16.0   µg/m3
2 2015-01-01 03:00:00  2015    1    1     3   20.0            20.0   µg/m3
3 2015-01-01 04:00:00  2015    1    1     4   12.0            12.0   µg/m3
4 2015-01-01 05:00:00  2015    1    1     5   19.0            19.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True      True
2          True      True
3          True      True
4          True      True
001
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/MP10/SP0063RA001.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
12014915           270.0   ug/m3 2016-12-24 13:00:00
17537746           261.0   ug/m3 2015-08-09 09:00:00
17537517           220.0   ug/m3 2015-07-30 15:00:00
12012874           199.0   ug/m3 2016-09-30 10:00:00
17533608           194.0   ug/m3 2015-01-18 19:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1998-01-01 01:00:00  1998    1    1     1   62.0            62.0   µg/m3
1 1998-01-01 02:00:00  1998    1    1     2  130.0           130.0   µg/m3
2 1998-01-01 03:00:00  1998    1    1     3   71.0            71.0   µg/m3
3 1998-01-01 04:00:00  1998    1    1     4   59.0            59.0   µg/m3
4 1998-01-01 05:00:00  1998    1    1     5   62.0            62.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1998-01-01 01:00:00  1998    1    1     1   62.0            62.0   µg/m3
1 1998-01-01 02:00:00  1998    1    1     2  130.0           130.0   µg/m3
2 1998-01-01 03:00:00  1998    1    1     3   71.0            71.0   µg/m3
3 1998-01-01 04:00:00  1998    1    1     4   59.0            59.0   µg/m3
4 1998-01-01 05:00:00  1998    1    1     5   62.0            62.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
001
001
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/MP10/SP0111RA001.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
13026709           596.0   ug/m3 2020-10-07 02:00:00
13026708           576.0   ug/m3 2020-10-07 01:00:00
13026710           482.0   ug/m3 2020-10-07 03:00:00
13026711           343.0   ug/m3 2020-10-07 04:00:00
16250729           326.0   ug/m3 2021-08-12 20:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2008-04-30 02:00:00  2008    4   30     2    6.0             6.0   µg/m3
1 2008-04-30 03:00:00  2008    4   30     3    5.0             5.0   µg/m3
2 2008-04-30 04:00:00  2008    4   30     4    2.0             2.0   µg/m3
3 2008-04-30 05:00:00  2008    4   30     5    3.0             3.0   µg/m3
4 2008-04-30 06:00:00  2008    4   30     6    2.0             2.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2008-04-30 02:00:00  2008    4   30     2    6.0             6.0   µg/m3
1 2008-04-30 03:00:00  2008    4   30     3    5.0             5.0   µg/m3
2 2008-04-30 04:00:00  2008    4   30     4    2.0             2.0   µg/m3
3 2008-04-30 05:00:00  2008    4   30     5    3.0             3.0   µg/m3
4 2008-04-30 06:00:00  2008    4   30     6    2.0             2.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
O3
['RJ0050', 'SP0259', 'RJ0032', 'SP0266', 'RJ0022', 'PR0009 ', 'MG0008', 'PR0006 ', 'PR0005 ', 'MG0036', 'RJ0048', 'MG0009', 'SP0284', 'RJ0228', 'SP0086', 'RJ0037', 'SP0290', 'RJ0021', 'BA0005', 'SP0288', 'RJ0227', 'RJ0045', nan, 'MG0039', 'RJ0079', 'RJ0055', 'RJ0226', 'SP0092', 'SP0258', 'RJ0063', 'SP0116', 'RJ0043', 'SP0289', 'RJ0044', 'PR0003 ', 'MG0001', 'MG0006', 'SP0085', 'MG0011', 'RJ0018', 'MG0002', 'MG0057', 'SP0262', 'BA0006', 'RJ0036', 'RJ0081', 'SP0106', 'MG0012', 'PR0011 ', 'SP0263', 'SP0109', 'SP0097', 'RJ0019', 'CE0001', 'SP0293', 'SP0256', 'SP0083', 'RJ0025', 'BA0011', 'RJ0225', 'RJ0070', 'MG0017', 'MG0010', 'RJ0038', 'RJ0051', 'SP0269', 'PR0004 ', 'RJ0057', 'RJ0027', 'RJ0078', 'RJ0033', 'BA0001', 'RJ0222', 'MG0013', 'MG0004', 'SP0110', 'RJ0031', 'PR0015 ', 'RJ0064', 'SP0065', 'MG0055', 'SP0114', 'PR0008 ', 'RJ0054', 'RJ0030', 'RJ0020', 'RJ0029', 'SP0113', 'SP0107', 'MG0003', 'SP0281', 'RJ0039', 'RJ0223', 'PR0007 ', 'RJ0023', 'MG0035', 'SP0248', 'SP0064', 'BA0004', 'MG0053', 'SP0117', 'SP0280', 'RJ0024', 'RJ0229', 'PR0012 ', 'SP0108', 'RJ0026', 'SP0099', 'MG0005', 'RJ0060', 'RJ0034', 'SP0067', 'RJ0058', 'PR0002 ', 'RJ0071', 'SP0063', 'RJ0069', 'BA0010', 'RJ0224', 'SP0111']
005
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/O3/RJ0050RA005.csv
iema
          VALOR_ORIGINAL UNIDADE            DATETIME
24149267        433.7110   µg/m3 2020-12-03 14:00:00
23478699        345.4866   µg/m3 2020-07-22 11:00:00
23938992        302.3419   µg/m3 2020-10-21 13:00:00
23797254        262.9732   µg/m3 2020-09-23 10:00:00
23797459        189.1584   µg/m3 2020-09-23 11:00:00
mma
             DATETIME     ANO   MES   DIA  HORA  VALOR  VALOR_ORIGINAL  \
0 2018-10-18 15:00:00  2018.0  10.0  18.0  15.0    NaN             NaN
1 2018-10-18 16:00:00  2018.0  10.0  18.0  16.0    NaN             NaN
2 2018-10-18 17:00:00  2018.0  10.0  18.0  17.0    NaN             NaN
3 2018-10-18 18:00:00  2018.0  10.0  18.0  18.0    NaN             NaN
4 2018-10-18 19:00:00  2018.0  10.0  18.0  19.0    NaN             NaN

  UNIDADE  QAQC_INTERNO  QAQC_MMA
0   µg/m³         False     False
1   µg/m³         False     False
2   µg/m³         False     False
3   µg/m³         False     False
4   µg/m³         False     False
final
             DATETIME     ANO   MES   DIA  HORA  VALOR  VALOR_ORIGINAL  \
0 2018-10-18 15:00:00  2018.0  10.0  18.0  15.0    NaN             NaN
1 2018-10-18 16:00:00  2018.0  10.0  18.0  16.0    NaN             NaN
2 2018-10-18 17:00:00  2018.0  10.0  18.0  17.0    NaN             NaN
3 2018-10-18 18:00:00  2018.0  10.0  18.0  18.0    NaN             NaN
4 2018-10-18 19:00:00  2018.0  10.0  18.0  19.0    NaN             NaN

  UNIDADE  QAQC_INTERNO  QAQC_MMA
0   µg/m³          True     False
1   µg/m³          True     False
2   µg/m³          True     False
3   µg/m³          True     False
4   µg/m³          True     False

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

005
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/O3/SP0259RA005.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
8986695            273.0   ug/m3 2022-10-06 10:00:00
18626332           220.0   ug/m3 2017-09-18 15:00:00
19447157           213.0   ug/m3 2015-09-23 13:00:00
18626287           210.0   ug/m3 2017-09-16 16:00:00
14554916           207.0   ug/m3 2016-04-07 17:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2011-01-01 01:00:00  2011    1    1     1   25.0            25.0   µg/m3
1 2011-01-01 02:00:00  2011    1    1     2   35.0            35.0   µg/m3
2 2011-01-01 03:00:00  2011    1    1     3   36.0            36.0   µg/m3
3 2011-01-01 04:00:00  2011    1    1     4   33.0            33.0   µg/m3
4 2011-01-01 05:00:00  2011    1    1     5   30.0            30.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2011-01-01 01:00:00  2011    1    1     1   25.0            25.0   µg/m3
1 2011-01-01 02:00:00  2011    1    1     2   35.0            35.0   µg/m3
2 2011-01-01 03:00:00  2011    1    1     3   36.0            36.0   µg/m3
3 2011-01-01 04:00:00  2011    1    1     4   33.0            33.0   µg/m3
4 2011-01-01 05:00:00  2011    1    1     5   30.0            30.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
005
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/O3/RJ0032RA005.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
19535807      400.590773   µg/m3 2019-01-04 12:00:00
20161402      325.442411   µg/m3 2019-06-07 16:00:00
19535686      314.625721   µg/m3 2019-01-04 11:00:00
20161218      310.779709   µg/m3 2019-06-07 15:00:00
20161589      305.516046   µg/m3 2019-06-07 17:00:00
mma
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2004-03-01 12:00:00  2004.0  3.0  1.0  12.0    NaN             NaN   µg/m³
1 2004-03-01 13:00:00  2004.0  3.0  1.0  13.0    NaN             NaN   µg/m³
2 2004-03-01 14:00:00  2004.0  3.0  1.0  14.0    NaN             NaN   µg/m³
3 2004-03-01 15:00:00  2004.0  3.0  1.0  15.0    NaN             NaN   µg/m³
4 2004-03-01 16:00:00  2004.0  3.0  1.0  16.0    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0         False     False
1         False     False
2         False     False
3         False     False
4         False     False
final
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2004-03-01 12:00:00  2004.0  3.0  1.0  12.0    NaN             NaN   µg/m³
1 2004-03-01 13:00:00  2004.0  3.0  1.0  13.0    NaN             NaN   µg/m³
2 2004-03-01 14:00:00  2004.0  3.0  1.0  14.0    NaN             NaN   µg/m³
3 2004-03-01 15:00:00  2004.0  3.0  1.0  15.0    NaN             NaN   µg/m³
4 2004-03-01 16:00:00  2004.0  3.0  1.0  16.0    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
005
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/O3/SP0266RA005.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
18603221           268.0   ug/m3 2017-11-24 16:00:00
19415300           247.0   ug/m3 2015-02-03 17:00:00
12877198           239.0   ug/m3 2020-12-04 11:00:00
13706553           235.0   ug/m3 2019-02-08 17:00:00
19415299           232.0   ug/m3 2015-02-03 16:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2012-07-03 01:00:00  2012    7    3     1    NaN             0.0   µg/m3
1 2012-07-03 02:00:00  2012    7    3     2    NaN             0.0   µg/m3
2 2012-07-03 03:00:00  2012    7    3     3    NaN             0.0   µg/m3
3 2012-07-03 04:00:00  2012    7    3     4    NaN             0.0   µg/m3
4 2012-07-03 05:00:00  2012    7    3     5    NaN             0.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2012-07-03 01:00:00  2012    7    3     1    NaN             0.0   µg/m3
1 2012-07-03 02:00:00  2012    7    3     2    NaN             0.0   µg/m3
2 2012-07-03 03:00:00  2012    7    3     3    NaN             0.0   µg/m3
3 2012-07-03 04:00:00  2012    7    3     4    NaN             0.0   µg/m3
4 2012-07-03 05:00:00  2012    7    3     5    NaN             0.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
005
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/O3/RJ0022RA005.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
23743965        162.7485   µg/m3 2020-09-12 14:00:00
29532258        153.8640   ug/m3 2016-03-17 12:30:00
29531600        133.7620   ug/m3 2016-02-17 13:30:00
23744177        131.9264   µg/m3 2020-09-12 15:00:00
29532032        129.8920   ug/m3 2016-03-06 14:30:00
mma
             DATETIME     ANO  MES   DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2000-07-26 08:00:00  2000.0  7.0  26.0   8.0   0.20            0.20   µg/m³
1 2000-07-26 09:00:00  2000.0  7.0  26.0   9.0   0.23            0.23   µg/m³
2 2000-07-26 10:00:00  2000.0  7.0  26.0  10.0   0.20            0.20   µg/m³
3 2000-07-26 11:00:00  2000.0  7.0  26.0  11.0   0.20            0.20   µg/m³
4 2000-07-26 12:00:00  2000.0  7.0  26.0  12.0   0.20            0.20   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME     ANO  MES   DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2000-07-26 08:00:00  2000.0  7.0  26.0   8.0   0.20            0.20   µg/m³
1 2000-07-26 09:00:00  2000.0  7.0  26.0   9.0   0.23            0.23   µg/m³
2 2000-07-26 10:00:00  2000.0  7.0  26.0  10.0   0.20            0.20   µg/m³
3 2000-07-26 11:00:00  2000.0  7.0  26.0  11.0   0.20            0.20   µg/m³
4 2000-07-26 12:00:00  2000.0  7.0  26.0  12.0   0.20            0.20   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
005
005
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/O3/MG0008RA005.csv

/tmp/ipykernel_273420/1352582357.py:97: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  df_mma = pd.read_csv(arquivo, encoding = 'UTF-8')
/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
34061064          318.14   µg/m3 2019-03-24 14:30:00
32964618          244.92   µg/m3 2015-11-29 14:30:00
32964619          239.59   µg/m3 2015-11-20 12:30:00
32964620          220.78   µg/m3 2015-04-21 12:30:00
32964621          213.11   µg/m3 2015-11-29 13:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR VALOR_ORIGINAL UNIDADE  \
0 2013-01-01 01:00:00  2013    1    1     1   18.0             18     ppb
1 2013-01-01 02:00:00  2013    1    1     2   14.0             14     ppb
2 2013-01-01 03:00:00  2013    1    1     3   18.0             18     ppb
3 2013-01-01 04:00:00  2013    1    1     4   16.0             16     ppb
4 2013-01-01 05:00:00  2013    1    1     5   19.0             19     ppb

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR VALOR_ORIGINAL UNIDADE  \
0 2013-01-01 01:00:00  2013    1    1     1   18.0             18     ppb
1 2013-01-01 02:00:00  2013    1    1     2   14.0             14     ppb
2 2013-01-01 03:00:00  2013    1    1     3   18.0             18     ppb
3 2013-01-01 04:00:00  2013    1    1     4   16.0             16     ppb
4 2013-01-01 05:00:00  2013    1    1     5   19.0             19     ppb

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
005
005
005
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/O3/MG0036RA005.csv
iema
          VALOR_ORIGINAL UNIDADE            DATETIME
37669079           516.6   µg/m3 2021-05-12 16:30:00
38154171           215.7   µg/m3 2021-09-10 16:30:00
38186252           215.6   µg/m3 2021-09-18 17:30:00
38186083           214.4   µg/m3 2021-09-18 16:30:00
38154015           209.3   µg/m3 2021-09-10 15:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2017-08-22 17:00:00  2017    8   22    17    NaN             NaN   µg/m3
1 2017-08-22 18:00:00  2017    8   22    18   23.6            23.6   µg/m3
2 2017-08-22 19:00:00  2017    8   22    19   23.1            23.1   µg/m3
3 2017-08-22 20:00:00  2017    8   22    20   21.7            21.7   µg/m3
4 2017-08-22 21:00:00  2017    8   22    21   21.4            21.4   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2017-08-22 17:00:00  2017    8   22    17    NaN             NaN   µg/m3
1 2017-08-22 18:00:00  2017    8   22    18   23.6            23.6   µg/m3
2 2017-08-22 19:00:00  2017    8   22    19   23.1            23.1   µg/m3
3 2017-08-22 20:00:00  2017    8   22    20   21.7            21.7   µg/m3
4 2017-08-22 21:00:00  2017    8   22    21   21.4            21.4   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True      True
2          True      True
3          True      True
4          True      True

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

005
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/O3/RJ0048RA005.csv
iema
          VALOR_ORIGINAL UNIDADE            DATETIME
22775914          132.80   ug/m3 2022-06-25 16:00:00
22775913          126.72   ug/m3 2022-06-25 15:00:00
24477135          123.77   µg/m³ 2021-09-21 17:00:00
22775915          121.57   ug/m3 2022-06-25 17:00:00
22776720          120.90   ug/m3 2022-07-29 17:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2019-09-17 16:00:00  2019    9   17    16    NaN             NaN   µg/m³
1 2019-09-17 17:00:00  2019    9   17    17    NaN             NaN   µg/m³
2 2019-09-17 18:00:00  2019    9   17    18    NaN             NaN   µg/m³
3 2019-09-17 19:00:00  2019    9   17    19    NaN             NaN   µg/m³
4 2019-09-17 20:00:00  2019    9   17    20    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0         False     False
1         False     False
2         False     False
3         False     False
4         False     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2019-09-17 16:00:00  2019    9   17    16    NaN             NaN   µg/m³
1 2019-09-17 17:00:00  2019    9   17    17    NaN             NaN   µg/m³
2 2019-09-17 18:00:00  2019    9   17    18    NaN             NaN   µg/m³
3 2019-09-17 19:00:00  2019    9   17    19    NaN             NaN   µg/m³
4 2019-09-17 20:00:00  2019    9   17    20    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

005
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/O3/MG0009RA005.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
33375629          185.14   µg/m3 2015-11-05 14:30:00
33375630          183.48   µg/m3 2015-11-05 15:30:00
33375631          181.13   µg/m3 2015-11-13 10:30:00
33375632          177.47   µg/m3 2015-11-05 16:30:00
33375633          174.65   µg/m3 2015-11-06 11:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2014-01-01 01:00:00  2014    1    1     1   4.82            4.82   µg/m3
1 2014-01-01 02:00:00  2014    1    1     2   4.70            4.70   µg/m3
2 2014-01-01 03:00:00  2014    1    1     3   4.57            4.57   µg/m3
3 2014-01-01 04:00:00  2014    1    1     4   4.93            4.93   µg/m3
4 2014-01-01 05:00:00  2014    1    1     5   4.67            4.67   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2014-01-01 01:00:00  2014    1    1     1   4.82            4.82   µg/m3
1 2014-01-01 02:00:00  2014    1    1     2   4.70            4.70   µg/m3
2 2014-01-01 03:00:00  2014    1    1     3   4.57            4.57   µg/m3
3 2014-01-01 04:00:00  2014    1    1     4   4.93            4.93   µg/m3
4 2014-01-01 05:00:00  2014    1    1     5   4.67            4.67   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
005
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/O3/SP0284RA005.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
         VALOR_ORIGINAL UNIDADE            DATETIME
7765947           290.0   ug/m3 2019-10-14 15:00:00
7761682           282.0   ug/m3 2019-01-31 16:00:00
7766160           275.0   ug/m3 2019-10-25 12:00:00
7765946           259.0   ug/m3 2019-10-14 14:00:00
7761683           258.0   ug/m3 2019-01-31 17:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2016-07-20 01:00:00  2016    7   20     1    NaN             0.0   µg/m3
1 2016-07-20 02:00:00  2016    7   20     2    NaN             0.0   µg/m3
2 2016-07-20 03:00:00  2016    7   20     3    NaN             0.0   µg/m3
3 2016-07-20 04:00:00  2016    7   20     4    NaN             0.0   µg/m3
4 2016-07-20 05:00:00  2016    7   20     5    NaN             0.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2016-07-20 01:00:00  2016    7   20     1    NaN             0.0   ug/m3
1 2016-07-20 02:00:00  2016    7   20     2    NaN             0.0   ug/m3
2 2016-07-20 03:00:00  2016    7   20     3    NaN             0.0   ug/m3
3 2016-07-20 04:00:00  2016    7   20     4    NaN             0.0   ug/m3
4 2016-07-20 05:00:00  2016    7   20     5    NaN             0.0   ug/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
005
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/O3/RJ0228RA005.csv
iema
          VALOR_ORIGINAL UNIDADE            DATETIME
26891178            83.9     ppb 2015-10-16 13:30:00
26891179            83.4     ppb 2015-10-16 14:30:00
26891155            82.5     ppb 2015-10-15 14:30:00
26891154            81.5     ppb 2015-10-15 13:30:00
26890651            72.8     ppb 2015-09-24 13:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2013-04-18 16:00:00  2013    4   18    16    NaN             NaN   µg/m³
1 2013-04-18 17:00:00  2013    4   18    17    NaN             NaN   µg/m³
2 2013-04-18 18:00:00  2013    4   18    18    NaN             NaN   µg/m³
3 2013-04-18 19:00:00  2013    4   18    19    NaN             NaN   µg/m³
4 2013-04-18 20:00:00  2013    4   18    20  16.41           16.41   µg/m³

   QAQC_INTERNO  QAQC_MMA
0         False     False
1         False     False
2         False     False
3         False     False
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2013-04-18 16:00:00  2013    4   18    16    NaN             NaN   µg/m³
1 2013-04-18 17:00:00  2013    4   18    17    NaN             NaN   µg/m³
2 2013-04-18 18:00:00  2013    4   18    18    NaN             NaN   µg/m³
3 2013-04-18 19:00:00  2013    4   18    19    NaN             NaN   µg/m³
4 2013-04-18 20:00:00  2013    4   18    20  16.41           16.41   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True      True

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

005
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/O3/SP0086RA005.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
         VALOR_ORIGINAL UNIDADE            DATETIME
8171637           363.0   ug/m3 2019-01-31 13:00:00
7138495           270.0   ug/m3 2017-12-16 15:00:00
7138494           250.0   ug/m3 2017-12-16 14:00:00
8171636           244.0   ug/m3 2019-01-31 12:00:00
7138496           237.0   ug/m3 2017-12-16 16:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1998-01-14 15:00:00  1998    1   14    15  174.0           174.0   µg/m3
1 1998-01-14 16:00:00  1998    1   14    16  187.0           187.0   µg/m3
2 1998-01-14 17:00:00  1998    1   14    17  168.0           168.0   µg/m3
3 1998-01-14 18:00:00  1998    1   14    18  151.0           151.0   µg/m3
4 1998-01-14 19:00:00  1998    1   14    19  104.0           104.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1998-01-14 15:00:00  1998    1   14    15  174.0           174.0   µg/m3
1 1998-01-14 16:00:00  1998    1   14    16  187.0           187.0   µg/m3
2 1998-01-14 17:00:00  1998    1   14    17  168.0           168.0   µg/m3
3 1998-01-14 18:00:00  1998    1   14    18  151.0           151.0   µg/m3
4 1998-01-14 19:00:00  1998    1   14    19  104.0           104.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
005
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/O3/RJ0037RA005.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
25506406      479.786200   ug/m3 2017-09-20 14:00:00
25505291      309.808500   ug/m3 2017-08-02 11:00:00
25507394      303.821800   ug/m3 2017-11-01 14:00:00
31499453      207.038037   µg/m3 2020-06-01 13:00:00
31561289      206.527607   µg/m3 2020-06-13 14:00:00
mma
             DATETIME     ANO  MES   DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2011-08-26 10:00:00  2011.0  8.0  26.0  10.0  49.53           49.53   µg/m³
1 2011-08-26 11:00:00  2011.0  8.0  26.0  11.0  30.21           30.21   µg/m³
2 2011-08-26 12:00:00  2011.0  8.0  26.0  12.0  50.53           50.53   µg/m³
3 2011-08-26 13:00:00  2011.0  8.0  26.0  13.0  64.47           64.47   µg/m³
4 2011-08-26 14:00:00  2011.0  8.0  26.0  14.0  61.28           61.28   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME     ANO  MES   DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2011-08-26 10:00:00  2011.0  8.0  26.0  10.0  49.53           49.53   µg/m³
1 2011-08-26 11:00:00  2011.0  8.0  26.0  11.0  30.21           30.21   µg/m³
2 2011-08-26 12:00:00  2011.0  8.0  26.0  12.0  50.53           50.53   µg/m³
3 2011-08-26 13:00:00  2011.0  8.0  26.0  13.0  64.47           64.47   µg/m³
4 2011-08-26 14:00:00  2011.0  8.0  26.0  14.0  61.28           61.28   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
005
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/O3/SP0290RA005.csv
iema
          VALOR_ORIGINAL UNIDADE            DATETIME
15521550           203.0   ug/m3 2021-09-29 13:00:00
13097552           199.0   ug/m3 2019-10-03 16:00:00
12316153           197.0   ug/m3 2020-09-29 18:00:00
13097553           195.0   ug/m3 2019-10-03 17:00:00
13097554           194.0   ug/m3 2019-10-03 18:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2018-02-26 13:00:00  2018    2   26    13   45.0            45.0   µg/m3
1 2018-02-26 14:00:00  2018    2   26    14   39.0            39.0   µg/m3
2 2018-02-26 15:00:00  2018    2   26    15   27.0            27.0   µg/m3
3 2018-02-26 16:00:00  2018    2   26    16   28.0            28.0   µg/m3
4 2018-02-26 17:00:00  2018    2   26    17   20.0            20.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2018-02-26 13:00:00  2018    2   26    13   45.0            45.0   ug/m3
1 2018-02-26 14:00:00  2018    2   26    14   39.0            39.0   ug/m3
2 2018-02-26 15:00:00  2018    2   26    15   27.0            27.0   ug/m3
3 2018-02-26 16:00:00  2018    2   26    16   28.0            28.0   ug/m3
4 2018-02-26 17:00:00  2018    2   26    17   20.0            20.0   ug/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

005
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/O3/RJ0021RA005.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
31249433      185.325153   µg/m3 2020-04-11 20:00:00
23403406      135.263800   µg/m3 2020-07-07 16:00:00
23768317      129.177900   µg/m3 2020-09-17 13:00:00
27014847      125.274156   ug/m3 2015-10-08 14:30:00
23403199      120.736200   µg/m3 2020-07-07 15:00:00
mma
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1999-05-01 00:00:00  1999.0  5.0  1.0   0.0    NaN             0.0   µg/m³
1 1999-05-01 01:00:00  1999.0  5.0  1.0   1.0    NaN             0.0   µg/m³
2 1999-05-01 02:00:00  1999.0  5.0  1.0   2.0    NaN             0.0   µg/m³
3 1999-05-01 03:00:00  1999.0  5.0  1.0   3.0    NaN             0.0   µg/m³
4 1999-05-01 04:00:00  1999.0  5.0  1.0   4.0    NaN             0.0   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1999-05-01 00:00:00  1999.0  5.0  1.0   0.0    NaN             0.0   µg/m³
1 1999-05-01 01:00:00  1999.0  5.0  1.0   1.0    NaN             0.0   µg/m³
2 1999-05-01 02:00:00  1999.0  5.0  1.0   2.0    NaN             0.0   µg/m³
3 1999-05-01 03:00:00  1999.0  5.0  1.0   3.0    NaN             0.0   µg/m³
4 1999-05-01 04:00:00  1999.0  5.0  1.0   4.0    NaN             0.0   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
005
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/O3/BA0005ND005.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
         VALOR_ORIGINAL UNIDADE            DATETIME
5336941      496.035635   ug/m3 2017-12-13 11:00:00
5336942      496.035635   ug/m3 2017-12-13 12:00:00
5336939      496.035635   ug/m3 2017-12-13 09:00:00
5336940      496.035635   ug/m3 2017-12-13 10:00:00
5331936       87.233853   ug/m3 2017-05-16 13:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1998-01-01 00:00:00  1998    1    1     0    NaN             NaN   ug/m³
1 1998-01-01 01:00:00  1998    1    1     1    NaN             NaN   ug/m³
2 1998-01-01 02:00:00  1998    1    1     2    NaN             NaN   ug/m³
3 1998-01-01 03:00:00  1998    1    1     3    NaN             NaN   ug/m³
4 1998-01-01 04:00:00  1998    1    1     4    NaN             NaN   ug/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1998-01-01 00:00:00  1998    1    1     0    NaN             NaN   ug/m³
1 1998-01-01 01:00:00  1998    1    1     1    NaN             NaN   ug/m³
2 1998-01-01 02:00:00  1998    1    1     2    NaN             NaN   ug/m³
3 1998-01-01 03:00:00  1998    1    1     3    NaN             NaN   ug/m³
4 1998-01-01 04:00:00  1998    1    1     4    NaN             NaN   ug/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
005
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/O3/SP0288RA005.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
11134200           178.0   ug/m3 2021-10-05 13:00:00
10349560           175.0   ug/m3 2020-10-03 17:00:00
11134201           173.0   ug/m3 2021-10-05 14:00:00
10349559           172.0   ug/m3 2020-10-03 16:00:00
10349558           171.0   ug/m3 2020-10-03 15:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2016-12-07 14:00:00  2016   12    7    14   82.0            82.0   µg/m3
1 2016-12-07 15:00:00  2016   12    7    15   70.0            70.0   µg/m3
2 2016-12-07 16:00:00  2016   12    7    16    NaN             NaN     NaN
3 2016-12-07 17:00:00  2016   12    7    17   68.0            68.0   µg/m3
4 2016-12-07 18:00:00  2016   12    7    18   69.0            69.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True     False
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2016-12-07 14:00:00  2016   12    7    14   82.0            82.0   ug/m3
1 2016-12-07 15:00:00  2016   12    7    15   70.0            70.0   ug/m3
2 2016-12-07 16:00:00  2016   12    7    16    NaN             NaN     NaN
3 2016-12-07 17:00:00  2016   12    7    17   68.0            68.0   ug/m3
4 2016-12-07 18:00:00  2016   12    7    18   69.0            69.0   ug/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True     False
3          True      True
4          True      True
005
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/O3/RJ0227RA005.csv
iema
          VALOR_ORIGINAL UNIDADE            DATETIME
29549553          80.944   ug/m3 2016-06-01 14:30:00
29549552          79.851   ug/m3 2016-06-01 13:30:00
29549554          75.818   ug/m3 2016-06-01 15:30:00
29549555          72.536   ug/m3 2016-06-01 16:30:00
26900171          71.600     ppb 2015-02-27 12:30:00
mma
             DATETIME   ANO  MES  DIA  HORA   VALOR  VALOR_ORIGINAL UNIDADE  \
0 2015-02-11 11:00:00  2015    2   11    11   52.97           52.97   µg/m³
1 2015-02-11 12:00:00  2015    2   11    12   44.92           44.92   µg/m³
2 2015-02-11 13:00:00  2015    2   11    13  101.62          101.62   µg/m³
3 2015-02-11 14:00:00  2015    2   11    14     NaN             NaN   µg/m³
4 2015-02-11 15:00:00  2015    2   11    15  122.81          122.81   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3         False     False
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA   VALOR  VALOR_ORIGINAL UNIDADE  \
0 2015-02-11 11:00:00  2015    2   11    11   52.97           52.97   µg/m³
1 2015-02-11 12:00:00  2015    2   11    12   44.92           44.92   µg/m³
2 2015-02-11 13:00:00  2015    2   11    13  101.62          101.62   µg/m³
3 2015-02-11 14:00:00  2015    2   11    14     NaN             NaN   µg/m³
4 2015-02-11 15:00:00  2015    2   11    15  122.81          122.81   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True     False
4          True      True
005

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/O3/RJ0045RA005.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
28708134     1140.523738   µg/m3 2019-09-26 08:00:00
21959361      784.099777   ug/m3 2017-09-01 04:00:00
28708338      717.722950   µg/m3 2019-09-26 09:00:00
21961806      632.274387   ug/m3 2017-12-25 11:00:00
21959921      598.834744   ug/m3 2017-09-30 21:00:00
mma
             DATETIME     ANO  MES   DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2001-05-12 23:00:00  2001.0  5.0  12.0  23.0    NaN             NaN   µg/m³
1 2001-05-13 00:00:00  2001.0  5.0  13.0   0.0    NaN             NaN   µg/m³
2 2001-05-13 01:00:00  2001.0  5.0  13.0   1.0    NaN             NaN   µg/m³
3 2001-05-13 02:00:00  2001.0  5.0  13.0   2.0    NaN             NaN   µg/m³
4 2001-05-13 03:00:00  2001.0  5.0  13.0   3.0    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0         False     False
1         False     False
2         False     False
3         False     False
4         False     False
final
             DATETIME     ANO  MES   DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2001-05-12 23:00:00  2001.0  5.0  12.0  23.0    NaN             NaN   µg/m³
1 2001-05-13 00:00:00  2001.0  5.0  13.0   0.0    NaN             NaN   µg/m³
2 2001-05-13 01:00:00  2001.0  5.0  13.0   1.0    NaN             NaN   µg/m³
3 2001-05-13 02:00:00  2001.0  5.0  13.0   2.0    NaN             NaN   µg/m³
4 2001-05-13 03:00:00  2001.0  5.0  13.0   3.0    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
005
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/O3/MG0039RA005.csv
iema
          VALOR_ORIGINAL UNIDADE            DATETIME
32667228          269.14   µg/m3 2020-10-09 12:30:00
32667663          238.43   µg/m3 2020-10-09 15:30:00
32667518          234.17   µg/m3 2020-10-09 14:30:00
32590992          226.37   µg/m3 2020-09-18 16:30:00
32667087          225.72   µg/m3 2020-10-09 11:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2017-05-03 09:00:00  2017    5    3     9    NaN             NaN   µg/m3
1 2017-05-03 10:00:00  2017    5    3    10    NaN             NaN   µg/m3
2 2017-05-03 11:00:00  2017    5    3    11    NaN             NaN   µg/m3
3 2017-05-03 12:00:00  2017    5    3    12    NaN             NaN   µg/m3
4 2017-05-03 13:00:00  2017    5    3    13    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2017-05-03 09:00:00  2017    5    3     9    NaN             NaN   µg/m3
1 2017-05-03 10:00:00  2017    5    3    10    NaN             NaN   µg/m3
2 2017-05-03 11:00:00  2017    5    3    11    NaN             NaN   µg/m3
3 2017-05-03 12:00:00  2017    5    3    12    NaN             NaN   µg/m3
4 2017-05-03 13:00:00  2017    5    3    13    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

005
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/O3/RJ0079RA005.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
20693843        207.2290     ppb 2016-10-19 15:30:00
24789655        170.7902   ug/m3 2017-10-12 19:00:00
24789697        169.6570   ug/m3 2017-10-14 13:00:00
24789696        164.0980   ug/m3 2017-10-14 12:00:00
24789326        163.8414   ug/m3 2017-09-28 15:00:00
mma
             DATETIME     ANO   MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1998-10-01 00:00:00  1998.0  10.0  1.0   0.0  56.74           56.74   µg/m³
1 1998-10-01 01:00:00  1998.0  10.0  1.0   1.0  46.31           46.31   µg/m³
2 1998-10-01 02:00:00  1998.0  10.0  1.0   2.0  42.32           42.32   µg/m³
3 1998-10-01 03:00:00  1998.0  10.0  1.0   3.0    NaN             NaN   µg/m³
4 1998-10-01 04:00:00  1998.0  10.0  1.0   4.0    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3         False     False
4         False     False
final
             DATETIME     ANO   MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1998-10-01 00:00:00  1998.0  10.0  1.0   0.0  56.74           56.74   µg/m³
1 1998-10-01 01:00:00  1998.0  10.0  1.0   1.0  46.31           46.31   µg/m³
2 1998-10-01 02:00:00  1998.0  10.0  1.0   2.0  42.32           42.32   µg/m³
3 1998-10-01 03:00:00  1998.0  10.0  1.0   3.0    NaN             NaN   µg/m³
4 1998-10-01 04:00:00  1998.0  10.0  1.0   4.0    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True     False
4          True     False
005
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/O3/RJ0055RA005.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
19801620      667.708629   µg/m3 2019-03-11 16:00:00
25305613      478.745200   ug/m3 2017-08-11 16:00:00
20001572      269.641811   µg/m3 2019-04-29 22:00:00
19729881      259.153538   µg/m3 2019-02-22 11:00:00
19898554      254.986472   µg/m3 2019-04-04 16:00:00
mma
             DATETIME     ANO   MES   DIA  HORA  VALOR  VALOR_ORIGINAL  \
0 2001-12-29 10:00:00  2001.0  12.0  29.0  10.0  52.33           52.33
1 2001-12-29 11:00:00  2001.0  12.0  29.0  11.0  51.83           51.83
2 2001-12-29 12:00:00  2001.0  12.0  29.0  12.0  53.03           53.03
3 2001-12-29 13:00:00  2001.0  12.0  29.0  13.0  54.37           54.37
4 2001-12-29 14:00:00  2001.0  12.0  29.0  14.0  55.39           55.39

  UNIDADE  QAQC_INTERNO  QAQC_MMA
0   µg/m³          True      True
1   µg/m³          True      True
2   µg/m³          True      True
3   µg/m³          True      True
4   µg/m³          True      True
final
             DATETIME     ANO   MES   DIA  HORA  VALOR  VALOR_ORIGINAL  \
0 2001-12-29 10:00:00  2001.0  12.0  29.0  10.0  52.33           52.33
1 2001-12-29 11:00:00  2001.0  12.0  29.0  11.0  51.83           51.83
2 2001-12-29 12:00:00  2001.0  12.0  29.0  12.0  53.03           53.03
3 2001-12-29 13:00:00  2001.0  12.0  29.0  13.0  54.37           54.37
4 2001-12-29 14:00:00  2001.0  12.0  29.0  14.0  55.39           55.39

  UNIDADE  QAQC_INTERNO  QAQC_MMA
0   µg/m³          True      True
1   µg/m³          True      True
2   µg/m³          True      True
3   µg/m³          True      True
4   µg/m³          True      True
005
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/O3/RJ0226RA005.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
29562935         130.084   ug/m3 2016-02-16 18:30:00
29562983         129.722   ug/m3 2016-02-18 18:30:00
29562695         126.397   ug/m3 2016-02-06 17:30:00
29562574         123.643   ug/m3 2016-02-01 16:30:00
29562932         122.320   ug/m3 2016-02-16 15:30:00
mma
             DATETIME     ANO  MES   DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2006-07-21 00:00:00  2006.0  7.0  21.0   0.0    NaN             NaN   µg/m³
1 2006-07-21 01:00:00  2006.0  7.0  21.0   1.0    NaN             0.0   µg/m³
2 2006-07-21 02:00:00  2006.0  7.0  21.0   2.0    NaN             0.0   µg/m³
3 2006-07-21 03:00:00  2006.0  7.0  21.0   3.0    NaN             0.0   µg/m³
4 2006-07-21 04:00:00  2006.0  7.0  21.0   4.0    NaN             0.0   µg/m³

   QAQC_INTERNO  QAQC_MMA
0         False     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME     ANO  MES   DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2006-07-21 00:00:00  2006.0  7.0  21.0   0.0    NaN             NaN   µg/m³
1 2006-07-21 01:00:00  2006.0  7.0  21.0   1.0    NaN             0.0   µg/m³
2 2006-07-21 02:00:00  2006.0  7.0  21.0   2.0    NaN             0.0   µg/m³
3 2006-07-21 03:00:00  2006.0  7.0  21.0   3.0    NaN             0.0   µg/m³
4 2006-07-21 04:00:00  2006.0  7.0  21.0   4.0    NaN             0.0   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
005
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/O3/SP0092RA005.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
19213259           327.0   ug/m3 2015-01-20 15:00:00
19213258           293.0   ug/m3 2015-01-20 14:00:00
19213257           287.0   ug/m3 2015-01-20 13:00:00
8719538            275.0   ug/m3 2022-01-20 12:00:00
13470278           248.0   ug/m3 2019-01-11 15:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1999-05-14 05:00:00  1999    5   14     5    1.0             1.0   µg/m3
1 1999-05-14 06:00:00  1999    5   14     6    1.0             1.0   µg/m3
2 1999-05-14 07:00:00  1999    5   14     7    NaN             0.0   µg/m3
3 1999-05-14 08:00:00  1999    5   14     8    NaN             0.0   µg/m3
4 1999-05-14 09:00:00  1999    5   14     9    4.0             4.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True     False
3          True     False
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1999-05-14 05:00:00  1999    5   14     5    1.0             1.0   µg/m3
1 1999-05-14 06:00:00  1999    5   14     6    1.0             1.0   µg/m3
2 1999-05-14 07:00:00  1999    5   14     7    NaN             0.0   µg/m3
3 1999-05-14 08:00:00  1999    5   14     8    NaN             0.0   µg/m3
4 1999-05-14 09:00:00  1999    5   14     9    4.0             4.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True     False
3          True     False
4          True      True
005
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/O3/SP0258RA005.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
17627101           213.0   ug/m3 2015-02-12 15:00:00
17627102           212.0   ug/m3 2015-02-12 16:00:00
17627103           199.0   ug/m3 2015-02-12 17:00:00
8134230            179.0   ug/m3 2019-01-08 13:00:00
17627100           177.0   ug/m3 2015-02-12 14:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2011-06-07 01:00:00  2011    6    7     1    3.0             3.0   µg/m3
1 2011-06-07 02:00:00  2011    6    7     2    2.0             2.0   µg/m3
2 2011-06-07 03:00:00  2011    6    7     3    1.0             1.0   µg/m3
3 2011-06-07 04:00:00  2011    6    7     4    3.0             3.0   µg/m3
4 2011-06-07 05:00:00  2011    6    7     5    3.0             3.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2011-06-07 01:00:00  2011    6    7     1    3.0             3.0   µg/m3
1 2011-06-07 02:00:00  2011    6    7     2    2.0             2.0   µg/m3
2 2011-06-07 03:00:00  2011    6    7     3    1.0             1.0   µg/m3
3 2011-06-07 04:00:00  2011    6    7     4    3.0             3.0   µg/m3
4 2011-06-07 05:00:00  2011    6    7     5    3.0             3.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
005
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/O3/RJ0063RA005.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
19546037      519.928552   µg/m3 2019-01-07 02:00:00
24234901      253.001200   µg/m3 2020-12-21 10:00:00
24283043      252.072000   µg/m3 2020-12-31 13:00:00
19547180      237.357529   µg/m3 2019-01-07 09:00:00
24235101      233.065600   µg/m3 2020-12-21 11:00:00
mma
             DATETIME     ANO  MES   DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2016-06-13 10:00:00  2016.0  6.0  13.0  10.0    NaN             NaN   µg/m³
1 2016-06-13 11:00:00  2016.0  6.0  13.0  11.0    NaN             NaN   µg/m³
2 2016-06-13 12:00:00  2016.0  6.0  13.0  12.0    NaN             NaN   µg/m³
3 2016-06-13 13:00:00  2016.0  6.0  13.0  13.0    NaN             NaN   µg/m³
4 2016-06-13 14:00:00  2016.0  6.0  13.0  14.0    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0         False     False
1         False     False
2         False     False
3         False     False
4         False     False
final
             DATETIME     ANO  MES   DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2016-06-13 10:00:00  2016.0  6.0  13.0  10.0    NaN             NaN   µg/m³
1 2016-06-13 11:00:00  2016.0  6.0  13.0  11.0    NaN             NaN   µg/m³
2 2016-06-13 12:00:00  2016.0  6.0  13.0  12.0    NaN             NaN   µg/m³
3 2016-06-13 13:00:00  2016.0  6.0  13.0  13.0    NaN             NaN   µg/m³
4 2016-06-13 14:00:00  2016.0  6.0  13.0  14.0    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
005
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/O3/SP0116RA005.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
7273707            193.0   ug/m3 2017-08-31 16:00:00
8216223            191.0   ug/m3 2019-09-13 13:00:00
16977204           187.0   ug/m3 2022-09-13 13:00:00
8216222            183.0   ug/m3 2019-09-13 12:00:00
17705413           180.0   ug/m3 2015-11-13 13:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2008-06-26 01:00:00  2008    6   26     1    2.0             2.0   µg/m3
1 2008-06-26 02:00:00  2008    6   26     2    NaN             0.0   µg/m3
2 2008-06-26 03:00:00  2008    6   26     3    NaN             0.0   µg/m3
3 2008-06-26 04:00:00  2008    6   26     4    NaN             0.0   µg/m3
4 2008-06-26 05:00:00  2008    6   26     5    NaN             0.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2008-06-26 01:00:00  2008    6   26     1    2.0             2.0   µg/m3
1 2008-06-26 02:00:00  2008    6   26     2    NaN             0.0   µg/m3
2 2008-06-26 03:00:00  2008    6   26     3    NaN             0.0   µg/m3
3 2008-06-26 04:00:00  2008    6   26     4    NaN             0.0   µg/m3
4 2008-06-26 05:00:00  2008    6   26     5    NaN             0.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True     False
2          True     False
3          True     False
4          True     False
005
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/O3/RJ0043RA005.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
19815439     1131.488589   µg/m3 2019-03-15 05:00:00
19913527     1060.974724   µg/m3 2019-04-08 08:00:00
19644065     1000.595943   µg/m3 2019-02-01 16:00:00
19914038      966.066258   µg/m3 2019-04-08 11:00:00
19732891      765.388957   µg/m3 2019-02-23 04:00:00
mma
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2009-06-06 20:00:00  2009.0  6.0  6.0  20.0  94.29           94.29   µg/m³
1 2009-06-06 21:00:00  2009.0  6.0  6.0  21.0  80.09           80.09   µg/m³
2 2009-06-06 22:00:00  2009.0  6.0  6.0  22.0  75.12           75.12   µg/m³
3 2009-06-06 23:00:00  2009.0  6.0  6.0  23.0  77.74           77.74   µg/m³
4 2009-06-07 00:00:00  2009.0  6.0  7.0   0.0  73.74           73.74   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2009-06-06 20:00:00  2009.0  6.0  6.0  20.0  94.29           94.29   µg/m³
1 2009-06-06 21:00:00  2009.0  6.0  6.0  21.0  80.09           80.09   µg/m³
2 2009-06-06 22:00:00  2009.0  6.0  6.0  22.0  75.12           75.12   µg/m³
3 2009-06-06 23:00:00  2009.0  6.0  6.0  23.0  77.74           77.74   µg/m³
4 2009-06-07 00:00:00  2009.0  6.0  7.0   0.0  73.74           73.74   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
005
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/O3/SP0289RA005.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
8808573            151.0   ug/m3 2022-09-03 14:00:00
18420026           150.0   ug/m3 2017-10-14 16:00:00
8808574            149.0   ug/m3 2022-09-03 15:00:00
18420025           148.0   ug/m3 2017-10-14 15:00:00
18419382           147.0   ug/m3 2017-09-16 16:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2017-01-19 11:00:00  2017    1   19    11    2.0             2.0   µg/m3
1 2017-01-19 12:00:00  2017    1   19    12    2.0             2.0   µg/m3
2 2017-01-19 13:00:00  2017    1   19    13    3.0             3.0   µg/m3
3 2017-01-19 14:00:00  2017    1   19    14    3.0             3.0   µg/m3
4 2017-01-19 15:00:00  2017    1   19    15    3.0             3.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2017-01-19 11:00:00  2017    1   19    11    2.0             2.0   ug/m3
1 2017-01-19 12:00:00  2017    1   19    12    2.0             2.0   ug/m3
2 2017-01-19 13:00:00  2017    1   19    13    3.0             3.0   ug/m3
3 2017-01-19 14:00:00  2017    1   19    14    3.0             3.0   ug/m3
4 2017-01-19 15:00:00  2017    1   19    15    3.0             3.0   ug/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
005
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/O3/RJ0044RA005.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
28688283      834.409966   µg/m3 2019-09-22 05:00:00
20304238      803.822478   µg/m3 2019-07-10 17:00:00
28689101      799.818446   µg/m3 2019-09-22 09:00:00
20304620      798.666780   µg/m3 2019-07-10 19:00:00
28687871      766.152742   µg/m3 2019-09-22 03:00:00
mma
             DATETIME     ANO  MES   DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2002-02-10 03:00:00  2002.0  2.0  10.0   3.0  23.17           23.17   µg/m³
1 2002-02-10 04:00:00  2002.0  2.0  10.0   4.0  23.58           23.58   µg/m³
2 2002-02-10 05:00:00  2002.0  2.0  10.0   5.0  24.40           24.40   µg/m³
3 2002-02-10 06:00:00  2002.0  2.0  10.0   6.0  25.73           25.73   µg/m³
4 2002-02-10 07:00:00  2002.0  2.0  10.0   7.0  28.43           28.43   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME     ANO  MES   DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2002-02-10 03:00:00  2002.0  2.0  10.0   3.0  23.17           23.17   µg/m³
1 2002-02-10 04:00:00  2002.0  2.0  10.0   4.0  23.58           23.58   µg/m³
2 2002-02-10 05:00:00  2002.0  2.0  10.0   5.0  24.40           24.40   µg/m³
3 2002-02-10 06:00:00  2002.0  2.0  10.0   6.0  25.73           25.73   µg/m³
4 2002-02-10 07:00:00  2002.0  2.0  10.0   7.0  28.43           28.43   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
005
005
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/O3/MG0001RA005.csv

/tmp/ipykernel_273420/1352582357.py:97: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  df_mma = pd.read_csv(arquivo, encoding = 'UTF-8')
/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
35169791          266.22   µg/m3 2017-01-10 14:30:00
35169792          216.46   µg/m3 2017-08-09 15:30:00
36382701          205.19   µg/m3 2018-04-24 14:30:00
36846655          198.63   µg/m3 2018-09-17 14:30:00
35169793          196.27   µg/m3 2017-07-31 11:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR VALOR_ORIGINAL UNIDADE  \
0 2009-01-01 01:00:00  2009    1    1     1    7.2            7.2     ppb
1 2009-01-01 02:00:00  2009    1    1     2    9.2            9.2     ppb
2 2009-01-01 03:00:00  2009    1    1     3    8.2            8.2     ppb
3 2009-01-01 04:00:00  2009    1    1     4    9.8            9.8     ppb
4 2009-01-01 05:00:00  2009    1    1     5   14.5           14.5     ppb

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR VALOR_ORIGINAL UNIDADE  \
0 2009-01-01 01:00:00  2009    1    1     1    7.2            7.2     ppb
1 2009-01-01 02:00:00  2009    1    1     2    9.2            9.2     ppb
2 2009-01-01 03:00:00  2009    1    1     3    8.2            8.2     ppb
3 2009-01-01 04:00:00  2009    1    1     4    9.8            9.8     ppb
4 2009-01-01 05:00:00  2009    1    1     5   14.5           14.5     ppb

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
005
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/O3/MG0006RA005.csv

/tmp/ipykernel_273420/1352582357.py:97: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  df_mma = pd.read_csv(arquivo, encoding = 'UTF-8')
/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
34678802          186.22   µg/m3 2019-09-11 11:30:00
34824187          167.47   µg/m3 2019-10-19 10:30:00
34713696          166.53   µg/m3 2019-09-20 13:30:00
33121092          166.13   µg/m3 2015-01-03 11:30:00
33121105          162.00   µg/m3 2015-01-10 16:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR VALOR_ORIGINAL UNIDADE  \
0 2010-01-01 01:00:00  2010    1    1     1   11.8           11.8     ppb
1 2010-01-01 02:00:00  2010    1    1     2   12.2           12.2     ppb
2 2010-01-01 03:00:00  2010    1    1     3   13.8           13.8     ppb
3 2010-01-01 04:00:00  2010    1    1     4   11.2           11.2     ppb
4 2010-01-01 05:00:00  2010    1    1     5   10.0             10     ppb

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR VALOR_ORIGINAL UNIDADE  \
0 2010-01-01 01:00:00  2010    1    1     1   11.8           11.8     ppb
1 2010-01-01 02:00:00  2010    1    1     2   12.2           12.2     ppb
2 2010-01-01 03:00:00  2010    1    1     3   13.8           13.8     ppb
3 2010-01-01 04:00:00  2010    1    1     4   11.2           11.2     ppb
4 2010-01-01 05:00:00  2010    1    1     5   10.0             10     ppb

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
005
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/O3/SP0085RA005.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
17172131           269.0   ug/m3 2015-03-27 15:00:00
17172151           246.0   ug/m3 2015-03-28 12:00:00
6660184            244.0   ug/m3 2017-10-14 13:00:00
13075959           243.0   ug/m3 2020-03-12 14:00:00
9176818            243.0   ug/m3 2022-01-20 15:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1998-01-03 01:00:00  1998    1    3     1   16.0            16.0   µg/m3
1 1998-01-03 02:00:00  1998    1    3     2   21.0            21.0   µg/m3
2 1998-01-03 03:00:00  1998    1    3     3   22.0            22.0   µg/m3
3 1998-01-03 04:00:00  1998    1    3     4    NaN             NaN     NaN
4 1998-01-03 05:00:00  1998    1    3     5    9.0             9.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True     False
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1998-01-03 01:00:00  1998    1    3     1   16.0            16.0   µg/m3
1 1998-01-03 02:00:00  1998    1    3     2   21.0            21.0   µg/m3
2 1998-01-03 03:00:00  1998    1    3     3   22.0            22.0   µg/m3
3 1998-01-03 04:00:00  1998    1    3     4    NaN             NaN     NaN
4 1998-01-03 05:00:00  1998    1    3     5    9.0             9.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True     False
4          True      True
005
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/O3/MG0011RA005.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
33724911          233.39   µg/m3 2015-12-07 13:30:00
33724914          221.75   µg/m3 2015-12-07 12:30:00
33724926          214.16   µg/m3 2015-12-05 16:30:00
33724931          213.88   µg/m3 2015-12-05 14:30:00
33724934          212.98   µg/m3 2015-12-05 15:30:00
mma
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2014-01-01 01:00:00  2014.0  1.0  1.0   1.0  13.16           13.16   µg/m3
1 2014-01-01 02:00:00  2014.0  1.0  1.0   2.0   9.24            9.24   µg/m3
2 2014-01-01 03:00:00  2014.0  1.0  1.0   3.0   6.04            6.04   µg/m3
3 2014-01-01 04:00:00  2014.0  1.0  1.0   4.0   7.71            7.71   µg/m3
4 2014-01-01 05:00:00  2014.0  1.0  1.0   5.0   5.98            5.98   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2014-01-01 01:00:00  2014.0  1.0  1.0   1.0  13.16           13.16   µg/m3
1 2014-01-01 02:00:00  2014.0  1.0  1.0   2.0   9.24            9.24   µg/m3
2 2014-01-01 03:00:00  2014.0  1.0  1.0   3.0   6.04            6.04   µg/m3
3 2014-01-01 04:00:00  2014.0  1.0  1.0   4.0   7.71            7.71   µg/m3
4 2014-01-01 05:00:00  2014.0  1.0  1.0   5.0   5.98            5.98   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
005
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/O3/RJ0018RA005.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
19610943      304.141739   µg/m3 2019-01-24 10:00:00
19988034      300.564417   µg/m3 2019-04-26 10:00:00
31433407      193.570552   µg/m3 2020-05-18 16:00:00
20929565      188.375000   ug/m3 2016-02-17 16:30:00
24072031      159.018400   µg/m3 2020-11-17 13:00:00
mma
             DATETIME     ANO  MES   DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2012-05-10 00:00:00  2012.0  5.0  10.0   0.0    NaN             NaN   µg/m³
1 2012-05-10 01:00:00  2012.0  5.0  10.0   1.0    NaN             NaN   µg/m³
2 2012-05-10 02:00:00  2012.0  5.0  10.0   2.0    NaN             NaN   µg/m³
3 2012-05-10 03:00:00  2012.0  5.0  10.0   3.0    NaN             NaN   µg/m³
4 2012-05-10 04:00:00  2012.0  5.0  10.0   4.0    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0         False     False
1         False     False
2         False     False
3         False     False
4         False     False
final
             DATETIME     ANO  MES   DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2012-05-10 00:00:00  2012.0  5.0  10.0   0.0    NaN             NaN   µg/m³
1 2012-05-10 01:00:00  2012.0  5.0  10.0   1.0    NaN             NaN   µg/m³
2 2012-05-10 02:00:00  2012.0  5.0  10.0   2.0    NaN             NaN   µg/m³
3 2012-05-10 03:00:00  2012.0  5.0  10.0   3.0    NaN             NaN   µg/m³
4 2012-05-10 04:00:00  2012.0  5.0  10.0   4.0    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
005
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/O3/MG0002RA005.csv

/tmp/ipykernel_273420/1352582357.py:97: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  df_mma = pd.read_csv(arquivo, encoding = 'UTF-8')
/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
32002300          216.82   µg/m3 2020-04-04 15:30:00
32002150          209.57   µg/m3 2020-04-04 14:30:00
32002450          193.93   µg/m3 2020-04-04 16:30:00
33161462          191.50   µg/m3 2015-11-06 12:30:00
32006250          190.16   µg/m3 2020-04-05 17:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR VALOR_ORIGINAL UNIDADE  \
0 2009-01-01 01:00:00  2009    1    1     1   12.0             12     ppb
1 2009-01-01 02:00:00  2009    1    1     2    6.5            6.5     ppb
2 2009-01-01 03:00:00  2009    1    1     3   10.8           10.8     ppb
3 2009-01-01 04:00:00  2009    1    1     4    7.0              7     ppb
4 2009-01-01 05:00:00  2009    1    1     5   13.2           13.2     ppb

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR VALOR_ORIGINAL UNIDADE  \
0 2009-01-01 01:00:00  2009    1    1     1   12.0             12     ppb
1 2009-01-01 02:00:00  2009    1    1     2    6.5            6.5     ppb
2 2009-01-01 03:00:00  2009    1    1     3   10.8           10.8     ppb
3 2009-01-01 04:00:00  2009    1    1     4    7.0              7     ppb
4 2009-01-01 05:00:00  2009    1    1     5   13.2           13.2     ppb

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
005
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/O3/MG0057RA005.csv
iema
          VALOR_ORIGINAL UNIDADE            DATETIME
32623068          293.47   µg/m3 2020-09-27 15:30:00
34824744          216.11   µg/m3 2019-10-19 13:30:00
38170091          212.39   µg/m3 2021-09-14 16:30:00
32526576          206.36   µg/m3 2020-08-31 13:30:00
38248775          200.16   µg/m3 2021-10-04 15:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2019-01-01 01:00:00  2019    1    1     1  11.53           11.53   µg/m3
1 2019-01-01 02:00:00  2019    1    1     2   8.69            8.69   µg/m3
2 2019-01-01 03:00:00  2019    1    1     3   4.33            4.33   µg/m3
3 2019-01-01 04:00:00  2019    1    1     4   4.68            4.68   µg/m3
4 2019-01-01 05:00:00  2019    1    1     5  23.70           23.70   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2019-01-01 01:00:00  2019    1    1     1  11.53           11.53   µg/m3
1 2019-01-01 02:00:00  2019    1    1     2   8.69            8.69   µg/m3
2 2019-01-01 03:00:00  2019    1    1     3   4.33            4.33   µg/m3
3 2019-01-01 04:00:00  2019    1    1     4   4.68            4.68   µg/m3
4 2019-01-01 05:00:00  2019    1    1     5  23.70           23.70   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

005
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/O3/SP0262RA005.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
13670590           326.0   ug/m3 2019-02-01 11:00:00
19388499           258.0   ug/m3 2015-01-20 13:00:00
19388500           255.0   ug/m3 2015-01-20 14:00:00
8924668            246.0   ug/m3 2022-03-08 16:00:00
8924016            239.0   ug/m3 2022-01-20 14:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2012-02-27 01:00:00  2012    2   27     1   38.0            38.0   µg/m3
1 2012-02-27 02:00:00  2012    2   27     2   32.0            32.0   µg/m3
2 2012-02-27 03:00:00  2012    2   27     3   28.0            28.0   µg/m3
3 2012-02-27 04:00:00  2012    2   27     4   37.0            37.0   µg/m3
4 2012-02-27 05:00:00  2012    2   27     5   37.0            37.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2012-02-27 01:00:00  2012    2   27     1   38.0            38.0   µg/m3
1 2012-02-27 02:00:00  2012    2   27     2   32.0            32.0   µg/m3
2 2012-02-27 03:00:00  2012    2   27     3   28.0            28.0   µg/m3
3 2012-02-27 04:00:00  2012    2   27     4   37.0            37.0   µg/m3
4 2012-02-27 05:00:00  2012    2   27     5   37.0            37.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
005
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/O3/BA0006ND005.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
         VALOR_ORIGINAL UNIDADE            DATETIME
5249332       88.944321   ug/m3 2017-05-16 12:00:00
5249333       85.523385   ug/m3 2017-05-16 13:00:00
5253019       84.026726   ug/m3 2017-10-19 11:00:00
5249331       81.247216   ug/m3 2017-05-16 11:00:00
5254271       76.971047   ug/m3 2017-12-10 19:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1998-01-01 00:00:00  1998    1    1     0    NaN             NaN   ug/m³
1 1998-01-01 01:00:00  1998    1    1     1    NaN             NaN   ug/m³
2 1998-01-01 02:00:00  1998    1    1     2    NaN             NaN   ug/m³
3 1998-01-01 03:00:00  1998    1    1     3    NaN             NaN   ug/m³
4 1998-01-01 04:00:00  1998    1    1     4    NaN             NaN   ug/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1998-01-01 00:00:00  1998    1    1     0    NaN             NaN   ug/m³
1 1998-01-01 01:00:00  1998    1    1     1    NaN             NaN   ug/m³
2 1998-01-01 02:00:00  1998    1    1     2    NaN             NaN   ug/m³
3 1998-01-01 03:00:00  1998    1    1     3    NaN             NaN   ug/m³
4 1998-01-01 04:00:00  1998    1    1     4    NaN             NaN   ug/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
005
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/O3/RJ0036RA005.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
30923399      286.743558   µg/m3 2020-02-01 12:00:00
31561070      273.865031   µg/m3 2020-06-13 13:00:00
30918925      261.143558   µg/m3 2020-01-31 13:00:00
28893386      257.609816   µg/m3 2019-11-05 12:00:00
25470328      247.590200   ug/m3 2017-01-11 11:00:00
mma
             DATETIME     ANO  MES   DIA  HORA   VALOR  VALOR_ORIGINAL  \
0 2011-08-26 10:00:00  2011.0  8.0  26.0  10.0   41.76           41.76
1 2011-08-26 11:00:00  2011.0  8.0  26.0  11.0   52.46           52.46
2 2011-08-26 12:00:00  2011.0  8.0  26.0  12.0   70.06           70.06
3 2011-08-26 13:00:00  2011.0  8.0  26.0  13.0   87.74           87.74
4 2011-08-26 14:00:00  2011.0  8.0  26.0  14.0  107.09          107.09

  UNIDADE  QAQC_INTERNO  QAQC_MMA
0   µg/m³          True      True
1   µg/m³          True      True
2   µg/m³          True      True
3   µg/m³          True      True
4   µg/m³          True      True
final
             DATETIME     ANO  MES   DIA  HORA   VALOR  VALOR_ORIGINAL  \
0 2011-08-26 10:00:00  2011.0  8.0  26.0  10.0   41.76           41.76
1 2011-08-26 11:00:00  2011.0  8.0  26.0  11.0   52.46           52.46
2 2011-08-26 12:00:00  2011.0  8.0  26.0  12.0   70.06           70.06
3 2011-08-26 13:00:00  2011.0  8.0  26.0  13.0   87.74           87.74
4 2011-08-26 14:00:00  2011.0  8.0  26.0  14.0  107.09          107.09

  UNIDADE  QAQC_INTERNO  QAQC_MMA
0   µg/m³          True      True
1   µg/m³          True      True
2   µg/m³          True      True
3   µg/m³          True      True
4   µg/m³          True      True
005
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/O3/RJ0081RA005.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
29097222       415.60042   µg/m3 2019-12-19 09:00:00
23733370       320.72750   µg/m3 2020-09-10 12:00:00
23733578       312.04420   µg/m3 2020-09-10 13:00:00
23726774       308.45320   µg/m3 2020-09-09 04:00:00
24207121       305.62730   µg/m3 2020-12-15 13:00:00
mma
             DATETIME     ANO  MES   DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2005-09-18 20:00:00  2005.0  9.0  18.0  20.0  13.73           13.73   µg/m³
1 2005-09-18 21:00:00  2005.0  9.0  18.0  21.0  14.67           14.67   µg/m³
2 2005-09-18 22:00:00  2005.0  9.0  18.0  22.0    NaN             NaN   µg/m³
3 2005-09-18 23:00:00  2005.0  9.0  18.0  23.0    NaN             NaN   µg/m³
4 2005-09-19 00:00:00  2005.0  9.0  19.0   0.0    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2         False     False
3         False     False
4         False     False
final
             DATETIME     ANO  MES   DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2005-09-18 20:00:00  2005.0  9.0  18.0  20.0  13.73           13.73   µg/m³
1 2005-09-18 21:00:00  2005.0  9.0  18.0  21.0  14.67           14.67   µg/m³
2 2005-09-18 22:00:00  2005.0  9.0  18.0  22.0    NaN             NaN   µg/m³
3 2005-09-18 23:00:00  2005.0  9.0  18.0  23.0    NaN             NaN   µg/m³
4 2005-09-19 00:00:00  2005.0  9.0  19.0   0.0    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True     False
3          True     False
4          True     False
005
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/O3/SP0106RA005.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
17847341           184.0   ug/m3 2017-08-31 14:00:00
13138900           184.0   ug/m3 2019-10-03 17:00:00
17847342           184.0   ug/m3 2017-08-31 15:00:00
17847343           180.0   ug/m3 2017-08-31 16:00:00
17847340           180.0   ug/m3 2017-08-31 13:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2008-07-11 01:00:00  2008    7   11     1   42.0            42.0   µg/m3
1 2008-07-11 02:00:00  2008    7   11     2   34.0            34.0   µg/m3
2 2008-07-11 03:00:00  2008    7   11     3   31.0            31.0   µg/m3
3 2008-07-11 04:00:00  2008    7   11     4   32.0            32.0   µg/m3
4 2008-07-11 05:00:00  2008    7   11     5   38.0            38.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2008-07-11 01:00:00  2008    7   11     1   42.0            42.0   µg/m3
1 2008-07-11 02:00:00  2008    7   11     2   34.0            34.0   µg/m3
2 2008-07-11 03:00:00  2008    7   11     3   31.0            31.0   µg/m3
3 2008-07-11 04:00:00  2008    7   11     4   32.0            32.0   µg/m3
4 2008-07-11 05:00:00  2008    7   11     5   38.0            38.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
005
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/O3/MG0012RA005.csv

/tmp/ipykernel_273420/1352582357.py:97: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  df_mma = pd.read_csv(arquivo, encoding = 'UTF-8')
/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
31717800         784.634   µg/m3 2020-01-14 23:30:00
31718071         784.634   µg/m3 2020-01-15 01:30:00
31717934         784.634   µg/m3 2020-01-15 00:30:00
31717382         784.634   µg/m3 2020-01-14 20:30:00
31760368         784.634   µg/m3 2020-01-27 23:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR VALOR_ORIGINAL UNIDADE  \
0 2014-01-01 01:00:00  2014    1    1     1    NaN              *     ppb
1 2014-01-01 02:00:00  2014    1    1     2    NaN              *     ppb
2 2014-01-01 03:00:00  2014    1    1     3    NaN              *     ppb
3 2014-01-01 04:00:00  2014    1    1     4    NaN              *     ppb
4 2014-01-01 05:00:00  2014    1    1     5    NaN              *     ppb

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR VALOR_ORIGINAL UNIDADE  \
0 2014-01-01 01:00:00  2014    1    1     1    NaN              *     ppb
1 2014-01-01 02:00:00  2014    1    1     2    NaN              *     ppb
2 2014-01-01 03:00:00  2014    1    1     3    NaN              *     ppb
3 2014-01-01 04:00:00  2014    1    1     4    NaN              *     ppb
4 2014-01-01 05:00:00  2014    1    1     5    NaN              *     ppb

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
005
005
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/O3/SP0263RA005.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
18979332           298.0   ug/m3 2015-01-15 15:00:00
18979333           290.0   ug/m3 2015-01-15 16:00:00
18979331           266.0   ug/m3 2015-01-15 14:00:00
18986048           257.0   ug/m3 2015-11-12 16:00:00
13252123           251.0   ug/m3 2019-01-09 17:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2012-02-27 01:00:00  2012    2   27     1   21.0            21.0   µg/m3
1 2012-02-27 02:00:00  2012    2   27     2   35.0            35.0   µg/m3
2 2012-02-27 03:00:00  2012    2   27     3   29.0            29.0   µg/m3
3 2012-02-27 04:00:00  2012    2   27     4   24.0            24.0   µg/m3
4 2012-02-27 05:00:00  2012    2   27     5   20.0            20.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2012-02-27 01:00:00  2012    2   27     1   21.0            21.0   µg/m3
1 2012-02-27 02:00:00  2012    2   27     2   35.0            35.0   µg/m3
2 2012-02-27 03:00:00  2012    2   27     3   29.0            29.0   µg/m3
3 2012-02-27 04:00:00  2012    2   27     4   24.0            24.0   µg/m3
4 2012-02-27 05:00:00  2012    2   27     5   20.0            20.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
005
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/O3/SP0109RA005.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
19495540           289.0   ug/m3 2015-10-14 17:00:00
13798182           265.0   ug/m3 2019-10-25 15:00:00
12950831           263.0   ug/m3 2020-11-09 16:00:00
18689964           261.0   ug/m3 2017-09-20 16:00:00
13792187           249.0   ug/m3 2019-01-31 18:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2008-10-15 01:00:00  2008   10   15     1   22.0            22.0   µg/m3
1 2008-10-15 02:00:00  2008   10   15     2   60.0            60.0   µg/m3
2 2008-10-15 03:00:00  2008   10   15     3   59.0            59.0   µg/m3
3 2008-10-15 04:00:00  2008   10   15     4   58.0            58.0   µg/m3
4 2008-10-15 05:00:00  2008   10   15     5    NaN             NaN     NaN

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2008-10-15 01:00:00  2008   10   15     1   22.0            22.0   µg/m3
1 2008-10-15 02:00:00  2008   10   15     2   60.0            60.0   µg/m3
2 2008-10-15 03:00:00  2008   10   15     3   59.0            59.0   µg/m3
3 2008-10-15 04:00:00  2008   10   15     4   58.0            58.0   µg/m3
4 2008-10-15 05:00:00  2008   10   15     5    NaN             NaN     NaN

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True     False
005
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/O3/SP0097RA005.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
13719388           272.0   ug/m3 2019-10-02 15:00:00
19423036           258.0   ug/m3 2015-01-20 15:00:00
8969994            255.0   ug/m3 2022-10-20 14:00:00
8969993            255.0   ug/m3 2022-10-20 13:00:00
13715762           253.0   ug/m3 2019-04-19 15:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2007-08-09 01:00:00  2007    8    9     1   10.0            10.0   µg/m3
1 2007-08-09 02:00:00  2007    8    9     2    6.0             6.0   µg/m3
2 2007-08-09 03:00:00  2007    8    9     3    4.0             4.0   µg/m3
3 2007-08-09 04:00:00  2007    8    9     4    8.0             8.0   µg/m3
4 2007-08-09 05:00:00  2007    8    9     5   14.0            14.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2007-08-09 01:00:00  2007    8    9     1   10.0            10.0   µg/m3
1 2007-08-09 02:00:00  2007    8    9     2    6.0             6.0   µg/m3
2 2007-08-09 03:00:00  2007    8    9     3    4.0             4.0   µg/m3
3 2007-08-09 04:00:00  2007    8    9     4    8.0             8.0   µg/m3
4 2007-08-09 05:00:00  2007    8    9     5   14.0            14.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
005
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/O3/RJ0019RA005.csv
iema
          VALOR_ORIGINAL UNIDADE            DATETIME
23744380        200.4417   µg/m3 2020-09-12 16:00:00
23713778        161.1779   µg/m3 2020-09-06 15:00:00
23708894        160.7853   µg/m3 2020-09-05 16:00:00
23402985        158.0368   µg/m3 2020-07-07 14:00:00
23708682        149.7914   µg/m3 2020-09-05 15:00:00
mma
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2015-03-01 00:00:00  2015.0  3.0  1.0   0.0  15.23           15.23   µg/m³
1 2015-03-01 01:00:00  2015.0  3.0  1.0   1.0   7.92            7.92   µg/m³
2 2015-03-01 02:00:00  2015.0  3.0  1.0   2.0   8.71            8.71   µg/m³
3 2015-03-01 03:00:00  2015.0  3.0  1.0   3.0   6.73            6.73   µg/m³
4 2015-03-01 04:00:00  2015.0  3.0  1.0   4.0   3.96            3.96   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2015-03-01 00:00:00  2015.0  3.0  1.0   0.0  15.23           15.23   µg/m³
1 2015-03-01 01:00:00  2015.0  3.0  1.0   1.0   7.92            7.92   µg/m³
2 2015-03-01 02:00:00  2015.0  3.0  1.0   2.0   8.71            8.71   µg/m³
3 2015-03-01 03:00:00  2015.0  3.0  1.0   3.0   6.73            6.73   µg/m³
4 2015-03-01 04:00:00  2015.0  3.0  1.0   4.0   3.96            3.96   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
005
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/O3/CE0001ND005.csv
iema
         VALOR_ORIGINAL UNIDADE            DATETIME
4789630           308.0   ug/m3 2016-11-30 10:00:00
4863476           301.0   ug/m3 2017-02-09 11:00:00
4788338           300.0   ug/m3 2016-08-29 14:00:00
4788337           298.0   ug/m3 2016-08-29 13:00:00
4788336           275.0   ug/m3 2016-08-29 12:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2016-08-25 14:00:00  2016    8   25    14    NaN             NaN   µg/m³
1 2016-08-25 15:00:00  2016    8   25    15    NaN             NaN   µg/m³
2 2016-08-25 16:00:00  2016    8   25    16    NaN             NaN   µg/m³
3 2016-08-25 17:00:00  2016    8   25    17    NaN             NaN   µg/m³
4 2016-08-25 18:00:00  2016    8   25    18    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2016-08-25 14:00:00  2016    8   25    14  146.0           146.0   ug/m3
1 2016-08-25 15:00:00  2016    8   25    15  149.0           149.0   ug/m3
2 2016-08-25 16:00:00  2016    8   25    16  151.0           151.0   ug/m3
3 2016-08-25 17:00:00  2016    8   25    17  110.0           110.0   ug/m3
4 2016-08-25 18:00:00  2016    8   25    18   50.0            50.0   ug/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

005
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/O3/SP0293RA005.csv
iema
          VALOR_ORIGINAL UNIDADE            DATETIME
10228245           298.0   ug/m3 2020-11-09 15:00:00
11000030           285.0   ug/m3 2021-03-15 16:00:00
10228244           255.0   ug/m3 2020-11-09 14:00:00
7745680            242.0   ug/m3 2019-10-25 13:00:00
7745444            241.0   ug/m3 2019-10-14 15:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2019-03-10 01:00:00  2019    3   10     1    4.0             4.0   µg/m3
1 2019-03-10 02:00:00  2019    3   10     2   24.0            24.0   µg/m3
2 2019-03-10 03:00:00  2019    3   10     3   41.0            41.0   µg/m3
3 2019-03-10 04:00:00  2019    3   10     4   39.0            39.0   µg/m3
4 2019-03-10 05:00:00  2019    3   10     5   41.0            41.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2019-03-10 01:00:00  2019    3   10     1    4.0             4.0   ug/m3
1 2019-03-10 02:00:00  2019    3   10     2   24.0            24.0   ug/m3
2 2019-03-10 03:00:00  2019    3   10     3   41.0            41.0   ug/m3
3 2019-03-10 04:00:00  2019    3   10     4   39.0            39.0   ug/m3
4 2019-03-10 05:00:00  2019    3   10     5   41.0            41.0   ug/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

005
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/O3/SP0256RA005.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
17772314           173.0   ug/m3 2015-09-24 13:00:00
7494793            173.0   ug/m3 2017-09-13 15:00:00
7494470            173.0   ug/m3 2017-08-30 14:00:00
17772313           172.0   ug/m3 2015-09-24 12:00:00
7494471            172.0   ug/m3 2017-08-30 15:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2011-01-07 15:00:00  2011    1    7    15   30.0            30.0   µg/m3
1 2011-01-07 16:00:00  2011    1    7    16   36.0            36.0   µg/m3
2 2011-01-07 17:00:00  2011    1    7    17   34.0            34.0   µg/m3
3 2011-01-07 18:00:00  2011    1    7    18   37.0            37.0   µg/m3
4 2011-01-07 19:00:00  2011    1    7    19   32.0            32.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2011-01-07 15:00:00  2011    1    7    15   30.0            30.0   µg/m3
1 2011-01-07 16:00:00  2011    1    7    16   36.0            36.0   µg/m3
2 2011-01-07 17:00:00  2011    1    7    17   34.0            34.0   µg/m3
3 2011-01-07 18:00:00  2011    1    7    18   37.0            37.0   µg/m3
4 2011-01-07 19:00:00  2011    1    7    19   32.0            32.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
005
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/O3/SP0083RA005.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
13649883           296.0   ug/m3 2019-01-31 14:00:00
12822544           283.0   ug/m3 2020-11-27 13:00:00
19366770           268.0   ug/m3 2015-03-27 14:00:00
19366771           256.0   ug/m3 2015-03-27 15:00:00
12822131           256.0   ug/m3 2020-11-09 13:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1998-01-01 01:00:00  1998    1    1     1   38.0            38.0   µg/m3
1 1998-01-01 02:00:00  1998    1    1     2   37.0            37.0   µg/m3
2 1998-01-01 03:00:00  1998    1    1     3   35.0            35.0   µg/m3
3 1998-01-01 04:00:00  1998    1    1     4    NaN             NaN     NaN
4 1998-01-01 05:00:00  1998    1    1     5   53.0            53.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True     False
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1998-01-01 01:00:00  1998    1    1     1   38.0            38.0   µg/m3
1 1998-01-01 02:00:00  1998    1    1     2   37.0            37.0   µg/m3
2 1998-01-01 03:00:00  1998    1    1     3   35.0            35.0   µg/m3
3 1998-01-01 04:00:00  1998    1    1     4    NaN             NaN     NaN
4 1998-01-01 05:00:00  1998    1    1     5   53.0            53.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True     False
4          True      True
005
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/O3/RJ0025RA005.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
19603463      264.373339   µg/m3 2019-01-22 10:00:00
19984462      248.539877   µg/m3 2019-04-25 13:00:00
30826019      244.613497   µg/m3 2020-01-11 07:00:00
29100254      238.920245   µg/m3 2019-12-20 01:00:00
19603307      218.829085   µg/m3 2019-01-22 09:00:00
mma
             DATETIME     ANO  MES   DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2013-04-28 00:00:00  2013.0  4.0  28.0   0.0   0.98            0.98   µg/m³
1 2013-04-28 01:00:00  2013.0  4.0  28.0   1.0    NaN             NaN   µg/m³
2 2013-04-28 02:00:00  2013.0  4.0  28.0   2.0   0.78            0.78   µg/m³
3 2013-04-28 03:00:00  2013.0  4.0  28.0   3.0   0.78            0.78   µg/m³
4 2013-04-28 04:00:00  2013.0  4.0  28.0   4.0   0.78            0.78   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1         False     False
2          True      True
3          True      True
4          True      True
final
             DATETIME     ANO  MES   DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2013-04-28 00:00:00  2013.0  4.0  28.0   0.0   0.98            0.98   µg/m³
1 2013-04-28 01:00:00  2013.0  4.0  28.0   1.0    NaN             NaN   µg/m³
2 2013-04-28 02:00:00  2013.0  4.0  28.0   2.0   0.78            0.78   µg/m³
3 2013-04-28 03:00:00  2013.0  4.0  28.0   3.0   0.78            0.78   µg/m³
4 2013-04-28 04:00:00  2013.0  4.0  28.0   4.0   0.78            0.78   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True     False
2          True      True
3          True      True
4          True      True
005
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/O3/BA0011ND005.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
         VALOR_ORIGINAL UNIDADE            DATETIME
5349295      165.060134   ug/m3 2017-05-16 14:00:00
5351342      139.189310   ug/m3 2017-08-10 14:00:00
5349893      136.837416   ug/m3 2017-06-10 14:00:00
5353468      133.630290   ug/m3 2017-11-07 13:00:00
5348122      131.064588   ug/m3 2017-03-28 13:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1998-01-01 00:00:00  1998    1    1     0    NaN             NaN   ug/m³
1 1998-01-01 01:00:00  1998    1    1     1    NaN             NaN   ug/m³
2 1998-01-01 02:00:00  1998    1    1     2    NaN             NaN   ug/m³
3 1998-01-01 03:00:00  1998    1    1     3    NaN             NaN   ug/m³
4 1998-01-01 04:00:00  1998    1    1     4    NaN             NaN   ug/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1998-01-01 00:00:00  1998    1    1     0    NaN             NaN   ug/m³
1 1998-01-01 01:00:00  1998    1    1     1    NaN             NaN   ug/m³
2 1998-01-01 02:00:00  1998    1    1     2    NaN             NaN   ug/m³
3 1998-01-01 03:00:00  1998    1    1     3    NaN             NaN   ug/m³
4 1998-01-01 04:00:00  1998    1    1     4    NaN             NaN   ug/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
005
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/O3/RJ0225RA005.csv
iema
          VALOR_ORIGINAL UNIDADE            DATETIME
26947384            88.2     ppb 2015-02-27 16:30:00
26947383            83.5     ppb 2015-02-27 15:30:00
26947386            79.3     ppb 2015-02-27 18:30:00
26947385            78.3     ppb 2015-02-27 17:30:00
26947387            78.3     ppb 2015-02-27 19:30:00
mma
             DATETIME     ANO  MES   DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2013-04-28 00:00:00  2013.0  4.0  28.0   0.0   0.98            0.98   µg/m³
1 2013-04-28 01:00:00  2013.0  4.0  28.0   1.0    NaN             NaN   µg/m³
2 2013-04-28 02:00:00  2013.0  4.0  28.0   2.0   0.78            0.78   µg/m³
3 2013-04-28 03:00:00  2013.0  4.0  28.0   3.0   0.78            0.78   µg/m³
4 2013-04-28 04:00:00  2013.0  4.0  28.0   4.0   0.78            0.78   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1         False     False
2          True      True
3          True      True
4          True      True
final
             DATETIME     ANO  MES   DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2013-04-28 00:00:00  2013.0  4.0  28.0   0.0   0.98            0.98   µg/m³
1 2013-04-28 01:00:00  2013.0  4.0  28.0   1.0    NaN             NaN   µg/m³
2 2013-04-28 02:00:00  2013.0  4.0  28.0   2.0   0.78            0.78   µg/m³
3 2013-04-28 03:00:00  2013.0  4.0  28.0   3.0   0.78            0.78   µg/m³
4 2013-04-28 04:00:00  2013.0  4.0  28.0   4.0   0.78            0.78   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True     False
2          True      True
3          True      True
4          True      True

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

005
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/O3/RJ0070RA005.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
31211815      182.912011   µg/m3 2020-04-04 04:00:00
19898234      152.283782   µg/m3 2019-04-04 14:00:00
24889076      116.936400   ug/m3 2017-01-18 17:00:00
24889052      116.102100   ug/m3 2017-01-17 17:00:00
24889004      115.314900   ug/m3 2017-01-15 17:00:00
mma
             DATETIME     ANO   MES   DIA  HORA  VALOR  VALOR_ORIGINAL  \
0 2000-12-17 12:00:00  2000.0  12.0  17.0  12.0    NaN             NaN
1 2000-12-17 13:00:00  2000.0  12.0  17.0  13.0    NaN             NaN
2 2000-12-17 14:00:00  2000.0  12.0  17.0  14.0    NaN             NaN
3 2000-12-17 15:00:00  2000.0  12.0  17.0  15.0  29.06           29.06
4 2000-12-17 16:00:00  2000.0  12.0  17.0  16.0  17.63           17.63

  UNIDADE  QAQC_INTERNO  QAQC_MMA
0   µg/m³         False     False
1   µg/m³         False     False
2   µg/m³         False     False
3   µg/m³          True      True
4   µg/m³          True      True
final
             DATETIME     ANO   MES   DIA  HORA  VALOR  VALOR_ORIGINAL  \
0 2000-12-17 12:00:00  2000.0  12.0  17.0  12.0    NaN             NaN
1 2000-12-17 13:00:00  2000.0  12.0  17.0  13.0    NaN             NaN
2 2000-12-17 14:00:00  2000.0  12.0  17.0  14.0    NaN             NaN
3 2000-12-17 15:00:00  2000.0  12.0  17.0  15.0  29.06           29.06
4 2000-12-17 16:00:00  2000.0  12.0  17.0  16.0  17.63           17.63

  UNIDADE  QAQC_INTERNO  QAQC_MMA
0   µg/m³          True     False
1   µg/m³          True     False
2   µg/m³          True     False
3   µg/m³          True      True
4   µg/m³          True      True
005
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/O3/MG0017RA005.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
31716911         647.323   µg/m3 2020-01-14 16:30:00
33531165         189.450   µg/m3 2015-11-06 11:30:00
33531171         182.220   µg/m3 2015-10-21 13:30:00
33531172         180.660   µg/m3 2015-11-05 14:30:00
33531173         179.570   µg/m3 2015-11-06 13:30:00
mma
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2014-01-01 01:00:00  2014.0  1.0  1.0   1.0    NaN             NaN   µg/m3
1 2014-01-01 02:00:00  2014.0  1.0  1.0   2.0    NaN             NaN   µg/m3
2 2014-01-01 03:00:00  2014.0  1.0  1.0   3.0    NaN             NaN   µg/m3
3 2014-01-01 04:00:00  2014.0  1.0  1.0   4.0    NaN             NaN   µg/m3
4 2014-01-01 05:00:00  2014.0  1.0  1.0   5.0    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2014-01-01 01:00:00  2014.0  1.0  1.0   1.0    NaN             NaN   µg/m3
1 2014-01-01 02:00:00  2014.0  1.0  1.0   2.0    NaN             NaN   µg/m3
2 2014-01-01 03:00:00  2014.0  1.0  1.0   3.0    NaN             NaN   µg/m3
3 2014-01-01 04:00:00  2014.0  1.0  1.0   4.0    NaN             NaN   µg/m3
4 2014-01-01 05:00:00  2014.0  1.0  1.0   5.0    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
005
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/O3/MG0010RA005.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
40443928          234.79   µg/m3 2016-01-12 12:30:00
40443930          223.40   µg/m3 2016-01-12 13:30:00
34824481          195.99   µg/m3 2019-10-19 12:30:00
33426226          192.36   µg/m3 2015-03-05 14:30:00
32660163          190.09   µg/m3 2020-10-07 13:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2014-01-01 01:00:00  2014    1    1     1    NaN             NaN   µg/m3
1 2014-01-01 02:00:00  2014    1    1     2    NaN             NaN   µg/m3
2 2014-01-01 03:00:00  2014    1    1     3    NaN             NaN   µg/m3
3 2014-01-01 04:00:00  2014    1    1     4    NaN             NaN   µg/m3
4 2014-01-01 05:00:00  2014    1    1     5    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2014-01-01 01:00:00  2014    1    1     1    NaN             NaN   µg/m3
1 2014-01-01 02:00:00  2014    1    1     2    NaN             NaN   µg/m3
2 2014-01-01 03:00:00  2014    1    1     3    NaN             NaN   µg/m3
3 2014-01-01 04:00:00  2014    1    1     4    NaN             NaN   µg/m3
4 2014-01-01 05:00:00  2014    1    1     5    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
005
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/O3/RJ0038RA005.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
25227597        604.8557   ug/m3 2017-02-17 14:00:00
25232048        556.9480   ug/m3 2017-09-14 10:00:00
25231662        426.4758   ug/m3 2017-08-24 09:00:00
25229822        414.2085   ug/m3 2017-06-01 12:00:00
25230999        412.0435   ug/m3 2017-07-26 14:00:00
mma
             DATETIME     ANO  MES   DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2009-01-14 00:00:00  2009.0  1.0  14.0   0.0    NaN             NaN   µg/m³
1 2009-01-14 01:00:00  2009.0  1.0  14.0   1.0    NaN             NaN   µg/m³
2 2009-01-14 02:00:00  2009.0  1.0  14.0   2.0    NaN             NaN   µg/m³
3 2009-01-14 03:00:00  2009.0  1.0  14.0   3.0    NaN             NaN   µg/m³
4 2009-01-14 04:00:00  2009.0  1.0  14.0   4.0    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0         False     False
1         False     False
2         False     False
3         False     False
4         False     False
final
             DATETIME     ANO  MES   DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2009-01-14 00:00:00  2009.0  1.0  14.0   0.0    NaN             NaN   µg/m³
1 2009-01-14 01:00:00  2009.0  1.0  14.0   1.0    NaN             NaN   µg/m³
2 2009-01-14 02:00:00  2009.0  1.0  14.0   2.0    NaN             NaN   µg/m³
3 2009-01-14 03:00:00  2009.0  1.0  14.0   3.0    NaN             NaN   µg/m³
4 2009-01-14 04:00:00  2009.0  1.0  14.0   4.0    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
005
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/O3/RJ0051RA005.csv
iema
          VALOR_ORIGINAL UNIDADE            DATETIME
25642820          120.00   µg/m³ 2021-09-15 13:00:00
21270871          115.37   ug/m3 2021-09-15 12:00:00
25642822          110.26   µg/m³ 2021-09-14 15:00:00
21270873          109.96   ug/m3 2021-09-15 14:00:00
21270870          107.76   ug/m3 2021-09-15 11:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2020-02-12 12:00:00  2020    2   12    12  32.57           32.57   µg/m³
1 2020-02-12 13:00:00  2020    2   12    13    NaN             NaN   µg/m³
2 2020-02-12 14:00:00  2020    2   12    14  31.63           31.63   µg/m³
3 2020-02-12 15:00:00  2020    2   12    15  30.09           30.09   µg/m³
4 2020-02-12 16:00:00  2020    2   12    16  11.20           11.20   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1         False     False
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2020-02-12 12:00:00  2020    2   12    12  32.57           32.57   µg/m³
1 2020-02-12 13:00:00  2020    2   12    13    NaN             NaN   µg/m³
2 2020-02-12 14:00:00  2020    2   12    14  31.63           31.63   µg/m³
3 2020-02-12 15:00:00  2020    2   12    15  30.09           30.09   µg/m³
4 2020-02-12 16:00:00  2020    2   12    16  11.20           11.20   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True     False
2          True      True
3          True      True
4          True      True

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

005
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/O3/SP0269RA005.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
13229456           313.0   ug/m3 2019-02-01 12:00:00
17983852           253.0   ug/m3 2017-09-16 14:00:00
8494996            244.0   ug/m3 2022-03-09 14:00:00
8494975            235.0   ug/m3 2022-03-08 16:00:00
8494995            232.0   ug/m3 2022-03-09 13:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2012-09-01 01:00:00  2012    9    1     1    NaN             0.0   µg/m3
1 2012-09-01 02:00:00  2012    9    1     2    NaN             0.0   µg/m3
2 2012-09-01 03:00:00  2012    9    1     3    1.0             1.0   µg/m3
3 2012-09-01 04:00:00  2012    9    1     4    NaN             0.0   µg/m3
4 2012-09-01 05:00:00  2012    9    1     5    NaN             0.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True      True
3          True     False
4          True     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2012-09-01 01:00:00  2012    9    1     1    NaN             0.0   µg/m3
1 2012-09-01 02:00:00  2012    9    1     2    NaN             0.0   µg/m3
2 2012-09-01 03:00:00  2012    9    1     3    1.0             1.0   µg/m3
3 2012-09-01 04:00:00  2012    9    1     4    NaN             0.0   µg/m3
4 2012-09-01 05:00:00  2012    9    1     5    NaN             0.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True      True
3          True     False
4          True     False
005
005
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/O3/RJ0057RA005.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
19531551     1103.273620   µg/m3 2019-01-03 10:00:00
19644242      243.788957   µg/m3 2019-02-01 17:00:00
19644069      215.793865   µg/m3 2019-02-01 16:00:00
29469327      202.280000     ppb 2016-07-27 15:30:00
19643896      195.435583   µg/m3 2019-02-01 15:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2014-03-01 23:00:00  2014    3    1    23  56.99           56.99   µg/m³
1 2014-03-02 00:00:00  2014    3    2     0    NaN             NaN   µg/m³
2 2014-03-02 01:00:00  2014    3    2     1    NaN             NaN   µg/m³
3 2014-03-02 02:00:00  2014    3    2     2    NaN             NaN   µg/m³
4 2014-03-02 03:00:00  2014    3    2     3    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1         False     False
2         False     False
3         False     False
4         False     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2014-03-01 23:00:00  2014    3    1    23  56.99           56.99   µg/m³
1 2014-03-02 00:00:00  2014    3    2     0    NaN             NaN   µg/m³
2 2014-03-02 01:00:00  2014    3    2     1    NaN             NaN   µg/m³
3 2014-03-02 02:00:00  2014    3    2     2    NaN             NaN   µg/m³
4 2014-03-02 03:00:00  2014    3    2     3    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True     False
2          True     False
3          True     False
4          True     False
005
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/O3/RJ0027RA005.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
30850618      671.411043   µg/m3 2020-01-16 16:00:00
28448239      627.239264   µg/m3 2019-07-30 10:00:00
31004852      481.766871   µg/m3 2020-02-19 14:00:00
31004485      460.564417   µg/m3 2020-02-19 12:00:00
31005033      457.815951   µg/m3 2020-02-19 15:00:00
mma
             DATETIME     ANO  MES   DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2002-01-29 17:00:00  2002.0  1.0  29.0  17.0   3.85            3.85   µg/m³
1 2002-01-29 18:00:00  2002.0  1.0  29.0  18.0   3.86            3.86   µg/m³
2 2002-01-29 19:00:00  2002.0  1.0  29.0  19.0   1.94            1.94   µg/m³
3 2002-01-29 20:00:00  2002.0  1.0  29.0  20.0    NaN             NaN   µg/m³
4 2002-01-29 21:00:00  2002.0  1.0  29.0  21.0    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3         False     False
4         False     False
final
             DATETIME     ANO  MES   DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2002-01-29 17:00:00  2002.0  1.0  29.0  17.0   3.85            3.85   µg/m³
1 2002-01-29 18:00:00  2002.0  1.0  29.0  18.0   3.86            3.86   µg/m³
2 2002-01-29 19:00:00  2002.0  1.0  29.0  19.0   1.94            1.94   µg/m³
3 2002-01-29 20:00:00  2002.0  1.0  29.0  20.0    NaN             NaN   µg/m³
4 2002-01-29 21:00:00  2002.0  1.0  29.0  21.0    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True     False
4          True     False
005
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/O3/RJ0078RA005.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
24077478        159.5485   µg/m3 2020-11-18 16:00:00
23847869        152.5595   µg/m3 2020-10-03 13:00:00
24139636        151.4209   µg/m3 2020-12-01 14:00:00
23979926        150.5963   µg/m3 2020-10-29 15:00:00
23975303        149.7718   µg/m3 2020-10-28 17:00:00
mma
             DATETIME     ANO   MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1998-10-01 21:00:00  1998.0  10.0  1.0  21.0  34.65           34.65   µg/m³
1 1998-10-01 22:00:00  1998.0  10.0  1.0  22.0  36.69           36.69   µg/m³
2 1998-10-01 23:00:00  1998.0  10.0  1.0  23.0    NaN             NaN   µg/m³
3 1998-10-02 00:00:00  1998.0  10.0  2.0   0.0    NaN             NaN   µg/m³
4 1998-10-02 01:00:00  1998.0  10.0  2.0   1.0    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2         False     False
3         False     False
4         False     False
final
             DATETIME     ANO   MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1998-10-01 21:00:00  1998.0  10.0  1.0  21.0  34.65           34.65   µg/m³
1 1998-10-01 22:00:00  1998.0  10.0  1.0  22.0  36.69           36.69   µg/m³
2 1998-10-01 23:00:00  1998.0  10.0  1.0  23.0    NaN             NaN   µg/m³
3 1998-10-02 00:00:00  1998.0  10.0  2.0   0.0    NaN             NaN   µg/m³
4 1998-10-02 01:00:00  1998.0  10.0  2.0   1.0    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True     False
3          True     False
4          True     False
005
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/O3/RJ0033RA005.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
25203473        380.7632   ug/m3 2017-10-30 23:00:00
25203468        363.9554   ug/m3 2017-10-30 18:00:00
25203475        363.8538   ug/m3 2017-10-31 01:00:00
25203476        359.7811   ug/m3 2017-10-31 02:00:00
25203103        356.3743   ug/m3 2017-10-12 11:00:00
mma
             DATETIME     ANO  MES   DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2006-05-12 12:00:00  2006.0  5.0  12.0  12.0  42.19           42.19   µg/m³
1 2006-05-12 13:00:00  2006.0  5.0  12.0  13.0  43.66           43.66   µg/m³
2 2006-05-12 14:00:00  2006.0  5.0  12.0  14.0  45.02           45.02   µg/m³
3 2006-05-12 15:00:00  2006.0  5.0  12.0  15.0  33.02           33.02   µg/m³
4 2006-05-12 16:00:00  2006.0  5.0  12.0  16.0  21.24           21.24   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME     ANO  MES   DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2006-05-12 12:00:00  2006.0  5.0  12.0  12.0  42.19           42.19   µg/m³
1 2006-05-12 13:00:00  2006.0  5.0  12.0  13.0  43.66           43.66   µg/m³
2 2006-05-12 14:00:00  2006.0  5.0  12.0  14.0  45.02           45.02   µg/m³
3 2006-05-12 15:00:00  2006.0  5.0  12.0  15.0  33.02           33.02   µg/m³
4 2006-05-12 16:00:00  2006.0  5.0  12.0  16.0  21.24           21.24   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
005
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/O3/BA0001ND005.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
         VALOR_ORIGINAL UNIDADE            DATETIME
5206943       92.151448   ug/m3 2017-05-16 12:00:00
5206944       92.151448   ug/m3 2017-05-16 13:00:00
5206942       88.944321   ug/m3 2017-05-16 11:00:00
5208856       85.523385   ug/m3 2017-08-04 13:00:00
5206945       78.040089   ug/m3 2017-05-16 14:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1998-01-01 00:00:00  1998    1    1     0    NaN             NaN   ug/m³
1 1998-01-01 01:00:00  1998    1    1     1    NaN             NaN   ug/m³
2 1998-01-01 02:00:00  1998    1    1     2    NaN             NaN   ug/m³
3 1998-01-01 03:00:00  1998    1    1     3    NaN             NaN   ug/m³
4 1998-01-01 04:00:00  1998    1    1     4    NaN             NaN   ug/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1998-01-01 00:00:00  1998    1    1     0    NaN             NaN   ug/m³
1 1998-01-01 01:00:00  1998    1    1     1    NaN             NaN   ug/m³
2 1998-01-01 02:00:00  1998    1    1     2    NaN             NaN   ug/m³
3 1998-01-01 03:00:00  1998    1    1     3    NaN             NaN   ug/m³
4 1998-01-01 04:00:00  1998    1    1     4    NaN             NaN   ug/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
005
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/O3/RJ0222RA005.csv
iema
          VALOR_ORIGINAL UNIDADE            DATETIME
29652732         177.294   ug/m3 2016-03-06 13:30:00
29652317         158.265   ug/m3 2016-02-10 14:30:00
29652316         156.137   ug/m3 2016-02-10 13:30:00
29652733         146.828   ug/m3 2016-03-06 14:30:00
29652532         141.909   ug/m3 2016-02-19 14:30:00
mma
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2023-06-06 17:00:00  2023.0  6.0  6.0  17.0    NaN             NaN   µg/m³
1 2023-06-06 18:00:00  2023.0  6.0  6.0  18.0    NaN             NaN   µg/m³
2 2023-06-06 19:00:00  2023.0  6.0  6.0  19.0    NaN             NaN   µg/m³
3 2023-06-06 20:00:00  2023.0  6.0  6.0  20.0    NaN             NaN   µg/m³
4 2023-06-06 21:00:00  2023.0  6.0  6.0  21.0    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0         False     False
1         False     False
2         False     False
3         False     False
4         False     False
final
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2023-06-06 17:00:00  2023.0  6.0  6.0  17.0    NaN             NaN   µg/m³
1 2023-06-06 18:00:00  2023.0  6.0  6.0  18.0    NaN             NaN   µg/m³
2 2023-06-06 19:00:00  2023.0  6.0  6.0  19.0    NaN             NaN   µg/m³
3 2023-06-06 20:00:00  2023.0  6.0  6.0  20.0    NaN             NaN   µg/m³
4 2023-06-06 21:00:00  2023.0  6.0  6.0  21.0    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
005

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/O3/MG0013RA005.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
33480983          166.37   µg/m3 2015-09-26 12:30:00
33480986          161.30   µg/m3 2015-10-21 15:30:00
33480987          160.45   µg/m3 2015-09-26 13:30:00
33480989          157.95   µg/m3 2015-09-26 14:30:00
33480990          157.02   µg/m3 2015-10-21 12:30:00
mma
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2014-01-01 01:00:00  2014.0  1.0  1.0   1.0  16.44           16.44   µg/m3
1 2014-01-01 02:00:00  2014.0  1.0  1.0   2.0  14.68           14.68   µg/m3
2 2014-01-01 03:00:00  2014.0  1.0  1.0   3.0  12.53           12.53   µg/m3
3 2014-01-01 04:00:00  2014.0  1.0  1.0   4.0  12.80           12.80   µg/m3
4 2014-01-01 05:00:00  2014.0  1.0  1.0   5.0  14.25           14.25   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2014-01-01 01:00:00  2014.0  1.0  1.0   1.0  16.44           16.44   µg/m3
1 2014-01-01 02:00:00  2014.0  1.0  1.0   2.0  14.68           14.68   µg/m3
2 2014-01-01 03:00:00  2014.0  1.0  1.0   3.0  12.53           12.53   µg/m3
3 2014-01-01 04:00:00  2014.0  1.0  1.0   4.0  12.80           12.80   µg/m3
4 2014-01-01 05:00:00  2014.0  1.0  1.0   5.0  14.25           14.25   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
005
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/O3/MG0004RA005.csv

/tmp/ipykernel_273420/1352582357.py:97: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  df_mma = pd.read_csv(arquivo, encoding = 'UTF-8')
/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
31676174         457.637   µg/m3 2020-01-02 11:30:00
31674871         448.222   µg/m3 2020-01-02 01:30:00
34679661         201.020   µg/m3 2019-09-11 16:30:00
33080973         199.380   µg/m3 2015-11-06 12:30:00
33080977         188.840   µg/m3 2015-11-06 11:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR VALOR_ORIGINAL UNIDADE  \
0 2009-01-01 01:00:00  2009    1    1     1    9.2            9.2     ppb
1 2009-01-01 02:00:00  2009    1    1     2    2.0              2     ppb
2 2009-01-01 03:00:00  2009    1    1     3    1.5            1.5     ppb
3 2009-01-01 04:00:00  2009    1    1     4    1.5            1.5     ppb
4 2009-01-01 05:00:00  2009    1    1     5    5.2            5.2     ppb

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR VALOR_ORIGINAL UNIDADE  \
0 2009-01-01 01:00:00  2009    1    1     1    9.2            9.2     ppb
1 2009-01-01 02:00:00  2009    1    1     2    2.0              2     ppb
2 2009-01-01 03:00:00  2009    1    1     3    1.5            1.5     ppb
3 2009-01-01 04:00:00  2009    1    1     4    1.5            1.5     ppb
4 2009-01-01 05:00:00  2009    1    1     5    5.2            5.2     ppb

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
005
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/O3/SP0110RA005.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
19471368           175.0   ug/m3 2015-11-13 16:00:00
13767963           163.0   ug/m3 2019-09-19 14:00:00
19470361           163.0   ug/m3 2015-09-24 12:00:00
13767964           163.0   ug/m3 2019-09-19 15:00:00
19470854           161.0   ug/m3 2015-10-16 11:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2008-09-25 01:00:00  2008    9   25     1   27.0            27.0   µg/m3
1 2008-09-25 02:00:00  2008    9   25     2   28.0            28.0   µg/m3
2 2008-09-25 03:00:00  2008    9   25     3   25.0            25.0   µg/m3
3 2008-09-25 04:00:00  2008    9   25     4   23.0            23.0   µg/m3
4 2008-09-25 05:00:00  2008    9   25     5   22.0            22.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2008-09-25 01:00:00  2008    9   25     1   27.0            27.0   µg/m3
1 2008-09-25 02:00:00  2008    9   25     2   28.0            28.0   µg/m3
2 2008-09-25 03:00:00  2008    9   25     3   25.0            25.0   µg/m3
3 2008-09-25 04:00:00  2008    9   25     4   23.0            23.0   µg/m3
4 2008-09-25 05:00:00  2008    9   25     5   22.0            22.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
005
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/O3/RJ0031RA005.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
30941650      952.674797   µg/m3 2020-02-05 12:00:00
30929357      809.766822   µg/m3 2020-02-02 19:00:00
30930479      675.597368   µg/m3 2020-02-03 01:00:00
30927602      628.436381   µg/m3 2020-02-02 10:00:00
20221997      593.267515   µg/m3 2019-06-21 11:00:00
mma
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2004-03-01 12:00:00  2004.0  3.0  1.0  12.0    NaN             NaN   µg/m³
1 2004-03-01 13:00:00  2004.0  3.0  1.0  13.0    NaN             NaN   µg/m³
2 2004-03-01 14:00:00  2004.0  3.0  1.0  14.0    NaN             NaN   µg/m³
3 2004-03-01 15:00:00  2004.0  3.0  1.0  15.0    NaN             NaN   µg/m³
4 2004-03-01 16:00:00  2004.0  3.0  1.0  16.0    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0         False     False
1         False     False
2         False     False
3         False     False
4         False     False
final
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2004-03-01 12:00:00  2004.0  3.0  1.0  12.0    NaN             NaN   µg/m³
1 2004-03-01 13:00:00  2004.0  3.0  1.0  13.0    NaN             NaN   µg/m³
2 2004-03-01 14:00:00  2004.0  3.0  1.0  14.0    NaN             NaN   µg/m³
3 2004-03-01 15:00:00  2004.0  3.0  1.0  15.0    NaN             NaN   µg/m³
4 2004-03-01 16:00:00  2004.0  3.0  1.0  16.0    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
005
005
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/O3/RJ0064RA005.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
25399825        236.1437   ug/m3 2017-12-23 15:00:00
25399826        204.4377   ug/m3 2017-12-23 16:00:00
25399850        198.5829   ug/m3 2017-12-24 16:00:00
25399824        198.3448   ug/m3 2017-12-23 14:00:00
25399827        196.6266   ug/m3 2017-12-23 17:00:00
mma
             DATETIME     ANO  MES   DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2016-06-29 14:00:00  2016.0  6.0  29.0  14.0    NaN             NaN   µg/m³
1 2016-06-29 15:00:00  2016.0  6.0  29.0  15.0  36.05           36.05   µg/m³
2 2016-06-29 16:00:00  2016.0  6.0  29.0  16.0  32.91           32.91   µg/m³
3 2016-06-29 17:00:00  2016.0  6.0  29.0  17.0  30.01           30.01   µg/m³
4 2016-06-29 18:00:00  2016.0  6.0  29.0  18.0  26.19           26.19   µg/m³

   QAQC_INTERNO  QAQC_MMA
0         False     False
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME     ANO  MES   DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2016-06-29 14:00:00  2016.0  6.0  29.0  14.0    NaN             NaN   µg/m³
1 2016-06-29 15:00:00  2016.0  6.0  29.0  15.0  36.05           36.05   µg/m³
2 2016-06-29 16:00:00  2016.0  6.0  29.0  16.0  32.91           32.91   µg/m³
3 2016-06-29 17:00:00  2016.0  6.0  29.0  17.0  30.01           30.01   µg/m³
4 2016-06-29 18:00:00  2016.0  6.0  29.0  18.0  26.19           26.19   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True      True
2          True      True
3          True      True
4          True      True
005
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/O3/SP0065RA005.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
13904541           302.0   ug/m3 2019-02-02 15:00:00
13904542           291.0   ug/m3 2019-02-02 16:00:00
13904679           280.0   ug/m3 2019-02-08 15:00:00
13904678           259.0   ug/m3 2019-02-08 14:00:00
9161111            258.0   ug/m3 2022-12-10 11:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1998-01-01 01:00:00  1998    1    1     1   40.0            40.0   µg/m3
1 1998-01-01 02:00:00  1998    1    1     2   43.0            43.0   µg/m3
2 1998-01-01 03:00:00  1998    1    1     3   40.0            40.0   µg/m3
3 1998-01-01 04:00:00  1998    1    1     4    NaN             NaN     NaN
4 1998-01-01 05:00:00  1998    1    1     5   48.0            48.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True     False
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1998-01-01 01:00:00  1998    1    1     1   40.0            40.0   µg/m3
1 1998-01-01 02:00:00  1998    1    1     2   43.0            43.0   µg/m3
2 1998-01-01 03:00:00  1998    1    1     3   40.0            40.0   µg/m3
3 1998-01-01 04:00:00  1998    1    1     4    NaN             NaN     NaN
4 1998-01-01 05:00:00  1998    1    1     5   48.0            48.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True     False
4          True      True
005
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/O3/MG0055RA005.csv
iema
          VALOR_ORIGINAL UNIDADE            DATETIME
38232676           236.1   µg/m3 2021-09-30 12:30:00
38232848           231.5   µg/m3 2021-09-30 13:30:00
38173026           219.4   µg/m3 2021-09-15 10:30:00
38233012           209.6   µg/m3 2021-09-30 14:30:00
38173371           209.0   µg/m3 2021-09-15 12:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2022-01-01 01:00:00  2022    1    1     1    NaN             NaN   µg/m3
1 2022-01-01 02:00:00  2022    1    1     2    NaN             NaN   µg/m3
2 2022-01-01 03:00:00  2022    1    1     3    NaN             NaN   µg/m3
3 2022-01-01 04:00:00  2022    1    1     4    NaN             NaN   µg/m3
4 2022-01-01 05:00:00  2022    1    1     5    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2022-01-01 01:00:00  2022    1    1     1    NaN             NaN   µg/m3
1 2022-01-01 02:00:00  2022    1    1     2    NaN             NaN   µg/m3
2 2022-01-01 03:00:00  2022    1    1     3    NaN             NaN   µg/m3
3 2022-01-01 04:00:00  2022    1    1     4    NaN             NaN   µg/m3
4 2022-01-01 05:00:00  2022    1    1     5    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

005
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/O3/SP0114RA005.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
6981099            171.0   ug/m3 2017-10-13 17:00:00
6981098            165.0   ug/m3 2017-10-13 16:00:00
11105221           162.0   ug/m3 2021-09-07 17:00:00
6981097            160.0   ug/m3 2017-10-13 15:00:00
6981100            158.0   ug/m3 2017-10-13 18:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2008-05-15 03:00:00  2008    5   15     3   26.0            26.0   µg/m3
1 2008-05-15 04:00:00  2008    5   15     4   25.0            25.0   µg/m3
2 2008-05-15 05:00:00  2008    5   15     5   23.0            23.0   µg/m3
3 2008-05-15 06:00:00  2008    5   15     6   19.0            19.0   µg/m3
4 2008-05-15 07:00:00  2008    5   15     7   13.0            13.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2008-05-15 03:00:00  2008    5   15     3   26.0            26.0   µg/m3
1 2008-05-15 04:00:00  2008    5   15     4   25.0            25.0   µg/m3
2 2008-05-15 05:00:00  2008    5   15     5   23.0            23.0   µg/m3
3 2008-05-15 06:00:00  2008    5   15     6   19.0            19.0   µg/m3
4 2008-05-15 07:00:00  2008    5   15     7   13.0            13.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
005
005
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/O3/RJ0054RA005.csv
iema
          VALOR_ORIGINAL UNIDADE            DATETIME
29823858          590.33   µg/m³ 2022-02-15 18:00:00
25610725          539.49   µg/m³ 2021-08-02 16:00:00
25610726          476.30   µg/m³ 2021-11-24 17:00:00
25610727          376.02   µg/m³ 2021-08-02 17:00:00
29830709          320.26   µg/m³ 2022-12-07 14:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2021-03-12 16:00:00  2021    3   12    16  13.18           13.18   µg/m³
1 2021-03-12 17:00:00  2021    3   12    17  10.79           10.79   µg/m³
2 2021-03-12 18:00:00  2021    3   12    18   8.47            8.47   µg/m³
3 2021-03-12 19:00:00  2021    3   12    19   8.14            8.14   µg/m³
4 2021-03-12 20:00:00  2021    3   12    20   9.05            9.05   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2021-03-12 16:00:00  2021    3   12    16  13.18           13.18   µg/m³
1 2021-03-12 17:00:00  2021    3   12    17  10.79           10.79   µg/m³
2 2021-03-12 18:00:00  2021    3   12    18   8.47            8.47   µg/m³
3 2021-03-12 19:00:00  2021    3   12    19   8.14            8.14   µg/m³
4 2021-03-12 20:00:00  2021    3   12    20   9.05            9.05   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

005
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/O3/RJ0030RA005.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
25038105        545.0332   ug/m3 2017-05-26 11:00:00
25039767        373.3743   ug/m3 2017-08-14 13:00:00
25039766        367.0045   ug/m3 2017-08-14 12:00:00
25039765        355.0981   ug/m3 2017-08-14 11:00:00
24278883        350.1843   µg/m3 2020-12-30 17:00:00
mma
             DATETIME     ANO   MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2001-11-03 00:00:00  2001.0  11.0  3.0   0.0    NaN             0.0   µg/m³
1 2001-11-03 01:00:00  2001.0  11.0  3.0   1.0    NaN             0.0   µg/m³
2 2001-11-03 02:00:00  2001.0  11.0  3.0   2.0    NaN             0.0   µg/m³
3 2001-11-03 03:00:00  2001.0  11.0  3.0   3.0    NaN             0.0   µg/m³
4 2001-11-03 04:00:00  2001.0  11.0  3.0   4.0    NaN             0.0   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME     ANO   MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2001-11-03 00:00:00  2001.0  11.0  3.0   0.0    NaN             0.0   µg/m³
1 2001-11-03 01:00:00  2001.0  11.0  3.0   1.0    NaN             0.0   µg/m³
2 2001-11-03 02:00:00  2001.0  11.0  3.0   2.0    NaN             0.0   µg/m³
3 2001-11-03 03:00:00  2001.0  11.0  3.0   3.0    NaN             0.0   µg/m³
4 2001-11-03 04:00:00  2001.0  11.0  3.0   4.0    NaN             0.0   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
005
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/O3/RJ0020RA005.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
19917258      425.226994   µg/m3 2019-04-09 06:00:00
19607314      320.981595   µg/m3 2019-01-23 11:00:00
19980128      295.460123   µg/m3 2019-04-24 12:00:00
28644951      190.233129   µg/m3 2019-09-12 18:00:00
23744176      174.920200   µg/m3 2020-09-12 15:00:00
mma
             DATETIME     ANO  MES   DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2013-05-30 01:00:00  2013.0  5.0  30.0   1.0   8.36            8.36   µg/m³
1 2013-05-30 02:00:00  2013.0  5.0  30.0   2.0   5.39            5.39   µg/m³
2 2013-05-30 03:00:00  2013.0  5.0  30.0   3.0   1.00            1.00   µg/m³
3 2013-05-30 04:00:00  2013.0  5.0  30.0   4.0  32.88           32.88   µg/m³
4 2013-05-30 05:00:00  2013.0  5.0  30.0   5.0  33.61           33.61   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME     ANO  MES   DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2013-05-30 01:00:00  2013.0  5.0  30.0   1.0   8.36            8.36   µg/m³
1 2013-05-30 02:00:00  2013.0  5.0  30.0   2.0   5.39            5.39   µg/m³
2 2013-05-30 03:00:00  2013.0  5.0  30.0   3.0   1.00            1.00   µg/m³
3 2013-05-30 04:00:00  2013.0  5.0  30.0   4.0  32.88           32.88   µg/m³
4 2013-05-30 05:00:00  2013.0  5.0  30.0   5.0  33.61           33.61   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
005
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/O3/RJ0029RA005.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
31510609     1199.803681   µg/m3 2020-06-03 18:00:00
31351073     1197.801227   µg/m3 2020-05-02 07:00:00
31512499     1196.957055   µg/m3 2020-06-04 03:00:00
31529972     1195.622086   µg/m3 2020-06-07 13:00:00
31525655     1194.876074   µg/m3 2020-06-06 17:00:00
mma
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2011-05-01 00:00:00  2011.0  5.0  1.0   0.0  41.20           41.20   µg/m³
1 2011-05-01 01:00:00  2011.0  5.0  1.0   1.0  41.20           41.20   µg/m³
2 2011-05-01 02:00:00  2011.0  5.0  1.0   2.0    NaN             NaN   µg/m³
3 2011-05-01 03:00:00  2011.0  5.0  1.0   3.0  41.20           41.20   µg/m³
4 2011-05-01 04:00:00  2011.0  5.0  1.0   4.0  19.62           19.62   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2         False     False
3          True      True
4          True      True
final
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2011-05-01 00:00:00  2011.0  5.0  1.0   0.0  41.20           41.20   µg/m³
1 2011-05-01 01:00:00  2011.0  5.0  1.0   1.0  41.20           41.20   µg/m³
2 2011-05-01 02:00:00  2011.0  5.0  1.0   2.0    NaN             NaN   µg/m³
3 2011-05-01 03:00:00  2011.0  5.0  1.0   3.0  41.20           41.20   µg/m³
4 2011-05-01 04:00:00  2011.0  5.0  1.0   4.0  19.62           19.62   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True     False
3          True      True
4          True      True
005
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/O3/SP0113RA005.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
17364433           223.0   ug/m3 2015-01-14 16:00:00
17370275           210.0   ug/m3 2015-10-16 14:00:00
17364432           194.0   ug/m3 2015-01-14 15:00:00
7834262            191.0   ug/m3 2019-10-04 17:00:00
17364434           190.0   ug/m3 2015-01-14 17:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2008-09-02 21:00:00  2008    9    2    21   15.0            15.0   µg/m3
1 2008-09-02 22:00:00  2008    9    2    22    4.0             4.0   µg/m3
2 2008-09-02 23:00:00  2008    9    2    23    4.0             4.0   µg/m3
3 2008-09-03 00:00:00  2008    9    3     0    1.0             1.0   µg/m3
4 2008-09-03 01:00:00  2008    9    3     1    NaN             0.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2008-09-02 21:00:00  2008    9    2    21   15.0            15.0   µg/m3
1 2008-09-02 22:00:00  2008    9    2    22    4.0             4.0   µg/m3
2 2008-09-02 23:00:00  2008    9    2    23    4.0             4.0   µg/m3
3 2008-09-03 00:00:00  2008    9    3     0    1.0             1.0   µg/m3
4 2008-09-03 01:00:00  2008    9    3     1    NaN             0.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True     False
005
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/O3/SP0107RA005.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
13948652           156.0   ug/m3 2016-09-17 17:00:00
13948651           155.0   ug/m3 2016-09-17 16:00:00
17815484           152.0   ug/m3 2017-08-31 17:00:00
12333053           152.0   ug/m3 2020-10-05 15:00:00
12333052           150.0   ug/m3 2020-10-05 14:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2008-08-20 01:00:00  2008    8   20     1   45.0            45.0   µg/m3
1 2008-08-20 02:00:00  2008    8   20     2    NaN             NaN     NaN
2 2008-08-20 03:00:00  2008    8   20     3   57.0            57.0   µg/m3
3 2008-08-20 04:00:00  2008    8   20     4   65.0            65.0   µg/m3
4 2008-08-20 05:00:00  2008    8   20     5   64.0            64.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True     False
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2008-08-20 01:00:00  2008    8   20     1   45.0            45.0   µg/m3
1 2008-08-20 02:00:00  2008    8   20     2    NaN             NaN     NaN
2 2008-08-20 03:00:00  2008    8   20     3   57.0            57.0   µg/m3
3 2008-08-20 04:00:00  2008    8   20     4   65.0            65.0   µg/m3
4 2008-08-20 05:00:00  2008    8   20     5   64.0            64.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True     False
2          True      True
3          True      True
4          True      True
005
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/O3/MG0003RA005.csv

/tmp/ipykernel_273420/1352582357.py:97: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  df_mma = pd.read_csv(arquivo, encoding = 'UTF-8')
/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
36892778          206.09   µg/m3 2018-10-01 15:30:00
36892922          189.72   µg/m3 2018-10-01 16:30:00
36892092          186.38   µg/m3 2018-10-01 10:30:00
35124474          176.35   µg/m3 2017-06-21 07:30:00
36893066          175.04   µg/m3 2018-10-01 17:30:00
mma
             DATETIME     ANO  MES  DIA  HORA  VALOR VALOR_ORIGINAL UNIDADE  \
0 2009-01-01 01:00:00  2009.0  1.0  1.0   1.0    6.2            6.2     ppb
1 2009-01-01 02:00:00  2009.0  1.0  1.0   2.0   15.5           15.5     ppb
2 2009-01-01 03:00:00  2009.0  1.0  1.0   3.0   11.8           11.8     ppb
3 2009-01-01 04:00:00  2009.0  1.0  1.0   4.0   12.2           12.2     ppb
4 2009-01-01 05:00:00  2009.0  1.0  1.0   5.0   12.2           12.2     ppb

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME     ANO  MES  DIA  HORA  VALOR VALOR_ORIGINAL UNIDADE  \
0 2009-01-01 01:00:00  2009.0  1.0  1.0   1.0    6.2            6.2     ppb
1 2009-01-01 02:00:00  2009.0  1.0  1.0   2.0   15.5           15.5     ppb
2 2009-01-01 03:00:00  2009.0  1.0  1.0   3.0   11.8           11.8     ppb
3 2009-01-01 04:00:00  2009.0  1.0  1.0   4.0   12.2           12.2     ppb
4 2009-01-01 05:00:00  2009.0  1.0  1.0   5.0   12.2           12.2     ppb

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
005
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/O3/SP0281RA005.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
13823803           195.0   ug/m3 2019-10-03 17:00:00
9977960            193.0   ug/m3 2018-12-21 15:00:00
9977959            193.0   ug/m3 2018-12-21 14:00:00
12977988           190.0   ug/m3 2020-09-29 13:00:00
13823804           187.0   ug/m3 2019-10-03 18:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2016-01-01 01:00:00  2016    1    1     1   31.0            31.0   µg/m3
1 2016-01-01 02:00:00  2016    1    1     2   28.0            28.0   µg/m3
2 2016-01-01 03:00:00  2016    1    1     3   27.0            27.0   µg/m3
3 2016-01-01 04:00:00  2016    1    1     4   30.0            30.0   µg/m3
4 2016-01-01 05:00:00  2016    1    1     5   28.0            28.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2016-01-01 01:00:00  2016    1    1     1   31.0            31.0   ug/m3
1 2016-01-01 02:00:00  2016    1    1     2   28.0            28.0   ug/m3
2 2016-01-01 03:00:00  2016    1    1     3   27.0            27.0   ug/m3
3 2016-01-01 04:00:00  2016    1    1     4   30.0            30.0   ug/m3
4 2016-01-01 05:00:00  2016    1    1     5   28.0            28.0   ug/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
005
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/O3/RJ0039RA005.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
25271028        307.4003   ug/m3 2017-08-01 13:00:00
25268143        306.3464   ug/m3 2017-03-28 11:00:00
25269144        263.1934   ug/m3 2017-05-09 12:00:00
25271691        255.1307   ug/m3 2017-08-29 12:00:00
25270372        220.0646   ug/m3 2017-07-03 11:00:00
mma
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2007-02-01 00:00:00  2007.0  2.0  1.0   0.0  22.32           22.32   µg/m³
1 2007-02-01 01:00:00  2007.0  2.0  1.0   1.0  19.24           19.24   µg/m³
2 2007-02-01 02:00:00  2007.0  2.0  1.0   2.0  13.48           13.48   µg/m³
3 2007-02-01 03:00:00  2007.0  2.0  1.0   3.0  16.16           16.16   µg/m³
4 2007-02-01 04:00:00  2007.0  2.0  1.0   4.0  16.16           16.16   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2007-02-01 00:00:00  2007.0  2.0  1.0   0.0  22.32           22.32   µg/m³
1 2007-02-01 01:00:00  2007.0  2.0  1.0   1.0  19.24           19.24   µg/m³
2 2007-02-01 02:00:00  2007.0  2.0  1.0   2.0  13.48           13.48   µg/m³
3 2007-02-01 03:00:00  2007.0  2.0  1.0   3.0  16.16           16.16   µg/m³
4 2007-02-01 04:00:00  2007.0  2.0  1.0   4.0  16.16           16.16   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
005
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/O3/RJ0223RA005.csv
iema
          VALOR_ORIGINAL UNIDADE            DATETIME
26987877            65.2     ppb 2015-11-20 14:30:00
26987878            60.1     ppb 2015-11-20 15:30:00
26987855            53.7     ppb 2015-11-19 16:30:00
26987854            52.2     ppb 2015-11-19 15:30:00
26987879            52.2     ppb 2015-11-20 16:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2015-08-20 20:00:00  2015    8   20    20  15.89           15.89   µg/m³
1 2015-08-20 21:00:00  2015    8   20    21  18.05           18.05   µg/m³
2 2015-08-20 22:00:00  2015    8   20    22  17.46           17.46   µg/m³
3 2015-08-20 23:00:00  2015    8   20    23  17.46           17.46   µg/m³
4 2015-08-21 00:00:00  2015    8   21     0  12.95           12.95   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2015-08-20 20:00:00  2015    8   20    20  15.89           15.89   µg/m³
1 2015-08-20 21:00:00  2015    8   20    21  18.05           18.05   µg/m³
2 2015-08-20 22:00:00  2015    8   20    22  17.46           17.46   µg/m³
3 2015-08-20 23:00:00  2015    8   20    23  17.46           17.46   µg/m³
4 2015-08-21 00:00:00  2015    8   21     0  12.95           12.95   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
005

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

005
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/O3/RJ0023RA005.csv
iema
          VALOR_ORIGINAL UNIDADE            DATETIME
19614552      375.553331   µg/m3 2019-01-25 09:00:00
28644406      311.950920   µg/m3 2019-09-12 15:00:00
28617152      309.398773   µg/m3 2019-09-06 11:00:00
25453149      277.688100   ug/m3 2017-02-08 21:00:00
19914749      258.527481   µg/m3 2019-04-08 15:00:00
mma
             DATETIME     ANO  MES   DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2013-04-15 16:00:00  2013.0  4.0  15.0  16.0  40.15           40.15   µg/m³
1 2013-04-15 17:00:00  2013.0  4.0  15.0  17.0  26.11           26.11   µg/m³
2 2013-04-15 18:00:00  2013.0  4.0  15.0  18.0  17.05           17.05   µg/m³
3 2013-04-15 19:00:00  2013.0  4.0  15.0  19.0   5.35            5.35   µg/m³
4 2013-04-15 20:00:00  2013.0  4.0  15.0  20.0   5.75            5.75   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME     ANO  MES   DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2013-04-15 16:00:00  2013.0  4.0  15.0  16.0  40.15           40.15   µg/m³
1 2013-04-15 17:00:00  2013.0  4.0  15.0  17.0  26.11           26.11   µg/m³
2 2013-04-15 18:00:00  2013.0  4.0  15.0  18.0  17.05           17.05   µg/m³
3 2013-04-15 19:00:00  2013.0  4.0  15.0  19.0   5.35            5.35   µg/m³
4 2013-04-15 20:00:00  2013.0  4.0  15.0  20.0   5.75            5.75   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

005
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/O3/MG0035RA005.csv
iema
          VALOR_ORIGINAL UNIDADE            DATETIME
35910408          160.92   µg/m3 2017-08-10 19:30:00
35910409          160.05   µg/m3 2017-10-15 18:30:00
35910412          159.49   µg/m3 2017-10-15 19:30:00
35910413          156.54   µg/m3 2017-08-10 17:30:00
35910414          154.99   µg/m3 2017-08-10 18:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2017-01-01 01:00:00  2017    1    1     1    NaN             NaN   µg/m3
1 2017-01-01 02:00:00  2017    1    1     2    NaN             NaN   µg/m3
2 2017-01-01 03:00:00  2017    1    1     3    NaN             NaN   µg/m3
3 2017-01-01 04:00:00  2017    1    1     4    NaN             NaN   µg/m3
4 2017-01-01 05:00:00  2017    1    1     5    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2017-01-01 01:00:00  2017    1    1     1    NaN             NaN   µg/m3
1 2017-01-01 02:00:00  2017    1    1     2    NaN             NaN   µg/m3
2 2017-01-01 03:00:00  2017    1    1     3    NaN             NaN   µg/m3
3 2017-01-01 04:00:00  2017    1    1     4    NaN             NaN   µg/m3
4 2017-01-01 05:00:00  2017    1    1     5    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

005
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/O3/SP0248RA005.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
19009927           195.0   ug/m3 2015-10-16 12:00:00
13282151           184.0   ug/m3 2019-09-13 14:00:00
13282150           181.0   ug/m3 2019-09-13 13:00:00
18058384           177.0   ug/m3 2017-08-31 13:00:00
15688125           176.0   ug/m3 2021-09-25 14:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2009-04-15 01:00:00  2009    4   15     1    5.0             5.0   µg/m3
1 2009-04-15 02:00:00  2009    4   15     2    6.0             6.0   µg/m3
2 2009-04-15 03:00:00  2009    4   15     3    1.0             1.0   µg/m3
3 2009-04-15 04:00:00  2009    4   15     4    2.0             2.0   µg/m3
4 2009-04-15 05:00:00  2009    4   15     5    NaN             0.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2009-04-15 01:00:00  2009    4   15     1    5.0             5.0   µg/m3
1 2009-04-15 02:00:00  2009    4   15     2    6.0             6.0   µg/m3
2 2009-04-15 03:00:00  2009    4   15     3    1.0             1.0   µg/m3
3 2009-04-15 04:00:00  2009    4   15     4    2.0             2.0   µg/m3
4 2009-04-15 05:00:00  2009    4   15     5    NaN             0.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True     False
005
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/O3/SP0064RA005.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
17563459           243.0   ug/m3 2015-01-13 14:00:00
17563461           239.0   ug/m3 2015-01-13 16:00:00
16838567           239.0   ug/m3 2022-10-05 13:00:00
8077263            227.0   ug/m3 2019-01-11 15:00:00
8077696            226.0   ug/m3 2019-02-01 11:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2002-07-03 01:00:00  2002    7    3     1   26.0            26.0   µg/m3
1 2002-07-03 02:00:00  2002    7    3     2   24.0            24.0   µg/m3
2 2002-07-03 03:00:00  2002    7    3     3   21.0            21.0   µg/m3
3 2002-07-03 04:00:00  2002    7    3     4   14.0            14.0   µg/m3
4 2002-07-03 05:00:00  2002    7    3     5   38.0            38.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2002-07-03 01:00:00  2002    7    3     1   26.0            26.0   µg/m3
1 2002-07-03 02:00:00  2002    7    3     2   24.0            24.0   µg/m3
2 2002-07-03 03:00:00  2002    7    3     3   21.0            21.0   µg/m3
3 2002-07-03 04:00:00  2002    7    3     4   14.0            14.0   µg/m3
4 2002-07-03 05:00:00  2002    7    3     5   38.0            38.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
005
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/O3/BA0004ND005.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
         VALOR_ORIGINAL UNIDADE            DATETIME
5295425      496.035635   ug/m3 2017-12-06 11:00:00
5295413      496.035635   ug/m3 2017-12-05 23:00:00
5295426      496.035635   ug/m3 2017-12-06 12:00:00
5295419      496.035635   ug/m3 2017-12-06 05:00:00
5295420      496.035635   ug/m3 2017-12-06 06:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1998-01-01 00:00:00  1998    1    1     0    NaN             NaN   ug/m³
1 1998-01-01 01:00:00  1998    1    1     1    NaN             NaN   ug/m³
2 1998-01-01 02:00:00  1998    1    1     2    NaN             NaN   ug/m³
3 1998-01-01 03:00:00  1998    1    1     3    NaN             NaN   ug/m³
4 1998-01-01 04:00:00  1998    1    1     4    NaN             NaN   ug/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1998-01-01 00:00:00  1998    1    1     0    NaN             NaN   ug/m³
1 1998-01-01 01:00:00  1998    1    1     1    NaN             NaN   ug/m³
2 1998-01-01 02:00:00  1998    1    1     2    NaN             NaN   ug/m³
3 1998-01-01 03:00:00  1998    1    1     3    NaN             NaN   ug/m³
4 1998-01-01 04:00:00  1998    1    1     4    NaN             NaN   ug/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
005
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/O3/MG0053RA005.csv
iema
          VALOR_ORIGINAL UNIDADE            DATETIME
34821099          280.48   µg/m3 2019-10-18 14:30:00
34820939          264.57   µg/m3 2019-10-18 13:30:00
34679364          263.07   µg/m3 2019-09-11 14:30:00
34821259          254.73   µg/m3 2019-10-18 15:30:00
34824429          249.36   µg/m3 2019-10-19 11:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2018-01-01 01:00:00  2018    1    1     1    NaN             NaN   µg/m3
1 2018-01-01 02:00:00  2018    1    1     2    NaN             NaN   µg/m3
2 2018-01-01 03:00:00  2018    1    1     3    NaN             NaN   µg/m3
3 2018-01-01 04:00:00  2018    1    1     4    NaN             NaN   µg/m3
4 2018-01-01 05:00:00  2018    1    1     5    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2018-01-01 01:00:00  2018    1    1     1    NaN             NaN   µg/m3
1 2018-01-01 02:00:00  2018    1    1     2    NaN             NaN   µg/m3
2 2018-01-01 03:00:00  2018    1    1     3    NaN             NaN   µg/m3
3 2018-01-01 04:00:00  2018    1    1     4    NaN             NaN   µg/m3
4 2018-01-01 05:00:00  2018    1    1     5    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

005
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/O3/SP0117RA005.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
14879377           232.0   ug/m3 2018-09-25 18:00:00
11744151           222.0   ug/m3 2016-06-17 11:00:00
7718102            219.0   ug/m3 2019-01-31 16:00:00
6834590            218.0   ug/m3 2017-12-05 18:00:00
14879375           216.0   ug/m3 2018-09-25 16:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2000-03-01 17:00:00  2000    3    1    17   11.0            11.0   µg/m3
1 2000-03-01 18:00:00  2000    3    1    18   11.0            11.0   µg/m3
2 2000-03-01 19:00:00  2000    3    1    19   10.0            10.0   µg/m3
3 2000-03-01 20:00:00  2000    3    1    20   10.0            10.0   µg/m3
4 2000-03-01 21:00:00  2000    3    1    21   10.0            10.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2000-03-01 17:00:00  2000    3    1    17   11.0            11.0   µg/m3
1 2000-03-01 18:00:00  2000    3    1    18   11.0            11.0   µg/m3
2 2000-03-01 19:00:00  2000    3    1    19   10.0            10.0   µg/m3
3 2000-03-01 20:00:00  2000    3    1    20   10.0            10.0   µg/m3
4 2000-03-01 21:00:00  2000    3    1    21   10.0            10.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
005
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/O3/SP0280RA005.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
12296267           183.0   ug/m3 2016-10-18 16:00:00
17094665           180.0   ug/m3 2022-10-14 14:00:00
8348019            179.0   ug/m3 2019-01-31 13:00:00
8349787            178.0   ug/m3 2019-04-18 17:00:00
17777650           175.0   ug/m3 2015-11-13 17:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2015-10-01 01:00:00  2015   10    1     1   42.0            42.0   µg/m3
1 2015-10-01 02:00:00  2015   10    1     2   56.0            56.0   µg/m3
2 2015-10-01 03:00:00  2015   10    1     3   49.0            49.0   µg/m3
3 2015-10-01 04:00:00  2015   10    1     4   39.0            39.0   µg/m3
4 2015-10-01 05:00:00  2015   10    1     5   33.0            33.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2015-10-01 01:00:00  2015   10    1     1   42.0            42.0   ug/m3
1 2015-10-01 02:00:00  2015   10    1     2   56.0            56.0   ug/m3
2 2015-10-01 03:00:00  2015   10    1     3   49.0            49.0   ug/m3
3 2015-10-01 04:00:00  2015   10    1     4   39.0            39.0   ug/m3
4 2015-10-01 05:00:00  2015   10    1     5   33.0            33.0   ug/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
005
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/O3/RJ0024RA005.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
28785122      180.220859   µg/m3 2019-10-13 14:00:00
20295228      170.012270   µg/m3 2019-07-08 15:00:00
28785316      158.429448   µg/m3 2019-10-13 15:00:00
28784923      156.858896   µg/m3 2019-10-13 13:00:00
30900584      154.895705   µg/m3 2020-01-27 14:00:00
mma
             DATETIME     ANO   MES   DIA  HORA  VALOR  VALOR_ORIGINAL  \
0 2013-12-14 02:00:00  2013.0  12.0  14.0   2.0   1.98            1.98
1 2013-12-14 03:00:00  2013.0  12.0  14.0   3.0   1.39            1.39
2 2013-12-14 04:00:00  2013.0  12.0  14.0   4.0    NaN            0.00
3 2013-12-14 05:00:00  2013.0  12.0  14.0   5.0   0.20            0.20
4 2013-12-14 06:00:00  2013.0  12.0  14.0   6.0   1.19            1.19

  UNIDADE  QAQC_INTERNO  QAQC_MMA
0   µg/m³          True      True
1   µg/m³          True      True
2   µg/m³          True     False
3   µg/m³          True      True
4   µg/m³          True      True
final
             DATETIME     ANO   MES   DIA  HORA  VALOR  VALOR_ORIGINAL  \
0 2013-12-14 02:00:00  2013.0  12.0  14.0   2.0   1.98            1.98
1 2013-12-14 03:00:00  2013.0  12.0  14.0   3.0   1.39            1.39
2 2013-12-14 04:00:00  2013.0  12.0  14.0   4.0    NaN            0.00
3 2013-12-14 05:00:00  2013.0  12.0  14.0   5.0   0.20            0.20
4 2013-12-14 06:00:00  2013.0  12.0  14.0   6.0   1.19            1.19

  UNIDADE  QAQC_INTERNO  QAQC_MMA
0   µg/m³          True      True
1   µg/m³          True      True
2   µg/m³          True     False
3   µg/m³          True      True
4   µg/m³          True      True
005
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/O3/RJ0229RA005.csv
iema
          VALOR_ORIGINAL UNIDADE            DATETIME
29399403          94.099     ppb 2016-02-25 16:30:00
26824995          81.900     ppb 2015-11-19 14:30:00
26824996          77.400     ppb 2015-11-19 15:30:00
29398757          75.299     ppb 2016-01-26 15:30:00
29398756          75.299     ppb 2016-01-26 14:30:00
mma
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2011-05-01 00:00:00  2011.0  5.0  1.0   0.0  41.20           41.20   µg/m³
1 2011-05-01 01:00:00  2011.0  5.0  1.0   1.0  41.20           41.20   µg/m³
2 2011-05-01 02:00:00  2011.0  5.0  1.0   2.0    NaN             NaN   µg/m³
3 2011-05-01 03:00:00  2011.0  5.0  1.0   3.0  41.20           41.20   µg/m³
4 2011-05-01 04:00:00  2011.0  5.0  1.0   4.0  19.62           19.62   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2         False     False
3          True      True
4          True      True
final
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2011-05-01 00:00:00  2011.0  5.0  1.0   0.0  41.20           41.20   µg/m³
1 2011-05-01 01:00:00  2011.0  5.0  1.0   1.0  41.20           41.20   µg/m³
2 2011-05-01 02:00:00  2011.0  5.0  1.0   2.0    NaN             NaN   µg/m³
3 2011-05-01 03:00:00  2011.0  5.0  1.0   3.0  41.20           41.20   µg/m³
4 2011-05-01 04:00:00  2011.0  5.0  1.0   4.0  19.62           19.62   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True     False
3          True      True
4          True      True

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

005
005
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/O3/SP0108RA005.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
12378531           176.0   ug/m3 2020-10-05 16:00:00
12378532           171.0   ug/m3 2020-10-05 17:00:00
12378530           169.0   ug/m3 2020-10-05 15:00:00
12378483           164.0   ug/m3 2020-10-03 16:00:00
12378482           161.0   ug/m3 2020-10-03 15:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2008-05-09 03:00:00  2008    5    9     3   25.0            25.0   µg/m3
1 2008-05-09 04:00:00  2008    5    9     4   23.0            23.0   µg/m3
2 2008-05-09 05:00:00  2008    5    9     5   33.0            33.0   µg/m3
3 2008-05-09 06:00:00  2008    5    9     6   24.0            24.0   µg/m3
4 2008-05-09 07:00:00  2008    5    9     7   11.0            11.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2008-05-09 03:00:00  2008    5    9     3   25.0            25.0   µg/m3
1 2008-05-09 04:00:00  2008    5    9     4   23.0            23.0   µg/m3
2 2008-05-09 05:00:00  2008    5    9     5   33.0            33.0   µg/m3
3 2008-05-09 06:00:00  2008    5    9     6   24.0            24.0   µg/m3
4 2008-05-09 07:00:00  2008    5    9     7   11.0            11.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
005
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/O3/RJ0026RA005.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
31556490      171.975460   µg/m3 2020-06-12 16:00:00
31556275      160.392638   µg/m3 2020-06-12 15:00:00
23837893      158.625800   µg/m3 2020-10-01 14:00:00
23733990      152.932500   µg/m3 2020-09-10 15:00:00
31597173      144.687117   µg/m3 2020-06-20 15:00:00
mma
             DATETIME     ANO  MES   DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2006-07-21 00:00:00  2006.0  7.0  21.0   0.0    NaN             NaN   µg/m³
1 2006-07-21 01:00:00  2006.0  7.0  21.0   1.0    NaN             0.0   µg/m³
2 2006-07-21 02:00:00  2006.0  7.0  21.0   2.0    NaN             0.0   µg/m³
3 2006-07-21 03:00:00  2006.0  7.0  21.0   3.0    NaN             0.0   µg/m³
4 2006-07-21 04:00:00  2006.0  7.0  21.0   4.0    NaN             0.0   µg/m³

   QAQC_INTERNO  QAQC_MMA
0         False     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME     ANO  MES   DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2006-07-21 00:00:00  2006.0  7.0  21.0   0.0    NaN             NaN   µg/m³
1 2006-07-21 01:00:00  2006.0  7.0  21.0   1.0    NaN             0.0   µg/m³
2 2006-07-21 02:00:00  2006.0  7.0  21.0   2.0    NaN             0.0   µg/m³
3 2006-07-21 03:00:00  2006.0  7.0  21.0   3.0    NaN             0.0   µg/m³
4 2006-07-21 04:00:00  2006.0  7.0  21.0   4.0    NaN             0.0   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
005
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/O3/SP0099RA005.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
10282818           262.0   ug/m3 2020-11-27 13:00:00
17339844           244.0   ug/m3 2015-09-20 13:00:00
7797521            230.0   ug/m3 2019-01-22 14:00:00
17339843           228.0   ug/m3 2015-09-20 12:00:00
11780799           221.0   ug/m3 2016-02-02 15:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1999-09-01 01:00:00  1999    9    1     1   13.0            13.0   µg/m3
1 1999-09-01 02:00:00  1999    9    1     2   11.0            11.0   µg/m3
2 1999-09-01 03:00:00  1999    9    1     3   10.0            10.0   µg/m3
3 1999-09-01 04:00:00  1999    9    1     4    8.0             8.0   µg/m3
4 1999-09-01 05:00:00  1999    9    1     5    8.0             8.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1999-09-01 01:00:00  1999    9    1     1   13.0            13.0   µg/m3
1 1999-09-01 02:00:00  1999    9    1     2   11.0            11.0   µg/m3
2 1999-09-01 03:00:00  1999    9    1     3   10.0            10.0   µg/m3
3 1999-09-01 04:00:00  1999    9    1     4    8.0             8.0   µg/m3
4 1999-09-01 05:00:00  1999    9    1     5    8.0             8.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
005
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/O3/MG0005RA005.csv

/tmp/ipykernel_273420/1352582357.py:97: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  df_mma = pd.read_csv(arquivo, encoding = 'UTF-8')
/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
33188592          197.60   µg/m3 2015-11-06 12:30:00
33188593          183.82   µg/m3 2015-11-06 13:30:00
38233541          182.92   µg/m3 2021-09-30 17:30:00
33188594          175.36   µg/m3 2015-10-15 15:30:00
33188596          170.40   µg/m3 2015-11-06 11:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR VALOR_ORIGINAL UNIDADE  \
0 2009-01-01 01:00:00  2009    1    1     1    NaN              *     ppb
1 2009-01-01 02:00:00  2009    1    1     2    NaN              *     ppb
2 2009-01-01 03:00:00  2009    1    1     3    NaN              *     ppb
3 2009-01-01 04:00:00  2009    1    1     4    NaN              *     ppb
4 2009-01-01 05:00:00  2009    1    1     5    NaN              *     ppb

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR VALOR_ORIGINAL UNIDADE  \
0 2009-01-01 01:00:00  2009    1    1     1    NaN              *     ppb
1 2009-01-01 02:00:00  2009    1    1     2    NaN              *     ppb
2 2009-01-01 03:00:00  2009    1    1     3    NaN              *     ppb
3 2009-01-01 04:00:00  2009    1    1     4    NaN              *     ppb
4 2009-01-01 05:00:00  2009    1    1     5    NaN              *     ppb

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
005
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/O3/RJ0060RA005.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
25331655        435.9412   ug/m3 2017-01-12 06:00:00
25331653        412.5125   ug/m3 2017-01-12 04:00:00
25331654        409.8369   ug/m3 2017-01-12 05:00:00
25331650        409.6464   ug/m3 2017-01-12 01:00:00
25331648        391.2711   ug/m3 2017-01-11 23:00:00
mma
             DATETIME     ANO   MES   DIA  HORA  VALOR  VALOR_ORIGINAL  \
0 2008-12-15 00:00:00  2008.0  12.0  15.0   0.0   7.46            7.46
1 2008-12-15 01:00:00  2008.0  12.0  15.0   1.0   5.18            5.18
2 2008-12-15 02:00:00  2008.0  12.0  15.0   2.0   3.47            3.47
3 2008-12-15 03:00:00  2008.0  12.0  15.0   3.0   7.17            7.17
4 2008-12-15 04:00:00  2008.0  12.0  15.0   4.0   4.99            4.99

  UNIDADE  QAQC_INTERNO  QAQC_MMA
0   µg/m³          True      True
1   µg/m³          True      True
2   µg/m³          True      True
3   µg/m³          True      True
4   µg/m³          True      True
final
             DATETIME     ANO   MES   DIA  HORA  VALOR  VALOR_ORIGINAL  \
0 2008-12-15 00:00:00  2008.0  12.0  15.0   0.0   7.46            7.46
1 2008-12-15 01:00:00  2008.0  12.0  15.0   1.0   5.18            5.18
2 2008-12-15 02:00:00  2008.0  12.0  15.0   2.0   3.47            3.47
3 2008-12-15 03:00:00  2008.0  12.0  15.0   3.0   7.17            7.17
4 2008-12-15 04:00:00  2008.0  12.0  15.0   4.0   4.99            4.99

  UNIDADE  QAQC_INTERNO  QAQC_MMA
0   µg/m³          True      True
1   µg/m³          True      True
2   µg/m³          True      True
3   µg/m³          True      True
4   µg/m³          True      True
005
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/O3/RJ0034RA005.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
29061039      352.619297   µg/m3 2019-12-11 15:00:00
29060844      346.224826   µg/m3 2019-12-11 14:00:00
19600541      344.344685   µg/m3 2019-01-21 15:00:00
28416379      344.224329   µg/m3 2019-07-23 12:00:00
19832871      344.171939   µg/m3 2019-03-19 11:00:00
mma
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2004-03-01 12:00:00  2004.0  3.0  1.0  12.0  37.80           37.80   µg/m³
1 2004-03-01 13:00:00  2004.0  3.0  1.0  13.0  39.34           39.34   µg/m³
2 2004-03-01 14:00:00  2004.0  3.0  1.0  14.0  40.74           40.74   µg/m³
3 2004-03-01 15:00:00  2004.0  3.0  1.0  15.0  42.23           42.23   µg/m³
4 2004-03-01 16:00:00  2004.0  3.0  1.0  16.0  42.85           42.85   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2004-03-01 12:00:00  2004.0  3.0  1.0  12.0  37.80           37.80   µg/m³
1 2004-03-01 13:00:00  2004.0  3.0  1.0  13.0  39.34           39.34   µg/m³
2 2004-03-01 14:00:00  2004.0  3.0  1.0  14.0  40.74           40.74   µg/m³
3 2004-03-01 15:00:00  2004.0  3.0  1.0  15.0  42.23           42.23   µg/m³
4 2004-03-01 16:00:00  2004.0  3.0  1.0  16.0  42.85           42.85   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
005
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/O3/SP0067RA005.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
17727968           179.0   ug/m3 2015-09-24 13:00:00
17727967           177.0   ug/m3 2015-09-24 12:00:00
7429376            177.0   ug/m3 2017-09-06 16:00:00
17727971           174.0   ug/m3 2015-09-24 16:00:00
17727970           171.0   ug/m3 2015-09-24 15:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2000-01-28 18:00:00  2000    1   28    18   18.0            18.0   µg/m3
1 2000-01-28 19:00:00  2000    1   28    19   16.0            16.0   µg/m3
2 2000-01-28 20:00:00  2000    1   28    20   17.0            17.0   µg/m3
3 2000-01-28 21:00:00  2000    1   28    21   16.0            16.0   µg/m3
4 2000-01-28 22:00:00  2000    1   28    22   14.0            14.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2000-01-28 18:00:00  2000    1   28    18   18.0            18.0   µg/m3
1 2000-01-28 19:00:00  2000    1   28    19   16.0            16.0   µg/m3
2 2000-01-28 20:00:00  2000    1   28    20   17.0            17.0   µg/m3
3 2000-01-28 21:00:00  2000    1   28    21   16.0            16.0   µg/m3
4 2000-01-28 22:00:00  2000    1   28    22   14.0            14.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
005
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/O3/RJ0058RA005.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
31091133      280.734887   µg/m3 2020-03-09 12:00:00
30977297      265.347402   µg/m3 2020-02-13 12:00:00
28675657      263.880245   µg/m3 2019-09-19 13:00:00
30900408      248.745359   µg/m3 2020-01-27 13:00:00
23397704      238.652600   µg/m3 2020-07-06 13:00:00
mma
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2008-07-01 00:00:00  2008.0  7.0  1.0   0.0    NaN             0.0   µg/m³
1 2008-07-01 01:00:00  2008.0  7.0  1.0   1.0    NaN             NaN   µg/m³
2 2008-07-01 02:00:00  2008.0  7.0  1.0   2.0    NaN             NaN   µg/m³
3 2008-07-01 03:00:00  2008.0  7.0  1.0   3.0    NaN             NaN   µg/m³
4 2008-07-01 04:00:00  2008.0  7.0  1.0   4.0    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1         False     False
2         False     False
3         False     False
4         False     False
final
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2008-07-01 00:00:00  2008.0  7.0  1.0   0.0    NaN             0.0   µg/m³
1 2008-07-01 01:00:00  2008.0  7.0  1.0   1.0    NaN             NaN   µg/m³
2 2008-07-01 02:00:00  2008.0  7.0  1.0   2.0    NaN             NaN   µg/m³
3 2008-07-01 03:00:00  2008.0  7.0  1.0   3.0    NaN             NaN   µg/m³
4 2008-07-01 04:00:00  2008.0  7.0  1.0   4.0    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
005
005
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/O3/RJ0071RA005.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
23432688        311.2280   µg/m3 2020-07-13 11:00:00
24997864        213.2646   ug/m3 2017-10-14 13:00:00
24997820        211.7286   ug/m3 2017-10-12 17:00:00
24997819        210.7242   ug/m3 2017-10-12 16:00:00
24997865        206.9692   ug/m3 2017-10-14 14:00:00
mma
             DATETIME     ANO   MES   DIA  HORA  VALOR  VALOR_ORIGINAL  \
0 2000-12-21 06:00:00  2000.0  12.0  21.0   6.0    NaN             NaN
1 2000-12-21 07:00:00  2000.0  12.0  21.0   7.0    NaN             NaN
2 2000-12-21 08:00:00  2000.0  12.0  21.0   8.0    NaN             NaN
3 2000-12-21 09:00:00  2000.0  12.0  21.0   9.0    NaN             NaN
4 2000-12-21 10:00:00  2000.0  12.0  21.0  10.0    NaN             NaN

  UNIDADE  QAQC_INTERNO  QAQC_MMA
0   µg/m³         False     False
1   µg/m³         False     False
2   µg/m³         False     False
3   µg/m³         False     False
4   µg/m³         False     False
final
             DATETIME     ANO   MES   DIA  HORA  VALOR  VALOR_ORIGINAL  \
0 2000-12-21 06:00:00  2000.0  12.0  21.0   6.0    NaN             NaN
1 2000-12-21 07:00:00  2000.0  12.0  21.0   7.0    NaN             NaN
2 2000-12-21 08:00:00  2000.0  12.0  21.0   8.0    NaN             NaN
3 2000-12-21 09:00:00  2000.0  12.0  21.0   9.0    NaN             NaN
4 2000-12-21 10:00:00  2000.0  12.0  21.0  10.0    NaN             NaN

  UNIDADE  QAQC_INTERNO  QAQC_MMA
0   µg/m³          True     False
1   µg/m³          True     False
2   µg/m³          True     False
3   µg/m³          True     False
4   µg/m³          True     False
005
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/O3/SP0063RA005.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
8056715            380.0   ug/m3 2019-01-31 15:00:00
8056716            296.0   ug/m3 2019-01-31 16:00:00
17542604           286.0   ug/m3 2015-03-28 13:00:00
17542584           272.0   ug/m3 2015-03-27 16:00:00
8056714            257.0   ug/m3 2019-01-31 14:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1999-05-06 01:00:00  1999    5    6     1    NaN             0.0   µg/m3
1 1999-05-06 02:00:00  1999    5    6     2    NaN             0.0   µg/m3
2 1999-05-06 03:00:00  1999    5    6     3    NaN             0.0   µg/m3
3 1999-05-06 04:00:00  1999    5    6     4    NaN             NaN     NaN
4 1999-05-06 05:00:00  1999    5    6     5    3.0             3.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1999-05-06 01:00:00  1999    5    6     1    NaN             0.0   µg/m3
1 1999-05-06 02:00:00  1999    5    6     2    NaN             0.0   µg/m3
2 1999-05-06 03:00:00  1999    5    6     3    NaN             0.0   µg/m3
3 1999-05-06 04:00:00  1999    5    6     4    NaN             NaN     NaN
4 1999-05-06 05:00:00  1999    5    6     5    3.0             3.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True      True
005
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/O3/RJ0069RA005.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
24850621        169.1970   ug/m3 2017-02-18 19:00:00
24850620        164.9860   ug/m3 2017-02-18 18:00:00
24850622        147.5012   ug/m3 2017-02-18 20:00:00
24850623        137.9301   ug/m3 2017-02-18 21:00:00
24850644        130.4174   ug/m3 2017-02-19 18:00:00
mma
             DATETIME     ANO   MES   DIA  HORA  VALOR  VALOR_ORIGINAL  \
0 2000-12-19 07:00:00  2000.0  12.0  19.0   7.0  50.69           50.69
1 2000-12-19 08:00:00  2000.0  12.0  19.0   8.0  62.61           62.61
2 2000-12-19 09:00:00  2000.0  12.0  19.0   9.0  45.30           45.30
3 2000-12-19 10:00:00  2000.0  12.0  19.0  10.0    NaN             NaN
4 2000-12-19 11:00:00  2000.0  12.0  19.0  11.0  57.36           57.36

  UNIDADE  QAQC_INTERNO  QAQC_MMA
0   µg/m³          True      True
1   µg/m³          True      True
2   µg/m³          True      True
3   µg/m³         False     False
4   µg/m³          True      True
final
             DATETIME     ANO   MES   DIA  HORA  VALOR  VALOR_ORIGINAL  \
0 2000-12-19 07:00:00  2000.0  12.0  19.0   7.0  50.69           50.69
1 2000-12-19 08:00:00  2000.0  12.0  19.0   8.0  62.61           62.61
2 2000-12-19 09:00:00  2000.0  12.0  19.0   9.0  45.30           45.30
3 2000-12-19 10:00:00  2000.0  12.0  19.0  10.0    NaN             NaN
4 2000-12-19 11:00:00  2000.0  12.0  19.0  11.0  57.36           57.36

  UNIDADE  QAQC_INTERNO  QAQC_MMA
0   µg/m³          True      True
1   µg/m³          True      True
2   µg/m³          True      True
3   µg/m³          True     False
4   µg/m³          True      True
005
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/O3/BA0010ND005.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
         VALOR_ORIGINAL UNIDADE            DATETIME
5180928      136.409800   ug/m3 2017-05-16 13:00:00
5180284      117.808463   ug/m3 2017-04-19 16:00:00
5179756      117.167038   ug/m3 2017-03-28 13:00:00
5180929      111.821826   ug/m3 2017-05-16 14:00:00
5177784      106.690423   ug/m3 2017-01-02 12:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1998-01-01 00:00:00  1998    1    1     0    NaN             NaN   ug/m³
1 1998-01-01 01:00:00  1998    1    1     1    NaN             NaN   ug/m³
2 1998-01-01 02:00:00  1998    1    1     2    NaN             NaN   ug/m³
3 1998-01-01 03:00:00  1998    1    1     3    NaN             NaN   ug/m³
4 1998-01-01 04:00:00  1998    1    1     4    NaN             NaN   ug/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1998-01-01 00:00:00  1998    1    1     0    NaN             NaN   ug/m³
1 1998-01-01 01:00:00  1998    1    1     1    NaN             NaN   ug/m³
2 1998-01-01 02:00:00  1998    1    1     2    NaN             NaN   ug/m³
3 1998-01-01 03:00:00  1998    1    1     3    NaN             NaN   ug/m³
4 1998-01-01 04:00:00  1998    1    1     4    NaN             NaN   ug/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
005
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/O3/RJ0224RA005.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
26982478         118.300     ppb 2015-05-21 11:30:00
26985716         117.100     ppb 2015-10-16 13:30:00
26985693         115.300     ppb 2015-10-15 14:30:00
29628271         114.712   ug/m3 2016-10-20 16:30:00
26985715         111.500     ppb 2015-10-16 12:30:00
mma
             DATETIME     ANO   MES   DIA  HORA  VALOR  VALOR_ORIGINAL  \
0 2013-12-14 02:00:00  2013.0  12.0  14.0   2.0   1.98            1.98
1 2013-12-14 03:00:00  2013.0  12.0  14.0   3.0   1.39            1.39
2 2013-12-14 04:00:00  2013.0  12.0  14.0   4.0    NaN            0.00
3 2013-12-14 05:00:00  2013.0  12.0  14.0   5.0   0.20            0.20
4 2013-12-14 06:00:00  2013.0  12.0  14.0   6.0   1.19            1.19

  UNIDADE  QAQC_INTERNO  QAQC_MMA
0   µg/m³          True      True
1   µg/m³          True      True
2   µg/m³          True     False
3   µg/m³          True      True
4   µg/m³          True      True
final
             DATETIME     ANO   MES   DIA  HORA  VALOR  VALOR_ORIGINAL  \
0 2013-12-14 02:00:00  2013.0  12.0  14.0   2.0   1.98            1.98
1 2013-12-14 03:00:00  2013.0  12.0  14.0   3.0   1.39            1.39
2 2013-12-14 04:00:00  2013.0  12.0  14.0   4.0    NaN            0.00
3 2013-12-14 05:00:00  2013.0  12.0  14.0   5.0   0.20            0.20
4 2013-12-14 06:00:00  2013.0  12.0  14.0   6.0   1.19            1.19

  UNIDADE  QAQC_INTERNO  QAQC_MMA
0   µg/m³          True      True
1   µg/m³          True      True
2   µg/m³          True     False
3   µg/m³          True      True
4   µg/m³          True      True
005
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/O3/SP0111RA005.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
18793272           168.0   ug/m3 2017-09-19 15:00:00
18793754           166.0   ug/m3 2017-10-10 15:00:00
18793273           164.0   ug/m3 2017-09-19 16:00:00
16265356           163.0   ug/m3 2021-09-19 17:00:00
13889379           163.0   ug/m3 2019-09-19 16:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2008-04-30 03:00:00  2008    4   30     3   18.0            18.0   µg/m3
1 2008-04-30 04:00:00  2008    4   30     4   21.0            21.0   µg/m3
2 2008-04-30 05:00:00  2008    4   30     5   18.0            18.0   µg/m3
3 2008-04-30 06:00:00  2008    4   30     6   24.0            24.0   µg/m3
4 2008-04-30 07:00:00  2008    4   30     7   20.0            20.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2008-04-30 03:00:00  2008    4   30     3   18.0            18.0   µg/m3
1 2008-04-30 04:00:00  2008    4   30     4   21.0            21.0   µg/m3
2 2008-04-30 05:00:00  2008    4   30     5   18.0            18.0   µg/m3
3 2008-04-30 06:00:00  2008    4   30     6   24.0            24.0   µg/m3
4 2008-04-30 07:00:00  2008    4   30     7   20.0            20.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
NO2
['RJ0050', 'SP0259', 'RJ0032', 'SP0266', 'RJ0022', 'PR0009 ', 'MG0008', 'PR0006 ', 'PR0005 ', 'MG0036', 'RJ0048', 'MG0009', 'SP0284', 'SP0086', 'RJ0037', 'RJ0021', 'SP0091', 'BA0005', 'SP0288', 'RJ0045', nan, 'MG0039', 'RJ0079', 'RJ0055', 'RJ0226', 'SP0258', 'RJ0063', 'SP0116', 'RJ0043', 'SP0289', 'RJ0044', 'PR0003 ', 'MG0001', 'SP0120', 'MG0006', 'MG0011', 'RJ0018', 'MG0002', 'MG0057', 'SP0262', 'BA0006', 'RJ0036', 'RJ0081', 'SP0106', 'MG0012', 'BA0008', 'PR0011 ', 'SP0263', 'SP0109', 'BA0007', 'RJ0019', 'MG0058', 'CE0001', 'SP0256', 'SP0083', 'SP0273', 'BA0011', 'RJ0225', 'RJ0070', 'MG0017', 'MG0010', 'RJ0038', 'RJ0051', 'SP0269', 'RJ0057', 'RJ0078', 'RJ0033', 'BA0001', 'SP0103', 'MG0013', 'MG0004', 'SP0110', 'RJ0031', 'PR0015 ', 'RJ0064', 'SP0065', 'PR0008 ', 'SP0114', 'RJ0030', 'RJ0020', 'RJ0029', 'SP0113', 'MG0003', 'SP0281', 'RJ0039', 'PR0007 ', 'RJ0023', 'SP0248', 'BA0004', 'MG0053', 'PR0001 ', 'SP0117', 'SP0280', 'RJ0229', 'PR0012 ', 'SP0108', 'RJ0026', 'SP0099', 'MG0005', 'RJ0060', 'RJ0034', 'SP0067', 'SP0073', 'RJ0058', 'PR0002 ', 'RJ0071', 'RJ0069', 'BA0003', 'PR0014 ', 'BA0010', 'SP0111']
004
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/NO2/RJ0050RA004.csv
iema
          VALOR_ORIGINAL UNIDADE            DATETIME
19657732     1291.223135   µg/m3 2019-02-05 00:00:00
19683941     1015.872573   µg/m3 2019-02-11 08:00:00
19657891      945.801883   µg/m3 2019-02-05 01:00:00
19683441      809.764709   µg/m3 2019-02-11 05:00:00
19657566      800.797934   µg/m3 2019-02-04 23:00:00
mma
             DATETIME     ANO   MES   DIA  HORA  VALOR  VALOR_ORIGINAL  \
0 2018-10-10 16:00:00  2018.0  10.0  10.0  16.0    NaN             NaN
1 2018-10-10 17:00:00  2018.0  10.0  10.0  17.0    NaN             NaN
2 2018-10-10 18:00:00  2018.0  10.0  10.0  18.0    NaN             NaN
3 2018-10-10 19:00:00  2018.0  10.0  10.0  19.0    NaN             NaN
4 2018-10-10 20:00:00  2018.0  10.0  10.0  20.0    NaN             NaN

  UNIDADE  QAQC_INTERNO  QAQC_MMA
0   µg/m³         False     False
1   µg/m³         False     False
2   µg/m³         False     False
3   µg/m³         False     False
4   µg/m³         False     False
final
             DATETIME     ANO   MES   DIA  HORA  VALOR  VALOR_ORIGINAL  \
0 2018-10-10 16:00:00  2018.0  10.0  10.0  16.0    NaN             NaN
1 2018-10-10 17:00:00  2018.0  10.0  10.0  17.0    NaN             NaN
2 2018-10-10 18:00:00  2018.0  10.0  10.0  18.0    NaN             NaN
3 2018-10-10 19:00:00  2018.0  10.0  10.0  19.0    NaN             NaN
4 2018-10-10 20:00:00  2018.0  10.0  10.0  20.0    NaN             NaN

  UNIDADE  QAQC_INTERNO  QAQC_MMA
0   µg/m³          True     False
1   µg/m³          True     False
2   µg/m³          True     False
3   µg/m³          True     False
4   µg/m³          True     False

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

004
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/NO2/SP0259RA004.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
14553845           137.0   ug/m3 2016-12-26 20:00:00
14552633           117.0   ug/m3 2016-05-09 16:00:00
14553844           109.0   ug/m3 2016-12-26 19:00:00
14553843           108.0   ug/m3 2016-12-26 18:00:00
14552635           107.0   ug/m3 2016-05-09 18:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2011-03-11 13:00:00  2011    3   11    13    4.0             4.0   µg/m3
1 2011-03-11 14:00:00  2011    3   11    14    5.0             5.0   µg/m3
2 2011-03-11 15:00:00  2011    3   11    15    4.0             4.0   µg/m3
3 2011-03-11 16:00:00  2011    3   11    16    6.0             6.0   µg/m3
4 2011-03-11 17:00:00  2011    3   11    17    7.0             7.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2011-03-11 13:00:00  2011    3   11    13    4.0             4.0   µg/m3
1 2011-03-11 14:00:00  2011    3   11    14    5.0             5.0   µg/m3
2 2011-03-11 15:00:00  2011    3   11    15    4.0             4.0   µg/m3
3 2011-03-11 16:00:00  2011    3   11    16    6.0             6.0   µg/m3
4 2011-03-11 17:00:00  2011    3   11    17    7.0             7.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
004
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/NO2/RJ0032RA004.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
25158101       110.66990   ug/m3 2017-03-27 10:00:00
25156926       109.79070   ug/m3 2017-01-25 08:00:00
25160885       104.47660   ug/m3 2017-08-30 19:00:00
25160886       103.22930   ug/m3 2017-08-30 20:00:00
25162489        97.57285   ug/m3 2017-11-16 19:00:00
mma
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2004-03-05 08:00:00  2004.0  3.0  5.0   8.0    NaN             NaN   µg/m³
1 2004-03-05 09:00:00  2004.0  3.0  5.0   9.0    NaN             NaN   µg/m³
2 2004-03-05 10:00:00  2004.0  3.0  5.0  10.0    NaN             NaN   µg/m³
3 2004-03-05 11:00:00  2004.0  3.0  5.0  11.0    NaN             NaN   µg/m³
4 2004-03-05 12:00:00  2004.0  3.0  5.0  12.0    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0         False     False
1         False     False
2         False     False
3         False     False
4         False     False
final
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2004-03-05 08:00:00  2004.0  3.0  5.0   8.0    NaN             NaN   µg/m³
1 2004-03-05 09:00:00  2004.0  3.0  5.0   9.0    NaN             NaN   µg/m³
2 2004-03-05 10:00:00  2004.0  3.0  5.0  10.0    NaN             NaN   µg/m³
3 2004-03-05 11:00:00  2004.0  3.0  5.0  11.0    NaN             NaN   µg/m³
4 2004-03-05 12:00:00  2004.0  3.0  5.0  12.0    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
004
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/NO2/SP0266RA004.csv
iema
          VALOR_ORIGINAL UNIDADE            DATETIME
12868052           179.0   ug/m3 2020-10-02 20:00:00
12868053           172.0   ug/m3 2020-10-02 21:00:00
8952652            143.0   ug/m3 2022-07-05 21:00:00
16088858           140.0   ug/m3 2021-08-10 21:00:00
16088857           137.0   ug/m3 2021-08-10 20:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2018-02-01 16:00:00  2018    2    1    16    9.0             9.0   µg/m3
1 2018-02-01 17:00:00  2018    2    1    17    9.0             9.0   µg/m3
2 2018-02-01 18:00:00  2018    2    1    18    9.0             9.0   µg/m3
3 2018-02-01 19:00:00  2018    2    1    19   10.0            10.0   µg/m3
4 2018-02-01 20:00:00  2018    2    1    20   11.0            11.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2018-02-01 16:00:00  2018    2    1    16    9.0             9.0   ug/m3
1 2018-02-01 17:00:00  2018    2    1    17    9.0             9.0   ug/m3
2 2018-02-01 18:00:00  2018    2    1    18    9.0             9.0   ug/m3
3 2018-02-01 19:00:00  2018    2    1    19   10.0            10.0   ug/m3
4 2018-02-01 20:00:00  2018    2    1    20   11.0            11.0   ug/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

004
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/NO2/RJ0022RA004.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
29522172         194.391   ug/m3 2016-07-15 16:30:00
29522916         189.451   ug/m3 2016-08-15 16:30:00
29522169         187.566   ug/m3 2016-07-15 13:30:00
29522915         180.192   ug/m3 2016-08-15 15:30:00
29522101         174.857   ug/m3 2016-07-12 17:30:00
mma
             DATETIME     ANO  MES   DIA  HORA   VALOR  VALOR_ORIGINAL  \
0 2000-07-26 08:00:00  2000.0  7.0  26.0   8.0   59.81           59.81
1 2000-07-26 09:00:00  2000.0  7.0  26.0   9.0   65.70           65.70
2 2000-07-26 10:00:00  2000.0  7.0  26.0  10.0   69.93           69.93
3 2000-07-26 11:00:00  2000.0  7.0  26.0  11.0   91.24           91.24
4 2000-07-26 12:00:00  2000.0  7.0  26.0  12.0  101.32          101.32

  UNIDADE  QAQC_INTERNO  QAQC_MMA
0   µg/m³          True      True
1   µg/m³          True      True
2   µg/m³          True      True
3   µg/m³          True      True
4   µg/m³          True      True
final
             DATETIME     ANO  MES   DIA  HORA   VALOR  VALOR_ORIGINAL  \
0 2000-07-26 08:00:00  2000.0  7.0  26.0   8.0   59.81           59.81
1 2000-07-26 09:00:00  2000.0  7.0  26.0   9.0   65.70           65.70
2 2000-07-26 10:00:00  2000.0  7.0  26.0  10.0   69.93           69.93
3 2000-07-26 11:00:00  2000.0  7.0  26.0  11.0   91.24           91.24
4 2000-07-26 12:00:00  2000.0  7.0  26.0  12.0  101.32          101.32

  UNIDADE  QAQC_INTERNO  QAQC_MMA
0   µg/m³          True      True
1   µg/m³          True      True
2   µg/m³          True      True
3   µg/m³          True      True
4   µg/m³          True      True
004
004
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/NO2/MG0008RA004.csv

/tmp/ipykernel_273420/1352582357.py:97: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  df_mma = pd.read_csv(arquivo, encoding = 'UTF-8')
/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
37925739          305.49   µg/m3 2021-07-16 07:30:00
37925565          261.39   µg/m3 2021-07-16 06:30:00
37974512          259.51   µg/m3 2021-07-28 07:30:00
32211009          254.24   µg/m3 2020-06-03 07:30:00
37925908          252.10   µg/m3 2021-07-16 08:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR VALOR_ORIGINAL UNIDADE  \
0 2013-01-01 01:00:00  2013    1    1     1   12.0             12     ppb
1 2013-01-01 02:00:00  2013    1    1     2   15.0             15     ppb
2 2013-01-01 03:00:00  2013    1    1     3    9.0              9     ppb
3 2013-01-01 04:00:00  2013    1    1     4    9.0              9     ppb
4 2013-01-01 05:00:00  2013    1    1     5    7.0              7     ppb

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR VALOR_ORIGINAL UNIDADE  \
0 2013-01-01 01:00:00  2013    1    1     1   12.0             12     ppb
1 2013-01-01 02:00:00  2013    1    1     2   15.0             15     ppb
2 2013-01-01 03:00:00  2013    1    1     3    9.0              9     ppb
3 2013-01-01 04:00:00  2013    1    1     4    9.0              9     ppb
4 2013-01-01 05:00:00  2013    1    1     5    7.0              7     ppb

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
004
004
004
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/NO2/MG0036RA004.csv
iema
          VALOR_ORIGINAL UNIDADE            DATETIME
37975770           114.3   µg/m3 2021-07-28 15:30:00
38135421            92.4   µg/m3 2021-09-05 20:30:00
34651648            86.0   µg/m3 2019-09-04 12:30:00
34651799            85.0   µg/m3 2019-09-04 13:30:00
36622654            81.7   µg/m3 2018-07-10 00:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2017-08-22 17:00:00  2017    8   22    17    NaN             NaN   µg/m3
1 2017-08-22 18:00:00  2017    8   22    18    2.8             2.8   µg/m3
2 2017-08-22 19:00:00  2017    8   22    19    3.6             3.6   µg/m3
3 2017-08-22 20:00:00  2017    8   22    20    4.5             4.5   µg/m3
4 2017-08-22 21:00:00  2017    8   22    21    4.8             4.8   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2017-08-22 17:00:00  2017    8   22    17    NaN             NaN   µg/m3
1 2017-08-22 18:00:00  2017    8   22    18    2.8             2.8   µg/m3
2 2017-08-22 19:00:00  2017    8   22    19    3.6             3.6   µg/m3
3 2017-08-22 20:00:00  2017    8   22    20    4.5             4.5   µg/m3
4 2017-08-22 21:00:00  2017    8   22    21    4.8             4.8   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True      True
2          True      True
3          True      True
4          True      True

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

004
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/NO2/RJ0048RA004.csv
iema
          VALOR_ORIGINAL UNIDADE            DATETIME
22759927           45.06   ug/m3 2022-06-22 19:00:00
22763044           39.76   ug/m3 2022-12-20 19:00:00
22759314           37.38   ug/m3 2022-05-27 21:00:00
22760187           34.83   ug/m3 2022-07-03 18:00:00
22759832           33.75   ug/m3 2022-06-18 15:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2019-09-17 16:00:00  2019    9   17    16    NaN             NaN   µg/m³
1 2019-09-17 17:00:00  2019    9   17    17    NaN             NaN   µg/m³
2 2019-09-17 18:00:00  2019    9   17    18    NaN             NaN   µg/m³
3 2019-09-17 19:00:00  2019    9   17    19    NaN             NaN   µg/m³
4 2019-09-17 20:00:00  2019    9   17    20    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0         False     False
1         False     False
2         False     False
3         False     False
4         False     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2019-09-17 16:00:00  2019    9   17    16    NaN             NaN   µg/m³
1 2019-09-17 17:00:00  2019    9   17    17    NaN             NaN   µg/m³
2 2019-09-17 18:00:00  2019    9   17    18    NaN             NaN   µg/m³
3 2019-09-17 19:00:00  2019    9   17    19    NaN             NaN   µg/m³
4 2019-09-17 20:00:00  2019    9   17    20    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

004
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/NO2/MG0009RA004.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
39628005           67.20   µg/m3 2022-10-24 05:30:00
39622619           64.83   µg/m3 2022-10-22 17:30:00
39626956           60.51   µg/m3 2022-10-23 22:30:00
39627409           59.29   µg/m3 2022-10-24 01:30:00
40389309           58.39   µg/m3 2016-10-08 23:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2014-01-01 01:00:00  2014    1    1     1  14.59           14.59   µg/m3
1 2014-01-01 02:00:00  2014    1    1     2  14.50           14.50   µg/m3
2 2014-01-01 03:00:00  2014    1    1     3  10.00           10.00   µg/m3
3 2014-01-01 04:00:00  2014    1    1     4   7.56            7.56   µg/m3
4 2014-01-01 05:00:00  2014    1    1     5   5.87            5.87   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2014-01-01 01:00:00  2014    1    1     1  14.59           14.59   µg/m3
1 2014-01-01 02:00:00  2014    1    1     2  14.50           14.50   µg/m3
2 2014-01-01 03:00:00  2014    1    1     3  10.00           10.00   µg/m3
3 2014-01-01 04:00:00  2014    1    1     4   7.56            7.56   µg/m3
4 2014-01-01 05:00:00  2014    1    1     5   5.87            5.87   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
004
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/NO2/SP0284RA004.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
6862480            162.0   ug/m3 2017-09-28 01:00:00
6861784            158.0   ug/m3 2017-08-29 22:00:00
6861785            155.0   ug/m3 2017-08-29 23:00:00
14899900           151.0   ug/m3 2018-06-27 11:00:00
6861786            142.0   ug/m3 2017-08-29 23:55:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2016-07-20 02:00:00  2016    7   20     2   47.0            47.0   µg/m3
1 2016-07-20 03:00:00  2016    7   20     3   46.0            46.0   µg/m3
2 2016-07-20 04:00:00  2016    7   20     4   45.0            45.0   µg/m3
3 2016-07-20 05:00:00  2016    7   20     5   42.0            42.0   µg/m3
4 2016-07-20 06:00:00  2016    7   20     6   37.0            37.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2016-07-20 02:00:00  2016    7   20     2   47.0            47.0   ug/m3
1 2016-07-20 03:00:00  2016    7   20     3   46.0            46.0   ug/m3
2 2016-07-20 04:00:00  2016    7   20     4   45.0            45.0   ug/m3
3 2016-07-20 05:00:00  2016    7   20     5   42.0            42.0   ug/m3
4 2016-07-20 06:00:00  2016    7   20     6   37.0            37.0   ug/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
004
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/NO2/SP0086RA004.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
16927127           273.0   ug/m3 2022-06-25 10:00:00
15332622           250.0   ug/m3 2018-07-03 10:00:00
17655719           244.0   ug/m3 2015-09-01 09:00:00
17655718           228.0   ug/m3 2015-09-01 08:00:00
17656257           215.0   ug/m3 2015-09-24 23:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1998-01-14 17:00:00  1998    1   14    17   49.0            49.0   µg/m3
1 1998-01-14 18:00:00  1998    1   14    18   59.0            59.0   µg/m3
2 1998-01-14 19:00:00  1998    1   14    19   48.0            48.0   µg/m3
3 1998-01-14 20:00:00  1998    1   14    20   47.0            47.0   µg/m3
4 1998-01-14 21:00:00  1998    1   14    21   63.0            63.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1998-01-14 17:00:00  1998    1   14    17   49.0            49.0   µg/m3
1 1998-01-14 18:00:00  1998    1   14    18   59.0            59.0   µg/m3
2 1998-01-14 19:00:00  1998    1   14    19   48.0            48.0   µg/m3
3 1998-01-14 20:00:00  1998    1   14    20   47.0            47.0   µg/m3
4 1998-01-14 21:00:00  1998    1   14    21   63.0            63.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
004
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/NO2/RJ0037RA004.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
30658518          139.28   µg/m³ 2022-09-09 18:00:00
30658519          130.63   µg/m³ 2022-09-09 19:00:00
30656677          125.27   µg/m³ 2022-06-24 17:00:00
26419072          119.86   µg/m³ 2021-06-25 18:00:00
30656080          118.96   µg/m³ 2022-05-30 18:00:00
mma
             DATETIME     ANO   MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2001-12-04 15:00:00  2001.0  12.0  4.0  15.0    NaN            0.00   µg/m³
1 2001-12-04 16:00:00  2001.0  12.0  4.0  16.0    NaN            0.00   µg/m³
2 2001-12-04 17:00:00  2001.0  12.0  4.0  17.0    NaN            0.00   µg/m³
3 2001-12-04 18:00:00  2001.0  12.0  4.0  18.0   4.92            4.92   µg/m³
4 2001-12-04 19:00:00  2001.0  12.0  4.0  19.0   7.00            7.00   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True      True
4          True      True
final
             DATETIME     ANO   MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2001-12-04 15:00:00  2001.0  12.0  4.0  15.0    NaN            0.00   µg/m³
1 2001-12-04 16:00:00  2001.0  12.0  4.0  16.0    NaN            0.00   µg/m³
2 2001-12-04 17:00:00  2001.0  12.0  4.0  17.0    NaN            0.00   µg/m³
3 2001-12-04 18:00:00  2001.0  12.0  4.0  18.0   4.92            4.92   µg/m³
4 2001-12-04 19:00:00  2001.0  12.0  4.0  19.0   7.00            7.00   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True      True
4          True      True
004
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/NO2/RJ0021RA004.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
27000967      230.473393   ug/m3 2015-10-15 17:30:00
29636996      223.899000   ug/m3 2016-01-15 11:30:00
29637662      223.723000   ug/m3 2016-02-17 15:30:00
27000966      221.879003   ug/m3 2015-10-15 16:30:00
29637000      218.853000   ug/m3 2016-01-15 15:30:00
mma
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1999-05-01 00:00:00  1999.0  5.0  1.0   0.0  34.34           34.34   µg/m³
1 1999-05-01 01:00:00  1999.0  5.0  1.0   1.0  32.47           32.47   µg/m³
2 1999-05-01 02:00:00  1999.0  5.0  1.0   2.0  24.85           24.85   µg/m³
3 1999-05-01 03:00:00  1999.0  5.0  1.0   3.0  22.96           22.96   µg/m³
4 1999-05-01 04:00:00  1999.0  5.0  1.0   4.0  22.99           22.99   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1999-05-01 00:00:00  1999.0  5.0  1.0   0.0  34.34           34.34   µg/m³
1 1999-05-01 01:00:00  1999.0  5.0  1.0   1.0  32.47           32.47   µg/m³
2 1999-05-01 02:00:00  1999.0  5.0  1.0   2.0  24.85           24.85   µg/m³
3 1999-05-01 03:00:00  1999.0  5.0  1.0   3.0  22.96           22.96   µg/m³
4 1999-05-01 04:00:00  1999.0  5.0  1.0   4.0  22.99           22.99   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
004
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/NO2/SP0091RA004.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
19033257           229.0   ug/m3 2015-09-25 10:00:00
13301630           226.0   ug/m3 2019-01-31 12:00:00
19033256           213.0   ug/m3 2015-09-25 09:00:00
18090657           204.0   ug/m3 2017-08-29 20:00:00
19033258           202.0   ug/m3 2015-09-25 11:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1998-01-01 01:00:00  1998    1    1     1   33.0            33.0   µg/m3
1 1998-01-01 02:00:00  1998    1    1     2   34.0            34.0   µg/m3
2 1998-01-01 03:00:00  1998    1    1     3   35.0            35.0   µg/m3
3 1998-01-01 04:00:00  1998    1    1     4   32.0            32.0   µg/m3
4 1998-01-01 05:00:00  1998    1    1     5   29.0            29.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1998-01-01 01:00:00  1998    1    1     1   33.0            33.0   µg/m3
1 1998-01-01 02:00:00  1998    1    1     2   34.0            34.0   µg/m3
2 1998-01-01 03:00:00  1998    1    1     3   35.0            35.0   µg/m3
3 1998-01-01 04:00:00  1998    1    1     4   32.0            32.0   µg/m3
4 1998-01-01 05:00:00  1998    1    1     5   29.0            29.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
004
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/NO2/BA0005ND004.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
         VALOR_ORIGINAL UNIDADE            DATETIME
5328489      475.470824   ug/m3 2017-12-13 10:00:00
5328488      475.470824   ug/m3 2017-12-13 09:00:00
5328490      475.470824   ug/m3 2017-12-13 11:00:00
5328491      475.470824   ug/m3 2017-12-13 12:00:00
5323696       52.773163   ug/m3 2017-05-15 13:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1998-01-01 00:00:00  1998    1    1     0    NaN             NaN   ug/m³
1 1998-01-01 01:00:00  1998    1    1     1    NaN             NaN   ug/m³
2 1998-01-01 02:00:00  1998    1    1     2    NaN             NaN   ug/m³
3 1998-01-01 03:00:00  1998    1    1     3    NaN             NaN   ug/m³
4 1998-01-01 04:00:00  1998    1    1     4    NaN             NaN   ug/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1998-01-01 00:00:00  1998    1    1     0    NaN             NaN   ug/m³
1 1998-01-01 01:00:00  1998    1    1     1    NaN             NaN   ug/m³
2 1998-01-01 02:00:00  1998    1    1     2    NaN             NaN   ug/m³
3 1998-01-01 03:00:00  1998    1    1     3    NaN             NaN   ug/m³
4 1998-01-01 04:00:00  1998    1    1     4    NaN             NaN   ug/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
004
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/NO2/SP0288RA004.csv
iema
          VALOR_ORIGINAL UNIDADE            DATETIME
7888260             73.0   ug/m3 2019-04-27 21:00:00
7007766             70.0   ug/m3 2017-08-10 10:00:00
11127725            69.0   ug/m3 2021-09-20 19:00:00
11127564            64.0   ug/m3 2021-09-13 19:00:00
7008503             61.0   ug/m3 2017-09-14 20:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2016-12-07 13:00:00  2016   12    7    13    5.0             5.0   µg/m3
1 2016-12-07 14:00:00  2016   12    7    14    5.0             5.0   µg/m3
2 2016-12-07 15:00:00  2016   12    7    15    4.0             4.0   µg/m3
3 2016-12-07 16:00:00  2016   12    7    16    NaN             NaN     NaN
4 2016-12-07 17:00:00  2016   12    7    17    5.0             5.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True     False
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2016-12-07 13:00:00  2016   12    7    13    5.0             5.0   ug/m3
1 2016-12-07 14:00:00  2016   12    7    14    5.0             5.0   ug/m3
2 2016-12-07 15:00:00  2016   12    7    15    4.0             4.0   ug/m3
3 2016-12-07 16:00:00  2016   12    7    16    NaN             NaN     NaN
4 2016-12-07 17:00:00  2016   12    7    17    5.0             5.0   ug/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True     False
4          True      True

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

004
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/NO2/RJ0045RA004.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
28836739      673.089892   µg/m3 2019-10-24 12:00:00
28822081      237.671288   µg/m3 2019-10-21 10:00:00
21948060      176.989915   ug/m3 2017-10-24 11:00:00
21943437      154.999390   ug/m3 2017-01-25 15:00:00
21944578      111.038833   ug/m3 2017-03-29 10:00:00
mma
             DATETIME     ANO  MES   DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2001-05-12 23:00:00  2001.0  5.0  12.0  23.0    NaN             NaN   µg/m³
1 2001-05-13 00:00:00  2001.0  5.0  13.0   0.0    NaN             NaN   µg/m³
2 2001-05-13 01:00:00  2001.0  5.0  13.0   1.0    NaN             NaN   µg/m³
3 2001-05-13 02:00:00  2001.0  5.0  13.0   2.0    NaN             NaN   µg/m³
4 2001-05-13 03:00:00  2001.0  5.0  13.0   3.0    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0         False     False
1         False     False
2         False     False
3         False     False
4         False     False
final
             DATETIME     ANO  MES   DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2001-05-12 23:00:00  2001.0  5.0  12.0  23.0    NaN             NaN   µg/m³
1 2001-05-13 00:00:00  2001.0  5.0  13.0   0.0    NaN             NaN   µg/m³
2 2001-05-13 01:00:00  2001.0  5.0  13.0   1.0    NaN             NaN   µg/m³
3 2001-05-13 02:00:00  2001.0  5.0  13.0   2.0    NaN             NaN   µg/m³
4 2001-05-13 03:00:00  2001.0  5.0  13.0   3.0    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
004
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/NO2/MG0039RA004.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
34412358           99.26   µg/m3 2019-07-02 19:30:00
36770494           86.18   µg/m3 2018-08-25 11:30:00
34412509           85.09   µg/m3 2019-07-02 20:30:00
39467560           72.99   µg/m3 2022-09-09 10:30:00
37915310           71.04   µg/m3 2021-07-13 18:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2017-05-03 09:00:00  2017    5    3     9    NaN             NaN   µg/m3
1 2017-05-03 10:00:00  2017    5    3    10    NaN             NaN   µg/m3
2 2017-05-03 11:00:00  2017    5    3    11    NaN             NaN   µg/m3
3 2017-05-03 12:00:00  2017    5    3    12    NaN             NaN   µg/m3
4 2017-05-03 13:00:00  2017    5    3    13    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2017-05-03 09:00:00  2017    5    3     9    NaN             NaN   µg/m3
1 2017-05-03 10:00:00  2017    5    3    10    NaN             NaN   µg/m3
2 2017-05-03 11:00:00  2017    5    3    11    NaN             NaN   µg/m3
3 2017-05-03 12:00:00  2017    5    3    12    NaN             NaN   µg/m3
4 2017-05-03 13:00:00  2017    5    3    13    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
004
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/NO2/RJ0079RA004.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
30977061      123.257873   µg/m3 2020-02-13 11:00:00
19804828      105.945317   µg/m3 2019-03-12 11:00:00
20299337       85.810061   µg/m3 2019-07-09 14:00:00
19696594       74.519264   µg/m3 2019-02-14 10:00:00
30977246       69.250225   µg/m3 2020-02-13 12:00:00
mma
             DATETIME     ANO   MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1998-10-01 00:00:00  1998.0  10.0  1.0   0.0    NaN             0.0   µg/m³
1 1998-10-01 01:00:00  1998.0  10.0  1.0   1.0    NaN             NaN   µg/m³
2 1998-10-01 02:00:00  1998.0  10.0  1.0   2.0    NaN             NaN   µg/m³
3 1998-10-01 03:00:00  1998.0  10.0  1.0   3.0    NaN             NaN   µg/m³
4 1998-10-01 04:00:00  1998.0  10.0  1.0   4.0    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1         False     False
2         False     False
3         False     False
4         False     False
final
             DATETIME     ANO   MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1998-10-01 00:00:00  1998.0  10.0  1.0   0.0    NaN             0.0   µg/m³
1 1998-10-01 01:00:00  1998.0  10.0  1.0   1.0    NaN             NaN   µg/m³
2 1998-10-01 02:00:00  1998.0  10.0  1.0   2.0    NaN             NaN   µg/m³
3 1998-10-01 03:00:00  1998.0  10.0  1.0   3.0    NaN             NaN   µg/m³
4 1998-10-01 04:00:00  1998.0  10.0  1.0   4.0    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
004
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/NO2/RJ0055RA004.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
29413114       402.00000     ppb 2016-05-03 16:30:00
29413115       299.00000     ppb 2016-05-03 17:30:00
29413113       128.00000     ppb 2016-05-03 15:30:00
27451961        49.49000     ppb 2015-05-27 21:30:00
25290053        46.05826   ug/m3 2017-08-30 20:00:00
mma
             DATETIME     ANO   MES   DIA  HORA  VALOR  VALOR_ORIGINAL  \
0 2001-12-29 10:00:00  2001.0  12.0  29.0  10.0    NaN             NaN
1 2001-12-29 11:00:00  2001.0  12.0  29.0  11.0    NaN             NaN
2 2001-12-29 12:00:00  2001.0  12.0  29.0  12.0    NaN             NaN
3 2001-12-29 13:00:00  2001.0  12.0  29.0  13.0    NaN             NaN
4 2001-12-29 14:00:00  2001.0  12.0  29.0  14.0    NaN             NaN

  UNIDADE  QAQC_INTERNO  QAQC_MMA
0   µg/m³         False     False
1   µg/m³         False     False
2   µg/m³         False     False
3   µg/m³         False     False
4   µg/m³         False     False
final
             DATETIME     ANO   MES   DIA  HORA  VALOR  VALOR_ORIGINAL  \
0 2001-12-29 10:00:00  2001.0  12.0  29.0  10.0    NaN             NaN
1 2001-12-29 11:00:00  2001.0  12.0  29.0  11.0    NaN             NaN
2 2001-12-29 12:00:00  2001.0  12.0  29.0  12.0    NaN             NaN
3 2001-12-29 13:00:00  2001.0  12.0  29.0  13.0    NaN             NaN
4 2001-12-29 14:00:00  2001.0  12.0  29.0  14.0    NaN             NaN

  UNIDADE  QAQC_INTERNO  QAQC_MMA
0   µg/m³          True     False
1   µg/m³          True     False
2   µg/m³          True     False
3   µg/m³          True     False
4   µg/m³          True     False
004
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/NO2/RJ0226RA004.csv
iema
          VALOR_ORIGINAL UNIDADE            DATETIME
29557470         176.706   ug/m3 2016-07-11 11:30:00
29557565         148.907   ug/m3 2016-07-15 10:30:00
29557478         148.432   ug/m3 2016-07-11 19:30:00
29557566         146.985   ug/m3 2016-07-15 11:30:00
29557502         145.071   ug/m3 2016-07-12 19:30:00
mma
             DATETIME     ANO  MES   DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2006-07-21 00:00:00  2006.0  7.0  21.0   0.0    NaN             NaN   µg/m³
1 2006-07-21 01:00:00  2006.0  7.0  21.0   1.0  27.02           27.02   µg/m³
2 2006-07-21 02:00:00  2006.0  7.0  21.0   2.0  28.43           28.43   µg/m³
3 2006-07-21 03:00:00  2006.0  7.0  21.0   3.0  25.45           25.45   µg/m³
4 2006-07-21 04:00:00  2006.0  7.0  21.0   4.0  29.10           29.10   µg/m³

   QAQC_INTERNO  QAQC_MMA
0         False     False
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME     ANO  MES   DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2006-07-21 00:00:00  2006.0  7.0  21.0   0.0    NaN             NaN   µg/m³
1 2006-07-21 01:00:00  2006.0  7.0  21.0   1.0  27.02           27.02   µg/m³
2 2006-07-21 02:00:00  2006.0  7.0  21.0   2.0  28.43           28.43   µg/m³
3 2006-07-21 03:00:00  2006.0  7.0  21.0   3.0  25.45           25.45   µg/m³
4 2006-07-21 04:00:00  2006.0  7.0  21.0   4.0  29.10           29.10   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True      True
2          True      True
3          True      True
4          True      True

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

004
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/NO2/SP0258RA004.csv
iema
          VALOR_ORIGINAL UNIDADE            DATETIME
17623054           200.0   ug/m3 2015-08-01 11:00:00
17624776           146.0   ug/m3 2015-10-15 20:00:00
12100965           145.0   ug/m3 2016-07-12 20:00:00
17623053           135.0   ug/m3 2015-08-01 10:00:00
15292389           131.0   ug/m3 2018-06-12 18:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2011-06-07 01:00:00  2011    6    7     1   53.0            53.0   µg/m3
1 2011-06-07 02:00:00  2011    6    7     2    NaN             NaN     NaN
2 2011-06-07 03:00:00  2011    6    7     3   46.0            46.0   µg/m3
3 2011-06-07 04:00:00  2011    6    7     4   50.0            50.0   µg/m3
4 2011-06-07 05:00:00  2011    6    7     5   53.0            53.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True     False
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2011-06-07 01:00:00  2011    6    7     1   53.0            53.0   µg/m3
1 2011-06-07 02:00:00  2011    6    7     2    NaN             NaN     NaN
2 2011-06-07 03:00:00  2011    6    7     3   46.0            46.0   µg/m3
3 2011-06-07 04:00:00  2011    6    7     4   50.0            50.0   µg/m3
4 2011-06-07 05:00:00  2011    6    7     5   53.0            53.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True     False
2          True      True
3          True      True
4          True      True

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

004
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/NO2/RJ0063RA004.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
28367081       93.025720   µg/m3 2019-07-12 17:00:00
28371933       90.277765   µg/m3 2019-07-13 18:00:00
28367272       89.925451   µg/m3 2019-07-12 18:00:00
25359790       87.469670   ug/m3 2017-09-15 19:00:00
25359936       85.542050   ug/m3 2017-09-22 20:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2016-06-15 10:00:00  2016    6   15    10    NaN             NaN   µg/m³
1 2016-06-15 11:00:00  2016    6   15    11    NaN             NaN   µg/m³
2 2016-06-15 12:00:00  2016    6   15    12    NaN             NaN   µg/m³
3 2016-06-15 13:00:00  2016    6   15    13    NaN             NaN   µg/m³
4 2016-06-15 14:00:00  2016    6   15    14    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0         False     False
1         False     False
2         False     False
3         False     False
4         False     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2016-06-15 10:00:00  2016    6   15    10    NaN             NaN   µg/m³
1 2016-06-15 11:00:00  2016    6   15    11    NaN             NaN   µg/m³
2 2016-06-15 12:00:00  2016    6   15    12    NaN             NaN   µg/m³
3 2016-06-15 13:00:00  2016    6   15    13    NaN             NaN   µg/m³
4 2016-06-15 14:00:00  2016    6   15    14    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
004
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/NO2/SP0116RA004.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
10701343           150.0   ug/m3 2020-10-05 20:00:00
15374740           142.0   ug/m3 2018-09-10 20:00:00
10701344           137.0   ug/m3 2020-10-05 21:00:00
10701413           136.0   ug/m3 2020-10-08 21:00:00
7265911            135.0   ug/m3 2017-08-28 20:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2008-06-26 02:00:00  2008    6   26     2   33.0            33.0   µg/m3
1 2008-06-26 03:00:00  2008    6   26     3   30.0            30.0   µg/m3
2 2008-06-26 04:00:00  2008    6   26     4   33.0            33.0   µg/m3
3 2008-06-26 05:00:00  2008    6   26     5   31.0            31.0   µg/m3
4 2008-06-26 06:00:00  2008    6   26     6   31.0            31.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2008-06-26 02:00:00  2008    6   26     2   33.0            33.0   µg/m3
1 2008-06-26 03:00:00  2008    6   26     3   30.0            30.0   µg/m3
2 2008-06-26 04:00:00  2008    6   26     4   33.0            33.0   µg/m3
3 2008-06-26 05:00:00  2008    6   26     5   31.0            31.0   µg/m3
4 2008-06-26 06:00:00  2008    6   26     6   31.0            31.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
004
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/NO2/RJ0043RA004.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
19603434      171.601305   µg/m3 2019-01-22 10:00:00
21994772      112.452949   ug/m3 2017-05-06 15:00:00
19604045       99.246110   µg/m3 2019-01-22 14:00:00
28621451       97.121233   µg/m3 2019-09-07 11:00:00
28621631       75.532778   µg/m3 2019-09-07 12:00:00
mma
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2009-06-06 20:00:00  2009.0  6.0  6.0  20.0  10.70           10.70   µg/m³
1 2009-06-06 21:00:00  2009.0  6.0  6.0  21.0   9.27            9.27   µg/m³
2 2009-06-06 22:00:00  2009.0  6.0  6.0  22.0   6.33            6.33   µg/m³
3 2009-06-06 23:00:00  2009.0  6.0  6.0  23.0   3.37            3.37   µg/m³
4 2009-06-07 00:00:00  2009.0  6.0  7.0   0.0   2.77            2.77   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2009-06-06 20:00:00  2009.0  6.0  6.0  20.0  10.70           10.70   µg/m³
1 2009-06-06 21:00:00  2009.0  6.0  6.0  21.0   9.27            9.27   µg/m³
2 2009-06-06 22:00:00  2009.0  6.0  6.0  22.0   6.33            6.33   µg/m³
3 2009-06-06 23:00:00  2009.0  6.0  6.0  23.0   3.37            3.37   µg/m³
4 2009-06-07 00:00:00  2009.0  6.0  7.0   0.0   2.77            2.77   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
004
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/NO2/SP0289RA004.csv
iema
          VALOR_ORIGINAL UNIDADE            DATETIME
13559361            88.0   ug/m3 2019-09-17 20:00:00
13559362            87.0   ug/m3 2019-09-17 21:00:00
13558369            79.0   ug/m3 2019-08-01 20:00:00
9717369             75.0   ug/m3 2018-07-17 20:00:00
8802459             75.0   ug/m3 2022-09-09 20:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2017-03-27 15:00:00  2017    3   27    15    9.0             9.0   µg/m3
1 2017-03-27 16:00:00  2017    3   27    16   12.0            12.0   µg/m3
2 2017-03-27 17:00:00  2017    3   27    17   11.0            11.0   µg/m3
3 2017-03-27 18:00:00  2017    3   27    18   19.0            19.0   µg/m3
4 2017-03-27 19:00:00  2017    3   27    19   51.0            51.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2017-03-27 15:00:00  2017    3   27    15    9.0             9.0   ug/m3
1 2017-03-27 16:00:00  2017    3   27    16   12.0            12.0   ug/m3
2 2017-03-27 17:00:00  2017    3   27    17   11.0            11.0   ug/m3
3 2017-03-27 18:00:00  2017    3   27    18   19.0            19.0   ug/m3
4 2017-03-27 19:00:00  2017    3   27    19   51.0            51.0   ug/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

004
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/NO2/RJ0044RA004.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
21926251      205.272232   ug/m3 2017-09-26 12:00:00
21927764      163.934962   ug/m3 2017-12-13 10:00:00
21926912      130.938927   ug/m3 2017-10-25 09:00:00
21927470       91.712584   ug/m3 2017-11-29 08:00:00
26649473       58.320000     ppb 2015-05-28 11:30:00
mma
             DATETIME     ANO  MES   DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2002-02-10 03:00:00  2002.0  2.0  10.0   3.0    NaN             NaN   µg/m³
1 2002-02-10 04:00:00  2002.0  2.0  10.0   4.0    NaN             NaN   µg/m³
2 2002-02-10 05:00:00  2002.0  2.0  10.0   5.0    NaN             NaN   µg/m³
3 2002-02-10 06:00:00  2002.0  2.0  10.0   6.0    NaN             NaN   µg/m³
4 2002-02-10 07:00:00  2002.0  2.0  10.0   7.0    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0         False     False
1         False     False
2         False     False
3         False     False
4         False     False
final
             DATETIME     ANO  MES   DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2002-02-10 03:00:00  2002.0  2.0  10.0   3.0    NaN             NaN   µg/m³
1 2002-02-10 04:00:00  2002.0  2.0  10.0   4.0    NaN             NaN   µg/m³
2 2002-02-10 05:00:00  2002.0  2.0  10.0   5.0    NaN             NaN   µg/m³
3 2002-02-10 06:00:00  2002.0  2.0  10.0   6.0    NaN             NaN   µg/m³
4 2002-02-10 07:00:00  2002.0  2.0  10.0   7.0    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
004
004
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/NO2/MG0001RA004.csv

/tmp/ipykernel_273420/1352582357.py:97: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  df_mma = pd.read_csv(arquivo, encoding = 'UTF-8')
/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
37284808          212.94   µg/m3 2021-01-28 11:30:00
32597277          203.22   µg/m3 2020-09-20 12:30:00
38198367          184.39   µg/m3 2021-09-21 19:30:00
35169801          171.43   µg/m3 2017-03-14 22:30:00
37233477          167.99   µg/m3 2021-01-14 08:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR VALOR_ORIGINAL UNIDADE  \
0 2009-01-01 01:00:00  2009    1    1     1    NaN              -     ppb
1 2009-01-01 02:00:00  2009    1    1     2    NaN              -     ppb
2 2009-01-01 03:00:00  2009    1    1     3    NaN              -     ppb
3 2009-01-01 04:00:00  2009    1    1     4    NaN              -     ppb
4 2009-01-01 05:00:00  2009    1    1     5    NaN              -     ppb

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR VALOR_ORIGINAL UNIDADE  \
0 2009-01-01 01:00:00  2009    1    1     1    NaN              -     ppb
1 2009-01-01 02:00:00  2009    1    1     2    NaN              -     ppb
2 2009-01-01 03:00:00  2009    1    1     3    NaN              -     ppb
3 2009-01-01 04:00:00  2009    1    1     4    NaN              -     ppb
4 2009-01-01 05:00:00  2009    1    1     5    NaN              -     ppb

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
004
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/NO2/SP0120RA004.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
10872997           209.0   ug/m3 2021-08-21 11:00:00
6710341            207.0   ug/m3 2017-08-29 19:00:00
10873074           196.0   ug/m3 2021-08-24 19:00:00
10873097           196.0   ug/m3 2021-08-25 19:00:00
10872468           191.0   ug/m3 2021-07-21 19:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1998-01-01 01:00:00  1998    1    1     1   40.0            40.0   µg/m3
1 1998-01-01 02:00:00  1998    1    1     2   46.0            46.0   µg/m3
2 1998-01-01 03:00:00  1998    1    1     3   44.0            44.0   µg/m3
3 1998-01-01 04:00:00  1998    1    1     4   39.0            39.0   µg/m3
4 1998-01-01 05:00:00  1998    1    1     5   34.0            34.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1998-01-01 01:00:00  1998    1    1     1   40.0            40.0   µg/m3
1 1998-01-01 02:00:00  1998    1    1     2   46.0            46.0   µg/m3
2 1998-01-01 03:00:00  1998    1    1     3   44.0            44.0   µg/m3
3 1998-01-01 04:00:00  1998    1    1     4   39.0            39.0   µg/m3
4 1998-01-01 05:00:00  1998    1    1     5   34.0            34.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
004
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/NO2/MG0006RA004.csv

/tmp/ipykernel_273420/1352582357.py:97: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  df_mma = pd.read_csv(arquivo, encoding = 'UTF-8')
/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
32563839          255.28   µg/m3 2020-09-10 18:30:00
35258965          217.95   µg/m3 2017-08-03 06:30:00
35258967          196.43   µg/m3 2017-08-10 19:30:00
35258968          190.73   µg/m3 2017-08-03 07:30:00
35258969          189.73   µg/m3 2017-06-30 19:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR VALOR_ORIGINAL UNIDADE  \
0 2010-01-01 01:00:00  2010    1    1     1    6.5            6.5     ppb
1 2010-01-01 02:00:00  2010    1    1     2    8.2            8.2     ppb
2 2010-01-01 03:00:00  2010    1    1     3    6.5            6.5     ppb
3 2010-01-01 04:00:00  2010    1    1     4    9.0              9     ppb
4 2010-01-01 05:00:00  2010    1    1     5   11.5           11.5     ppb

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR VALOR_ORIGINAL UNIDADE  \
0 2010-01-01 01:00:00  2010    1    1     1    6.5            6.5     ppb
1 2010-01-01 02:00:00  2010    1    1     2    8.2            8.2     ppb
2 2010-01-01 03:00:00  2010    1    1     3    6.5            6.5     ppb
3 2010-01-01 04:00:00  2010    1    1     4    9.0              9     ppb
4 2010-01-01 05:00:00  2010    1    1     5   11.5           11.5     ppb

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
004
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/NO2/MG0011RA004.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
39676674           92.13   µg/m3 2022-11-06 22:30:00
39601838           91.90   µg/m3 2022-10-16 22:30:00
39594258           91.84   µg/m3 2022-10-14 21:30:00
39601995           88.15   µg/m3 2022-10-16 23:30:00
39590570           87.34   µg/m3 2022-10-13 21:30:00
mma
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2014-01-01 01:00:00  2014.0  1.0  1.0   1.0  24.27           24.27   µg/m3
1 2014-01-01 02:00:00  2014.0  1.0  1.0   2.0  22.56           22.56   µg/m3
2 2014-01-01 03:00:00  2014.0  1.0  1.0   3.0  21.89           21.89   µg/m3
3 2014-01-01 04:00:00  2014.0  1.0  1.0   4.0  19.84           19.84   µg/m3
4 2014-01-01 05:00:00  2014.0  1.0  1.0   5.0  17.26           17.26   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2014-01-01 01:00:00  2014.0  1.0  1.0   1.0  24.27           24.27   µg/m3
1 2014-01-01 02:00:00  2014.0  1.0  1.0   2.0  22.56           22.56   µg/m3
2 2014-01-01 03:00:00  2014.0  1.0  1.0   3.0  21.89           21.89   µg/m3
3 2014-01-01 04:00:00  2014.0  1.0  1.0   4.0  19.84           19.84   µg/m3
4 2014-01-01 05:00:00  2014.0  1.0  1.0   5.0  17.26           17.26   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
004
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/NO2/RJ0018RA004.csv
iema
          VALOR_ORIGINAL UNIDADE            DATETIME
19827387      184.272389   µg/m3 2019-03-18 03:00:00
28952802      164.092924   µg/m3 2019-11-18 11:00:00
19998567      157.694806   µg/m3 2019-04-29 02:00:00
19928948      129.223242   µg/m3 2019-04-12 06:00:00
19998977      104.816237   µg/m3 2019-04-29 05:00:00
mma
             DATETIME     ANO  MES   DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2012-05-10 00:00:00  2012.0  5.0  10.0   0.0    NaN             NaN   µg/m³
1 2012-05-10 01:00:00  2012.0  5.0  10.0   1.0    NaN             NaN   µg/m³
2 2012-05-10 02:00:00  2012.0  5.0  10.0   2.0    NaN             NaN   µg/m³
3 2012-05-10 03:00:00  2012.0  5.0  10.0   3.0    NaN             NaN   µg/m³
4 2012-05-10 04:00:00  2012.0  5.0  10.0   4.0    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0         False     False
1         False     False
2         False     False
3         False     False
4         False     False
final
             DATETIME     ANO  MES   DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2012-05-10 00:00:00  2012.0  5.0  10.0   0.0    NaN             NaN   µg/m³
1 2012-05-10 01:00:00  2012.0  5.0  10.0   1.0    NaN             NaN   µg/m³
2 2012-05-10 02:00:00  2012.0  5.0  10.0   2.0    NaN             NaN   µg/m³
3 2012-05-10 03:00:00  2012.0  5.0  10.0   3.0    NaN             NaN   µg/m³
4 2012-05-10 04:00:00  2012.0  5.0  10.0   4.0    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

004
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/NO2/MG0002RA004.csv

/tmp/ipykernel_273420/1352582357.py:97: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  df_mma = pd.read_csv(arquivo, encoding = 'UTF-8')
/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
40107643          289.89   µg/m3 2016-05-23 10:30:00
40107697          151.98   µg/m3 2016-12-12 16:30:00
33161515          129.28   µg/m3 2015-12-18 18:30:00
32230199          127.23   µg/m3 2020-06-08 10:30:00
33161525          125.83   µg/m3 2015-12-09 19:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR VALOR_ORIGINAL UNIDADE  \
0 2009-01-01 01:00:00  2009    1    1     1    NaN          InVld     ppb
1 2009-01-01 02:00:00  2009    1    1     2    NaN          InVld     ppb
2 2009-01-01 03:00:00  2009    1    1     3    NaN          InVld     ppb
3 2009-01-01 04:00:00  2009    1    1     4    NaN          InVld     ppb
4 2009-01-01 05:00:00  2009    1    1     5    NaN          InVld     ppb

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR VALOR_ORIGINAL UNIDADE  \
0 2009-01-01 01:00:00  2009    1    1     1    NaN          InVld     ppb
1 2009-01-01 02:00:00  2009    1    1     2    NaN          InVld     ppb
2 2009-01-01 03:00:00  2009    1    1     3    NaN          InVld     ppb
3 2009-01-01 04:00:00  2009    1    1     4    NaN          InVld     ppb
4 2009-01-01 05:00:00  2009    1    1     5    NaN          InVld     ppb

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
004
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/NO2/MG0057RA004.csv
iema
          VALOR_ORIGINAL UNIDADE            DATETIME
33884580          165.39   µg/m3 2019-01-30 19:30:00
33912770          123.99   µg/m3 2019-02-07 19:30:00
37378739          118.11   µg/m3 2021-02-24 01:30:00
37399520          117.63   µg/m3 2021-03-01 23:30:00
37381541          117.12   µg/m3 2021-02-24 20:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2019-01-01 01:00:00  2019    1    1     1  16.41           16.41   µg/m3
1 2019-01-01 02:00:00  2019    1    1     2  17.06           17.06   µg/m3
2 2019-01-01 03:00:00  2019    1    1     3  17.84           17.84   µg/m3
3 2019-01-01 04:00:00  2019    1    1     4  15.37           15.37   µg/m3
4 2019-01-01 05:00:00  2019    1    1     5   7.68            7.68   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2019-01-01 01:00:00  2019    1    1     1  16.41           16.41   µg/m3
1 2019-01-01 02:00:00  2019    1    1     2  17.06           17.06   µg/m3
2 2019-01-01 03:00:00  2019    1    1     3  17.84           17.84   µg/m3
3 2019-01-01 04:00:00  2019    1    1     4  15.37           15.37   µg/m3
4 2019-01-01 05:00:00  2019    1    1     5   7.68            7.68   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

004
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/NO2/SP0262RA004.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
19386277           188.0   ug/m3 2015-09-25 09:00:00
18563799           156.0   ug/m3 2017-09-14 20:00:00
18563509           154.0   ug/m3 2017-08-30 21:00:00
13667413           154.0   ug/m3 2019-08-30 21:00:00
19384720           152.0   ug/m3 2015-06-09 10:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2012-02-27 02:00:00  2012    2   27     2   27.0            27.0   µg/m3
1 2012-02-27 03:00:00  2012    2   27     3   27.0            27.0   µg/m3
2 2012-02-27 04:00:00  2012    2   27     4   21.0            21.0   µg/m3
3 2012-02-27 05:00:00  2012    2   27     5   18.0            18.0   µg/m3
4 2012-02-27 06:00:00  2012    2   27     6   31.0            31.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2012-02-27 02:00:00  2012    2   27     2   27.0            27.0   µg/m3
1 2012-02-27 03:00:00  2012    2   27     3   27.0            27.0   µg/m3
2 2012-02-27 04:00:00  2012    2   27     4   21.0            21.0   µg/m3
3 2012-02-27 05:00:00  2012    2   27     5   18.0            18.0   µg/m3
4 2012-02-27 06:00:00  2012    2   27     6   31.0            31.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
004
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/NO2/BA0006ND004.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
         VALOR_ORIGINAL UNIDADE            DATETIME
5240970       55.929305   ug/m3 2017-05-16 11:00:00
5239846       53.715906   ug/m3 2017-03-30 11:00:00
5242825       42.382486   ug/m3 2017-08-02 09:00:00
5242824       39.882165   ug/m3 2017-08-02 08:00:00
5242938       39.103376   ug/m3 2017-08-14 06:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1998-01-01 00:00:00  1998    1    1     0    NaN             NaN   ug/m³
1 1998-01-01 01:00:00  1998    1    1     1    NaN             NaN   ug/m³
2 1998-01-01 02:00:00  1998    1    1     2    NaN             NaN   ug/m³
3 1998-01-01 03:00:00  1998    1    1     3    NaN             NaN   ug/m³
4 1998-01-01 04:00:00  1998    1    1     4    NaN             NaN   ug/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1998-01-01 00:00:00  1998    1    1     0    NaN             NaN   ug/m³
1 1998-01-01 01:00:00  1998    1    1     1    NaN             NaN   ug/m³
2 1998-01-01 02:00:00  1998    1    1     2    NaN             NaN   ug/m³
3 1998-01-01 03:00:00  1998    1    1     3    NaN             NaN   ug/m³
4 1998-01-01 04:00:00  1998    1    1     4    NaN             NaN   ug/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
004
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/NO2/RJ0036RA004.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
30709630          124.62   µg/m³ 2022-09-09 18:00:00
30708701          113.27   µg/m³ 2022-08-01 19:00:00
26471315          109.80   µg/m³ 2021-08-25 18:00:00
30709727          108.67   µg/m³ 2022-09-13 20:00:00
26469868          105.97   µg/m³ 2021-06-25 19:00:00
mma
             DATETIME     ANO  MES   DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2011-08-26 10:00:00  2011.0  8.0  26.0  10.0  26.49           26.49   µg/m³
1 2011-08-26 11:00:00  2011.0  8.0  26.0  11.0  21.54           21.54   µg/m³
2 2011-08-26 12:00:00  2011.0  8.0  26.0  12.0  17.78           17.78   µg/m³
3 2011-08-26 13:00:00  2011.0  8.0  26.0  13.0  14.56           14.56   µg/m³
4 2011-08-26 14:00:00  2011.0  8.0  26.0  14.0  21.42           21.42   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME     ANO  MES   DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2011-08-26 10:00:00  2011.0  8.0  26.0  10.0  26.49           26.49   µg/m³
1 2011-08-26 11:00:00  2011.0  8.0  26.0  11.0  21.54           21.54   µg/m³
2 2011-08-26 12:00:00  2011.0  8.0  26.0  12.0  17.78           17.78   µg/m³
3 2011-08-26 13:00:00  2011.0  8.0  26.0  13.0  14.56           14.56   µg/m³
4 2011-08-26 14:00:00  2011.0  8.0  26.0  14.0  21.42           21.42   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
004
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/NO2/RJ0081RA004.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
24938559       120.46030   ug/m3 2017-08-23 14:00:00
24934190       115.83950   ug/m3 2017-02-15 15:00:00
23755028        91.36921   µg/m3 2020-09-14 19:00:00
23764619        82.49287   µg/m3 2020-09-16 19:00:00
24938996        80.83004   ug/m3 2017-09-15 19:00:00
mma
             DATETIME     ANO  MES   DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2005-09-18 20:00:00  2005.0  9.0  18.0  20.0  24.46           24.46   µg/m³
1 2005-09-18 21:00:00  2005.0  9.0  18.0  21.0  19.20           19.20   µg/m³
2 2005-09-18 22:00:00  2005.0  9.0  18.0  22.0    NaN             NaN   µg/m³
3 2005-09-18 23:00:00  2005.0  9.0  18.0  23.0    NaN             NaN   µg/m³
4 2005-09-19 00:00:00  2005.0  9.0  19.0   0.0    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2         False     False
3         False     False
4         False     False
final
             DATETIME     ANO  MES   DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2005-09-18 20:00:00  2005.0  9.0  18.0  20.0  24.46           24.46   µg/m³
1 2005-09-18 21:00:00  2005.0  9.0  18.0  21.0  19.20           19.20   µg/m³
2 2005-09-18 22:00:00  2005.0  9.0  18.0  22.0    NaN             NaN   µg/m³
3 2005-09-18 23:00:00  2005.0  9.0  18.0  23.0    NaN             NaN   µg/m³
4 2005-09-19 00:00:00  2005.0  9.0  19.0   0.0    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True     False
3          True     False
4          True     False
004
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/NO2/SP0106RA004.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
13964545           183.0   ug/m3 2016-08-17 20:00:00
13964475           180.0   ug/m3 2016-08-14 22:00:00
13964476           176.0   ug/m3 2016-08-14 23:00:00
13964450           169.0   ug/m3 2016-08-13 21:00:00
15546336           168.0   ug/m3 2021-08-11 06:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2008-07-11 02:00:00  2008    7   11     2   27.0            27.0   µg/m3
1 2008-07-11 03:00:00  2008    7   11     3   26.0            26.0   µg/m3
2 2008-07-11 04:00:00  2008    7   11     4   20.0            20.0   µg/m3
3 2008-07-11 05:00:00  2008    7   11     5   14.0            14.0   µg/m3
4 2008-07-11 06:00:00  2008    7   11     6   23.0            23.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2008-07-11 02:00:00  2008    7   11     2   27.0            27.0   µg/m3
1 2008-07-11 03:00:00  2008    7   11     3   26.0            26.0   µg/m3
2 2008-07-11 04:00:00  2008    7   11     4   20.0            20.0   µg/m3
3 2008-07-11 05:00:00  2008    7   11     5   14.0            14.0   µg/m3
4 2008-07-11 06:00:00  2008    7   11     6   23.0            23.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
004
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/NO2/MG0012RA004.csv

/tmp/ipykernel_273420/1352582357.py:97: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  df_mma = pd.read_csv(arquivo, encoding = 'UTF-8')
/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
32657364         977.640   µg/m3 2020-10-06 19:30:00
32677198         940.038   µg/m3 2020-10-12 11:30:00
32928969         940.038   µg/m3 2020-12-22 03:30:00
32677623         940.038   µg/m3 2020-10-12 14:30:00
32678472         940.038   µg/m3 2020-10-12 20:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR VALOR_ORIGINAL UNIDADE  \
0 2014-01-01 01:00:00  2014    1    1     1    NaN              *     ppb
1 2014-01-01 02:00:00  2014    1    1     2    NaN              *     ppb
2 2014-01-01 03:00:00  2014    1    1     3    NaN              *     ppb
3 2014-01-01 04:00:00  2014    1    1     4    NaN              *     ppb
4 2014-01-01 05:00:00  2014    1    1     5    NaN              *     ppb

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR VALOR_ORIGINAL UNIDADE  \
0 2014-01-01 01:00:00  2014    1    1     1    NaN              *     ppb
1 2014-01-01 02:00:00  2014    1    1     2    NaN              *     ppb
2 2014-01-01 03:00:00  2014    1    1     3    NaN              *     ppb
3 2014-01-01 04:00:00  2014    1    1     4    NaN              *     ppb
4 2014-01-01 05:00:00  2014    1    1     5    NaN              *     ppb

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
004
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/NO2/BA0008ND004.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
         VALOR_ORIGINAL UNIDADE            DATETIME
5313293       89.478690   ug/m3 2017-01-08 20:00:00
5313292       74.538249   ug/m3 2017-01-08 19:00:00
5313557       70.644307   ug/m3 2017-01-19 20:00:00
5313556       69.066236   ug/m3 2017-01-19 19:00:00
5314405       65.254272   ug/m3 2017-03-10 19:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1998-01-01 00:00:00  1998    1    1     0    NaN             NaN   ug/m³
1 1998-01-01 01:00:00  1998    1    1     1    NaN             NaN   ug/m³
2 1998-01-01 02:00:00  1998    1    1     2    NaN             NaN   ug/m³
3 1998-01-01 03:00:00  1998    1    1     3    NaN             NaN   ug/m³
4 1998-01-01 04:00:00  1998    1    1     4    NaN             NaN   ug/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1998-01-01 00:00:00  1998    1    1     0    NaN             NaN   ug/m³
1 1998-01-01 01:00:00  1998    1    1     1    NaN             NaN   ug/m³
2 1998-01-01 02:00:00  1998    1    1     2    NaN             NaN   ug/m³
3 1998-01-01 03:00:00  1998    1    1     3    NaN             NaN   ug/m³
4 1998-01-01 04:00:00  1998    1    1     4    NaN             NaN   ug/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
004
004
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/NO2/SP0263RA004.csv
iema
          VALOR_ORIGINAL UNIDADE            DATETIME
14108128           190.0   ug/m3 2016-06-16 11:00:00
18974586           184.0   ug/m3 2015-06-09 11:00:00
18016291           178.0   ug/m3 2017-08-29 19:00:00
18016315           165.0   ug/m3 2017-08-30 20:00:00
18974996           165.0   ug/m3 2015-06-29 10:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2012-02-27 01:00:00  2012    2   27     1   31.0            31.0   µg/m3
1 2012-02-27 02:00:00  2012    2   27     2   20.0            20.0   µg/m3
2 2012-02-27 03:00:00  2012    2   27     3   26.0            26.0   µg/m3
3 2012-02-27 04:00:00  2012    2   27     4   23.0            23.0   µg/m3
4 2012-02-27 05:00:00  2012    2   27     5   32.0            32.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2012-02-27 01:00:00  2012    2   27     1   31.0            31.0   µg/m3
1 2012-02-27 02:00:00  2012    2   27     2   20.0            20.0   µg/m3
2 2012-02-27 03:00:00  2012    2   27     3   26.0            26.0   µg/m3
3 2012-02-27 04:00:00  2012    2   27     4   23.0            23.0   µg/m3
4 2012-02-27 05:00:00  2012    2   27     5   32.0            32.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

004
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/NO2/SP0109RA004.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
13788299           160.0   ug/m3 2019-08-09 12:00:00
9032263            135.0   ug/m3 2022-07-22 19:00:00
16163788           134.0   ug/m3 2021-08-24 20:00:00
18681210           134.0   ug/m3 2017-08-29 20:00:00
9033392            133.0   ug/m3 2022-09-09 21:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2008-10-15 02:00:00  2008   10   15     2   19.0            19.0   µg/m3
1 2008-10-15 03:00:00  2008   10   15     3   13.0            13.0   µg/m3
2 2008-10-15 04:00:00  2008   10   15     4   12.0            12.0   µg/m3
3 2008-10-15 05:00:00  2008   10   15     5   18.0            18.0   µg/m3
4 2008-10-15 06:00:00  2008   10   15     6   36.0            36.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2008-10-15 02:00:00  2008   10   15     2   19.0            19.0   µg/m3
1 2008-10-15 03:00:00  2008   10   15     3   13.0            13.0   µg/m3
2 2008-10-15 04:00:00  2008   10   15     4   12.0            12.0   µg/m3
3 2008-10-15 05:00:00  2008   10   15     5   18.0            18.0   µg/m3
4 2008-10-15 06:00:00  2008   10   15     6   36.0            36.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
004
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/NO2/BA0007ND004.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
         VALOR_ORIGINAL UNIDADE            DATETIME
5236154      475.470824   ug/m3 2017-10-26 19:00:00
5231241       64.946855   ug/m3 2017-03-23 08:00:00
5233447       47.895488   ug/m3 2017-06-26 05:00:00
5231720       47.014227   ug/m3 2017-04-12 09:00:00
5234403       46.665822   ug/m3 2017-08-05 08:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1998-01-01 00:00:00  1998    1    1     0    NaN             NaN   ug/m³
1 1998-01-01 01:00:00  1998    1    1     1    NaN             NaN   ug/m³
2 1998-01-01 02:00:00  1998    1    1     2    NaN             NaN   ug/m³
3 1998-01-01 03:00:00  1998    1    1     3    NaN             NaN   ug/m³
4 1998-01-01 04:00:00  1998    1    1     4    NaN             NaN   ug/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1998-01-01 00:00:00  1998    1    1     0    NaN             NaN   ug/m³
1 1998-01-01 01:00:00  1998    1    1     1    NaN             NaN   ug/m³
2 1998-01-01 02:00:00  1998    1    1     2    NaN             NaN   ug/m³
3 1998-01-01 03:00:00  1998    1    1     3    NaN             NaN   ug/m³
4 1998-01-01 04:00:00  1998    1    1     4    NaN             NaN   ug/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
004
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/NO2/RJ0019RA004.csv
iema
          VALOR_ORIGINAL UNIDADE            DATETIME
26808044           113.4     ppb 2015-09-18 18:30:00
26808035           109.3     ppb 2015-09-18 09:30:00
26808046           108.0     ppb 2015-09-18 20:30:00
26808045           104.7     ppb 2015-09-18 19:30:00
26808047            99.1     ppb 2015-09-18 21:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2023-06-29 15:00:00  2023    6   29    15    NaN             NaN   µg/m³
1 2023-06-29 16:00:00  2023    6   29    16    NaN             NaN   µg/m³
2 2023-06-29 17:00:00  2023    6   29    17    NaN             NaN   µg/m³
3 2023-06-29 18:00:00  2023    6   29    18    NaN             NaN   µg/m³
4 2023-06-29 19:00:00  2023    6   29    19    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0         False     False
1         False     False
2         False     False
3         False     False
4         False     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2023-06-29 15:00:00  2023    6   29    15    NaN             NaN   µg/m³
1 2023-06-29 16:00:00  2023    6   29    16    NaN             NaN   µg/m³
2 2023-06-29 17:00:00  2023    6   29    17    NaN             NaN   µg/m³
3 2023-06-29 18:00:00  2023    6   29    18    NaN             NaN   µg/m³
4 2023-06-29 19:00:00  2023    6   29    19    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
004

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/NO2/MG0058RA004.csv
iema
          VALOR_ORIGINAL UNIDADE            DATETIME
38174393           126.3   µg/m3 2021-09-15 18:30:00
38174236            96.3   µg/m3 2021-09-15 17:30:00
38058397            82.2   µg/m3 2021-08-17 17:30:00
38154934            72.8   µg/m3 2021-09-10 20:30:00
38030438            68.2   µg/m3 2021-08-10 21:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2021-01-01 01:00:00  2021    1    1     1   15.3            15.3   µg/m3
1 2021-01-01 02:00:00  2021    1    1     2   17.8            17.8   µg/m3
2 2021-01-01 03:00:00  2021    1    1     3   13.1            13.1   µg/m3
3 2021-01-01 04:00:00  2021    1    1     4   11.8            11.8   µg/m3
4 2021-01-01 05:00:00  2021    1    1     5    9.8             9.8   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2021-01-01 01:00:00  2021    1    1     1   15.3            15.3   µg/m3
1 2021-01-01 02:00:00  2021    1    1     2   17.8            17.8   µg/m3
2 2021-01-01 03:00:00  2021    1    1     3   13.1            13.1   µg/m3
3 2021-01-01 04:00:00  2021    1    1     4   11.8            11.8   µg/m3
4 2021-01-01 05:00:00  2021    1    1     5    9.8             9.8   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

004
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/NO2/CE0001ND004.csv
iema
         VALOR_ORIGINAL UNIDADE            DATETIME
4786232           190.0   ug/m3 2016-08-29 19:00:00
4786233           182.0   ug/m3 2016-08-29 20:00:00
4786222           176.0   ug/m3 2016-08-29 09:00:00
4786161           171.0   ug/m3 2016-08-26 20:00:00
4787060           169.0   ug/m3 2016-10-16 09:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2016-08-25 14:00:00  2016    8   25    14    NaN             NaN   µg/m³
1 2016-08-25 15:00:00  2016    8   25    15    NaN             NaN   µg/m³
2 2016-08-25 16:00:00  2016    8   25    16    NaN             NaN   µg/m³
3 2016-08-25 17:00:00  2016    8   25    17    NaN             NaN   µg/m³
4 2016-08-25 18:00:00  2016    8   25    18    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2016-08-25 14:00:00  2016    8   25    14   34.0            34.0   ug/m3
1 2016-08-25 15:00:00  2016    8   25    15   32.0            32.0   ug/m3
2 2016-08-25 16:00:00  2016    8   25    16   36.0            36.0   ug/m3
3 2016-08-25 17:00:00  2016    8   25    17   62.0            62.0   ug/m3
4 2016-08-25 18:00:00  2016    8   25    18  113.0           113.0   ug/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

004
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/NO2/SP0256RA004.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
         VALOR_ORIGINAL UNIDADE            DATETIME
8311182           119.0   ug/m3 2019-09-17 21:00:00
8311019           111.0   ug/m3 2019-09-10 19:00:00
8311181           103.0   ug/m3 2019-09-17 20:00:00
8310722           102.0   ug/m3 2019-08-01 19:00:00
8310723           101.0   ug/m3 2019-08-01 20:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2011-01-07 16:00:00  2011    1    7    16    5.0             5.0   µg/m3
1 2011-01-07 17:00:00  2011    1    7    17    3.0             3.0   µg/m3
2 2011-01-07 18:00:00  2011    1    7    18    2.0             2.0   µg/m3
3 2011-01-07 19:00:00  2011    1    7    19    7.0             7.0   µg/m3
4 2011-01-07 20:00:00  2011    1    7    20   24.0            24.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2011-01-07 16:00:00  2011    1    7    16    5.0             5.0   µg/m3
1 2011-01-07 17:00:00  2011    1    7    17    3.0             3.0   µg/m3
2 2011-01-07 18:00:00  2011    1    7    18    2.0             2.0   µg/m3
3 2011-01-07 19:00:00  2011    1    7    19    7.0             7.0   µg/m3
4 2011-01-07 20:00:00  2011    1    7    20   24.0            24.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
004
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/NO2/SP0083RA004.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
18532505           197.0   ug/m3 2017-08-30 21:00:00
18532506           196.0   ug/m3 2017-08-30 22:00:00
9812424            193.0   ug/m3 2018-07-06 11:00:00
12813193           190.0   ug/m3 2020-09-19 10:00:00
18532507           181.0   ug/m3 2017-08-30 23:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1998-01-17 07:00:00  1998    1   17     7   31.0            31.0   µg/m3
1 1998-01-17 08:00:00  1998    1   17     8   32.0            32.0   µg/m3
2 1998-01-17 09:00:00  1998    1   17     9   27.0            27.0   µg/m3
3 1998-01-17 10:00:00  1998    1   17    10   22.0            22.0   µg/m3
4 1998-01-17 11:00:00  1998    1   17    11   24.0            24.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1998-01-17 07:00:00  1998    1   17     7   31.0            31.0   µg/m3
1 1998-01-17 08:00:00  1998    1   17     8   32.0            32.0   µg/m3
2 1998-01-17 09:00:00  1998    1   17     9   27.0            27.0   µg/m3
3 1998-01-17 10:00:00  1998    1   17    10   22.0            22.0   µg/m3
4 1998-01-17 11:00:00  1998    1   17    11   24.0            24.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
004
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/NO2/SP0273RA004.csv
iema
          VALOR_ORIGINAL UNIDADE            DATETIME
8046169            149.0   ug/m3 2019-09-19 19:00:00
10537459           145.0   ug/m3 2020-08-04 19:00:00
11313253           142.0   ug/m3 2021-08-25 21:00:00
10538346           139.0   ug/m3 2020-09-10 20:00:00
10538345           138.0   ug/m3 2020-09-10 19:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2018-02-14 02:00:00  2018    2   14     2   18.0            18.0   µg/m3
1 2018-02-14 03:00:00  2018    2   14     3   13.0            13.0   µg/m3
2 2018-02-14 04:00:00  2018    2   14     4   13.0            13.0   µg/m3
3 2018-02-14 05:00:00  2018    2   14     5   10.0            10.0   µg/m3
4 2018-02-14 06:00:00  2018    2   14     6   17.0            17.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2018-02-14 02:00:00  2018    2   14     2   18.0            18.0   ug/m3
1 2018-02-14 03:00:00  2018    2   14     3   13.0            13.0   ug/m3
2 2018-02-14 04:00:00  2018    2   14     4   13.0            13.0   ug/m3
3 2018-02-14 05:00:00  2018    2   14     5   10.0            10.0   ug/m3
4 2018-02-14 06:00:00  2018    2   14     6   17.0            17.0   ug/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

004
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/NO2/BA0011ND004.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
         VALOR_ORIGINAL UNIDADE            DATETIME
5370258      475.470824   ug/m3 2017-10-30 19:00:00
5370256      475.470824   ug/m3 2017-10-30 17:00:00
5370271      475.470824   ug/m3 2017-10-31 08:00:00
5370257      475.470824   ug/m3 2017-10-30 18:00:00
5370262      475.470824   ug/m3 2017-10-30 23:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1998-01-01 00:00:00  1998    1    1     0    NaN             NaN   ug/m³
1 1998-01-01 01:00:00  1998    1    1     1    NaN             NaN   ug/m³
2 1998-01-01 02:00:00  1998    1    1     2    NaN             NaN   ug/m³
3 1998-01-01 03:00:00  1998    1    1     3    NaN             NaN   ug/m³
4 1998-01-01 04:00:00  1998    1    1     4    NaN             NaN   ug/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1998-01-01 00:00:00  1998    1    1     0    NaN             NaN   ug/m³
1 1998-01-01 01:00:00  1998    1    1     1    NaN             NaN   ug/m³
2 1998-01-01 02:00:00  1998    1    1     2    NaN             NaN   ug/m³
3 1998-01-01 03:00:00  1998    1    1     3    NaN             NaN   ug/m³
4 1998-01-01 04:00:00  1998    1    1     4    NaN             NaN   ug/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
004
004
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/NO2/RJ0070RA004.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
24877798        152.0575   ug/m3 2017-07-13 18:00:00
24877164        147.0413   ug/m3 2017-06-09 16:00:00
24877183        141.1403   ug/m3 2017-06-10 16:00:00
24877231        139.7415   ug/m3 2017-06-12 22:00:00
24877226        139.3830   ug/m3 2017-06-12 16:00:00
mma
             DATETIME     ANO   MES   DIA  HORA  VALOR  VALOR_ORIGINAL  \
0 2000-12-17 12:00:00  2000.0  12.0  17.0  12.0    NaN             NaN
1 2000-12-17 13:00:00  2000.0  12.0  17.0  13.0    NaN             NaN
2 2000-12-17 14:00:00  2000.0  12.0  17.0  14.0    NaN             NaN
3 2000-12-17 15:00:00  2000.0  12.0  17.0  15.0    NaN             NaN
4 2000-12-17 16:00:00  2000.0  12.0  17.0  16.0  22.28           22.28

  UNIDADE  QAQC_INTERNO  QAQC_MMA
0   µg/m³         False     False
1   µg/m³         False     False
2   µg/m³         False     False
3   µg/m³         False     False
4   µg/m³          True      True
final
             DATETIME     ANO   MES   DIA  HORA  VALOR  VALOR_ORIGINAL  \
0 2000-12-17 12:00:00  2000.0  12.0  17.0  12.0    NaN             NaN
1 2000-12-17 13:00:00  2000.0  12.0  17.0  13.0    NaN             NaN
2 2000-12-17 14:00:00  2000.0  12.0  17.0  14.0    NaN             NaN
3 2000-12-17 15:00:00  2000.0  12.0  17.0  15.0    NaN             NaN
4 2000-12-17 16:00:00  2000.0  12.0  17.0  16.0  22.28           22.28

  UNIDADE  QAQC_INTERNO  QAQC_MMA
0   µg/m³          True     False
1   µg/m³          True     False
2   µg/m³          True     False
3   µg/m³          True     False
4   µg/m³          True      True
004
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/NO2/MG0017RA004.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
31993132         169.223   µg/m3 2020-04-02 01:30:00
38174427          97.110   µg/m3 2021-09-15 18:30:00
38238006          95.270   µg/m3 2021-10-01 20:30:00
38038101          91.410   µg/m3 2021-08-12 18:30:00
33532362          90.380   µg/m3 2015-09-30 18:30:00
mma
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2014-01-01 01:00:00  2014.0  1.0  1.0   1.0    NaN             NaN   µg/m3
1 2014-01-01 02:00:00  2014.0  1.0  1.0   2.0    NaN             NaN   µg/m3
2 2014-01-01 03:00:00  2014.0  1.0  1.0   3.0    NaN             NaN   µg/m3
3 2014-01-01 04:00:00  2014.0  1.0  1.0   4.0    NaN             NaN   µg/m3
4 2014-01-01 05:00:00  2014.0  1.0  1.0   5.0    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2014-01-01 01:00:00  2014.0  1.0  1.0   1.0    NaN             NaN   µg/m3
1 2014-01-01 02:00:00  2014.0  1.0  1.0   2.0    NaN             NaN   µg/m3
2 2014-01-01 03:00:00  2014.0  1.0  1.0   3.0    NaN             NaN   µg/m3
3 2014-01-01 04:00:00  2014.0  1.0  1.0   4.0    NaN             NaN   µg/m3
4 2014-01-01 05:00:00  2014.0  1.0  1.0   5.0    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
004
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/NO2/MG0010RA004.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
40444154          113.44   µg/m3 2016-08-18 18:30:00
40444187          111.04   µg/m3 2016-08-18 17:30:00
34590665           91.36   µg/m3 2019-08-19 17:30:00
38037796           89.64   µg/m3 2021-08-12 17:30:00
40444840           86.85   µg/m3 2016-07-11 17:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2014-01-01 01:00:00  2014    1    1     1  16.60           16.60   µg/m3
1 2014-01-01 02:00:00  2014    1    1     2  18.24           18.24   µg/m3
2 2014-01-01 03:00:00  2014    1    1     3  17.20           17.20   µg/m3
3 2014-01-01 04:00:00  2014    1    1     4  14.04           14.04   µg/m3
4 2014-01-01 05:00:00  2014    1    1     5  13.04           13.04   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2014-01-01 01:00:00  2014    1    1     1  16.60           16.60   µg/m3
1 2014-01-01 02:00:00  2014    1    1     2  18.24           18.24   µg/m3
2 2014-01-01 03:00:00  2014    1    1     3  17.20           17.20   µg/m3
3 2014-01-01 04:00:00  2014    1    1     4  14.04           14.04   µg/m3
4 2014-01-01 05:00:00  2014    1    1     5  13.04           13.04   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
004
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/NO2/RJ0038RA004.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
31332260      625.698394   µg/m3 2020-04-28 14:00:00
25212783      357.054000   ug/m3 2017-04-04 11:00:00
19526865      209.884284   µg/m3 2019-01-02 07:00:00
25216216      131.996100   ug/m3 2017-09-06 14:00:00
25217088      112.792200   ug/m3 2017-10-19 16:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2009-01-02 01:00:00  2009    1    2     1   8.46            8.46   µg/m³
1 2009-01-02 02:00:00  2009    1    2     2   7.90            7.90   µg/m³
2 2009-01-02 03:00:00  2009    1    2     3   7.90            7.90   µg/m³
3 2009-01-02 04:00:00  2009    1    2     4   8.46            8.46   µg/m³
4 2009-01-02 05:00:00  2009    1    2     5   7.71            7.71   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2009-01-02 01:00:00  2009    1    2     1   8.46            8.46   µg/m³
1 2009-01-02 02:00:00  2009    1    2     2   7.90            7.90   µg/m³
2 2009-01-02 03:00:00  2009    1    2     3   7.90            7.90   µg/m³
3 2009-01-02 04:00:00  2009    1    2     4   8.46            8.46   µg/m³
4 2009-01-02 05:00:00  2009    1    2     5   7.71            7.71   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
004
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/NO2/RJ0051RA004.csv
iema
          VALOR_ORIGINAL UNIDADE            DATETIME
21253599           46.39   ug/m3 2021-08-26 18:00:00
21253598           39.77   ug/m3 2021-08-26 17:00:00
21253600           38.03   ug/m3 2021-08-26 19:00:00
25634191           36.74   µg/m³ 2021-04-21 18:00:00
25634192           33.10   µg/m³ 2021-12-08 13:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2020-02-12 12:00:00  2020    2   12    12    NaN             NaN   µg/m³
1 2020-02-12 13:00:00  2020    2   12    13    NaN             NaN   µg/m³
2 2020-02-12 14:00:00  2020    2   12    14    NaN             NaN   µg/m³
3 2020-02-12 15:00:00  2020    2   12    15    NaN             NaN   µg/m³
4 2020-02-12 16:00:00  2020    2   12    16    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0         False     False
1         False     False
2         False     False
3         False     False
4         False     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2020-02-12 12:00:00  2020    2   12    12    NaN             NaN   µg/m³
1 2020-02-12 13:00:00  2020    2   12    13    NaN             NaN   µg/m³
2 2020-02-12 14:00:00  2020    2   12    14    NaN             NaN   µg/m³
3 2020-02-12 15:00:00  2020    2   12    15    NaN             NaN   µg/m³
4 2020-02-12 16:00:00  2020    2   12    16    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

004
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/NO2/SP0269RA004.csv
iema
          VALOR_ORIGINAL UNIDADE            DATETIME
14077909           164.0   ug/m3 2016-06-16 11:00:00
18945308           162.0   ug/m3 2015-10-20 22:00:00
18944730           153.0   ug/m3 2015-09-25 11:00:00
18943712           143.0   ug/m3 2015-08-04 10:00:00
18943781           142.0   ug/m3 2015-08-07 10:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2012-09-01 02:00:00  2012    9    1     2   53.0            53.0   µg/m3
1 2012-09-01 03:00:00  2012    9    1     3   57.0            57.0   µg/m3
2 2012-09-01 04:00:00  2012    9    1     4   58.0            58.0   µg/m3
3 2012-09-01 05:00:00  2012    9    1     5   61.0            61.0   µg/m3
4 2012-09-01 06:00:00  2012    9    1     6   66.0            66.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2012-09-01 02:00:00  2012    9    1     2   53.0            53.0   µg/m3
1 2012-09-01 03:00:00  2012    9    1     3   57.0            57.0   µg/m3
2 2012-09-01 04:00:00  2012    9    1     4   58.0            58.0   µg/m3
3 2012-09-01 05:00:00  2012    9    1     5   61.0            61.0   µg/m3
4 2012-09-01 06:00:00  2012    9    1     6   66.0            66.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

004
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/NO2/RJ0057RA004.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
27494138        239.2590     ppb 2015-06-08 16:30:00
27494160        157.9300     ppb 2015-06-09 14:30:00
25428066        152.6015   ug/m3 2017-11-30 16:00:00
27494137        119.8190     ppb 2015-06-08 15:30:00
29448920        103.0300     ppb 2016-02-10 09:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2014-03-01 23:00:00  2014    3    1    23  13.23           13.23   µg/m³
1 2014-03-02 00:00:00  2014    3    2     0    NaN             NaN   µg/m³
2 2014-03-02 01:00:00  2014    3    2     1    NaN             NaN   µg/m³
3 2014-03-02 02:00:00  2014    3    2     2    NaN             NaN   µg/m³
4 2014-03-02 03:00:00  2014    3    2     3    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1         False     False
2         False     False
3         False     False
4         False     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2014-03-01 23:00:00  2014    3    1    23  13.23           13.23   µg/m³
1 2014-03-02 00:00:00  2014    3    2     0    NaN             NaN   µg/m³
2 2014-03-02 01:00:00  2014    3    2     1    NaN             NaN   µg/m³
3 2014-03-02 02:00:00  2014    3    2     2    NaN             NaN   µg/m³
4 2014-03-02 03:00:00  2014    3    2     3    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True     False
2          True     False
3          True     False
4          True     False
004
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/NO2/RJ0078RA004.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
24737534      191.622940   ug/m3 2017-01-26 14:00:00
24737535      185.064722   ug/m3 2017-01-26 15:00:00
24737889      100.422717   ug/m3 2017-02-10 14:00:00
24737773       93.044722   ug/m3 2017-02-05 16:00:00
24737536       88.945835   ug/m3 2017-01-26 16:00:00
mma
             DATETIME     ANO   MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1998-10-01 21:00:00  1998.0  10.0  1.0  21.0  12.74           12.74   µg/m³
1 1998-10-01 22:00:00  1998.0  10.0  1.0  22.0    NaN             NaN   µg/m³
2 1998-10-01 23:00:00  1998.0  10.0  1.0  23.0   5.22            5.22   µg/m³
3 1998-10-02 00:00:00  1998.0  10.0  2.0   0.0    NaN             NaN   µg/m³
4 1998-10-02 01:00:00  1998.0  10.0  2.0   1.0    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1         False     False
2          True      True
3         False     False
4         False     False
final
             DATETIME     ANO   MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1998-10-01 21:00:00  1998.0  10.0  1.0  21.0  12.74           12.74   µg/m³
1 1998-10-01 22:00:00  1998.0  10.0  1.0  22.0    NaN             NaN   µg/m³
2 1998-10-01 23:00:00  1998.0  10.0  1.0  23.0   5.22            5.22   µg/m³
3 1998-10-02 00:00:00  1998.0  10.0  2.0   0.0    NaN             NaN   µg/m³
4 1998-10-02 01:00:00  1998.0  10.0  2.0   1.0    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True     False
2          True      True
3          True     False
4          True     False
004
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/NO2/RJ0033RA004.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
28644907      255.169411   µg/m3 2019-09-12 18:00:00
28645093      237.845355   µg/m3 2019-09-12 19:00:00
25187186      213.083500   ug/m3 2017-06-07 18:00:00
25187187      207.156000   ug/m3 2017-06-07 19:00:00
25187185      204.679600   ug/m3 2017-06-07 17:00:00
mma
             DATETIME     ANO   MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2004-12-07 00:00:00  2004.0  12.0  7.0   0.0    NaN             NaN   µg/m³
1 2004-12-07 01:00:00  2004.0  12.0  7.0   1.0    NaN             NaN   µg/m³
2 2004-12-07 02:00:00  2004.0  12.0  7.0   2.0    NaN             NaN   µg/m³
3 2004-12-07 03:00:00  2004.0  12.0  7.0   3.0    NaN             NaN   µg/m³
4 2004-12-07 04:00:00  2004.0  12.0  7.0   4.0    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0         False     False
1         False     False
2         False     False
3         False     False
4         False     False
final
             DATETIME     ANO   MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2004-12-07 00:00:00  2004.0  12.0  7.0   0.0    NaN             NaN   µg/m³
1 2004-12-07 01:00:00  2004.0  12.0  7.0   1.0    NaN             NaN   µg/m³
2 2004-12-07 02:00:00  2004.0  12.0  7.0   2.0    NaN             NaN   µg/m³
3 2004-12-07 03:00:00  2004.0  12.0  7.0   3.0    NaN             NaN   µg/m³
4 2004-12-07 04:00:00  2004.0  12.0  7.0   4.0    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
004
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/NO2/BA0001ND004.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
         VALOR_ORIGINAL UNIDADE            DATETIME
5195805       79.641363   ug/m3 2017-01-27 19:00:00
5195804       73.964405   ug/m3 2017-01-27 18:00:00
5196142       70.685296   ug/m3 2017-02-10 20:00:00
5196234       70.500846   ug/m3 2017-02-14 18:00:00
5532198       69.400000     ppb 2015-06-26 16:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1998-01-01 00:00:00  1998    1    1     0    NaN             NaN   ug/m³
1 1998-01-01 01:00:00  1998    1    1     1    NaN             NaN   ug/m³
2 1998-01-01 02:00:00  1998    1    1     2    NaN             NaN   ug/m³
3 1998-01-01 03:00:00  1998    1    1     3    NaN             NaN   ug/m³
4 1998-01-01 04:00:00  1998    1    1     4    NaN             NaN   ug/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1998-01-01 00:00:00  1998    1    1     0    NaN             NaN   ug/m³
1 1998-01-01 01:00:00  1998    1    1     1    NaN             NaN   ug/m³
2 1998-01-01 02:00:00  1998    1    1     2    NaN             NaN   ug/m³
3 1998-01-01 03:00:00  1998    1    1     3    NaN             NaN   ug/m³
4 1998-01-01 04:00:00  1998    1    1     4    NaN             NaN   ug/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
004
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/NO2/SP0103RA004.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
17750307           212.0   ug/m3 2015-10-20 21:00:00
17751010           208.0   ug/m3 2015-12-19 21:00:00
17750306           207.0   ug/m3 2015-10-20 20:00:00
17751009           205.0   ug/m3 2015-12-19 20:00:00
17750308           194.0   ug/m3 2015-10-20 22:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2004-08-31 16:00:00  2004    8   31    16   54.0            54.0   µg/m3
1 2004-08-31 17:00:00  2004    8   31    17   61.0            61.0   µg/m3
2 2004-08-31 18:00:00  2004    8   31    18   63.0            63.0   µg/m3
3 2004-08-31 19:00:00  2004    8   31    19   58.0            58.0   µg/m3
4 2004-08-31 20:00:00  2004    8   31    20   45.0            45.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2004-08-31 16:00:00  2004    8   31    16   54.0            54.0   µg/m3
1 2004-08-31 17:00:00  2004    8   31    17   61.0            61.0   µg/m3
2 2004-08-31 18:00:00  2004    8   31    18   63.0            63.0   µg/m3
3 2004-08-31 19:00:00  2004    8   31    19   58.0            58.0   µg/m3
4 2004-08-31 20:00:00  2004    8   31    20   45.0            45.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
004
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/NO2/MG0013RA004.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
33482896           75.11   µg/m3 2015-09-23 20:30:00
40501480           71.18   µg/m3 2016-06-01 10:30:00
40501521           70.95   µg/m3 2016-08-16 18:30:00
40501523           70.92   µg/m3 2016-09-15 19:30:00
33483377           70.76   µg/m3 2015-09-10 18:30:00
mma
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2014-01-01 01:00:00  2014.0  1.0  1.0   1.0  21.09           21.09   µg/m3
1 2014-01-01 02:00:00  2014.0  1.0  1.0   2.0  20.32           20.32   µg/m3
2 2014-01-01 03:00:00  2014.0  1.0  1.0   3.0  19.74           19.74   µg/m3
3 2014-01-01 04:00:00  2014.0  1.0  1.0   4.0  16.78           16.78   µg/m3
4 2014-01-01 05:00:00  2014.0  1.0  1.0   5.0  13.19           13.19   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2014-01-01 01:00:00  2014.0  1.0  1.0   1.0  21.09           21.09   µg/m3
1 2014-01-01 02:00:00  2014.0  1.0  1.0   2.0  20.32           20.32   µg/m3
2 2014-01-01 03:00:00  2014.0  1.0  1.0   3.0  19.74           19.74   µg/m3
3 2014-01-01 04:00:00  2014.0  1.0  1.0   4.0  16.78           16.78   µg/m3
4 2014-01-01 05:00:00  2014.0  1.0  1.0   5.0  13.19           13.19   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
004
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/NO2/MG0004RA004.csv

/tmp/ipykernel_273420/1352582357.py:97: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  df_mma = pd.read_csv(arquivo, encoding = 'UTF-8')
/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
33080952         325.660   µg/m3 2015-01-08 16:30:00
34594761         309.500   µg/m3 2019-08-20 18:30:00
34591252         303.430   µg/m3 2019-08-19 20:30:00
31675499         289.907   µg/m3 2020-01-02 06:30:00
34594600         286.400   µg/m3 2019-08-20 17:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR VALOR_ORIGINAL UNIDADE  \
0 2009-01-01 01:00:00  2009    1    1     1    7.8            7.8     ppb
1 2009-01-01 02:00:00  2009    1    1     2   17.8           17.8     ppb
2 2009-01-01 03:00:00  2009    1    1     3   18.2           18.2     ppb
3 2009-01-01 04:00:00  2009    1    1     4   12.2           12.2     ppb
4 2009-01-01 05:00:00  2009    1    1     5    9.8            9.8     ppb

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR VALOR_ORIGINAL UNIDADE  \
0 2009-01-01 01:00:00  2009    1    1     1    7.8            7.8     ppb
1 2009-01-01 02:00:00  2009    1    1     2   17.8           17.8     ppb
2 2009-01-01 03:00:00  2009    1    1     3   18.2           18.2     ppb
3 2009-01-01 04:00:00  2009    1    1     4   12.2           12.2     ppb
4 2009-01-01 05:00:00  2009    1    1     5    9.8            9.8     ppb

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
004
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/NO2/SP0110RA004.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
19462726           158.0   ug/m3 2015-09-23 20:00:00
18648057           153.0   ug/m3 2017-08-30 19:00:00
14570861           143.0   ug/m3 2016-08-19 19:00:00
13758035           140.0   ug/m3 2019-07-12 19:00:00
19462725           139.0   ug/m3 2015-09-23 19:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2008-09-25 02:00:00  2008    9   25     2    5.0             5.0   µg/m3
1 2008-09-25 03:00:00  2008    9   25     3   11.0            11.0   µg/m3
2 2008-09-25 04:00:00  2008    9   25     4    8.0             8.0   µg/m3
3 2008-09-25 05:00:00  2008    9   25     5    7.0             7.0   µg/m3
4 2008-09-25 06:00:00  2008    9   25     6    8.0             8.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2008-09-25 02:00:00  2008    9   25     2    5.0             5.0   µg/m3
1 2008-09-25 03:00:00  2008    9   25     3   11.0            11.0   µg/m3
2 2008-09-25 04:00:00  2008    9   25     4    8.0             8.0   µg/m3
3 2008-09-25 05:00:00  2008    9   25     5    7.0             7.0   µg/m3
4 2008-09-25 06:00:00  2008    9   25     6    8.0             8.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
004
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/NO2/RJ0031RA004.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
28461951      197.904158   µg/m3 2019-08-02 10:00:00
28462144      194.386762   µg/m3 2019-08-02 11:00:00
25072007      166.913500   ug/m3 2017-08-03 08:00:00
28645465      156.359774   µg/m3 2019-09-12 21:00:00
28645277      153.800526   µg/m3 2019-09-12 20:00:00
mma
             DATETIME     ANO  MES  DIA  HORA   VALOR  VALOR_ORIGINAL UNIDADE  \
0 2004-03-04 12:00:00  2004.0  3.0  4.0  12.0  488.86          488.86   µg/m³
1 2004-03-04 13:00:00  2004.0  3.0  4.0  13.0  488.86          488.86   µg/m³
2 2004-03-04 14:00:00  2004.0  3.0  4.0  14.0  488.86          488.86   µg/m³
3 2004-03-04 15:00:00  2004.0  3.0  4.0  15.0  488.86          488.86   µg/m³
4 2004-03-04 16:00:00  2004.0  3.0  4.0  16.0  451.26          451.26   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME     ANO  MES  DIA  HORA   VALOR  VALOR_ORIGINAL UNIDADE  \
0 2004-03-04 12:00:00  2004.0  3.0  4.0  12.0  488.86          488.86   µg/m³
1 2004-03-04 13:00:00  2004.0  3.0  4.0  13.0  488.86          488.86   µg/m³
2 2004-03-04 14:00:00  2004.0  3.0  4.0  14.0  488.86          488.86   µg/m³
3 2004-03-04 15:00:00  2004.0  3.0  4.0  15.0  488.86          488.86   µg/m³
4 2004-03-04 16:00:00  2004.0  3.0  4.0  16.0  451.26          451.26   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
004
004
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/NO2/RJ0064RA004.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
25387459        61.47988   ug/m3 2017-06-04 17:00:00
25387528        56.77129   ug/m3 2017-06-07 19:00:00
25387460        56.35684   ug/m3 2017-06-04 18:00:00
25388775        50.51536   ug/m3 2017-08-09 07:00:00
25389707        50.05025   ug/m3 2017-09-22 22:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2016-06-29 14:00:00  2016    6   29    14    NaN             NaN   µg/m³
1 2016-06-29 15:00:00  2016    6   29    15  20.47           20.47   µg/m³
2 2016-06-29 16:00:00  2016    6   29    16  17.80           17.80   µg/m³
3 2016-06-29 17:00:00  2016    6   29    17  23.45           23.45   µg/m³
4 2016-06-29 18:00:00  2016    6   29    18  23.04           23.04   µg/m³

   QAQC_INTERNO  QAQC_MMA
0         False     False
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2016-06-29 14:00:00  2016    6   29    14    NaN             NaN   µg/m³
1 2016-06-29 15:00:00  2016    6   29    15  20.47           20.47   µg/m³
2 2016-06-29 16:00:00  2016    6   29    16  17.80           17.80   µg/m³
3 2016-06-29 17:00:00  2016    6   29    17  23.45           23.45   µg/m³
4 2016-06-29 18:00:00  2016    6   29    18  23.04           23.04   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True      True
2          True      True
3          True      True
4          True      True
004
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/NO2/SP0065RA004.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
14693936           209.0   ug/m3 2018-07-03 09:00:00
17146372           208.0   ug/m3 2015-09-01 10:00:00
11577961           189.0   ug/m3 2016-09-01 08:00:00
14693937           188.0   ug/m3 2018-07-03 10:00:00
17146371           185.0   ug/m3 2015-09-01 09:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1998-01-01 01:00:00  1998    1    1     1    6.0             6.0   µg/m3
1 1998-01-01 02:00:00  1998    1    1     2    4.0             4.0   µg/m3
2 1998-01-01 03:00:00  1998    1    1     3    5.0             5.0   µg/m3
3 1998-01-01 04:00:00  1998    1    1     4    4.0             4.0   µg/m3
4 1998-01-01 05:00:00  1998    1    1     5    3.0             3.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1998-01-01 01:00:00  1998    1    1     1    6.0             6.0   µg/m3
1 1998-01-01 02:00:00  1998    1    1     2    4.0             4.0   µg/m3
2 1998-01-01 03:00:00  1998    1    1     3    5.0             5.0   µg/m3
3 1998-01-01 04:00:00  1998    1    1     4    4.0             4.0   µg/m3
4 1998-01-01 05:00:00  1998    1    1     5    3.0             3.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
004
004
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/NO2/SP0114RA004.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
10321692           179.0   ug/m3 2020-10-02 21:00:00
10321668           154.0   ug/m3 2020-10-01 20:00:00
16565100           150.0   ug/m3 2022-06-24 21:00:00
16565099           145.0   ug/m3 2022-06-24 20:00:00
6972563            144.0   ug/m3 2017-08-29 21:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2008-05-15 02:00:00  2008    5   15     2   12.0            12.0   µg/m3
1 2008-05-15 03:00:00  2008    5   15     3    NaN             NaN     NaN
2 2008-05-15 04:00:00  2008    5   15     4    8.0             8.0   µg/m3
3 2008-05-15 05:00:00  2008    5   15     5    7.0             7.0   µg/m3
4 2008-05-15 06:00:00  2008    5   15     6    8.0             8.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True     False
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2008-05-15 02:00:00  2008    5   15     2   12.0            12.0   µg/m3
1 2008-05-15 03:00:00  2008    5   15     3    NaN             NaN     NaN
2 2008-05-15 04:00:00  2008    5   15     4    8.0             8.0   µg/m3
3 2008-05-15 05:00:00  2008    5   15     5    7.0             7.0   µg/m3
4 2008-05-15 06:00:00  2008    5   15     6    8.0             8.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True     False
2          True      True
3          True      True
4          True      True
004
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/NO2/RJ0030RA004.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
25023899    2.550000e+12   ug/m3 2017-04-30 03:00:00
25023858    2.510000e+12   ug/m3 2017-04-28 10:00:00
25023486    2.430000e+12   ug/m3 2017-04-12 17:00:00
24101562    3.139232e+04   µg/m3 2020-11-23 17:00:00
24101769    2.163770e+04   µg/m3 2020-11-23 18:00:00
mma
             DATETIME     ANO   MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2001-11-03 00:00:00  2001.0  11.0  3.0   0.0    NaN             0.0   µg/m³
1 2001-11-03 01:00:00  2001.0  11.0  3.0   1.0    NaN             0.0   µg/m³
2 2001-11-03 02:00:00  2001.0  11.0  3.0   2.0    NaN             0.0   µg/m³
3 2001-11-03 03:00:00  2001.0  11.0  3.0   3.0    NaN             0.0   µg/m³
4 2001-11-03 04:00:00  2001.0  11.0  3.0   4.0    NaN             0.0   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME     ANO   MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2001-11-03 00:00:00  2001.0  11.0  3.0   0.0    NaN             0.0   µg/m³
1 2001-11-03 01:00:00  2001.0  11.0  3.0   1.0    NaN             0.0   µg/m³
2 2001-11-03 02:00:00  2001.0  11.0  3.0   2.0    NaN             0.0   µg/m³
3 2001-11-03 03:00:00  2001.0  11.0  3.0   3.0    NaN             0.0   µg/m³
4 2001-11-03 04:00:00  2001.0  11.0  3.0   4.0    NaN             0.0   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
004
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/NO2/RJ0020RA004.csv
iema
          VALOR_ORIGINAL UNIDADE            DATETIME
28645294      162.399305   µg/m3 2019-09-12 20:00:00
28645482      146.027648   µg/m3 2019-09-12 21:00:00
23844485      131.349600   µg/m3 2020-10-02 21:00:00
28461967      128.715092   µg/m3 2019-08-02 10:00:00
23844910      128.150600   µg/m3 2020-10-02 23:00:00
mma
             DATETIME     ANO  MES   DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2013-07-11 16:00:00  2013.0  7.0  11.0  16.0   9.39            9.39   µg/m³
1 2013-07-11 17:00:00  2013.0  7.0  11.0  17.0    NaN             NaN   µg/m³
2 2013-07-11 18:00:00  2013.0  7.0  11.0  18.0    NaN             NaN   µg/m³
3 2013-07-11 19:00:00  2013.0  7.0  11.0  19.0    NaN             NaN   µg/m³
4 2013-07-11 20:00:00  2013.0  7.0  11.0  20.0   8.16            8.16   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1         False     False
2         False     False
3         False     False
4          True      True
final
             DATETIME     ANO  MES   DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2013-07-11 16:00:00  2013.0  7.0  11.0  16.0   9.39            9.39   µg/m³
1 2013-07-11 17:00:00  2013.0  7.0  11.0  17.0    NaN             NaN   µg/m³
2 2013-07-11 18:00:00  2013.0  7.0  11.0  18.0    NaN             NaN   µg/m³
3 2013-07-11 19:00:00  2013.0  7.0  11.0  19.0    NaN             NaN   µg/m³
4 2013-07-11 20:00:00  2013.0  7.0  11.0  20.0   8.16            8.16   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True     False
2          True     False
3          True     False
4          True      True

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

004
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/NO2/RJ0029RA004.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
20214527      314.900344   µg/m3 2019-06-19 19:00:00
19528554      310.591023   µg/m3 2019-01-02 17:00:00
20214332      305.246712   µg/m3 2019-06-19 18:00:00
20214722      280.331685   µg/m3 2019-06-19 20:00:00
20093603      270.847415   µg/m3 2019-05-22 19:00:00
mma
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2011-05-01 00:00:00  2011.0  5.0  1.0   0.0  24.44           24.44   µg/m³
1 2011-05-01 01:00:00  2011.0  5.0  1.0   1.0  18.80           18.80   µg/m³
2 2011-05-01 02:00:00  2011.0  5.0  1.0   2.0  18.80           18.80   µg/m³
3 2011-05-01 03:00:00  2011.0  5.0  1.0   3.0  13.16           13.16   µg/m³
4 2011-05-01 04:00:00  2011.0  5.0  1.0   4.0  11.28           11.28   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2011-05-01 00:00:00  2011.0  5.0  1.0   0.0  24.44           24.44   µg/m³
1 2011-05-01 01:00:00  2011.0  5.0  1.0   1.0  18.80           18.80   µg/m³
2 2011-05-01 02:00:00  2011.0  5.0  1.0   2.0  18.80           18.80   µg/m³
3 2011-05-01 03:00:00  2011.0  5.0  1.0   3.0  13.16           13.16   µg/m³
4 2011-05-01 04:00:00  2011.0  5.0  1.0   4.0  11.28           11.28   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
004
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/NO2/SP0113RA004.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
11810146           115.0   ug/m3 2016-09-17 16:00:00
10297040           112.0   ug/m3 2020-09-18 19:00:00
17363141           109.0   ug/m3 2015-07-30 19:00:00
7826168            107.0   ug/m3 2019-08-23 19:00:00
17363142            98.0   ug/m3 2015-07-30 20:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2008-09-06 02:00:00  2008    9    6     2   59.0            59.0   µg/m3
1 2008-09-06 03:00:00  2008    9    6     3   55.0            55.0   µg/m3
2 2008-09-06 04:00:00  2008    9    6     4   54.0            54.0   µg/m3
3 2008-09-06 05:00:00  2008    9    6     5   48.0            48.0   µg/m3
4 2008-09-06 06:00:00  2008    9    6     6   48.0            48.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2008-09-06 02:00:00  2008    9    6     2   59.0            59.0   µg/m3
1 2008-09-06 03:00:00  2008    9    6     3   55.0            55.0   µg/m3
2 2008-09-06 04:00:00  2008    9    6     4   54.0            54.0   µg/m3
3 2008-09-06 05:00:00  2008    9    6     5   48.0            48.0   µg/m3
4 2008-09-06 06:00:00  2008    9    6     6   48.0            48.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
004
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/NO2/MG0003RA004.csv

/tmp/ipykernel_273420/1352582357.py:97: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  df_mma = pd.read_csv(arquivo, encoding = 'UTF-8')
/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
35124473          236.14   µg/m3 2017-08-23 10:30:00
35124475          160.18   µg/m3 2017-08-09 21:30:00
33001869          156.58   µg/m3 2015-09-28 15:30:00
33001870          155.82   µg/m3 2015-09-28 13:30:00
34862555          152.09   µg/m3 2019-10-29 16:30:00
mma
             DATETIME     ANO  MES  DIA  HORA  VALOR VALOR_ORIGINAL UNIDADE  \
0 2009-01-01 01:00:00  2009.0  1.0  1.0   1.0   15.8           15.8     ppb
1 2009-01-01 02:00:00  2009.0  1.0  1.0   2.0    8.2            8.2     ppb
2 2009-01-01 03:00:00  2009.0  1.0  1.0   3.0    8.2            8.2     ppb
3 2009-01-01 04:00:00  2009.0  1.0  1.0   4.0    7.0              7     ppb
4 2009-01-01 05:00:00  2009.0  1.0  1.0   5.0    5.0              5     ppb

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME     ANO  MES  DIA  HORA  VALOR VALOR_ORIGINAL UNIDADE  \
0 2009-01-01 01:00:00  2009.0  1.0  1.0   1.0   15.8           15.8     ppb
1 2009-01-01 02:00:00  2009.0  1.0  1.0   2.0    8.2            8.2     ppb
2 2009-01-01 03:00:00  2009.0  1.0  1.0   3.0    8.2            8.2     ppb
3 2009-01-01 04:00:00  2009.0  1.0  1.0   4.0    7.0              7     ppb
4 2009-01-01 05:00:00  2009.0  1.0  1.0   5.0    5.0              5     ppb

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
004
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/NO2/SP0281RA004.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
12969724           147.0   ug/m3 2020-09-14 20:00:00
12968793           134.0   ug/m3 2020-08-05 19:00:00
12969288           133.0   ug/m3 2020-08-26 19:00:00
12969725           119.0   ug/m3 2020-09-14 21:00:00
12969633           117.0   ug/m3 2020-09-10 21:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2016-01-01 02:00:00  2016    1    1     2   11.0            11.0   µg/m3
1 2016-01-01 03:00:00  2016    1    1     3   10.0            10.0   µg/m3
2 2016-01-01 04:00:00  2016    1    1     4    7.0             7.0   µg/m3
3 2016-01-01 05:00:00  2016    1    1     5    8.0             8.0   µg/m3
4 2016-01-01 06:00:00  2016    1    1     6    5.0             5.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2016-01-01 02:00:00  2016    1    1     2   11.0            11.0   ug/m3
1 2016-01-01 03:00:00  2016    1    1     3   10.0            10.0   ug/m3
2 2016-01-01 04:00:00  2016    1    1     4    7.0             7.0   ug/m3
3 2016-01-01 05:00:00  2016    1    1     5    8.0             8.0   ug/m3
4 2016-01-01 06:00:00  2016    1    1     6    5.0             5.0   ug/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
004
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/NO2/RJ0039RA004.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
28948598     3636.224026   µg/m3 2019-11-17 14:00:00
28940935     3591.677971   µg/m3 2019-11-15 16:00:00
28940473     3554.982879   µg/m3 2019-11-15 13:00:00
28944513     3423.931897   µg/m3 2019-11-16 14:00:00
28943037     3337.966675   µg/m3 2019-11-16 05:00:00
mma
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2007-02-01 00:00:00  2007.0  2.0  1.0   0.0   8.84            8.84   µg/m³
1 2007-02-01 01:00:00  2007.0  2.0  1.0   1.0   9.89            9.89   µg/m³
2 2007-02-01 02:00:00  2007.0  2.0  1.0   2.0  14.85           14.85   µg/m³
3 2007-02-01 03:00:00  2007.0  2.0  1.0   3.0   8.84            8.84   µg/m³
4 2007-02-01 04:00:00  2007.0  2.0  1.0   4.0   9.89            9.89   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2007-02-01 00:00:00  2007.0  2.0  1.0   0.0   8.84            8.84   µg/m³
1 2007-02-01 01:00:00  2007.0  2.0  1.0   1.0   9.89            9.89   µg/m³
2 2007-02-01 02:00:00  2007.0  2.0  1.0   2.0  14.85           14.85   µg/m³
3 2007-02-01 03:00:00  2007.0  2.0  1.0   3.0   8.84            8.84   µg/m³
4 2007-02-01 04:00:00  2007.0  2.0  1.0   4.0   9.89            9.89   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
004
004
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/NO2/RJ0023RA004.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
31500676      284.904458   µg/m3 2020-06-01 19:00:00
31500887      275.119100   µg/m3 2020-06-01 20:00:00
31501099      264.957382   µg/m3 2020-06-01 21:00:00
25451890      264.279000   ug/m3 2017-02-08 21:00:00
31501312      224.686871   µg/m3 2020-06-01 22:00:00
mma
             DATETIME     ANO  MES   DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2013-04-12 19:00:00  2013.0  4.0  12.0  19.0  62.48           62.48   µg/m³
1 2013-04-12 20:00:00  2013.0  4.0  12.0  20.0  52.45           52.45   µg/m³
2 2013-04-12 21:00:00  2013.0  4.0  12.0  21.0  45.73           45.73   µg/m³
3 2013-04-12 22:00:00  2013.0  4.0  12.0  22.0  41.51           41.51   µg/m³
4 2013-04-12 23:00:00  2013.0  4.0  12.0  23.0  36.72           36.72   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME     ANO  MES   DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2013-04-12 19:00:00  2013.0  4.0  12.0  19.0  62.48           62.48   µg/m³
1 2013-04-12 20:00:00  2013.0  4.0  12.0  20.0  52.45           52.45   µg/m³
2 2013-04-12 21:00:00  2013.0  4.0  12.0  21.0  45.73           45.73   µg/m³
3 2013-04-12 22:00:00  2013.0  4.0  12.0  22.0  41.51           41.51   µg/m³
4 2013-04-12 23:00:00  2013.0  4.0  12.0  23.0  36.72           36.72   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
004
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/NO2/SP0248RA004.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
12482308           109.0   ug/m3 2020-10-05 20:00:00
13272338           104.0   ug/m3 2019-07-11 19:00:00
9412672            104.0   ug/m3 2018-07-04 20:00:00
9413814            102.0   ug/m3 2018-08-23 20:00:00
8538676            100.0   ug/m3 2022-06-15 19:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2009-04-15 02:00:00  2009    4   15     2    1.0             1.0   µg/m3
1 2009-04-15 03:00:00  2009    4   15     3    NaN             0.0   µg/m3
2 2009-04-15 04:00:00  2009    4   15     4    NaN             0.0   µg/m3
3 2009-04-15 05:00:00  2009    4   15     5    NaN             0.0   µg/m3
4 2009-04-15 06:00:00  2009    4   15     6    NaN             0.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2009-04-15 02:00:00  2009    4   15     2    1.0             1.0   µg/m3
1 2009-04-15 03:00:00  2009    4   15     3    NaN             0.0   µg/m3
2 2009-04-15 04:00:00  2009    4   15     4    NaN             0.0   µg/m3
3 2009-04-15 05:00:00  2009    4   15     5    NaN             0.0   µg/m3
4 2009-04-15 06:00:00  2009    4   15     6    NaN             0.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True     False
2          True     False
3          True     False
4          True     False
004
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/NO2/BA0004ND004.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
         VALOR_ORIGINAL UNIDADE            DATETIME
5283803       73.861933   ug/m3 2017-07-15 18:00:00
5283804       72.324851   ug/m3 2017-07-15 19:00:00
5281326       56.708094   ug/m3 2017-03-29 20:00:00
5282423       47.690543   ug/m3 2017-05-17 15:00:00
5280079       46.788788   ug/m3 2017-01-19 19:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1998-01-01 00:00:00  1998    1    1     0    NaN             NaN   ug/m³
1 1998-01-01 01:00:00  1998    1    1     1    NaN             NaN   ug/m³
2 1998-01-01 02:00:00  1998    1    1     2    NaN             NaN   ug/m³
3 1998-01-01 03:00:00  1998    1    1     3    NaN             NaN   ug/m³
4 1998-01-01 04:00:00  1998    1    1     4    NaN             NaN   ug/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1998-01-01 00:00:00  1998    1    1     0    NaN             NaN   ug/m³
1 1998-01-01 01:00:00  1998    1    1     1    NaN             NaN   ug/m³
2 1998-01-01 02:00:00  1998    1    1     2    NaN             NaN   ug/m³
3 1998-01-01 03:00:00  1998    1    1     3    NaN             NaN   ug/m³
4 1998-01-01 04:00:00  1998    1    1     4    NaN             NaN   ug/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
004
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/NO2/MG0053RA004.csv
iema
          VALOR_ORIGINAL UNIDADE            DATETIME
39446813          130.96   µg/m3 2022-09-03 19:30:00
39446962          112.50   µg/m3 2022-09-03 20:30:00
39443174          111.11   µg/m3 2022-09-02 19:30:00
38170583          110.13   µg/m3 2021-09-14 19:30:00
39443325          109.13   µg/m3 2022-09-02 20:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2018-01-01 01:00:00  2018    1    1     1    NaN             NaN   µg/m3
1 2018-01-01 02:00:00  2018    1    1     2    NaN             NaN   µg/m3
2 2018-01-01 03:00:00  2018    1    1     3    NaN             NaN   µg/m3
3 2018-01-01 04:00:00  2018    1    1     4    NaN             NaN   µg/m3
4 2018-01-01 05:00:00  2018    1    1     5    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2018-01-01 01:00:00  2018    1    1     1    NaN             NaN   µg/m3
1 2018-01-01 02:00:00  2018    1    1     2    NaN             NaN   µg/m3
2 2018-01-01 03:00:00  2018    1    1     3    NaN             NaN   µg/m3
3 2018-01-01 04:00:00  2018    1    1     4    NaN             NaN   µg/m3
4 2018-01-01 05:00:00  2018    1    1     5    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

004
004
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/NO2/SP0117RA004.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
         VALOR_ORIGINAL UNIDADE            DATETIME
6824983           153.0   ug/m3 2017-08-30 22:00:00
6824982           145.0   ug/m3 2017-08-30 21:00:00
6824959           140.0   ug/m3 2017-08-29 21:00:00
6824960           139.0   ug/m3 2017-08-29 22:00:00
6824936           136.0   ug/m3 2017-08-28 21:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2000-03-01 18:00:00  2000    3    1    18    NaN             0.0   µg/m3
1 2000-03-01 19:00:00  2000    3    1    19    NaN             0.0   µg/m3
2 2000-03-01 20:00:00  2000    3    1    20    NaN             0.0   µg/m3
3 2000-03-01 21:00:00  2000    3    1    21    NaN             0.0   µg/m3
4 2000-03-01 22:00:00  2000    3    1    22    NaN             0.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2000-03-01 18:00:00  2000    3    1    18    NaN             0.0   µg/m3
1 2000-03-01 19:00:00  2000    3    1    19    NaN             0.0   µg/m3
2 2000-03-01 20:00:00  2000    3    1    20    NaN             0.0   µg/m3
3 2000-03-01 21:00:00  2000    3    1    21    NaN             0.0   µg/m3
4 2000-03-01 22:00:00  2000    3    1    22    NaN             0.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
004
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/NO2/SP0280RA004.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
11553173           115.0   ug/m3 2021-09-14 19:00:00
7533212            112.0   ug/m3 2017-08-09 20:00:00
7533211            111.0   ug/m3 2017-08-09 19:00:00
10792859           110.0   ug/m3 2020-09-10 20:00:00
7533695            108.0   ug/m3 2017-08-30 21:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2015-10-01 02:00:00  2015   10    1     2   18.0            18.0   µg/m3
1 2015-10-01 03:00:00  2015   10    1     3   14.0            14.0   µg/m3
2 2015-10-01 04:00:00  2015   10    1     4   15.0            15.0   µg/m3
3 2015-10-01 05:00:00  2015   10    1     5   15.0            15.0   µg/m3
4 2015-10-01 06:00:00  2015   10    1     6   18.0            18.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2015-10-01 02:00:00  2015   10    1     2   18.0            18.0   ug/m3
1 2015-10-01 03:00:00  2015   10    1     3   14.0            14.0   ug/m3
2 2015-10-01 04:00:00  2015   10    1     4   15.0            15.0   ug/m3
3 2015-10-01 05:00:00  2015   10    1     5   15.0            15.0   ug/m3
4 2015-10-01 06:00:00  2015   10    1     6   18.0            18.0   ug/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
004
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/NO2/RJ0229RA004.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
26818528             7.0     ppb 2015-04-11 12:30:00
mma
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2011-05-01 00:00:00  2011.0  5.0  1.0   0.0  24.44           24.44   µg/m³
1 2011-05-01 01:00:00  2011.0  5.0  1.0   1.0  18.80           18.80   µg/m³
2 2011-05-01 02:00:00  2011.0  5.0  1.0   2.0  18.80           18.80   µg/m³
3 2011-05-01 03:00:00  2011.0  5.0  1.0   3.0  13.16           13.16   µg/m³
4 2011-05-01 04:00:00  2011.0  5.0  1.0   4.0  11.28           11.28   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2011-05-01 00:00:00  2011.0  5.0  1.0   0.0  24.44           24.44   µg/m³
1 2011-05-01 01:00:00  2011.0  5.0  1.0   1.0  18.80           18.80   µg/m³
2 2011-05-01 02:00:00  2011.0  5.0  1.0   2.0  18.80           18.80   µg/m³
3 2011-05-01 03:00:00  2011.0  5.0  1.0   3.0  13.16           13.16   µg/m³
4 2011-05-01 04:00:00  2011.0  5.0  1.0   4.0  11.28           11.28   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
004
004
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/NO2/SP0108RA004.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
15570313           133.0   ug/m3 2021-08-19 20:00:00
18867021           126.0   ug/m3 2015-05-20 19:00:00
8428720            120.0   ug/m3 2022-07-26 20:00:00
12369593           120.0   ug/m3 2020-09-12 20:00:00
9266995            119.0   ug/m3 2018-08-31 20:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2008-05-09 02:00:00  2008    5    9     2   47.0            47.0   µg/m3
1 2008-05-09 03:00:00  2008    5    9     3    NaN             NaN     NaN
2 2008-05-09 04:00:00  2008    5    9     4   33.0            33.0   µg/m3
3 2008-05-09 05:00:00  2008    5    9     5   31.0            31.0   µg/m3
4 2008-05-09 06:00:00  2008    5    9     6   33.0            33.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True     False
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2008-05-09 02:00:00  2008    5    9     2   47.0            47.0   µg/m3
1 2008-05-09 03:00:00  2008    5    9     3    NaN             NaN     NaN
2 2008-05-09 04:00:00  2008    5    9     4   33.0            33.0   µg/m3
3 2008-05-09 05:00:00  2008    5    9     5   31.0            31.0   µg/m3
4 2008-05-09 06:00:00  2008    5    9     6   33.0            33.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True     False
2          True      True
3          True      True
4          True      True
004
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/NO2/RJ0026RA004.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
23258179      549.044882   ug/m3 2018-09-21 17:29:59
23258191      233.354746   ug/m3 2018-09-24 11:29:59
23257980       60.288506   ug/m3 2018-08-20 21:29:59
23257979       58.137933   ug/m3 2018-08-20 20:29:59
23257981       56.426892   ug/m3 2018-08-20 22:30:00
mma
             DATETIME     ANO  MES   DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2006-07-21 00:00:00  2006.0  7.0  21.0   0.0    NaN             NaN   µg/m³
1 2006-07-21 01:00:00  2006.0  7.0  21.0   1.0  27.02           27.02   µg/m³
2 2006-07-21 02:00:00  2006.0  7.0  21.0   2.0  28.43           28.43   µg/m³
3 2006-07-21 03:00:00  2006.0  7.0  21.0   3.0  25.45           25.45   µg/m³
4 2006-07-21 04:00:00  2006.0  7.0  21.0   4.0  29.10           29.10   µg/m³

   QAQC_INTERNO  QAQC_MMA
0         False     False
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME     ANO  MES   DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2006-07-21 00:00:00  2006.0  7.0  21.0   0.0    NaN             NaN   µg/m³
1 2006-07-21 01:00:00  2006.0  7.0  21.0   1.0  27.02           27.02   µg/m³
2 2006-07-21 02:00:00  2006.0  7.0  21.0   2.0  28.43           28.43   µg/m³
3 2006-07-21 03:00:00  2006.0  7.0  21.0   3.0  25.45           25.45   µg/m³
4 2006-07-21 04:00:00  2006.0  7.0  21.0   4.0  29.10           29.10   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True      True
2          True      True
3          True      True
4          True      True
004
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/NO2/SP0099RA004.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
17331409           235.0   ug/m3 2015-09-25 11:00:00
17331408           210.0   ug/m3 2015-09-25 10:00:00
6906347            203.0   ug/m3 2017-08-30 10:00:00
11778026           198.0   ug/m3 2016-09-29 10:00:00
14937293           197.0   ug/m3 2018-07-16 11:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1999-09-01 14:00:00  1999    9    1    14   77.0            77.0   µg/m3
1 1999-09-01 15:00:00  1999    9    1    15    NaN             NaN     NaN
2 1999-09-01 16:00:00  1999    9    1    16  126.0           126.0   µg/m3
3 1999-09-01 17:00:00  1999    9    1    17  181.0           181.0   µg/m3
4 1999-09-01 18:00:00  1999    9    1    18  277.0           277.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True     False
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1999-09-01 14:00:00  1999    9    1    14   77.0            77.0   µg/m3
1 1999-09-01 15:00:00  1999    9    1    15    NaN             NaN     NaN
2 1999-09-01 16:00:00  1999    9    1    16  126.0           126.0   µg/m3
3 1999-09-01 17:00:00  1999    9    1    17  181.0           181.0   µg/m3
4 1999-09-01 18:00:00  1999    9    1    18  277.0           277.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True     False
2          True      True
3          True      True
4          True      True
004
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/NO2/MG0005RA004.csv

/tmp/ipykernel_273420/1352582357.py:97: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  df_mma = pd.read_csv(arquivo, encoding = 'UTF-8')
/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
40154971          308.42   µg/m3 2016-11-10 22:30:00
40154974          287.35   µg/m3 2016-11-10 23:30:00
40154975          286.68   µg/m3 2016-11-10 21:30:00
40154978          277.99   µg/m3 2016-11-10 05:30:00
40154980          269.20   µg/m3 2016-11-10 06:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR VALOR_ORIGINAL UNIDADE  \
0 2009-01-01 01:00:00  2009    1    1     1    NaN              *     ppb
1 2009-01-01 02:00:00  2009    1    1     2    NaN              *     ppb
2 2009-01-01 03:00:00  2009    1    1     3    NaN              *     ppb
3 2009-01-01 04:00:00  2009    1    1     4    NaN              *     ppb
4 2009-01-01 05:00:00  2009    1    1     5    NaN              *     ppb

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR VALOR_ORIGINAL UNIDADE  \
0 2009-01-01 01:00:00  2009    1    1     1    NaN              *     ppb
1 2009-01-01 02:00:00  2009    1    1     2    NaN              *     ppb
2 2009-01-01 03:00:00  2009    1    1     3    NaN              *     ppb
3 2009-01-01 04:00:00  2009    1    1     4    NaN              *     ppb
4 2009-01-01 05:00:00  2009    1    1     5    NaN              *     ppb

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
004
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/NO2/RJ0060RA004.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
29266599        349.5160   ug/m3 2016-07-22 13:30:00
29266600        338.1720   ug/m3 2016-07-22 14:30:00
25326457        285.1815   ug/m3 2017-05-24 15:00:00
29266598        276.8130   ug/m3 2016-07-22 12:30:00
29266601        224.7780   ug/m3 2016-07-22 15:30:00
mma
             DATETIME     ANO   MES   DIA  HORA  VALOR  VALOR_ORIGINAL  \
0 2008-12-15 00:00:00  2008.0  12.0  15.0   0.0    NaN             NaN
1 2008-12-15 01:00:00  2008.0  12.0  15.0   1.0    NaN             NaN
2 2008-12-15 02:00:00  2008.0  12.0  15.0   2.0    NaN             NaN
3 2008-12-15 03:00:00  2008.0  12.0  15.0   3.0    NaN             NaN
4 2008-12-15 04:00:00  2008.0  12.0  15.0   4.0    NaN             NaN

  UNIDADE  QAQC_INTERNO  QAQC_MMA
0   µg/m³         False     False
1   µg/m³         False     False
2   µg/m³         False     False
3   µg/m³         False     False
4   µg/m³         False     False
final
             DATETIME     ANO   MES   DIA  HORA  VALOR  VALOR_ORIGINAL  \
0 2008-12-15 00:00:00  2008.0  12.0  15.0   0.0    NaN             NaN
1 2008-12-15 01:00:00  2008.0  12.0  15.0   1.0    NaN             NaN
2 2008-12-15 02:00:00  2008.0  12.0  15.0   2.0    NaN             NaN
3 2008-12-15 03:00:00  2008.0  12.0  15.0   3.0    NaN             NaN
4 2008-12-15 04:00:00  2008.0  12.0  15.0   4.0    NaN             NaN

  UNIDADE  QAQC_INTERNO  QAQC_MMA
0   µg/m³          True     False
1   µg/m³          True     False
2   µg/m³          True     False
3   µg/m³          True     False
4   µg/m³          True     False
004
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/NO2/RJ0034RA004.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
25131751    2.460000e+12   ug/m3 2017-04-25 03:00:00
25131158    1.910000e+12   ug/m3 2017-03-30 15:00:00
25129899    7.225620e+11   ug/m3 2017-01-25 09:00:00
29066591    2.143119e+02   µg/m3 2019-12-12 19:00:00
29066387    1.908934e+02   µg/m3 2019-12-12 18:00:00
mma
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2004-03-01 12:00:00  2004.0  3.0  1.0  12.0    NaN             NaN   µg/m³
1 2004-03-01 13:00:00  2004.0  3.0  1.0  13.0    NaN             NaN   µg/m³
2 2004-03-01 14:00:00  2004.0  3.0  1.0  14.0    NaN             NaN   µg/m³
3 2004-03-01 15:00:00  2004.0  3.0  1.0  15.0    NaN             NaN   µg/m³
4 2004-03-01 16:00:00  2004.0  3.0  1.0  16.0    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0         False     False
1         False     False
2         False     False
3         False     False
4         False     False
final
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2004-03-01 12:00:00  2004.0  3.0  1.0  12.0    NaN             NaN   µg/m³
1 2004-03-01 13:00:00  2004.0  3.0  1.0  13.0    NaN             NaN   µg/m³
2 2004-03-01 14:00:00  2004.0  3.0  1.0  14.0    NaN             NaN   µg/m³
3 2004-03-01 15:00:00  2004.0  3.0  1.0  15.0    NaN             NaN   µg/m³
4 2004-03-01 16:00:00  2004.0  3.0  1.0  16.0    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
004
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/NO2/SP0067RA004.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
17720209           130.0   ug/m3 2015-09-24 22:00:00
17720208           125.0   ug/m3 2015-09-24 21:00:00
8271097            125.0   ug/m3 2019-07-12 19:00:00
17720584           124.0   ug/m3 2015-10-20 22:00:00
11481453           123.0   ug/m3 2021-08-10 20:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2002-01-07 20:00:00  2002    1    7    20   22.0            22.0   µg/m3
1 2002-01-07 21:00:00  2002    1    7    21   28.0            28.0   µg/m3
2 2002-01-07 22:00:00  2002    1    7    22   33.0            33.0   µg/m3
3 2002-01-07 23:00:00  2002    1    7    23   34.0            34.0   µg/m3
4 2002-01-08 00:00:00  2002    1    8     0   36.0            36.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2002-01-07 20:00:00  2002    1    7    20   22.0            22.0   µg/m3
1 2002-01-07 21:00:00  2002    1    7    21   28.0            28.0   µg/m3
2 2002-01-07 22:00:00  2002    1    7    22   33.0            33.0   µg/m3
3 2002-01-07 23:00:00  2002    1    7    23   34.0            34.0   µg/m3
4 2002-01-08 00:00:00  2002    1    8     0   36.0            36.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
004
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/NO2/SP0073RA004.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
8626947            267.0   ug/m3 2022-06-24 17:00:00
19107239           256.0   ug/m3 2015-09-25 11:00:00
19107238           241.0   ug/m3 2015-09-25 10:00:00
8626948            230.0   ug/m3 2022-06-24 18:00:00
18168073           226.0   ug/m3 2017-09-27 22:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1998-01-01 01:00:00  1998    1    1     1   38.0            38.0   µg/m3
1 1998-01-01 02:00:00  1998    1    1     2   42.0            42.0   µg/m3
2 1998-01-01 03:00:00  1998    1    1     3   45.0            45.0   µg/m3
3 1998-01-01 04:00:00  1998    1    1     4   45.0            45.0   µg/m3
4 1998-01-01 05:00:00  1998    1    1     5   32.0            32.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1998-01-01 01:00:00  1998    1    1     1   38.0            38.0   µg/m3
1 1998-01-01 02:00:00  1998    1    1     2   42.0            42.0   µg/m3
2 1998-01-01 03:00:00  1998    1    1     3   45.0            45.0   µg/m3
3 1998-01-01 04:00:00  1998    1    1     4   45.0            45.0   µg/m3
4 1998-01-01 05:00:00  1998    1    1     5   32.0            32.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
004
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/NO2/RJ0058RA004.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
21867268      108.911511   ug/m3 2017-03-20 08:00:00
21867266      108.876670   ug/m3 2017-03-18 18:00:00
21867267      108.870522   ug/m3 2017-03-18 21:00:00
21867265      108.866423   ug/m3 2017-03-18 16:00:00
21867264      108.862324   ug/m3 2017-03-18 14:00:00
mma
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2008-07-01 00:00:00  2008.0  7.0  1.0   0.0    NaN             NaN   µg/m³
1 2008-07-01 01:00:00  2008.0  7.0  1.0   1.0    NaN             NaN   µg/m³
2 2008-07-01 02:00:00  2008.0  7.0  1.0   2.0    NaN             NaN   µg/m³
3 2008-07-01 03:00:00  2008.0  7.0  1.0   3.0    NaN             NaN   µg/m³
4 2008-07-01 04:00:00  2008.0  7.0  1.0   4.0    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0         False     False
1         False     False
2         False     False
3         False     False
4         False     False
final
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2008-07-01 00:00:00  2008.0  7.0  1.0   0.0    NaN             NaN   µg/m³
1 2008-07-01 01:00:00  2008.0  7.0  1.0   1.0    NaN             NaN   µg/m³
2 2008-07-01 02:00:00  2008.0  7.0  1.0   2.0    NaN             NaN   µg/m³
3 2008-07-01 03:00:00  2008.0  7.0  1.0   3.0    NaN             NaN   µg/m³
4 2008-07-01 04:00:00  2008.0  7.0  1.0   4.0    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
004
004
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/NO2/RJ0071RA004.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
24978932        200.9353   ug/m3 2017-04-03 09:00:00
24979002        118.2020   ug/m3 2017-04-06 07:00:00
24979001        114.6261   ug/m3 2017-04-06 06:00:00
24978787        106.4314   ug/m3 2017-03-27 09:00:00
24978690        104.6088   ug/m3 2017-03-21 08:00:00
mma
             DATETIME     ANO   MES   DIA  HORA  VALOR  VALOR_ORIGINAL  \
0 2000-12-21 06:00:00  2000.0  12.0  21.0   6.0   4.42            4.42
1 2000-12-21 07:00:00  2000.0  12.0  21.0   7.0   1.95            1.95
2 2000-12-21 08:00:00  2000.0  12.0  21.0   8.0   3.21            3.21
3 2000-12-21 09:00:00  2000.0  12.0  21.0   9.0   4.79            4.79
4 2000-12-21 10:00:00  2000.0  12.0  21.0  10.0   5.02            5.02

  UNIDADE  QAQC_INTERNO  QAQC_MMA
0   µg/m³          True      True
1   µg/m³          True      True
2   µg/m³          True      True
3   µg/m³          True      True
4   µg/m³          True      True
final
             DATETIME     ANO   MES   DIA  HORA  VALOR  VALOR_ORIGINAL  \
0 2000-12-21 06:00:00  2000.0  12.0  21.0   6.0   4.42            4.42
1 2000-12-21 07:00:00  2000.0  12.0  21.0   7.0   1.95            1.95
2 2000-12-21 08:00:00  2000.0  12.0  21.0   8.0   3.21            3.21
3 2000-12-21 09:00:00  2000.0  12.0  21.0   9.0   4.79            4.79
4 2000-12-21 10:00:00  2000.0  12.0  21.0  10.0   5.02            5.02

  UNIDADE  QAQC_INTERNO  QAQC_MMA
0   µg/m³          True      True
1   µg/m³          True      True
2   µg/m³          True      True
3   µg/m³          True      True
4   µg/m³          True      True
004
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/NO2/RJ0069RA004.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
24839801      176.706100   ug/m3 2017-09-15 18:00:00
19566447      159.163974   µg/m3 2019-01-12 09:00:00
24839802      152.781700   ug/m3 2017-09-15 19:00:00
19792470      144.365136   µg/m3 2019-03-09 11:00:00
24840370      142.875200   ug/m3 2017-10-11 19:00:00
mma
             DATETIME     ANO   MES   DIA  HORA  VALOR  VALOR_ORIGINAL  \
0 2000-12-19 07:00:00  2000.0  12.0  19.0   7.0  11.26           11.26
1 2000-12-19 08:00:00  2000.0  12.0  19.0   8.0  16.20           16.20
2 2000-12-19 09:00:00  2000.0  12.0  19.0   9.0  42.11           42.11
3 2000-12-19 10:00:00  2000.0  12.0  19.0  10.0  53.18           53.18
4 2000-12-19 11:00:00  2000.0  12.0  19.0  11.0  60.73           60.73

  UNIDADE  QAQC_INTERNO  QAQC_MMA
0   µg/m³          True      True
1   µg/m³          True      True
2   µg/m³          True      True
3   µg/m³          True      True
4   µg/m³          True      True
final
             DATETIME     ANO   MES   DIA  HORA  VALOR  VALOR_ORIGINAL  \
0 2000-12-19 07:00:00  2000.0  12.0  19.0   7.0  11.26           11.26
1 2000-12-19 08:00:00  2000.0  12.0  19.0   8.0  16.20           16.20
2 2000-12-19 09:00:00  2000.0  12.0  19.0   9.0  42.11           42.11
3 2000-12-19 10:00:00  2000.0  12.0  19.0  10.0  53.18           53.18
4 2000-12-19 11:00:00  2000.0  12.0  19.0  11.0  60.73           60.73

  UNIDADE  QAQC_INTERNO  QAQC_MMA
0   µg/m³          True      True
1   µg/m³          True      True
2   µg/m³          True      True
3   µg/m³          True      True
4   µg/m³          True      True
004
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/NO2/BA0003ND004.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
         VALOR_ORIGINAL UNIDADE            DATETIME
5277631       82.899978   ug/m3 2017-09-24 08:00:00
5271711       58.778031   ug/m3 2017-01-10 01:00:00
5273590       54.084806   ug/m3 2017-04-01 16:00:00
5271899       54.043817   ug/m3 2017-01-17 21:00:00
5272042       51.625474   ug/m3 2017-01-23 20:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1998-01-01 00:00:00  1998    1    1     0    NaN             NaN   ug/m³
1 1998-01-01 01:00:00  1998    1    1     1    NaN             NaN   ug/m³
2 1998-01-01 02:00:00  1998    1    1     2    NaN             NaN   ug/m³
3 1998-01-01 03:00:00  1998    1    1     3    NaN             NaN   ug/m³
4 1998-01-01 04:00:00  1998    1    1     4    NaN             NaN   ug/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1998-01-01 00:00:00  1998    1    1     0    NaN             NaN   ug/m³
1 1998-01-01 01:00:00  1998    1    1     1    NaN             NaN   ug/m³
2 1998-01-01 02:00:00  1998    1    1     2    NaN             NaN   ug/m³
3 1998-01-01 03:00:00  1998    1    1     3    NaN             NaN   ug/m³
4 1998-01-01 04:00:00  1998    1    1     4    NaN             NaN   ug/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
004
004
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/NO2/BA0010ND004.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
         VALOR_ORIGINAL UNIDADE            DATETIME
4902876       60.960000     ppb 2016-04-19 11:00:00
5191922       37.709755   ug/m3 2017-04-19 15:00:00
4902900       37.300000     ppb 2016-04-20 11:00:00
5193308       36.910472   ug/m3 2017-06-23 19:00:00
5190434       35.414379   ug/m3 2017-02-14 03:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1998-01-01 00:00:00  1998    1    1     0    NaN             NaN   ug/m³
1 1998-01-01 01:00:00  1998    1    1     1    NaN             NaN   ug/m³
2 1998-01-01 02:00:00  1998    1    1     2    NaN             NaN   ug/m³
3 1998-01-01 03:00:00  1998    1    1     3    NaN             NaN   ug/m³
4 1998-01-01 04:00:00  1998    1    1     4    NaN             NaN   ug/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1998-01-01 00:00:00  1998    1    1     0    NaN             NaN   ug/m³
1 1998-01-01 01:00:00  1998    1    1     1    NaN             NaN   ug/m³
2 1998-01-01 02:00:00  1998    1    1     2    NaN             NaN   ug/m³
3 1998-01-01 03:00:00  1998    1    1     3    NaN             NaN   ug/m³
4 1998-01-01 04:00:00  1998    1    1     4    NaN             NaN   ug/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
004
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/NO2/SP0111RA004.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
18784983           136.0   ug/m3 2017-08-30 20:00:00
18785906           127.0   ug/m3 2017-10-10 20:00:00
14685501           121.0   ug/m3 2016-07-13 19:00:00
13034374           119.0   ug/m3 2020-10-01 21:00:00
18784960           118.0   ug/m3 2017-08-29 20:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2008-04-30 02:00:00  2008    4   30     2   16.0            16.0   µg/m3
1 2008-04-30 03:00:00  2008    4   30     3    NaN             NaN     NaN
2 2008-04-30 04:00:00  2008    4   30     4    1.0             1.0   µg/m3
3 2008-04-30 05:00:00  2008    4   30     5    2.0             2.0   µg/m3
4 2008-04-30 06:00:00  2008    4   30     6    1.0             1.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True     False
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2008-04-30 02:00:00  2008    4   30     2   16.0            16.0   µg/m3
1 2008-04-30 03:00:00  2008    4   30     3    NaN             NaN     NaN
2 2008-04-30 04:00:00  2008    4   30     4    1.0             1.0   µg/m3
3 2008-04-30 05:00:00  2008    4   30     5    2.0             2.0   µg/m3
4 2008-04-30 06:00:00  2008    4   30     6    1.0             1.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True     False
2          True      True
3          True      True
4          True      True
SO2
['RJ0032', 'RJ0022', 'PR0009 ', 'MG0008', 'PR0006 ', 'PR0005 ', 'MG0036', 'RJ0048', 'MG0009', 'SP0086', 'RJ0037', 'BA0002', 'RJ0021', 'SP0091', 'BA0005', nan, 'MG0039', 'RJ0079', 'RJ0226', 'RJ0055', 'RJ0063', 'RJ0043', 'PR0003 ', 'MG0001', 'SP0120', 'MG0006', 'MG0002', 'MG0057', 'SP0262', 'BA0006', 'RJ0036', 'RJ0081', 'MG0012', 'BA0008', 'BA0007', 'RJ0019', 'CE0001', 'BA0011', 'RJ0225', 'RJ0070', 'MG0017', 'MG0010', 'RJ0038', 'PR0004 ', 'RJ0057', 'RJ0027', 'RJ0078', 'RJ0033', 'BA0001', 'MG0013', 'MG0004', 'RJ0031', 'PR0015 ', 'RJ0064', 'PR0008 ', 'RJ0030', 'RJ0029', 'MG0003', 'RJ0039', 'PR0007 ', 'BA0004', 'MG0053', 'PR0001 ', 'SP0280', 'SP0117', 'PR0012 ', 'RJ0026', 'SP0099', 'MG0005', 'RJ0060', 'RJ0034', 'SP0073', 'RJ0058', 'PR0002 ', 'RJ0071', 'RJ0069', 'BA0003', 'BA0010']
003
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/SO2/RJ0032RA003.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
25151697      725.152000   ug/m3 2017-04-24 11:00:00
31297210      454.079100   µg/m3 2020-04-21 12:00:00
19853455      452.083969   µg/m3 2019-03-24 11:00:00
20079846      425.853832   µg/m3 2019-05-19 09:00:00
20101093      412.138806   µg/m3 2019-05-24 12:00:00
mma
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2004-03-01 12:00:00  2004.0  3.0  1.0  12.0    NaN             NaN   µg/m³
1 2004-03-01 13:00:00  2004.0  3.0  1.0  13.0    NaN             NaN   µg/m³
2 2004-03-01 14:00:00  2004.0  3.0  1.0  14.0    NaN             NaN   µg/m³
3 2004-03-01 15:00:00  2004.0  3.0  1.0  15.0    NaN             NaN   µg/m³
4 2004-03-01 16:00:00  2004.0  3.0  1.0  16.0    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0         False     False
1         False     False
2         False     False
3         False     False
4         False     False
final
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2004-03-01 12:00:00  2004.0  3.0  1.0  12.0    NaN             NaN   µg/m³
1 2004-03-01 13:00:00  2004.0  3.0  1.0  13.0    NaN             NaN   µg/m³
2 2004-03-01 14:00:00  2004.0  3.0  1.0  14.0    NaN             NaN   µg/m³
3 2004-03-01 15:00:00  2004.0  3.0  1.0  15.0    NaN             NaN   µg/m³
4 2004-03-01 16:00:00  2004.0  3.0  1.0  16.0    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
003
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/SO2/RJ0022RA003.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
29516745         151.177   ug/m3 2016-08-14 14:30:00
29516770         113.820   ug/m3 2016-08-15 15:30:00
29512884         109.203   ug/m3 2016-02-26 15:30:00
29518206         103.646   ug/m3 2016-10-14 11:30:00
29516769         102.817   ug/m3 2016-08-15 14:30:00
mma
             DATETIME     ANO  MES   DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2000-07-26 08:00:00  2000.0  7.0  26.0   8.0  52.19           52.19   µg/m³
1 2000-07-26 09:00:00  2000.0  7.0  26.0   9.0  50.87           50.87   µg/m³
2 2000-07-26 10:00:00  2000.0  7.0  26.0  10.0  68.93           68.93   µg/m³
3 2000-07-26 11:00:00  2000.0  7.0  26.0  11.0  54.84           54.84   µg/m³
4 2000-07-26 12:00:00  2000.0  7.0  26.0  12.0  48.45           48.45   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME     ANO  MES   DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2000-07-26 08:00:00  2000.0  7.0  26.0   8.0  52.19           52.19   µg/m³
1 2000-07-26 09:00:00  2000.0  7.0  26.0   9.0  50.87           50.87   µg/m³
2 2000-07-26 10:00:00  2000.0  7.0  26.0  10.0  68.93           68.93   µg/m³
3 2000-07-26 11:00:00  2000.0  7.0  26.0  11.0  54.84           54.84   µg/m³
4 2000-07-26 12:00:00  2000.0  7.0  26.0  12.0  48.45           48.45   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
003
003
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/SO2/MG0008RA003.csv

/tmp/ipykernel_273420/1352582357.py:97: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  df_mma = pd.read_csv(arquivo, encoding = 'UTF-8')
/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
35088267          163.65   µg/m3 2017-09-07 09:30:00
39867794          102.54   µg/m3 2016-08-11 03:30:00
39867818          101.09   µg/m3 2016-08-11 04:30:00
32966729           76.81   µg/m3 2015-01-12 14:30:00
36489136           76.63   µg/m3 2018-05-28 20:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR VALOR_ORIGINAL UNIDADE  \
0 2013-01-01 01:00:00  2013    1    1     1    2.4            2.4     ppb
1 2013-01-01 02:00:00  2013    1    1     2    2.0              2     ppb
2 2013-01-01 03:00:00  2013    1    1     3    2.5            2.5     ppb
3 2013-01-01 04:00:00  2013    1    1     4    3.3            3.3     ppb
4 2013-01-01 05:00:00  2013    1    1     5    4.3            4.3     ppb

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR VALOR_ORIGINAL UNIDADE  \
0 2013-01-01 01:00:00  2013    1    1     1    2.4            2.4     ppb
1 2013-01-01 02:00:00  2013    1    1     2    2.0              2     ppb
2 2013-01-01 03:00:00  2013    1    1     3    2.5            2.5     ppb
3 2013-01-01 04:00:00  2013    1    1     4    3.3            3.3     ppb
4 2013-01-01 05:00:00  2013    1    1     5    4.3            4.3     ppb

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
003
003
003
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/SO2/MG0036RA003.csv
iema
          VALOR_ORIGINAL UNIDADE            DATETIME
38860238           214.6   µg/m3 2022-03-25 10:30:00
34651650            69.2   µg/m3 2019-09-04 12:30:00
34651801            63.0   µg/m3 2019-09-04 13:30:00
34668079            48.0   µg/m3 2019-09-08 17:30:00
34280075            45.0   µg/m3 2019-05-26 11:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2017-08-22 17:00:00  2017    8   22    17    NaN             NaN   µg/m3
1 2017-08-22 18:00:00  2017    8   22    18    1.1             1.1   µg/m3
2 2017-08-22 19:00:00  2017    8   22    19    1.2             1.2   µg/m3
3 2017-08-22 20:00:00  2017    8   22    20    1.0             1.0   µg/m3
4 2017-08-22 21:00:00  2017    8   22    21    0.8             0.8   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2017-08-22 17:00:00  2017    8   22    17    NaN             NaN   µg/m3
1 2017-08-22 18:00:00  2017    8   22    18    1.1             1.1   µg/m3
2 2017-08-22 19:00:00  2017    8   22    19    1.2             1.2   µg/m3
3 2017-08-22 20:00:00  2017    8   22    20    1.0             1.0   µg/m3
4 2017-08-22 21:00:00  2017    8   22    21    0.8             0.8   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True      True
2          True      True
3          True      True
4          True      True

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

003
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/SO2/RJ0048RA003.csv
iema
          VALOR_ORIGINAL UNIDADE            DATETIME
22755304           20.24   ug/m3 2022-12-04 23:00:00
22755305           19.95   ug/m3 2022-12-05 00:00:00
24447976           19.85   µg/m³ 2021-04-28 21:00:00
24447974           19.76   µg/m³ 2021-04-28 19:00:00
24447975           19.69   µg/m³ 2021-04-28 20:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2019-09-17 16:00:00  2019    9   17    16    NaN             NaN   µg/m³
1 2019-09-17 17:00:00  2019    9   17    17    NaN             NaN   µg/m³
2 2019-09-17 18:00:00  2019    9   17    18    NaN             NaN   µg/m³
3 2019-09-17 19:00:00  2019    9   17    19    NaN             NaN   µg/m³
4 2019-09-17 20:00:00  2019    9   17    20    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0         False     False
1         False     False
2         False     False
3         False     False
4         False     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2019-09-17 16:00:00  2019    9   17    16    NaN             NaN   µg/m³
1 2019-09-17 17:00:00  2019    9   17    17    NaN             NaN   µg/m³
2 2019-09-17 18:00:00  2019    9   17    18    NaN             NaN   µg/m³
3 2019-09-17 19:00:00  2019    9   17    19    NaN             NaN   µg/m³
4 2019-09-17 20:00:00  2019    9   17    20    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

003
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/SO2/MG0009RA003.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
34454734          117.43   µg/m3 2019-07-14 10:30:00
35559513          110.90   µg/m3 2017-10-29 09:30:00
40387144          108.52   µg/m3 2016-08-18 10:30:00
34454895          107.37   µg/m3 2019-07-14 11:30:00
36620752          103.52   µg/m3 2018-07-09 10:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2014-01-01 01:00:00  2014    1    1     1    NaN             NaN   µg/m3
1 2014-01-01 02:00:00  2014    1    1     2    NaN             NaN   µg/m3
2 2014-01-01 03:00:00  2014    1    1     3    NaN             NaN   µg/m3
3 2014-01-01 04:00:00  2014    1    1     4    NaN             NaN   µg/m3
4 2014-01-01 05:00:00  2014    1    1     5    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2014-01-01 01:00:00  2014    1    1     1    NaN             NaN   µg/m3
1 2014-01-01 02:00:00  2014    1    1     2    NaN             NaN   µg/m3
2 2014-01-01 03:00:00  2014    1    1     3    NaN             NaN   µg/m3
3 2014-01-01 04:00:00  2014    1    1     4    NaN             NaN   µg/m3
4 2014-01-01 05:00:00  2014    1    1     5    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
003
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/SO2/SP0086RA003.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
7141459             63.0   ug/m3 2017-04-25 19:00:00
17672391            60.0   ug/m3 2015-09-23 03:00:00
16941328            58.0   ug/m3 2022-04-07 09:00:00
17672392            56.0   ug/m3 2015-09-23 05:00:00
7141461             55.0   ug/m3 2017-04-25 21:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1998-01-29 14:00:00  1998    1   29    14   16.0            16.0   µg/m3
1 1998-01-29 15:00:00  1998    1   29    15   13.0            13.0   µg/m3
2 1998-01-29 16:00:00  1998    1   29    16   14.0            14.0   µg/m3
3 1998-01-29 17:00:00  1998    1   29    17   10.0            10.0   µg/m3
4 1998-01-29 18:00:00  1998    1   29    18    7.0             7.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1998-01-29 14:00:00  1998    1   29    14   16.0            16.0   µg/m3
1 1998-01-29 15:00:00  1998    1   29    15   13.0            13.0   µg/m3
2 1998-01-29 16:00:00  1998    1   29    16   14.0            14.0   µg/m3
3 1998-01-29 17:00:00  1998    1   29    17   10.0            10.0   µg/m3
4 1998-01-29 18:00:00  1998    1   29    18    7.0             7.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
003
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/SO2/RJ0037RA003.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
26408577          158.05   µg/m³ 2021-04-02 14:00:00
30648908          108.45   µg/m³ 2022-07-22 15:00:00
23236616          107.90     ppb 2018-04-21 11:29:59
30646522           94.76   µg/m³ 2022-04-13 13:00:00
30647118           81.27   µg/m³ 2022-05-08 12:00:00
mma
             DATETIME     ANO   MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2001-12-04 15:00:00  2001.0  12.0  4.0  15.0   2.68            2.68   µg/m³
1 2001-12-04 16:00:00  2001.0  12.0  4.0  16.0   1.51            1.51   µg/m³
2 2001-12-04 17:00:00  2001.0  12.0  4.0  17.0   1.24            1.24   µg/m³
3 2001-12-04 18:00:00  2001.0  12.0  4.0  18.0   1.79            1.79   µg/m³
4 2001-12-04 19:00:00  2001.0  12.0  4.0  19.0   2.14            2.14   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME     ANO   MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2001-12-04 15:00:00  2001.0  12.0  4.0  15.0   2.68            2.68   µg/m³
1 2001-12-04 16:00:00  2001.0  12.0  4.0  16.0   1.51            1.51   µg/m³
2 2001-12-04 17:00:00  2001.0  12.0  4.0  17.0   1.24            1.24   µg/m³
3 2001-12-04 18:00:00  2001.0  12.0  4.0  18.0   1.79            1.79   µg/m³
4 2001-12-04 19:00:00  2001.0  12.0  4.0  19.0   2.14            2.14   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
003
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/SO2/BA0002ND003.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
         VALOR_ORIGINAL UNIDADE            DATETIME
4974152           382.2     ppb 2016-07-03 08:00:00
4971589           353.3     ppb 2016-03-18 07:00:00
5727204           295.8     ppb 2015-04-03 07:00:00
4973001           282.8     ppb 2016-05-16 07:00:00
4972905           257.7     ppb 2016-05-12 07:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1998-01-01 00:00:00  1998    1    1     0    NaN             NaN   ug/m³
1 1998-01-01 01:00:00  1998    1    1     1    NaN             NaN   ug/m³
2 1998-01-01 02:00:00  1998    1    1     2    NaN             NaN   ug/m³
3 1998-01-01 03:00:00  1998    1    1     3    NaN             NaN   ug/m³
4 1998-01-01 04:00:00  1998    1    1     4    NaN             NaN   ug/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1998-01-01 00:00:00  1998    1    1     0    NaN             NaN   ug/m³
1 1998-01-01 01:00:00  1998    1    1     1    NaN             NaN   ug/m³
2 1998-01-01 02:00:00  1998    1    1     2    NaN             NaN   ug/m³
3 1998-01-01 03:00:00  1998    1    1     3    NaN             NaN   ug/m³
4 1998-01-01 04:00:00  1998    1    1     4    NaN             NaN   ug/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
003
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/SO2/RJ0021RA003.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
25517169        153.6810   ug/m3 2017-01-30 17:00:00
25517168        153.4930   ug/m3 2017-01-30 16:00:00
25517167        147.9760   ug/m3 2017-01-30 15:00:00
25517166        146.0946   ug/m3 2017-01-30 14:00:00
25517170        143.9143   ug/m3 2017-01-30 18:00:00
mma
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1999-05-01 00:00:00  1999.0  5.0  1.0   0.0   2.66            2.66   µg/m³
1 1999-05-01 01:00:00  1999.0  5.0  1.0   1.0   2.66            2.66   µg/m³
2 1999-05-01 02:00:00  1999.0  5.0  1.0   2.0    NaN            0.00   µg/m³
3 1999-05-01 03:00:00  1999.0  5.0  1.0   3.0    NaN            0.00   µg/m³
4 1999-05-01 04:00:00  1999.0  5.0  1.0   4.0    NaN            0.00   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True     False
3          True     False
4          True     False
final
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1999-05-01 00:00:00  1999.0  5.0  1.0   0.0   2.66            2.66   µg/m³
1 1999-05-01 01:00:00  1999.0  5.0  1.0   1.0   2.66            2.66   µg/m³
2 1999-05-01 02:00:00  1999.0  5.0  1.0   2.0    NaN            0.00   µg/m³
3 1999-05-01 03:00:00  1999.0  5.0  1.0   3.0    NaN            0.00   µg/m³
4 1999-05-01 04:00:00  1999.0  5.0  1.0   4.0    NaN            0.00   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True     False
3          True     False
4          True     False
003
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/SO2/SP0091RA003.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
18099116            32.0   ug/m3 2017-09-26 23:00:00
15713506            31.0   ug/m3 2021-02-10 10:00:00
19039927            28.0   ug/m3 2015-07-29 14:00:00
19041156            28.0   ug/m3 2015-09-23 07:00:00
19040142            27.0   ug/m3 2015-08-07 22:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1998-01-04 11:00:00  1998    1    4    11   26.0            26.0   µg/m3
1 1998-01-04 12:00:00  1998    1    4    12   27.0            27.0   µg/m3
2 1998-01-04 13:00:00  1998    1    4    13   26.0            26.0   µg/m3
3 1998-01-04 14:00:00  1998    1    4    14   24.0            24.0   µg/m3
4 1998-01-04 15:00:00  1998    1    4    15   24.0            24.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1998-01-04 11:00:00  1998    1    4    11   26.0            26.0   µg/m3
1 1998-01-04 12:00:00  1998    1    4    12   27.0            27.0   µg/m3
2 1998-01-04 13:00:00  1998    1    4    13   26.0            26.0   µg/m3
3 1998-01-04 14:00:00  1998    1    4    14   24.0            24.0   µg/m3
4 1998-01-04 15:00:00  1998    1    4    15   24.0            24.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
003
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/SO2/BA0005ND003.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
         VALOR_ORIGINAL UNIDADE            DATETIME
5791839            44.7     ppb 2015-12-01 10:00:00
5791840            44.2     ppb 2015-12-01 11:00:00
5147962            13.3     ppb 2016-03-23 15:00:00
5147961             8.8     ppb 2016-03-23 14:00:00
5791841             6.7     ppb 2015-12-01 12:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1998-01-01 00:00:00  1998    1    1     0    NaN             NaN   ug/m³
1 1998-01-01 01:00:00  1998    1    1     1    NaN             NaN   ug/m³
2 1998-01-01 02:00:00  1998    1    1     2    NaN             NaN   ug/m³
3 1998-01-01 03:00:00  1998    1    1     3    NaN             NaN   ug/m³
4 1998-01-01 04:00:00  1998    1    1     4    NaN             NaN   ug/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1998-01-01 00:00:00  1998    1    1     0    NaN             NaN   ug/m³
1 1998-01-01 01:00:00  1998    1    1     1    NaN             NaN   ug/m³
2 1998-01-01 02:00:00  1998    1    1     2    NaN             NaN   ug/m³
3 1998-01-01 03:00:00  1998    1    1     3    NaN             NaN   ug/m³
4 1998-01-01 04:00:00  1998    1    1     4    NaN             NaN   ug/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
003
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/SO2/MG0039RA003.csv
iema
          VALOR_ORIGINAL UNIDADE            DATETIME
39467562           229.1   µg/m3 2022-09-09 10:30:00
39467717           107.2   µg/m3 2022-09-09 11:30:00
32687054            81.6   µg/m3 2020-10-15 09:30:00
39429044            73.8   µg/m3 2022-08-30 01:30:00
39429839            70.2   µg/m3 2022-08-30 06:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2017-05-03 09:00:00  2017    5    3     9    NaN             NaN   µg/m3
1 2017-05-03 10:00:00  2017    5    3    10    NaN             NaN   µg/m3
2 2017-05-03 11:00:00  2017    5    3    11    NaN             NaN   µg/m3
3 2017-05-03 12:00:00  2017    5    3    12    NaN             NaN   µg/m3
4 2017-05-03 13:00:00  2017    5    3    13    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2017-05-03 09:00:00  2017    5    3     9    NaN             NaN   µg/m3
1 2017-05-03 10:00:00  2017    5    3    10    NaN             NaN   µg/m3
2 2017-05-03 11:00:00  2017    5    3    11    NaN             NaN   µg/m3
3 2017-05-03 12:00:00  2017    5    3    12    NaN             NaN   µg/m3
4 2017-05-03 13:00:00  2017    5    3    13    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

003
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/SO2/RJ0079RA003.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
31268168     1115.370978   µg/m3 2020-04-15 15:00:00
20299060      968.213427   µg/m3 2019-07-09 12:00:00
20056204      890.851648   µg/m3 2019-05-13 11:00:00
20182517      855.953763   µg/m3 2019-06-12 10:00:00
20298881      815.060667   µg/m3 2019-07-09 11:00:00
mma
             DATETIME     ANO   MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1998-10-01 01:00:00  1998.0  10.0  1.0   1.0    NaN             NaN   µg/m³
1 1998-10-01 02:00:00  1998.0  10.0  1.0   2.0    NaN             NaN   µg/m³
2 1998-10-01 03:00:00  1998.0  10.0  1.0   3.0    NaN             NaN   µg/m³
3 1998-10-01 04:00:00  1998.0  10.0  1.0   4.0    NaN             NaN   µg/m³
4 1998-10-01 05:00:00  1998.0  10.0  1.0   5.0    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0         False     False
1         False     False
2         False     False
3         False     False
4         False     False
final
             DATETIME     ANO   MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1998-10-01 01:00:00  1998.0  10.0  1.0   1.0    NaN             NaN   µg/m³
1 1998-10-01 02:00:00  1998.0  10.0  1.0   2.0    NaN             NaN   µg/m³
2 1998-10-01 03:00:00  1998.0  10.0  1.0   3.0    NaN             NaN   µg/m³
3 1998-10-01 04:00:00  1998.0  10.0  1.0   4.0    NaN             NaN   µg/m³
4 1998-10-01 05:00:00  1998.0  10.0  1.0   5.0    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
003
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/SO2/RJ0226RA003.csv
iema
          VALOR_ORIGINAL UNIDADE            DATETIME
29555485         256.726   ug/m3 2016-12-18 23:30:00
29555484         241.504   ug/m3 2016-12-18 22:30:00
29555483         233.813   ug/m3 2016-12-18 21:30:00
29553541         226.890   ug/m3 2016-09-10 07:30:00
29555482         211.578   ug/m3 2016-12-18 20:30:00
mma
             DATETIME     ANO  MES   DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2006-07-21 00:00:00  2006.0  7.0  21.0   0.0    NaN             NaN   µg/m³
1 2006-07-21 01:00:00  2006.0  7.0  21.0   1.0    NaN             NaN   µg/m³
2 2006-07-21 02:00:00  2006.0  7.0  21.0   2.0    NaN             NaN   µg/m³
3 2006-07-21 03:00:00  2006.0  7.0  21.0   3.0    NaN             NaN   µg/m³
4 2006-07-21 04:00:00  2006.0  7.0  21.0   4.0    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0         False     False
1         False     False
2         False     False
3         False     False
4         False     False
final
             DATETIME     ANO  MES   DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2006-07-21 00:00:00  2006.0  7.0  21.0   0.0    NaN             NaN   µg/m³
1 2006-07-21 01:00:00  2006.0  7.0  21.0   1.0    NaN             NaN   µg/m³
2 2006-07-21 02:00:00  2006.0  7.0  21.0   2.0    NaN             NaN   µg/m³
3 2006-07-21 03:00:00  2006.0  7.0  21.0   3.0    NaN             NaN   µg/m³
4 2006-07-21 04:00:00  2006.0  7.0  21.0   4.0    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

003
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/SO2/RJ0055RA003.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
19590495      177.105353   µg/m3 2019-01-18 19:00:00
19593046      169.582624   µg/m3 2019-01-19 12:00:00
30969071      163.507803   µg/m3 2020-02-11 15:00:00
19593338      140.632789   µg/m3 2019-01-19 14:00:00
25284328      139.700600   ug/m3 2017-11-29 14:00:00
mma
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2009-01-01 00:00:00  2009.0  1.0  1.0   0.0  23.72           23.72   µg/m³
1 2009-01-01 01:00:00  2009.0  1.0  1.0   1.0  23.79           23.79   µg/m³
2 2009-01-01 02:00:00  2009.0  1.0  1.0   2.0  23.78           23.78   µg/m³
3 2009-01-01 03:00:00  2009.0  1.0  1.0   3.0  23.82           23.82   µg/m³
4 2009-01-01 04:00:00  2009.0  1.0  1.0   4.0  23.84           23.84   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2009-01-01 00:00:00  2009.0  1.0  1.0   0.0  23.72           23.72   µg/m³
1 2009-01-01 01:00:00  2009.0  1.0  1.0   1.0  23.79           23.79   µg/m³
2 2009-01-01 02:00:00  2009.0  1.0  1.0   2.0  23.78           23.78   µg/m³
3 2009-01-01 03:00:00  2009.0  1.0  1.0   3.0  23.82           23.82   µg/m³
4 2009-01-01 04:00:00  2009.0  1.0  1.0   4.0  23.84           23.84   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
003
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/SO2/RJ0063RA003.csv
iema
          VALOR_ORIGINAL UNIDADE            DATETIME
30182245          215.77   µg/m³ 2022-02-01 15:00:00
30182244          176.10   µg/m³ 2022-02-01 14:00:00
25984560          163.15   µg/m³ 2021-11-04 02:00:00
25984561          153.80   µg/m³ 2021-07-14 15:00:00
25984562          134.38   µg/m³ 2021-11-06 00:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2021-05-18 08:00:00  2021    5   18     8    NaN             NaN   µg/m³
1 2021-05-18 09:00:00  2021    5   18     9    NaN             NaN   µg/m³
2 2021-05-18 10:00:00  2021    5   18    10    NaN             NaN   µg/m³
3 2021-05-18 11:00:00  2021    5   18    11    NaN             NaN   µg/m³
4 2021-05-18 12:00:00  2021    5   18    12    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0         False     False
1         False     False
2         False     False
3         False     False
4         False     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2021-05-18 08:00:00  2021    5   18     8    NaN             NaN   µg/m³
1 2021-05-18 09:00:00  2021    5   18     9    NaN             NaN   µg/m³
2 2021-05-18 10:00:00  2021    5   18    10    NaN             NaN   µg/m³
3 2021-05-18 11:00:00  2021    5   18    11    NaN             NaN   µg/m³
4 2021-05-18 12:00:00  2021    5   18    12    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

003
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/SO2/RJ0043RA003.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
31587005     1744.770966   µg/m3 2020-06-18 15:00:00
19746833     1738.166025   µg/m3 2019-02-26 12:00:00
20031909     1559.204113   µg/m3 2019-05-07 15:00:00
31433685     1505.670781   µg/m3 2020-05-18 17:00:00
29093913     1414.021504   µg/m3 2019-12-18 15:00:00
mma
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2009-06-06 20:00:00  2009.0  6.0  6.0  20.0   7.72            7.72   µg/m³
1 2009-06-06 21:00:00  2009.0  6.0  6.0  21.0   7.22            7.22   µg/m³
2 2009-06-06 22:00:00  2009.0  6.0  6.0  22.0   6.06            6.06   µg/m³
3 2009-06-06 23:00:00  2009.0  6.0  6.0  23.0   5.66            5.66   µg/m³
4 2009-06-07 00:00:00  2009.0  6.0  7.0   0.0   5.16            5.16   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2009-06-06 20:00:00  2009.0  6.0  6.0  20.0   7.72            7.72   µg/m³
1 2009-06-06 21:00:00  2009.0  6.0  6.0  21.0   7.22            7.22   µg/m³
2 2009-06-06 22:00:00  2009.0  6.0  6.0  22.0   6.06            6.06   µg/m³
3 2009-06-06 23:00:00  2009.0  6.0  6.0  23.0   5.66            5.66   µg/m³
4 2009-06-07 00:00:00  2009.0  6.0  7.0   0.0   5.16            5.16   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
003
003
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/SO2/MG0001RA003.csv

/tmp/ipykernel_273420/1352582357.py:97: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  df_mma = pd.read_csv(arquivo, encoding = 'UTF-8')
/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
39963124          372.64   µg/m3 2016-05-18 12:30:00
34572208          248.97   µg/m3 2019-08-14 19:30:00
36126386          188.09   µg/m3 2018-01-31 18:30:00
32501739          157.54   µg/m3 2020-08-24 21:30:00
36126510          148.36   µg/m3 2018-01-31 19:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR VALOR_ORIGINAL UNIDADE  \
0 2009-01-01 01:00:00  2009    1    1     1    NaN              0     ppb
1 2009-01-01 02:00:00  2009    1    1     2    NaN              0     ppb
2 2009-01-01 03:00:00  2009    1    1     3    NaN              0     ppb
3 2009-01-01 04:00:00  2009    1    1     4    NaN              0     ppb
4 2009-01-01 05:00:00  2009    1    1     5    NaN              0     ppb

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR VALOR_ORIGINAL UNIDADE  \
0 2009-01-01 01:00:00  2009    1    1     1    NaN              0     ppb
1 2009-01-01 02:00:00  2009    1    1     2    NaN              0     ppb
2 2009-01-01 03:00:00  2009    1    1     3    NaN              0     ppb
3 2009-01-01 04:00:00  2009    1    1     4    NaN              0     ppb
4 2009-01-01 05:00:00  2009    1    1     5    NaN              0     ppb

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
003
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/SO2/SP0120RA003.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
16327456           103.0   ug/m3 2022-04-28 02:00:00
16327457            56.0   ug/m3 2022-04-28 03:00:00
10880595            51.0   ug/m3 2021-08-23 23:00:00
16327455            45.0   ug/m3 2022-04-28 01:00:00
16329417            44.0   ug/m3 2022-07-22 09:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1998-01-01 02:00:00  1998    1    1     2    7.0             7.0   µg/m3
1 1998-01-01 03:00:00  1998    1    1     3    7.0             7.0   µg/m3
2 1998-01-01 04:00:00  1998    1    1     4    6.0             6.0   µg/m3
3 1998-01-01 05:00:00  1998    1    1     5    5.0             5.0   µg/m3
4 1998-01-01 06:00:00  1998    1    1     6    5.0             5.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1998-01-01 02:00:00  1998    1    1     2    7.0             7.0   µg/m3
1 1998-01-01 03:00:00  1998    1    1     3    7.0             7.0   µg/m3
2 1998-01-01 04:00:00  1998    1    1     4    6.0             6.0   µg/m3
3 1998-01-01 05:00:00  1998    1    1     5    5.0             5.0   µg/m3
4 1998-01-01 06:00:00  1998    1    1     6    5.0             5.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
003
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/SO2/MG0006RA003.csv

/tmp/ipykernel_273420/1352582357.py:97: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  df_mma = pd.read_csv(arquivo, encoding = 'UTF-8')
/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
32304683          922.68   µg/m3 2020-06-29 11:30:00
32737306          603.27   µg/m3 2020-10-30 07:30:00
32087945          594.41   µg/m3 2020-04-29 10:30:00
32416089          550.52   µg/m3 2020-07-31 16:30:00
32119335          396.76   µg/m3 2020-05-08 11:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR VALOR_ORIGINAL UNIDADE  \
0 2010-01-01 01:00:00  2010    1    1     1    NaN              0     ppb
1 2010-01-01 02:00:00  2010    1    1     2    NaN              0     ppb
2 2010-01-01 03:00:00  2010    1    1     3    NaN              0     ppb
3 2010-01-01 04:00:00  2010    1    1     4    NaN              0     ppb
4 2010-01-01 05:00:00  2010    1    1     5    NaN              0     ppb

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR VALOR_ORIGINAL UNIDADE  \
0 2010-01-01 01:00:00  2010    1    1     1    NaN              0     ppb
1 2010-01-01 02:00:00  2010    1    1     2    NaN              0     ppb
2 2010-01-01 03:00:00  2010    1    1     3    NaN              0     ppb
3 2010-01-01 04:00:00  2010    1    1     4    NaN              0     ppb
4 2010-01-01 05:00:00  2010    1    1     5    NaN              0     ppb

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
003
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/SO2/MG0002RA003.csv

/tmp/ipykernel_273420/1352582357.py:97: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  df_mma = pd.read_csv(arquivo, encoding = 'UTF-8')
/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
31833208           815.0   µg/m3 2020-02-17 08:30:00
38564228           710.8   µg/m3 2021-12-27 16:30:00
32784853           592.0   µg/m3 2020-11-12 11:30:00
33788596           549.9   µg/m3 2019-01-03 13:30:00
32457141           502.4   µg/m3 2020-08-12 13:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR VALOR_ORIGINAL UNIDADE  \
0 2009-01-01 01:00:00  2009    1    1     1    0.8            0.8     ppb
1 2009-01-01 02:00:00  2009    1    1     2    1.3            1.3     ppb
2 2009-01-01 03:00:00  2009    1    1     3    1.3            1.3     ppb
3 2009-01-01 04:00:00  2009    1    1     4    1.0              1     ppb
4 2009-01-01 05:00:00  2009    1    1     5    0.3            0.3     ppb

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR VALOR_ORIGINAL UNIDADE  \
0 2009-01-01 01:00:00  2009    1    1     1    0.8            0.8     ppb
1 2009-01-01 02:00:00  2009    1    1     2    1.3            1.3     ppb
2 2009-01-01 03:00:00  2009    1    1     3    1.3            1.3     ppb
3 2009-01-01 04:00:00  2009    1    1     4    1.0              1     ppb
4 2009-01-01 05:00:00  2009    1    1     5    0.3            0.3     ppb

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
003
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/SO2/MG0057RA003.csv
iema
          VALOR_ORIGINAL UNIDADE            DATETIME
37690196          933.90   µg/m3 2021-05-18 03:30:00
37261266          842.26   µg/m3 2021-01-22 01:30:00
38034854          673.42   µg/m3 2021-08-11 23:30:00
37609873          673.31   µg/m3 2021-04-27 02:30:00
39388930          624.87   µg/m3 2022-08-19 07:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2019-01-01 01:00:00  2019    1    1     1   5.94            5.94   µg/m3
1 2019-01-01 02:00:00  2019    1    1     2   6.03            6.03   µg/m3
2 2019-01-01 03:00:00  2019    1    1     3   6.19            6.19   µg/m3
3 2019-01-01 04:00:00  2019    1    1     4   6.30            6.30   µg/m3
4 2019-01-01 05:00:00  2019    1    1     5   6.39            6.39   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2019-01-01 01:00:00  2019    1    1     1   5.94            5.94   µg/m3
1 2019-01-01 02:00:00  2019    1    1     2   6.03            6.03   µg/m3
2 2019-01-01 03:00:00  2019    1    1     3   6.19            6.19   µg/m3
3 2019-01-01 04:00:00  2019    1    1     4   6.30            6.30   µg/m3
4 2019-01-01 05:00:00  2019    1    1     5   6.39            6.39   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

003
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/SO2/SP0262RA003.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
9850771             49.0   ug/m3 2018-03-26 14:00:00
13678159            41.0   ug/m3 2019-01-31 22:00:00
9851330             31.0   ug/m3 2018-04-18 21:00:00
12842054            30.0   ug/m3 2020-05-03 23:00:00
9851331             29.0   ug/m3 2018-04-18 22:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2012-02-27 01:00:00  2012    2   27     1    NaN             0.0   µg/m3
1 2012-02-27 02:00:00  2012    2   27     2    NaN             0.0   µg/m3
2 2012-02-27 03:00:00  2012    2   27     3    NaN             0.0   µg/m3
3 2012-02-27 04:00:00  2012    2   27     4    NaN             NaN     NaN
4 2012-02-27 05:00:00  2012    2   27     5    NaN             0.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2012-02-27 01:00:00  2012    2   27     1    NaN             0.0   µg/m3
1 2012-02-27 02:00:00  2012    2   27     2    NaN             0.0   µg/m3
2 2012-02-27 03:00:00  2012    2   27     3    NaN             0.0   µg/m3
3 2012-02-27 04:00:00  2012    2   27     4    NaN             NaN     NaN
4 2012-02-27 05:00:00  2012    2   27     5    NaN             0.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
003
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/SO2/BA0006ND003.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
         VALOR_ORIGINAL UNIDADE            DATETIME
5747655           454.2     ppb 2015-09-11 07:00:00
5745978           122.6     ppb 2015-06-29 05:00:00
5747656           122.5     ppb 2015-09-11 08:00:00
5744744            78.6     ppb 2015-05-06 07:00:00
5743937            76.5     ppb 2015-04-02 07:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1998-01-01 00:00:00  1998    1    1     0    NaN             NaN   ug/m³
1 1998-01-01 01:00:00  1998    1    1     1    NaN             NaN   ug/m³
2 1998-01-01 02:00:00  1998    1    1     2    NaN             NaN   ug/m³
3 1998-01-01 03:00:00  1998    1    1     3    NaN             NaN   ug/m³
4 1998-01-01 04:00:00  1998    1    1     4    NaN             NaN   ug/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1998-01-01 00:00:00  1998    1    1     0    NaN             NaN   ug/m³
1 1998-01-01 01:00:00  1998    1    1     1    NaN             NaN   ug/m³
2 1998-01-01 02:00:00  1998    1    1     2    NaN             NaN   ug/m³
3 1998-01-01 03:00:00  1998    1    1     3    NaN             NaN   ug/m³
4 1998-01-01 04:00:00  1998    1    1     4    NaN             NaN   ug/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
003
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/SO2/RJ0036RA003.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
30697647          164.06   µg/m³ 2022-04-21 13:00:00
30700309          144.85   µg/m³ 2022-08-11 03:00:00
30697646          111.77   µg/m³ 2022-04-21 12:00:00
30698308           93.85   µg/m³ 2022-05-19 07:00:00
30699840           89.97   µg/m³ 2022-07-22 14:00:00
mma
             DATETIME     ANO  MES   DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2011-08-26 10:00:00  2011.0  8.0  26.0  10.0  20.05           20.05   µg/m³
1 2011-08-26 11:00:00  2011.0  8.0  26.0  11.0  20.00           20.00   µg/m³
2 2011-08-26 12:00:00  2011.0  8.0  26.0  12.0  15.38           15.38   µg/m³
3 2011-08-26 13:00:00  2011.0  8.0  26.0  13.0   6.75            6.75   µg/m³
4 2011-08-26 14:00:00  2011.0  8.0  26.0  14.0   6.92            6.92   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME     ANO  MES   DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2011-08-26 10:00:00  2011.0  8.0  26.0  10.0  20.05           20.05   µg/m³
1 2011-08-26 11:00:00  2011.0  8.0  26.0  11.0  20.00           20.00   µg/m³
2 2011-08-26 12:00:00  2011.0  8.0  26.0  12.0  15.38           15.38   µg/m³
3 2011-08-26 13:00:00  2011.0  8.0  26.0  13.0   6.75            6.75   µg/m³
4 2011-08-26 14:00:00  2011.0  8.0  26.0  14.0   6.92            6.92   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
003
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/SO2/RJ0081RA003.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
24933423        230.1129   ug/m3 2017-12-25 16:00:00
24933422        222.6221   ug/m3 2017-12-25 15:00:00
24931217        214.1531   ug/m3 2017-09-15 16:00:00
24931216        209.7250   ug/m3 2017-09-15 15:00:00
24933421        206.1388   ug/m3 2017-12-25 14:00:00
mma
             DATETIME     ANO  MES   DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2005-09-18 20:00:00  2005.0  9.0  18.0  20.0    NaN             NaN   µg/m³
1 2005-09-18 21:00:00  2005.0  9.0  18.0  21.0    NaN             NaN   µg/m³
2 2005-09-18 22:00:00  2005.0  9.0  18.0  22.0    NaN             NaN   µg/m³
3 2005-09-18 23:00:00  2005.0  9.0  18.0  23.0    NaN             NaN   µg/m³
4 2005-09-19 00:00:00  2005.0  9.0  19.0   0.0    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0         False     False
1         False     False
2         False     False
3         False     False
4         False     False
final
             DATETIME     ANO  MES   DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2005-09-18 20:00:00  2005.0  9.0  18.0  20.0    NaN             NaN   µg/m³
1 2005-09-18 21:00:00  2005.0  9.0  18.0  21.0    NaN             NaN   µg/m³
2 2005-09-18 22:00:00  2005.0  9.0  18.0  22.0    NaN             NaN   µg/m³
3 2005-09-18 23:00:00  2005.0  9.0  18.0  23.0    NaN             NaN   µg/m³
4 2005-09-19 00:00:00  2005.0  9.0  19.0   0.0    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
003
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/SO2/MG0012RA003.csv

/tmp/ipykernel_273420/1352582357.py:97: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  df_mma = pd.read_csv(arquivo, encoding = 'UTF-8')
/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
36437441          218.31   µg/m3 2018-05-12 10:30:00
36724324          208.21   µg/m3 2018-08-11 07:30:00
36437577          170.50   µg/m3 2018-05-12 11:30:00
35397693          164.20   µg/m3 2017-08-08 18:30:00
38029680          158.47   µg/m3 2021-08-10 17:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR VALOR_ORIGINAL UNIDADE  \
0 2014-01-01 01:00:00  2014    1    1     1    NaN              *     ppb
1 2014-01-01 02:00:00  2014    1    1     2    NaN              *     ppb
2 2014-01-01 03:00:00  2014    1    1     3    NaN              *     ppb
3 2014-01-01 04:00:00  2014    1    1     4    NaN              *     ppb
4 2014-01-01 05:00:00  2014    1    1     5    NaN              *     ppb

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR VALOR_ORIGINAL UNIDADE  \
0 2014-01-01 01:00:00  2014    1    1     1    NaN              *     ppb
1 2014-01-01 02:00:00  2014    1    1     2    NaN              *     ppb
2 2014-01-01 03:00:00  2014    1    1     3    NaN              *     ppb
3 2014-01-01 04:00:00  2014    1    1     4    NaN              *     ppb
4 2014-01-01 05:00:00  2014    1    1     5    NaN              *     ppb

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
003
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/SO2/BA0008ND003.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
         VALOR_ORIGINAL UNIDADE            DATETIME
5110738           671.5     ppb 2016-11-19 07:00:00
5110551           633.1     ppb 2016-11-11 12:00:00
5110737           472.0     ppb 2016-11-19 06:00:00
5103411           419.7     ppb 2016-01-12 06:00:00
5783018           377.3     ppb 2015-11-20 06:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1998-01-01 00:00:00  1998    1    1     0    NaN             NaN   ug/m³
1 1998-01-01 01:00:00  1998    1    1     1    NaN             NaN   ug/m³
2 1998-01-01 02:00:00  1998    1    1     2    NaN             NaN   ug/m³
3 1998-01-01 03:00:00  1998    1    1     3    NaN             NaN   ug/m³
4 1998-01-01 04:00:00  1998    1    1     4    NaN             NaN   ug/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1998-01-01 00:00:00  1998    1    1     0    NaN             NaN   ug/m³
1 1998-01-01 01:00:00  1998    1    1     1    NaN             NaN   ug/m³
2 1998-01-01 02:00:00  1998    1    1     2    NaN             NaN   ug/m³
3 1998-01-01 03:00:00  1998    1    1     3    NaN             NaN   ug/m³
4 1998-01-01 04:00:00  1998    1    1     4    NaN             NaN   ug/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
003
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/SO2/BA0007ND003.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
         VALOR_ORIGINAL UNIDADE            DATETIME
4982581           242.3     ppb 2016-07-07 08:00:00
4982582           211.6     ppb 2016-07-07 09:00:00
5736608           156.2     ppb 2015-05-07 08:00:00
4980934           144.4     ppb 2016-04-22 08:00:00
4980933           141.3     ppb 2016-04-22 07:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1998-01-01 00:00:00  1998    1    1     0    NaN             NaN   ug/m³
1 1998-01-01 01:00:00  1998    1    1     1    NaN             NaN   ug/m³
2 1998-01-01 02:00:00  1998    1    1     2    NaN             NaN   ug/m³
3 1998-01-01 03:00:00  1998    1    1     3    NaN             NaN   ug/m³
4 1998-01-01 04:00:00  1998    1    1     4    NaN             NaN   ug/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1998-01-01 00:00:00  1998    1    1     0    NaN             NaN   ug/m³
1 1998-01-01 01:00:00  1998    1    1     1    NaN             NaN   ug/m³
2 1998-01-01 02:00:00  1998    1    1     2    NaN             NaN   ug/m³
3 1998-01-01 03:00:00  1998    1    1     3    NaN             NaN   ug/m³
4 1998-01-01 04:00:00  1998    1    1     4    NaN             NaN   ug/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
003
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/SO2/RJ0019RA003.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
29386080          32.200     ppb 2016-02-05 10:30:00
29386079          28.300     ppb 2016-02-05 09:30:00
29386272          27.600     ppb 2016-02-13 10:30:00
29386273          25.699     ppb 2016-02-13 11:30:00
29386153          23.500     ppb 2016-02-08 11:30:00
mma
             DATETIME     ANO  MES   DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1999-04-24 00:00:00  1999.0  4.0  24.0   0.0    NaN            0.00   µg/m³
1 1999-04-24 01:00:00  1999.0  4.0  24.0   1.0   2.62            2.62   µg/m³
2 1999-04-24 02:00:00  1999.0  4.0  24.0   2.0   5.24            5.24   µg/m³
3 1999-04-24 03:00:00  1999.0  4.0  24.0   3.0   2.62            2.62   µg/m³
4 1999-04-24 04:00:00  1999.0  4.0  24.0   4.0   5.24            5.24   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME     ANO  MES   DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1999-04-24 00:00:00  1999.0  4.0  24.0   0.0    NaN            0.00   µg/m³
1 1999-04-24 01:00:00  1999.0  4.0  24.0   1.0   2.62            2.62   µg/m³
2 1999-04-24 02:00:00  1999.0  4.0  24.0   2.0   5.24            5.24   µg/m³
3 1999-04-24 03:00:00  1999.0  4.0  24.0   3.0   2.62            2.62   µg/m³
4 1999-04-24 04:00:00  1999.0  4.0  24.0   4.0   5.24            5.24   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True      True
2          True      True
3          True      True
4          True      True
003
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/SO2/CE0001ND003.csv
iema
         VALOR_ORIGINAL UNIDADE            DATETIME
4793200           448.0   ug/m3 2016-10-06 17:00:00
4793199           418.0   ug/m3 2016-10-06 16:00:00
4793849           401.0   ug/m3 2016-11-30 12:00:00
4792465           218.0   ug/m3 2016-08-25 20:00:00
4793201           212.0   ug/m3 2016-10-06 18:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2016-08-25 14:00:00  2016    8   25    14    NaN             NaN   µg/m³
1 2016-08-25 15:00:00  2016    8   25    15    NaN             NaN   µg/m³
2 2016-08-25 16:00:00  2016    8   25    16    NaN             NaN   µg/m³
3 2016-08-25 17:00:00  2016    8   25    17    NaN             NaN   µg/m³
4 2016-08-25 18:00:00  2016    8   25    18    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2016-08-25 14:00:00  2016    8   25    14   39.0            39.0   ug/m3
1 2016-08-25 15:00:00  2016    8   25    15   37.0            37.0   ug/m3
2 2016-08-25 16:00:00  2016    8   25    16   57.0            57.0   ug/m3
3 2016-08-25 17:00:00  2016    8   25    17   20.0            20.0   ug/m3
4 2016-08-25 18:00:00  2016    8   25    18   16.0            16.0   ug/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

003
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/SO2/BA0011ND003.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
         VALOR_ORIGINAL UNIDADE            DATETIME
4912544           312.7     ppb 2016-10-19 00:00:00
4910925           300.2     ppb 2016-08-12 03:00:00
4910993           284.0     ppb 2016-08-14 23:00:00
4910288           272.0     ppb 2016-07-16 08:00:00
4912543           256.6     ppb 2016-10-18 23:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1998-01-01 00:00:00  1998    1    1     0    NaN             NaN   ug/m³
1 1998-01-01 01:00:00  1998    1    1     1    NaN             NaN   ug/m³
2 1998-01-01 02:00:00  1998    1    1     2    NaN             NaN   ug/m³
3 1998-01-01 03:00:00  1998    1    1     3    NaN             NaN   ug/m³
4 1998-01-01 04:00:00  1998    1    1     4    NaN             NaN   ug/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1998-01-01 00:00:00  1998    1    1     0    NaN             NaN   ug/m³
1 1998-01-01 01:00:00  1998    1    1     1    NaN             NaN   ug/m³
2 1998-01-01 02:00:00  1998    1    1     2    NaN             NaN   ug/m³
3 1998-01-01 03:00:00  1998    1    1     3    NaN             NaN   ug/m³
4 1998-01-01 04:00:00  1998    1    1     4    NaN             NaN   ug/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
003
003
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/SO2/RJ0070RA003.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
31209488      257.467753   µg/m3 2020-04-03 16:00:00
31212071      171.111703   µg/m3 2020-04-04 05:00:00
24872910      156.171800   ug/m3 2017-10-11 13:00:00
24872911      148.517700   ug/m3 2017-10-11 14:00:00
31211866      144.356731   µg/m3 2020-04-04 04:00:00
mma
             DATETIME     ANO   MES   DIA  HORA  VALOR  VALOR_ORIGINAL  \
0 2000-12-17 12:00:00  2000.0  12.0  17.0  12.0    NaN             NaN
1 2000-12-17 13:00:00  2000.0  12.0  17.0  13.0    NaN             NaN
2 2000-12-17 14:00:00  2000.0  12.0  17.0  14.0    NaN             NaN
3 2000-12-17 15:00:00  2000.0  12.0  17.0  15.0  35.35           35.35
4 2000-12-17 16:00:00  2000.0  12.0  17.0  16.0  48.59           48.59

  UNIDADE  QAQC_INTERNO  QAQC_MMA
0   µg/m³         False     False
1   µg/m³         False     False
2   µg/m³         False     False
3   µg/m³          True      True
4   µg/m³          True      True
final
             DATETIME     ANO   MES   DIA  HORA  VALOR  VALOR_ORIGINAL  \
0 2000-12-17 12:00:00  2000.0  12.0  17.0  12.0    NaN             NaN
1 2000-12-17 13:00:00  2000.0  12.0  17.0  13.0    NaN             NaN
2 2000-12-17 14:00:00  2000.0  12.0  17.0  14.0    NaN             NaN
3 2000-12-17 15:00:00  2000.0  12.0  17.0  15.0  35.35           35.35
4 2000-12-17 16:00:00  2000.0  12.0  17.0  16.0  48.59           48.59

  UNIDADE  QAQC_INTERNO  QAQC_MMA
0   µg/m³          True     False
1   µg/m³          True     False
2   µg/m³          True     False
3   µg/m³          True      True
4   µg/m³          True      True
003
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/SO2/MG0017RA003.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
33532031           98.22   µg/m3 2015-06-09 10:30:00
37691360           83.66   µg/m3 2021-05-18 10:30:00
34911643           83.57   µg/m3 2019-11-11 21:30:00
33532776           83.43   µg/m3 2015-06-09 11:30:00
37214386           82.73   µg/m3 2021-01-08 22:30:00
mma
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2014-01-01 01:00:00  2014.0  1.0  1.0   1.0    NaN             NaN   µg/m3
1 2014-01-01 02:00:00  2014.0  1.0  1.0   2.0    NaN             NaN   µg/m3
2 2014-01-01 03:00:00  2014.0  1.0  1.0   3.0    NaN             NaN   µg/m3
3 2014-01-01 04:00:00  2014.0  1.0  1.0   4.0    NaN             NaN   µg/m3
4 2014-01-01 05:00:00  2014.0  1.0  1.0   5.0    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2014-01-01 01:00:00  2014.0  1.0  1.0   1.0    NaN             NaN   µg/m3
1 2014-01-01 02:00:00  2014.0  1.0  1.0   2.0    NaN             NaN   µg/m3
2 2014-01-01 03:00:00  2014.0  1.0  1.0   3.0    NaN             NaN   µg/m3
3 2014-01-01 04:00:00  2014.0  1.0  1.0   4.0    NaN             NaN   µg/m3
4 2014-01-01 05:00:00  2014.0  1.0  1.0   5.0    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
003
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/SO2/MG0010RA003.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
35615464          102.57   µg/m3 2017-11-28 16:30:00
34450903           99.90   µg/m3 2019-07-13 10:30:00
36662416           95.31   µg/m3 2018-07-22 12:30:00
36620758           85.93   µg/m3 2018-07-09 10:30:00
40445020           83.04   µg/m3 2016-06-20 11:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2014-01-01 01:00:00  2014    1    1     1   0.21            0.21   µg/m3
1 2014-01-01 02:00:00  2014    1    1     2   0.01            0.01   µg/m3
2 2014-01-01 03:00:00  2014    1    1     3   0.16            0.16   µg/m3
3 2014-01-01 04:00:00  2014    1    1     4   0.21            0.21   µg/m3
4 2014-01-01 05:00:00  2014    1    1     5   0.04            0.04   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2014-01-01 01:00:00  2014    1    1     1   0.21            0.21   µg/m3
1 2014-01-01 02:00:00  2014    1    1     2   0.01            0.01   µg/m3
2 2014-01-01 03:00:00  2014    1    1     3   0.16            0.16   µg/m3
3 2014-01-01 04:00:00  2014    1    1     4   0.21            0.21   µg/m3
4 2014-01-01 05:00:00  2014    1    1     5   0.04            0.04   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
003
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/SO2/RJ0038RA003.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
31208269      720.824700   µg/m3 2020-04-03 10:00:00
31208464      592.753653   µg/m3 2020-04-03 11:00:00
31208079      589.404952   µg/m3 2020-04-03 09:00:00
31207885      546.468360   µg/m3 2020-04-03 08:00:00
31238156      545.544405   µg/m3 2020-04-09 13:00:00
mma
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2009-01-02 01:00:00  2009.0  1.0  2.0   1.0   4.71            4.71   µg/m³
1 2009-01-02 02:00:00  2009.0  1.0  2.0   2.0   4.97            4.97   µg/m³
2 2009-01-02 03:00:00  2009.0  1.0  2.0   3.0   5.76            5.76   µg/m³
3 2009-01-02 04:00:00  2009.0  1.0  2.0   4.0   5.76            5.76   µg/m³
4 2009-01-02 05:00:00  2009.0  1.0  2.0   5.0   4.71            4.71   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2009-01-02 01:00:00  2009.0  1.0  2.0   1.0   4.71            4.71   µg/m³
1 2009-01-02 02:00:00  2009.0  1.0  2.0   2.0   4.97            4.97   µg/m³
2 2009-01-02 03:00:00  2009.0  1.0  2.0   3.0   5.76            5.76   µg/m³
3 2009-01-02 04:00:00  2009.0  1.0  2.0   4.0   5.76            5.76   µg/m³
4 2009-01-02 05:00:00  2009.0  1.0  2.0   5.0   4.71            4.71   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
003
003
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/SO2/RJ0057RA003.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
19576550      150.744204   µg/m3 2019-01-15 00:00:00
25418587      145.269900   ug/m3 2017-09-15 20:00:00
19576710      126.370663   µg/m3 2019-01-15 01:00:00
25417903      119.152700   ug/m3 2017-08-13 12:00:00
25419169      109.829200   ug/m3 2017-10-11 18:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2014-03-01 23:00:00  2014    3    1    23    NaN             NaN   µg/m³
1 2014-03-02 00:00:00  2014    3    2     0    NaN             NaN   µg/m³
2 2014-03-02 01:00:00  2014    3    2     1    NaN             NaN   µg/m³
3 2014-03-02 02:00:00  2014    3    2     2    NaN             NaN   µg/m³
4 2014-03-02 03:00:00  2014    3    2     3    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0         False     False
1         False     False
2         False     False
3         False     False
4         False     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2014-03-01 23:00:00  2014    3    1    23    NaN             NaN   µg/m³
1 2014-03-02 00:00:00  2014    3    2     0    NaN             NaN   µg/m³
2 2014-03-02 01:00:00  2014    3    2     1    NaN             NaN   µg/m³
3 2014-03-02 02:00:00  2014    3    2     2    NaN             NaN   µg/m³
4 2014-03-02 03:00:00  2014    3    2     3    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
003
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/SO2/RJ0027RA003.csv
iema
          VALOR_ORIGINAL UNIDADE            DATETIME
19635525      583.566197   µg/m3 2019-01-30 12:00:00
19635691      434.740528   µg/m3 2019-01-30 13:00:00
28604043      422.806339   µg/m3 2019-09-03 10:00:00
28448842      311.017914   µg/m3 2019-07-30 13:00:00
31592087      233.525235   µg/m3 2020-06-19 15:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2023-04-17 13:00:00  2023    4   17    13    NaN             NaN   µg/m³
1 2023-04-17 14:00:00  2023    4   17    14    NaN             NaN   µg/m³
2 2023-04-17 15:00:00  2023    4   17    15    NaN             NaN   µg/m³
3 2023-04-17 16:00:00  2023    4   17    16    NaN             NaN   µg/m³
4 2023-04-17 17:00:00  2023    4   17    17    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0         False     False
1         False     False
2         False     False
3         False     False
4         False     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2023-04-17 13:00:00  2023    4   17    13    NaN             NaN   µg/m³
1 2023-04-17 14:00:00  2023    4   17    14    NaN             NaN   µg/m³
2 2023-04-17 15:00:00  2023    4   17    15    NaN             NaN   µg/m³
3 2023-04-17 16:00:00  2023    4   17    16    NaN             NaN   µg/m³
4 2023-04-17 17:00:00  2023    4   17    17    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
003

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/SO2/RJ0078RA003.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
31100206     1013.295317   µg/m3 2020-03-11 10:00:00
31199814      812.337951   µg/m3 2020-04-01 16:00:00
31100402      526.374258   µg/m3 2020-03-11 11:00:00
31199615      523.965701   µg/m3 2020-04-01 15:00:00
30840676      297.063996   µg/m3 2020-01-14 13:00:00
mma
             DATETIME     ANO   MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1998-10-01 00:00:00  1998.0  10.0  1.0   0.0   5.63            5.63   µg/m³
1 1998-10-01 01:00:00  1998.0  10.0  1.0   1.0   2.95            2.95   µg/m³
2 1998-10-01 02:00:00  1998.0  10.0  1.0   2.0   4.56            4.56   µg/m³
3 1998-10-01 03:00:00  1998.0  10.0  1.0   3.0   4.56            4.56   µg/m³
4 1998-10-01 04:00:00  1998.0  10.0  1.0   4.0   4.83            4.83   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME     ANO   MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1998-10-01 00:00:00  1998.0  10.0  1.0   0.0   5.63            5.63   µg/m³
1 1998-10-01 01:00:00  1998.0  10.0  1.0   1.0   2.95            2.95   µg/m³
2 1998-10-01 02:00:00  1998.0  10.0  1.0   2.0   4.56            4.56   µg/m³
3 1998-10-01 03:00:00  1998.0  10.0  1.0   3.0   4.56            4.56   µg/m³
4 1998-10-01 04:00:00  1998.0  10.0  1.0   4.0   4.83            4.83   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
003
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/SO2/RJ0033RA003.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
31088081      975.687078   µg/m3 2020-03-08 20:00:00
25183845      542.680300   ug/m3 2017-10-31 12:00:00
25183844      531.324200   ug/m3 2017-10-31 11:00:00
25183843      510.151100   ug/m3 2017-10-31 10:00:00
31219849      473.511830   µg/m3 2020-04-05 19:00:00
mma
             DATETIME     ANO   MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2001-12-07 14:00:00  2001.0  12.0  7.0  14.0   1.89            1.89   µg/m³
1 2001-12-07 15:00:00  2001.0  12.0  7.0  15.0    NaN            0.00   µg/m³
2 2001-12-07 16:00:00  2001.0  12.0  7.0  16.0    NaN            0.00   µg/m³
3 2001-12-07 17:00:00  2001.0  12.0  7.0  17.0    NaN            0.00   µg/m³
4 2001-12-07 18:00:00  2001.0  12.0  7.0  18.0    NaN            0.00   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME     ANO   MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2001-12-07 14:00:00  2001.0  12.0  7.0  14.0   1.89            1.89   µg/m³
1 2001-12-07 15:00:00  2001.0  12.0  7.0  15.0    NaN            0.00   µg/m³
2 2001-12-07 16:00:00  2001.0  12.0  7.0  16.0    NaN            0.00   µg/m³
3 2001-12-07 17:00:00  2001.0  12.0  7.0  17.0    NaN            0.00   µg/m³
4 2001-12-07 18:00:00  2001.0  12.0  7.0  18.0    NaN            0.00   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True     False
2          True     False
3          True     False
4          True     False
003
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/SO2/BA0001ND003.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
         VALOR_ORIGINAL UNIDADE            DATETIME
4955173            60.1     ppb 2016-04-26 07:00:00
4952923            41.6     ppb 2016-01-23 08:00:00
5722255            33.8     ppb 2015-09-04 07:00:00
4955198            25.6     ppb 2016-04-27 08:00:00
4955197            19.8     ppb 2016-04-27 07:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1998-01-01 00:00:00  1998    1    1     0    NaN             NaN   ug/m³
1 1998-01-01 01:00:00  1998    1    1     1    NaN             NaN   ug/m³
2 1998-01-01 02:00:00  1998    1    1     2    NaN             NaN   ug/m³
3 1998-01-01 03:00:00  1998    1    1     3    NaN             NaN   ug/m³
4 1998-01-01 04:00:00  1998    1    1     4    NaN             NaN   ug/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1998-01-01 00:00:00  1998    1    1     0    NaN             NaN   ug/m³
1 1998-01-01 01:00:00  1998    1    1     1    NaN             NaN   ug/m³
2 1998-01-01 02:00:00  1998    1    1     2    NaN             NaN   ug/m³
3 1998-01-01 03:00:00  1998    1    1     3    NaN             NaN   ug/m³
4 1998-01-01 04:00:00  1998    1    1     4    NaN             NaN   ug/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
003
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/SO2/MG0013RA003.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
40499104          224.64   µg/m3 2016-05-31 10:30:00
40499112          207.68   µg/m3 2016-06-18 10:30:00
40499134          168.75   µg/m3 2016-06-01 10:30:00
40499160          150.37   µg/m3 2016-08-17 10:30:00
40499186          143.02   µg/m3 2016-08-02 10:30:00
mma
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2014-01-01 01:00:00  2014.0  1.0  1.0   1.0   2.25            2.25   µg/m3
1 2014-01-01 02:00:00  2014.0  1.0  1.0   2.0   0.95            0.95   µg/m3
2 2014-01-01 03:00:00  2014.0  1.0  1.0   3.0   0.72            0.72   µg/m3
3 2014-01-01 04:00:00  2014.0  1.0  1.0   4.0   0.08            0.08   µg/m3
4 2014-01-01 05:00:00  2014.0  1.0  1.0   5.0   0.49            0.49   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2014-01-01 01:00:00  2014.0  1.0  1.0   1.0   2.25            2.25   µg/m3
1 2014-01-01 02:00:00  2014.0  1.0  1.0   2.0   0.95            0.95   µg/m3
2 2014-01-01 03:00:00  2014.0  1.0  1.0   3.0   0.72            0.72   µg/m3
3 2014-01-01 04:00:00  2014.0  1.0  1.0   4.0   0.08            0.08   µg/m3
4 2014-01-01 05:00:00  2014.0  1.0  1.0   5.0   0.49            0.49   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
003
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/SO2/MG0004RA003.csv

/tmp/ipykernel_273420/1352582357.py:97: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  df_mma = pd.read_csv(arquivo, encoding = 'UTF-8')
/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
37999700           948.4   µg/m3 2021-08-03 11:30:00
37947099           836.6   µg/m3 2021-07-21 13:30:00
37991996           830.2   µg/m3 2021-08-01 14:30:00
38037383           782.7   µg/m3 2021-08-12 14:30:00
37859906           756.6   µg/m3 2021-06-30 12:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR VALOR_ORIGINAL UNIDADE  \
0 2009-01-01 01:00:00  2009    1    1     1    1.3            1.3     ppb
1 2009-01-01 02:00:00  2009    1    1     2   12.0             12     ppb
2 2009-01-01 03:00:00  2009    1    1     3   15.3           15.3     ppb
3 2009-01-01 04:00:00  2009    1    1     4    7.5            7.5     ppb
4 2009-01-01 05:00:00  2009    1    1     5    3.3            3.3     ppb

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR VALOR_ORIGINAL UNIDADE  \
0 2009-01-01 01:00:00  2009    1    1     1    1.3            1.3     ppb
1 2009-01-01 02:00:00  2009    1    1     2   12.0             12     ppb
2 2009-01-01 03:00:00  2009    1    1     3   15.3           15.3     ppb
3 2009-01-01 04:00:00  2009    1    1     4    7.5            7.5     ppb
4 2009-01-01 05:00:00  2009    1    1     5    3.3            3.3     ppb

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
003
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/SO2/RJ0031RA003.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
25057235      488.953400   ug/m3 2017-07-21 14:00:00
25057233      469.298400   ug/m3 2017-07-21 13:00:00
29135519      403.350557   µg/m3 2019-12-27 18:00:00
20979241      397.384000     ppb 2016-08-25 11:30:00
20979240      394.731000     ppb 2016-08-25 10:30:00
mma
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2004-03-01 12:00:00  2004.0  3.0  1.0  12.0    NaN             NaN   µg/m³
1 2004-03-01 13:00:00  2004.0  3.0  1.0  13.0    NaN             NaN   µg/m³
2 2004-03-01 14:00:00  2004.0  3.0  1.0  14.0    NaN             NaN   µg/m³
3 2004-03-01 15:00:00  2004.0  3.0  1.0  15.0    NaN             NaN   µg/m³
4 2004-03-01 16:00:00  2004.0  3.0  1.0  16.0    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0         False     False
1         False     False
2         False     False
3         False     False
4         False     False
final
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2004-03-01 12:00:00  2004.0  3.0  1.0  12.0    NaN             NaN   µg/m³
1 2004-03-01 13:00:00  2004.0  3.0  1.0  13.0    NaN             NaN   µg/m³
2 2004-03-01 14:00:00  2004.0  3.0  1.0  14.0    NaN             NaN   µg/m³
3 2004-03-01 15:00:00  2004.0  3.0  1.0  15.0    NaN             NaN   µg/m³
4 2004-03-01 16:00:00  2004.0  3.0  1.0  16.0    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
003
003
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/SO2/RJ0064RA003.csv
iema
          VALOR_ORIGINAL UNIDADE            DATETIME
26232574          114.87   µg/m³ 2021-12-15 07:00:00
26232575          102.05   µg/m³ 2021-12-15 08:00:00
30459684           88.86   µg/m³ 2022-07-25 14:00:00
26230736           76.68   µg/m³ 2021-09-29 13:00:00
26229161           62.20   µg/m³ 2021-07-25 10:00:00
mma
             DATETIME     ANO  MES   DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2021-05-18 10:00:00  2021.0  5.0  18.0  10.0    NaN             NaN   µg/m³
1 2021-05-18 11:00:00  2021.0  5.0  18.0  11.0   2.23            2.23   µg/m³
2 2021-05-18 12:00:00  2021.0  5.0  18.0  12.0    NaN             NaN   µg/m³
3 2021-05-18 13:00:00  2021.0  5.0  18.0  13.0    NaN             NaN   µg/m³
4 2021-05-18 14:00:00  2021.0  5.0  18.0  14.0    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0         False     False
1          True      True
2         False     False
3         False     False
4         False     False
final
             DATETIME     ANO  MES   DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2021-05-18 10:00:00  2021.0  5.0  18.0  10.0    NaN             NaN   µg/m³
1 2021-05-18 11:00:00  2021.0  5.0  18.0  11.0   2.23            2.23   µg/m³
2 2021-05-18 12:00:00  2021.0  5.0  18.0  12.0    NaN             NaN   µg/m³
3 2021-05-18 13:00:00  2021.0  5.0  18.0  13.0    NaN             NaN   µg/m³
4 2021-05-18 14:00:00  2021.0  5.0  18.0  14.0    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True      True
2          True     False
3          True     False
4          True     False

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

003
003
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/SO2/RJ0030RA003.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
25019687      565.647900   ug/m3 2017-10-13 17:00:00
20237241      545.600887   µg/m3 2019-06-25 13:00:00
25016667      534.704100   ug/m3 2017-05-24 12:00:00
20130693      514.305433   µg/m3 2019-05-31 10:00:00
25018137      508.485500   ug/m3 2017-07-30 10:00:00
mma
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1998-03-01 00:00:00  1998.0  3.0  1.0   0.0    NaN             NaN   µg/m³
1 1998-03-01 01:00:00  1998.0  3.0  1.0   1.0    NaN             NaN   µg/m³
2 1998-03-01 02:00:00  1998.0  3.0  1.0   2.0    NaN             NaN   µg/m³
3 1998-03-01 03:00:00  1998.0  3.0  1.0   3.0    NaN             NaN   µg/m³
4 1998-03-01 04:00:00  1998.0  3.0  1.0   4.0    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0         False     False
1         False     False
2         False     False
3         False     False
4         False     False
final
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1998-03-01 00:00:00  1998.0  3.0  1.0   0.0    NaN             NaN   µg/m³
1 1998-03-01 01:00:00  1998.0  3.0  1.0   1.0    NaN             NaN   µg/m³
2 1998-03-01 02:00:00  1998.0  3.0  1.0   2.0    NaN             NaN   µg/m³
3 1998-03-01 03:00:00  1998.0  3.0  1.0   3.0    NaN             NaN   µg/m³
4 1998-03-01 04:00:00  1998.0  3.0  1.0   4.0    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
003
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/SO2/RJ0029RA003.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
31301952      369.425403   µg/m3 2020-04-22 11:00:00
20092453      129.486078   µg/m3 2019-05-22 12:00:00
31301747      113.123603   µg/m3 2020-04-22 10:00:00
28780138      108.594470   µg/m3 2019-10-12 13:00:00
28644458      108.280311   µg/m3 2019-09-12 15:00:00
mma
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2011-05-01 00:00:00  2011.0  5.0  1.0   0.0  20.95           20.95   µg/m³
1 2011-05-01 01:00:00  2011.0  5.0  1.0   1.0  18.33           18.33   µg/m³
2 2011-05-01 02:00:00  2011.0  5.0  1.0   2.0  18.33           18.33   µg/m³
3 2011-05-01 03:00:00  2011.0  5.0  1.0   3.0  18.33           18.33   µg/m³
4 2011-05-01 04:00:00  2011.0  5.0  1.0   4.0  18.33           18.33   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2011-05-01 00:00:00  2011.0  5.0  1.0   0.0  20.95           20.95   µg/m³
1 2011-05-01 01:00:00  2011.0  5.0  1.0   1.0  18.33           18.33   µg/m³
2 2011-05-01 02:00:00  2011.0  5.0  1.0   2.0  18.33           18.33   µg/m³
3 2011-05-01 03:00:00  2011.0  5.0  1.0   3.0  18.33           18.33   µg/m³
4 2011-05-01 04:00:00  2011.0  5.0  1.0   4.0  18.33           18.33   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
003
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/SO2/MG0003RA003.csv

/tmp/ipykernel_273420/1352582357.py:97: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  df_mma = pd.read_csv(arquivo, encoding = 'UTF-8')
/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
32305124          936.78   µg/m3 2020-06-29 14:30:00
32042387          680.55   µg/m3 2020-04-16 07:30:00
38448542          645.68   µg/m3 2021-11-27 11:30:00
32132730          550.13   µg/m3 2020-05-12 07:30:00
38514009          529.44   µg/m3 2021-12-14 09:30:00
mma
             DATETIME     ANO  MES  DIA  HORA  VALOR VALOR_ORIGINAL UNIDADE  \
0 2009-01-01 01:00:00  2009.0  1.0  1.0   1.0    NaN              *     ppb
1 2009-01-01 02:00:00  2009.0  1.0  1.0   2.0    NaN              *     ppb
2 2009-01-01 03:00:00  2009.0  1.0  1.0   3.0    NaN              *     ppb
3 2009-01-01 04:00:00  2009.0  1.0  1.0   4.0    NaN              *     ppb
4 2009-01-01 05:00:00  2009.0  1.0  1.0   5.0    NaN              *     ppb

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME     ANO  MES  DIA  HORA  VALOR VALOR_ORIGINAL UNIDADE  \
0 2009-01-01 01:00:00  2009.0  1.0  1.0   1.0    NaN              *     ppb
1 2009-01-01 02:00:00  2009.0  1.0  1.0   2.0    NaN              *     ppb
2 2009-01-01 03:00:00  2009.0  1.0  1.0   3.0    NaN              *     ppb
3 2009-01-01 04:00:00  2009.0  1.0  1.0   4.0    NaN              *     ppb
4 2009-01-01 05:00:00  2009.0  1.0  1.0   5.0    NaN              *     ppb

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
003
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/SO2/RJ0039RA003.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
31332521     2598.361064   µg/m3 2020-04-28 15:00:00
31333205     2562.727229   µg/m3 2020-04-28 19:00:00
28939469     2543.095047   µg/m3 2019-11-15 06:00:00
31332855     2543.092259   µg/m3 2020-04-28 17:00:00
31332350     2525.638952   µg/m3 2020-04-28 14:00:00
mma
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2007-02-01 00:00:00  2007.0  2.0  1.0   0.0    NaN             0.0   µg/m³
1 2007-02-01 01:00:00  2007.0  2.0  1.0   1.0    NaN             0.0   µg/m³
2 2007-02-01 02:00:00  2007.0  2.0  1.0   2.0    NaN             0.0   µg/m³
3 2007-02-01 03:00:00  2007.0  2.0  1.0   3.0    NaN             0.0   µg/m³
4 2007-02-01 04:00:00  2007.0  2.0  1.0   4.0    NaN             0.0   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2007-02-01 00:00:00  2007.0  2.0  1.0   0.0    NaN             0.0   µg/m³
1 2007-02-01 01:00:00  2007.0  2.0  1.0   1.0    NaN             0.0   µg/m³
2 2007-02-01 02:00:00  2007.0  2.0  1.0   2.0    NaN             0.0   µg/m³
3 2007-02-01 03:00:00  2007.0  2.0  1.0   3.0    NaN             0.0   µg/m³
4 2007-02-01 04:00:00  2007.0  2.0  1.0   4.0    NaN             0.0   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
003
003
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/SO2/BA0004ND003.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
         VALOR_ORIGINAL UNIDADE            DATETIME
5772117           856.0     ppb 2015-08-01 21:00:00
5770234           267.5     ppb 2015-05-07 08:00:00
5773340           204.7     ppb 2015-09-22 08:00:00
5772128           201.5     ppb 2015-08-02 08:00:00
5772299           192.8     ppb 2015-08-09 11:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1998-01-01 00:00:00  1998    1    1     0    NaN             NaN   ug/m³
1 1998-01-01 01:00:00  1998    1    1     1    NaN             NaN   ug/m³
2 1998-01-01 02:00:00  1998    1    1     2    NaN             NaN   ug/m³
3 1998-01-01 03:00:00  1998    1    1     3    NaN             NaN   ug/m³
4 1998-01-01 04:00:00  1998    1    1     4    NaN             NaN   ug/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1998-01-01 00:00:00  1998    1    1     0    NaN             NaN   ug/m³
1 1998-01-01 01:00:00  1998    1    1     1    NaN             NaN   ug/m³
2 1998-01-01 02:00:00  1998    1    1     2    NaN             NaN   ug/m³
3 1998-01-01 03:00:00  1998    1    1     3    NaN             NaN   ug/m³
4 1998-01-01 04:00:00  1998    1    1     4    NaN             NaN   ug/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
003
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/SO2/MG0053RA003.csv
iema
          VALOR_ORIGINAL UNIDADE            DATETIME
34939449          201.88   µg/m3 2019-11-19 17:30:00
39388615          187.74   µg/m3 2022-08-19 05:30:00
36577947          182.82   µg/m3 2018-06-25 23:30:00
39388464          176.56   µg/m3 2022-08-19 04:30:00
39283508          174.64   µg/m3 2022-07-21 22:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2018-01-01 01:00:00  2018    1    1     1    NaN             NaN   µg/m3
1 2018-01-01 02:00:00  2018    1    1     2    NaN             NaN   µg/m3
2 2018-01-01 03:00:00  2018    1    1     3    NaN             NaN   µg/m3
3 2018-01-01 04:00:00  2018    1    1     4    NaN             NaN   µg/m3
4 2018-01-01 05:00:00  2018    1    1     5    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2018-01-01 01:00:00  2018    1    1     1    NaN             NaN   µg/m3
1 2018-01-01 02:00:00  2018    1    1     2    NaN             NaN   µg/m3
2 2018-01-01 03:00:00  2018    1    1     3    NaN             NaN   µg/m3
3 2018-01-01 04:00:00  2018    1    1     4    NaN             NaN   µg/m3
4 2018-01-01 05:00:00  2018    1    1     5    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

003
003
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/SO2/SP0280RA003.csv
iema
          VALOR_ORIGINAL UNIDADE            DATETIME
7547720             20.0   ug/m3 2017-06-10 16:00:00
12300615            18.0   ug/m3 2016-07-07 12:00:00
12300616            16.0   ug/m3 2016-07-07 13:00:00
7547767             16.0   ug/m3 2017-06-12 17:00:00
15501710            16.0   ug/m3 2018-06-08 12:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2015-10-01 01:00:00  2015   10    1     1    1.0             1.0   µg/m3
1 2015-10-01 02:00:00  2015   10    1     2    1.0             1.0   µg/m3
2 2015-10-01 03:00:00  2015   10    1     3    NaN             0.0   µg/m3
3 2015-10-01 04:00:00  2015   10    1     4    NaN             NaN     NaN
4 2015-10-01 05:00:00  2015   10    1     5    1.0             1.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True     False
3          True     False
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2015-10-01 01:00:00  2015   10    1     1    1.0             1.0   ug/m3
1 2015-10-01 02:00:00  2015   10    1     2    1.0             1.0   ug/m3
2 2015-10-01 03:00:00  2015   10    1     3    NaN             0.0   ug/m3
3 2015-10-01 04:00:00  2015   10    1     4    NaN             NaN     NaN
4 2015-10-01 05:00:00  2015   10    1     5    1.0             1.0   ug/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True     False
3          True     False
4          True      True

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

003
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/SO2/SP0117RA003.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
11752052           263.0   ug/m3 2016-06-13 01:00:00
14883383           178.0   ug/m3 2018-03-22 13:00:00
17299839           165.0   ug/m3 2015-05-02 03:00:00
10190808           136.0   ug/m3 2020-01-27 10:00:00
14885391           131.0   ug/m3 2018-06-20 12:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2000-03-01 18:00:00  2000    3    1    18   16.0            16.0   µg/m3
1 2000-03-01 19:00:00  2000    3    1    19   15.0            15.0   µg/m3
2 2000-03-01 20:00:00  2000    3    1    20   15.0            15.0   µg/m3
3 2000-03-01 21:00:00  2000    3    1    21   15.0            15.0   µg/m3
4 2000-03-01 22:00:00  2000    3    1    22   15.0            15.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2000-03-01 18:00:00  2000    3    1    18   16.0            16.0   µg/m3
1 2000-03-01 19:00:00  2000    3    1    19   15.0            15.0   µg/m3
2 2000-03-01 20:00:00  2000    3    1    20   15.0            15.0   µg/m3
3 2000-03-01 21:00:00  2000    3    1    21   15.0            15.0   µg/m3
4 2000-03-01 22:00:00  2000    3    1    22   15.0            15.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
003
003
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/SO2/RJ0026RA003.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
28608803     1441.468548   µg/m3 2019-09-04 13:00:00
20282439      456.578487   µg/m3 2019-07-05 16:00:00
19627946      361.864972   µg/m3 2019-01-28 16:00:00
19627774      356.285936   µg/m3 2019-01-28 15:00:00
19955225      325.940491   µg/m3 2019-04-18 13:00:00
mma
             DATETIME     ANO  MES   DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2006-07-21 00:00:00  2006.0  7.0  21.0   0.0    NaN             NaN   µg/m³
1 2006-07-21 01:00:00  2006.0  7.0  21.0   1.0    NaN             NaN   µg/m³
2 2006-07-21 02:00:00  2006.0  7.0  21.0   2.0    NaN             NaN   µg/m³
3 2006-07-21 03:00:00  2006.0  7.0  21.0   3.0    NaN             NaN   µg/m³
4 2006-07-21 04:00:00  2006.0  7.0  21.0   4.0    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0         False     False
1         False     False
2         False     False
3         False     False
4         False     False
final
             DATETIME     ANO  MES   DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2006-07-21 00:00:00  2006.0  7.0  21.0   0.0    NaN             NaN   µg/m³
1 2006-07-21 01:00:00  2006.0  7.0  21.0   1.0    NaN             NaN   µg/m³
2 2006-07-21 02:00:00  2006.0  7.0  21.0   2.0    NaN             NaN   µg/m³
3 2006-07-21 03:00:00  2006.0  7.0  21.0   3.0    NaN             NaN   µg/m³
4 2006-07-21 04:00:00  2006.0  7.0  21.0   4.0    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
003
003
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/SO2/MG0005RA003.csv

/tmp/ipykernel_273420/1352582357.py:97: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  df_mma = pd.read_csv(arquivo, encoding = 'UTF-8')
/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
32119851          876.59   µg/m3 2020-05-08 14:30:00
32504240          634.21   µg/m3 2020-08-25 13:30:00
37569310          571.35   µg/m3 2021-04-16 12:30:00
32832884          446.95   µg/m3 2020-11-25 12:30:00
32504388          425.63   µg/m3 2020-08-25 14:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR VALOR_ORIGINAL UNIDADE  \
0 2009-01-01 01:00:00  2009    1    1     1    NaN              *     ppb
1 2009-01-01 02:00:00  2009    1    1     2    NaN              *     ppb
2 2009-01-01 03:00:00  2009    1    1     3    NaN              *     ppb
3 2009-01-01 04:00:00  2009    1    1     4    NaN              *     ppb
4 2009-01-01 05:00:00  2009    1    1     5    NaN              *     ppb

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR VALOR_ORIGINAL UNIDADE  \
0 2009-01-01 01:00:00  2009    1    1     1    NaN              *     ppb
1 2009-01-01 02:00:00  2009    1    1     2    NaN              *     ppb
2 2009-01-01 03:00:00  2009    1    1     3    NaN              *     ppb
3 2009-01-01 04:00:00  2009    1    1     4    NaN              *     ppb
4 2009-01-01 05:00:00  2009    1    1     5    NaN              *     ppb

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
003
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/SO2/RJ0060RA003.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
23479621      374.115200   µg/m3 2020-07-22 15:00:00
23479410      231.081000   µg/m3 2020-07-22 14:00:00
24268498       86.656160   µg/m3 2020-12-28 13:00:00
30817636       58.560322   µg/m3 2020-01-09 12:00:00
24213321       54.579000   µg/m3 2020-12-16 20:00:00
mma
             DATETIME     ANO   MES   DIA  HORA  VALOR  VALOR_ORIGINAL  \
0 2008-12-15 00:00:00  2008.0  12.0  15.0   0.0    NaN             NaN
1 2008-12-15 01:00:00  2008.0  12.0  15.0   1.0    NaN             NaN
2 2008-12-15 02:00:00  2008.0  12.0  15.0   2.0    NaN             NaN
3 2008-12-15 03:00:00  2008.0  12.0  15.0   3.0    NaN             NaN
4 2008-12-15 04:00:00  2008.0  12.0  15.0   4.0    NaN             NaN

  UNIDADE  QAQC_INTERNO  QAQC_MMA
0   µg/m³         False     False
1   µg/m³         False     False
2   µg/m³         False     False
3   µg/m³         False     False
4   µg/m³         False     False
final
             DATETIME     ANO   MES   DIA  HORA  VALOR  VALOR_ORIGINAL  \
0 2008-12-15 00:00:00  2008.0  12.0  15.0   0.0    NaN             NaN
1 2008-12-15 01:00:00  2008.0  12.0  15.0   1.0    NaN             NaN
2 2008-12-15 02:00:00  2008.0  12.0  15.0   2.0    NaN             NaN
3 2008-12-15 03:00:00  2008.0  12.0  15.0   3.0    NaN             NaN
4 2008-12-15 04:00:00  2008.0  12.0  15.0   4.0    NaN             NaN

  UNIDADE  QAQC_INTERNO  QAQC_MMA
0   µg/m³          True     False
1   µg/m³          True     False
2   µg/m³          True     False
3   µg/m³          True     False
4   µg/m³          True     False
003
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/SO2/RJ0034RA003.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
28416818     1021.084845   µg/m3 2019-07-23 14:00:00
28416630      693.855763   µg/m3 2019-07-23 13:00:00
20170684      690.281597   µg/m3 2019-06-09 18:00:00
20170503      618.836367   µg/m3 2019-06-09 17:00:00
20113833      579.400126   µg/m3 2019-05-27 11:00:00
mma
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2004-03-01 12:00:00  2004.0  3.0  1.0  12.0    NaN             NaN   µg/m³
1 2004-03-01 13:00:00  2004.0  3.0  1.0  13.0    NaN             NaN   µg/m³
2 2004-03-01 14:00:00  2004.0  3.0  1.0  14.0    NaN             NaN   µg/m³
3 2004-03-01 15:00:00  2004.0  3.0  1.0  15.0    NaN             NaN   µg/m³
4 2004-03-01 16:00:00  2004.0  3.0  1.0  16.0    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0         False     False
1         False     False
2         False     False
3         False     False
4         False     False
final
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2004-03-01 12:00:00  2004.0  3.0  1.0  12.0    NaN             NaN   µg/m³
1 2004-03-01 13:00:00  2004.0  3.0  1.0  13.0    NaN             NaN   µg/m³
2 2004-03-01 14:00:00  2004.0  3.0  1.0  14.0    NaN             NaN   µg/m³
3 2004-03-01 15:00:00  2004.0  3.0  1.0  15.0    NaN             NaN   µg/m³
4 2004-03-01 16:00:00  2004.0  3.0  1.0  16.0    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
003
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/SO2/SP0073RA003.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
19114602            50.0   ug/m3 2015-08-23 05:00:00
19114604            46.0   ug/m3 2015-08-23 07:00:00
19109579            43.0   ug/m3 2015-01-05 21:00:00
19114605            42.0   ug/m3 2015-08-23 08:00:00
19114606            41.0   ug/m3 2015-08-23 09:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1998-01-01 02:00:00  1998    1    1     2    2.0             2.0   µg/m3
1 1998-01-01 03:00:00  1998    1    1     3    3.0             3.0   µg/m3
2 1998-01-01 04:00:00  1998    1    1     4    3.0             3.0   µg/m3
3 1998-01-01 05:00:00  1998    1    1     5    3.0             3.0   µg/m3
4 1998-01-01 06:00:00  1998    1    1     6    3.0             3.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1998-01-01 02:00:00  1998    1    1     2    2.0             2.0   µg/m3
1 1998-01-01 03:00:00  1998    1    1     3    3.0             3.0   µg/m3
2 1998-01-01 04:00:00  1998    1    1     4    3.0             3.0   µg/m3
3 1998-01-01 05:00:00  1998    1    1     5    3.0             3.0   µg/m3
4 1998-01-01 06:00:00  1998    1    1     6    3.0             3.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
003
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/SO2/RJ0058RA003.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
19689455      264.417587   µg/m3 2019-02-12 15:00:00
19582531      264.365227   µg/m3 2019-01-16 14:00:00
23398173      259.935100   µg/m3 2020-07-06 15:00:00
30973431      256.460188   µg/m3 2020-02-12 15:00:00
31499732      218.006193   µg/m3 2020-06-01 14:00:00
mma
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2008-07-01 00:00:00  2008.0  7.0  1.0   0.0   0.06            0.06   µg/m³
1 2008-07-01 01:00:00  2008.0  7.0  1.0   1.0    NaN             NaN   µg/m³
2 2008-07-01 02:00:00  2008.0  7.0  1.0   2.0    NaN             NaN   µg/m³
3 2008-07-01 03:00:00  2008.0  7.0  1.0   3.0    NaN             NaN   µg/m³
4 2008-07-01 04:00:00  2008.0  7.0  1.0   4.0    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1         False     False
2         False     False
3         False     False
4         False     False
final
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2008-07-01 00:00:00  2008.0  7.0  1.0   0.0   0.06            0.06   µg/m³
1 2008-07-01 01:00:00  2008.0  7.0  1.0   1.0    NaN             NaN   µg/m³
2 2008-07-01 02:00:00  2008.0  7.0  1.0   2.0    NaN             NaN   µg/m³
3 2008-07-01 03:00:00  2008.0  7.0  1.0   3.0    NaN             NaN   µg/m³
4 2008-07-01 04:00:00  2008.0  7.0  1.0   4.0    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True     False
2          True     False
3          True     False
4          True     False
003
003
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/SO2/RJ0071RA003.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
31331363      258.529132   µg/m3 2020-04-28 09:00:00
31331570      250.556316   µg/m3 2020-04-28 10:00:00
31367202      231.454685   µg/m3 2020-05-05 12:00:00
31366989      208.715434   µg/m3 2020-05-05 11:00:00
31341490      192.368449   µg/m3 2020-04-30 10:00:00
mma
             DATETIME     ANO   MES   DIA  HORA  VALOR  VALOR_ORIGINAL  \
0 2000-12-21 06:00:00  2000.0  12.0  21.0   6.0   2.16            2.16
1 2000-12-21 07:00:00  2000.0  12.0  21.0   7.0    NaN            0.00
2 2000-12-21 08:00:00  2000.0  12.0  21.0   8.0   1.39            1.39
3 2000-12-21 09:00:00  2000.0  12.0  21.0   9.0   1.77            1.77
4 2000-12-21 10:00:00  2000.0  12.0  21.0  10.0   2.01            2.01

  UNIDADE  QAQC_INTERNO  QAQC_MMA
0   µg/m³          True      True
1   µg/m³          True     False
2   µg/m³          True      True
3   µg/m³          True      True
4   µg/m³          True      True
final
             DATETIME     ANO   MES   DIA  HORA  VALOR  VALOR_ORIGINAL  \
0 2000-12-21 06:00:00  2000.0  12.0  21.0   6.0   2.16            2.16
1 2000-12-21 07:00:00  2000.0  12.0  21.0   7.0    NaN            0.00
2 2000-12-21 08:00:00  2000.0  12.0  21.0   8.0   1.39            1.39
3 2000-12-21 09:00:00  2000.0  12.0  21.0   9.0   1.77            1.77
4 2000-12-21 10:00:00  2000.0  12.0  21.0  10.0   2.01            2.01

  UNIDADE  QAQC_INTERNO  QAQC_MMA
0   µg/m³          True      True
1   µg/m³          True     False
2   µg/m³          True      True
3   µg/m³          True      True
4   µg/m³          True      True
003
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/SO2/RJ0069RA003.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
28526199      161.335307   µg/m3 2019-08-16 20:00:00
24832451      160.494600   ug/m3 2017-09-06 10:00:00
28525812      146.345608   µg/m3 2019-08-16 18:00:00
28526005      112.634766   µg/m3 2019-08-16 19:00:00
24832452      111.166200   ug/m3 2017-09-06 11:00:00
mma
             DATETIME     ANO   MES   DIA  HORA  VALOR  VALOR_ORIGINAL  \
0 2000-12-19 07:00:00  2000.0  12.0  19.0   7.0   0.31            0.31
1 2000-12-19 08:00:00  2000.0  12.0  19.0   8.0   1.66            1.66
2 2000-12-19 09:00:00  2000.0  12.0  19.0   9.0   2.60            2.60
3 2000-12-19 10:00:00  2000.0  12.0  19.0  10.0    NaN             NaN
4 2000-12-19 11:00:00  2000.0  12.0  19.0  11.0   1.39            1.39

  UNIDADE  QAQC_INTERNO  QAQC_MMA
0   µg/m³          True      True
1   µg/m³          True      True
2   µg/m³          True      True
3   µg/m³         False     False
4   µg/m³          True      True
final
             DATETIME     ANO   MES   DIA  HORA  VALOR  VALOR_ORIGINAL  \
0 2000-12-19 07:00:00  2000.0  12.0  19.0   7.0   0.31            0.31
1 2000-12-19 08:00:00  2000.0  12.0  19.0   8.0   1.66            1.66
2 2000-12-19 09:00:00  2000.0  12.0  19.0   9.0   2.60            2.60
3 2000-12-19 10:00:00  2000.0  12.0  19.0  10.0    NaN             NaN
4 2000-12-19 11:00:00  2000.0  12.0  19.0  11.0   1.39            1.39

  UNIDADE  QAQC_INTERNO  QAQC_MMA
0   µg/m³          True      True
1   µg/m³          True      True
2   µg/m³          True      True
3   µg/m³          True     False
4   µg/m³          True      True
003
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/SO2/BA0003ND003.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
         VALOR_ORIGINAL UNIDADE            DATETIME
5046105           229.0     ppb 2016-01-23 08:00:00
5045911           139.1     ppb 2016-01-15 06:00:00
5048663           139.0     ppb 2016-05-12 08:00:00
5048281           128.3     ppb 2016-04-26 07:00:00
5046104            93.7     ppb 2016-01-23 07:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1998-01-01 00:00:00  1998    1    1     0    NaN             NaN   ug/m³
1 1998-01-01 01:00:00  1998    1    1     1    NaN             NaN   ug/m³
2 1998-01-01 02:00:00  1998    1    1     2    NaN             NaN   ug/m³
3 1998-01-01 03:00:00  1998    1    1     3    NaN             NaN   ug/m³
4 1998-01-01 04:00:00  1998    1    1     4    NaN             NaN   ug/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1998-01-01 00:00:00  1998    1    1     0    NaN             NaN   ug/m³
1 1998-01-01 01:00:00  1998    1    1     1    NaN             NaN   ug/m³
2 1998-01-01 02:00:00  1998    1    1     2    NaN             NaN   ug/m³
3 1998-01-01 03:00:00  1998    1    1     3    NaN             NaN   ug/m³
4 1998-01-01 04:00:00  1998    1    1     4    NaN             NaN   ug/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
003
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/SO2/BA0010ND003.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
         VALOR_ORIGINAL UNIDADE            DATETIME
4883742           150.8     ppb 2016-12-05 05:00:00
4880402           130.3     ppb 2016-07-18 03:00:00
4883741            99.5     ppb 2016-12-05 04:00:00
4878512            78.2     ppb 2016-04-27 08:00:00
4883240            70.9     ppb 2016-11-14 07:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1998-01-01 00:00:00  1998    1    1     0    NaN             NaN   ug/m³
1 1998-01-01 01:00:00  1998    1    1     1    NaN             NaN   ug/m³
2 1998-01-01 02:00:00  1998    1    1     2    NaN             NaN   ug/m³
3 1998-01-01 03:00:00  1998    1    1     3    NaN             NaN   ug/m³
4 1998-01-01 04:00:00  1998    1    1     4    NaN             NaN   ug/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1998-01-01 00:00:00  1998    1    1     0    NaN             NaN   ug/m³
1 1998-01-01 01:00:00  1998    1    1     1    NaN             NaN   ug/m³
2 1998-01-01 02:00:00  1998    1    1     2    NaN             NaN   ug/m³
3 1998-01-01 03:00:00  1998    1    1     3    NaN             NaN   ug/m³
4 1998-01-01 04:00:00  1998    1    1     4    NaN             NaN   ug/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
PTS
['MG0015', 'PR0009 ', 'MG0042', 'RJ0074', 'PR0006 ', 'MG0054', 'PR0005 ', 'MG0036', 'RJ0048', 'MG0009', 'RJ0037', 'RJ0086', 'SP0091', 'RJ0073', nan, 'MG0039', 'MG0032', 'RJ0067', 'MG0040', 'RJ0063', 'RJ0043', 'PR0003 ', 'SP0120', 'MG0011', 'MG0028', 'RJ0036', 'RJ0081', 'MG0016', 'PR0011 ', 'MG0058', 'MG0014', 'SP0083', 'MG0038', 'MG0021', 'RJ0070', 'MG0017', 'MG0010', 'PR0014 ', 'RJ0038', 'MG0020', 'RJ0051', 'MG0044', 'PR0004 ', 'MG0056', 'RJ0076', 'MG0013', 'MG0034', 'PR0015 ', 'RJ0064', 'RJ0068', 'MG0047', 'MG0055', 'PR0008 ', 'RJ0054', 'RJ0077', 'RJ0082', 'RJ0066', 'RJ0039', 'MG0019', 'RJ0223', 'MG0062', 'RJ0080', 'MG0027', 'MG0035', 'SP0064', 'MG0022', 'DF0002', 'PR0001 ', 'RJ0075', 'PR0012 ', 'MG0031', 'SP0099', 'RJ0060', 'MG0045', 'RJ0071', 'RJ0069', 'MG0026', 'MG0030', 'RJ0804']
008
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/PTS/MG0015RA008.csv
iema
          VALOR_ORIGINAL UNIDADE            DATETIME
33580440           524.0   µg/m3 2015-09-04 17:30:00
33580441           459.0   µg/m3 2015-08-19 16:30:00
33580442           451.0   µg/m3 2015-08-21 14:30:00
33580443           450.0   µg/m3 2015-08-29 14:30:00
33580444           442.0   µg/m3 2015-08-29 07:30:00
mma
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2014-01-01 01:00:00  2014.0  1.0  1.0   1.0    NaN             NaN   µg/m3
1 2014-01-01 02:00:00  2014.0  1.0  1.0   2.0    NaN             NaN   µg/m3
2 2014-01-01 03:00:00  2014.0  1.0  1.0   3.0    NaN             NaN   µg/m3
3 2014-01-01 04:00:00  2014.0  1.0  1.0   4.0    NaN             NaN   µg/m3
4 2014-01-01 05:00:00  2014.0  1.0  1.0   5.0    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2014-01-01 01:00:00  2014.0  1.0  1.0   1.0    NaN             NaN   µg/m3
1 2014-01-01 02:00:00  2014.0  1.0  1.0   2.0    NaN             NaN   µg/m3
2 2014-01-01 03:00:00  2014.0  1.0  1.0   3.0    NaN             NaN   µg/m3
3 2014-01-01 04:00:00  2014.0  1.0  1.0   4.0    NaN             NaN   µg/m3
4 2014-01-01 05:00:00  2014.0  1.0  1.0   5.0    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

008
008
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/PTS/MG0042RA008.csv
iema
          VALOR_ORIGINAL UNIDADE            DATETIME
39610667          1145.0   µg/m3 2022-10-19 09:30:00
37952070          1144.0   µg/m3 2021-07-22 18:30:00
39487322          1124.0   µg/m3 2022-09-14 19:30:00
38137143           946.0   µg/m3 2021-09-06 06:30:00
32245734           932.0   µg/m3 2020-06-12 17:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2017-08-31 01:00:00  2017    8   31     1   72.0            72.0   µg/m3
1 2017-08-31 02:00:00  2017    8   31     2  107.0           107.0   µg/m3
2 2017-08-31 03:00:00  2017    8   31     3   59.0            59.0   µg/m3
3 2017-08-31 04:00:00  2017    8   31     4   77.0            77.0   µg/m3
4 2017-08-31 05:00:00  2017    8   31     5  103.0           103.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2017-08-31 01:00:00  2017    8   31     1   72.0            72.0   µg/m3
1 2017-08-31 02:00:00  2017    8   31     2  107.0           107.0   µg/m3
2 2017-08-31 03:00:00  2017    8   31     3   59.0            59.0   µg/m3
3 2017-08-31 04:00:00  2017    8   31     4   77.0            77.0   µg/m3
4 2017-08-31 05:00:00  2017    8   31     5  103.0           103.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

008
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/PTS/RJ0074RA008.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
24728010           845.0   ug/m3 2017-11-15 15:00:00
24723503           840.0   ug/m3 2017-01-13 03:00:00
24723504           840.0   ug/m3 2017-01-13 04:00:00
24723502           840.0   ug/m3 2017-01-13 02:00:00
24728032           828.0   ug/m3 2017-11-16 14:00:00
mma
             DATETIME     ANO  MES   DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2004-04-21 02:00:00  2004.0  4.0  21.0   2.0    NaN             NaN   µg/m³
1 2004-04-21 03:00:00  2004.0  4.0  21.0   3.0    NaN             NaN   µg/m³
2 2004-04-21 04:00:00  2004.0  4.0  21.0   4.0    NaN             NaN   µg/m³
3 2004-04-21 05:00:00  2004.0  4.0  21.0   5.0    NaN             NaN   µg/m³
4 2004-04-21 06:00:00  2004.0  4.0  21.0   6.0    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0         False     False
1         False     False
2         False     False
3         False     False
4         False     False
final
             DATETIME     ANO  MES   DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2004-04-21 02:00:00  2004.0  4.0  21.0   2.0    NaN             NaN   µg/m³
1 2004-04-21 03:00:00  2004.0  4.0  21.0   3.0    NaN             NaN   µg/m³
2 2004-04-21 04:00:00  2004.0  4.0  21.0   4.0    NaN             NaN   µg/m³
3 2004-04-21 05:00:00  2004.0  4.0  21.0   5.0    NaN             NaN   µg/m³
4 2004-04-21 06:00:00  2004.0  4.0  21.0   6.0    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
008
008
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/PTS/MG0054RA008.csv
iema
          VALOR_ORIGINAL UNIDADE            DATETIME
39296156           964.0   µg/m3 2022-07-25 10:30:00
39568279           956.0   µg/m3 2022-10-07 15:30:00
33841671           752.0   µg/m3 2019-01-18 13:30:00
34891869           702.0   µg/m3 2019-11-06 14:30:00
34858849           472.0   µg/m3 2019-10-28 16:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2018-01-01 01:00:00  2018    1    1     1   33.0            33.0   µg/m3
1 2018-01-01 02:00:00  2018    1    1     2   23.0            23.0   µg/m3
2 2018-01-01 03:00:00  2018    1    1     3    NaN             NaN   µg/m3
3 2018-01-01 04:00:00  2018    1    1     4   20.0            20.0   µg/m3
4 2018-01-01 05:00:00  2018    1    1     5   21.0            21.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True     False
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2018-01-01 01:00:00  2018    1    1     1   33.0            33.0   µg/m3
1 2018-01-01 02:00:00  2018    1    1     2   23.0            23.0   µg/m3
2 2018-01-01 03:00:00  2018    1    1     3    NaN             NaN   µg/m3
3 2018-01-01 04:00:00  2018    1    1     4   20.0            20.0   µg/m3
4 2018-01-01 05:00:00  2018    1    1     5   21.0            21.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True     False
3          True      True
4          True      True

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

008
008
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/PTS/MG0036RA008.csv
iema
          VALOR_ORIGINAL UNIDADE            DATETIME
37975446           973.0   µg/m3 2021-07-28 13:30:00
37975278           928.0   µg/m3 2021-07-28 12:30:00
37765418           858.0   µg/m3 2021-06-06 14:30:00
37723715           751.0   µg/m3 2021-05-26 17:30:00
37975612           711.0   µg/m3 2021-07-28 14:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2017-08-22 17:00:00  2017    8   22    17   60.0            60.0   µg/m3
1 2017-08-22 18:00:00  2017    8   22    18   58.0            58.0   µg/m3
2 2017-08-22 19:00:00  2017    8   22    19    NaN             NaN   µg/m3
3 2017-08-22 20:00:00  2017    8   22    20   34.0            34.0   µg/m3
4 2017-08-22 21:00:00  2017    8   22    21   28.0            28.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True     False
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2017-08-22 17:00:00  2017    8   22    17   60.0            60.0   µg/m3
1 2017-08-22 18:00:00  2017    8   22    18   58.0            58.0   µg/m3
2 2017-08-22 19:00:00  2017    8   22    19    NaN             NaN   µg/m3
3 2017-08-22 20:00:00  2017    8   22    20   34.0            34.0   µg/m3
4 2017-08-22 21:00:00  2017    8   22    21   28.0            28.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True     False
3          True      True
4          True      True

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

008
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/PTS/RJ0048RA008.csv
iema
          VALOR_ORIGINAL UNIDADE            DATETIME
22768504           297.0   ug/m3 2022-08-11 12:00:00
22768505           280.0   ug/m3 2022-08-11 13:00:00
24467031           227.0   µg/m³ 2021-07-20 10:00:00
22763911           222.0   ug/m3 2022-01-26 12:00:00
24469271           205.0   µg/m³ 2021-10-23 14:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2019-09-17 16:00:00  2019    9   17    16    NaN             NaN   µg/m³
1 2019-09-17 17:00:00  2019    9   17    17    NaN             NaN   µg/m³
2 2019-09-17 18:00:00  2019    9   17    18    NaN             NaN   µg/m³
3 2019-09-17 19:00:00  2019    9   17    19    NaN             NaN   µg/m³
4 2019-09-17 20:00:00  2019    9   17    20    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0         False     False
1         False     False
2         False     False
3         False     False
4         False     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2019-09-17 16:00:00  2019    9   17    16    NaN             NaN   µg/m³
1 2019-09-17 17:00:00  2019    9   17    17    NaN             NaN   µg/m³
2 2019-09-17 18:00:00  2019    9   17    18    NaN             NaN   µg/m³
3 2019-09-17 19:00:00  2019    9   17    19    NaN             NaN   µg/m³
4 2019-09-17 20:00:00  2019    9   17    20    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

008
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/PTS/MG0009RA008.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
39357432           591.0   µg/m3 2022-08-10 22:30:00
33375621           439.0   µg/m3 2015-11-13 18:30:00
33375622           437.0   µg/m3 2015-12-30 09:30:00
40386994           414.0   µg/m3 2016-10-14 20:30:00
32503546           403.0   µg/m3 2020-08-25 09:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2014-01-01 01:00:00  2014    1    1     1   73.0            73.0   µg/m3
1 2014-01-01 02:00:00  2014    1    1     2   67.0            67.0   µg/m3
2 2014-01-01 03:00:00  2014    1    1     3   70.0            70.0   µg/m3
3 2014-01-01 04:00:00  2014    1    1     4   67.0            67.0   µg/m3
4 2014-01-01 05:00:00  2014    1    1     5   70.0            70.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2014-01-01 01:00:00  2014    1    1     1   73.0            73.0   µg/m3
1 2014-01-01 02:00:00  2014    1    1     2   67.0            67.0   µg/m3
2 2014-01-01 03:00:00  2014    1    1     3   70.0            70.0   µg/m3
3 2014-01-01 04:00:00  2014    1    1     4   67.0            67.0   µg/m3
4 2014-01-01 05:00:00  2014    1    1     5   70.0            70.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
008
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/PTS/RJ0037RA008.csv
iema
          VALOR_ORIGINAL UNIDADE            DATETIME
23602155           429.0   µg/m3 2020-08-15 13:00:00
23723602           276.0   µg/m3 2020-09-08 13:00:00
31632578           232.0   µg/m3 2020-06-27 15:00:00
23723813           226.0   µg/m3 2020-09-08 14:00:00
31500749           212.0   µg/m3 2020-06-01 19:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2019-08-28 12:00:00  2019    8   28    12    NaN             NaN   µg/m³
1 2019-08-28 13:00:00  2019    8   28    13    NaN             NaN   µg/m³
2 2019-08-28 14:00:00  2019    8   28    14    NaN             NaN   µg/m³
3 2019-08-28 15:00:00  2019    8   28    15    NaN             NaN   µg/m³
4 2019-08-28 16:00:00  2019    8   28    16    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0         False     False
1         False     False
2         False     False
3         False     False
4         False     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2019-08-28 12:00:00  2019    8   28    12    NaN             NaN   µg/m³
1 2019-08-28 13:00:00  2019    8   28    13    NaN             NaN   µg/m³
2 2019-08-28 14:00:00  2019    8   28    14    NaN             NaN   µg/m³
3 2019-08-28 15:00:00  2019    8   28    15    NaN             NaN   µg/m³
4 2019-08-28 16:00:00  2019    8   28    16    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

008
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/PTS/RJ0086RA008.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
22036440          529.21   ug/m3 2017-06-12 13:00:00
22038021          494.74   ug/m3 2017-08-31 14:00:00
22038018          418.14   ug/m3 2017-08-31 11:00:00
22038019          413.18   ug/m3 2017-08-31 12:00:00
22038022          389.48   ug/m3 2017-08-31 15:00:00
mma
             DATETIME     ANO   MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2015-10-01 00:00:00  2015.0  10.0  1.0   0.0  43.44           43.44   µg/m³
1 2015-10-01 01:00:00  2015.0  10.0  1.0   1.0  51.50           51.50   µg/m³
2 2015-10-01 02:00:00  2015.0  10.0  1.0   2.0  54.03           54.03   µg/m³
3 2015-10-01 03:00:00  2015.0  10.0  1.0   3.0  56.98           56.98   µg/m³
4 2015-10-01 04:00:00  2015.0  10.0  1.0   4.0  59.89           59.89   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME     ANO   MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2015-10-01 00:00:00  2015.0  10.0  1.0   0.0  43.44           43.44   µg/m³
1 2015-10-01 01:00:00  2015.0  10.0  1.0   1.0  51.50           51.50   µg/m³
2 2015-10-01 02:00:00  2015.0  10.0  1.0   2.0  54.03           54.03   µg/m³
3 2015-10-01 03:00:00  2015.0  10.0  1.0   3.0  56.98           56.98   µg/m³
4 2015-10-01 04:00:00  2015.0  10.0  1.0   4.0  59.89           59.89   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
008
008
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/PTS/RJ0073RA008.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
31328392           900.0   µg/m3 2020-04-27 19:00:00
20121854           897.0   µg/m3 2019-05-29 08:00:00
31336964           891.0   µg/m3 2020-04-29 13:00:00
20092251           888.0   µg/m3 2019-05-22 11:00:00
20101071           885.0   µg/m3 2019-05-24 12:00:00
mma
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2000-06-01 00:00:00  2000.0  6.0  1.0   0.0    NaN             NaN   µg/m³
1 2000-06-01 01:00:00  2000.0  6.0  1.0   1.0    NaN             NaN   µg/m³
2 2000-06-01 02:00:00  2000.0  6.0  1.0   2.0    NaN             NaN   µg/m³
3 2000-06-01 03:00:00  2000.0  6.0  1.0   3.0    NaN             NaN   µg/m³
4 2000-06-01 04:00:00  2000.0  6.0  1.0   4.0    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0         False     False
1         False     False
2         False     False
3         False     False
4         False     False
final
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2000-06-01 00:00:00  2000.0  6.0  1.0   0.0    NaN             NaN   µg/m³
1 2000-06-01 01:00:00  2000.0  6.0  1.0   1.0    NaN             NaN   µg/m³
2 2000-06-01 02:00:00  2000.0  6.0  1.0   2.0    NaN             NaN   µg/m³
3 2000-06-01 03:00:00  2000.0  6.0  1.0   3.0    NaN             NaN   µg/m³
4 2000-06-01 04:00:00  2000.0  6.0  1.0   4.0    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
008
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/PTS/MG0039RA008.csv
iema
          VALOR_ORIGINAL UNIDADE            DATETIME
37726928           956.0   µg/m3 2021-05-27 12:30:00
32204924           952.0   µg/m3 2020-06-01 14:30:00
37733960           909.0   µg/m3 2021-05-29 07:30:00
32156523           890.0   µg/m3 2020-05-18 23:30:00
39415083           890.0   µg/m3 2022-08-26 07:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2017-05-03 09:00:00  2017    5    3     9    NaN             NaN   µg/m3
1 2017-05-03 10:00:00  2017    5    3    10    NaN             NaN   µg/m3
2 2017-05-03 11:00:00  2017    5    3    11    NaN             NaN   µg/m3
3 2017-05-03 12:00:00  2017    5    3    12    NaN             NaN   µg/m3
4 2017-05-03 13:00:00  2017    5    3    13    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2017-05-03 09:00:00  2017    5    3     9    NaN             NaN   µg/m3
1 2017-05-03 10:00:00  2017    5    3    10    NaN             NaN   µg/m3
2 2017-05-03 11:00:00  2017    5    3    11    NaN             NaN   µg/m3
3 2017-05-03 12:00:00  2017    5    3    12    NaN             NaN   µg/m3
4 2017-05-03 13:00:00  2017    5    3    13    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

008
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/PTS/MG0032RA008.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
40682667           939.0   µg/m3 2016-10-18 13:30:00
34825568           922.0   µg/m3 2019-10-19 19:30:00
40682668           858.0   µg/m3 2016-10-08 16:30:00
40682669           852.0   µg/m3 2016-10-19 10:30:00
40682670           847.0   µg/m3 2016-09-06 16:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2016-02-18 11:00:00  2016    2   18    11    NaN             0.0   µg/m3
1 2016-02-18 12:00:00  2016    2   18    12    NaN             NaN   µg/m3
2 2016-02-18 13:00:00  2016    2   18    13    NaN             NaN   µg/m3
3 2016-02-18 14:00:00  2016    2   18    14    NaN             NaN   µg/m3
4 2016-02-18 15:00:00  2016    2   18    15  144.0           144.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2016-02-18 11:00:00  2016    2   18    11    NaN             0.0   µg/m3
1 2016-02-18 12:00:00  2016    2   18    12    NaN             NaN   µg/m3
2 2016-02-18 13:00:00  2016    2   18    13    NaN             NaN   µg/m3
3 2016-02-18 14:00:00  2016    2   18    14    NaN             NaN   µg/m3
4 2016-02-18 15:00:00  2016    2   18    15  144.0           144.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True      True
008
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/PTS/RJ0067RA008.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
23667609      444.000000   µg/m3 2020-08-28 14:00:00
24148129      280.000000   µg/m3 2020-12-03 08:00:00
19634151      270.000011   µg/m3 2019-01-30 04:00:00
28385256      237.000003   µg/m3 2019-07-16 17:00:00
31612635      224.999994   µg/m3 2020-06-23 16:00:00
mma
             DATETIME     ANO  MES   DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2014-07-21 00:00:00  2014.0  7.0  21.0   0.0    9.0             9.0   µg/m³
1 2014-07-21 01:00:00  2014.0  7.0  21.0   1.0   10.0            10.0   µg/m³
2 2014-07-21 02:00:00  2014.0  7.0  21.0   2.0    9.0             9.0   µg/m³
3 2014-07-21 03:00:00  2014.0  7.0  21.0   3.0   10.0            10.0   µg/m³
4 2014-07-21 04:00:00  2014.0  7.0  21.0   4.0    8.0             8.0   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME     ANO  MES   DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2014-07-21 00:00:00  2014.0  7.0  21.0   0.0    9.0             9.0   µg/m³
1 2014-07-21 01:00:00  2014.0  7.0  21.0   1.0   10.0            10.0   µg/m³
2 2014-07-21 02:00:00  2014.0  7.0  21.0   2.0    9.0             9.0   µg/m³
3 2014-07-21 03:00:00  2014.0  7.0  21.0   3.0   10.0            10.0   µg/m³
4 2014-07-21 04:00:00  2014.0  7.0  21.0   4.0    8.0             8.0   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
008
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/PTS/MG0040RA008.csv
iema
          VALOR_ORIGINAL UNIDADE            DATETIME
39439382           875.0   µg/m3 2022-09-01 18:30:00
34310689           816.0   µg/m3 2019-06-03 17:30:00
39322951           782.0   µg/m3 2022-08-01 15:30:00
38658768           701.0   µg/m3 2022-01-25 14:30:00
34552212           680.0   µg/m3 2019-08-09 09:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2017-06-28 16:00:00  2017    6   28    16   60.0            60.0   µg/m3
1 2017-06-28 17:00:00  2017    6   28    17  104.0           104.0   µg/m3
2 2017-06-28 18:00:00  2017    6   28    18  104.0           104.0   µg/m3
3 2017-06-28 19:00:00  2017    6   28    19  335.0           335.0   µg/m3
4 2017-06-28 20:00:00  2017    6   28    20  141.0           141.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2017-06-28 16:00:00  2017    6   28    16   60.0            60.0   µg/m3
1 2017-06-28 17:00:00  2017    6   28    17  104.0           104.0   µg/m3
2 2017-06-28 18:00:00  2017    6   28    18  104.0           104.0   µg/m3
3 2017-06-28 19:00:00  2017    6   28    19  335.0           335.0   µg/m3
4 2017-06-28 20:00:00  2017    6   28    20  141.0           141.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

008
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/PTS/RJ0063RA008.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
29381301         533.200   ug/m3 2016-06-22 08:30:00
29381302         530.500   ug/m3 2016-06-22 09:30:00
29381299         519.799   ug/m3 2016-06-22 06:30:00
29381300         513.500   ug/m3 2016-06-22 07:30:00
29381298         486.399   ug/m3 2016-06-22 05:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2013-03-14 03:00:00  2013    3   14     3    NaN             NaN   µg/m³
1 2013-03-14 04:00:00  2013    3   14     4    NaN             NaN   µg/m³
2 2013-03-14 05:00:00  2013    3   14     5    NaN             NaN   µg/m³
3 2013-03-14 06:00:00  2013    3   14     6    NaN             NaN   µg/m³
4 2013-03-14 07:00:00  2013    3   14     7    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0         False     False
1         False     False
2         False     False
3         False     False
4         False     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2013-03-14 03:00:00  2013    3   14     3    NaN             NaN   µg/m³
1 2013-03-14 04:00:00  2013    3   14     4    NaN             NaN   µg/m³
2 2013-03-14 05:00:00  2013    3   14     5    NaN             NaN   µg/m³
3 2013-03-14 06:00:00  2013    3   14     6    NaN             NaN   µg/m³
4 2013-03-14 07:00:00  2013    3   14     7    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
008
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/PTS/RJ0043RA008.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
23667608        874.1707   µg/m3 2020-08-28 14:00:00
23905892        866.0028   µg/m3 2020-10-14 21:00:00
23905684        853.9840   µg/m3 2020-10-14 20:00:00
23498437        838.2307   µg/m3 2020-07-26 07:00:00
23908138        837.6504   µg/m3 2020-10-15 08:00:00
mma
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2009-06-06 20:00:00  2009.0  6.0  6.0  20.0    NaN             NaN   µg/m³
1 2009-06-06 21:00:00  2009.0  6.0  6.0  21.0    NaN             NaN   µg/m³
2 2009-06-06 22:00:00  2009.0  6.0  6.0  22.0    NaN             NaN   µg/m³
3 2009-06-06 23:00:00  2009.0  6.0  6.0  23.0    NaN             NaN   µg/m³
4 2009-06-07 00:00:00  2009.0  6.0  7.0   0.0    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0         False     False
1         False     False
2         False     False
3         False     False
4         False     False
final
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2009-06-06 20:00:00  2009.0  6.0  6.0  20.0    NaN             NaN   µg/m³
1 2009-06-06 21:00:00  2009.0  6.0  6.0  21.0    NaN             NaN   µg/m³
2 2009-06-06 22:00:00  2009.0  6.0  6.0  22.0    NaN             NaN   µg/m³
3 2009-06-06 23:00:00  2009.0  6.0  6.0  23.0    NaN             NaN   µg/m³
4 2009-06-07 00:00:00  2009.0  6.0  7.0   0.0    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
008
008
008
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/PTS/MG0011RA008.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
40715583           893.0   µg/m3 2016-08-23 06:30:00
40715585           829.0   µg/m3 2016-10-31 23:30:00
34704880           721.0   µg/m3 2019-09-18 06:30:00
34616197           493.0   µg/m3 2019-08-26 09:30:00
40715589           426.0   µg/m3 2016-04-23 12:30:00
mma
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2014-01-01 01:00:00  2014.0  1.0  1.0   1.0    NaN             NaN   µg/m3
1 2014-01-01 02:00:00  2014.0  1.0  1.0   2.0    NaN             NaN   µg/m3
2 2014-01-01 03:00:00  2014.0  1.0  1.0   3.0    NaN             NaN   µg/m3
3 2014-01-01 04:00:00  2014.0  1.0  1.0   4.0    NaN             NaN   µg/m3
4 2014-01-01 05:00:00  2014.0  1.0  1.0   5.0    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2014-01-01 01:00:00  2014.0  1.0  1.0   1.0    NaN             NaN   µg/m3
1 2014-01-01 02:00:00  2014.0  1.0  1.0   2.0    NaN             NaN   µg/m3
2 2014-01-01 03:00:00  2014.0  1.0  1.0   3.0    NaN             NaN   µg/m3
3 2014-01-01 04:00:00  2014.0  1.0  1.0   4.0    NaN             NaN   µg/m3
4 2014-01-01 05:00:00  2014.0  1.0  1.0   5.0    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
008
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/PTS/MG0028RA008.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
38964048           975.0   µg/m3 2022-04-23 15:30:00
32530669           787.3   µg/m3 2020-09-01 15:30:00
39407954           732.2   µg/m3 2022-08-24 09:30:00
39035842           722.5   µg/m3 2022-05-13 14:30:00
39051377           622.7   µg/m3 2022-05-18 02:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2015-01-01 01:00:00  2015    1    1     1   54.3            54.3   µg/m3
1 2015-01-01 02:00:00  2015    1    1     2   43.2            43.2   µg/m3
2 2015-01-01 03:00:00  2015    1    1     3   16.2            16.2   µg/m3
3 2015-01-01 04:00:00  2015    1    1     4   23.1            23.1   µg/m3
4 2015-01-01 05:00:00  2015    1    1     5   18.6            18.6   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2015-01-01 01:00:00  2015    1    1     1   54.3            54.3   µg/m3
1 2015-01-01 02:00:00  2015    1    1     2   43.2            43.2   µg/m3
2 2015-01-01 03:00:00  2015    1    1     3   16.2            16.2   µg/m3
3 2015-01-01 04:00:00  2015    1    1     4   23.1            23.1   µg/m3
4 2015-01-01 05:00:00  2015    1    1     5   18.6            18.6   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
008
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/PTS/RJ0036RA008.csv
iema
          VALOR_ORIGINAL UNIDADE            DATETIME
23752833           531.0   µg/m3 2020-09-14 08:00:00
23586110           326.0   µg/m3 2020-08-12 10:00:00
23602154           319.0   µg/m3 2020-08-15 13:00:00
23752621           219.0   µg/m3 2020-09-14 07:00:00
28945719           215.0   µg/m3 2019-11-16 21:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2019-10-11 14:00:00  2019   10   11    14  24.08           24.08   µg/m³
1 2019-10-11 15:00:00  2019   10   11    15  24.79           24.79   µg/m³
2 2019-10-11 16:00:00  2019   10   11    16  24.78           24.78   µg/m³
3 2019-10-11 17:00:00  2019   10   11    17  24.46           24.46   µg/m³
4 2019-10-11 18:00:00  2019   10   11    18  24.01           24.01   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2019-10-11 14:00:00  2019   10   11    14  24.08           24.08   µg/m3
1 2019-10-11 15:00:00  2019   10   11    15  24.79           24.79   µg/m3
2 2019-10-11 16:00:00  2019   10   11    16  24.78           24.78   µg/m3
3 2019-10-11 17:00:00  2019   10   11    17  24.46           24.46   µg/m3
4 2019-10-11 18:00:00  2019   10   11    18  24.01           24.01   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

008
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/PTS/RJ0081RA008.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
20921099         898.000   ug/m3 2016-09-14 16:30:00
23509872         852.000   µg/m3 2020-07-28 13:00:00
20920258         732.999   ug/m3 2016-08-09 08:30:00
20921098         726.999   ug/m3 2016-09-14 15:30:00
20920408         725.000   ug/m3 2016-08-15 20:30:00
mma
             DATETIME     ANO   MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2008-12-04 13:00:00  2008.0  12.0  4.0  13.0    NaN             NaN   µg/m³
1 2008-12-04 14:00:00  2008.0  12.0  4.0  14.0    NaN             NaN   µg/m³
2 2008-12-04 15:00:00  2008.0  12.0  4.0  15.0    NaN             NaN   µg/m³
3 2008-12-04 16:00:00  2008.0  12.0  4.0  16.0    NaN             NaN   µg/m³
4 2008-12-04 17:00:00  2008.0  12.0  4.0  17.0    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0         False     False
1         False     False
2         False     False
3         False     False
4         False     False
final
             DATETIME     ANO   MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2008-12-04 13:00:00  2008.0  12.0  4.0  13.0    NaN             NaN   µg/m³
1 2008-12-04 14:00:00  2008.0  12.0  4.0  14.0    NaN             NaN   µg/m³
2 2008-12-04 15:00:00  2008.0  12.0  4.0  15.0    NaN             NaN   µg/m³
3 2008-12-04 16:00:00  2008.0  12.0  4.0  16.0    NaN             NaN   µg/m³
4 2008-12-04 17:00:00  2008.0  12.0  4.0  17.0    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
008
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/PTS/MG0016RA008.csv
iema
          VALOR_ORIGINAL UNIDADE            DATETIME
33361552           827.0   µg/m3 2015-11-13 18:30:00
33361553           786.0   µg/m3 2015-08-12 09:30:00
33361554           566.0   µg/m3 2015-10-20 11:30:00
33361555           552.0   µg/m3 2015-01-28 20:30:00
33361556           520.0   µg/m3 2015-08-13 07:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2014-01-01 01:00:00  2014    1    1     1    NaN             NaN   µg/m3
1 2014-01-01 02:00:00  2014    1    1     2    NaN             NaN   µg/m3
2 2014-01-01 03:00:00  2014    1    1     3    NaN             NaN   µg/m3
3 2014-01-01 04:00:00  2014    1    1     4    NaN             NaN   µg/m3
4 2014-01-01 05:00:00  2014    1    1     5    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2014-01-01 01:00:00  2014    1    1     1    NaN             NaN   µg/m3
1 2014-01-01 02:00:00  2014    1    1     2    NaN             NaN   µg/m3
2 2014-01-01 03:00:00  2014    1    1     3    NaN             NaN   µg/m3
3 2014-01-01 04:00:00  2014    1    1     4    NaN             NaN   µg/m3
4 2014-01-01 05:00:00  2014    1    1     5    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

008
008
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/PTS/MG0058RA008.csv
iema
          VALOR_ORIGINAL UNIDADE            DATETIME
34568399           723.0   µg/m3 2019-08-13 18:30:00
32666813           628.0   µg/m3 2020-10-09 09:30:00
39554548           598.5   µg/m3 2022-10-03 19:30:00
39554402           548.2   µg/m3 2022-10-03 18:30:00
32646560           541.0   µg/m3 2020-10-03 22:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2019-07-30 13:00:00  2019    7   30    13    NaN             NaN   µg/m3
1 2019-07-30 14:00:00  2019    7   30    14    NaN             NaN   µg/m3
2 2019-07-30 15:00:00  2019    7   30    15    NaN             NaN   µg/m3
3 2019-07-30 16:00:00  2019    7   30    16   76.0            76.0   µg/m3
4 2019-07-30 17:00:00  2019    7   30    17    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True      True
4          True     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2019-07-30 13:00:00  2019    7   30    13    NaN             NaN   µg/m3
1 2019-07-30 14:00:00  2019    7   30    14    NaN             NaN   µg/m3
2 2019-07-30 15:00:00  2019    7   30    15    NaN             NaN   µg/m3
3 2019-07-30 16:00:00  2019    7   30    16   76.0            76.0   µg/m3
4 2019-07-30 17:00:00  2019    7   30    17    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True      True
4          True     False

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

008
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/PTS/MG0014RA008.csv
iema
          VALOR_ORIGINAL UNIDADE            DATETIME
40589797           847.0   µg/m3 2016-04-20 09:30:00
34813701           773.0   µg/m3 2019-10-16 17:30:00
40589798           752.0   µg/m3 2016-02-04 20:30:00
40589799           751.0   µg/m3 2016-01-11 21:30:00
36083018           743.0   µg/m3 2018-01-17 18:30:00
mma
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2014-01-01 01:00:00  2014.0  1.0  1.0   1.0    NaN             NaN   µg/m3
1 2014-01-01 02:00:00  2014.0  1.0  1.0   2.0    NaN             NaN   µg/m3
2 2014-01-01 03:00:00  2014.0  1.0  1.0   3.0    NaN             NaN   µg/m3
3 2014-01-01 04:00:00  2014.0  1.0  1.0   4.0    NaN             NaN   µg/m3
4 2014-01-01 05:00:00  2014.0  1.0  1.0   5.0    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2014-01-01 01:00:00  2014.0  1.0  1.0   1.0    NaN             NaN   µg/m3
1 2014-01-01 02:00:00  2014.0  1.0  1.0   2.0    NaN             NaN   µg/m3
2 2014-01-01 03:00:00  2014.0  1.0  1.0   3.0    NaN             NaN   µg/m3
3 2014-01-01 04:00:00  2014.0  1.0  1.0   4.0    NaN             NaN   µg/m3
4 2014-01-01 05:00:00  2014.0  1.0  1.0   5.0    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

008
008
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/PTS/MG0038RA008.csv
iema
          VALOR_ORIGINAL UNIDADE            DATETIME
36671543           853.0   µg/m3 2018-07-25 11:30:00
35949393           800.0   µg/m3 2017-08-16 12:30:00
35949394           766.0   µg/m3 2017-03-07 12:30:00
35949395           639.0   µg/m3 2017-08-16 13:30:00
36671410           580.0   µg/m3 2018-07-25 10:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2017-01-04 20:00:00  2017    1    4    20   31.0            31.0   µg/m3
1 2017-01-04 21:00:00  2017    1    4    21   28.0            28.0   µg/m3
2 2017-01-04 22:00:00  2017    1    4    22   20.0            20.0   µg/m3
3 2017-01-04 23:00:00  2017    1    4    23   27.0            27.0   µg/m3
4 2017-01-05 00:00:00  2017    1    5     0   16.0            16.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2017-01-04 20:00:00  2017    1    4    20   31.0            31.0   µg/m3
1 2017-01-04 21:00:00  2017    1    4    21   28.0            28.0   µg/m3
2 2017-01-04 22:00:00  2017    1    4    22   20.0            20.0   µg/m3
3 2017-01-04 23:00:00  2017    1    4    23   27.0            27.0   µg/m3
4 2017-01-05 00:00:00  2017    1    5     0   16.0            16.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

008
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/PTS/MG0021RA008.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
38139826           835.0   µg/m3 2021-09-06 23:30:00
39430402           827.0   µg/m3 2022-08-30 09:30:00
35748332           813.0   µg/m3 2017-09-16 17:30:00
39430561           754.0   µg/m3 2022-08-30 10:30:00
39252111           735.0   µg/m3 2022-07-13 08:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2015-01-01 01:00:00  2015    1    1     1   47.0            47.0   µg/m3
1 2015-01-01 02:00:00  2015    1    1     2   51.0            51.0   µg/m3
2 2015-01-01 03:00:00  2015    1    1     3   34.0            34.0   µg/m3
3 2015-01-01 04:00:00  2015    1    1     4   20.0            20.0   µg/m3
4 2015-01-01 05:00:00  2015    1    1     5   43.0            43.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2015-01-01 01:00:00  2015    1    1     1   47.0            47.0   µg/m3
1 2015-01-01 02:00:00  2015    1    1     2   51.0            51.0   µg/m3
2 2015-01-01 03:00:00  2015    1    1     3   34.0            34.0   µg/m3
3 2015-01-01 04:00:00  2015    1    1     4   20.0            20.0   µg/m3
4 2015-01-01 05:00:00  2015    1    1     5   43.0            43.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
008
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/PTS/RJ0070RA008.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
21506723         837.314   ug/m3 2015-09-01 17:30:00
28758927         770.000   µg/m3 2019-10-07 15:00:00
21503024         755.601   ug/m3 2015-03-23 07:30:00
20823027         728.098   ug/m3 2016-02-16 10:30:00
19915125         707.000   µg/m3 2019-04-08 17:00:00
mma
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1993-01-06 12:00:00  1993.0  1.0  6.0  12.0   81.1            81.1   µg/m³
1 1993-01-06 13:00:00  1993.0  1.0  6.0  13.0    NaN             NaN   µg/m³
2 1993-01-06 14:00:00  1993.0  1.0  6.0  14.0    NaN             NaN   µg/m³
3 1993-01-06 15:00:00  1993.0  1.0  6.0  15.0    NaN             NaN   µg/m³
4 1993-01-06 16:00:00  1993.0  1.0  6.0  16.0    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1         False     False
2         False     False
3         False     False
4         False     False
final
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1993-01-06 12:00:00  1993.0  1.0  6.0  12.0   81.1            81.1   µg/m³
1 1993-01-06 13:00:00  1993.0  1.0  6.0  13.0    NaN             NaN   µg/m³
2 1993-01-06 14:00:00  1993.0  1.0  6.0  14.0    NaN             NaN   µg/m³
3 1993-01-06 15:00:00  1993.0  1.0  6.0  15.0    NaN             NaN   µg/m³
4 1993-01-06 16:00:00  1993.0  1.0  6.0  16.0    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True     False
2          True     False
3          True     False
4          True     False
008
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/PTS/MG0017RA008.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
39274153           705.0   µg/m3 2022-07-19 09:30:00
38230088           614.0   µg/m3 2021-09-29 20:30:00
37963160           541.0   µg/m3 2021-07-25 11:30:00
34911342           535.0   µg/m3 2019-11-11 19:30:00
32142066           502.0   µg/m3 2020-05-14 20:30:00
mma
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2014-01-01 01:00:00  2014.0  1.0  1.0   1.0    NaN             NaN   µg/m3
1 2014-01-01 02:00:00  2014.0  1.0  1.0   2.0    NaN             NaN   µg/m3
2 2014-01-01 03:00:00  2014.0  1.0  1.0   3.0    NaN             NaN   µg/m3
3 2014-01-01 04:00:00  2014.0  1.0  1.0   4.0    NaN             NaN   µg/m3
4 2014-01-01 05:00:00  2014.0  1.0  1.0   5.0    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2014-01-01 01:00:00  2014.0  1.0  1.0   1.0    NaN             NaN   µg/m3
1 2014-01-01 02:00:00  2014.0  1.0  1.0   2.0    NaN             NaN   µg/m3
2 2014-01-01 03:00:00  2014.0  1.0  1.0   3.0    NaN             NaN   µg/m3
3 2014-01-01 04:00:00  2014.0  1.0  1.0   4.0    NaN             NaN   µg/m3
4 2014-01-01 05:00:00  2014.0  1.0  1.0   5.0    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
008
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/PTS/MG0010RA008.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
32664298           832.0   µg/m3 2020-10-08 17:30:00
33426209           644.0   µg/m3 2015-10-22 19:30:00
32661334           581.0   µg/m3 2020-10-07 21:30:00
40443919           563.0   µg/m3 2016-12-28 16:30:00
33426210           509.0   µg/m3 2015-12-28 18:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2014-01-01 01:00:00  2014    1    1     1   64.0            64.0   µg/m3
1 2014-01-01 02:00:00  2014    1    1     2   64.0            64.0   µg/m3
2 2014-01-01 03:00:00  2014    1    1     3   60.0            60.0   µg/m3
3 2014-01-01 04:00:00  2014    1    1     4   78.0            78.0   µg/m3
4 2014-01-01 05:00:00  2014    1    1     5   70.0            70.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2014-01-01 01:00:00  2014    1    1     1   64.0            64.0   µg/m3
1 2014-01-01 02:00:00  2014    1    1     2   64.0            64.0   µg/m3
2 2014-01-01 03:00:00  2014    1    1     3   60.0            60.0   µg/m3
3 2014-01-01 04:00:00  2014    1    1     4   78.0            78.0   µg/m3
4 2014-01-01 05:00:00  2014    1    1     5   70.0            70.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
008
008
008
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/PTS/MG0020RA008.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
33709050           886.0   µg/m3 2015-08-26 16:30:00
34212706           883.0   µg/m3 2019-05-07 16:30:00
40701891           877.0   µg/m3 2016-08-15 18:30:00
33709051           876.0   µg/m3 2015-09-18 17:30:00
40701892           874.0   µg/m3 2016-07-07 17:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2015-01-01 01:00:00  2015    1    1     1    NaN             NaN   µg/m3
1 2015-01-01 02:00:00  2015    1    1     2    NaN             NaN   µg/m3
2 2015-01-01 03:00:00  2015    1    1     3    NaN             NaN   µg/m3
3 2015-01-01 04:00:00  2015    1    1     4    NaN             NaN   µg/m3
4 2015-01-01 05:00:00  2015    1    1     5    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2015-01-01 01:00:00  2015    1    1     1    NaN             NaN   µg/m3
1 2015-01-01 02:00:00  2015    1    1     2    NaN             NaN   µg/m3
2 2015-01-01 03:00:00  2015    1    1     3    NaN             NaN   µg/m3
3 2015-01-01 04:00:00  2015    1    1     4    NaN             NaN   µg/m3
4 2015-01-01 05:00:00  2015    1    1     5    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
008
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/PTS/RJ0051RA008.csv
iema
          VALOR_ORIGINAL UNIDADE            DATETIME
25651557          305.08   µg/m³ 2021-08-03 13:00:00
21256581          206.34   ug/m3 2021-01-08 08:00:00
25651559          191.68   µg/m³ 2021-07-25 03:00:00
29887130          189.11   µg/m³ 2022-08-05 17:00:00
21261251          183.77   ug/m3 2021-07-28 17:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2020-03-18 14:00:00  2020    3   18    14    NaN             NaN   µg/m³
1 2020-03-18 15:00:00  2020    3   18    15    NaN             NaN   µg/m³
2 2020-03-18 16:00:00  2020    3   18    16    NaN             NaN   µg/m³
3 2020-03-18 17:00:00  2020    3   18    17    NaN             NaN   µg/m³
4 2020-03-18 18:00:00  2020    3   18    18    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0         False     False
1         False     False
2         False     False
3         False     False
4         False     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2020-03-18 14:00:00  2020    3   18    14    NaN             NaN   µg/m³
1 2020-03-18 15:00:00  2020    3   18    15    NaN             NaN   µg/m³
2 2020-03-18 16:00:00  2020    3   18    16    NaN             NaN   µg/m³
3 2020-03-18 17:00:00  2020    3   18    17    NaN             NaN   µg/m³
4 2020-03-18 18:00:00  2020    3   18    18    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

008
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/PTS/MG0044RA008.csv
iema
          VALOR_ORIGINAL UNIDADE            DATETIME
39127403           697.0   µg/m3 2022-06-08 12:30:00
34211868           569.0   µg/m3 2019-05-07 10:30:00
37960753           442.0   µg/m3 2021-07-24 21:30:00
34594911           426.0   µg/m3 2019-08-20 19:30:00
37975704           426.0   µg/m3 2021-07-28 14:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2017-07-01 01:00:00  2017    7    1     1    NaN             NaN   µg/m3
1 2017-07-01 02:00:00  2017    7    1     2    NaN             NaN   µg/m3
2 2017-07-01 03:00:00  2017    7    1     3    NaN             NaN   µg/m3
3 2017-07-01 04:00:00  2017    7    1     4    NaN             NaN   µg/m3
4 2017-07-01 05:00:00  2017    7    1     5    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2017-07-01 01:00:00  2017    7    1     1    NaN             NaN   µg/m3
1 2017-07-01 02:00:00  2017    7    1     2    NaN             NaN   µg/m3
2 2017-07-01 03:00:00  2017    7    1     3    NaN             NaN   µg/m3
3 2017-07-01 04:00:00  2017    7    1     4    NaN             NaN   µg/m3
4 2017-07-01 05:00:00  2017    7    1     5    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

008
008
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/PTS/MG0056RA008.csv
iema
          VALOR_ORIGINAL UNIDADE            DATETIME
38087023          986.00   µg/m3 2021-08-24 20:30:00
37854963          932.00   µg/m3 2021-06-29 07:30:00
34421538          890.89   µg/m3 2019-07-05 08:30:00
37289006          879.00   µg/m3 2021-01-29 14:30:00
36472398          852.53   µg/m3 2018-05-23 10:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2019-01-01 01:00:00  2019    1    1     1    NaN             NaN   µg/m3
1 2019-01-01 02:00:00  2019    1    1     2    NaN             NaN   µg/m3
2 2019-01-01 03:00:00  2019    1    1     3    NaN             NaN   µg/m3
3 2019-01-01 04:00:00  2019    1    1     4    NaN             NaN   µg/m3
4 2019-01-01 05:00:00  2019    1    1     5    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2019-01-01 01:00:00  2019    1    1     1    NaN             NaN   µg/m3
1 2019-01-01 02:00:00  2019    1    1     2    NaN             NaN   µg/m3
2 2019-01-01 03:00:00  2019    1    1     3    NaN             NaN   µg/m3
3 2019-01-01 04:00:00  2019    1    1     4    NaN             NaN   µg/m3
4 2019-01-01 05:00:00  2019    1    1     5    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

008
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/PTS/RJ0076RA008.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
19857383      890.999973   µg/m3 2019-03-25 11:00:00
31647768      875.000000   µg/m3 2020-06-30 16:00:00
20611533      762.000000   ug/m3 2016-12-30 00:30:00
19714887      745.999992   µg/m3 2019-02-18 20:00:00
19643397      683.000028   µg/m3 2019-02-01 12:00:00
mma
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2004-01-07 00:00:00  2004.0  1.0  7.0   0.0   66.3            66.3   µg/m³
1 2004-01-07 01:00:00  2004.0  1.0  7.0   1.0   61.5            61.5   µg/m³
2 2004-01-07 02:00:00  2004.0  1.0  7.0   2.0   42.3            42.3   µg/m³
3 2004-01-07 03:00:00  2004.0  1.0  7.0   3.0   49.2            49.2   µg/m³
4 2004-01-07 04:00:00  2004.0  1.0  7.0   4.0   62.1            62.1   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2004-01-07 00:00:00  2004.0  1.0  7.0   0.0   66.3            66.3   µg/m³
1 2004-01-07 01:00:00  2004.0  1.0  7.0   1.0   61.5            61.5   µg/m³
2 2004-01-07 02:00:00  2004.0  1.0  7.0   2.0   42.3            42.3   µg/m³
3 2004-01-07 03:00:00  2004.0  1.0  7.0   3.0   49.2            49.2   µg/m³
4 2004-01-07 04:00:00  2004.0  1.0  7.0   4.0   62.1            62.1   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
008
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/PTS/MG0013RA008.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
40499085           863.0   µg/m3 2016-10-26 17:30:00
32661372           772.0   µg/m3 2020-10-07 21:30:00
40499086           491.0   µg/m3 2016-09-19 02:30:00
40499087           481.0   µg/m3 2016-09-14 01:30:00
36057033           370.0   µg/m3 2018-01-09 11:30:00
mma
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2014-01-01 01:00:00  2014.0  1.0  1.0   1.0   80.0            80.0   µg/m3
1 2014-01-01 02:00:00  2014.0  1.0  1.0   2.0   89.0            89.0   µg/m3
2 2014-01-01 03:00:00  2014.0  1.0  1.0   3.0   71.0            71.0   µg/m3
3 2014-01-01 04:00:00  2014.0  1.0  1.0   4.0   44.0            44.0   µg/m3
4 2014-01-01 05:00:00  2014.0  1.0  1.0   5.0   51.0            51.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2014-01-01 01:00:00  2014.0  1.0  1.0   1.0   80.0            80.0   µg/m3
1 2014-01-01 02:00:00  2014.0  1.0  1.0   2.0   89.0            89.0   µg/m3
2 2014-01-01 03:00:00  2014.0  1.0  1.0   3.0   71.0            71.0   µg/m3
3 2014-01-01 04:00:00  2014.0  1.0  1.0   4.0   44.0            44.0   µg/m3
4 2014-01-01 05:00:00  2014.0  1.0  1.0   5.0   51.0            51.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
008
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/PTS/MG0034RA008.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
37940206           915.1   µg/m3 2021-07-19 20:30:00
38150347           876.0   µg/m3 2021-09-09 16:30:00
40354308           730.7   µg/m3 2016-01-02 14:30:00
35038336           690.8   µg/m3 2019-12-17 17:30:00
35038186           656.2   µg/m3 2019-12-17 16:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2016-01-01 01:00:00  2016    1    1     1   73.8            73.8   µg/m3
1 2016-01-01 02:00:00  2016    1    1     2   66.4            66.4   µg/m3
2 2016-01-01 03:00:00  2016    1    1     3   61.5            61.5   µg/m3
3 2016-01-01 04:00:00  2016    1    1     4   61.9            61.9   µg/m3
4 2016-01-01 05:00:00  2016    1    1     5   46.6            46.6   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2016-01-01 01:00:00  2016    1    1     1   73.8            73.8   µg/m3
1 2016-01-01 02:00:00  2016    1    1     2   66.4            66.4   µg/m3
2 2016-01-01 03:00:00  2016    1    1     3   61.5            61.5   µg/m3
3 2016-01-01 04:00:00  2016    1    1     4   61.9            61.9   µg/m3
4 2016-01-01 05:00:00  2016    1    1     5   46.6            46.6   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
008
008
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/PTS/RJ0064RA008.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
29501281        896.4840   ug/m3 2016-07-06 14:30:00
29102203        868.0000   µg/m3 2019-12-20 11:00:00
25410813        863.9254   ug/m3 2017-08-30 09:00:00
29502600        860.7680   ug/m3 2016-09-01 11:30:00
29502599        842.2980   ug/m3 2016-09-01 10:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2013-01-01 00:00:00  2013    1    1     0    NaN             NaN   µg/m³
1 2013-01-01 01:00:00  2013    1    1     1   26.6            26.6   µg/m³
2 2013-01-01 02:00:00  2013    1    1     2   25.9            25.9   µg/m³
3 2013-01-01 03:00:00  2013    1    1     3   25.4            25.4   µg/m³
4 2013-01-01 04:00:00  2013    1    1     4   25.3            25.3   µg/m³

   QAQC_INTERNO  QAQC_MMA
0         False     False
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2013-01-01 00:00:00  2013    1    1     0    NaN             NaN   µg/m³
1 2013-01-01 01:00:00  2013    1    1     1   26.6            26.6   µg/m³
2 2013-01-01 02:00:00  2013    1    1     2   25.9            25.9   µg/m³
3 2013-01-01 03:00:00  2013    1    1     3   25.4            25.4   µg/m³
4 2013-01-01 04:00:00  2013    1    1     4   25.3            25.3   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True      True
2          True      True
3          True      True
4          True      True
008
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/PTS/RJ0068RA008.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
19521982      550.999999   µg/m3 2019-01-01 00:00:00
28591760      474.000007   µg/m3 2019-08-31 15:00:00
19636518      381.999999   µg/m3 2019-01-30 18:00:00
19640176      340.999991   µg/m3 2019-01-31 18:00:00
28587501      335.000008   µg/m3 2019-08-30 16:00:00
mma
             DATETIME     ANO  MES   DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2014-07-21 00:00:00  2014.0  7.0  21.0   0.0    NaN             NaN   µg/m³
1 2014-07-21 01:00:00  2014.0  7.0  21.0   1.0    NaN             NaN   µg/m³
2 2014-07-21 02:00:00  2014.0  7.0  21.0   2.0    NaN             NaN   µg/m³
3 2014-07-21 03:00:00  2014.0  7.0  21.0   3.0    NaN             NaN   µg/m³
4 2014-07-21 04:00:00  2014.0  7.0  21.0   4.0    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0         False     False
1         False     False
2         False     False
3         False     False
4         False     False
final
             DATETIME     ANO  MES   DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2014-07-21 00:00:00  2014.0  7.0  21.0   0.0    NaN             NaN   µg/m³
1 2014-07-21 01:00:00  2014.0  7.0  21.0   1.0    NaN             NaN   µg/m³
2 2014-07-21 02:00:00  2014.0  7.0  21.0   2.0    NaN             NaN   µg/m³
3 2014-07-21 03:00:00  2014.0  7.0  21.0   3.0    NaN             NaN   µg/m³
4 2014-07-21 04:00:00  2014.0  7.0  21.0   4.0    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
008
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/PTS/MG0047RA008.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
38731539          1651.0   µg/m3 2022-02-16 15:30:00
38679497           979.0   µg/m3 2022-01-31 16:30:00
34910875           903.0   µg/m3 2019-11-11 16:30:00
38174434           832.0   µg/m3 2021-09-15 18:30:00
38464817           813.0   µg/m3 2021-12-01 16:30:00
mma
             DATETIME     ANO  MES   DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2015-05-24 11:00:00  2015.0  5.0  24.0  11.0    NaN             NaN   µg/m3
1 2015-05-24 12:00:00  2015.0  5.0  24.0  12.0    NaN             NaN   µg/m3
2 2015-05-24 13:00:00  2015.0  5.0  24.0  13.0    NaN             NaN   µg/m3
3 2015-05-24 14:00:00  2015.0  5.0  24.0  14.0    NaN             NaN   µg/m3
4 2015-05-24 15:00:00  2015.0  5.0  24.0  15.0    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME     ANO  MES   DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2015-05-24 11:00:00  2015.0  5.0  24.0  11.0    NaN             NaN   µg/m3
1 2015-05-24 12:00:00  2015.0  5.0  24.0  12.0    NaN             NaN   µg/m3
2 2015-05-24 13:00:00  2015.0  5.0  24.0  13.0    NaN             NaN   µg/m3
3 2015-05-24 14:00:00  2015.0  5.0  24.0  14.0    NaN             NaN   µg/m3
4 2015-05-24 15:00:00  2015.0  5.0  24.0  15.0    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
008
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/PTS/MG0055RA008.csv
iema
          VALOR_ORIGINAL UNIDADE            DATETIME
32479989           820.2   µg/m3 2020-08-18 17:30:00
38025931           739.3   µg/m3 2021-08-09 19:30:00
32358876           736.2   µg/m3 2020-07-14 18:30:00
32461170           676.5   µg/m3 2020-08-13 15:30:00
32359022           614.1   µg/m3 2020-07-14 19:30:00
mma
             DATETIME     ANO  MES   DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2019-07-22 12:00:00  2019.0  7.0  22.0  12.0    NaN             NaN   µg/m3
1 2019-07-22 13:00:00  2019.0  7.0  22.0  13.0    NaN             NaN   µg/m3
2 2019-07-22 14:00:00  2019.0  7.0  22.0  14.0    NaN             NaN   µg/m3
3 2019-07-22 15:00:00  2019.0  7.0  22.0  15.0    NaN             NaN   µg/m3
4 2019-07-22 16:00:00  2019.0  7.0  22.0  16.0    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME     ANO  MES   DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2019-07-22 12:00:00  2019.0  7.0  22.0  12.0    NaN             NaN   µg/m3
1 2019-07-22 13:00:00  2019.0  7.0  22.0  13.0    NaN             NaN   µg/m3
2 2019-07-22 14:00:00  2019.0  7.0  22.0  14.0    NaN             NaN   µg/m3
3 2019-07-22 15:00:00  2019.0  7.0  22.0  15.0    NaN             NaN   µg/m3
4 2019-07-22 16:00:00  2019.0  7.0  22.0  16.0    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

008
008
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/PTS/RJ0054RA008.csv
iema
          VALOR_ORIGINAL UNIDADE            DATETIME
19690738      559.060000   µg/m3 2019-02-12 23:00:00
28384876      549.795959   µg/m3 2019-07-16 15:00:00
23539853      539.966800   µg/m3 2020-08-03 10:00:00
24027954      516.471800   µg/m3 2020-11-08 12:00:00
23418115      435.979800   µg/m3 2020-07-10 15:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2018-10-03 11:00:00  2018   10    3    11    NaN             NaN   µg/m³
1 2018-10-03 12:00:00  2018   10    3    12  43.87           43.87   µg/m³
2 2018-10-03 13:00:00  2018   10    3    13  71.66           71.66   µg/m³
3 2018-10-03 14:00:00  2018   10    3    14  59.30           59.30   µg/m³
4 2018-10-03 15:00:00  2018   10    3    15  36.82           36.82   µg/m³

   QAQC_INTERNO  QAQC_MMA
0         False     False
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2018-10-03 11:00:00  2018   10    3    11    NaN             NaN   µg/m³
1 2018-10-03 12:00:00  2018   10    3    12  43.87           43.87   µg/m³
2 2018-10-03 13:00:00  2018   10    3    13  71.66           71.66   µg/m³
3 2018-10-03 14:00:00  2018   10    3    14  59.30           59.30   µg/m³
4 2018-10-03 15:00:00  2018   10    3    15  36.82           36.82   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True      True
2          True      True
3          True      True
4          True      True

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

008
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/PTS/RJ0077RA008.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
30834462      888.000011   µg/m3 2020-01-13 04:00:00
31372880      874.000013   µg/m3 2020-05-06 15:00:00
19663915      856.999993   µg/m3 2019-02-06 12:00:00
28507944      839.999974   µg/m3 2019-08-12 17:00:00
20712045      825.999000   ug/m3 2016-02-17 14:30:00
mma
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2004-01-07 00:00:00  2004.0  1.0  7.0   0.0  115.2           115.2   µg/m³
1 2004-01-07 01:00:00  2004.0  1.0  7.0   1.0  164.7           164.7   µg/m³
2 2004-01-07 02:00:00  2004.0  1.0  7.0   2.0  267.2           267.2   µg/m³
3 2004-01-07 03:00:00  2004.0  1.0  7.0   3.0   90.4            90.4   µg/m³
4 2004-01-07 04:00:00  2004.0  1.0  7.0   4.0   87.3            87.3   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2004-01-07 00:00:00  2004.0  1.0  7.0   0.0  115.2           115.2   µg/m³
1 2004-01-07 01:00:00  2004.0  1.0  7.0   1.0  164.7           164.7   µg/m³
2 2004-01-07 02:00:00  2004.0  1.0  7.0   2.0  267.2           267.2   µg/m³
3 2004-01-07 03:00:00  2004.0  1.0  7.0   3.0   90.4            90.4   µg/m³
4 2004-01-07 04:00:00  2004.0  1.0  7.0   4.0   87.3            87.3   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
008
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/PTS/RJ0082RA008.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
24825667      887.000000   ug/m3 2017-10-06 04:00:00
24825552      863.000000   ug/m3 2017-09-29 14:00:00
28665805      856.000006   µg/m3 2019-09-17 09:00:00
24824527      795.000000   ug/m3 2017-08-08 06:00:00
24824576      791.000000   ug/m3 2017-08-10 07:00:00
mma
             DATETIME     ANO   MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2008-12-08 18:00:00  2008.0  12.0  8.0  18.0    NaN             NaN   µg/m³
1 2008-12-08 19:00:00  2008.0  12.0  8.0  19.0    NaN             NaN   µg/m³
2 2008-12-08 20:00:00  2008.0  12.0  8.0  20.0    NaN             NaN   µg/m³
3 2008-12-08 21:00:00  2008.0  12.0  8.0  21.0    NaN             NaN   µg/m³
4 2008-12-08 22:00:00  2008.0  12.0  8.0  22.0    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0         False     False
1         False     False
2         False     False
3         False     False
4         False     False
final
             DATETIME     ANO   MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2008-12-08 18:00:00  2008.0  12.0  8.0  18.0    NaN             NaN   µg/m³
1 2008-12-08 19:00:00  2008.0  12.0  8.0  19.0    NaN             NaN   µg/m³
2 2008-12-08 20:00:00  2008.0  12.0  8.0  20.0    NaN             NaN   µg/m³
3 2008-12-08 21:00:00  2008.0  12.0  8.0  21.0    NaN             NaN   µg/m³
4 2008-12-08 22:00:00  2008.0  12.0  8.0  22.0    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
008
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/PTS/RJ0066RA008.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
24134899      617.000000   µg/m3 2020-11-30 14:00:00
23504084      422.000000   µg/m3 2020-07-27 10:00:00
23843523      304.000000   µg/m3 2020-10-02 16:00:00
28511719      296.999991   µg/m3 2019-08-13 13:00:00
28536131      282.999992   µg/m3 2019-08-19 01:00:00
mma
             DATETIME     ANO  MES   DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2014-07-21 00:00:00  2014.0  7.0  21.0   0.0   33.0            33.0   µg/m³
1 2014-07-21 01:00:00  2014.0  7.0  21.0   1.0   40.0            40.0   µg/m³
2 2014-07-21 02:00:00  2014.0  7.0  21.0   2.0   26.0            26.0   µg/m³
3 2014-07-21 03:00:00  2014.0  7.0  21.0   3.0    NaN             NaN   µg/m³
4 2014-07-21 04:00:00  2014.0  7.0  21.0   4.0   30.0            30.0   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3         False     False
4          True      True
final
             DATETIME     ANO  MES   DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2014-07-21 00:00:00  2014.0  7.0  21.0   0.0   33.0            33.0   µg/m³
1 2014-07-21 01:00:00  2014.0  7.0  21.0   1.0   40.0            40.0   µg/m³
2 2014-07-21 02:00:00  2014.0  7.0  21.0   2.0   26.0            26.0   µg/m³
3 2014-07-21 03:00:00  2014.0  7.0  21.0   3.0    NaN             NaN   µg/m³
4 2014-07-21 04:00:00  2014.0  7.0  21.0   4.0   30.0            30.0   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True     False
4          True      True
008
008
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/PTS/MG0019RA008.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
38052586           787.0   µg/m3 2021-08-16 07:30:00
39356369           781.0   µg/m3 2022-08-10 15:30:00
35761977           761.0   µg/m3 2017-07-04 17:30:00
37926074           747.0   µg/m3 2021-07-16 09:30:00
39477705           744.0   µg/m3 2022-09-12 03:30:00
mma
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2015-01-01 01:00:00  2015.0  1.0  1.0   1.0   45.0            45.0   µg/m3
1 2015-01-01 02:00:00  2015.0  1.0  1.0   2.0   33.0            33.0   µg/m3
2 2015-01-01 03:00:00  2015.0  1.0  1.0   3.0   37.0            37.0   µg/m3
3 2015-01-01 04:00:00  2015.0  1.0  1.0   4.0   35.0            35.0   µg/m3
4 2015-01-01 05:00:00  2015.0  1.0  1.0   5.0   46.0            46.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2015-01-01 01:00:00  2015.0  1.0  1.0   1.0   45.0            45.0   µg/m3
1 2015-01-01 02:00:00  2015.0  1.0  1.0   2.0   33.0            33.0   µg/m3
2 2015-01-01 03:00:00  2015.0  1.0  1.0   3.0   37.0            37.0   µg/m3
3 2015-01-01 04:00:00  2015.0  1.0  1.0   4.0   35.0            35.0   µg/m3
4 2015-01-01 05:00:00  2015.0  1.0  1.0   5.0   46.0            46.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
008
008
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/PTS/MG0062RA008.csv
iema
          VALOR_ORIGINAL UNIDADE            DATETIME
32592733           933.0   µg/m3 2020-09-19 04:30:00
32562206           917.0   µg/m3 2020-09-10 06:30:00
32618028           866.0   µg/m3 2020-09-26 06:30:00
32635704           855.0   µg/m3 2020-10-01 01:30:00
32592880           846.0   µg/m3 2020-09-19 05:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2020-01-01 01:00:00  2020    1    1     1    NaN             NaN   µg/m3
1 2020-01-01 02:00:00  2020    1    1     2    NaN             NaN   µg/m3
2 2020-01-01 03:00:00  2020    1    1     3    NaN             NaN   µg/m3
3 2020-01-01 04:00:00  2020    1    1     4    NaN             NaN   µg/m3
4 2020-01-01 05:00:00  2020    1    1     5    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2020-01-01 01:00:00  2020    1    1     1    NaN             NaN   µg/m3
1 2020-01-01 02:00:00  2020    1    1     2    NaN             NaN   µg/m3
2 2020-01-01 03:00:00  2020    1    1     3    NaN             NaN   µg/m3
3 2020-01-01 04:00:00  2020    1    1     4    NaN             NaN   µg/m3
4 2020-01-01 05:00:00  2020    1    1     5    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

008
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/PTS/RJ0080RA008.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
24923885           875.0   ug/m3 2017-09-17 11:00:00
24922984           774.0   ug/m3 2017-08-03 15:00:00
24923888           659.0   ug/m3 2017-09-17 15:00:00
21402161           642.0   ug/m3 2015-01-18 20:30:00
24924242           606.0   ug/m3 2017-10-05 14:00:00
mma
             DATETIME     ANO   MES   DIA  HORA  VALOR  VALOR_ORIGINAL  \
0 2008-12-10 15:00:00  2008.0  12.0  10.0  15.0    NaN             NaN
1 2008-12-10 16:00:00  2008.0  12.0  10.0  16.0  150.0           150.0
2 2008-12-10 17:00:00  2008.0  12.0  10.0  17.0  141.0           141.0
3 2008-12-10 18:00:00  2008.0  12.0  10.0  18.0   86.0            86.0
4 2008-12-10 19:00:00  2008.0  12.0  10.0  19.0   55.0            55.0

  UNIDADE  QAQC_INTERNO  QAQC_MMA
0   µg/m³         False     False
1   µg/m³          True      True
2   µg/m³          True      True
3   µg/m³          True      True
4   µg/m³          True      True
final
             DATETIME     ANO   MES   DIA  HORA  VALOR  VALOR_ORIGINAL  \
0 2008-12-10 15:00:00  2008.0  12.0  10.0  15.0    NaN             NaN
1 2008-12-10 16:00:00  2008.0  12.0  10.0  16.0  150.0           150.0
2 2008-12-10 17:00:00  2008.0  12.0  10.0  17.0  141.0           141.0
3 2008-12-10 18:00:00  2008.0  12.0  10.0  18.0   86.0            86.0
4 2008-12-10 19:00:00  2008.0  12.0  10.0  19.0   55.0            55.0

  UNIDADE  QAQC_INTERNO  QAQC_MMA
0   µg/m³          True     False
1   µg/m³          True      True
2   µg/m³          True      True
3   µg/m³          True      True
4   µg/m³          True      True
008
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/PTS/MG0027RA008.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
39282418          1618.0   µg/m3 2022-07-21 15:30:00
39281654          1494.0   µg/m3 2022-07-21 10:30:00
39355912          1012.4   µg/m3 2022-08-10 12:30:00
39357345           818.4   µg/m3 2022-08-10 21:30:00
38874826           814.0   µg/m3 2022-03-29 14:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2015-01-01 01:00:00  2015    1    1     1   59.2            59.2   µg/m3
1 2015-01-01 02:00:00  2015    1    1     2   59.4            59.4   µg/m3
2 2015-01-01 03:00:00  2015    1    1     3   26.8            26.8   µg/m3
3 2015-01-01 04:00:00  2015    1    1     4   28.7            28.7   µg/m3
4 2015-01-01 05:00:00  2015    1    1     5   22.2            22.2   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2015-01-01 01:00:00  2015    1    1     1   59.2            59.2   µg/m3
1 2015-01-01 02:00:00  2015    1    1     2   59.4            59.4   µg/m3
2 2015-01-01 03:00:00  2015    1    1     3   26.8            26.8   µg/m3
3 2015-01-01 04:00:00  2015    1    1     4   28.7            28.7   µg/m3
4 2015-01-01 05:00:00  2015    1    1     5   22.2            22.2   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
008
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/PTS/MG0035RA008.csv
iema
          VALOR_ORIGINAL UNIDADE            DATETIME
39124341           936.0   µg/m3 2022-06-07 15:30:00
39355985           896.0   µg/m3 2022-08-10 13:30:00
34381101           882.0   µg/m3 2019-06-23 22:30:00
39356149           859.0   µg/m3 2022-08-10 14:30:00
34866006           840.0   µg/m3 2019-10-30 15:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2017-01-01 01:00:00  2017    1    1     1    NaN             NaN   µg/m3
1 2017-01-01 02:00:00  2017    1    1     2    NaN             NaN   µg/m3
2 2017-01-01 03:00:00  2017    1    1     3    NaN             NaN   µg/m3
3 2017-01-01 04:00:00  2017    1    1     4    NaN             NaN   µg/m3
4 2017-01-01 05:00:00  2017    1    1     5    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2017-01-01 01:00:00  2017    1    1     1    NaN             NaN   µg/m3
1 2017-01-01 02:00:00  2017    1    1     2    NaN             NaN   µg/m3
2 2017-01-01 03:00:00  2017    1    1     3    NaN             NaN   µg/m3
3 2017-01-01 04:00:00  2017    1    1     4    NaN             NaN   µg/m3
4 2017-01-01 05:00:00  2017    1    1     5    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

008
008
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/PTS/MG0022RA008.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
39357180           966.1   µg/m3 2022-08-10 20:30:00
39355738           961.0   µg/m3 2022-08-10 11:30:00
38333525           788.0   µg/m3 2021-10-27 13:30:00
38672195           673.5   µg/m3 2022-01-29 13:30:00
39355901           670.7   µg/m3 2022-08-10 12:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2015-01-01 01:00:00  2015    1    1     1   39.1            39.1   µg/m3
1 2015-01-01 02:00:00  2015    1    1     2   36.8            36.8   µg/m3
2 2015-01-01 03:00:00  2015    1    1     3   27.1            27.1   µg/m3
3 2015-01-01 04:00:00  2015    1    1     4   26.1            26.1   µg/m3
4 2015-01-01 05:00:00  2015    1    1     5   24.8            24.8   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2015-01-01 01:00:00  2015    1    1     1   39.1            39.1   µg/m3
1 2015-01-01 02:00:00  2015    1    1     2   36.8            36.8   µg/m3
2 2015-01-01 03:00:00  2015    1    1     3   27.1            27.1   µg/m3
3 2015-01-01 04:00:00  2015    1    1     4   26.1            26.1   µg/m3
4 2015-01-01 05:00:00  2015    1    1     5   24.8            24.8   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
008
008
008
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/PTS/RJ0075RA008.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
30969578           840.0   µg/m3 2020-02-11 18:00:00
24693087           733.0   ug/m3 2017-09-22 14:00:00
24694335           578.0   ug/m3 2017-11-26 06:00:00
24694685           451.0   ug/m3 2017-12-19 08:00:00
21288005           398.0   ug/m3 2015-11-09 18:30:00
mma
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2004-01-07 00:00:00  2004.0  1.0  7.0   0.0    NaN             NaN   µg/m³
1 2004-01-07 01:00:00  2004.0  1.0  7.0   1.0    NaN             NaN   µg/m³
2 2004-01-07 02:00:00  2004.0  1.0  7.0   2.0    NaN             NaN   µg/m³
3 2004-01-07 03:00:00  2004.0  1.0  7.0   3.0    NaN             NaN   µg/m³
4 2004-01-07 04:00:00  2004.0  1.0  7.0   4.0    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0         False     False
1         False     False
2         False     False
3         False     False
4         False     False
final
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2004-01-07 00:00:00  2004.0  1.0  7.0   0.0    NaN             NaN   µg/m³
1 2004-01-07 01:00:00  2004.0  1.0  7.0   1.0    NaN             NaN   µg/m³
2 2004-01-07 02:00:00  2004.0  1.0  7.0   2.0    NaN             NaN   µg/m³
3 2004-01-07 03:00:00  2004.0  1.0  7.0   3.0    NaN             NaN   µg/m³
4 2004-01-07 04:00:00  2004.0  1.0  7.0   4.0    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
008
008
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/PTS/MG0031RA008.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
34764678           944.0   µg/m3 2019-10-03 23:30:00
33682372           890.0   µg/m3 2015-10-23 01:30:00
34785374           850.0   µg/m3 2019-10-09 10:30:00
35809813           848.0   µg/m3 2017-09-01 09:30:00
34781872           833.0   µg/m3 2019-10-08 12:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2015-01-01 01:00:00  2015    1    1     1   60.0            60.0   µg/m3
1 2015-01-01 02:00:00  2015    1    1     2   44.0            44.0   µg/m3
2 2015-01-01 03:00:00  2015    1    1     3   31.0            31.0   µg/m3
3 2015-01-01 04:00:00  2015    1    1     4   34.0            34.0   µg/m3
4 2015-01-01 05:00:00  2015    1    1     5   37.0            37.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2015-01-01 01:00:00  2015    1    1     1   60.0            60.0   µg/m3
1 2015-01-01 02:00:00  2015    1    1     2   44.0            44.0   µg/m3
2 2015-01-01 03:00:00  2015    1    1     3   31.0            31.0   µg/m3
3 2015-01-01 04:00:00  2015    1    1     4   34.0            34.0   µg/m3
4 2015-01-01 05:00:00  2015    1    1     5   37.0            37.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
008
008
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/PTS/RJ0060RA008.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
30813882      575.709179   µg/m3 2020-01-08 17:00:00
27381757      504.811000   ug/m3 2015-06-08 23:30:00
27382238      504.476000   ug/m3 2015-07-01 00:30:00
27382037      477.143000   ug/m3 2015-06-21 19:30:00
29289812      470.196000   ug/m3 2016-07-13 03:30:00
mma
             DATETIME     ANO   MES   DIA  HORA  VALOR  VALOR_ORIGINAL  \
0 2008-12-15 00:00:00  2008.0  12.0  15.0   0.0  18.07           18.07
1 2008-12-15 01:00:00  2008.0  12.0  15.0   1.0  14.35           14.35
2 2008-12-15 02:00:00  2008.0  12.0  15.0   2.0  10.31           10.31
3 2008-12-15 03:00:00  2008.0  12.0  15.0   3.0  10.46           10.46
4 2008-12-15 04:00:00  2008.0  12.0  15.0   4.0  15.00           15.00

  UNIDADE  QAQC_INTERNO  QAQC_MMA
0   µg/m³          True      True
1   µg/m³          True      True
2   µg/m³          True      True
3   µg/m³          True      True
4   µg/m³          True      True
final
             DATETIME     ANO   MES   DIA  HORA  VALOR  VALOR_ORIGINAL  \
0 2008-12-15 00:00:00  2008.0  12.0  15.0   0.0  18.07           18.07
1 2008-12-15 01:00:00  2008.0  12.0  15.0   1.0  14.35           14.35
2 2008-12-15 02:00:00  2008.0  12.0  15.0   2.0  10.31           10.31
3 2008-12-15 03:00:00  2008.0  12.0  15.0   3.0  10.46           10.46
4 2008-12-15 04:00:00  2008.0  12.0  15.0   4.0  15.00           15.00

  UNIDADE  QAQC_INTERNO  QAQC_MMA
0   µg/m³          True      True
1   µg/m³          True      True
2   µg/m³          True      True
3   µg/m³          True      True
4   µg/m³          True      True
008
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/PTS/MG0045RA008.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
38198482           989.0   µg/m3 2021-09-21 19:30:00
37888361           979.0   µg/m3 2021-07-07 07:30:00
37727782           963.0   µg/m3 2021-05-27 17:30:00
37843283           939.0   µg/m3 2021-06-26 07:30:00
38170417           932.0   µg/m3 2021-09-14 18:30:00
mma
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2017-01-01 01:00:00  2017.0  1.0  1.0   1.0    NaN             NaN   µg/m3
1 2017-01-01 02:00:00  2017.0  1.0  1.0   2.0    NaN             NaN   µg/m3
2 2017-01-01 03:00:00  2017.0  1.0  1.0   3.0    NaN             NaN   µg/m3
3 2017-01-01 04:00:00  2017.0  1.0  1.0   4.0    NaN             NaN   µg/m3
4 2017-01-01 05:00:00  2017.0  1.0  1.0   5.0    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2017-01-01 01:00:00  2017.0  1.0  1.0   1.0    NaN             NaN   µg/m3
1 2017-01-01 02:00:00  2017.0  1.0  1.0   2.0    NaN             NaN   µg/m3
2 2017-01-01 03:00:00  2017.0  1.0  1.0   3.0    NaN             NaN   µg/m3
3 2017-01-01 04:00:00  2017.0  1.0  1.0   4.0    NaN             NaN   µg/m3
4 2017-01-01 05:00:00  2017.0  1.0  1.0   5.0    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
008
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/PTS/RJ0071RA008.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
20031204      836.448569   µg/m3 2019-05-07 11:00:00
21555429      739.768000   ug/m3 2015-08-15 19:30:00
21555428      725.934000   ug/m3 2015-08-15 17:30:00
20197874      601.124677   µg/m3 2019-06-15 22:00:00
19535602      597.959656   µg/m3 2019-01-04 10:00:00
mma
             DATETIME     ANO   MES   DIA  HORA  VALOR  VALOR_ORIGINAL  \
0 2000-12-21 06:00:00  2000.0  12.0  21.0   6.0  16.24           16.24
1 2000-12-21 07:00:00  2000.0  12.0  21.0   7.0  14.95           14.95
2 2000-12-21 08:00:00  2000.0  12.0  21.0   8.0  20.27           20.27
3 2000-12-21 09:00:00  2000.0  12.0  21.0   9.0  23.72           23.72
4 2000-12-21 10:00:00  2000.0  12.0  21.0  10.0  30.02           30.02

  UNIDADE  QAQC_INTERNO  QAQC_MMA
0   µg/m³          True      True
1   µg/m³          True      True
2   µg/m³          True      True
3   µg/m³          True      True
4   µg/m³          True      True
final
             DATETIME     ANO   MES   DIA  HORA  VALOR  VALOR_ORIGINAL  \
0 2000-12-21 06:00:00  2000.0  12.0  21.0   6.0  16.24           16.24
1 2000-12-21 07:00:00  2000.0  12.0  21.0   7.0  14.95           14.95
2 2000-12-21 08:00:00  2000.0  12.0  21.0   8.0  20.27           20.27
3 2000-12-21 09:00:00  2000.0  12.0  21.0   9.0  23.72           23.72
4 2000-12-21 10:00:00  2000.0  12.0  21.0  10.0  30.02           30.02

  UNIDADE  QAQC_INTERNO  QAQC_MMA
0   µg/m³          True      True
1   µg/m³          True      True
2   µg/m³          True      True
3   µg/m³          True      True
4   µg/m³          True      True
008
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/PTS/RJ0069RA008.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
24863569      766.386000   ug/m3 2017-05-15 16:00:00
30868398      690.498245   µg/m3 2020-01-20 11:00:00
20775852      540.059000   ug/m3 2016-02-02 08:30:00
30865289      505.424011   µg/m3 2020-01-19 19:00:00
21451651      496.938000   ug/m3 2015-01-13 15:30:00
mma
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1993-01-06 12:00:00  1993.0  1.0  6.0  12.0  216.8           216.8   µg/m³
1 1993-01-06 13:00:00  1993.0  1.0  6.0  13.0    NaN             NaN   µg/m³
2 1993-01-06 14:00:00  1993.0  1.0  6.0  14.0    NaN             NaN   µg/m³
3 1993-01-06 15:00:00  1993.0  1.0  6.0  15.0    NaN             NaN   µg/m³
4 1993-01-06 16:00:00  1993.0  1.0  6.0  16.0    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1         False     False
2         False     False
3         False     False
4         False     False
final
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 1993-01-06 12:00:00  1993.0  1.0  6.0  12.0  216.8           216.8   µg/m³
1 1993-01-06 13:00:00  1993.0  1.0  6.0  13.0    NaN             NaN   µg/m³
2 1993-01-06 14:00:00  1993.0  1.0  6.0  14.0    NaN             NaN   µg/m³
3 1993-01-06 15:00:00  1993.0  1.0  6.0  15.0    NaN             NaN   µg/m³
4 1993-01-06 16:00:00  1993.0  1.0  6.0  16.0    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True     False
2          True     False
3          True     False
4          True     False
008
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/PTS/MG0026RA008.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
35781025           863.0   µg/m3 2017-08-20 21:30:00
39497353           731.0   µg/m3 2022-09-17 16:30:00
34679948           598.0   µg/m3 2019-09-11 18:30:00
39489479           540.0   µg/m3 2022-09-15 09:30:00
38211304           506.0   µg/m3 2021-09-25 02:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2015-01-01 01:00:00  2015    1    1     1   24.0            24.0   µg/m3
1 2015-01-01 02:00:00  2015    1    1     2   25.0            25.0   µg/m3
2 2015-01-01 03:00:00  2015    1    1     3   31.0            31.0   µg/m3
3 2015-01-01 04:00:00  2015    1    1     4   18.0            18.0   µg/m3
4 2015-01-01 05:00:00  2015    1    1     5   22.0            22.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2015-01-01 01:00:00  2015    1    1     1   24.0            24.0   µg/m3
1 2015-01-01 02:00:00  2015    1    1     2   25.0            25.0   µg/m3
2 2015-01-01 03:00:00  2015    1    1     3   31.0            31.0   µg/m3
3 2015-01-01 04:00:00  2015    1    1     4   18.0            18.0   µg/m3
4 2015-01-01 05:00:00  2015    1    1     5   22.0            22.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
008
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/PTS/MG0030RA008.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
39381495           936.0   µg/m3 2022-08-17 07:30:00
33666600           865.0   µg/m3 2015-09-07 17:30:00
38201977           849.0   µg/m3 2021-09-22 17:30:00
38180883           840.0   µg/m3 2021-09-17 09:30:00
39521769           794.0   µg/m3 2022-09-24 18:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2015-01-01 01:00:00  2015    1    1     1   19.0            19.0   µg/m3
1 2015-01-01 02:00:00  2015    1    1     2   17.0            17.0   µg/m3
2 2015-01-01 03:00:00  2015    1    1     3   28.0            28.0   µg/m3
3 2015-01-01 04:00:00  2015    1    1     4   13.0            13.0   µg/m3
4 2015-01-01 05:00:00  2015    1    1     5   20.0            20.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2015-01-01 01:00:00  2015    1    1     1   19.0            19.0   µg/m3
1 2015-01-01 02:00:00  2015    1    1     2   17.0            17.0   µg/m3
2 2015-01-01 03:00:00  2015    1    1     3   28.0            28.0   µg/m3
3 2015-01-01 04:00:00  2015    1    1     4   13.0            13.0   µg/m3
4 2015-01-01 05:00:00  2015    1    1     5   20.0            20.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
008
MP25
['RJ0050', 'MG0015', 'SP0266', 'MG0008', 'MG0033', 'MG0054', 'MG0036', 'MG0009', 'SP0284', 'SP0086', 'MG0061', 'MG0049', 'SP0091', 'SP0288', nan, 'MG0039', 'MG0032', 'RJ0226', 'MG0040', 'SP0116', 'SP0289', 'MG0001', 'SP0120', 'MG0006', 'SP0085', 'MG0011', 'MG0002', 'MG0057', 'MG0028', 'MG0012', 'MG0016', 'SP0109', 'MG0058', 'MG0014', 'MG0059', 'SP0293', 'SP0083', 'SP0273', 'MG0038', 'MG0060', 'MG0025', 'RJ0025', 'MG0052', 'RJ0070', 'MG0017', 'MG0010', 'MG0020', 'RJ0051', 'MG0044', 'RJ0222', 'MG0013', 'MG0018', 'MG0034', 'MG0004', 'RJ0031', 'SP0065', 'MG0047', 'MG0055', 'RJ0054', 'RJ0030', 'RJ0029', 'SP0113', 'MG0003', 'MG0023', 'SP0281', 'RJ0039', 'MG0019', 'RJ0223', 'RJ0023', 'MG0027', 'MG0035', 'SP0064', 'MG0022', 'MG0053', 'SP0280', 'MG0031', 'SP0099', 'MG0005', 'SP0073', 'RJ0071', 'RJ0069', 'SP0063', 'RJ0224']
002
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/MP25/RJ0050RA002.csv
iema
          VALOR_ORIGINAL UNIDADE            DATETIME
28798931      275.452266   µg/m3 2019-10-16 12:00:00
19750800      274.400000   µg/m3 2019-02-27 12:00:00
28798132      204.078056   µg/m3 2019-10-16 08:00:00
28798335      165.127361   µg/m3 2019-10-16 09:00:00
28798735      158.114960   µg/m3 2019-10-16 11:00:00
mma
             DATETIME     ANO   MES   DIA  HORA  VALOR  VALOR_ORIGINAL  \
0 2018-10-10 16:00:00  2018.0  10.0  10.0  16.0  17.61           17.61
1 2018-10-10 17:00:00  2018.0  10.0  10.0  17.0    NaN             NaN
2 2018-10-10 18:00:00  2018.0  10.0  10.0  18.0    NaN             NaN
3 2018-10-10 19:00:00  2018.0  10.0  10.0  19.0    NaN             NaN
4 2018-10-10 20:00:00  2018.0  10.0  10.0  20.0    NaN             NaN

  UNIDADE  QAQC_INTERNO  QAQC_MMA
0   µg/m³          True      True
1   µg/m³         False     False
2   µg/m³         False     False
3   µg/m³         False     False
4   µg/m³         False     False
final
             DATETIME     ANO   MES   DIA  HORA  VALOR  VALOR_ORIGINAL  \
0 2018-10-10 16:00:00  2018.0  10.0  10.0  16.0  17.61           17.61
1 2018-10-10 17:00:00  2018.0  10.0  10.0  17.0    NaN             NaN
2 2018-10-10 18:00:00  2018.0  10.0  10.0  18.0    NaN             NaN
3 2018-10-10 19:00:00  2018.0  10.0  10.0  19.0    NaN             NaN
4 2018-10-10 20:00:00  2018.0  10.0  10.0  20.0    NaN             NaN

  UNIDADE  QAQC_INTERNO  QAQC_MMA
0   µg/m³          True      True
1   µg/m³          True     False
2   µg/m³          True     False
3   µg/m³          True     False
4   µg/m³          True     False

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

002
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/MP25/MG0015RA002.csv
iema
          VALOR_ORIGINAL UNIDADE            DATETIME
39207503           329.0   µg/m3 2022-06-30 17:30:00
38164084           194.0   µg/m3 2021-09-13 04:30:00
39207658           173.0   µg/m3 2022-06-30 18:30:00
38164562           159.0   µg/m3 2021-09-13 07:30:00
38167171           158.0   µg/m3 2021-09-13 23:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2020-01-01 02:00:00  2020    1    1     2    NaN             NaN     NaN
1 2020-01-01 03:00:00  2020    1    1     3    NaN             NaN     NaN
2 2020-01-01 04:00:00  2020    1    1     4    NaN             NaN     NaN
3 2020-01-01 05:00:00  2020    1    1     5    NaN             NaN     NaN
4 2020-01-01 06:00:00  2020    1    1     6    NaN             NaN     NaN

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2020-01-01 02:00:00  2020    1    1     2    NaN             NaN     NaN
1 2020-01-01 03:00:00  2020    1    1     3    NaN             NaN     NaN
2 2020-01-01 04:00:00  2020    1    1     4    NaN             NaN     NaN
3 2020-01-01 05:00:00  2020    1    1     5    NaN             NaN     NaN
4 2020-01-01 06:00:00  2020    1    1     6    NaN             NaN     NaN

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

002
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/MP25/SP0266RA002.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
19413094           261.0   ug/m3 2015-10-20 21:00:00
14530267           256.0   ug/m3 2016-04-04 02:00:00
9867316            207.0   ug/m3 2018-07-16 23:00:00
19412476           199.0   ug/m3 2015-09-25 02:00:00
13694436           196.0   ug/m3 2019-07-14 02:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2015-06-28 02:00:00  2015    6   28     2   77.0            77.0   µg/m3
1 2015-06-28 03:00:00  2015    6   28     3   55.0            55.0   µg/m3
2 2015-06-28 04:00:00  2015    6   28     4   31.0            31.0   µg/m3
3 2015-06-28 05:00:00  2015    6   28     5   14.0            14.0   µg/m3
4 2015-06-28 06:00:00  2015    6   28     6   12.0            12.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2015-06-28 02:00:00  2015    6   28     2   77.0            77.0   ug/m3
1 2015-06-28 03:00:00  2015    6   28     3   55.0            55.0   ug/m3
2 2015-06-28 04:00:00  2015    6   28     4   31.0            31.0   ug/m3
3 2015-06-28 05:00:00  2015    6   28     5   14.0            14.0   ug/m3
4 2015-06-28 06:00:00  2015    6   28     6   12.0            12.0   ug/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
002
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/MP25/MG0008RA002.csv

/tmp/ipykernel_273420/1352582357.py:97: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  df_mma = pd.read_csv(arquivo, encoding = 'UTF-8')
/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
34870607           139.0   µg/m3 2019-10-31 20:30:00
34418940           134.0   µg/m3 2019-07-04 15:30:00
32577160           114.0   µg/m3 2020-09-14 15:30:00
34707383           114.0   µg/m3 2019-09-18 21:30:00
34821686           113.0   µg/m3 2019-10-18 18:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR VALOR_ORIGINAL UNIDADE  \
0 2013-01-01 01:00:00  2013    1    1     1    NaN              *   µg/m3
1 2013-01-01 02:00:00  2013    1    1     2    NaN              *   µg/m3
2 2013-01-01 03:00:00  2013    1    1     3    NaN              *   µg/m3
3 2013-01-01 04:00:00  2013    1    1     4    NaN              *   µg/m3
4 2013-01-01 05:00:00  2013    1    1     5    NaN              *   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR VALOR_ORIGINAL UNIDADE  \
0 2013-01-01 01:00:00  2013    1    1     1    NaN              *   µg/m3
1 2013-01-01 02:00:00  2013    1    1     2    NaN              *   µg/m3
2 2013-01-01 03:00:00  2013    1    1     3    NaN              *   µg/m3
3 2013-01-01 04:00:00  2013    1    1     4    NaN              *   µg/m3
4 2013-01-01 05:00:00  2013    1    1     5    NaN              *   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
002
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/MP25/MG0033RA002.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
33288127           716.0   µg/m3 2015-09-07 18:30:00
34358115           653.0   µg/m3 2019-06-17 07:30:00
34360469           511.0   µg/m3 2019-06-17 23:30:00
34367407           385.0   µg/m3 2019-06-20 00:30:00
40292604           377.0   µg/m3 2016-04-20 21:30:00
mma
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2016-01-01 01:00:00  2016.0  1.0  1.0   1.0   24.0            24.0   µg/m3
1 2016-01-01 02:00:00  2016.0  1.0  1.0   2.0   28.0            28.0   µg/m3
2 2016-01-01 03:00:00  2016.0  1.0  1.0   3.0   17.0            17.0   µg/m3
3 2016-01-01 04:00:00  2016.0  1.0  1.0   4.0   22.0            22.0   µg/m3
4 2016-01-01 05:00:00  2016.0  1.0  1.0   5.0   21.0            21.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2016-01-01 01:00:00  2016.0  1.0  1.0   1.0   24.0            24.0   µg/m3
1 2016-01-01 02:00:00  2016.0  1.0  1.0   2.0   28.0            28.0   µg/m3
2 2016-01-01 03:00:00  2016.0  1.0  1.0   3.0   17.0            17.0   µg/m3
3 2016-01-01 04:00:00  2016.0  1.0  1.0   4.0   22.0            22.0   µg/m3
4 2016-01-01 05:00:00  2016.0  1.0  1.0   5.0   21.0            21.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
002
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/MP25/MG0054RA002.csv
iema
          VALOR_ORIGINAL UNIDADE            DATETIME
35969584           126.0   µg/m3 2017-07-03 21:30:00
34826086           110.0   µg/m3 2019-10-19 22:30:00
35969605           109.0   µg/m3 2017-09-18 09:30:00
35969604           109.0   µg/m3 2017-08-05 20:30:00
34819985           109.0   µg/m3 2019-10-18 07:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2018-01-01 01:00:00  2018    1    1     1    6.0             6.0   µg/m3
1 2018-01-01 02:00:00  2018    1    1     2    7.0             7.0   µg/m3
2 2018-01-01 03:00:00  2018    1    1     3    7.0             7.0   µg/m3
3 2018-01-01 04:00:00  2018    1    1     4    9.0             9.0   µg/m3
4 2018-01-01 05:00:00  2018    1    1     5    7.0             7.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2018-01-01 01:00:00  2018    1    1     1    6.0             6.0   µg/m3
1 2018-01-01 02:00:00  2018    1    1     2    7.0             7.0   µg/m3
2 2018-01-01 03:00:00  2018    1    1     3    7.0             7.0   µg/m3
3 2018-01-01 04:00:00  2018    1    1     4    9.0             9.0   µg/m3
4 2018-01-01 05:00:00  2018    1    1     5    7.0             7.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

002
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/MP25/MG0036RA002.csv
iema
          VALOR_ORIGINAL UNIDADE            DATETIME
37765417           536.0   µg/m3 2021-06-06 14:30:00
37975445           361.0   µg/m3 2021-07-28 13:30:00
39725831           297.0   µg/m3 2022-11-20 14:30:00
34668080           259.0   µg/m3 2019-09-08 17:30:00
34656021           244.0   µg/m3 2019-09-05 15:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2018-01-01 01:00:00  2018    1    1     1    NaN             NaN   µg/m3
1 2018-01-01 02:00:00  2018    1    1     2    NaN             NaN   µg/m3
2 2018-01-01 03:00:00  2018    1    1     3    NaN             NaN   µg/m3
3 2018-01-01 04:00:00  2018    1    1     4    NaN             NaN   µg/m3
4 2018-01-01 05:00:00  2018    1    1     5    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2018-01-01 01:00:00  2018    1    1     1    NaN             NaN   µg/m3
1 2018-01-01 02:00:00  2018    1    1     2    NaN             NaN   µg/m3
2 2018-01-01 03:00:00  2018    1    1     3    NaN             NaN   µg/m3
3 2018-01-01 04:00:00  2018    1    1     4    NaN             NaN   µg/m3
4 2018-01-01 05:00:00  2018    1    1     5    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

002
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/MP25/MG0009RA002.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
34722619           126.0   µg/m3 2019-09-22 22:30:00
34685948           100.0   µg/m3 2019-09-13 08:30:00
34823692            71.0   µg/m3 2019-10-19 07:30:00
35560687            70.0   µg/m3 2017-04-11 14:30:00
34824165            68.0   µg/m3 2019-10-19 10:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2015-01-01 01:00:00  2015    1    1     1    NaN             NaN   µg/m3
1 2015-01-01 02:00:00  2015    1    1     2    NaN             NaN   µg/m3
2 2015-01-01 03:00:00  2015    1    1     3    NaN             NaN   µg/m3
3 2015-01-01 04:00:00  2015    1    1     4    NaN             NaN   µg/m3
4 2015-01-01 05:00:00  2015    1    1     5    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2015-01-01 01:00:00  2015    1    1     1    NaN             NaN   µg/m3
1 2015-01-01 02:00:00  2015    1    1     2    NaN             NaN   µg/m3
2 2015-01-01 03:00:00  2015    1    1     3    NaN             NaN   µg/m3
3 2015-01-01 04:00:00  2015    1    1     4    NaN             NaN   µg/m3
4 2015-01-01 05:00:00  2015    1    1     5    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
002
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/MP25/SP0284RA002.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
14893730           396.0   ug/m3 2018-07-21 07:00:00
14893729           374.0   ug/m3 2018-07-21 06:00:00
14893728           281.0   ug/m3 2018-07-21 05:00:00
7747553            245.0   ug/m3 2019-02-02 07:00:00
14893725           171.0   ug/m3 2018-07-21 02:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2016-07-20 01:00:00  2016    7   20     1   34.0            34.0   µg/m3
1 2016-07-20 02:00:00  2016    7   20     2   20.0            20.0   µg/m3
2 2016-07-20 03:00:00  2016    7   20     3   19.0            19.0   µg/m3
3 2016-07-20 04:00:00  2016    7   20     4   21.0            21.0   µg/m3
4 2016-07-20 05:00:00  2016    7   20     5   19.0            19.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2016-07-20 01:00:00  2016    7   20     1   34.0            34.0   ug/m3
1 2016-07-20 02:00:00  2016    7   20     2   20.0            20.0   ug/m3
2 2016-07-20 03:00:00  2016    7   20     3   19.0            19.0   ug/m3
3 2016-07-20 04:00:00  2016    7   20     4   21.0            21.0   ug/m3
4 2016-07-20 05:00:00  2016    7   20     5   19.0            19.0   ug/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
002
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/MP25/SP0086RA002.csv
iema
          VALOR_ORIGINAL UNIDADE            DATETIME
15324367           193.0   ug/m3 2018-07-16 03:00:00
15324366           170.0   ug/m3 2018-07-16 02:00:00
15324368           159.0   ug/m3 2018-07-16 04:00:00
16919276           140.0   ug/m3 2022-07-10 10:00:00
15324125           139.0   ug/m3 2018-07-06 01:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2018-01-05 01:00:00  2018    1    5     1   13.0            13.0   µg/m3
1 2018-01-05 02:00:00  2018    1    5     2   12.0            12.0   µg/m3
2 2018-01-05 03:00:00  2018    1    5     3    9.0             9.0   µg/m3
3 2018-01-05 04:00:00  2018    1    5     4    5.0             5.0   µg/m3
4 2018-01-05 05:00:00  2018    1    5     5   10.0            10.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2018-01-05 01:00:00  2018    1    5     1   13.0            13.0   ug/m3
1 2018-01-05 02:00:00  2018    1    5     2   12.0            12.0   ug/m3
2 2018-01-05 03:00:00  2018    1    5     3    9.0             9.0   ug/m3
3 2018-01-05 04:00:00  2018    1    5     4    5.0             5.0   ug/m3
4 2018-01-05 05:00:00  2018    1    5     5   10.0            10.0   ug/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

002
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/MP25/MG0061RA002.csv
iema
          VALOR_ORIGINAL UNIDADE            DATETIME
38176515            70.6   µg/m3 2021-09-16 07:30:00
32791850            53.0   µg/m3 2020-11-14 08:30:00
32548258            51.9   µg/m3 2020-09-06 08:30:00
38176353            51.8   µg/m3 2021-09-16 06:30:00
38230571            50.4   µg/m3 2021-09-29 23:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2020-01-01 01:00:00  2020    1    1     1    NaN             NaN   µg/m3
1 2020-01-01 02:00:00  2020    1    1     2    NaN             NaN   µg/m3
2 2020-01-01 03:00:00  2020    1    1     3    NaN             NaN   µg/m3
3 2020-01-01 04:00:00  2020    1    1     4    NaN             NaN   µg/m3
4 2020-01-01 05:00:00  2020    1    1     5    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2020-01-01 01:00:00  2020    1    1     1    NaN             NaN   µg/m3
1 2020-01-01 02:00:00  2020    1    1     2    NaN             NaN   µg/m3
2 2020-01-01 03:00:00  2020    1    1     3    NaN             NaN   µg/m3
3 2020-01-01 04:00:00  2020    1    1     4    NaN             NaN   µg/m3
4 2020-01-01 05:00:00  2020    1    1     5    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

002
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/MP25/MG0049RA002.csv
iema
          VALOR_ORIGINAL UNIDADE            DATETIME
37930561           163.3   µg/m3 2021-07-17 11:30:00
37451635           132.1   µg/m3 2021-03-16 09:30:00
37930386           104.2   µg/m3 2021-07-17 10:30:00
37983784           103.5   µg/m3 2021-07-30 15:30:00
32629368            95.6   µg/m3 2020-09-29 09:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2020-01-01 01:00:00  2020    1    1     1    NaN             NaN   µg/m3
1 2020-01-01 02:00:00  2020    1    1     2    NaN             NaN   µg/m3
2 2020-01-01 03:00:00  2020    1    1     3    NaN             NaN   µg/m3
3 2020-01-01 04:00:00  2020    1    1     4    NaN             NaN   µg/m3
4 2020-01-01 05:00:00  2020    1    1     5    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2020-01-01 01:00:00  2020    1    1     1    NaN             NaN   µg/m3
1 2020-01-01 02:00:00  2020    1    1     2    NaN             NaN   µg/m3
2 2020-01-01 03:00:00  2020    1    1     3    NaN             NaN   µg/m3
3 2020-01-01 04:00:00  2020    1    1     4    NaN             NaN   µg/m3
4 2020-01-01 05:00:00  2020    1    1     5    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

002
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/MP25/SP0091RA002.csv
iema
          VALOR_ORIGINAL UNIDADE            DATETIME
12304088            50.0   ug/m3 2016-06-16 01:00:00
7552116             47.0   ug/m3 2017-08-29 01:00:00
15505868            47.0   ug/m3 2018-07-29 01:00:00
17783979            43.0   ug/m3 2015-09-24 01:00:00
17783972            40.0   ug/m3 2015-08-01 01:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2024-02-05 14:00:00  2024    2    5    14    7.0             7.0   µg/m3
1 2024-02-05 15:00:00  2024    2    5    15    9.0             9.0   µg/m3
2 2024-02-05 16:00:00  2024    2    5    16    9.0             9.0   µg/m3
3 2024-02-05 17:00:00  2024    2    5    17    6.0             6.0   µg/m3
4 2024-02-05 18:00:00  2024    2    5    18    5.0             5.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2024-02-05 14:00:00  2024    2    5    14    7.0             7.0   µg/m3
1 2024-02-05 15:00:00  2024    2    5    15    9.0             9.0   µg/m3
2 2024-02-05 16:00:00  2024    2    5    16    9.0             9.0   µg/m3
3 2024-02-05 17:00:00  2024    2    5    17    6.0             6.0   µg/m3
4 2024-02-05 18:00:00  2024    2    5    18    5.0             5.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
002

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/MP25/SP0288RA002.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
11123631           314.0   ug/m3 2021-09-06 09:00:00
11123630           304.0   ug/m3 2021-09-06 08:00:00
11123632           279.0   ug/m3 2021-09-06 10:00:00
11123551           271.0   ug/m3 2021-09-03 01:00:00
11123552           262.0   ug/m3 2021-09-03 02:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2017-01-11 15:00:00  2017    1   11    15   10.0            10.0   µg/m3
1 2017-01-11 16:00:00  2017    1   11    16    NaN             NaN     NaN
2 2017-01-11 17:00:00  2017    1   11    17   13.0            13.0   µg/m3
3 2017-01-11 18:00:00  2017    1   11    18    2.0             2.0   µg/m3
4 2017-01-11 19:00:00  2017    1   11    19    8.0             8.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True     False
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2017-01-11 15:00:00  2017    1   11    15   10.0            10.0   ug/m3
1 2017-01-11 16:00:00  2017    1   11    16    NaN             NaN     NaN
2 2017-01-11 17:00:00  2017    1   11    17   13.0            13.0   ug/m3
3 2017-01-11 18:00:00  2017    1   11    18    2.0             2.0   ug/m3
4 2017-01-11 19:00:00  2017    1   11    19    8.0             8.0   ug/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True     False
2          True      True
3          True      True
4          True      True
002
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/MP25/MG0039RA002.csv
iema
          VALOR_ORIGINAL UNIDADE            DATETIME
36770497           407.0   µg/m3 2018-08-25 11:30:00
34412361           311.0   µg/m3 2019-07-02 19:30:00
34412512           296.0   µg/m3 2019-07-02 20:30:00
37726927           290.0   µg/m3 2021-05-27 12:30:00
34545325           273.0   µg/m3 2019-08-07 13:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2017-05-03 09:00:00  2017    5    3     9    NaN             NaN   µg/m3
1 2017-05-03 10:00:00  2017    5    3    10    NaN             NaN   µg/m3
2 2017-05-03 11:00:00  2017    5    3    11    NaN             NaN   µg/m3
3 2017-05-03 12:00:00  2017    5    3    12    NaN             NaN   µg/m3
4 2017-05-03 13:00:00  2017    5    3    13    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2017-05-03 09:00:00  2017    5    3     9    NaN             NaN   µg/m3
1 2017-05-03 10:00:00  2017    5    3    10    NaN             NaN   µg/m3
2 2017-05-03 11:00:00  2017    5    3    11    NaN             NaN   µg/m3
3 2017-05-03 12:00:00  2017    5    3    12    NaN             NaN   µg/m3
4 2017-05-03 13:00:00  2017    5    3    13    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

002
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/MP25/MG0032RA002.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
33819259           109.0   µg/m3 2019-01-12 03:30:00
33836465           104.0   µg/m3 2019-01-17 03:30:00
38176254           100.0   µg/m3 2021-09-16 06:30:00
38176580            93.0   µg/m3 2021-09-16 08:30:00
40685664            82.0   µg/m3 2016-06-14 17:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2016-02-18 11:00:00  2016    2   18    11    NaN             NaN   µg/m3
1 2016-02-18 12:00:00  2016    2   18    12    NaN             NaN   µg/m3
2 2016-02-18 13:00:00  2016    2   18    13    NaN             NaN   µg/m3
3 2016-02-18 14:00:00  2016    2   18    14    NaN             NaN   µg/m3
4 2016-02-18 15:00:00  2016    2   18    15    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2016-02-18 11:00:00  2016    2   18    11    NaN             NaN   µg/m3
1 2016-02-18 12:00:00  2016    2   18    12    NaN             NaN   µg/m3
2 2016-02-18 13:00:00  2016    2   18    13    NaN             NaN   µg/m3
3 2016-02-18 14:00:00  2016    2   18    14    NaN             NaN   µg/m3
4 2016-02-18 15:00:00  2016    2   18    15    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
002
002
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/MP25/MG0040RA002.csv
iema
          VALOR_ORIGINAL UNIDADE            DATETIME
35878410           175.0   µg/m3 2017-09-24 19:30:00
32574051           166.0   µg/m3 2020-09-13 17:30:00
35878547           153.0   µg/m3 2017-09-24 18:30:00
35878641           143.0   µg/m3 2017-08-09 18:30:00
34714347           130.0   µg/m3 2019-09-20 17:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2017-06-28 16:00:00  2017    6   28    16    NaN             NaN   µg/m3
1 2017-06-28 17:00:00  2017    6   28    17    NaN             NaN   µg/m3
2 2017-06-28 18:00:00  2017    6   28    18    NaN             NaN   µg/m3
3 2017-06-28 19:00:00  2017    6   28    19    NaN             NaN   µg/m3
4 2017-06-28 20:00:00  2017    6   28    20    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2017-06-28 16:00:00  2017    6   28    16    NaN             NaN   µg/m3
1 2017-06-28 17:00:00  2017    6   28    17    NaN             NaN   µg/m3
2 2017-06-28 18:00:00  2017    6   28    18    NaN             NaN   µg/m3
3 2017-06-28 19:00:00  2017    6   28    19    NaN             NaN   µg/m3
4 2017-06-28 20:00:00  2017    6   28    20    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

002
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/MP25/SP0116RA002.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
17687797           390.0   ug/m3 2015-08-10 15:00:00
11455010           234.0   ug/m3 2021-08-17 04:00:00
12166448           229.0   ug/m3 2016-08-06 22:00:00
11455011           224.0   ug/m3 2021-08-17 05:00:00
12166449           222.0   ug/m3 2016-08-06 23:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2013-01-01 01:00:00  2013    1    1     1   24.0            24.0   µg/m3
1 2013-01-01 02:00:00  2013    1    1     2   26.0            26.0   µg/m3
2 2013-01-01 03:00:00  2013    1    1     3   14.0            14.0   µg/m3
3 2013-01-01 04:00:00  2013    1    1     4   14.0            14.0   µg/m3
4 2013-01-01 05:00:00  2013    1    1     5   15.0            15.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2013-01-01 01:00:00  2013    1    1     1   24.0            24.0   µg/m3
1 2013-01-01 02:00:00  2013    1    1     2   26.0            26.0   µg/m3
2 2013-01-01 03:00:00  2013    1    1     3   14.0            14.0   µg/m3
3 2013-01-01 04:00:00  2013    1    1     4   14.0            14.0   µg/m3
4 2013-01-01 05:00:00  2013    1    1     5   15.0            15.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
002
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/MP25/SP0289RA002.csv
iema
          VALOR_ORIGINAL UNIDADE            DATETIME
15921609           100.0   ug/m3 2021-10-16 20:00:00
13550804            77.0   ug/m3 2019-08-11 01:00:00
13551780            69.0   ug/m3 2019-09-20 17:00:00
13546061            68.0   ug/m3 2019-01-22 16:00:00
15921109            67.0   ug/m3 2021-09-24 18:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2018-01-01 01:00:00  2018    1    1     1   18.0            18.0   µg/m3
1 2018-01-01 02:00:00  2018    1    1     2   15.0            15.0   µg/m3
2 2018-01-01 03:00:00  2018    1    1     3   12.0            12.0   µg/m3
3 2018-01-01 04:00:00  2018    1    1     4   14.0            14.0   µg/m3
4 2018-01-01 05:00:00  2018    1    1     5   13.0            13.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2018-01-01 01:00:00  2018    1    1     1   18.0            18.0   ug/m3
1 2018-01-01 02:00:00  2018    1    1     2   15.0            15.0   ug/m3
2 2018-01-01 03:00:00  2018    1    1     3   12.0            12.0   ug/m3
3 2018-01-01 04:00:00  2018    1    1     4   14.0            14.0   ug/m3
4 2018-01-01 05:00:00  2018    1    1     5   13.0            13.0   ug/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

002
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/MP25/MG0001RA002.csv

/tmp/ipykernel_273420/1352582357.py:97: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  df_mma = pd.read_csv(arquivo, encoding = 'UTF-8')
/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
36662271           921.0   µg/m3 2018-07-22 11:30:00
34326338           234.0   µg/m3 2019-06-08 04:30:00
34326476           213.0   µg/m3 2019-06-08 05:30:00
39963362           135.0   µg/m3 2016-05-19 07:30:00
34822086           134.0   µg/m3 2019-10-18 21:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR VALOR_ORIGINAL UNIDADE  \
0 2009-01-01 01:00:00  2009    1    1     1    NaN              *   µg/m3
1 2009-01-01 02:00:00  2009    1    1     2    NaN              *   µg/m3
2 2009-01-01 03:00:00  2009    1    1     3    NaN              *   µg/m3
3 2009-01-01 04:00:00  2009    1    1     4    NaN              *   µg/m3
4 2009-01-01 05:00:00  2009    1    1     5    NaN              *   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR VALOR_ORIGINAL UNIDADE  \
0 2009-01-01 01:00:00  2009    1    1     1    NaN              *   µg/m3
1 2009-01-01 02:00:00  2009    1    1     2    NaN              *   µg/m3
2 2009-01-01 03:00:00  2009    1    1     3    NaN              *   µg/m3
3 2009-01-01 04:00:00  2009    1    1     4    NaN              *   µg/m3
4 2009-01-01 05:00:00  2009    1    1     5    NaN              *   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
002
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/MP25/SP0120RA002.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
14771349           318.0   ug/m3 2018-07-16 21:00:00
14772640           183.0   ug/m3 2018-09-08 17:00:00
10864894           173.0   ug/m3 2021-08-23 01:00:00
14771350           171.0   ug/m3 2018-07-16 22:00:00
14767455           169.0   ug/m3 2018-01-31 14:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2017-07-09 01:00:00  2017    7    9     1   51.0            51.0   µg/m3
1 2017-07-09 02:00:00  2017    7    9     2   30.0            30.0   µg/m3
2 2017-07-09 03:00:00  2017    7    9     3   36.0            36.0   µg/m3
3 2017-07-09 04:00:00  2017    7    9     4   45.0            45.0   µg/m3
4 2017-07-09 05:00:00  2017    7    9     5   42.0            42.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2017-07-09 01:00:00  2017    7    9     1   51.0            51.0   ug/m3
1 2017-07-09 02:00:00  2017    7    9     2   30.0            30.0   ug/m3
2 2017-07-09 03:00:00  2017    7    9     3   36.0            36.0   ug/m3
3 2017-07-09 04:00:00  2017    7    9     4   45.0            45.0   ug/m3
4 2017-07-09 05:00:00  2017    7    9     5   42.0            42.0   ug/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
002
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/MP25/MG0006RA002.csv

/tmp/ipykernel_273420/1352582357.py:97: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  df_mma = pd.read_csv(arquivo, encoding = 'UTF-8')
/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
32558401           202.0   µg/m3 2020-09-09 05:30:00
40058432           202.0   µg/m3 2016-07-14 00:30:00
40058491           179.0   µg/m3 2016-08-09 01:30:00
32568696           177.0   µg/m3 2020-09-12 04:30:00
33786922           176.0   µg/m3 2019-01-03 01:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR VALOR_ORIGINAL UNIDADE  \
0 2010-01-01 01:00:00  2010    1    1     1    NaN              *   µg/m3
1 2010-01-01 02:00:00  2010    1    1     2    NaN              *   µg/m3
2 2010-01-01 03:00:00  2010    1    1     3    NaN              *   µg/m3
3 2010-01-01 04:00:00  2010    1    1     4    NaN              *   µg/m3
4 2010-01-01 05:00:00  2010    1    1     5    NaN              *   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR VALOR_ORIGINAL UNIDADE  \
0 2010-01-01 01:00:00  2010    1    1     1    NaN              *   µg/m3
1 2010-01-01 02:00:00  2010    1    1     2    NaN              *   µg/m3
2 2010-01-01 03:00:00  2010    1    1     3    NaN              *   µg/m3
3 2010-01-01 04:00:00  2010    1    1     4    NaN              *   µg/m3
4 2010-01-01 05:00:00  2010    1    1     5    NaN              *   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
002
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/MP25/SP0085RA002.csv
iema
          VALOR_ORIGINAL UNIDADE            DATETIME
9169064            164.0   ug/m3 2022-01-01 02:00:00
9169065            126.0   ug/m3 2022-01-01 03:00:00
14721110           124.0   ug/m3 2018-06-27 02:00:00
14721260           123.0   ug/m3 2018-07-03 08:00:00
14721502           119.0   ug/m3 2018-07-13 10:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2018-01-25 01:00:00  2018    1   25     1   24.0            24.0   µg/m3
1 2018-01-25 02:00:00  2018    1   25     2   24.0            24.0   µg/m3
2 2018-01-25 03:00:00  2018    1   25     3   15.0            15.0   µg/m3
3 2018-01-25 04:00:00  2018    1   25     4    7.0             7.0   µg/m3
4 2018-01-25 05:00:00  2018    1   25     5    8.0             8.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2018-01-25 01:00:00  2018    1   25     1   24.0            24.0   ug/m3
1 2018-01-25 02:00:00  2018    1   25     2   24.0            24.0   ug/m3
2 2018-01-25 03:00:00  2018    1   25     3   15.0            15.0   ug/m3
3 2018-01-25 04:00:00  2018    1   25     4    7.0             7.0   ug/m3
4 2018-01-25 05:00:00  2018    1   25     5    8.0             8.0   ug/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

002
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/MP25/MG0011RA002.csv
iema
          VALOR_ORIGINAL UNIDADE            DATETIME
37872406           193.0   µg/m3 2021-07-03 12:30:00
39365171           124.0   µg/m3 2022-08-12 23:30:00
39377500           118.0   µg/m3 2022-08-16 06:30:00
32436029           116.0   µg/m3 2020-08-06 17:30:00
32126198           116.0   µg/m3 2020-05-10 10:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2020-01-01 02:00:00  2020    1    1     2    NaN             NaN     NaN
1 2020-01-01 03:00:00  2020    1    1     3    NaN             NaN     NaN
2 2020-01-01 04:00:00  2020    1    1     4    NaN             NaN     NaN
3 2020-01-01 05:00:00  2020    1    1     5    NaN             NaN     NaN
4 2020-01-01 06:00:00  2020    1    1     6    NaN             NaN     NaN

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2020-01-01 02:00:00  2020    1    1     2    NaN             NaN     NaN
1 2020-01-01 03:00:00  2020    1    1     3    NaN             NaN     NaN
2 2020-01-01 04:00:00  2020    1    1     4    NaN             NaN     NaN
3 2020-01-01 05:00:00  2020    1    1     5    NaN             NaN     NaN
4 2020-01-01 06:00:00  2020    1    1     6    NaN             NaN     NaN

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

002
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/MP25/MG0002RA002.csv

/tmp/ipykernel_273420/1352582357.py:97: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  df_mma = pd.read_csv(arquivo, encoding = 'UTF-8')
/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
38199313           122.0   µg/m3 2021-09-22 01:30:00
37809829           114.0   µg/m3 2021-06-17 22:30:00
39200298           113.0   µg/m3 2022-06-28 17:30:00
37833040           107.0   µg/m3 2021-06-23 18:30:00
38199469           106.0   µg/m3 2021-09-22 02:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR VALOR_ORIGINAL UNIDADE  \
0 2009-01-01 01:00:00  2009    1    1     1    NaN              *   µg/m3
1 2009-01-01 02:00:00  2009    1    1     2    NaN              *   µg/m3
2 2009-01-01 03:00:00  2009    1    1     3    NaN              *   µg/m3
3 2009-01-01 04:00:00  2009    1    1     4    NaN              *   µg/m3
4 2009-01-01 05:00:00  2009    1    1     5    NaN              *   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR VALOR_ORIGINAL UNIDADE  \
0 2009-01-01 01:00:00  2009    1    1     1    NaN              *   µg/m3
1 2009-01-01 02:00:00  2009    1    1     2    NaN              *   µg/m3
2 2009-01-01 03:00:00  2009    1    1     3    NaN              *   µg/m3
3 2009-01-01 04:00:00  2009    1    1     4    NaN              *   µg/m3
4 2009-01-01 05:00:00  2009    1    1     5    NaN              *   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
002
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/MP25/MG0057RA002.csv
iema
          VALOR_ORIGINAL UNIDADE            DATETIME
34707448           251.0   µg/m3 2019-09-18 21:30:00
34707616           187.0   µg/m3 2019-09-18 22:30:00
34707281           185.0   µg/m3 2019-09-18 20:30:00
34810977           171.0   µg/m3 2019-10-16 00:30:00
34711159           159.0   µg/m3 2019-09-19 20:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2019-01-01 01:00:00  2019    1    1     1    NaN             NaN   µg/m3
1 2019-01-01 02:00:00  2019    1    1     2    NaN             NaN   µg/m3
2 2019-01-01 03:00:00  2019    1    1     3   20.0            20.0   µg/m3
3 2019-01-01 04:00:00  2019    1    1     4   24.0            24.0   µg/m3
4 2019-01-01 05:00:00  2019    1    1     5    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True      True
3          True      True
4          True     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2019-01-01 01:00:00  2019    1    1     1    NaN             NaN   µg/m3
1 2019-01-01 02:00:00  2019    1    1     2    NaN             NaN   µg/m3
2 2019-01-01 03:00:00  2019    1    1     3   20.0            20.0   µg/m3
3 2019-01-01 04:00:00  2019    1    1     4   24.0            24.0   µg/m3
4 2019-01-01 05:00:00  2019    1    1     5    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True      True
3          True      True
4          True     False

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

002
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/MP25/MG0028RA002.csv
iema
          VALOR_ORIGINAL UNIDADE            DATETIME
38156917           317.0   µg/m3 2021-09-11 08:30:00
37611474           269.0   µg/m3 2021-04-27 12:30:00
38275023           177.0   µg/m3 2021-10-11 15:30:00
38298635           153.7   µg/m3 2021-10-18 03:30:00
37188935           123.0   µg/m3 2021-01-01 18:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2020-01-01 01:00:00  2020    1    1     1    NaN             NaN   µg/m3
1 2020-01-01 02:00:00  2020    1    1     2    NaN             NaN   µg/m3
2 2020-01-01 03:00:00  2020    1    1     3    NaN             NaN   µg/m3
3 2020-01-01 04:00:00  2020    1    1     4    NaN             NaN   µg/m3
4 2020-01-01 05:00:00  2020    1    1     5    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2020-01-01 01:00:00  2020    1    1     1    NaN             NaN   µg/m3
1 2020-01-01 02:00:00  2020    1    1     2    NaN             NaN   µg/m3
2 2020-01-01 03:00:00  2020    1    1     3    NaN             NaN   µg/m3
3 2020-01-01 04:00:00  2020    1    1     4    NaN             NaN   µg/m3
4 2020-01-01 05:00:00  2020    1    1     5    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

002
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/MP25/MG0012RA002.csv

/tmp/ipykernel_273420/1352582357.py:97: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  df_mma = pd.read_csv(arquivo, encoding = 'UTF-8')
/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
40202914           133.0   µg/m3 2016-03-23 06:30:00
34131781           132.0   µg/m3 2019-04-14 12:30:00
40202943           128.0   µg/m3 2016-03-13 11:30:00
40202950           127.0   µg/m3 2016-03-23 07:30:00
36649107           116.0   µg/m3 2018-07-18 06:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR VALOR_ORIGINAL UNIDADE  \
0 2014-01-01 01:00:00  2014    1    1     1    NaN              *   µg/m3
1 2014-01-01 02:00:00  2014    1    1     2    NaN              *   µg/m3
2 2014-01-01 03:00:00  2014    1    1     3    NaN              *   µg/m3
3 2014-01-01 04:00:00  2014    1    1     4    NaN              *   µg/m3
4 2014-01-01 05:00:00  2014    1    1     5    NaN              *   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR VALOR_ORIGINAL UNIDADE  \
0 2014-01-01 01:00:00  2014    1    1     1    NaN              *   µg/m3
1 2014-01-01 02:00:00  2014    1    1     2    NaN              *   µg/m3
2 2014-01-01 03:00:00  2014    1    1     3    NaN              *   µg/m3
3 2014-01-01 04:00:00  2014    1    1     4    NaN              *   µg/m3
4 2014-01-01 05:00:00  2014    1    1     5    NaN              *   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
002
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/MP25/MG0016RA002.csv
iema
          VALOR_ORIGINAL UNIDADE            DATETIME
32340938           161.0   µg/m3 2020-07-09 18:30:00
37856550           145.0   µg/m3 2021-06-29 16:30:00
32209138           141.0   µg/m3 2020-06-02 18:30:00
37685097           118.0   µg/m3 2021-05-16 19:30:00
38098703           110.0   µg/m3 2021-08-27 18:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2020-01-01 01:00:00  2020    1    1     1    NaN             NaN   µg/m3
1 2020-01-01 02:00:00  2020    1    1     2    NaN             NaN   µg/m3
2 2020-01-01 03:00:00  2020    1    1     3    NaN             NaN   µg/m3
3 2020-01-01 04:00:00  2020    1    1     4    NaN             NaN   µg/m3
4 2020-01-01 05:00:00  2020    1    1     5    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2020-01-01 01:00:00  2020    1    1     1    NaN             NaN   µg/m3
1 2020-01-01 02:00:00  2020    1    1     2    NaN             NaN   µg/m3
2 2020-01-01 03:00:00  2020    1    1     3    NaN             NaN   µg/m3
3 2020-01-01 04:00:00  2020    1    1     4    NaN             NaN   µg/m3
4 2020-01-01 05:00:00  2020    1    1     5    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

002
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/MP25/SP0109RA002.csv
iema
          VALOR_ORIGINAL UNIDADE            DATETIME
12938235           130.0   ug/m3 2020-09-19 02:00:00
12938234           130.0   ug/m3 2020-09-19 01:00:00
13781807           126.0   ug/m3 2019-10-03 03:00:00
12938574           107.0   ug/m3 2020-10-03 05:00:00
12938690           106.0   ug/m3 2020-10-08 01:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2019-02-21 01:00:00  2019    2   21     1    9.0             9.0   µg/m3
1 2019-02-21 02:00:00  2019    2   21     2    8.0             8.0   µg/m3
2 2019-02-21 03:00:00  2019    2   21     3    6.0             6.0   µg/m3
3 2019-02-21 04:00:00  2019    2   21     4    9.0             9.0   µg/m3
4 2019-02-21 05:00:00  2019    2   21     5    6.0             6.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2019-02-21 01:00:00  2019    2   21     1    9.0             9.0   ug/m3
1 2019-02-21 02:00:00  2019    2   21     2    8.0             8.0   ug/m3
2 2019-02-21 03:00:00  2019    2   21     3    6.0             6.0   ug/m3
3 2019-02-21 04:00:00  2019    2   21     4    9.0             9.0   ug/m3
4 2019-02-21 05:00:00  2019    2   21     5    6.0             6.0   ug/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

002
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/MP25/MG0058RA002.csv
iema
          VALOR_ORIGINAL UNIDADE            DATETIME
34710664           205.4   µg/m3 2019-09-19 17:30:00
34797492           194.4   µg/m3 2019-10-12 14:30:00
35030354           164.1   µg/m3 2019-12-15 11:30:00
38174552           156.7   µg/m3 2021-09-15 19:30:00
34844708           146.2   µg/m3 2019-10-24 22:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2019-07-30 13:00:00  2019    7   30    13    5.5             5.5   µg/m3
1 2019-07-30 14:00:00  2019    7   30    14    4.1             4.1   µg/m3
2 2019-07-30 15:00:00  2019    7   30    15    NaN             NaN   µg/m3
3 2019-07-30 16:00:00  2019    7   30    16    5.4             5.4   µg/m3
4 2019-07-30 17:00:00  2019    7   30    17    6.5             6.5   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True     False
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2019-07-30 13:00:00  2019    7   30    13    5.5             5.5   µg/m3
1 2019-07-30 14:00:00  2019    7   30    14    4.1             4.1   µg/m3
2 2019-07-30 15:00:00  2019    7   30    15    NaN             NaN   µg/m3
3 2019-07-30 16:00:00  2019    7   30    16    5.4             5.4   µg/m3
4 2019-07-30 17:00:00  2019    7   30    17    6.5             6.5   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True     False
3          True      True
4          True      True

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

002
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/MP25/MG0014RA002.csv
iema
          VALOR_ORIGINAL UNIDADE            DATETIME
32598336           155.0   µg/m3 2020-09-20 19:30:00
32627360           123.0   µg/m3 2020-09-28 20:30:00
32598191           123.0   µg/m3 2020-09-20 18:30:00
32512323           120.0   µg/m3 2020-08-27 18:30:00
32549841           118.0   µg/m3 2020-09-06 19:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2020-01-01 03:00:00  2020    1    1     3    NaN             NaN     NaN
1 2020-01-01 04:00:00  2020    1    1     4    NaN             NaN     NaN
2 2020-01-01 05:00:00  2020    1    1     5    NaN             NaN     NaN
3 2020-01-01 06:00:00  2020    1    1     6    NaN             NaN     NaN
4 2020-01-01 07:00:00  2020    1    1     7    NaN             NaN     NaN

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2020-01-01 03:00:00  2020    1    1     3    NaN             NaN     NaN
1 2020-01-01 04:00:00  2020    1    1     4    NaN             NaN     NaN
2 2020-01-01 05:00:00  2020    1    1     5    NaN             NaN     NaN
3 2020-01-01 06:00:00  2020    1    1     6    NaN             NaN     NaN
4 2020-01-01 07:00:00  2020    1    1     7    NaN             NaN     NaN

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

002
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/MP25/MG0059RA002.csv
iema
          VALOR_ORIGINAL UNIDADE            DATETIME
38172774           129.0   µg/m3 2021-09-15 08:30:00
38176853            49.2   µg/m3 2021-09-16 09:30:00
32459838            45.0   µg/m3 2020-08-13 06:30:00
38241580            44.9   µg/m3 2021-10-02 18:30:00
32581082            44.0   µg/m3 2020-09-15 18:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2020-01-01 01:00:00  2020    1    1     1    NaN             NaN   µg/m3
1 2020-01-01 02:00:00  2020    1    1     2    NaN             NaN   µg/m3
2 2020-01-01 03:00:00  2020    1    1     3    NaN             NaN   µg/m3
3 2020-01-01 04:00:00  2020    1    1     4    NaN             NaN   µg/m3
4 2020-01-01 05:00:00  2020    1    1     5    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2020-01-01 01:00:00  2020    1    1     1    NaN             NaN   µg/m3
1 2020-01-01 02:00:00  2020    1    1     2    NaN             NaN   µg/m3
2 2020-01-01 03:00:00  2020    1    1     3    NaN             NaN   µg/m3
3 2020-01-01 04:00:00  2020    1    1     4    NaN             NaN   µg/m3
4 2020-01-01 05:00:00  2020    1    1     5    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

002
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/MP25/SP0293RA002.csv
iema
          VALOR_ORIGINAL UNIDADE            DATETIME
10995840           297.0   ug/m3 2021-08-23 01:00:00
10995848           275.0   ug/m3 2021-08-23 09:00:00
10995847           260.0   ug/m3 2021-08-23 08:00:00
10995841           255.0   ug/m3 2021-08-23 02:00:00
10995846           211.0   ug/m3 2021-08-23 07:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2019-03-10 01:00:00  2019    3   10     1   19.0            19.0   µg/m3
1 2019-03-10 02:00:00  2019    3   10     2   13.0            13.0   µg/m3
2 2019-03-10 03:00:00  2019    3   10     3    5.0             5.0   µg/m3
3 2019-03-10 04:00:00  2019    3   10     4    1.0             1.0   µg/m3
4 2019-03-10 05:00:00  2019    3   10     5    6.0             6.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2019-03-10 01:00:00  2019    3   10     1   19.0            19.0   ug/m3
1 2019-03-10 02:00:00  2019    3   10     2   13.0            13.0   ug/m3
2 2019-03-10 03:00:00  2019    3   10     3    5.0             5.0   ug/m3
3 2019-03-10 04:00:00  2019    3   10     4    1.0             1.0   ug/m3
4 2019-03-10 05:00:00  2019    3   10     5    6.0             6.0   ug/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

002
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/MP25/SP0083RA002.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
18519385           119.0   ug/m3 2017-08-29 22:00:00
8897399            114.0   ug/m3 2022-09-09 08:00:00
8897398            110.0   ug/m3 2022-09-09 07:00:00
16025823           109.0   ug/m3 2021-09-12 20:00:00
16025822           102.0   ug/m3 2021-09-12 19:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2014-04-13 01:00:00  2014    4   13     1    5.0             5.0   µg/m3
1 2014-04-13 02:00:00  2014    4   13     2    NaN             0.0   µg/m3
2 2014-04-13 03:00:00  2014    4   13     3    5.0             5.0   µg/m3
3 2014-04-13 04:00:00  2014    4   13     4    7.0             7.0   µg/m3
4 2014-04-13 05:00:00  2014    4   13     5    NaN             0.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True     False
2          True      True
3          True      True
4          True     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2014-04-13 01:00:00  2014    4   13     1    5.0             5.0   µg/m3
1 2014-04-13 02:00:00  2014    4   13     2    NaN             0.0   µg/m3
2 2014-04-13 03:00:00  2014    4   13     3    5.0             5.0   µg/m3
3 2014-04-13 04:00:00  2014    4   13     4    7.0             7.0   µg/m3
4 2014-04-13 05:00:00  2014    4   13     5    NaN             0.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True     False
2          True      True
3          True      True
4          True     False
002
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/MP25/SP0273RA002.csv
iema
          VALOR_ORIGINAL UNIDADE            DATETIME
11304887           209.0   ug/m3 2021-08-09 11:00:00
10525636           199.0   ug/m3 2020-01-04 22:00:00
11305100           186.0   ug/m3 2021-08-18 10:00:00
11304888           175.0   ug/m3 2021-08-09 12:00:00
11305099           161.0   ug/m3 2021-08-18 09:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2018-08-10 01:00:00  2018    8   10     1    8.0             8.0   µg/m3
1 2018-08-10 02:00:00  2018    8   10     2    7.0             7.0   µg/m3
2 2018-08-10 03:00:00  2018    8   10     3    9.0             9.0   µg/m3
3 2018-08-10 04:00:00  2018    8   10     4    7.0             7.0   µg/m3
4 2018-08-10 05:00:00  2018    8   10     5   12.0            12.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2018-08-10 01:00:00  2018    8   10     1    8.0             8.0   ug/m3
1 2018-08-10 02:00:00  2018    8   10     2    7.0             7.0   ug/m3
2 2018-08-10 03:00:00  2018    8   10     3    9.0             9.0   ug/m3
3 2018-08-10 04:00:00  2018    8   10     4    7.0             7.0   ug/m3
4 2018-08-10 05:00:00  2018    8   10     5   12.0            12.0   ug/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

002
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/MP25/MG0038RA002.csv
iema
          VALOR_ORIGINAL UNIDADE            DATETIME
32312286           578.0   µg/m3 2020-07-01 16:30:00
32273806           442.0   µg/m3 2020-06-20 17:30:00
32312436           378.0   µg/m3 2020-07-01 17:30:00
32266912           292.0   µg/m3 2020-06-18 17:30:00
35949414           266.0   µg/m3 2017-07-20 19:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2017-01-04 20:00:00  2017    1    4    20    NaN             NaN   µg/m3
1 2017-01-04 21:00:00  2017    1    4    21    NaN             NaN   µg/m3
2 2017-01-04 22:00:00  2017    1    4    22    NaN             NaN   µg/m3
3 2017-01-04 23:00:00  2017    1    4    23    NaN             NaN   µg/m3
4 2017-01-05 00:00:00  2017    1    5     0    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2017-01-04 20:00:00  2017    1    4    20    NaN             NaN   µg/m3
1 2017-01-04 21:00:00  2017    1    4    21    NaN             NaN   µg/m3
2 2017-01-04 22:00:00  2017    1    4    22    NaN             NaN   µg/m3
3 2017-01-04 23:00:00  2017    1    4    23    NaN             NaN   µg/m3
4 2017-01-05 00:00:00  2017    1    5     0    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

002
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/MP25/MG0060RA002.csv
iema
          VALOR_ORIGINAL UNIDADE            DATETIME
38038570           162.3   µg/m3 2021-08-12 21:30:00
38038738           147.9   µg/m3 2021-08-12 22:30:00
38038909           122.2   µg/m3 2021-08-12 23:30:00
38038227            80.4   µg/m3 2021-08-12 19:30:00
38038398            80.4   µg/m3 2021-08-12 20:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2020-01-01 01:00:00  2020    1    1     1    NaN             NaN   µg/m3
1 2020-01-01 02:00:00  2020    1    1     2    NaN             NaN   µg/m3
2 2020-01-01 03:00:00  2020    1    1     3    NaN             NaN   µg/m3
3 2020-01-01 04:00:00  2020    1    1     4    NaN             NaN   µg/m3
4 2020-01-01 05:00:00  2020    1    1     5    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2020-01-01 01:00:00  2020    1    1     1    NaN             NaN   µg/m3
1 2020-01-01 02:00:00  2020    1    1     2    NaN             NaN   µg/m3
2 2020-01-01 03:00:00  2020    1    1     3    NaN             NaN   µg/m3
3 2020-01-01 04:00:00  2020    1    1     4    NaN             NaN   µg/m3
4 2020-01-01 05:00:00  2020    1    1     5    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

002
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/MP25/MG0025RA002.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
40279875           570.0   µg/m3 2016-06-22 10:30:00
40279876           566.0   µg/m3 2016-08-30 17:30:00
33277026           513.0   µg/m3 2015-10-14 20:30:00
40279879           472.0   µg/m3 2016-09-01 17:30:00
33277028           452.0   µg/m3 2015-10-14 17:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2015-04-06 14:00:00  2015    4    6    14    NaN             NaN   µg/m3
1 2015-04-06 15:00:00  2015    4    6    15    NaN             NaN   µg/m3
2 2015-04-06 16:00:00  2015    4    6    16    NaN             NaN   µg/m3
3 2015-04-06 17:00:00  2015    4    6    17   11.0            11.0   µg/m3
4 2015-04-06 18:00:00  2015    4    6    18   17.0            17.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2015-04-06 14:00:00  2015    4    6    14    NaN             NaN   µg/m3
1 2015-04-06 15:00:00  2015    4    6    15    NaN             NaN   µg/m3
2 2015-04-06 16:00:00  2015    4    6    16    NaN             NaN   µg/m3
3 2015-04-06 17:00:00  2015    4    6    17   11.0            11.0   µg/m3
4 2015-04-06 18:00:00  2015    4    6    18   17.0            17.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True      True
4          True      True
002
002
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/MP25/MG0052RA002.csv
iema
          VALOR_ORIGINAL UNIDADE            DATETIME
38479745           355.0   µg/m3 2021-12-05 11:30:00
38480070           283.4   µg/m3 2021-12-05 13:30:00
38480233           200.0   µg/m3 2021-12-05 14:30:00
37202629           185.7   µg/m3 2021-01-05 17:30:00
38268738           178.8   µg/m3 2021-10-09 20:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2020-01-01 01:00:00  2020    1    1     1    NaN             NaN   µg/m3
1 2020-01-01 02:00:00  2020    1    1     2    NaN             NaN   µg/m3
2 2020-01-01 03:00:00  2020    1    1     3    NaN             NaN   µg/m3
3 2020-01-01 04:00:00  2020    1    1     4    NaN             NaN   µg/m3
4 2020-01-01 05:00:00  2020    1    1     5    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2020-01-01 01:00:00  2020    1    1     1    NaN             NaN   µg/m3
1 2020-01-01 02:00:00  2020    1    1     2    NaN             NaN   µg/m3
2 2020-01-01 03:00:00  2020    1    1     3    NaN             NaN   µg/m3
3 2020-01-01 04:00:00  2020    1    1     4    NaN             NaN   µg/m3
4 2020-01-01 05:00:00  2020    1    1     5    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

002
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/MP25/RJ0070RA002.csv
iema
          VALOR_ORIGINAL UNIDADE            DATETIME
22901259           97.50   ug/m3 2022-07-29 09:00:00
22897845           90.67   ug/m3 2022-03-07 23:00:00
24595453           82.36   µg/m³ 2021-08-22 07:00:00
22902120           78.41   ug/m3 2022-09-03 07:00:00
24595883           78.38   µg/m³ 2021-09-09 16:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2020-10-01 00:00:00  2020   10    1     0    NaN             NaN   µg/m³
1 2020-10-01 01:00:00  2020   10    1     1    NaN             NaN   µg/m³
2 2020-10-01 02:00:00  2020   10    1     2    NaN             NaN   µg/m³
3 2020-10-01 03:00:00  2020   10    1     3    NaN             NaN   µg/m³
4 2020-10-01 04:00:00  2020   10    1     4    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0         False     False
1         False     False
2         False     False
3         False     False
4         False     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2020-10-01 00:00:00  2020   10    1     0    NaN             NaN   µg/m³
1 2020-10-01 01:00:00  2020   10    1     1    NaN             NaN   µg/m³
2 2020-10-01 02:00:00  2020   10    1     2    NaN             NaN   µg/m³
3 2020-10-01 03:00:00  2020   10    1     3    NaN             NaN   µg/m³
4 2020-10-01 04:00:00  2020   10    1     4    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

002
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/MP25/MG0017RA002.csv
iema
          VALOR_ORIGINAL UNIDADE            DATETIME
38166917           138.0   µg/m3 2021-09-13 21:30:00
34916097            95.0   µg/m3 2019-11-13 03:30:00
39064232            93.0   µg/m3 2022-05-21 17:30:00
38166752            87.0   µg/m3 2021-09-13 20:30:00
38131909            86.0   µg/m3 2021-09-04 22:30:00
mma
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2015-01-01 01:00:00  2015.0  1.0  1.0   1.0    NaN             NaN   µg/m3
1 2015-01-01 02:00:00  2015.0  1.0  1.0   2.0    NaN             NaN   µg/m3
2 2015-01-01 03:00:00  2015.0  1.0  1.0   3.0    NaN             NaN   µg/m3
3 2015-01-01 04:00:00  2015.0  1.0  1.0   4.0    NaN             NaN   µg/m3
4 2015-01-01 05:00:00  2015.0  1.0  1.0   5.0    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2015-01-01 01:00:00  2015.0  1.0  1.0   1.0    NaN             NaN   µg/m3
1 2015-01-01 02:00:00  2015.0  1.0  1.0   2.0    NaN             NaN   µg/m3
2 2015-01-01 03:00:00  2015.0  1.0  1.0   3.0    NaN             NaN   µg/m3
3 2015-01-01 04:00:00  2015.0  1.0  1.0   4.0    NaN             NaN   µg/m3
4 2015-01-01 05:00:00  2015.0  1.0  1.0   5.0    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

002
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/MP25/MG0010RA002.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
35615565            94.0   µg/m3 2017-02-22 20:30:00
34824327            79.0   µg/m3 2019-10-19 11:30:00
38967106            72.0   µg/m3 2022-04-24 12:30:00
34593082            72.0   µg/m3 2019-08-20 08:30:00
34685954            71.0   µg/m3 2019-09-13 08:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2014-01-01 01:00:00  2014    1    1     1   25.0            25.0   µg/m3
1 2014-01-01 02:00:00  2014    1    1     2   24.0            24.0   µg/m3
2 2014-01-01 03:00:00  2014    1    1     3   21.0            21.0   µg/m3
3 2014-01-01 04:00:00  2014    1    1     4   22.0            22.0   µg/m3
4 2014-01-01 05:00:00  2014    1    1     5   26.0            26.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2014-01-01 01:00:00  2014    1    1     1   25.0            25.0   µg/m3
1 2014-01-01 02:00:00  2014    1    1     2   24.0            24.0   µg/m3
2 2014-01-01 03:00:00  2014    1    1     3   21.0            21.0   µg/m3
3 2014-01-01 04:00:00  2014    1    1     4   22.0            22.0   µg/m3
4 2014-01-01 05:00:00  2014    1    1     5   26.0            26.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
002
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/MP25/MG0020RA002.csv
iema
          VALOR_ORIGINAL UNIDADE            DATETIME
38206598          215.52   µg/m3 2021-09-23 21:30:00
34851441          199.69   µg/m3 2019-10-26 17:30:00
32658015          120.48   µg/m3 2020-10-06 23:30:00
32658172          111.18   µg/m3 2020-10-07 00:30:00
38206760           97.15   µg/m3 2021-09-23 22:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2019-01-01 01:00:00  2019    1    1     1    NaN             NaN   µg/m3
1 2019-01-01 02:00:00  2019    1    1     2    NaN             NaN   µg/m3
2 2019-01-01 03:00:00  2019    1    1     3    NaN             NaN   µg/m3
3 2019-01-01 04:00:00  2019    1    1     4    NaN             NaN   µg/m3
4 2019-01-01 05:00:00  2019    1    1     5    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2019-01-01 01:00:00  2019    1    1     1    NaN             NaN   µg/m3
1 2019-01-01 02:00:00  2019    1    1     2    NaN             NaN   µg/m3
2 2019-01-01 03:00:00  2019    1    1     3    NaN             NaN   µg/m3
3 2019-01-01 04:00:00  2019    1    1     4    NaN             NaN   µg/m3
4 2019-01-01 05:00:00  2019    1    1     5    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

002
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/MP25/RJ0051RA002.csv
iema
          VALOR_ORIGINAL UNIDADE            DATETIME
25626025          163.20   µg/m³ 2021-08-03 13:00:00
25626026          154.48   µg/m³ 2021-01-08 08:00:00
25626027          115.15   µg/m³ 2021-12-27 21:00:00
25626028          105.89   µg/m³ 2021-07-25 03:00:00
25626029          102.24   µg/m³ 2021-03-07 06:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2020-03-18 14:00:00  2020    3   18    14    NaN             NaN   µg/m³
1 2020-03-18 15:00:00  2020    3   18    15    NaN             NaN   µg/m³
2 2020-03-18 16:00:00  2020    3   18    16    NaN             NaN   µg/m³
3 2020-03-18 17:00:00  2020    3   18    17    NaN             NaN   µg/m³
4 2020-03-18 18:00:00  2020    3   18    18    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0         False     False
1         False     False
2         False     False
3         False     False
4         False     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2020-03-18 14:00:00  2020    3   18    14    NaN             NaN   µg/m³
1 2020-03-18 15:00:00  2020    3   18    15    NaN             NaN   µg/m³
2 2020-03-18 16:00:00  2020    3   18    16    NaN             NaN   µg/m³
3 2020-03-18 17:00:00  2020    3   18    17    NaN             NaN   µg/m³
4 2020-03-18 18:00:00  2020    3   18    18    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

002
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/MP25/MG0044RA002.csv
iema
          VALOR_ORIGINAL UNIDADE            DATETIME
37960752           452.0   µg/m3 2021-07-24 21:30:00
34683893           175.0   µg/m3 2019-09-12 19:30:00
37554583           144.0   µg/m3 2021-04-12 19:30:00
38169040           109.0   µg/m3 2021-09-14 10:30:00
34688145           102.0   µg/m3 2019-09-13 21:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2019-01-01 01:00:00  2019    1    1     1    NaN             NaN   µg/m3
1 2019-01-01 02:00:00  2019    1    1     2    NaN             NaN   µg/m3
2 2019-01-01 03:00:00  2019    1    1     3    NaN             NaN   µg/m3
3 2019-01-01 04:00:00  2019    1    1     4    NaN             NaN   µg/m3
4 2019-01-01 05:00:00  2019    1    1     5    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2019-01-01 01:00:00  2019    1    1     1    NaN             NaN   µg/m3
1 2019-01-01 02:00:00  2019    1    1     2    NaN             NaN   µg/m3
2 2019-01-01 03:00:00  2019    1    1     3    NaN             NaN   µg/m3
3 2019-01-01 04:00:00  2019    1    1     4    NaN             NaN   µg/m3
4 2019-01-01 05:00:00  2019    1    1     5    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

002
002
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/MP25/MG0013RA002.csv
iema
          VALOR_ORIGINAL UNIDADE            DATETIME
38218584           132.0   µg/m3 2021-09-26 23:30:00
39409675           120.0   µg/m3 2022-08-24 20:30:00
39405724            94.0   µg/m3 2022-08-23 19:30:00
39583129            85.0   µg/m3 2022-10-11 19:30:00
39316389            84.0   µg/m3 2022-07-30 21:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2020-01-01 02:00:00  2020    1    1     2    NaN             NaN     NaN
1 2020-01-01 03:00:00  2020    1    1     3    NaN             NaN     NaN
2 2020-01-01 04:00:00  2020    1    1     4    NaN             NaN     NaN
3 2020-01-01 05:00:00  2020    1    1     5    NaN             NaN     NaN
4 2020-01-01 06:00:00  2020    1    1     6    NaN             NaN     NaN

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2020-01-01 02:00:00  2020    1    1     2    NaN             NaN     NaN
1 2020-01-01 03:00:00  2020    1    1     3    NaN             NaN     NaN
2 2020-01-01 04:00:00  2020    1    1     4    NaN             NaN     NaN
3 2020-01-01 05:00:00  2020    1    1     5    NaN             NaN     NaN
4 2020-01-01 06:00:00  2020    1    1     6    NaN             NaN     NaN

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

002
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/MP25/MG0018RA002.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
34493698           341.0   µg/m3 2019-07-24 23:30:00
34823711           207.0   µg/m3 2019-10-19 07:30:00
34818407           205.0   µg/m3 2019-10-17 22:30:00
34493848           201.0   µg/m3 2019-07-25 00:30:00
34823236           195.0   µg/m3 2019-10-19 04:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2015-01-01 01:00:00  2015    1    1     1    NaN             NaN   µg/m3
1 2015-01-01 02:00:00  2015    1    1     2    NaN             NaN   µg/m3
2 2015-01-01 03:00:00  2015    1    1     3    NaN             NaN   µg/m3
3 2015-01-01 04:00:00  2015    1    1     4    NaN             NaN   µg/m3
4 2015-01-01 05:00:00  2015    1    1     5    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2015-01-01 01:00:00  2015    1    1     1    NaN             NaN   µg/m3
1 2015-01-01 02:00:00  2015    1    1     2    NaN             NaN   µg/m3
2 2015-01-01 03:00:00  2015    1    1     3    NaN             NaN   µg/m3
3 2015-01-01 04:00:00  2015    1    1     4    NaN             NaN   µg/m3
4 2015-01-01 05:00:00  2015    1    1     5    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
002
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/MP25/MG0034RA002.csv
iema
          VALOR_ORIGINAL UNIDADE            DATETIME
37235016           202.2   µg/m3 2021-01-14 18:30:00
38150512           160.0   µg/m3 2021-09-09 17:30:00
38099346           157.5   µg/m3 2021-08-27 22:30:00
37974061           147.6   µg/m3 2021-07-28 04:30:00
37235159           143.6   µg/m3 2021-01-14 19:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2020-01-01 01:00:00  2020    1    1     1    NaN             NaN   µg/m3
1 2020-01-01 02:00:00  2020    1    1     2    NaN             NaN   µg/m3
2 2020-01-01 03:00:00  2020    1    1     3    NaN             NaN   µg/m3
3 2020-01-01 04:00:00  2020    1    1     4    NaN             NaN   µg/m3
4 2020-01-01 05:00:00  2020    1    1     5    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2020-01-01 01:00:00  2020    1    1     1    NaN             NaN   µg/m3
1 2020-01-01 02:00:00  2020    1    1     2    NaN             NaN   µg/m3
2 2020-01-01 03:00:00  2020    1    1     3    NaN             NaN   µg/m3
3 2020-01-01 04:00:00  2020    1    1     4    NaN             NaN   µg/m3
4 2020-01-01 05:00:00  2020    1    1     5    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

002
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/MP25/MG0004RA002.csv

/tmp/ipykernel_273420/1352582357.py:97: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  df_mma = pd.read_csv(arquivo, encoding = 'UTF-8')
/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
38166227           149.0   µg/m3 2021-09-13 17:30:00
37692628           149.0   µg/m3 2021-05-18 18:30:00
37693451           138.0   µg/m3 2021-05-18 23:30:00
38172078           137.0   µg/m3 2021-09-15 04:30:00
38172249           127.0   µg/m3 2021-09-15 05:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR VALOR_ORIGINAL UNIDADE  \
0 2009-01-01 01:00:00  2009    1    1     1    NaN              *   µg/m3
1 2009-01-01 02:00:00  2009    1    1     2    NaN              *   µg/m3
2 2009-01-01 03:00:00  2009    1    1     3    NaN              *   µg/m3
3 2009-01-01 04:00:00  2009    1    1     4    NaN              *   µg/m3
4 2009-01-01 05:00:00  2009    1    1     5    NaN              *   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR VALOR_ORIGINAL UNIDADE  \
0 2009-01-01 01:00:00  2009    1    1     1    NaN              *   µg/m3
1 2009-01-01 02:00:00  2009    1    1     2    NaN              *   µg/m3
2 2009-01-01 03:00:00  2009    1    1     3    NaN              *   µg/m3
3 2009-01-01 04:00:00  2009    1    1     4    NaN              *   µg/m3
4 2009-01-01 05:00:00  2009    1    1     5    NaN              *   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
002
002
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/MP25/SP0065RA002.csv
iema
          VALOR_ORIGINAL UNIDADE            DATETIME
16277833           157.0   ug/m3 2021-08-08 20:00:00
13045614           132.0   ug/m3 2020-01-01 03:00:00
13900396           131.0   ug/m3 2019-07-14 04:00:00
13899038           131.0   ug/m3 2019-03-09 22:00:00
16277832           129.0   ug/m3 2021-08-08 19:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2019-02-21 01:00:00  2019    2   21     1   24.0            24.0   µg/m3
1 2019-02-21 02:00:00  2019    2   21     2   43.0            43.0   µg/m3
2 2019-02-21 03:00:00  2019    2   21     3   40.0            40.0   µg/m3
3 2019-02-21 04:00:00  2019    2   21     4   38.0            38.0   µg/m3
4 2019-02-21 05:00:00  2019    2   21     5   28.0            28.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2019-02-21 01:00:00  2019    2   21     1   24.0            24.0   ug/m3
1 2019-02-21 02:00:00  2019    2   21     2   43.0            43.0   ug/m3
2 2019-02-21 03:00:00  2019    2   21     3   40.0            40.0   ug/m3
3 2019-02-21 04:00:00  2019    2   21     4   38.0            38.0   ug/m3
4 2019-02-21 05:00:00  2019    2   21     5   28.0            28.0   ug/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
002

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/MP25/MG0047RA002.csv
iema
          VALOR_ORIGINAL UNIDADE            DATETIME
38176698           149.0   µg/m3 2021-09-16 08:30:00
37196083            75.0   µg/m3 2021-01-03 20:30:00
38176369            56.0   µg/m3 2021-09-16 06:30:00
38174433            55.0   µg/m3 2021-09-15 18:30:00
37873939            54.0   µg/m3 2021-07-03 20:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2020-01-01 01:00:00  2020    1    1     1    NaN             NaN   µg/m3
1 2020-01-01 02:00:00  2020    1    1     2    NaN             NaN   µg/m3
2 2020-01-01 03:00:00  2020    1    1     3    NaN             NaN   µg/m3
3 2020-01-01 04:00:00  2020    1    1     4    NaN             NaN   µg/m3
4 2020-01-01 05:00:00  2020    1    1     5    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2020-01-01 01:00:00  2020    1    1     1    NaN             NaN   µg/m3
1 2020-01-01 02:00:00  2020    1    1     2    NaN             NaN   µg/m3
2 2020-01-01 03:00:00  2020    1    1     3    NaN             NaN   µg/m3
3 2020-01-01 04:00:00  2020    1    1     4    NaN             NaN   µg/m3
4 2020-01-01 05:00:00  2020    1    1     5    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

002
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/MP25/MG0055RA002.csv
iema
          VALOR_ORIGINAL UNIDADE            DATETIME
32646683            77.9   µg/m3 2020-10-03 23:30:00
32646836            75.9   µg/m3 2020-10-04 00:30:00
38176285            74.0   µg/m3 2021-09-16 06:30:00
38154894            71.0   µg/m3 2021-09-10 20:30:00
32646523            69.8   µg/m3 2020-10-03 22:30:00
mma
             DATETIME     ANO  MES   DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2019-07-22 12:00:00  2019.0  7.0  22.0  12.0    NaN             NaN   µg/m3
1 2019-07-22 13:00:00  2019.0  7.0  22.0  13.0    NaN             NaN   µg/m3
2 2019-07-22 14:00:00  2019.0  7.0  22.0  14.0    NaN             NaN   µg/m3
3 2019-07-22 15:00:00  2019.0  7.0  22.0  15.0    NaN             NaN   µg/m3
4 2019-07-22 16:00:00  2019.0  7.0  22.0  16.0    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME     ANO  MES   DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2019-07-22 12:00:00  2019.0  7.0  22.0  12.0    NaN             NaN   µg/m3
1 2019-07-22 13:00:00  2019.0  7.0  22.0  13.0    NaN             NaN   µg/m3
2 2019-07-22 14:00:00  2019.0  7.0  22.0  14.0    NaN             NaN   µg/m3
3 2019-07-22 15:00:00  2019.0  7.0  22.0  15.0    NaN             NaN   µg/m3
4 2019-07-22 16:00:00  2019.0  7.0  22.0  16.0    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

002
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/MP25/RJ0054RA002.csv
iema
          VALOR_ORIGINAL UNIDADE            DATETIME
28810164      579.635695   µg/m3 2019-10-18 20:00:00
28819824      578.848258   µg/m3 2019-10-20 22:00:00
23413613      571.589500   µg/m3 2020-07-09 17:00:00
28820009      568.277066   µg/m3 2019-10-20 23:00:00
23505897      561.696900   µg/m3 2020-07-27 19:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2018-10-03 11:00:00  2018   10    3    11    NaN             NaN   µg/m³
1 2018-10-03 12:00:00  2018   10    3    12  10.06           10.06   µg/m³
2 2018-10-03 13:00:00  2018   10    3    13   6.15            6.15   µg/m³
3 2018-10-03 14:00:00  2018   10    3    14   5.83            5.83   µg/m³
4 2018-10-03 15:00:00  2018   10    3    15   6.04            6.04   µg/m³

   QAQC_INTERNO  QAQC_MMA
0         False     False
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2018-10-03 11:00:00  2018   10    3    11    NaN             NaN   µg/m³
1 2018-10-03 12:00:00  2018   10    3    12  10.06           10.06   µg/m³
2 2018-10-03 13:00:00  2018   10    3    13   6.15            6.15   µg/m³
3 2018-10-03 14:00:00  2018   10    3    14   5.83            5.83   µg/m³
4 2018-10-03 15:00:00  2018   10    3    15   6.04            6.04   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True      True
2          True      True
3          True      True
4          True      True

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

002
002
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/MP25/RJ0029RA002.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
30740588           62.16   µg/m³ 2022-06-18 05:00:00
30740590           61.90   µg/m³ 2022-06-18 07:00:00
30740586           60.35   µg/m³ 2022-06-18 03:00:00
30741145           60.20   µg/m³ 2022-07-11 17:00:00
30740589           59.74   µg/m³ 2022-06-18 06:00:00
mma
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2011-05-01 00:00:00  2011.0  5.0  1.0   0.0    NaN             NaN   µg/m³
1 2011-05-01 01:00:00  2011.0  5.0  1.0   1.0    NaN             NaN   µg/m³
2 2011-05-01 02:00:00  2011.0  5.0  1.0   2.0    NaN             NaN   µg/m³
3 2011-05-01 03:00:00  2011.0  5.0  1.0   3.0    NaN             NaN   µg/m³
4 2011-05-01 04:00:00  2011.0  5.0  1.0   4.0    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0         False     False
1         False     False
2         False     False
3         False     False
4         False     False
final
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2011-05-01 00:00:00  2011.0  5.0  1.0   0.0    NaN             NaN   µg/m³
1 2011-05-01 01:00:00  2011.0  5.0  1.0   1.0    NaN             NaN   µg/m³
2 2011-05-01 02:00:00  2011.0  5.0  1.0   2.0    NaN             NaN   µg/m³
3 2011-05-01 03:00:00  2011.0  5.0  1.0   3.0    NaN             NaN   µg/m³
4 2011-05-01 04:00:00  2011.0  5.0  1.0   4.0    NaN             NaN   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
002
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/MP25/SP0113RA002.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
14959571           236.0   ug/m3 2018-07-08 01:00:00
14959575           211.0   ug/m3 2018-07-08 05:00:00
14959570           207.0   ug/m3 2018-07-07 23:55:00
14959573           187.0   ug/m3 2018-07-08 03:00:00
11072852           184.0   ug/m3 2021-08-25 23:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2012-02-09 01:00:00  2012    2    9     1   18.0            18.0   µg/m3
1 2012-02-09 02:00:00  2012    2    9     2   22.0            22.0   µg/m3
2 2012-02-09 03:00:00  2012    2    9     3   24.0            24.0   µg/m3
3 2012-02-09 04:00:00  2012    2    9     4   28.0            28.0   µg/m3
4 2012-02-09 05:00:00  2012    2    9     5   25.0            25.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2012-02-09 01:00:00  2012    2    9     1   18.0            18.0   µg/m3
1 2012-02-09 02:00:00  2012    2    9     2   22.0            22.0   µg/m3
2 2012-02-09 03:00:00  2012    2    9     3   24.0            24.0   µg/m3
3 2012-02-09 04:00:00  2012    2    9     4   28.0            28.0   µg/m3
4 2012-02-09 05:00:00  2012    2    9     5   25.0            25.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
002
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/MP25/MG0003RA002.csv

/tmp/ipykernel_273420/1352582357.py:97: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  df_mma = pd.read_csv(arquivo, encoding = 'UTF-8')
/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
37263205           172.0   µg/m3 2021-01-22 14:30:00
34814499           164.0   µg/m3 2019-10-16 22:30:00
34418615           153.0   µg/m3 2019-07-04 13:30:00
34707357           150.0   µg/m3 2019-09-18 21:30:00
34814335           121.0   µg/m3 2019-10-16 21:30:00
mma
             DATETIME     ANO  MES  DIA  HORA  VALOR VALOR_ORIGINAL UNIDADE  \
0 2009-01-01 01:00:00  2009.0  1.0  1.0   1.0    NaN              *   µg/m3
1 2009-01-01 02:00:00  2009.0  1.0  1.0   2.0    NaN              *   µg/m3
2 2009-01-01 03:00:00  2009.0  1.0  1.0   3.0    NaN              *   µg/m3
3 2009-01-01 04:00:00  2009.0  1.0  1.0   4.0    NaN              *   µg/m3
4 2009-01-01 05:00:00  2009.0  1.0  1.0   5.0    NaN              *   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME     ANO  MES  DIA  HORA  VALOR VALOR_ORIGINAL UNIDADE  \
0 2009-01-01 01:00:00  2009.0  1.0  1.0   1.0    NaN              *   µg/m3
1 2009-01-01 02:00:00  2009.0  1.0  1.0   2.0    NaN              *   µg/m3
2 2009-01-01 03:00:00  2009.0  1.0  1.0   3.0    NaN              *   µg/m3
3 2009-01-01 04:00:00  2009.0  1.0  1.0   4.0    NaN              *   µg/m3
4 2009-01-01 05:00:00  2009.0  1.0  1.0   5.0    NaN              *   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
002
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/MP25/MG0023RA002.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
32538680           344.0   µg/m3 2020-09-03 18:30:00
32538836           343.0   µg/m3 2020-09-03 19:30:00
34822003           283.0   µg/m3 2019-10-18 20:30:00
34818289           245.0   µg/m3 2019-10-17 21:30:00
34821694           235.0   µg/m3 2019-10-18 18:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2015-03-10 17:00:00  2015    3   10    17    NaN             NaN   µg/m3
1 2015-03-10 18:00:00  2015    3   10    18    2.0             2.0   µg/m3
2 2015-03-10 19:00:00  2015    3   10    19   10.0            10.0   µg/m3
3 2015-03-10 20:00:00  2015    3   10    20   15.0            15.0   µg/m3
4 2015-03-10 21:00:00  2015    3   10    21    3.0             3.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2015-03-10 17:00:00  2015    3   10    17    NaN             NaN   µg/m3
1 2015-03-10 18:00:00  2015    3   10    18    2.0             2.0   µg/m3
2 2015-03-10 19:00:00  2015    3   10    19   10.0            10.0   µg/m3
3 2015-03-10 20:00:00  2015    3   10    20   15.0            15.0   µg/m3
4 2015-03-10 21:00:00  2015    3   10    21    3.0             3.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True      True
2          True      True
3          True      True
4          True      True
002
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/MP25/SP0281RA002.csv
iema
          VALOR_ORIGINAL UNIDADE            DATETIME
12961926           116.0   ug/m3 2020-09-19 10:00:00
12962247           105.0   ug/m3 2020-10-03 01:00:00
12961927            99.0   ug/m3 2020-09-19 11:00:00
16184703            95.0   ug/m3 2021-03-19 15:00:00
12961941            95.0   ug/m3 2020-09-20 01:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2019-05-17 01:00:00  2019    5   17     1    6.0             6.0   µg/m3
1 2019-05-17 02:00:00  2019    5   17     2    5.0             5.0   µg/m3
2 2019-05-17 03:00:00  2019    5   17     3    3.0             3.0   µg/m3
3 2019-05-17 04:00:00  2019    5   17     4    3.0             3.0   µg/m3
4 2019-05-17 05:00:00  2019    5   17     5    5.0             5.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2019-05-17 01:00:00  2019    5   17     1    6.0             6.0   ug/m3
1 2019-05-17 02:00:00  2019    5   17     2    5.0             5.0   ug/m3
2 2019-05-17 03:00:00  2019    5   17     3    3.0             3.0   ug/m3
3 2019-05-17 04:00:00  2019    5   17     4    3.0             3.0   ug/m3
4 2019-05-17 05:00:00  2019    5   17     5    5.0             5.0   ug/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

002
002
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/MP25/MG0019RA002.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
35761984           513.0   µg/m3 2017-05-10 20:30:00
35761985           499.0   µg/m3 2017-05-10 19:30:00
34718793           321.0   µg/m3 2019-09-21 22:30:00
34719433           315.0   µg/m3 2019-09-22 02:30:00
37809019           314.0   µg/m3 2021-06-17 17:30:00
mma
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2015-01-01 01:00:00  2015.0  1.0  1.0   1.0    NaN             NaN   µg/m3
1 2015-01-01 02:00:00  2015.0  1.0  1.0   2.0    NaN             NaN   µg/m3
2 2015-01-01 03:00:00  2015.0  1.0  1.0   3.0    NaN             NaN   µg/m3
3 2015-01-01 04:00:00  2015.0  1.0  1.0   4.0    NaN             NaN   µg/m3
4 2015-01-01 05:00:00  2015.0  1.0  1.0   5.0    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2015-01-01 01:00:00  2015.0  1.0  1.0   1.0    NaN             NaN   µg/m3
1 2015-01-01 02:00:00  2015.0  1.0  1.0   2.0    NaN             NaN   µg/m3
2 2015-01-01 03:00:00  2015.0  1.0  1.0   3.0    NaN             NaN   µg/m3
3 2015-01-01 04:00:00  2015.0  1.0  1.0   4.0    NaN             NaN   µg/m3
4 2015-01-01 05:00:00  2015.0  1.0  1.0   5.0    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
002
002
002
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/MP25/MG0027RA002.csv
iema
          VALOR_ORIGINAL UNIDADE            DATETIME
37642476           155.3   µg/m3 2021-05-05 16:30:00
37641359           146.0   µg/m3 2021-05-05 09:30:00
38172726           110.7   µg/m3 2021-09-15 08:30:00
37624987           105.2   µg/m3 2021-05-01 01:30:00
37309008           103.2   µg/m3 2021-02-04 01:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2020-01-01 01:00:00  2020    1    1     1    NaN             NaN   µg/m3
1 2020-01-01 02:00:00  2020    1    1     2    NaN             NaN   µg/m3
2 2020-01-01 03:00:00  2020    1    1     3    NaN             NaN   µg/m3
3 2020-01-01 04:00:00  2020    1    1     4    NaN             NaN   µg/m3
4 2020-01-01 05:00:00  2020    1    1     5    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2020-01-01 01:00:00  2020    1    1     1    NaN             NaN   µg/m3
1 2020-01-01 02:00:00  2020    1    1     2    NaN             NaN   µg/m3
2 2020-01-01 03:00:00  2020    1    1     3    NaN             NaN   µg/m3
3 2020-01-01 04:00:00  2020    1    1     4    NaN             NaN   µg/m3
4 2020-01-01 05:00:00  2020    1    1     5    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

002
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/MP25/MG0035RA002.csv
iema
          VALOR_ORIGINAL UNIDADE            DATETIME
34632123           302.0   µg/m3 2019-08-30 12:30:00
32212482           153.0   µg/m3 2020-06-03 17:30:00
35910424           143.0   µg/m3 2017-10-27 08:30:00
35910441           132.0   µg/m3 2017-08-26 10:30:00
34825809           127.0   µg/m3 2019-10-19 21:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2017-01-01 01:00:00  2017    1    1     1    NaN             NaN   µg/m3
1 2017-01-01 02:00:00  2017    1    1     2    NaN             NaN   µg/m3
2 2017-01-01 03:00:00  2017    1    1     3    NaN             NaN   µg/m3
3 2017-01-01 04:00:00  2017    1    1     4    NaN             NaN   µg/m3
4 2017-01-01 05:00:00  2017    1    1     5    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2017-01-01 01:00:00  2017    1    1     1    NaN             NaN   µg/m3
1 2017-01-01 02:00:00  2017    1    1     2    NaN             NaN   µg/m3
2 2017-01-01 03:00:00  2017    1    1     3    NaN             NaN   µg/m3
3 2017-01-01 04:00:00  2017    1    1     4    NaN             NaN   µg/m3
4 2017-01-01 05:00:00  2017    1    1     5    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

002
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/MP25/SP0064RA002.csv
iema
          VALOR_ORIGINAL UNIDADE            DATETIME
11564313            46.0   ug/m3 2021-07-11 01:00:00
11564318            43.0   ug/m3 2021-08-10 01:00:00
11564320            38.0   ug/m3 2021-08-22 01:00:00
17097102            33.0   ug/m3 2022-07-04 01:00:00
17097099            33.0   ug/m3 2022-06-16 01:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2023-12-20 01:00:00  2023   12   20     1    NaN             0.0   µg/m3
1 2023-12-20 02:00:00  2023   12   20     2    2.0             2.0   µg/m3
2 2023-12-20 03:00:00  2023   12   20     3    2.0             2.0   µg/m3
3 2023-12-20 04:00:00  2023   12   20     4    1.0             1.0   µg/m3
4 2023-12-20 05:00:00  2023   12   20     5    NaN             0.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True      True
2          True      True
3          True      True
4          True     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2023-12-20 01:00:00  2023   12   20     1    NaN             0.0   µg/m3
1 2023-12-20 02:00:00  2023   12   20     2    2.0             2.0   µg/m3
2 2023-12-20 03:00:00  2023   12   20     3    2.0             2.0   µg/m3
3 2023-12-20 04:00:00  2023   12   20     4    1.0             1.0   µg/m3
4 2023-12-20 05:00:00  2023   12   20     5    NaN             0.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True      True
2          True      True
3          True      True
4          True     False
002

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/MP25/MG0022RA002.csv
iema
          VALOR_ORIGINAL UNIDADE            DATETIME
38248715           276.0   µg/m3 2021-10-04 15:30:00
37754605           238.8   µg/m3 2021-06-03 17:30:00
38248552           183.9   µg/m3 2021-10-04 14:30:00
37980489           140.9   µg/m3 2021-07-29 19:30:00
37754763           134.3   µg/m3 2021-06-03 18:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2020-01-01 01:00:00  2020    1    1     1    NaN             NaN   µg/m3
1 2020-01-01 02:00:00  2020    1    1     2    NaN             NaN   µg/m3
2 2020-01-01 03:00:00  2020    1    1     3    NaN             NaN   µg/m3
3 2020-01-01 04:00:00  2020    1    1     4    NaN             NaN   µg/m3
4 2020-01-01 05:00:00  2020    1    1     5    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2020-01-01 01:00:00  2020    1    1     1    NaN             NaN   µg/m3
1 2020-01-01 02:00:00  2020    1    1     2    NaN             NaN   µg/m3
2 2020-01-01 03:00:00  2020    1    1     3    NaN             NaN   µg/m3
3 2020-01-01 04:00:00  2020    1    1     4    NaN             NaN   µg/m3
4 2020-01-01 05:00:00  2020    1    1     5    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

002
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/MP25/MG0053RA002.csv
iema
          VALOR_ORIGINAL UNIDADE            DATETIME
32624261           205.0   µg/m3 2020-09-27 23:30:00
37254564           151.0   µg/m3 2021-01-20 05:30:00
34821741           132.0   µg/m3 2019-10-18 18:30:00
36436577           126.0   µg/m3 2018-05-12 03:30:00
34821897           118.0   µg/m3 2019-10-18 19:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2018-01-01 01:00:00  2018    1    1     1    7.0             7.0   µg/m3
1 2018-01-01 02:00:00  2018    1    1     2    4.0             4.0   µg/m3
2 2018-01-01 03:00:00  2018    1    1     3    4.0             4.0   µg/m3
3 2018-01-01 04:00:00  2018    1    1     4    6.0             6.0   µg/m3
4 2018-01-01 05:00:00  2018    1    1     5    9.0             9.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2018-01-01 01:00:00  2018    1    1     1    7.0             7.0   µg/m3
1 2018-01-01 02:00:00  2018    1    1     2    4.0             4.0   µg/m3
2 2018-01-01 03:00:00  2018    1    1     3    4.0             4.0   µg/m3
3 2018-01-01 04:00:00  2018    1    1     4    6.0             6.0   µg/m3
4 2018-01-01 05:00:00  2018    1    1     5    9.0             9.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

002
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/MP25/SP0280RA002.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
8335396            262.0   ug/m3 2019-07-26 09:00:00
8335395            182.0   ug/m3 2019-07-26 08:00:00
8335397            176.0   ug/m3 2019-07-26 10:00:00
12280414           148.0   ug/m3 2016-09-28 22:00:00
12278708           132.0   ug/m3 2016-07-14 23:55:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2016-02-03 01:00:00  2016    2    3     1   26.0            26.0   µg/m3
1 2016-02-03 02:00:00  2016    2    3     2   14.0            14.0   µg/m3
2 2016-02-03 03:00:00  2016    2    3     3    5.0             5.0   µg/m3
3 2016-02-03 04:00:00  2016    2    3     4    5.0             5.0   µg/m3
4 2016-02-03 05:00:00  2016    2    3     5    8.0             8.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2016-02-03 01:00:00  2016    2    3     1   26.0            26.0   ug/m3
1 2016-02-03 02:00:00  2016    2    3     2   14.0            14.0   ug/m3
2 2016-02-03 03:00:00  2016    2    3     3    5.0             5.0   ug/m3
3 2016-02-03 04:00:00  2016    2    3     4    5.0             5.0   ug/m3
4 2016-02-03 05:00:00  2016    2    3     5    8.0             8.0   ug/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
002
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/MP25/MG0031RA002.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
34716374           359.0   µg/m3 2019-09-21 06:30:00
38135894           329.0   µg/m3 2021-09-05 22:30:00
34719518           317.0   µg/m3 2019-09-22 02:30:00
34719678           311.0   µg/m3 2019-09-22 03:30:00
34719032           289.0   µg/m3 2019-09-21 23:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2015-01-01 01:00:00  2015    1    1     1    NaN             NaN   µg/m3
1 2015-01-01 02:00:00  2015    1    1     2    NaN             NaN   µg/m3
2 2015-01-01 03:00:00  2015    1    1     3    NaN             NaN   µg/m3
3 2015-01-01 04:00:00  2015    1    1     4    NaN             NaN   µg/m3
4 2015-01-01 05:00:00  2015    1    1     5    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2015-01-01 01:00:00  2015    1    1     1    NaN             NaN   µg/m3
1 2015-01-01 02:00:00  2015    1    1     2    NaN             NaN   µg/m3
2 2015-01-01 03:00:00  2015    1    1     3    NaN             NaN   µg/m3
3 2015-01-01 04:00:00  2015    1    1     4    NaN             NaN   µg/m3
4 2015-01-01 05:00:00  2015    1    1     5    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
002
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/MP25/SP0099RA002.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
14929373           111.0   ug/m3 2018-07-21 07:00:00
14928711           107.0   ug/m3 2018-06-23 09:00:00
11042716           105.0   ug/m3 2021-08-25 09:00:00
17325259           105.0   ug/m3 2015-09-25 09:00:00
14929234           103.0   ug/m3 2018-07-15 09:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2012-01-01 02:00:00  2012    1    1     2   10.0            10.0   µg/m3
1 2012-01-01 03:00:00  2012    1    1     3   21.0            21.0   µg/m3
2 2012-01-01 04:00:00  2012    1    1     4   29.0            29.0   µg/m3
3 2012-01-01 05:00:00  2012    1    1     5   43.0            43.0   µg/m3
4 2012-01-01 06:00:00  2012    1    1     6   54.0            54.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2012-01-01 02:00:00  2012    1    1     2   10.0            10.0   µg/m3
1 2012-01-01 03:00:00  2012    1    1     3   21.0            21.0   µg/m3
2 2012-01-01 04:00:00  2012    1    1     4   29.0            29.0   µg/m3
3 2012-01-01 05:00:00  2012    1    1     5   43.0            43.0   µg/m3
4 2012-01-01 06:00:00  2012    1    1     6   54.0            54.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
002
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/MP25/MG0005RA002.csv

/tmp/ipykernel_273420/1352582357.py:97: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  df_mma = pd.read_csv(arquivo, encoding = 'UTF-8')
/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
34624418           144.0   µg/m3 2019-08-28 12:30:00
40155124           133.0   µg/m3 2016-08-27 17:30:00
40155143           129.0   µg/m3 2016-08-27 22:30:00
32579922           125.0   µg/m3 2020-09-15 10:30:00
38199399           120.0   µg/m3 2021-09-22 01:30:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR VALOR_ORIGINAL UNIDADE  \
0 2009-01-01 01:00:00  2009    1    1     1    NaN              *   µg/m3
1 2009-01-01 02:00:00  2009    1    1     2    NaN              *   µg/m3
2 2009-01-01 03:00:00  2009    1    1     3    NaN              *   µg/m3
3 2009-01-01 04:00:00  2009    1    1     4    NaN              *   µg/m3
4 2009-01-01 05:00:00  2009    1    1     5    NaN              *   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
             DATETIME   ANO  MES  DIA  HORA  VALOR VALOR_ORIGINAL UNIDADE  \
0 2009-01-01 01:00:00  2009    1    1     1    NaN              *   µg/m3
1 2009-01-01 02:00:00  2009    1    1     2    NaN              *   µg/m3
2 2009-01-01 03:00:00  2009    1    1     3    NaN              *   µg/m3
3 2009-01-01 04:00:00  2009    1    1     4    NaN              *   µg/m3
4 2009-01-01 05:00:00  2009    1    1     5    NaN              *   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
002
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/MP25/SP0073RA002.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
19098420           122.0   ug/m3 2015-09-01 05:00:00
19098418           120.0   ug/m3 2015-09-01 03:00:00
14219896           119.0   ug/m3 2016-06-17 23:55:00
19098993           118.0   ug/m3 2015-09-25 03:00:00
19098417           118.0   ug/m3 2015-09-01 02:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2011-01-01 01:00:00  2011    1    1     1   15.0            15.0   µg/m3
1 2011-01-01 02:00:00  2011    1    1     2   44.0            44.0   µg/m3
2 2011-01-01 03:00:00  2011    1    1     3   34.0            34.0   µg/m3
3 2011-01-01 04:00:00  2011    1    1     4   14.0            14.0   µg/m3
4 2011-01-01 05:00:00  2011    1    1     5    6.0             6.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2011-01-01 01:00:00  2011    1    1     1   15.0            15.0   µg/m3
1 2011-01-01 02:00:00  2011    1    1     2   44.0            44.0   µg/m3
2 2011-01-01 03:00:00  2011    1    1     3   34.0            34.0   µg/m3
3 2011-01-01 04:00:00  2011    1    1     4   14.0            14.0   µg/m3
4 2011-01-01 05:00:00  2011    1    1     5    6.0             6.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
002
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/MP25/RJ0071RA002.csv
iema
          VALOR_ORIGINAL UNIDADE            DATETIME
22957954           96.53   ug/m3 2022-03-13 17:00:00
24648466           92.97   µg/m3 2021-07-02 10:00:00
24649343           92.72   µg/m3 2021-08-11 16:00:00
24652337           79.72   µg/m3 2021-12-27 17:00:00
22961993           79.44   ug/m3 2022-09-02 21:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2021-01-18 09:00:00  2021    1   18     9   1.82            1.82   µg/m³
1 2021-01-18 10:00:00  2021    1   18    10   2.49            2.49   µg/m³
2 2021-01-18 11:00:00  2021    1   18    11   5.49            5.49   µg/m³
3 2021-01-18 12:00:00  2021    1   18    12   8.62            8.62   µg/m³
4 2021-01-18 13:00:00  2021    1   18    13   4.63            4.63   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2021-01-18 09:00:00  2021    1   18     9   1.82            1.82   µg/m3
1 2021-01-18 10:00:00  2021    1   18    10   2.49            2.49   µg/m3
2 2021-01-18 11:00:00  2021    1   18    11   5.49            5.49   µg/m3
3 2021-01-18 12:00:00  2021    1   18    12   8.62            8.62   µg/m3
4 2021-01-18 13:00:00  2021    1   18    13   4.63            4.63   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

002
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/MP25/RJ0069RA002.csv
iema
          VALOR_ORIGINAL UNIDADE            DATETIME
22841549          109.45   ug/m3 2022-09-02 09:00:00
24535538           94.00   µg/m³ 2021-09-21 07:00:00
24534821           91.13   µg/m³ 2021-08-22 08:00:00
22840281           90.63   ug/m3 2022-07-11 13:00:00
24533611           85.48   µg/m³ 2021-07-02 11:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2021-01-18 09:00:00  2021    1   18     9   2.29            2.29   µg/m³
1 2021-01-18 10:00:00  2021    1   18    10   2.27            2.27   µg/m³
2 2021-01-18 11:00:00  2021    1   18    11   1.85            1.85   µg/m³
3 2021-01-18 12:00:00  2021    1   18    12   2.30            2.30   µg/m³
4 2021-01-18 13:00:00  2021    1   18    13   0.75            0.75   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2021-01-18 09:00:00  2021    1   18     9   2.29            2.29   µg/m³
1 2021-01-18 10:00:00  2021    1   18    10   2.27            2.27   µg/m³
2 2021-01-18 11:00:00  2021    1   18    11   1.85            1.85   µg/m³
3 2021-01-18 12:00:00  2021    1   18    12   2.30            2.30   µg/m³
4 2021-01-18 13:00:00  2021    1   18    13   0.75            0.75   µg/m³

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

002
/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/MP25/SP0063RA002.csv

/tmp/ipykernel_273420/1352582357.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_273420/1352582357.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_273420/1352582357.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_273420/1352582357.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_273420/1352582357.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

iema
          VALOR_ORIGINAL UNIDADE            DATETIME
10541008           234.0   ug/m3 2020-01-01 03:00:00
10541009           156.0   ug/m3 2020-01-01 04:00:00
16803772           135.0   ug/m3 2022-01-01 05:00:00
16808091           124.0   ug/m3 2022-07-24 08:00:00
7285021            122.0   ug/m3 2017-07-21 04:00:00
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2017-05-29 01:00:00  2017    5   29     1   42.0            42.0   µg/m3
1 2017-05-29 02:00:00  2017    5   29     2   49.0            49.0   µg/m3
2 2017-05-29 03:00:00  2017    5   29     3   42.0            42.0   µg/m3
3 2017-05-29 04:00:00  2017    5   29     4   34.0            34.0   µg/m3
4 2017-05-29 05:00:00  2017    5   29     5   26.0            26.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2017-05-29 01:00:00  2017    5   29     1   42.0            42.0   ug/m3
1 2017-05-29 02:00:00  2017    5   29     2   49.0            49.0   ug/m3
2 2017-05-29 03:00:00  2017    5   29     3   42.0            42.0   ug/m3
3 2017-05-29 04:00:00  2017    5   29     4   34.0            34.0   ug/m3
4 2017-05-29 05:00:00  2017    5   29     5   26.0            26.0   ug/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
002

In [529]:
pol

'PM10'

In [527]:
df_final = df_mma.merge(df_iema, on='DATETIME', how='left', suffixes=('', '_df2'))

df_mma = pd.read_csv(arquivo, encoding = 'UTF-8')

df_iema = df_pol_est[['Data','Hora','Valor','Unidade']]

mask_24 = df_iema['Hora'].str.startswith('24')

df_iema.loc[mask_24, 'Data'] = pd.to_datetime(df_iema.loc[mask_24, 'Data']) + pd.Timedelta(days=1)
df_iema.loc[mask_24, 'Hora'] = '00:00:00'

df_iema['Data'] = df_iema['Data'].astype(str)

df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')

df_iema.drop(columns=['Data','Hora'], inplace=True)

df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)

df_mma['DATETIME'] = pd.to_datetime(df_mma['DATETIME'], errors='coerce')
df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

df_mma = df_mma.dropna(subset=['DATETIME'])
df_iema = df_iema.dropna(subset=['DATETIME'])

if pol == 'CO':
    df_iema = ug_to_ppm(df_iema)

df_iema = (
    df_iema.sort_values('VALOR_ORIGINAL', ascending=False)
           .drop_duplicates(subset='DATETIME', keep='first')
)

df_final = df_mma.merge(df_iema, on='DATETIME', how='left', suffixes=('', '_df2'))

/tmp/ipykernel_175285/2951050035.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['Data'] = df_iema['Data'].astype(str)
/tmp/ipykernel_175285/2951050035.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['Data'] + ' ' + df_iema['Hora'], errors='coerce')
/tmp/ipykernel_175285/2951050035.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.drop(columns=['Data','Hora'], inplace=True)
/tmp/ipykernel_175285/2951050035.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema.rename(columns={'Valor':'VALOR_ORIGINAL','Unidade':'UNIDADE'},inplace=True)
/tmp/ipykernel_175285/2951050035.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_iema['DATETIME'] = pd.to_datetime(df_iema['DATETIME'], errors='coerce')

                  DATETIME   ANO  MES  DIA  HORA  VALOR  QAQC_INTERNO UNIDADE
0      1998-01-01 00:00:00  1998    1    1     0    NaN           0.0     ppm
1      1998-01-01 01:00:00  1998    1    1     1    NaN           0.0     ppm
2      1998-01-01 02:00:00  1998    1    1     2    NaN           0.0     ppm
3      1998-01-01 03:00:00  1998    1    1     3    NaN           0.0     ppm
4      1998-01-01 04:00:00  1998    1    1     4    NaN           0.0     ppm
...                    ...   ...  ...  ...   ...    ...           ...     ...
236683 2024-12-31 19:00:00  2024   12   31    19    0.1         100.0     ppm
236684 2024-12-31 20:00:00  2024   12   31    20    0.1         100.0     ppm
236685 2024-12-31 21:00:00  2024   12   31    21    0.1         100.0     ppm
236686 2024-12-31 22:00:00  2024   12   31    22    0.1         100.0     ppm
236687 2024-12-31 23:00:00  2024   12   31    23    0.1         100.0     ppm

[236688 rows x 8 columns]

In [ ]:
caminho = os.getcwd()+'/data/DADOS_BRUTOS/BRUTO_MONITORAR/'

df_colunas_monitorar = pd.read_csv(caminho+'colunas_monitorar.csv')

estados = os.listdir(caminho)

lista = []

lista_validacao = []

mapeamento = dict(zip(df_colunas_monitorar["COLUNAS_MONITORAR"], df_colunas_monitorar["COLUNAS_MMA"]))

dict_estacao_pol = {}

def unit_pol(pol):

    if pol in ['NOX','NO2','PTS','O3','MP10','MP25','NO','ERT','SO2']:
        unidade = 'µg/m³'
    elif pol in ['HCT','H2S','NH3','HCNM','BENZENO','CO','CH4']:
        unidade = 'ppm'

    return unidade
    
for estado in estados:

    print(estado)
    
    if '.csv' not in estado and estado != '.ipynb_checkpoints':

        if estado == 'RJ' or estado == 'PA' or estado == 'RN':
            df_rj_ou_pa_estacao = pd.read_csv(os.getcwd()+'/data/DADOS_BRUTOS/BRUTO_MONITORAR/'+estado+'_ID_MMA_monitorar.csv')
        else:
            df_estado_estacao = pd.read_csv(os.getcwd()+'/data/DADOS_ESTACOES/'+estado+'_estacoes.csv')

        estacoes = os.listdir(caminho+estado)
    
        for estacao in estacoes:
    
            if estacao != '.ipynb_checkpoints':
    
                df = pd.read_csv(caminho+estado+'/'+estacao, sep = ';')
                    
                df = df.rename(columns=mapeamento)

                df = df.dropna(axis=1, how='all')
                
                df_consolidado = df.groupby(df.columns, axis=1).first() 

                print(estacao)

                for col in df_consolidado.columns:
    
                    if col != 'DATA' and col != 'HORA' and 'QAQC' not in col:

                        df_consolidado[col] = df_consolidado[col].apply(
                            lambda x: str(x).replace('.', '') if pd.notna(x) else x
                        )
                        
                        df_consolidado[col] = df_consolidado[col].apply(
                            lambda x: str(x).replace(',', '.') if pd.notna(x) else x
                        ).astype(float)

                for pol in ['NOX','HCT','H2S','NO2','PTS','NH3','HCNM','HORA','O3','BENZENO','CO','MP10','MP25','CH4','NO','ERT','SO2']:
    
                    if pol in df_consolidado.columns and pol != 'HORA' and pol != 'DATA':
    
                        unidade = 'desconhecida'

                        print(pol)

                        qaqc = 'QAQC_'+pol
                        if qaqc in df_consolidado.columns:
                            print(df_consolidado.columns)
                            df_monitorar = df_consolidado[['DATA','HORA',pol,qaqc]]
                        else:
                            df_monitorar = df_consolidado[['DATA','HORA',pol]]

                        df_monitorar['DATA_HORA_STRING'] = df_monitorar['DATA'] + ' ' + df_monitorar['HORA']

                        df_monitorar['DATETIME'] = pd.to_datetime(
                            df_monitorar['DATA_HORA_STRING'],
                            format='%d/%m/%Y %H:%M'
                        )
                        
                        df_monitorar = df_monitorar.drop(columns=['DATA_HORA_STRING','DATA','HORA'])
    
                        df_monitorar.index = df_monitorar['DATETIME']
                        
                        df_monitorar.insert(1, 'ANO', df_monitorar.index.year)
                        df_monitorar.insert(2, 'MES', df_monitorar.index.month)
                        df_monitorar.insert(3, 'DIA', df_monitorar.index.day)
                        df_monitorar.insert(4, 'HORA', df_monitorar.index.hour)

                        df_monitorar['UNIDADE'] = unidade

                        dict_estacao_pol[estacao[:-4]+'_'+pol] = df_monitorar

                        if qaqc in df_monitorar.columns:
        
                            for validacao in list(set(df_monitorar[qaqc])):

                                lista_validacao.append(validacao)

                        print(estacao[:-4])
                        
                        if estado == 'RJ' or estado == 'PA' or estado == 'RN':
                            id_mma = df_rj_ou_pa_estacao.loc[df_rj_ou_pa_estacao['STATION']==estacao[:-4], 'ID_MMA'].iloc[0]
                        else:
                            mask = (df_estado_estacao['ID_OEMA']
                                .str.replace(' ', '', regex=False)
                                .str.replace('-', '', regex=False)
                                .str.lower()
                                == estacao[:-4].replace(' ', '').replace('-', '').lower()
                            )
                    
                            id_mma = df_estado_estacao.loc[mask, 'ID_MMA'].iloc[-1]
                            
                        print(id_mma)
                        
                        df_monitorar.rename(columns={pol:'VALOR_ORIGINAL','QAQC_'+pol:'QAQC_INTERNO'},inplace=True)

                        padrao = os.path.join(os.getcwd() + '/data/MQAr/'+pol+'/', f"{id_mma}*.csv")
                        arquivos = glob.glob(padrao)

                        if len(arquivos) == 0:

                            unidade = unit_pol(pol)

                            df_monitorar['UNIDADE'] = unidade
                
                            df_monitorar = create_QAQCMMA_VALOR(df_monitorar,pol)

                            cod_poluente = int(tabela_pols.loc[tabela_pols['POLUENTE'] == pol, 'COD_POLUENTE'].values[0])
                           
                            cod_poluente = f"{cod_poluente:03d}"

                            print(str(pol)+'/'+str(id_mma)+'ND'+cod_poluente+'.csv')
                            
                            df_monitorar.to_csv('/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/'+pol+'/'+id_mma+'ND'+cod_poluente+'.csv', index=False)
                            
                        else:
                            for arquivo in arquivos:
                    
                                df_mma = pd.read_csv(arquivo, encoding = 'UTF-8')
                                
                                df_mma = df_mma.dropna(subset=['DATETIME'])
                                df_monitorar = df_monitorar.dropna(subset=['DATETIME'])
                                
                                df_monitorar = (
                                    df_monitorar.sort_values('VALOR_ORIGINAL', ascending=False)
                                           .drop_duplicates(subset='DATETIME', keep='first')
                                )

                                df_monitorar = df_monitorar.reset_index(drop=True)

                                df_mma['DATETIME'] = pd.to_datetime(df_mma['DATETIME'], errors='coerce')
                                df_monitorar['DATETIME'] = pd.to_datetime(df_monitorar['DATETIME'], errors='coerce')

                                unidade = unit_pol(pol)

                                df_monitorar['UNIDADE'] = unidade
                                
                                df_final = df_mma.merge(df_monitorar, on='DATETIME', how='left', suffixes=('', '_df2'))
                                
                                df_final['VALOR_ORIGINAL'] = df_final['VALOR_ORIGINAL_df2'].combine_first(df_final['VALOR_ORIGINAL'])
                                df_final['UNIDADE'] = df_final['UNIDADE_df2'].combine_first(df_final['UNIDADE'])
                
                                df_final['VALOR'] = df_final['VALOR_ORIGINAL']
                
                                df_final.drop(columns=['VALOR_ORIGINAL','ANO','MES','DIA','HORA'], inplace=True)
                                df_final=df_final.set_index('DATETIME')
                    
                                lista_horas = pd.date_range(
                                    start=df_final.index.min(), 
                                    end=df_final.index.max(), 
                                    freq='H').strftime('%Y-%m-%d %H:%M:%S').tolist()

                                df_final = df_final[~df_final.index.duplicated(keep='first')]
                                
                                if len(lista_horas) != len(df_final):
                                    df_final = df_final.reindex(pd.DatetimeIndex(lista_horas))
                                
                                df_final['DATETIME'] = df_final.index
                                
                                cols = ["DATETIME"] + [c for c in df_final.columns if c != "DATETIME"]
                                df_final = df_final[cols]
                                
                                df_final.index = df_final['DATETIME']
                                
                                df_final.insert(1, 'ANO', df_final.index.year)
                                df_final.insert(2, 'MES', df_final.index.month)
                                df_final.insert(3, 'DIA', df_final.index.day)
                                df_final.insert(4, 'HORA', df_final.index.hour)
                
                                df_final = create_QAQCMMA_VALOR(df_final,pol)
                                
                                print('iema')
                                print(df_monitorar.head())
                                print('mma')
                                print(df_mma.head())
                                print('final')
                                print(df_final.head())
                                
                                df_final.to_csv(arquivo, index=False)
                            
                                                                
lista_colunas = list(set(lista))

lista_validacao = list(set(lista_validacao))

colunas_monitorar.csv
DF
FercalEscola.csv
MP10
Index(['DATA', 'HORA', 'MP10', 'MP25', 'QAQC_MP10', 'QAQC_MP25'], dtype='object')
FercalEscola
DF0002
iema
   VALOR_ORIGINAL   ANO  MES  DIA  HORA QAQC_INTERNO            DATETIME  \
0         323.084  2024   12    3     8           VA 2024-12-03 08:00:00
1         294.205  2024   12    3     7           VA 2024-12-03 07:00:00
2         218.271  2024    8   25    23           VA 2024-08-25 23:00:00
3         204.446  2024    8   25    22           VA 2024-08-25 22:00:00
4         180.625  2024   12    4     8           VA 2024-12-04 08:00:00

  UNIDADE
0   µg/m³
1   µg/m³
2   µg/m³
3   µg/m³
4   µg/m³
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2024-01-01 01:00:00  2024    1    1     1  29.25           29.25   ug/m3
1 2024-01-01 02:00:00  2024    1    1     2  26.62           26.62   ug/m3
2 2024-01-01 03:00:00  2024    1    1     3  22.00           22.00   ug/m3
3 2024-01-01 04:00:00  2024    1    1     4  18.31           18.31   ug/m3
4 2024-01-01 05:00:00  2024    1    1     5  18.71           18.71   ug/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
                               DATETIME   ANO  MES  DIA  HORA  VALOR  \
DATETIME
2024-01-01 01:00:00 2024-01-01 01:00:00  2024    1    1     1  29.25
2024-01-01 02:00:00 2024-01-01 02:00:00  2024    1    1     2  26.62
2024-01-01 03:00:00 2024-01-01 03:00:00  2024    1    1     3  22.00
2024-01-01 04:00:00 2024-01-01 04:00:00  2024    1    1     4  18.31
2024-01-01 05:00:00 2024-01-01 05:00:00  2024    1    1     5  18.71

                     VALOR_ORIGINAL UNIDADE  QAQC_INTERNO  QAQC_MMA
DATETIME
2024-01-01 01:00:00           29.25   ug/m3          True      True
2024-01-01 02:00:00           26.62   ug/m3          True      True
2024-01-01 03:00:00           22.00   ug/m3          True      True
2024-01-01 04:00:00           18.31   ug/m3          True      True
2024-01-01 05:00:00           18.71   ug/m3          True      True

/tmp/ipykernel_273420/3647521321.py:47: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  df_consolidado = df.groupby(df.columns, axis=1).first()
/tmp/ipykernel_273420/3647521321.py:78: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_monitorar['DATA_HORA_STRING'] = df_monitorar['DATA'] + ' ' + df_monitorar['HORA']
/tmp/ipykernel_273420/3647521321.py:173: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(

MP25
Index(['DATA', 'HORA', 'MP10', 'MP25', 'QAQC_MP10', 'QAQC_MP25'], dtype='object')
FercalEscola
DF0002
iema
   VALOR_ORIGINAL   ANO  MES  DIA  HORA QAQC_INTERNO            DATETIME  \
0         179.744  2024    8   25    23           VA 2024-08-25 23:00:00
1         165.605  2024    8   25    22           VA 2024-08-25 22:00:00
2         145.700  2024    8   26     0           VA 2024-08-26 00:00:00
3         128.109  2024    8   26     1           VA 2024-08-26 01:00:00
4         109.101  2024    8   26     2           VA 2024-08-26 02:00:00

  UNIDADE
0   µg/m³
1   µg/m³
2   µg/m³
3   µg/m³
4   µg/m³
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2024-01-01 01:00:00  2024    1    1     1   9.87            9.87   ug/m3
1 2024-01-01 02:00:00  2024    1    1     2   9.19            9.19   ug/m3
2 2024-01-01 03:00:00  2024    1    1     3   8.07            8.07   ug/m3
3 2024-01-01 04:00:00  2024    1    1     4   7.44            7.44   ug/m3
4 2024-01-01 05:00:00  2024    1    1     5   7.39            7.39   ug/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
                               DATETIME   ANO  MES  DIA  HORA  VALOR  \
DATETIME
2024-01-01 01:00:00 2024-01-01 01:00:00  2024    1    1     1   9.87
2024-01-01 02:00:00 2024-01-01 02:00:00  2024    1    1     2   9.19
2024-01-01 03:00:00 2024-01-01 03:00:00  2024    1    1     3   8.07
2024-01-01 04:00:00 2024-01-01 04:00:00  2024    1    1     4   7.44
2024-01-01 05:00:00 2024-01-01 05:00:00  2024    1    1     5   7.39

                     VALOR_ORIGINAL UNIDADE  QAQC_INTERNO  QAQC_MMA
DATETIME
2024-01-01 01:00:00            9.87   ug/m3          True      True
2024-01-01 02:00:00            9.19   ug/m3          True      True
2024-01-01 03:00:00            8.07   ug/m3          True      True
2024-01-01 04:00:00            7.44   ug/m3          True      True
2024-01-01 05:00:00            7.39   ug/m3          True      True

/tmp/ipykernel_273420/3647521321.py:78: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_monitorar['DATA_HORA_STRING'] = df_monitorar['DATA'] + ' ' + df_monitorar['HORA']
/tmp/ipykernel_273420/3647521321.py:173: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3647521321.py:47: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  df_consolidado = df.groupby(df.columns, axis=1).first()

FercalCRAS.csv
NO2
Index(['CO', 'DATA', 'HORA', 'MP10', 'MP25', 'NO2', 'O3', 'QAQC_CO',
       'QAQC_MP10', 'QAQC_MP25', 'QAQC_NO2', 'QAQC_O3', 'QAQC_SO2', 'SO2'],
      dtype='object')
FercalCRAS
DF0001
iema
   VALOR_ORIGINAL   ANO  MES  DIA  HORA QAQC_INTERNO            DATETIME  \
0           260.0  2024    8   24    10           VA 2024-08-24 10:00:00
1           190.0  2024    8   24     9           VA 2024-08-24 09:00:00
2           190.0  2024    9    5    10           VA 2024-09-05 10:00:00
3           170.0  2024    8   23    22           VA 2024-08-23 22:00:00
4           160.0  2024    8   23    21           VA 2024-08-23 21:00:00

  UNIDADE
0   µg/m³
1   µg/m³
2   µg/m³
3   µg/m³
4   µg/m³
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2024-01-01 01:00:00  2024    1    1     1   3.50            3.50   ug/m3
1 2024-01-01 02:00:00  2024    1    1     2   3.46            3.46   ug/m3
2 2024-01-01 03:00:00  2024    1    1     3   3.09            3.09   ug/m3
3 2024-01-01 04:00:00  2024    1    1     4   2.79            2.79   ug/m3
4 2024-01-01 05:00:00  2024    1    1     5   2.63            2.63   ug/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
                               DATETIME   ANO  MES  DIA  HORA  VALOR  \
DATETIME
2024-01-01 01:00:00 2024-01-01 01:00:00  2024    1    1     1   3.50
2024-01-01 02:00:00 2024-01-01 02:00:00  2024    1    1     2   3.46
2024-01-01 03:00:00 2024-01-01 03:00:00  2024    1    1     3   3.09
2024-01-01 04:00:00 2024-01-01 04:00:00  2024    1    1     4   2.79
2024-01-01 05:00:00 2024-01-01 05:00:00  2024    1    1     5   2.63

                     VALOR_ORIGINAL UNIDADE  QAQC_INTERNO  QAQC_MMA
DATETIME
2024-01-01 01:00:00            3.50   ug/m3          True      True
2024-01-01 02:00:00            3.46   ug/m3          True      True
2024-01-01 03:00:00            3.09   ug/m3          True      True
2024-01-01 04:00:00            2.79   ug/m3          True      True
2024-01-01 05:00:00            2.63   ug/m3          True      True
O3
Index(['CO', 'DATA', 'HORA', 'MP10', 'MP25', 'NO2', 'O3', 'QAQC_CO',
       'QAQC_MP10', 'QAQC_MP25', 'QAQC_NO2', 'QAQC_O3', 'QAQC_SO2', 'SO2'],
      dtype='object')
FercalCRAS
DF0001
iema
   VALOR_ORIGINAL   ANO  MES  DIA  HORA QAQC_INTERNO            DATETIME  \
0         128.745  2024    9    5    12           VA 2024-09-05 12:00:00
1         128.317  2024    9    5    13           VA 2024-09-05 13:00:00
2         127.373  2024    9    5    15           VA 2024-09-05 15:00:00
3         126.280  2024    9    5    14           VA 2024-09-05 14:00:00
4         125.504  2024    9    5    16           VA 2024-09-05 16:00:00

  UNIDADE
0   µg/m³
1   µg/m³
2   µg/m³
3   µg/m³
4   µg/m³
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2024-01-01 01:00:00  2024    1    1     1   9.75            9.75   ug/m3
1 2024-01-01 02:00:00  2024    1    1     2   9.88            9.88   ug/m3
2 2024-01-01 03:00:00  2024    1    1     3  10.04           10.04   ug/m3
3 2024-01-01 04:00:00  2024    1    1     4  10.48           10.48   ug/m3
4 2024-01-01 05:00:00  2024    1    1     5  11.33           11.33   ug/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
                               DATETIME   ANO  MES  DIA  HORA  VALOR  \
DATETIME
2024-01-01 01:00:00 2024-01-01 01:00:00  2024    1    1     1   9.75
2024-01-01 02:00:00 2024-01-01 02:00:00  2024    1    1     2   9.88
2024-01-01 03:00:00 2024-01-01 03:00:00  2024    1    1     3  10.04
2024-01-01 04:00:00 2024-01-01 04:00:00  2024    1    1     4  10.48
2024-01-01 05:00:00 2024-01-01 05:00:00  2024    1    1     5  11.33

                     VALOR_ORIGINAL UNIDADE  QAQC_INTERNO  QAQC_MMA
DATETIME
2024-01-01 01:00:00            9.75   ug/m3          True      True
2024-01-01 02:00:00            9.88   ug/m3          True      True
2024-01-01 03:00:00           10.04   ug/m3          True      True
2024-01-01 04:00:00           10.48   ug/m3          True      True
2024-01-01 05:00:00           11.33   ug/m3          True      True

/tmp/ipykernel_273420/3647521321.py:78: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_monitorar['DATA_HORA_STRING'] = df_monitorar['DATA'] + ' ' + df_monitorar['HORA']
/tmp/ipykernel_273420/3647521321.py:80: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_monitorar['DATETIME'] = pd.to_datetime(
/tmp/ipykernel_273420/3647521321.py:173: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3647521321.py:78: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_monitorar['DATA_HORA_STRING'] = df_monitorar['DATA'] + ' ' + df_monitorar['HORA']
/tmp/ipykernel_273420/3647521321.py:80: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_monitorar['DATETIME'] = pd.to_datetime(
/tmp/ipykernel_273420/3647521321.py:173: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(

CO
Index(['CO', 'DATA', 'HORA', 'MP10', 'MP25', 'NO2', 'O3', 'QAQC_CO',
       'QAQC_MP10', 'QAQC_MP25', 'QAQC_NO2', 'QAQC_O3', 'QAQC_SO2', 'SO2'],
      dtype='object')
FercalCRAS
DF0001
iema
   VALOR_ORIGINAL   ANO  MES  DIA  HORA QAQC_INTERNO            DATETIME  \
0           2.229  2024    8   31    23           VA 2024-08-31 23:00:00
1           2.150  2024    9    1     2           VA 2024-09-01 02:00:00
2           2.093  2024    9    1     1           VA 2024-09-01 01:00:00
3           2.004  2024    9    5     9           VA 2024-09-05 09:00:00
4           1.969  2024    8   31    22           VA 2024-08-31 22:00:00

  UNIDADE
0     ppm
1     ppm
2     ppm
3     ppm
4     ppm
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2024-01-01 01:00:00  2024    1    1     1  0.851           0.851     ppm
1 2024-01-01 02:00:00  2024    1    1     2  0.874           0.874     ppm
2 2024-01-01 03:00:00  2024    1    1     3  0.889           0.889     ppm
3 2024-01-01 04:00:00  2024    1    1     4  0.876           0.876     ppm
4 2024-01-01 05:00:00  2024    1    1     5  0.818           0.818     ppm

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
                               DATETIME   ANO  MES  DIA  HORA  VALOR  \
DATETIME
2024-01-01 01:00:00 2024-01-01 01:00:00  2024    1    1     1  0.851
2024-01-01 02:00:00 2024-01-01 02:00:00  2024    1    1     2  0.874
2024-01-01 03:00:00 2024-01-01 03:00:00  2024    1    1     3  0.889
2024-01-01 04:00:00 2024-01-01 04:00:00  2024    1    1     4  0.876
2024-01-01 05:00:00 2024-01-01 05:00:00  2024    1    1     5  0.818

                     VALOR_ORIGINAL UNIDADE  QAQC_INTERNO  QAQC_MMA
DATETIME
2024-01-01 01:00:00           0.851     ppm          True      True
2024-01-01 02:00:00           0.874     ppm          True      True
2024-01-01 03:00:00           0.889     ppm          True      True
2024-01-01 04:00:00           0.876     ppm          True      True
2024-01-01 05:00:00           0.818     ppm          True      True
MP10
Index(['CO', 'DATA', 'HORA', 'MP10', 'MP25', 'NO2', 'O3', 'QAQC_CO',
       'QAQC_MP10', 'QAQC_MP25', 'QAQC_NO2', 'QAQC_O3', 'QAQC_SO2', 'SO2'],
      dtype='object')
FercalCRAS
DF0001
iema
   VALOR_ORIGINAL   ANO  MES  DIA  HORA QAQC_INTERNO            DATETIME  \
0         431.127  2024   10    4    21           VA 2024-10-04 21:00:00
1         357.614  2024    8   25    21           VA 2024-08-25 21:00:00
2         324.662  2024    8   26     0           VA 2024-08-26 00:00:00
3         316.739  2024    8   25    20           VA 2024-08-25 20:00:00
4         310.925  2024    8   25    22           VA 2024-08-25 22:00:00

  UNIDADE
0   µg/m³
1   µg/m³
2   µg/m³
3   µg/m³
4   µg/m³
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2024-01-01 01:00:00  2024    1    1     1  21.02           21.02   ug/m3
1 2024-01-01 02:00:00  2024    1    1     2  18.58           18.58   ug/m3
2 2024-01-01 03:00:00  2024    1    1     3  16.99           16.99   ug/m3
3 2024-01-01 04:00:00  2024    1    1     4  15.04           15.04   ug/m3
4 2024-01-01 05:00:00  2024    1    1     5  16.25           16.25   ug/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
                               DATETIME   ANO  MES  DIA  HORA  VALOR  \
DATETIME
2024-01-01 01:00:00 2024-01-01 01:00:00  2024    1    1     1  21.02
2024-01-01 02:00:00 2024-01-01 02:00:00  2024    1    1     2  18.58
2024-01-01 03:00:00 2024-01-01 03:00:00  2024    1    1     3  16.99
2024-01-01 04:00:00 2024-01-01 04:00:00  2024    1    1     4  15.04
2024-01-01 05:00:00 2024-01-01 05:00:00  2024    1    1     5  16.25

                     VALOR_ORIGINAL UNIDADE  QAQC_INTERNO  QAQC_MMA
DATETIME
2024-01-01 01:00:00           21.02   ug/m3          True      True
2024-01-01 02:00:00           18.58   ug/m3          True      True
2024-01-01 03:00:00           16.99   ug/m3          True      True
2024-01-01 04:00:00           15.04   ug/m3          True      True
2024-01-01 05:00:00           16.25   ug/m3          True      True

/tmp/ipykernel_273420/3647521321.py:78: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_monitorar['DATA_HORA_STRING'] = df_monitorar['DATA'] + ' ' + df_monitorar['HORA']
/tmp/ipykernel_273420/3647521321.py:80: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_monitorar['DATETIME'] = pd.to_datetime(
/tmp/ipykernel_273420/3647521321.py:173: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3647521321.py:78: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_monitorar['DATA_HORA_STRING'] = df_monitorar['DATA'] + ' ' + df_monitorar['HORA']
/tmp/ipykernel_273420/3647521321.py:80: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_monitorar['DATETIME'] = pd.to_datetime(
/tmp/ipykernel_273420/3647521321.py:173: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(

MP25
Index(['CO', 'DATA', 'HORA', 'MP10', 'MP25', 'NO2', 'O3', 'QAQC_CO',
       'QAQC_MP10', 'QAQC_MP25', 'QAQC_NO2', 'QAQC_O3', 'QAQC_SO2', 'SO2'],
      dtype='object')
FercalCRAS
DF0001
iema
   VALOR_ORIGINAL   ANO  MES  DIA  HORA QAQC_INTERNO            DATETIME  \
0         226.489  2024    8   26     0           VA 2024-08-26 00:00:00
1         199.139  2024    8   26     1           VA 2024-08-26 01:00:00
2         165.962  2024    8   25    21           VA 2024-08-25 21:00:00
3         158.945  2024    8   25    23           VA 2024-08-25 23:00:00
4         154.294  2024    8   25    22           VA 2024-08-25 22:00:00

  UNIDADE
0   µg/m³
1   µg/m³
2   µg/m³
3   µg/m³
4   µg/m³
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2024-01-01 01:00:00  2024    1    1     1   8.98            8.98   ug/m3
1 2024-01-01 02:00:00  2024    1    1     2   7.11            7.11   ug/m3
2 2024-01-01 03:00:00  2024    1    1     3   6.93            6.93   ug/m3
3 2024-01-01 04:00:00  2024    1    1     4   6.60            6.60   ug/m3
4 2024-01-01 05:00:00  2024    1    1     5   7.73            7.73   ug/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
                               DATETIME   ANO  MES  DIA  HORA  VALOR  \
DATETIME
2024-01-01 01:00:00 2024-01-01 01:00:00  2024    1    1     1   8.98
2024-01-01 02:00:00 2024-01-01 02:00:00  2024    1    1     2   7.11
2024-01-01 03:00:00 2024-01-01 03:00:00  2024    1    1     3   6.93
2024-01-01 04:00:00 2024-01-01 04:00:00  2024    1    1     4   6.60
2024-01-01 05:00:00 2024-01-01 05:00:00  2024    1    1     5   7.73

                     VALOR_ORIGINAL UNIDADE  QAQC_INTERNO  QAQC_MMA
DATETIME
2024-01-01 01:00:00            8.98   ug/m3          True      True
2024-01-01 02:00:00            7.11   ug/m3          True      True
2024-01-01 03:00:00            6.93   ug/m3          True      True
2024-01-01 04:00:00            6.60   ug/m3          True      True
2024-01-01 05:00:00            7.73   ug/m3          True      True
SO2
Index(['CO', 'DATA', 'HORA', 'MP10', 'MP25', 'NO2', 'O3', 'QAQC_CO',
       'QAQC_MP10', 'QAQC_MP25', 'QAQC_NO2', 'QAQC_O3', 'QAQC_SO2', 'SO2'],
      dtype='object')
FercalCRAS
DF0001
iema
   VALOR_ORIGINAL   ANO  MES  DIA  HORA QAQC_INTERNO            DATETIME  \
0          65.831  2024    8   24    10           VA 2024-08-24 10:00:00
1          50.323  2024   12   18    16           VA 2024-12-18 16:00:00
2          49.445  2024    8   24     9           VA 2024-08-24 09:00:00
3          48.762  2024   12   15    16           VA 2024-12-15 16:00:00
4          39.444  2024   11   10    13           VA 2024-11-10 13:00:00

  UNIDADE
0   µg/m³
1   µg/m³
2   µg/m³
3   µg/m³
4   µg/m³
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2024-01-01 01:00:00  2024    1    1     1  0.233           0.233   ug/m3
1 2024-01-01 02:00:00  2024    1    1     2  0.142           0.142   ug/m3
2 2024-01-01 03:00:00  2024    1    1     3  0.756           0.756   ug/m3
3 2024-01-01 04:00:00  2024    1    1     4  0.214           0.214   ug/m3
4 2024-01-01 05:00:00  2024    1    1     5  0.060           0.060   ug/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
                               DATETIME   ANO  MES  DIA  HORA  VALOR  \
DATETIME
2024-01-01 01:00:00 2024-01-01 01:00:00  2024    1    1     1  0.233
2024-01-01 02:00:00 2024-01-01 02:00:00  2024    1    1     2  0.142
2024-01-01 03:00:00 2024-01-01 03:00:00  2024    1    1     3  0.756
2024-01-01 04:00:00 2024-01-01 04:00:00  2024    1    1     4  0.214
2024-01-01 05:00:00 2024-01-01 05:00:00  2024    1    1     5  0.060

                     VALOR_ORIGINAL UNIDADE  QAQC_INTERNO  QAQC_MMA
DATETIME
2024-01-01 01:00:00           0.233   ug/m3          True      True
2024-01-01 02:00:00           0.142   ug/m3          True      True
2024-01-01 03:00:00           0.756   ug/m3          True      True
2024-01-01 04:00:00           0.214   ug/m3          True      True
2024-01-01 05:00:00           0.060   ug/m3          True      True

/tmp/ipykernel_273420/3647521321.py:78: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_monitorar['DATA_HORA_STRING'] = df_monitorar['DATA'] + ' ' + df_monitorar['HORA']
/tmp/ipykernel_273420/3647521321.py:80: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_monitorar['DATETIME'] = pd.to_datetime(
/tmp/ipykernel_273420/3647521321.py:173: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_273420/3647521321.py:78: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_monitorar['DATA_HORA_STRING'] = df_monitorar['DATA'] + ' ' + df_monitorar['HORA']
/tmp/ipykernel_273420/3647521321.py:80: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_monitorar['DATETIME'] = pd.to_datetime(
/tmp/ipykernel_273420/3647521321.py:173: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(

.ipynb_checkpoints
PR
MG
EstaçãoFilinhaGama.csv
MP10
Index(['DATA', 'HORA', 'MP10', 'MP25', 'QAQC_MP10', 'QAQC_MP25'], dtype='object')
EstaçãoFilinhaGama
MG0023

/tmp/ipykernel_273420/3647521321.py:47: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  df_consolidado = df.groupby(df.columns, axis=1).first()
/tmp/ipykernel_273420/3647521321.py:78: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_monitorar['DATA_HORA_STRING'] = df_monitorar['DATA'] + ' ' + df_monitorar['HORA']
/tmp/ipykernel_273420/3647521321.py:173: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(

iema
   VALOR_ORIGINAL   ANO  MES  DIA  HORA QAQC_INTERNO            DATETIME  \
0           985.0  2022    3   26    22           IV 2022-03-26 22:00:00
1           985.0  2024   12   31    23           IV 2024-12-31 23:00:00
2           985.0  2024   12   31    22           IV 2024-12-31 22:00:00
3           985.0  2024   12   31    21           IV 2024-12-31 21:00:00
4           985.0  2024   12   31    20           IV 2024-12-31 20:00:00

  UNIDADE
0   µg/m³
1   µg/m³
2   µg/m³
3   µg/m³
4   µg/m³
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2015-03-10 17:00:00  2015    3   10    17   64.0            64.0   µg/m3
1 2015-03-10 18:00:00  2015    3   10    18   99.0            99.0   µg/m3
2 2015-03-10 19:00:00  2015    3   10    19   80.0            80.0   µg/m3
3 2015-03-10 20:00:00  2015    3   10    20  122.0           122.0   µg/m3
4 2015-03-10 21:00:00  2015    3   10    21   42.0            42.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
                               DATETIME   ANO  MES  DIA  HORA  VALOR  \
DATETIME
2015-03-10 17:00:00 2015-03-10 17:00:00  2015    3   10    17   64.0
2015-03-10 18:00:00 2015-03-10 18:00:00  2015    3   10    18   99.0
2015-03-10 19:00:00 2015-03-10 19:00:00  2015    3   10    19   80.0
2015-03-10 20:00:00 2015-03-10 20:00:00  2015    3   10    20  122.0
2015-03-10 21:00:00 2015-03-10 21:00:00  2015    3   10    21   42.0

                     VALOR_ORIGINAL UNIDADE  QAQC_INTERNO  QAQC_MMA
DATETIME
2015-03-10 17:00:00            64.0   µg/m3          True      True
2015-03-10 18:00:00            99.0   µg/m3          True      True
2015-03-10 19:00:00            80.0   µg/m3          True      True
2015-03-10 20:00:00           122.0   µg/m3          True      True
2015-03-10 21:00:00            42.0   µg/m3          True      True
MP25
Index(['DATA', 'HORA', 'MP10', 'MP25', 'QAQC_MP10', 'QAQC_MP25'], dtype='object')
EstaçãoFilinhaGama
MG0023

/tmp/ipykernel_273420/3647521321.py:78: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_monitorar['DATA_HORA_STRING'] = df_monitorar['DATA'] + ' ' + df_monitorar['HORA']
/tmp/ipykernel_273420/3647521321.py:173: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(

iema
   VALOR_ORIGINAL   ANO  MES  DIA  HORA QAQC_INTERNO            DATETIME  \
0           985.0  2022    3   26    12           IM 2022-03-26 12:00:00
1           985.0  2022    3   26    21           IV 2022-03-26 21:00:00
2           985.0  2022    3   26    18           IM 2022-03-26 18:00:00
3           985.0  2024   12   31     7           IV 2024-12-31 07:00:00
4           985.0  2024   12   29     8           IV 2024-12-29 08:00:00

  UNIDADE
0   µg/m³
1   µg/m³
2   µg/m³
3   µg/m³
4   µg/m³
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2015-03-10 17:00:00  2015    3   10    17    NaN             NaN   µg/m3
1 2015-03-10 18:00:00  2015    3   10    18    2.0             2.0   µg/m3
2 2015-03-10 19:00:00  2015    3   10    19   10.0            10.0   µg/m3
3 2015-03-10 20:00:00  2015    3   10    20   15.0            15.0   µg/m3
4 2015-03-10 21:00:00  2015    3   10    21    3.0             3.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True      True
2          True      True
3          True      True
4          True      True
final
                               DATETIME   ANO  MES  DIA  HORA  VALOR  \
DATETIME
2015-03-10 17:00:00 2015-03-10 17:00:00  2015    3   10    17    NaN
2015-03-10 18:00:00 2015-03-10 18:00:00  2015    3   10    18    2.0
2015-03-10 19:00:00 2015-03-10 19:00:00  2015    3   10    19   10.0
2015-03-10 20:00:00 2015-03-10 20:00:00  2015    3   10    20   15.0
2015-03-10 21:00:00 2015-03-10 21:00:00  2015    3   10    21    3.0

                     VALOR_ORIGINAL UNIDADE  QAQC_INTERNO  QAQC_MMA
DATETIME
2015-03-10 17:00:00             NaN   µg/m3          True     False
2015-03-10 18:00:00             2.0   µg/m3          True      True
2015-03-10 19:00:00            10.0   µg/m3          True      True
2015-03-10 20:00:00            15.0   µg/m3          True      True
2015-03-10 21:00:00             3.0   µg/m3          True      True

/tmp/ipykernel_273420/3647521321.py:47: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  df_consolidado = df.groupby(df.columns, axis=1).first()

EstaçãoPanorama.csv
PTS
Index(['DATA', 'HORA', 'MP10', 'MP25', 'PTS', 'QAQC_MP10', 'QAQC_MP25',
       'QAQC_PTS'],
      dtype='object')
EstaçãoPanorama
MG0028

/tmp/ipykernel_273420/3647521321.py:78: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_monitorar['DATA_HORA_STRING'] = df_monitorar['DATA'] + ' ' + df_monitorar['HORA']
/tmp/ipykernel_273420/3647521321.py:80: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_monitorar['DATETIME'] = pd.to_datetime(
/tmp/ipykernel_273420/3647521321.py:173: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(

iema
   VALOR_ORIGINAL   ANO  MES  DIA  HORA QAQC_INTERNO            DATETIME  \
0          4985.0  2024   12   17    12           IV 2024-12-17 12:30:00
1          4985.0  2024   12   17    13           IV 2024-12-17 13:30:00
2          4985.0  2024   12   27    11           IV 2024-12-27 11:30:00
3          4985.0  2024   12   30     6           IV 2024-12-30 06:30:00
4          4985.0  2024   12   20    11           IV 2024-12-20 11:30:00

  UNIDADE
0   µg/m³
1   µg/m³
2   µg/m³
3   µg/m³
4   µg/m³
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2015-01-01 01:00:00  2015    1    1     1   54.3            54.3   µg/m3
1 2015-01-01 02:00:00  2015    1    1     2   43.2            43.2   µg/m3
2 2015-01-01 03:00:00  2015    1    1     3   16.2            16.2   µg/m3
3 2015-01-01 04:00:00  2015    1    1     4   23.1            23.1   µg/m3
4 2015-01-01 05:00:00  2015    1    1     5   18.6            18.6   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
                               DATETIME   ANO  MES  DIA  HORA  VALOR  \
DATETIME
2015-01-01 01:00:00 2015-01-01 01:00:00  2015    1    1     1   54.3
2015-01-01 02:00:00 2015-01-01 02:00:00  2015    1    1     2   43.2
2015-01-01 03:00:00 2015-01-01 03:00:00  2015    1    1     3   16.2
2015-01-01 04:00:00 2015-01-01 04:00:00  2015    1    1     4   23.1
2015-01-01 05:00:00 2015-01-01 05:00:00  2015    1    1     5   18.6

                     VALOR_ORIGINAL UNIDADE  QAQC_INTERNO  QAQC_MMA
DATETIME
2015-01-01 01:00:00            54.3   µg/m3          True      True
2015-01-01 02:00:00            43.2   µg/m3          True      True
2015-01-01 03:00:00            16.2   µg/m3          True      True
2015-01-01 04:00:00            23.1   µg/m3          True      True
2015-01-01 05:00:00            18.6   µg/m3          True      True
MP10
Index(['DATA', 'HORA', 'MP10', 'MP25', 'PTS', 'QAQC_MP10', 'QAQC_MP25',
       'QAQC_PTS'],
      dtype='object')
EstaçãoPanorama
MG0028

/tmp/ipykernel_273420/3647521321.py:78: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_monitorar['DATA_HORA_STRING'] = df_monitorar['DATA'] + ' ' + df_monitorar['HORA']
/tmp/ipykernel_273420/3647521321.py:80: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_monitorar['DATETIME'] = pd.to_datetime(
/tmp/ipykernel_273420/3647521321.py:173: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(

iema
   VALOR_ORIGINAL   ANO  MES  DIA  HORA QAQC_INTERNO            DATETIME  \
0         6533.94  2022    5   19    22           IM 2022-05-19 22:30:00
1         4985.00  2024    3   31    18           IM 2024-03-31 18:30:00
2         4985.00  2024    3   31    20           IM 2024-03-31 20:30:00
3         4985.00  2024    3   31    19           IM 2024-03-31 19:30:00
4         4985.00  2024    3   28     0           IM 2024-03-28 00:30:00

  UNIDADE
0   µg/m³
1   µg/m³
2   µg/m³
3   µg/m³
4   µg/m³
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2015-01-01 01:00:00  2015    1    1     1   36.4            36.4   µg/m3
1 2015-01-01 02:00:00  2015    1    1     2   27.1            27.1   µg/m3
2 2015-01-01 03:00:00  2015    1    1     3    9.5             9.5   µg/m3
3 2015-01-01 04:00:00  2015    1    1     4   13.3            13.3   µg/m3
4 2015-01-01 05:00:00  2015    1    1     5   11.4            11.4   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
                               DATETIME   ANO  MES  DIA  HORA  VALOR  \
DATETIME
2015-01-01 01:00:00 2015-01-01 01:00:00  2015    1    1     1   36.4
2015-01-01 02:00:00 2015-01-01 02:00:00  2015    1    1     2   27.1
2015-01-01 03:00:00 2015-01-01 03:00:00  2015    1    1     3    9.5
2015-01-01 04:00:00 2015-01-01 04:00:00  2015    1    1     4   13.3
2015-01-01 05:00:00 2015-01-01 05:00:00  2015    1    1     5   11.4

                     VALOR_ORIGINAL UNIDADE  QAQC_INTERNO  QAQC_MMA
DATETIME
2015-01-01 01:00:00            36.4   µg/m3          True      True
2015-01-01 02:00:00            27.1   µg/m3          True      True
2015-01-01 03:00:00             9.5   µg/m3          True      True
2015-01-01 04:00:00            13.3   µg/m3          True      True
2015-01-01 05:00:00            11.4   µg/m3          True      True
MP25
Index(['DATA', 'HORA', 'MP10', 'MP25', 'PTS', 'QAQC_MP10', 'QAQC_MP25',
       'QAQC_PTS'],
      dtype='object')
EstaçãoPanorama
MG0028

/tmp/ipykernel_273420/3647521321.py:78: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_monitorar['DATA_HORA_STRING'] = df_monitorar['DATA'] + ' ' + df_monitorar['HORA']
/tmp/ipykernel_273420/3647521321.py:80: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_monitorar['DATETIME'] = pd.to_datetime(
/tmp/ipykernel_273420/3647521321.py:173: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(

iema
   VALOR_ORIGINAL   ANO  MES  DIA  HORA QAQC_INTERNO            DATETIME  \
0        6577.662  2022    5   19    22           IM 2022-05-19 22:30:00
1        4985.000  2024    3    1     5           IM 2024-03-01 05:30:00
2        4985.000  2024    3    1     4           IM 2024-03-01 04:30:00
3        4985.000  2023    6   17    20           IM 2023-06-17 20:30:00
4        4985.000  2023    6   17    19           IM 2023-06-17 19:30:00

  UNIDADE
0   µg/m³
1   µg/m³
2   µg/m³
3   µg/m³
4   µg/m³
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2020-01-01 01:00:00  2020    1    1     1    NaN             NaN   µg/m3
1 2020-01-01 02:00:00  2020    1    1     2    NaN             NaN   µg/m3
2 2020-01-01 03:00:00  2020    1    1     3    NaN             NaN   µg/m3
3 2020-01-01 04:00:00  2020    1    1     4    NaN             NaN   µg/m3
4 2020-01-01 05:00:00  2020    1    1     5    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
                               DATETIME   ANO  MES  DIA  HORA  VALOR  \
DATETIME
2020-01-01 01:00:00 2020-01-01 01:00:00  2020    1    1     1    NaN
2020-01-01 02:00:00 2020-01-01 02:00:00  2020    1    1     2    NaN
2020-01-01 03:00:00 2020-01-01 03:00:00  2020    1    1     3    NaN
2020-01-01 04:00:00 2020-01-01 04:00:00  2020    1    1     4    NaN
2020-01-01 05:00:00 2020-01-01 05:00:00  2020    1    1     5    NaN

                     VALOR_ORIGINAL UNIDADE  QAQC_INTERNO  QAQC_MMA
DATETIME
2020-01-01 01:00:00             NaN   µg/m3          True     False
2020-01-01 02:00:00             NaN   µg/m3          True     False
2020-01-01 03:00:00             NaN   µg/m3          True     False
2020-01-01 04:00:00             NaN   µg/m3          True     False
2020-01-01 05:00:00             NaN   µg/m3          True     False

/tmp/ipykernel_273420/3647521321.py:47: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  df_consolidado = df.groupby(df.columns, axis=1).first()

EstaçãoCentroBarraLonga.csv
PTS
Index(['DATA', 'HORA', 'MP10', 'MP25', 'PTS', 'QAQC_MP10', 'QAQC_MP25',
       'QAQC_PTS'],
      dtype='object')
EstaçãoCentroBarraLonga
MG0032

/tmp/ipykernel_273420/3647521321.py:78: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_monitorar['DATA_HORA_STRING'] = df_monitorar['DATA'] + ' ' + df_monitorar['HORA']
/tmp/ipykernel_273420/3647521321.py:80: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_monitorar['DATETIME'] = pd.to_datetime(
/tmp/ipykernel_273420/3647521321.py:173: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(

iema
   VALOR_ORIGINAL   ANO  MES  DIA  HORA QAQC_INTERNO            DATETIME  \
0          1985.0  2023    7   20    10           IV 2023-07-20 10:30:00
1          1985.0  2024   12   11    15           IV 2024-12-11 15:30:00
2          1985.0  2024   12   15    18           IV 2024-12-15 18:30:00
3          1985.0  2023    7   24    10           IV 2023-07-24 10:30:00
4          1985.0  2024   12   28    10           IV 2024-12-28 10:30:00

  UNIDADE
0   µg/m³
1   µg/m³
2   µg/m³
3   µg/m³
4   µg/m³
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2016-02-18 11:00:00  2016    2   18    11    NaN             0.0   µg/m3
1 2016-02-18 12:00:00  2016    2   18    12    NaN             NaN   µg/m3
2 2016-02-18 13:00:00  2016    2   18    13    NaN             NaN   µg/m3
3 2016-02-18 14:00:00  2016    2   18    14    NaN             NaN   µg/m3
4 2016-02-18 15:00:00  2016    2   18    15  144.0           144.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True      True
final
                               DATETIME   ANO  MES  DIA  HORA  VALOR  \
DATETIME
2016-02-18 11:00:00 2016-02-18 11:00:00  2016    2   18    11    NaN
2016-02-18 12:00:00 2016-02-18 12:00:00  2016    2   18    12    NaN
2016-02-18 13:00:00 2016-02-18 13:00:00  2016    2   18    13    NaN
2016-02-18 14:00:00 2016-02-18 14:00:00  2016    2   18    14    NaN
2016-02-18 15:00:00 2016-02-18 15:00:00  2016    2   18    15  144.0

                     VALOR_ORIGINAL UNIDADE  QAQC_INTERNO  QAQC_MMA
DATETIME
2016-02-18 11:00:00             0.0   µg/m3          True     False
2016-02-18 12:00:00             NaN   µg/m3          True     False
2016-02-18 13:00:00             NaN   µg/m3          True     False
2016-02-18 14:00:00             NaN   µg/m3          True     False
2016-02-18 15:00:00           144.0   µg/m3          True      True
MP10
Index(['DATA', 'HORA', 'MP10', 'MP25', 'PTS', 'QAQC_MP10', 'QAQC_MP25',
       'QAQC_PTS'],
      dtype='object')
EstaçãoCentroBarraLonga
MG0032

/tmp/ipykernel_273420/3647521321.py:78: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_monitorar['DATA_HORA_STRING'] = df_monitorar['DATA'] + ' ' + df_monitorar['HORA']
/tmp/ipykernel_273420/3647521321.py:80: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_monitorar['DATETIME'] = pd.to_datetime(
/tmp/ipykernel_273420/3647521321.py:173: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(

iema
   VALOR_ORIGINAL   ANO  MES  DIA  HORA QAQC_INTERNO            DATETIME  \
0          1985.0  2023    6   19     5           IM 2023-06-19 05:30:00
1          1985.0  2023    7   12    11           IM 2023-07-12 11:30:00
2          1985.0  2024   12   28    10           IV 2024-12-28 10:30:00
3          1985.0  2023    7   11    12           IM 2023-07-11 12:30:00
4          1985.0  2023    7   12    10           IV 2023-07-12 10:30:00

  UNIDADE
0   µg/m³
1   µg/m³
2   µg/m³
3   µg/m³
4   µg/m³
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2016-02-18 11:00:00  2016    2   18    11    NaN             NaN   µg/m3
1 2016-02-18 12:00:00  2016    2   18    12    NaN             NaN   µg/m3
2 2016-02-18 13:00:00  2016    2   18    13    NaN             NaN   µg/m3
3 2016-02-18 14:00:00  2016    2   18    14    NaN             NaN   µg/m3
4 2016-02-18 15:00:00  2016    2   18    15    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
                               DATETIME   ANO  MES  DIA  HORA  VALOR  \
DATETIME
2016-02-18 11:00:00 2016-02-18 11:00:00  2016    2   18    11    NaN
2016-02-18 12:00:00 2016-02-18 12:00:00  2016    2   18    12    NaN
2016-02-18 13:00:00 2016-02-18 13:00:00  2016    2   18    13    NaN
2016-02-18 14:00:00 2016-02-18 14:00:00  2016    2   18    14    NaN
2016-02-18 15:00:00 2016-02-18 15:00:00  2016    2   18    15    NaN

                     VALOR_ORIGINAL UNIDADE  QAQC_INTERNO  QAQC_MMA
DATETIME
2016-02-18 11:00:00             NaN   µg/m3          True     False
2016-02-18 12:00:00             NaN   µg/m3          True     False
2016-02-18 13:00:00             NaN   µg/m3          True     False
2016-02-18 14:00:00             NaN   µg/m3          True     False
2016-02-18 15:00:00             NaN   µg/m3          True     False
MP25
Index(['DATA', 'HORA', 'MP10', 'MP25', 'PTS', 'QAQC_MP10', 'QAQC_MP25',
       'QAQC_PTS'],
      dtype='object')
EstaçãoCentroBarraLonga
MG0032

/tmp/ipykernel_273420/3647521321.py:78: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_monitorar['DATA_HORA_STRING'] = df_monitorar['DATA'] + ' ' + df_monitorar['HORA']
/tmp/ipykernel_273420/3647521321.py:80: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_monitorar['DATETIME'] = pd.to_datetime(
/tmp/ipykernel_273420/3647521321.py:173: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(

iema
   VALOR_ORIGINAL   ANO  MES  DIA  HORA QAQC_INTERNO            DATETIME  \
0           985.0  2024   10    1    12           IV 2024-10-01 12:30:00
1           985.0  2024    9   30    18           IV 2024-09-30 18:30:00
2           985.0  2023    2    7    18           IV 2023-02-07 18:30:00
3           985.0  2023    6   15    11           IV 2023-06-15 11:30:00
4           985.0  2023    9   20    10           IM 2023-09-20 10:30:00

  UNIDADE
0   µg/m³
1   µg/m³
2   µg/m³
3   µg/m³
4   µg/m³
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2016-02-18 11:00:00  2016    2   18    11    NaN             NaN   µg/m3
1 2016-02-18 12:00:00  2016    2   18    12    NaN             NaN   µg/m3
2 2016-02-18 13:00:00  2016    2   18    13    NaN             NaN   µg/m3
3 2016-02-18 14:00:00  2016    2   18    14    NaN             NaN   µg/m3
4 2016-02-18 15:00:00  2016    2   18    15    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
                               DATETIME   ANO  MES  DIA  HORA  VALOR  \
DATETIME
2016-02-18 11:00:00 2016-02-18 11:00:00  2016    2   18    11    NaN
2016-02-18 12:00:00 2016-02-18 12:00:00  2016    2   18    12    NaN
2016-02-18 13:00:00 2016-02-18 13:00:00  2016    2   18    13    NaN
2016-02-18 14:00:00 2016-02-18 14:00:00  2016    2   18    14    NaN
2016-02-18 15:00:00 2016-02-18 15:00:00  2016    2   18    15    NaN

                     VALOR_ORIGINAL UNIDADE  QAQC_INTERNO  QAQC_MMA
DATETIME
2016-02-18 11:00:00             NaN   µg/m3          True     False
2016-02-18 12:00:00             NaN   µg/m3          True     False
2016-02-18 13:00:00             NaN   µg/m3          True     False
2016-02-18 14:00:00             NaN   µg/m3          True     False
2016-02-18 15:00:00             NaN   µg/m3          True     False

/tmp/ipykernel_273420/3647521321.py:47: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  df_consolidado = df.groupby(df.columns, axis=1).first()

EstaçãoSAAE.csv
MP10
Index(['DATA', 'HORA', 'MP10', 'QAQC_MP10'], dtype='object')
EstaçãoSAAE
MG0029

/tmp/ipykernel_273420/3647521321.py:173: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(

iema
   VALOR_ORIGINAL   ANO  MES  DIA  HORA QAQC_INTERNO            DATETIME  \
0          1000.0  2023    6   15     0           IV 2023-06-15 00:30:00
1           995.0  2022    4   19    11           IV 2022-04-19 11:30:00
2           995.0  2023    2    5     8           IV 2023-02-05 08:30:00
3           995.0  2023    2    5     7           IV 2023-02-05 07:30:00
4           995.0  2023    2    5     6           IV 2023-02-05 06:30:00

  UNIDADE
0   µg/m³
1   µg/m³
2   µg/m³
3   µg/m³
4   µg/m³
mma
             DATETIME     ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2015-01-01 01:00:00  2015.0  1.0  1.0   1.0    NaN             NaN   µg/m3
1 2015-01-01 02:00:00  2015.0  1.0  1.0   2.0  41.75           41.75   µg/m3
2 2015-01-01 03:00:00  2015.0  1.0  1.0   3.0  48.10           48.10   µg/m3
3 2015-01-01 04:00:00  2015.0  1.0  1.0   4.0  37.84           37.84   µg/m3
4 2015-01-01 05:00:00  2015.0  1.0  1.0   5.0  68.12           68.12   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True      True
2          True      True
3          True      True
4          True      True
final
                               DATETIME   ANO  MES  DIA  HORA  VALOR  \
DATETIME
2015-01-01 01:00:00 2015-01-01 01:00:00  2015    1    1     1    NaN
2015-01-01 02:00:00 2015-01-01 02:00:00  2015    1    1     2  41.75
2015-01-01 03:00:00 2015-01-01 03:00:00  2015    1    1     3  48.10
2015-01-01 04:00:00 2015-01-01 04:00:00  2015    1    1     4  37.84
2015-01-01 05:00:00 2015-01-01 05:00:00  2015    1    1     5  68.12

                     VALOR_ORIGINAL UNIDADE  QAQC_INTERNO  QAQC_MMA
DATETIME
2015-01-01 01:00:00             NaN   µg/m3          True     False
2015-01-01 02:00:00           41.75   µg/m3          True      True
2015-01-01 03:00:00           48.10   µg/m3          True      True
2015-01-01 04:00:00           37.84   µg/m3          True      True
2015-01-01 05:00:00           68.12   µg/m3          True      True

/tmp/ipykernel_273420/3647521321.py:47: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  df_consolidado = df.groupby(df.columns, axis=1).first()

EstaçãoBasílica.csv
NOX
Index(['DATA', 'HORA', 'MP10', 'MP25', 'NO', 'NO2', 'NOX', 'O3', 'PTS',
       'QAQC_MP10', 'QAQC_MP25', 'QAQC_NO', 'QAQC_NO2', 'QAQC_NOX', 'QAQC_O3',
       'QAQC_PTS', 'QAQC_SO2', 'SO2'],
      dtype='object')

/tmp/ipykernel_273420/3647521321.py:78: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_monitorar['DATA_HORA_STRING'] = df_monitorar['DATA'] + ' ' + df_monitorar['HORA']
/tmp/ipykernel_273420/3647521321.py:80: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_monitorar['DATETIME'] = pd.to_datetime(
/tmp/ipykernel_273420/3647521321.py:173: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(

EstaçãoBasílica
MG0036
iema
   VALOR_ORIGINAL   ANO  MES  DIA  HORA QAQC_INTERNO            DATETIME  \
0         1342.10  2024    8   28    14           IV 2024-08-28 14:30:00
1          165.36  2022    6    7     9           VA 2022-06-07 09:30:00
2          145.57  2023    6   29     9           VA 2023-06-29 09:30:00
3          134.34  2023    6    7     9           VA 2023-06-07 09:30:00
4          129.70  2022    6    3     9           VA 2022-06-03 09:30:00

  UNIDADE
0   µg/m³
1   µg/m³
2   µg/m³
3   µg/m³
4   µg/m³
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL  \
0 2022-01-01 00:30:00  2022    1    1     0   5.34            5.34
1 2022-01-01 01:30:00  2022    1    1     1   5.89            5.89
2 2022-01-01 02:30:00  2022    1    1     2   8.35            8.35
3 2022-01-01 03:30:00  2022    1    1     3   6.69            6.69
4 2022-01-01 04:30:00  2022    1    1     4   5.21            5.21

        UNIDADE  QAQC_INTERNO  QAQC_MMA
0  desconhecida          True      True
1  desconhecida          True      True
2  desconhecida          True      True
3  desconhecida          True      True
4  desconhecida          True      True
final
                               DATETIME   ANO  MES  DIA  HORA  VALOR  \
DATETIME
2022-01-01 00:30:00 2022-01-01 00:30:00  2022    1    1     0   5.34
2022-01-01 01:30:00 2022-01-01 01:30:00  2022    1    1     1   5.89
2022-01-01 02:30:00 2022-01-01 02:30:00  2022    1    1     2   8.35
2022-01-01 03:30:00 2022-01-01 03:30:00  2022    1    1     3   6.69
2022-01-01 04:30:00 2022-01-01 04:30:00  2022    1    1     4   5.21

                     VALOR_ORIGINAL UNIDADE  QAQC_INTERNO  QAQC_MMA
DATETIME
2022-01-01 00:30:00            5.34   µg/m³          True      True
2022-01-01 01:30:00            5.89   µg/m³          True      True
2022-01-01 02:30:00            8.35   µg/m³          True      True
2022-01-01 03:30:00            6.69   µg/m³          True      True
2022-01-01 04:30:00            5.21   µg/m³          True      True
NO2
Index(['DATA', 'HORA', 'MP10', 'MP25', 'NO', 'NO2', 'NOX', 'O3', 'PTS',
       'QAQC_MP10', 'QAQC_MP25', 'QAQC_NO', 'QAQC_NO2', 'QAQC_NOX', 'QAQC_O3',
       'QAQC_PTS', 'QAQC_SO2', 'SO2'],
      dtype='object')
EstaçãoBasílica
MG0036

/tmp/ipykernel_273420/3647521321.py:78: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_monitorar['DATA_HORA_STRING'] = df_monitorar['DATA'] + ' ' + df_monitorar['HORA']
/tmp/ipykernel_273420/3647521321.py:80: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_monitorar['DATETIME'] = pd.to_datetime(
/tmp/ipykernel_273420/3647521321.py:173: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(

iema
   VALOR_ORIGINAL   ANO  MES  DIA  HORA QAQC_INTERNO            DATETIME  \
0          168.62  2024    8   28    14           IV 2024-08-28 14:30:00
1          150.00  2022    6    7    22           VA 2022-06-07 22:30:00
2          150.00  2023    8    8     1           VA 2023-08-08 01:30:00
3          140.00  2022    6    8     0           VA 2022-06-08 00:30:00
4          140.00  2023    8    8     0           VA 2023-08-08 00:30:00

  UNIDADE
0   µg/m³
1   µg/m³
2   µg/m³
3   µg/m³
4   µg/m³
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2017-08-22 17:00:00  2017    8   22    17    NaN             NaN   µg/m3
1 2017-08-22 18:00:00  2017    8   22    18    2.8             2.8   µg/m3
2 2017-08-22 19:00:00  2017    8   22    19    3.6             3.6   µg/m3
3 2017-08-22 20:00:00  2017    8   22    20    4.5             4.5   µg/m3
4 2017-08-22 21:00:00  2017    8   22    21    4.8             4.8   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True      True
2          True      True
3          True      True
4          True      True
final
                               DATETIME   ANO  MES  DIA  HORA  VALOR  \
DATETIME
2017-08-22 17:00:00 2017-08-22 17:00:00  2017    8   22    17    NaN
2017-08-22 18:00:00 2017-08-22 18:00:00  2017    8   22    18    2.8
2017-08-22 19:00:00 2017-08-22 19:00:00  2017    8   22    19    3.6
2017-08-22 20:00:00 2017-08-22 20:00:00  2017    8   22    20    4.5
2017-08-22 21:00:00 2017-08-22 21:00:00  2017    8   22    21    4.8

                     VALOR_ORIGINAL UNIDADE  QAQC_INTERNO  QAQC_MMA
DATETIME
2017-08-22 17:00:00             NaN   µg/m3          True     False
2017-08-22 18:00:00             2.8   µg/m3          True      True
2017-08-22 19:00:00             3.6   µg/m3          True      True
2017-08-22 20:00:00             4.5   µg/m3          True      True
2017-08-22 21:00:00             4.8   µg/m3          True      True
PTS
Index(['DATA', 'HORA', 'MP10', 'MP25', 'NO', 'NO2', 'NOX', 'O3', 'PTS',
       'QAQC_MP10', 'QAQC_MP25', 'QAQC_NO', 'QAQC_NO2', 'QAQC_NOX', 'QAQC_O3',
       'QAQC_PTS', 'QAQC_SO2', 'SO2'],
      dtype='object')
EstaçãoBasílica
MG0036

/tmp/ipykernel_273420/3647521321.py:78: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_monitorar['DATA_HORA_STRING'] = df_monitorar['DATA'] + ' ' + df_monitorar['HORA']
/tmp/ipykernel_273420/3647521321.py:80: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_monitorar['DATETIME'] = pd.to_datetime(
/tmp/ipykernel_273420/3647521321.py:173: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(

iema
   VALOR_ORIGINAL   ANO  MES  DIA  HORA QAQC_INTERNO            DATETIME  \
0          1000.0  2024   12   29    14           IV 2024-12-29 14:30:00
1          1000.0  2024   12   30     8           IV 2024-12-30 08:30:00
2          1000.0  2024   12   25    11           IV 2024-12-25 11:30:00
3          1000.0  2024   12   25    12           IV 2024-12-25 12:30:00
4          1000.0  2024   12   22    14           IV 2024-12-22 14:30:00

  UNIDADE
0   µg/m³
1   µg/m³
2   µg/m³
3   µg/m³
4   µg/m³
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2017-08-22 17:00:00  2017    8   22    17   60.0            60.0   µg/m3
1 2017-08-22 18:00:00  2017    8   22    18   58.0            58.0   µg/m3
2 2017-08-22 19:00:00  2017    8   22    19    NaN             NaN   µg/m3
3 2017-08-22 20:00:00  2017    8   22    20   34.0            34.0   µg/m3
4 2017-08-22 21:00:00  2017    8   22    21   28.0            28.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True     False
3          True      True
4          True      True
final
                               DATETIME   ANO  MES  DIA  HORA  VALOR  \
DATETIME
2017-08-22 17:00:00 2017-08-22 17:00:00  2017    8   22    17   60.0
2017-08-22 18:00:00 2017-08-22 18:00:00  2017    8   22    18   58.0
2017-08-22 19:00:00 2017-08-22 19:00:00  2017    8   22    19    NaN
2017-08-22 20:00:00 2017-08-22 20:00:00  2017    8   22    20   34.0
2017-08-22 21:00:00 2017-08-22 21:00:00  2017    8   22    21   28.0

                     VALOR_ORIGINAL UNIDADE  QAQC_INTERNO  QAQC_MMA
DATETIME
2017-08-22 17:00:00            60.0   µg/m3          True      True
2017-08-22 18:00:00            58.0   µg/m3          True      True
2017-08-22 19:00:00             NaN   µg/m3          True     False
2017-08-22 20:00:00            34.0   µg/m3          True      True
2017-08-22 21:00:00            28.0   µg/m3          True      True
O3
Index(['DATA', 'HORA', 'MP10', 'MP25', 'NO', 'NO2', 'NOX', 'O3', 'PTS',
       'QAQC_MP10', 'QAQC_MP25', 'QAQC_NO', 'QAQC_NO2', 'QAQC_NOX', 'QAQC_O3',
       'QAQC_PTS', 'QAQC_SO2', 'SO2'],
      dtype='object')
EstaçãoBasílica
MG0036

/tmp/ipykernel_273420/3647521321.py:78: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_monitorar['DATA_HORA_STRING'] = df_monitorar['DATA'] + ' ' + df_monitorar['HORA']
/tmp/ipykernel_273420/3647521321.py:80: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_monitorar['DATETIME'] = pd.to_datetime(
/tmp/ipykernel_273420/3647521321.py:173: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(

iema
   VALOR_ORIGINAL   ANO  MES  DIA  HORA QAQC_INTERNO            DATETIME  \
0          178.03  2024    7   10    17           VA 2024-07-10 17:30:00
1          158.94  2023    9   25    13           VA 2023-09-25 13:30:00
2          155.92  2023   11   16    13           VA 2023-11-16 13:30:00
3          154.72  2023    9   26    15           VA 2023-09-26 15:30:00
4          153.88  2023    9   25    14           VA 2023-09-25 14:30:00

  UNIDADE
0   µg/m³
1   µg/m³
2   µg/m³
3   µg/m³
4   µg/m³
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2017-08-22 17:00:00  2017    8   22    17    NaN             NaN   µg/m3
1 2017-08-22 18:00:00  2017    8   22    18   23.6            23.6   µg/m3
2 2017-08-22 19:00:00  2017    8   22    19   23.1            23.1   µg/m3
3 2017-08-22 20:00:00  2017    8   22    20   21.7            21.7   µg/m3
4 2017-08-22 21:00:00  2017    8   22    21   21.4            21.4   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True      True
2          True      True
3          True      True
4          True      True
final
                               DATETIME   ANO  MES  DIA  HORA  VALOR  \
DATETIME
2017-08-22 17:00:00 2017-08-22 17:00:00  2017    8   22    17    NaN
2017-08-22 18:00:00 2017-08-22 18:00:00  2017    8   22    18   23.6
2017-08-22 19:00:00 2017-08-22 19:00:00  2017    8   22    19   23.1
2017-08-22 20:00:00 2017-08-22 20:00:00  2017    8   22    20   21.7
2017-08-22 21:00:00 2017-08-22 21:00:00  2017    8   22    21   21.4

                     VALOR_ORIGINAL UNIDADE  QAQC_INTERNO  QAQC_MMA
DATETIME
2017-08-22 17:00:00             NaN   µg/m3          True     False
2017-08-22 18:00:00            23.6   µg/m3          True      True
2017-08-22 19:00:00            23.1   µg/m3          True      True
2017-08-22 20:00:00            21.7   µg/m3          True      True
2017-08-22 21:00:00            21.4   µg/m3          True      True
MP10
Index(['DATA', 'HORA', 'MP10', 'MP25', 'NO', 'NO2', 'NOX', 'O3', 'PTS',
       'QAQC_MP10', 'QAQC_MP25', 'QAQC_NO', 'QAQC_NO2', 'QAQC_NOX', 'QAQC_O3',
       'QAQC_PTS', 'QAQC_SO2', 'SO2'],
      dtype='object')
EstaçãoBasílica
MG0036

/tmp/ipykernel_273420/3647521321.py:78: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_monitorar['DATA_HORA_STRING'] = df_monitorar['DATA'] + ' ' + df_monitorar['HORA']
/tmp/ipykernel_273420/3647521321.py:80: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_monitorar['DATETIME'] = pd.to_datetime(
/tmp/ipykernel_273420/3647521321.py:173: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(

iema
   VALOR_ORIGINAL   ANO  MES  DIA  HORA QAQC_INTERNO            DATETIME  \
0           992.0  2023    3   25     1           ID 2023-03-25 01:30:00
1           992.0  2023    5   15    18           ID 2023-05-15 18:30:00
2           992.0  2022   11   30    15           ID 2022-11-30 15:30:00
3           992.0  2023    1    3     2           ID 2023-01-03 02:30:00
4           992.0  2022   12    7    11           IM 2022-12-07 11:30:00

  UNIDADE
0   µg/m³
1   µg/m³
2   µg/m³
3   µg/m³
4   µg/m³
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2017-08-22 17:00:00  2017    8   22    17    NaN             NaN   µg/m3
1 2017-08-22 18:00:00  2017    8   22    18   18.0            18.0   µg/m3
2 2017-08-22 19:00:00  2017    8   22    19    NaN             NaN   µg/m3
3 2017-08-22 20:00:00  2017    8   22    20   18.0            18.0   µg/m3
4 2017-08-22 21:00:00  2017    8   22    21   10.0            10.0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True      True
2          True     False
3          True      True
4          True      True
final
                               DATETIME   ANO  MES  DIA  HORA  VALOR  \
DATETIME
2017-08-22 17:00:00 2017-08-22 17:00:00  2017    8   22    17    NaN
2017-08-22 18:00:00 2017-08-22 18:00:00  2017    8   22    18   18.0
2017-08-22 19:00:00 2017-08-22 19:00:00  2017    8   22    19    NaN
2017-08-22 20:00:00 2017-08-22 20:00:00  2017    8   22    20   18.0
2017-08-22 21:00:00 2017-08-22 21:00:00  2017    8   22    21   10.0

                     VALOR_ORIGINAL UNIDADE  QAQC_INTERNO  QAQC_MMA
DATETIME
2017-08-22 17:00:00             NaN   µg/m3          True     False
2017-08-22 18:00:00            18.0   µg/m3          True      True
2017-08-22 19:00:00             NaN   µg/m3          True     False
2017-08-22 20:00:00            18.0   µg/m3          True      True
2017-08-22 21:00:00            10.0   µg/m3          True      True
MP25
Index(['DATA', 'HORA', 'MP10', 'MP25', 'NO', 'NO2', 'NOX', 'O3', 'PTS',
       'QAQC_MP10', 'QAQC_MP25', 'QAQC_NO', 'QAQC_NO2', 'QAQC_NOX', 'QAQC_O3',
       'QAQC_PTS', 'QAQC_SO2', 'SO2'],
      dtype='object')
EstaçãoBasílica
MG0036

/tmp/ipykernel_273420/3647521321.py:78: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_monitorar['DATA_HORA_STRING'] = df_monitorar['DATA'] + ' ' + df_monitorar['HORA']
/tmp/ipykernel_273420/3647521321.py:80: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_monitorar['DATETIME'] = pd.to_datetime(
/tmp/ipykernel_273420/3647521321.py:173: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(

iema
   VALOR_ORIGINAL   ANO  MES  DIA  HORA QAQC_INTERNO            DATETIME  \
0           985.0  2024   12   11    11           IV 2024-12-11 11:30:00
1           985.0  2024   12   17    19           IV 2024-12-17 19:30:00
2           985.0  2023    3   11     3           IM 2023-03-11 03:30:00
3           985.0  2024   12   23     1           IM 2024-12-23 01:30:00
4           985.0  2024   12   25     1           IM 2024-12-25 01:30:00

  UNIDADE
0   µg/m³
1   µg/m³
2   µg/m³
3   µg/m³
4   µg/m³
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2018-01-01 01:00:00  2018    1    1     1    NaN             NaN   µg/m3
1 2018-01-01 02:00:00  2018    1    1     2    NaN             NaN   µg/m3
2 2018-01-01 03:00:00  2018    1    1     3    NaN             NaN   µg/m3
3 2018-01-01 04:00:00  2018    1    1     4    NaN             NaN   µg/m3
4 2018-01-01 05:00:00  2018    1    1     5    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
                               DATETIME   ANO  MES  DIA  HORA  VALOR  \
DATETIME
2018-01-01 01:00:00 2018-01-01 01:00:00  2018    1    1     1    NaN
2018-01-01 02:00:00 2018-01-01 02:00:00  2018    1    1     2    NaN
2018-01-01 03:00:00 2018-01-01 03:00:00  2018    1    1     3    NaN
2018-01-01 04:00:00 2018-01-01 04:00:00  2018    1    1     4    NaN
2018-01-01 05:00:00 2018-01-01 05:00:00  2018    1    1     5    NaN

                     VALOR_ORIGINAL UNIDADE  QAQC_INTERNO  QAQC_MMA
DATETIME
2018-01-01 01:00:00             NaN   µg/m3          True     False
2018-01-01 02:00:00             NaN   µg/m3          True     False
2018-01-01 03:00:00             NaN   µg/m3          True     False
2018-01-01 04:00:00             NaN   µg/m3          True     False
2018-01-01 05:00:00             NaN   µg/m3          True     False
NO
Index(['DATA', 'HORA', 'MP10', 'MP25', 'NO', 'NO2', 'NOX', 'O3', 'PTS',
       'QAQC_MP10', 'QAQC_MP25', 'QAQC_NO', 'QAQC_NO2', 'QAQC_NOX', 'QAQC_O3',
       'QAQC_PTS', 'QAQC_SO2', 'SO2'],
      dtype='object')
EstaçãoBasílica
MG0036

/tmp/ipykernel_273420/3647521321.py:78: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_monitorar['DATA_HORA_STRING'] = df_monitorar['DATA'] + ' ' + df_monitorar['HORA']
/tmp/ipykernel_273420/3647521321.py:80: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_monitorar['DATETIME'] = pd.to_datetime(
/tmp/ipykernel_273420/3647521321.py:173: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(

iema
   VALOR_ORIGINAL   ANO  MES  DIA  HORA QAQC_INTERNO            DATETIME  \
0         1226.50  2024    8   28    14           IV 2024-08-28 14:30:00
1          144.97  2022    6    7     9           VA 2022-06-07 09:30:00
2          126.69  2023    6   29     9           VA 2023-06-29 09:30:00
3          115.18  2023    6    7     9           VA 2023-06-07 09:30:00
4          111.98  2022    6    3     9           VA 2022-06-03 09:30:00

  UNIDADE
0   µg/m³
1   µg/m³
2   µg/m³
3   µg/m³
4   µg/m³
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL  \
0 2022-01-01 00:30:00  2022    1    1     0   0.79            0.79
1 2022-01-01 01:30:00  2022    1    1     1   1.00            1.00
2 2022-01-01 02:30:00  2022    1    1     2   1.64            1.64
3 2022-01-01 03:30:00  2022    1    1     3   1.15            1.15
4 2022-01-01 04:30:00  2022    1    1     4   1.07            1.07

        UNIDADE  QAQC_INTERNO  QAQC_MMA
0  desconhecida          True      True
1  desconhecida          True      True
2  desconhecida          True      True
3  desconhecida          True      True
4  desconhecida          True      True
final
                               DATETIME   ANO  MES  DIA  HORA  VALOR  \
DATETIME
2022-01-01 00:30:00 2022-01-01 00:30:00  2022    1    1     0   0.79
2022-01-01 01:30:00 2022-01-01 01:30:00  2022    1    1     1   1.00
2022-01-01 02:30:00 2022-01-01 02:30:00  2022    1    1     2   1.64
2022-01-01 03:30:00 2022-01-01 03:30:00  2022    1    1     3   1.15
2022-01-01 04:30:00 2022-01-01 04:30:00  2022    1    1     4   1.07

                     VALOR_ORIGINAL UNIDADE  QAQC_INTERNO  QAQC_MMA
DATETIME
2022-01-01 00:30:00            0.79   µg/m³          True      True
2022-01-01 01:30:00            1.00   µg/m³          True      True
2022-01-01 02:30:00            1.64   µg/m³          True      True
2022-01-01 03:30:00            1.15   µg/m³          True      True
2022-01-01 04:30:00            1.07   µg/m³          True      True
SO2
Index(['DATA', 'HORA', 'MP10', 'MP25', 'NO', 'NO2', 'NOX', 'O3', 'PTS',
       'QAQC_MP10', 'QAQC_MP25', 'QAQC_NO', 'QAQC_NO2', 'QAQC_NOX', 'QAQC_O3',
       'QAQC_PTS', 'QAQC_SO2', 'SO2'],
      dtype='object')

/tmp/ipykernel_273420/3647521321.py:78: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_monitorar['DATA_HORA_STRING'] = df_monitorar['DATA'] + ' ' + df_monitorar['HORA']
/tmp/ipykernel_273420/3647521321.py:80: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_monitorar['DATETIME'] = pd.to_datetime(
/tmp/ipykernel_273420/3647521321.py:173: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(

EstaçãoBasílica
MG0036
iema
   VALOR_ORIGINAL   ANO  MES  DIA  HORA QAQC_INTERNO            DATETIME  \
0          214.56  2022    3   25    10           VA 2022-03-25 10:30:00
1          103.77  2024    7   11    14           VA 2024-07-11 14:30:00
2           95.55  2024    7   11    13           VA 2024-07-11 13:30:00
3           86.88  2024    8   12    17           VA 2024-08-12 17:30:00
4           75.58  2024    7   11    15           VA 2024-07-11 15:30:00

  UNIDADE
0   µg/m³
1   µg/m³
2   µg/m³
3   µg/m³
4   µg/m³
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2017-08-22 17:00:00  2017    8   22    17    NaN             NaN   µg/m3
1 2017-08-22 18:00:00  2017    8   22    18    1.1             1.1   µg/m3
2 2017-08-22 19:00:00  2017    8   22    19    1.2             1.2   µg/m3
3 2017-08-22 20:00:00  2017    8   22    20    1.0             1.0   µg/m3
4 2017-08-22 21:00:00  2017    8   22    21    0.8             0.8   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True      True
2          True      True
3          True      True
4          True      True
final
                               DATETIME   ANO  MES  DIA  HORA  VALOR  \
DATETIME
2017-08-22 17:00:00 2017-08-22 17:00:00  2017    8   22    17    NaN
2017-08-22 18:00:00 2017-08-22 18:00:00  2017    8   22    18    1.1
2017-08-22 19:00:00 2017-08-22 19:00:00  2017    8   22    19    1.2
2017-08-22 20:00:00 2017-08-22 20:00:00  2017    8   22    20    1.0
2017-08-22 21:00:00 2017-08-22 21:00:00  2017    8   22    21    0.8

                     VALOR_ORIGINAL UNIDADE  QAQC_INTERNO  QAQC_MMA
DATETIME
2017-08-22 17:00:00             NaN   µg/m3          True     False
2017-08-22 18:00:00             1.1   µg/m3          True      True
2017-08-22 19:00:00             1.2   µg/m3          True      True
2017-08-22 20:00:00             1.0   µg/m3          True      True
2017-08-22 21:00:00             0.8   µg/m3          True      True

/tmp/ipykernel_273420/3647521321.py:47: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  df_consolidado = df.groupby(df.columns, axis=1).first()

EstaçãoVoltadaCapela.csv
PTS
Index(['DATA', 'HORA', 'MP10', 'MP25', 'PTS', 'QAQC_MP10', 'QAQC_MP25',
       'QAQC_PTS'],
      dtype='object')
EstaçãoVoltadaCapela
MG0047

/tmp/ipykernel_273420/3647521321.py:78: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_monitorar['DATA_HORA_STRING'] = df_monitorar['DATA'] + ' ' + df_monitorar['HORA']
/tmp/ipykernel_273420/3647521321.py:80: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_monitorar['DATETIME'] = pd.to_datetime(
/tmp/ipykernel_273420/3647521321.py:173: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(

iema
   VALOR_ORIGINAL   ANO  MES  DIA  HORA QAQC_INTERNO            DATETIME  \
0          1985.0  2024   11   18     8           IV 2024-11-18 08:30:00
1          1985.0  2023    5    3    14           IV 2023-05-03 14:30:00
2          1985.0  2023    5   25    13           IV 2023-05-25 13:30:00
3          1985.0  2022    2    7    17           IV 2022-02-07 17:30:00
4          1985.0  2022    2    7    18           IV 2022-02-07 18:30:00

  UNIDADE
0   µg/m³
1   µg/m³
2   µg/m³
3   µg/m³
4   µg/m³
mma
             DATETIME     ANO  MES   DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2015-05-24 11:00:00  2015.0  5.0  24.0  11.0    NaN             NaN   µg/m3
1 2015-05-24 12:00:00  2015.0  5.0  24.0  12.0    NaN             NaN   µg/m3
2 2015-05-24 13:00:00  2015.0  5.0  24.0  13.0    NaN             NaN   µg/m3
3 2015-05-24 14:00:00  2015.0  5.0  24.0  14.0    NaN             NaN   µg/m3
4 2015-05-24 15:00:00  2015.0  5.0  24.0  15.0    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
                               DATETIME   ANO  MES  DIA  HORA  VALOR  \
DATETIME
2015-05-24 11:00:00 2015-05-24 11:00:00  2015    5   24    11    NaN
2015-05-24 12:00:00 2015-05-24 12:00:00  2015    5   24    12    NaN
2015-05-24 13:00:00 2015-05-24 13:00:00  2015    5   24    13    NaN
2015-05-24 14:00:00 2015-05-24 14:00:00  2015    5   24    14    NaN
2015-05-24 15:00:00 2015-05-24 15:00:00  2015    5   24    15    NaN

                     VALOR_ORIGINAL UNIDADE  QAQC_INTERNO  QAQC_MMA
DATETIME
2015-05-24 11:00:00             NaN   µg/m3          True     False
2015-05-24 12:00:00             NaN   µg/m3          True     False
2015-05-24 13:00:00             NaN   µg/m3          True     False
2015-05-24 14:00:00             NaN   µg/m3          True     False
2015-05-24 15:00:00             NaN   µg/m3          True     False
MP10
Index(['DATA', 'HORA', 'MP10', 'MP25', 'PTS', 'QAQC_MP10', 'QAQC_MP25',
       'QAQC_PTS'],
      dtype='object')
EstaçãoVoltadaCapela
MG0047

/tmp/ipykernel_273420/3647521321.py:78: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_monitorar['DATA_HORA_STRING'] = df_monitorar['DATA'] + ' ' + df_monitorar['HORA']
/tmp/ipykernel_273420/3647521321.py:80: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_monitorar['DATETIME'] = pd.to_datetime(
/tmp/ipykernel_273420/3647521321.py:173: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(

iema
   VALOR_ORIGINAL   ANO  MES  DIA  HORA QAQC_INTERNO            DATETIME  \
0          1985.0  2024   12   28    22           IV 2024-12-28 22:30:00
1          1985.0  2022    2    5     6           IM 2022-02-05 06:30:00
2          1985.0  2022    2    7     8           IM 2022-02-07 08:30:00
3          1985.0  2022    2    5     7           IM 2022-02-05 07:30:00
4          1985.0  2022    2    3     3           IM 2022-02-03 03:30:00

  UNIDADE
0   µg/m³
1   µg/m³
2   µg/m³
3   µg/m³
4   µg/m³
mma
             DATETIME     ANO  MES   DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2015-05-24 11:00:00  2015.0  5.0  24.0  11.0    NaN             NaN   µg/m3
1 2015-05-24 12:00:00  2015.0  5.0  24.0  12.0    NaN             NaN   µg/m3
2 2015-05-24 13:00:00  2015.0  5.0  24.0  13.0    NaN             NaN   µg/m3
3 2015-05-24 14:00:00  2015.0  5.0  24.0  14.0    NaN             NaN   µg/m3
4 2015-05-24 15:00:00  2015.0  5.0  24.0  15.0    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
                               DATETIME   ANO  MES  DIA  HORA  VALOR  \
DATETIME
2015-05-24 11:00:00 2015-05-24 11:00:00  2015    5   24    11    NaN
2015-05-24 12:00:00 2015-05-24 12:00:00  2015    5   24    12    NaN
2015-05-24 13:00:00 2015-05-24 13:00:00  2015    5   24    13    NaN
2015-05-24 14:00:00 2015-05-24 14:00:00  2015    5   24    14    NaN
2015-05-24 15:00:00 2015-05-24 15:00:00  2015    5   24    15    NaN

                     VALOR_ORIGINAL UNIDADE  QAQC_INTERNO  QAQC_MMA
DATETIME
2015-05-24 11:00:00             NaN   µg/m3          True     False
2015-05-24 12:00:00             NaN   µg/m3          True     False
2015-05-24 13:00:00             NaN   µg/m3          True     False
2015-05-24 14:00:00             NaN   µg/m3          True     False
2015-05-24 15:00:00             NaN   µg/m3          True     False
MP25
Index(['DATA', 'HORA', 'MP10', 'MP25', 'PTS', 'QAQC_MP10', 'QAQC_MP25',
       'QAQC_PTS'],
      dtype='object')
EstaçãoVoltadaCapela
MG0047

/tmp/ipykernel_273420/3647521321.py:78: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_monitorar['DATA_HORA_STRING'] = df_monitorar['DATA'] + ' ' + df_monitorar['HORA']
/tmp/ipykernel_273420/3647521321.py:80: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_monitorar['DATETIME'] = pd.to_datetime(
/tmp/ipykernel_273420/3647521321.py:173: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(

iema
   VALOR_ORIGINAL   ANO  MES  DIA  HORA QAQC_INTERNO            DATETIME  \
0           985.0  2023    6   13    18           IM 2023-06-13 18:30:00
1           985.0  2023    5   25    13           IV 2023-05-25 13:30:00
2           985.0  2022    4    6    16           IM 2022-04-06 16:30:00
3           985.0  2022    4    6    10           IM 2022-04-06 10:30:00
4           985.0  2024   12   28    22           IV 2024-12-28 22:30:00

  UNIDADE
0   µg/m³
1   µg/m³
2   µg/m³
3   µg/m³
4   µg/m³
mma
             DATETIME   ANO  MES  DIA  HORA  VALOR  VALOR_ORIGINAL UNIDADE  \
0 2020-01-01 01:00:00  2020    1    1     1    NaN             NaN   µg/m3
1 2020-01-01 02:00:00  2020    1    1     2    NaN             NaN   µg/m3
2 2020-01-01 03:00:00  2020    1    1     3    NaN             NaN   µg/m3
3 2020-01-01 04:00:00  2020    1    1     4    NaN             NaN   µg/m3
4 2020-01-01 05:00:00  2020    1    1     5    NaN             NaN   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
                               DATETIME   ANO  MES  DIA  HORA  VALOR  \
DATETIME
2020-01-01 01:00:00 2020-01-01 01:00:00  2020    1    1     1    NaN
2020-01-01 02:00:00 2020-01-01 02:00:00  2020    1    1     2    NaN
2020-01-01 03:00:00 2020-01-01 03:00:00  2020    1    1     3    NaN
2020-01-01 04:00:00 2020-01-01 04:00:00  2020    1    1     4    NaN
2020-01-01 05:00:00 2020-01-01 05:00:00  2020    1    1     5    NaN

                     VALOR_ORIGINAL UNIDADE  QAQC_INTERNO  QAQC_MMA
DATETIME
2020-01-01 01:00:00             NaN   µg/m3          True     False
2020-01-01 02:00:00             NaN   µg/m3          True     False
2020-01-01 03:00:00             NaN   µg/m3          True     False
2020-01-01 04:00:00             NaN   µg/m3          True     False
2020-01-01 05:00:00             NaN   µg/m3          True     False

/tmp/ipykernel_273420/3647521321.py:47: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  df_consolidado = df.groupby(df.columns, axis=1).first()

EstaçãoCentroAv.doContorno.csv
CO
Index(['CO', 'DATA', 'HORA', 'MP10', 'MP25', 'QAQC_CO', 'QAQC_MP10',
       'QAQC_MP25'],
      dtype='object')
EstaçãoCentroAv.doContorno
MG0003

/tmp/ipykernel_273420/3647521321.py:78: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_monitorar['DATA_HORA_STRING'] = df_monitorar['DATA'] + ' ' + df_monitorar['HORA']
/tmp/ipykernel_273420/3647521321.py:80: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_monitorar['DATETIME'] = pd.to_datetime(
/tmp/ipykernel_273420/3647521321.py:144: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  df_mma = pd.read_csv(arquivo, encoding = 'UTF-8')
/tmp/ipykernel_273420/3647521321.py:173: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(

iema
   VALOR_ORIGINAL   ANO  MES  DIA  HORA QAQC_INTERNO            DATETIME  \
0          13.268  2024    8   22    13           VA 2024-08-22 13:00:00
1           8.534  2024    6   24    16           VA 2024-06-24 16:00:00
2           7.699  2023    3   31    14           VA 2023-03-31 14:00:00
3           5.400  2024    7   18    14           VA 2024-07-18 14:00:00
4           5.207  2023    1   26    13           VA 2023-01-26 13:00:00

  UNIDADE
0     ppm
1     ppm
2     ppm
3     ppm
4     ppm
mma
             DATETIME     ANO  MES  DIA  HORA  VALOR VALOR_ORIGINAL UNIDADE  \
0 2009-01-01 01:00:00  2009.0  1.0  1.0   1.0    0.3            0.3     ppm
1 2009-01-01 02:00:00  2009.0  1.0  1.0   2.0    0.2            0.2     ppm
2 2009-01-01 03:00:00  2009.0  1.0  1.0   3.0    0.2            0.2     ppm
3 2009-01-01 04:00:00  2009.0  1.0  1.0   4.0    0.2            0.2     ppm
4 2009-01-01 05:00:00  2009.0  1.0  1.0   5.0    0.2            0.2     ppm

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
final
                               DATETIME   ANO  MES  DIA  HORA  VALOR  \
DATETIME
2009-01-01 01:00:00 2009-01-01 01:00:00  2009    1    1     1    0.3
2009-01-01 02:00:00 2009-01-01 02:00:00  2009    1    1     2    0.2
2009-01-01 03:00:00 2009-01-01 03:00:00  2009    1    1     3    0.2
2009-01-01 04:00:00 2009-01-01 04:00:00  2009    1    1     4    0.2
2009-01-01 05:00:00 2009-01-01 05:00:00  2009    1    1     5    0.2

                    VALOR_ORIGINAL UNIDADE  QAQC_INTERNO  QAQC_MMA
DATETIME
2009-01-01 01:00:00            0.3     ppm          True      True
2009-01-01 02:00:00            0.2     ppm          True      True
2009-01-01 03:00:00            0.2     ppm          True      True
2009-01-01 04:00:00            0.2     ppm          True      True
2009-01-01 05:00:00            0.2     ppm          True      True
MP10
Index(['CO', 'DATA', 'HORA', 'MP10', 'MP25', 'QAQC_CO', 'QAQC_MP10',
       'QAQC_MP25'],
      dtype='object')
EstaçãoCentroAv.doContorno
MG0003

/tmp/ipykernel_273420/3647521321.py:78: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_monitorar['DATA_HORA_STRING'] = df_monitorar['DATA'] + ' ' + df_monitorar['HORA']
/tmp/ipykernel_273420/3647521321.py:80: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_monitorar['DATETIME'] = pd.to_datetime(
/tmp/ipykernel_273420/3647521321.py:144: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  df_mma = pd.read_csv(arquivo, encoding = 'UTF-8')
/tmp/ipykernel_273420/3647521321.py:173: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(

iema
   VALOR_ORIGINAL   ANO  MES  DIA  HORA QAQC_INTERNO            DATETIME  \
0          9999.9  2022    5   12    14           IV 2022-05-12 14:00:00
1          9999.9  2022    5   12     6           IV 2022-05-12 06:00:00
2          9999.9  2022    5   12    13           IV 2022-05-12 13:00:00
3          9999.9  2022    5   19    11           IV 2022-05-19 11:00:00
4          9999.9  2022    5   12     9           IV 2022-05-12 09:00:00

  UNIDADE
0   µg/m³
1   µg/m³
2   µg/m³
3   µg/m³
4   µg/m³
mma
             DATETIME     ANO  MES  DIA  HORA  VALOR VALOR_ORIGINAL UNIDADE  \
0 2009-01-01 01:00:00  2009.0  1.0  1.0   1.0   11.5           11.5   µg/m3
1 2009-01-01 02:00:00  2009.0  1.0  1.0   2.0   52.2           52.2   µg/m3
2 2009-01-01 03:00:00  2009.0  1.0  1.0   3.0   18.0             18   µg/m3
3 2009-01-01 04:00:00  2009.0  1.0  1.0   4.0    NaN              0   µg/m3
4 2009-01-01 05:00:00  2009.0  1.0  1.0   5.0    NaN              0   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True      True
1          True      True
2          True      True
3          True     False
4          True     False
final
                               DATETIME   ANO  MES  DIA  HORA  VALOR  \
DATETIME
2009-01-01 01:00:00 2009-01-01 01:00:00  2009    1    1     1   11.5
2009-01-01 02:00:00 2009-01-01 02:00:00  2009    1    1     2   52.2
2009-01-01 03:00:00 2009-01-01 03:00:00  2009    1    1     3   18.0
2009-01-01 04:00:00 2009-01-01 04:00:00  2009    1    1     4    NaN
2009-01-01 05:00:00 2009-01-01 05:00:00  2009    1    1     5    NaN

                    VALOR_ORIGINAL UNIDADE  QAQC_INTERNO  QAQC_MMA
DATETIME
2009-01-01 01:00:00           11.5   µg/m3          True      True
2009-01-01 02:00:00           52.2   µg/m3          True      True
2009-01-01 03:00:00             18   µg/m3          True      True
2009-01-01 04:00:00              0   µg/m3          True     False
2009-01-01 05:00:00              0   µg/m3          True     False
MP25
Index(['CO', 'DATA', 'HORA', 'MP10', 'MP25', 'QAQC_CO', 'QAQC_MP10',
       'QAQC_MP25'],
      dtype='object')
EstaçãoCentroAv.doContorno
MG0003

/tmp/ipykernel_273420/3647521321.py:78: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_monitorar['DATA_HORA_STRING'] = df_monitorar['DATA'] + ' ' + df_monitorar['HORA']
/tmp/ipykernel_273420/3647521321.py:80: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_monitorar['DATETIME'] = pd.to_datetime(
/tmp/ipykernel_273420/3647521321.py:144: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  df_mma = pd.read_csv(arquivo, encoding = 'UTF-8')
/tmp/ipykernel_273420/3647521321.py:173: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(

iema
   VALOR_ORIGINAL   ANO  MES  DIA  HORA QAQC_INTERNO            DATETIME  \
0           985.0  2023    1   11    21           IM 2023-01-11 21:00:00
1           985.0  2024   12   12     8           IM 2024-12-12 08:00:00
2           985.0  2022    4   12    15           IM 2022-04-12 15:00:00
3           985.0  2022    4   12    14           IM 2022-04-12 14:00:00
4           985.0  2022    4   12    13           IM 2022-04-12 13:00:00

  UNIDADE
0   µg/m³
1   µg/m³
2   µg/m³
3   µg/m³
4   µg/m³
mma
             DATETIME     ANO  MES  DIA  HORA  VALOR VALOR_ORIGINAL UNIDADE  \
0 2009-01-01 01:00:00  2009.0  1.0  1.0   1.0    NaN              *   µg/m3
1 2009-01-01 02:00:00  2009.0  1.0  1.0   2.0    NaN              *   µg/m3
2 2009-01-01 03:00:00  2009.0  1.0  1.0   3.0    NaN              *   µg/m3
3 2009-01-01 04:00:00  2009.0  1.0  1.0   4.0    NaN              *   µg/m3
4 2009-01-01 05:00:00  2009.0  1.0  1.0   5.0    NaN              *   µg/m3

   QAQC_INTERNO  QAQC_MMA
0          True     False
1          True     False
2          True     False
3          True     False
4          True     False
final
                               DATETIME   ANO  MES  DIA  HORA  VALOR  \
DATETIME
2009-01-01 01:00:00 2009-01-01 01:00:00  2009    1    1     1    NaN
2009-01-01 02:00:00 2009-01-01 02:00:00  2009    1    1     2    NaN
2009-01-01 03:00:00 2009-01-01 03:00:00  2009    1    1     3    NaN
2009-01-01 04:00:00 2009-01-01 04:00:00  2009    1    1     4    NaN
2009-01-01 05:00:00 2009-01-01 05:00:00  2009    1    1     5    NaN

                    VALOR_ORIGINAL UNIDADE  QAQC_INTERNO  QAQC_MMA
DATETIME
2009-01-01 01:00:00              *   µg/m3          True     False
2009-01-01 02:00:00              *   µg/m3          True     False
2009-01-01 03:00:00              *   µg/m3          True     False
2009-01-01 04:00:00              *   µg/m3          True     False
2009-01-01 05:00:00              *   µg/m3          True     False

/tmp/ipykernel_273420/3647521321.py:47: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  df_consolidado = df.groupby(df.columns, axis=1).first()

In [210]:
lista_validacao

['VA', None, 'IM', 'VU', 'ID', 'IF', 'VE', 'IC', 'IN', 'VR', 'IV', 'IO']

In [199]:
df_monitorar.columns

Index(['NO2', 'ANO', 'MES', 'DIA', 'HORA', 'DATETIME', 'UNIDADE'], dtype='object')

In [97]:
df_consolidado

linhas_encontradas = df_consolidado[df_consolidado[col] == '2.645,499']

linhas_encontradas

,DATA,HORA,MP10,MP25,PTS,QAQC_MP10,QAQC_MP25,QAQC_PTS
2677,23/04/2022,17:30,"2.645,499","2.257,856","2.575,189",IM,IV,IV

# Representatividade Temporal

In [1]:
import pandas as pd
import os
import numpy as np

os.chdir('/home/nobre/Notebooks/RQAR_2025_book/')

df_rep_temporal = pd.DataFrame({
    'POLUENTES': ['MP10','MP25','SO2','NO2','O3','FMC','CO','PTS','Pb'],
    'DIA': ['24','24','24','1','8','24','8','1',''],
    'MES': ['mensal','mensal','mensal','mensal','mensal','mensal','mensal','mensal_geom','mensal'],
    'ANO': ['anual','anual','anual','anual','anual','anual','anual','anual_geom','anual']
}).set_index("POLUENTES")

print(df_rep_temporal)

          DIA          MES         ANO
POLUENTES
MP10       24       mensal       anual
MP25       24       mensal       anual
SO2        24       mensal       anual
NO2         1       mensal       anual
O3          8       mensal       anual
FMC        24       mensal       anual
CO          8       mensal       anual
PTS         1  mensal_geom  anual_geom
Pb                  mensal       anual

In [3]:
for ano, dados in df_dia.groupby(['ANO']):
    print(ano)
    qntd_valor = dados['VALOR'].notna().sum()
    if (ano[0] % 4 == 0 and ano[0] % 100 != 0) or (ano[0] % 400 == 0):
        dias = 366
    else:
        dias = 365
    prcnt_rep = (100*qntd_valor/dias)
    print(prcnt_rep)

(2009,)
69.04109589041096
(2010,)
98.63013698630137
(2011,)
80.82191780821918
(2012,)
94.80874316939891
(2013,)
96.16438356164383
(2014,)
99.17808219178082
(2015,)
98.9041095890411
(2016,)
88.79781420765028
(2017,)
99.72602739726027
(2018,)
97.26027397260275
(2019,)
91.5068493150685
(2020,)
99.72677595628416
(2021,)
98.9041095890411
(2022,)
99.72602739726027
(2023,)
100.0
(2024,)
97.81420765027322
(2025,)
67.12328767123287

In [2]:
def rep_temp(df,agrupamento,criterio,periodo_ref):

    resultados = []
    
    for chave, dados in df.groupby(agrupamento):
        qntd_valor = dados['VALOR'].notna().sum()  

        if criterio == 'HORA':
            qntd_tempo = 24
        elif criterio == 'DIA':
            if chave[1] in [4,6,9,11]:
                qntd_tempo = 30
            elif chave[1] in [1,3,5,7,8,10,12]:
                qntd_tempo = 31
            else:
                if (chave[0] % 4 == 0 and chave[0] % 100 != 0) or (chave[0] % 400 == 0):
                    qntd_tempo = 29
                else:
                    qntd_tempo = 28
        
        if qntd_valor >= (2/3) * qntd_tempo:
            if periodo_ref == "8horas":
                media = dados["VALOR"].rolling(window=8, min_periods=1).mean().max()
            else:
                media = periodo_ref(dados["VALOR"])
            rep = True
        else:
            media = np.nan   
            rep = False

        prcnt = 100*qntd_valor/qntd_tempo

        resultados.append((*chave, media, rep, prcnt))

    return resultados

def conta_dias_quadrimestre(ano,quadrimestre):

    if quadrimestre == 1:
        if (ano % 4 == 0 and ano % 100 != 0) or (ano % 400 == 0):
            dias = 121
        else:
            dias = 120
    elif quadrimestre == 2:
        dias = 123
    else:
        dias = 122

    return dias

def rep_temp_ano(df,agrupamento,criterio):

    resultados = []
    
    for chave, dados in df.groupby(agrupamento):
        qntd_valor = dados['VALOR'].notna().sum()
        qntd_tempo = conta_dias_quadrimestre(chave[0],chave[1])         
        
        if qntd_valor >= (1/2) * qntd_tempo:
            rep = True
        else:
            rep = False
    
        resultados.append((*chave, rep))

    return resultados
    
df_estacoes_rep_temporal = pd.DataFrame({
                    'ID_MMA_COMPLETO':[],
                    'PRCNT_REP_DIA':[],
                    'PRCNT_REP_MES':[],
                    'PRCNT_REP_ANO':[]
                })
                
for pol in df_rep_temporal.index:
    
    path = os.getcwd()+'/data/MQAr/' + pol + '/'

    print(pol)
    
    if os.path.isdir(path) and os.listdir(path):
        
        arquivos = os.listdir(path)
    
        for estacao in arquivos:

            if estacao.endswith('.csv'):

                print(estacao)

                df = pd.read_csv(path+estacao)

                df["VALOR"] = pd.to_numeric(df["VALOR"], errors="coerce")

                resultados_24 = rep_temp(df,['ANO','MES','DIA'],'HORA',np.mean)

                df_24 = pd.DataFrame(resultados_24, columns=['ANO', 'MES', 'DIA', 'VALOR', 'REP_DIA','PRCNT_REP'])

                df_24['DATETIME'] = pd.to_datetime(
                        dict(year=df_24["ANO"], month=df_24["MES"], day=df_24["DIA"])
                    )
            
                df_24 = df_24[['DATETIME','ANO','MES','DIA','VALOR','REP_DIA','PRCNT_REP']]

                if df_rep_temporal['DIA'][pol] == 'dia':
                    df_dia = df_24
                elif df_rep_temporal['DIA'][pol] == '8horas':
                    resultados_dia = rep_temp(df,['ANO','MES','DIA'],'HORA','8horas')

                    df_dia = pd.DataFrame(resultados_dia, columns=['ANO', 'MES', 'DIA', 'VALOR', 'REP_DIA','PRCNT_REP'])

                    df_dia['DATETIME'] = pd.to_datetime(dict(year=df_dia["ANO"], month=df_dia["MES"], day=df_dia["DIA"]))

                    df_dia = df_dia[['DATETIME','ANO','MES','DIA','VALOR','REP_DIA','PRCNT_REP']]
                        
                else:
                    resultados_dia = rep_temp(df,['ANO','MES','DIA'],'HORA',np.max)

                    df_dia = pd.DataFrame(resultados_dia, columns=['ANO', 'MES', 'DIA', 'VALOR', 'REP_DIA','PRCNT_REP'])

                    df_dia['DATETIME'] = pd.to_datetime(dict(year=df_dia["ANO"], month=df_dia["MES"], day=df_dia["DIA"]))

                    df_dia = df_dia[['DATETIME','ANO','MES','DIA','VALOR','REP_DIA','PRCNT_REP']]

                df_dia.to_csv(os.getcwd()+'/data/MQAr_averages/'+df_rep_temporal['DIA'][pol]+'/'+pol+'/'+estacao,index=False)

                resultados_mes = rep_temp(df_24,['ANO','MES'],'DIA',np.mean)

                df_mes = pd.DataFrame(resultados_mes, columns=['ANO', 'MES', 'VALOR', 'REP_MES','PRCNT_REP'])

                df_mes['DATETIME'] = pd.to_datetime(dict(year=df_mes["ANO"], month=df_mes["MES"], day=1))
            
                df_mes = df_mes[['DATETIME','ANO','MES','VALOR','REP_MES','PRCNT_REP']]

                df_mes.to_csv(os.getcwd()+'/data/MQAr_averages/'+df_rep_temporal['MES'][pol][:6]+'/'+pol+'/'+estacao,index=False)

                condicoes = [
                    (df_dia['MES'] <= 4),
                    (df_dia['MES'] >= 5) & (df_dia['MES'] <= 8),
                    (df_dia['MES'] >= 9)
                ]
                
                quadrimestre = [1, 2, 3]
                
                df_dia['QUADRIMESTRE'] = np.select(condicoes, quadrimestre)

                resultados_quad = rep_temp_ano(df_dia,['ANO','QUADRIMESTRE'],'QUADRIMESTRE')

                df_quad = pd.DataFrame(resultados_quad, columns=['ANO', 'QUADRIMESTRE', 'REP_QUAD'])
                
                df_ano_quad = df_quad.groupby("ANO", as_index=False).agg({"REP_QUAD": lambda x: x.sum() == 3})

                resultados = []
                
                for ano, dados in df_dia.groupby(['ANO']):
                    qntd_valor = dados['VALOR'].notna().sum()
                    if (ano[0] % 4 == 0 and ano[0] % 100 != 0) or (ano[0] % 400 == 0):
                        dias = 366
                    else:
                        dias = 365
                    prcnt_rep = (100*qntd_valor/dias)
                    if df_ano_quad.loc[df_ano_quad["ANO"] == ano[0], "REP_QUAD"].values[0] == True:
                        media = dados['VALOR'].mean()
                        rep = True
                    else:
                        media = np.nan
                        rep = False
                    resultados.append((*ano, media, rep, prcnt_rep))
                
                df_ano = pd.DataFrame(resultados, columns=['ANO', 'VALOR','REP_ANO','PRCNT_REP'])
                
                df_ano['DATETIME'] = pd.to_datetime(dict(year=df_ano["ANO"], month=1, day=1))
            
                df_ano = df_ano[['DATETIME','ANO','VALOR','REP_ANO','PRCNT_REP']]

                df_ano.to_csv(os.getcwd()+'/data/MQAr_averages/'+df_rep_temporal['ANO'][pol][:5]+'/'+pol+'/'+estacao, index=False)

                prcnt_dia = 100 * df_dia['VALOR'].notna().sum() / len(df_dia)
                prcnt_mes = 100 * df_mes['VALOR'].notna().sum() / len(df_mes)
                prcnt_ano = 100 * df_ano['VALOR'].notna().sum() / len(df_ano)

                prcnt_estacao = {'ID_MMA_COMPLETO': estacao[:-4], 'PRCNT_REP_DIA': prcnt_dia, 'PRCNT_REP_MES': prcnt_mes, 'PRCNT_REP_ANO': prcnt_ano}

                df_estacoes_rep_temporal = pd.concat([df_estacoes_rep_temporal, pd.DataFrame([prcnt_estacao])], ignore_index=True)

df_estacoes_rep_temporal.to_csv(os.getcwd()+'/data/MQAr_averages/REP_TEMPORAL.csv', index=False)

MP10
SP0248RA001.csv
RJ0031RA001.csv

KeyboardInterrupt:

In [70]:
df_estacoes_rep_temporal

  ID_MMA_COMPLETO  PRCNT_REP_DIA  PRCNT_REP_MES  PRCNT_REP_ANO
0     SP0248RA001      96.243112      95.959596      88.235294
1     RJ0031RA001      88.713704      90.800000      80.952381
2     RJ0282RA001      84.054054      76.923077       0.000000

In [71]:
estacao

'SP0085RA001.csv'

In [74]:
condicoes = [
    (df_dia['MES'] <= 4),
    (df_dia['MES'] >= 5) & (df_dia['MES'] <= 8),
    (df_dia['MES'] >= 9)
]

quadrimestre = [1, 2, 3]

df_dia['QUADRIMESTRE'] = np.select(condicoes, quadrimestre)

resultados_quad = rep_temp_ano(df_dia,['ANO','QUADRIMESTRE'],'QUADRIMESTRE')

df_quad = pd.DataFrame(resultados_quad, columns=['ANO', 'QUADRIMESTRE', 'REP_QUAD'])

df_ano_quad = df_quad.groupby("ANO", as_index=False).agg({"REP_QUAD": lambda x: x.sum() == 3})

In [83]:
df_ano

        ANO      VALOR  REP_ANO
0   (2009,)        NaN    False
1   (2010,)  76.227778     True
2   (2011,)  75.494915     True
3   (2012,)  77.752161     True
4   (2013,)  69.000000     True
5   (2014,)  89.419890     True
6   (2015,)  67.670360     True
7   (2016,)  73.575385     True
8   (2017,)  72.285714     True
9   (2018,)  67.177465     True
10  (2019,)  61.461078     True
11  (2020,)  70.846575     True
12  (2021,)  74.279778     True
13  (2022,)  64.519231     True
14  (2023,)  71.071233     True
15  (2024,)  92.608939     True
16  (2025,)        NaN    False

In [41]:
df_pivot = df_mes.pivot(index='ANO', columns='MES', values='PRCNT_REP')

df_pivot = df_pivot.reindex(sorted(df_pivot.columns), axis=1)

df_pivot = df_pivot.reset_index()

df_pivot

MES,ANO,1,2,3,4,5,6,7,8,9,10,11,12
0,2009,NaN,NaN,NaN,53.333333,100.000000,100.000000,100.000000,87.096774,86.666667,100.000000,96.666667,100.000000
1,2010,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,96.666667,87.096774,100.000000,100.000000
2,2011,100.000000,100.000000,100.000000,100.000000,80.645161,0.000000,41.935484,100.000000,100.000000,96.774194,83.333333,67.741935
3,2012,58.064516,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,80.645161
4,2013,96.774194,96.428571,80.645161,100.000000,100.000000,93.333333,93.548387,100.000000,100.000000,93.548387,100.000000,100.000000
5,2014,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,90.322581,100.000000,100.000000,100.000000,100.000000
6,2015,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,90.000000,96.774194
7,2016,77.419355,100.000000,100.000000,100.000000,100.000000,86.666667,54.838710,100.000000,100.000000,100.000000,93.333333,54.838710
8,2017,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,96.774194,100.000000,100.000000
9,2018,100.000000,100.000000,100.000000,66.666667,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000
10,2019,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,93.548387,20.000000,100.000000,83.333333,100.000000
11,2020,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,96.774194,100.000000,100.000000,100.000000,100.000000
12,2021,96.774194,100.000000,100.000000,100.000000,100.000000,100.000000,96.774194,100.000000,96.666667,100.000000,96.666667,100.000000
13,2022,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,96.774194
14,2023,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000
15,2024,93.548387,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,87.096774,100.000000,100.000000,93.333333,100.000000
16,2025,100.000000,100.000000,100.000000,100.000000,93.548387,96.666667,100.000000,100.000000,16.666667,NaN,NaN,NaN

In [9]:
df = pd.read_csv(os.getcwd()+'/data/MQAr/MP10/ES0001RA001.csv')

def create_QAQCMMA_VALOR(df,pol):

    df = df.rename(columns={'VALOR':'VALOR_ORIGINAL'})

    flags_invalidos = ['!', 'IF', 'IO', 'IC', 'I%', 'IL', 'IE', 'IS', 'IU', 'IM', 'IP', 'ID', 'IT', 'IR', 
                       'Fora da Faixa de Medição', 'Disabilitada Temporariamente', 'Inválido', 
                       'Insuficientes', 'Inexistente']

    df['QAQC_INTERNO'] = ~df['QAQC_INTERNO'].isin(flags_invalidos)
    
    DEFAULT_RANGE_LIMITS = {
        "O3": (0, 500),
        "CO": (0, 50),
        "NO2": (0, 1000),
        "NOX": (0, 2000),
        "SO2": (0, 1000),
        "MP25": (0, 1000),
        "MP10": (0, 2000),
    }

    df['QAQC_MMA'] = df['QAQC_INTERNO']

    if pol in list(DEFAULT_RANGE_LIMITS.keys()):
        lim_min = DEFAULT_RANGE_LIMITS[pol][0]
        lim_max = DEFAULT_RANGE_LIMITS[pol][1]
    else:
        lim_min = 0
        lim_max = np.inf

    df['VALOR'] = df['VALOR_ORIGINAL']

    df['VALOR'] = pd.to_numeric(df['VALOR'], errors='coerce')
    
    df.loc[df['QAQC_MMA'] & (df['VALOR'].isna() | (df['VALOR'] < lim_min) | (df['VALOR'] > lim_max)), 'QAQC_MMA'] = False
    
    df.loc[~df['QAQC_MMA'], 'VALOR'] = np.nan
    
    df = df[['DATETIME', 'ANO', 'MES', 'DIA', 'HORA', 'VALOR', 'VALOR_ORIGINAL', 'UNIDADE', 'QAQC_INTERNO', 'QAQC_MMA']]

    return df

In [15]:
DEFAULT_RANGE_LIMITS = {
        "O3": (0, 500),
        "CO": (0, 50),
        "NO2": (0, 1000),
        "NOX": (0, 2000),
        "SO2": (0, 1000),
        "MP25": (0, 1000),
        "MP10": (0, 2000),
    }

DEFAULT_RANGE_LIMITS['MP10'][1]

2000

In [17]:
list(DEFAULT_RANGE_LIMITS.keys())

['O3', 'CO', 'NO2', 'NOX', 'SO2', 'MP25', 'MP10']

In [29]:
pol = 'CCCC'

df['QAQC_MMA'] = df['QAQC_INTERNO']

if pol in list(DEFAULT_RANGE_LIMITS.keys()):
    lim_min = DEFAULT_RANGE_LIMITS[pol][0]
    lim_max = DEFAULT_RANGE_LIMITS[pol][1]
else:
    lim_min = 0
    lim_max = np.inf

In [30]:
df['VALOR'] = df['VALOR_ORIGINAL']

df['VALOR'] = pd.to_numeric(df['VALOR'], errors='coerce')

df.loc[df['QAQC_MMA'] & (df['VALOR'].isna() | (df['VALOR'] < lim_min) | (df['VALOR'] > lim_max)), 'QAQC_MMA'] = False

df.loc[~df['QAQC_MMA'], 'VALOR'] = np.nan

df = df[['DATETIME', 'ANO', 'MES', 'DIA', 'HORA', 'VALOR', 'VALOR_ORIGINAL', 'UNIDADE', 'QAQC_INTERNO', 'QAQC_MMA']]

In [32]:
df.columns

Index(['DATETIME', 'ANO', 'MES', 'DIA', 'HORA', 'VALOR_ORIGINAL', 'UNIDADE',
       'QAQC_INTERNO', 'QAQC_MMA', 'VALOR'],
      dtype='object')

In [36]:
import pandas as pd
import os
from collections import defaultdict
from datetime import datetime, timedelta
import re
import numpy as np
from pathlib import Path

def ppb_to_ug(df,pol):

    if pol == 'so2':

        df.loc[df["Unidade"] != "ug/m3", "Valor"] *= 2661260.49/10**6        

    elif pol == 'no2':

        df.loc[df["Unidade"] != "ug/m3", "Valor"] *= 1911038.92/10**6        

    elif pol == 'o3':

        df.loc[df["Unidade"] != "ug/m3", "Valor"] *= 1993889.17/10**6        
    
    df.loc[:, "Unidade"] = "ug/m3"

    return df

def rectify_MT(path):

    dict_pols_stat = defaultdict(list)

    files = os.listdir(path)
    
    print(files)
    
    for item in files:
        
        estacao = " ".join(item.split('-')[1].split('.')[0].split('_')[0:2])
    
        print(estacao)
    
        df = pd.read_excel(path+item)
    
        df = df.drop(columns=['Nome da estação'])
    
        lista_pols = set(df['Poluente'])
    
        for pol in lista_pols:
    
            df_pol = df[df["Poluente"] == pol]
            
            if pol in ['no2','so2','o3']:
    
                df_pol = ppb_to_ug(df_pol,pol)
    
            df_pol_hora = df_pol.groupby(["Ano", "Mes", "Dia", "Hora", "Unidade"])
            
            df_pol_hora = df_pol_hora.filter(lambda g: len(g) >= 9)
            
            df_pol = (
                df_pol_hora.groupby(["Ano", "Mes", "Dia", "Hora", "Unidade"], as_index=False)
                      .agg({"Valor": "mean"})
            )
    
            df_pol['QAQC_INTERNO'] = None
    
            df_pol = df_pol.rename(columns={'Ano':'ANO',
                                            'Mes':'MES',
                                            'Dia':'DIA',
                                            'Hora':'HORA',
                                            'Unidade':'UNIDADE',
                                            'Valor':'VALOR'})
    
            for col in ["ANO", "MES", "DIA", "HORA"]:
                df_pol[col] = pd.to_numeric(df_pol[col], errors="coerce").astype("Int64")
            
            dict_pols_stat[estacao+'_'+pol].append(df_pol)

    dict_pols_MT = {
        'co':'CO',
        'no2': 'NO2',
        'so2': 'SO2',
        'o3': 'O3',
        'pm2p5':'MP25',
        'pm10': 'MP10'
    }

    dict_formatado = {}
    
    for chave in dict_pols_stat.keys():
        
        lista_dfs = dict_pols_stat[chave]
        
        df = pd.concat(lista_dfs, ignore_index=True)
    
        df["DATETIME"] = pd.to_datetime(
            df.apply(lambda r: f"{r.ANO}-{r.MES}-{r.DIA} {r.HORA}:00:00", axis=1)
        )
        df = df.set_index("DATETIME")
    
        df = df.sort_index()
        
        lista_horas = pd.date_range(
            start=df.index.min(), 
            end=df.index.max(), 
            freq='H').strftime('%Y-%m-%d %H:%M:%S').tolist()
        
        if len(lista_horas) != len(df):
            df = df.reindex(pd.DatetimeIndex(lista_horas))
    
        df['DATETIME'] = df.index
    
        df = df[['DATETIME','ANO','MES','DIA','HORA','VALOR','UNIDADE','QAQC_INTERNO']]
        
        dict_formatado[chave] = df
        
        primeiros_valores = {}
    
    for chave, df in dict_formatado.items():
        
        if ~df['VALOR'].isna().all() and (df['VALOR'] > 0).any(): 
            
            linha_valida = df[df["VALOR"].notna() & (df["VALOR"] > 0)].iloc[0]
            primeiros_valores[chave] = linha_valida["DATETIME"]
    
    codigo_estacao_MT = {}
    
    for chave in primeiros_valores.keys():
        
        station = chave.split('_')[0]
        data = primeiros_valores[chave]
        
        if station in codigo_estacao_MT:
            if data <= codigo_estacao_MT[station]:
                codigo_estacao_MT[station] = data
        else:
            codigo_estacao_MT[station] = data
    
    sorted_items = sorted(
        codigo_estacao_MT.items(),
        key=lambda x: (x[1], x[0])
    )
    
    codigo_estacao_MT = {}
    for i, (nome, ts) in enumerate(sorted_items, start=1):
        codigo = f"MT{i:04d}"
        codigo_estacao_MT[nome] = codigo
        
    for chave, df in dict_formatado.items():
        
        estacao = codigo_estacao_MT[chave.split('_')[0]]
        
        cod_pol = tabela_pols.loc[tabela_pols['POLUENTE'] == dict_pols_MT[chave.split('_')[-1]], 'COD_POLUENTE'].values[0]
        
        nome_pasta = tabela_pols.loc[tabela_pols['COD_POLUENTE'] == int(cod_pol), 'NOME_PASTA'].values[0]

        df = create_QAQCMMA_VALOR(df,nome_pasta)
        
        df.to_csv('/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/'+nome_pasta+'/'+estacao+'IA'+str(cod_pol).zfill(3)+'.csv',index=False)

    dict_stations_MT = {
        'Sema':'CPA - SEMA - CBA',
        'BEA CBA': 'Dom Aquino - BEA - CBA',
        'CBM VG': 'Água Limpa - CBM - VG',
        'Mae Bonifacia': 'Duque de Caxias - Pq Mãe Bonifácia - CBA',
        'UFMT':'Boa Esperança - UFMT - CBA'
    }
    
    df_ids = pd.DataFrame({
        'ID_OEMA': codigo_estacao_MT.keys(),
        'ID_MMA':list(codigo_estacao_MT.values())})
    
    df_ids["ID_OEMA"] = df_ids["ID_OEMA"].replace(dict_stations_MT)

    print(df_ids)
    
    return df_ids

funcoes = {
    'MT': rectify_MT
}

#lista_estados = ['SC','RS','MT','DF','MA','BA','ES','MG','SP','RJ']
lista_estados = ['MT']

tabela_ids = pd.read_csv('/home/nobre/Notebooks/RQAR_2025_book/data/Monitoramento_QAr_BR.csv')
tabela_pols = pd.read_csv('/home/nobre/Notebooks/RQAR_2025_book/data/dicionarios/CODIGO_POLUENTES.csv')

for estado in lista_estados:
    
    path = os.getcwd()+'/data/DADOS_BRUTOS/' + estado + '/'

    df_ids = funcoes[estado](path)
    
    create_df_estacao(estado,df_ids)

['dados_monitoramento-Sema.xlsx', 'dados_monitoramento-BEA_CBA_24-25.xlsx', 'dados_monitoramento-BEA_CBA_22-23.xlsx', 'dados_monitoramento-CBM_VG_22-23.xlsx', 'dados_monitoramento-CBM_VG_24-25.xlsx', 'dados_monitoramento-Mae_Bonifacia_22-23.xlsx', 'dados_monitoramento-Mae_Bonifacia_24-25.xlsx', 'dados_monitoramento-UFMT.xlsx']
Sema
BEA CBA

KeyboardInterrupt:

In [38]:
df = df_dia.groupby(['ANO'])

NameError: name 'df_dia' is not defined

In [72]:

tabela_pols = pd.read_csv('/home/nobre/Notebooks/RQAR_2025_book/data/dicionarios/CODIGO_POLUENTES.csv')

In [73]:
for pol in tabela_pols['NOME_PASTA'].unique():
    print(pol)

MP10
MP25
SO2
NO2
O3
FMC
CO
PTS
CHUMBO
BENZENO
CH4
ERT
ETILBENZENO
H2S
NH3
HCNM
NO
NOX
MP1
ACETAL
FORMAL
TOLUENO
XILENO
VOC
OXILENO
HCT
MPXILENO

In [68]:
import pandas as pd
import os
from collections import defaultdict
from datetime import datetime, timedelta
import re
import numpy as np
from pathlib import Path

os.chdir('/home/nobre/Notebooks/RQAR_2025_book/')

In [18]:
funcoes = {
    
    'MT': rectify_MT,
}

lista_estados = ['MT']

tabela_ids = pd.read_csv('/home/nobre/Notebooks/RQAR_2025_book/data/Monitoramento_QAr_BR.csv')
tabela_pols = pd.read_csv('/home/nobre/Notebooks/RQAR_2025_book/data/dicionarios/CODIGO_POLUENTES.csv')

In [72]:

estado = 'DF'
  
path = os.getcwd()+'/data/DADOS_BRUTOS/' + estado + '/'

#df_ids = funcoes[estado](path)
    
#create_df_estacao(estado,df_ids)

In [52]:
dict_pols_stat = defaultdict(list)

files = os.listdir(path)

print(files)

for item in files:
    
    estacao = " ".join(item.split('-')[1].split('.')[0].split('_')[0:2])

    print(estacao)

    df = pd.read_excel(path+item)

    df = df.drop(columns=['Nome da estação'])

    lista_pols = set(df['Poluente'])

    for pol in lista_pols:

        df_pol = df[df["Poluente"] == pol]
        
        if pol in ['no2','so2','o3']:

            df_pol = ppb_to_ug(df_pol,pol)

        df_pol_hora = df_pol.groupby(["Ano", "Mes", "Dia", "Hora", "Unidade"])
        
        df_pol_hora = df_pol_hora.filter(lambda g: len(g) >= 9)
        
        df_pol = (
            df_pol_hora.groupby(["Ano", "Mes", "Dia", "Hora", "Unidade"], as_index=False)
                  .agg({"Valor": "mean"})
        )

        df_pol['QAQC_INTERNO'] = None

        df_pol = df_pol.rename(columns={'Ano':'ANO',
                                        'Mes':'MES',
                                        'Dia':'DIA',
                                        'Hora':'HORA',
                                        'Unidade':'UNIDADE',
                                        'Valor':'VALOR'})

        for col in ["ANO", "MES", "DIA", "HORA"]:
            df_pol[col] = pd.to_numeric(df_pol[col], errors="coerce").astype("Int64")
        
        dict_pols_stat[estacao+'_'+pol].append(df_pol)

['dados_monitoramento-Sema.xlsx', 'dados_monitoramento-BEA_CBA_24-25.xlsx', 'dados_monitoramento-BEA_CBA_22-23.xlsx', 'dados_monitoramento-CBM_VG_22-23.xlsx', 'dados_monitoramento-CBM_VG_24-25.xlsx', 'dados_monitoramento-Mae_Bonifacia_22-23.xlsx', 'dados_monitoramento-Mae_Bonifacia_24-25.xlsx', 'dados_monitoramento-UFMT.xlsx']
Sema
BEA CBA
BEA CBA
CBM VG
CBM VG
Mae Bonifacia
Mae Bonifacia
UFMT

In [46]:
def ppb_to_ug(df,pol):

    if pol == 'so2':

        df.loc[df["Unidade"] != "ug/m3", "Valor"] *= 2661260.49/10**6        

    elif pol == 'no2':

        df.loc[df["Unidade"] != "ug/m3", "Valor"] *= 1911038.92/10**6        

    elif pol == 'o3':

        df.loc[df["Unidade"] != "ug/m3", "Valor"] *= 1993889.17/10**6        
    
    df.loc[:, "Unidade"] = "ug/m3"

    return df

In [60]:
dict_pols_MT = {
    'co':'CO',
    'no2': 'NO2',
    'so2': 'SO2',
    'o3': 'O3',
    'pm2p5':'MP25',
    'pm10': 'MP10'
}

dict_formatado = {}

for chave in dict_pols_stat.keys():
    
    lista_dfs = dict_pols_stat[chave]
    
    df = pd.concat(lista_dfs, ignore_index=True)

    df["DATETIME"] = pd.to_datetime(
        df.apply(lambda r: f"{r.ANO}-{r.MES}-{r.DIA} {r.HORA}:00:00", axis=1)
    )
    df = df.set_index("DATETIME")

    df = df.sort_index()
    
    lista_horas = pd.date_range(
        start=df.index.min(), 
        end=df.index.max(), 
        freq='H').strftime('%Y-%m-%d %H:%M:%S').tolist()
    
    if len(lista_horas) != len(df):
        df = df.reindex(pd.DatetimeIndex(lista_horas))

    df['DATETIME'] = df.index

    df = df[['DATETIME','ANO','MES','DIA','HORA','VALOR','UNIDADE','QAQC_INTERNO']]
    
    dict_formatado[chave] = df

primeiros_valores = {}

for chave, df in dict_formatado.items():
    
    if ~df['VALOR'].isna().all() and (df['VALOR'] > 0).any(): 
        
        linha_valida = df[df["VALOR"].notna() & (df["VALOR"] > 0)].iloc[0]
        primeiros_valores[chave] = linha_valida["DATETIME"]

codigo_estacao_MT = {}

for chave in primeiros_valores.keys():
    
    station = chave.split('_')[0]
    data = primeiros_valores[chave]
    
    if station in codigo_estacao_MT:
        if data <= codigo_estacao_MT[station]:
            codigo_estacao_MT[station] = data
    else:
        codigo_estacao_MT[station] = data

sorted_items = sorted(
    codigo_estacao_MT.items(),
    key=lambda x: (x[1], x[0])
)

codigo_estacao_MT = {}
for i, (nome, ts) in enumerate(sorted_items, start=1):
    codigo = f"MT{i:04d}"
    codigo_estacao_MT[nome] = codigo
    
for chave, df in dict_formatado.items():
    
    estacao = codigo_estacao_MT[chave.split('_')[0]]
    
    cod_pol = tabela_pols.loc[tabela_pols['POLUENTE'] == dict_pols_MT[chave.split('_')[-1]], 'COD_POLUENTE'].values[0]
    
    nome_pasta = tabela_pols.loc[tabela_pols['COD_POLUENTE'] == int(cod_pol), 'NOME_PASTA'].values[0]
    
    df.to_csv('/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/'+nome_pasta+'/'+estacao+'RA'+str(cod_pol).zfill(3)+'.csv',index=False)

df_ids = pd.DataFrame({
    'ID_OEMA': codigo_estacao_MT.keys(),
    'ID_MMA':list(codigo_estacao_MT.values())})

return df_ids

/tmp/ipykernel_564959/2479180702.py:25: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_564959/2479180702.py:25: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_564959/2479180702.py:25: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_564959/2479180702.py:25: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_564959/2479180702.py:25: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_564959/2479180702.py:25: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_564959/2479180702.py:25: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_564959/2479180702.py:25: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_564959/2479180702.py:25: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_564959/2479180702.py:25: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_564959/2479180702.py:25: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_564959/2479180702.py:25: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_564959/2479180702.py:25: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_564959/2479180702.py:25: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_564959/2479180702.py:25: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_564959/2479180702.py:25: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_564959/2479180702.py:25: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_564959/2479180702.py:25: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_564959/2479180702.py:25: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_564959/2479180702.py:25: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_564959/2479180702.py:25: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_564959/2479180702.py:25: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_564959/2479180702.py:25: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_564959/2479180702.py:25: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_564959/2479180702.py:25: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_564959/2479180702.py:25: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_564959/2479180702.py:25: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_564959/2479180702.py:25: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_564959/2479180702.py:25: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_564959/2479180702.py:25: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(

SyntaxError: 'return' outside function (2479180702.py, line 85)

In [61]:
df_ids

         ID_OEMA  ID_MMA
0  Mae Bonifacia  MT0001
1        BEA CBA  MT0002
2         CBM VG  MT0003
3           Sema  MT0004
4           UFMT  MT0005

In [185]:
from datetime import timedelta

def fix_24h(row):
    if isinstance(row, str) and row.startswith("24:"):
        # substitui 24: por 00:
        new_str = row.replace("24:", "00:", 1)
        # converte para datetime
        dt = pd.to_datetime(new_str, errors="coerce")
        # adiciona 1 dia
        if pd.notna(dt):
            dt += timedelta(days=1)
        return dt
    else:
        return pd.to_datetime(row, errors="coerce")

In [70]:
dict_stations_MT = {
        'Sema':'CPA - SEMA - CBA',
        'BEA CBA': 'Dom Aquino - BEA - CBA',
        'CBM VG': 'Água Limpa - CBM - VG',
        'Mae Bonifacia': 'Duque de Caxias - Pq Mãe Bonifácia - CBA',
        'UFMT':'Boa Esperança - UFMT - CBA'
    }
    
df_ids = pd.DataFrame({
    'ID_OEMA': codigo_estacao_MT.keys(),
    'ID_MMA':list(codigo_estacao_MT.values())})


df_ids["ID_OEMA"] = df_ids["ID_OEMA"].replace(dict_stations_MT)


df_ids['ID_OEMA']

0    Duque de Caxias - Pq Mãe Bonifácia - CBA
1                      Dom Aquino - BEA - CBA
2                       Água Limpa - CBM - VG
3                            CPA - SEMA - CBA
4                  Boa Esperança - UFMT - CBA
Name: ID_OEMA, dtype: object

In [71]:
df_ids

                                    ID_OEMA  ID_MMA
0  Duque de Caxias - Pq Mãe Bonifácia - CBA  MT0001
1                    Dom Aquino - BEA - CBA  MT0002
2                     Água Limpa - CBM - VG  MT0003
3                          CPA - SEMA - CBA  MT0004
4                Boa Esperança - UFMT - CBA  MT0005

In [120]:
estado = 'DF'

In [249]:
path = os.getcwd()+'/data/DADOS_BRUTOS/' + estado + '/'

path = path + 'Monitor Report 2024_FINAL.xlsx'

df = pd.read_excel(path)

df.iloc[1] = df.iloc[1].ffill()

poluentes = ['CO_ppm','NO2_ug/m3','NO_ug/m3','NOx_ug/m3','O3_ug/m3','PM10','PM25','PTS','SO2_ug/m3']

dict_pols = {'CO_ppm':'CO',
             'NO2_ug/m3':'NO2',
             'NO_ug/m3':'NO',
             'NOx_ug/m3':'NOX',
             'O3_ug/m3':'O3',
             'PM10':'MP10',
             'PM25':'MP25',
             'PTS':'PTS',
             'SO2_ug/m3':'SO2'}

df.columns = df.iloc[1]

df = df.drop(index=[0, 1]).reset_index(drop=True)

df = df.rename(columns={'Date Time':'DATETIME'})

estacoes = set(df.columns[1:])

dict_pols_stat = defaultdict(list)

for estacao in estacoes:

    df_estacao = df[["DATETIME",estacao]]

    df_estacao.columns = [df_estacao.columns.tolist()[0]] + df_estacao.iloc[0, 1:].tolist()

    df_estacao = df_estacao.drop(index=[0]).reset_index(drop=True)

    for pol in poluentes:

        if pol in df_estacao.columns:
            
            df_pol = df_estacao[["DATETIME",pol]]

            df_pol['UNIDADE'] = df_pol[pol][0]

            df_pol = df_pol.drop(index=[0]).reset_index(drop=True)

            df_pol = df_pol[df_pol["DATETIME"].astype(str).str.contains(r"\d", na=False)].reset_index(drop=True)

            df_pol['DATETIME'] = df_pol['DATETIME'].apply(fix_24h)

            df_pol = df_pol.rename(columns={pol:'VALOR'})

            df_pol.index = df_pol['DATETIME']

            lista_horas = pd.date_range(
                start=df_pol.index.min(), 
                end=df_pol.index.max(), 
                freq='H').strftime('%Y-%m-%d %H:%M:%S').tolist()
            
            if len(lista_horas) != len(df_pol):
                df_pol = df_pol.reindex(pd.DatetimeIndex(lista_horas))
            
            df_pol['QAQC_INTERNO'] = None
            
            df_pol.insert(1, 'ANO', df_pol.index.year)
            df_pol.insert(2, 'MES', df_pol.index.month)
            df_pol.insert(3, 'DIA', df_pol.index.day)
            df_pol.insert(4, 'HORA', df_pol.index.hour)

            pol = dict_pols[pol]

            df_pol['VALOR'] = pd.to_numeric(df_pol['VALOR'], errors='coerce')

            df_pol = df_pol[['DATETIME','ANO','MES','DIA','HORA','VALOR','UNIDADE','QAQC_INTERNO']] 

            dict_pols_stat[estacao+'_'+pol] = df_pol

/tmp/ipykernel_564959/901552261.py:45: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_pol['UNIDADE'] = df_pol[pol][0]
/tmp/ipykernel_564959/1508039512.py:14: UserWarning: Parsing dates in %d:%M %m/%H/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  return pd.to_datetime(row, errors="coerce")
/tmp/ipykernel_564959/901552261.py:57: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_564959/901552261.py:45: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_pol['UNIDADE'] = df_pol[pol][0]
/tmp/ipykernel_564959/1508039512.py:14: UserWarning: Parsing dates in %d:%M %m/%H/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  return pd.to_datetime(row, errors="coerce")
/tmp/ipykernel_564959/901552261.py:57: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_564959/901552261.py:45: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_pol['UNIDADE'] = df_pol[pol][0]
/tmp/ipykernel_564959/1508039512.py:14: UserWarning: Parsing dates in %d:%M %m/%H/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  return pd.to_datetime(row, errors="coerce")
/tmp/ipykernel_564959/901552261.py:57: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_564959/901552261.py:45: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_pol['UNIDADE'] = df_pol[pol][0]
/tmp/ipykernel_564959/1508039512.py:14: UserWarning: Parsing dates in %d:%M %m/%H/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  return pd.to_datetime(row, errors="coerce")
/tmp/ipykernel_564959/901552261.py:57: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_564959/901552261.py:45: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_pol['UNIDADE'] = df_pol[pol][0]
/tmp/ipykernel_564959/1508039512.py:14: UserWarning: Parsing dates in %d:%M %m/%H/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  return pd.to_datetime(row, errors="coerce")
/tmp/ipykernel_564959/901552261.py:57: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_564959/901552261.py:45: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_pol['UNIDADE'] = df_pol[pol][0]
/tmp/ipykernel_564959/1508039512.py:14: UserWarning: Parsing dates in %d:%M %m/%H/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  return pd.to_datetime(row, errors="coerce")
/tmp/ipykernel_564959/901552261.py:57: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_564959/901552261.py:45: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_pol['UNIDADE'] = df_pol[pol][0]
/tmp/ipykernel_564959/1508039512.py:14: UserWarning: Parsing dates in %d:%M %m/%H/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  return pd.to_datetime(row, errors="coerce")
/tmp/ipykernel_564959/901552261.py:57: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_564959/901552261.py:45: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_pol['UNIDADE'] = df_pol[pol][0]
/tmp/ipykernel_564959/1508039512.py:14: UserWarning: Parsing dates in %d:%M %m/%H/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  return pd.to_datetime(row, errors="coerce")
/tmp/ipykernel_564959/901552261.py:57: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_564959/901552261.py:45: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_pol['UNIDADE'] = df_pol[pol][0]
/tmp/ipykernel_564959/1508039512.py:14: UserWarning: Parsing dates in %d:%M %m/%H/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  return pd.to_datetime(row, errors="coerce")
/tmp/ipykernel_564959/901552261.py:57: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_564959/901552261.py:45: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_pol['UNIDADE'] = df_pol[pol][0]
/tmp/ipykernel_564959/1508039512.py:14: UserWarning: Parsing dates in %d:%M %m/%H/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  return pd.to_datetime(row, errors="coerce")
/tmp/ipykernel_564959/901552261.py:57: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_564959/901552261.py:45: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_pol['UNIDADE'] = df_pol[pol][0]
/tmp/ipykernel_564959/1508039512.py:14: UserWarning: Parsing dates in %d:%M %m/%H/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  return pd.to_datetime(row, errors="coerce")
/tmp/ipykernel_564959/901552261.py:57: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(

In [258]:
primeiros_valores = {}

for chave, df in dict_pols_stat.items():  
    
    if ~df['VALOR'].isna().all() and (df['VALOR'] > 0).any(): 
        
        linha_valida = df[df["VALOR"].notna() & (df["VALOR"] > 0)].iloc[0]
        primeiros_valores[chave] = linha_valida["DATETIME"]

codigo_estacao_DF = {}

for chave in primeiros_valores.keys():
    
    station = chave.split('_')[0]
    data = primeiros_valores[chave]
    
    if station in codigo_estacao_DF:
        if data <= codigo_estacao_DF[station]:
            codigo_estacao_DF[station] = data
    else:
        codigo_estacao_DF[station] = data

sorted_items = sorted(
    codigo_estacao_DF.items(),
    key=lambda x: (x[1], x[0])
)

codigo_estacao_DF = {}
for i, (nome, ts) in enumerate(sorted_items, start=1):
    codigo = f"DF{i:04d}"
    codigo_estacao_DF[nome] = codigo
    
for chave, df in dict_pols_stat.items():
    
    estacao = codigo_estacao_DF[chave.split('_')[0]]
    
    cod_pol = tabela_pols.loc[tabela_pols['POLUENTE'] == chave.split('_')[-1], 'COD_POLUENTE'].values[0]
    
    nome_pasta = tabela_pols.loc[tabela_pols['COD_POLUENTE'] == int(cod_pol), 'NOME_PASTA'].values[0]
    
    df.to_csv('/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/'+nome_pasta+'/'+estacao+'RA'+str(cod_pol).zfill(3)+'.csv',index=False)

dict_oemas = {
    'Estação CRAS FERCAL': 'Fercal CRAS',
    'Estação Escola':	   'Fercal Escola'}

df_ids = pd.DataFrame({
    'ID_OEMA': codigo_estacao_DF.keys(),
    'ID_MMA':list(codigo_estacao_DF.values())})

df_ids['ID_OEMA'] = df_ids['ID_OEMA'].replace(dict_oema)

return df_ids

In [275]:
df_ufs = pd.read_csv('/home/nobre/Notebooks/RQAR_2025_book/data/dicionarios/IBGE_UFS_CODIGOS.csv')
    
cod_uf =  df_ufs.loc[df_ufs['UF'] == uf, 'CODIGOS'].values[0]

print(cod_uf)

if os.path.exists('/home/nobre/Notebooks/RQAR_2025_book/data/DADOS_ESTACOES/'+uf+'_estacoes.csv'):

    df_estacao = pd.read_csv('/home/nobre/Notebooks/RQAR_2025_book/data/DADOS_ESTACOES/'+uf+'_estacoes.csv')

    df_estacao['ID_MMA'] = df_estacao['ID_OEMA'].map(df_ids.set_index('ID_OEMA')['ID_MMA'])

else:

    colunas = ['ID_OEMA', 'UF', 'ID_MMA', 'COD_UF_IBGE', 'CIDADE', 'CD_MUN',
               'PROPRIETARIO', 'PROP_ENTIDADE', 'OPERADOR', 'OP_ENTIDADE', 'LATITUDE',
               'LONGITUDE', 'MOBILIDADE', 'REALOCACAO', 'MARCA', 'CATEGORIA',
               'FUNCIONAMENTO', 'METODO', 'FINALIDADE', 'POLUENTE',
               'INICIO', 'STATUS', 'FIM', 'CALIBRACAO', 'OBS_CALIBRACAO', 'MONITORAR',
               'FONTE', 'OBS_GERAIS','DADOS_MONITORAMENTO','RECONHECIDA','REP_ESPACIAL_DECLARADA']
    
    df_estacao = pd.DataFrame(columns=colunas)

df_ids = pol_to_station(df_ids)

mapa = dict(zip(df_ids['ID_MMA'], df_ids['POLUENTE']))

df_estacao['POLUENTE'] = df_estacao['ID_MMA'].map(mapa).fillna(df_estacao['POLUENTE'])

#df_estacao = df_estacao.reindex(df_ids.index)

#df_estacao[["ID_MMA", "ID_OEMA", "POLUENTE"]] = df_ids[["ID_MMA", "ID_OEMA", "POLUENTE"]].values

df_estacao.loc[:, "COD_UF_IBGE"] = cod_uf
df_estacao.loc[:, "UF"] = uf
    
#df_estacao.to_csv('/home/nobre/Notebooks/RQAR_2025_book/data/DADOS_ESTACOES/'+uf+'_estacoes_teste.csv', index=False)

53

In [276]:
df_estacao['POLUENTE']

0                                 PM2,5
1                                  PM10
2                             MP10,MP25
3                                  PM10
4                                  PM10
5                           MP2,5, MP10
6                           MP2,5, MP10
7                           MP2,5, MP10
8    MP10,NO,CO,PTS,O3,SO2,NO2,NOX,MP25
Name: POLUENTE, dtype: object

In [262]:
def pol_to_station(df_ids):

    base_path = Path('/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/')

    id_to_poluentes = {}
    
    for poluente_dir in base_path.iterdir():
        if poluente_dir.is_dir():
            poluente = poluente_dir.name
    
            arquivos = [arq.stem for arq in poluente_dir.glob("*")]
    
            for id_mma in df_ids["ID_MMA"]:
                if any(str(arq).startswith(id_mma) for arq in arquivos):
                    id_to_poluentes.setdefault(id_mma, []).append(poluente)
    
    df_ids["POLUENTE"] = df_ids["ID_MMA"].map(id_to_poluentes).fillna("").apply(lambda x: ",".join(x) if isinstance(x, list) else "")
    
    return(df_ids)

In [4]:
df = pd.read_csv(os.getcwd()+'/data/DADOS_BRUTOS/PR/2017/FOZ2017/2017.xls', sep='\t', engine='python', encoding='latin1', header=2 )

df

,Data/Hora,CHUVA(mm),DV(º),PRESS(hPa),RADG(W/m²),TEMP(°C),TEMP INT(°C),UMID(%),VV(m/s),CH4(ppm),...,HCNM(ppm),HCT(ppm),MP10(µg/m³),NO(ppb),NO2(ppb),NOX(ppb),O3(ppb),PTS(µg/m³),SO2(ppb),Unnamed: 20
0,21/06/2017 00:00,insufic,"47,81",insufic,insufic,insufic,insufic,insufic,insufic,insufic,...,insufic,insufic,insufic,insufic,insufic,insufic,insufic,insufic,insufic,NaN
1,21/06/2017 01:00,insufic,insufic,insufic,insufic,insufic,insufic,insufic,insufic,insufic,...,insufic,insufic,insufic,insufic,insufic,insufic,insufic,insufic,insufic,NaN
2,21/06/2017 02:00,insufic,insufic,insufic,insufic,insufic,insufic,insufic,insufic,insufic,...,insufic,insufic,insufic,insufic,insufic,insufic,insufic,insufic,insufic,NaN
3,21/06/2017 03:00,insufic,insufic,insufic,insufic,insufic,insufic,insufic,insufic,insufic,...,insufic,insufic,insufic,insufic,insufic,insufic,insufic,insufic,insufic,NaN
4,21/06/2017 04:00,insufic,insufic,insufic,insufic,insufic,insufic,insufic,insufic,insufic,...,insufic,insufic,insufic,insufic,insufic,insufic,insufic,insufic,insufic,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4652,31/12/2017 20:00,"0,00","91,25","977,88",insufic,"30,06","30,13","68,28","0,42",insufic,...,insufic,insufic,"54,00","20,56","14,74","35,31","8,72","76,00",insufic,NaN
4653,31/12/2017 21:00,"0,00","50,02","977,78",insufic,"29,45","30,15","73,63","0,47",insufic,...,insufic,insufic,"62,00","0,82","6,98","7,80","10,42","74,00",insufic,NaN
4654,31/12/2017 22:00,"0,00","356,79","978,03",insufic,"28,75","30,16","77,48","0,51",insufic,...,insufic,insufic,"17,00","0,23","6,52","6,75","11,36","13,00",insufic,NaN
4655,31/12/2017 23:00,"0,00","13,49","978,11",insufic,"28,27","30,30","78,45","0,31",insufic,...,insufic,insufic,"41,00","2,15","8,29","10,44","8,64","43,00",insufic,NaN
4656,01/01/2018 00:00,"0,00","116,34","978,15","0,58","27,86","30,30","76,98","0,44",insufic,...,insufic,insufic,"28,00","3,62","6,74","10,36","11,03","27,00",insufic,NaN

In [69]:
def ler_dados_parana_2024(dicionario,ano):
    
    #caminho =  os.getcwd()+'/data/DADOS_BRUTOS/PR/2024/'

    caminho = os.getcwd()+'/data/DADOS_BRUTOS/PR/'+ano+'/'
    
    arquivos = os.listdir(caminho)
    
    for arquivo in arquivos:
    
        if arquivo.endswith(('.xls', '.xlsx')):
            caminho_arquivo = os.path.join(caminho, arquivo)
            try:
                df = pd.read_excel(caminho_arquivo, header=3)
            except Exception as e:
                print(f"Tentando ler como texto: {arquivo}")
                df = pd.read_csv(caminho_arquivo, sep='\t', engine='python', encoding='latin1', header=2, on_bad_lines='skip')
                
            col_data = next(c for c in df.columns if c.startswith('Data'))
    
            df = (
                df.replace('-', np.nan)
                  .assign(**{c: pd.to_numeric(df[c], errors='coerce') for c in df.columns if c != col_data})
                  .groupby(col_data, as_index=False)
                  .agg(lambda x: x.dropna().iloc[0] if len(x.dropna()) else np.nan)
            )

            if '5MIN' in arquivo:
                estacao = arquivo.split('_')[0]
            else:
                estacao = arquivo.split('2')[0]

            if df.columns[0] == 'Data/Hora':

                print(estacao)

                df = df[pd.to_datetime(df[col_data], errors='coerce').notna()]
    
                dicionario[ano][estacao] = df

            print(len(df))

    return dicionario

def adicionar_colunas_unidade(df):
    unidades = df.iloc[0]
    
    df = df.iloc[1:].reset_index(drop=True)
    
    for col, unidade in unidades.items():
        if pd.notna(unidade):
            df[f"{col}_UNIDADE"] = unidade
    
    return df

def num_para_hora(valor):
    try:
        h = int(valor)
        m = "30" if valor % 1 == 0.5 else "00"
        return f"{h}:{m}"
    except:
        return None
        
    return df

def ler_dados_parana_1998_2002(dicionario,ano):
    
    caminho = os.getcwd()+'/data/DADOS_BRUTOS/PR/'+ano+'/'
        
    arquivos = os.listdir(caminho)
    
    for arquivo in arquivos:

        print(arquivo)
    
        if any(Path(caminho+arquivo).iterdir()):
            pasta = os.listdir(caminho+arquivo)[0]
    
            df = pd.read_excel(caminho+arquivo+'/'+pasta,header=1)

            df = adicionar_colunas_unidade(df)

            for hora in ['H', 'HORA', 'Hora']:
                if hora in df.columns:
                    df[hora] = df[hora].astype(float).apply(num_para_hora)
                    break

            estacao = arquivo[:-4]
    
            dicionario[ano][estacao] = df 

            print(len(df))
    
        else:
            print('Não há nada em '+ caminho+arquivo)

    return dicionario

def ler_dados_mes_a_mes(caminho):

    tipos_arquivos_ignorar = ['.zip','.rar','.xls','.xlsx','.7z','testes','2016','.ipynb_checkpoints']

    df = pd.DataFrame()

    #print(caminho)
    #print(sorted(os.listdir(caminho)))

    estacao = caminho.split('/')[-2].split('2')[0]
    
    for arquivo in sorted(os.listdir(caminho)):
        df_mes = pd.DataFrame()
    
        if not any(p in arquivo for p in tipos_arquivos_ignorar) or any(p in arquivo for p in ['txt']):

            if '.txt' in arquivo:
                df_mes = pd.read_csv(caminho+arquivo, sep='\t', engine='python', encoding='latin1')
                #print(df_mes.head())
                #print(arquivo)
                df = pd.concat([df, df_mes], ignore_index=True)
            
            else:
                mes = arquivo[:2]
                base_path = os.path.join(caminho, arquivo)
                
                nomes_possiveis = [
                    [f"{estacao}1H_{mes}_{ano}.txt",0],
                    [f"{estacao}1H.txt",0],
                    [f"{estacao}1H_{mes}_{ano}.xls",3],
                    [f"{estacao}_1H.xls",2]
                ]

                for nome in nomes_possiveis:
                    full_path = os.path.join(base_path, nome[0])
                    
                    try:
                        df_mes = pd.read_csv(full_path, sep='\t', engine='python', encoding='latin1',header=nome[1])
                        break
                    except Exception:
                        try:
                            df_mes = pd.read_excel(full_path, engine='xlrd',header=nome[1])
                            break
                        except Exception:
                            continue

            if len(df_mes) == 0:

                print(caminho)
                #print(sorted(os.listdir(caminho)))
                #print(arquivo)
                print(df_mes.head())
                print('')
                
            df = pd.concat([df, df_mes], ignore_index=True)

            #df = pd.concat([df, df_mes], ignore_index=True)
           
    
    print('')
            
    
    return df

def verifica_numero(num):
    try:
        if num != np.nan:
            float(num)
            return True
    except (ValueError, TypeError):
        return False

def verifica_data(data):
    try:
        pd.to_datetime(data)
        return True
    except (ValueError, TypeError):
        return False

def ler_dados_parana_2003_2019(dicionario,ano):

    pastas_ignorar = ['IQA diário','IQA_IAP','2016','ARAUCARIA2018','ARAUCARIA2019','Thumbs.db','~$Validação_Maio_2014.xlsm','SIX1H_2017.zip','.ipynb_checkpoints']

    caminho = os.getcwd()+'/data/DADOS_BRUTOS/PR/'+ano+'/'
        
    arquivos = os.listdir(caminho)

    print('')
    print(ano)
    
    for arquivo in arquivos:

        if arquivo not in pastas_ignorar:

            print(arquivo)
            
            if any(nome.endswith(('.xls', '.xlsx')) for nome in os.listdir(caminho+arquivo)) and len(os.listdir(caminho+arquivo)) <= 3:
                print(os.listdir(caminho+arquivo))

                xlsx = [f for f in os.listdir(caminho+arquivo) if f.endswith('.xlsx')]
                xls = [f for f in os.listdir(caminho+arquivo) if f.endswith('.xls')]
                
                if xlsx:
                    estacao = xlsx[0] 
                elif xls:
                    estacao = xls[0]

                try:
                    if ano == '2003':
                        df = pd.read_excel(caminho+arquivo+'/'+estacao,header=1)
                    elif estacao == 'CIC2019.xlsx':
                        df = pd.read_excel(caminho+arquivo+'/'+estacao,header=2)
                    else:
                        df = pd.read_excel(caminho+arquivo+'/'+estacao)
                except Exception as e:
                    print(f"Tentando ler como texto: {arquivo}")
                    df = pd.read_csv(caminho+arquivo+'/'+estacao, sep='\t', engine='python', encoding='latin1', header=2)
                
                if not (verifica_numero(df[df.columns[0]].iloc[0]) or verifica_data(df[df.columns[0]].iloc[0])) or arquivo == 'SIX2017':

                    df = adicionar_colunas_unidade(df)

                print(len(df))
                    
                dicionario[ano][arquivo[:-4]] = df 

            elif 'IAP' not in arquivo:

                try:
                        
                    df = ler_dados_mes_a_mes(caminho+arquivo+'/')
                    
                    if not (verifica_numero(df[df.columns[0]].iloc[0]) or verifica_data(df[df.columns[0]].iloc[0])):
    
                        df = adicionar_colunas_unidade(df)
                
                    dicionario[ano][arquivo[:-4]] = df 

                    print(len(df))

                except Exception as e:
                    print(f"A seguinte pasta não existe: {caminho}{arquivo}")
                    
    return(dicionario)

In [65]:
len(pd.DataFrame())

0

In [240]:
estacoes_por_ano = {
    '1998': {},
    '1999': {},
    '2000': {},
    '2001': {},
    '2002': {},
    '2003': {},
    '2004': {},
    '2005': {},
    '2006': {},
    '2007': {},
    '2008': {},
    '2009': {},
    '2010': {},
    '2011': {},
    '2012': {},
    '2013': {},
    '2014': {},
    '2015': {},
    '2016': {},
    '2017': {},
    '2018': {},
    '2019': {},
    '2020': {},
    '2021': {},
    '2022': {},
    '2023': {},
    '2024': {}
}

for ano in ['1998','1999','2000',
            '2001','2002','2003','2004','2005','2006','2007','2008','2009','2010',
            '2011','2012','2013','2014','2015','2016','2017','2018','2019','2024']:

    if ano in ['1998','1999','2000','2001','2002']:
        estacoes_por_ano = ler_dados_parana_1998_2002(estacoes_por_ano,ano)
    elif ano in ['2003','2004','2005','2006','2007','2008','2009','2010','2011','2012','2013','2014','2015','2016','2017','2018','2019']:
        estacoes_por_ano = ler_dados_parana_2003_2019(estacoes_por_ano,ano)
    elif ano in ['2024']:
        estacoes_por_ano = ler_dados_parana_2024(estacoes_por_ano,ano)

STC1998
2969
CIC1998
12067
STC1999
17472
CIC1999
Não há nada em /home/nobre/Notebooks/RQAR_2025_book/data/DADOS_BRUTOS/PR/1999/CIC1999
CIC2000
Não há nada em /home/nobre/Notebooks/RQAR_2025_book/data/DADOS_BRUTOS/PR/2000/CIC2000
STC2000
Não há nada em /home/nobre/Notebooks/RQAR_2025_book/data/DADOS_BRUTOS/PR/2000/STC2000
ASS2000
Não há nada em /home/nobre/Notebooks/RQAR_2025_book/data/DADOS_BRUTOS/PR/2000/ASS2000
ASS2001
Não há nada em /home/nobre/Notebooks/RQAR_2025_book/data/DADOS_BRUTOS/PR/2001/ASS2001
STC2001
Não há nada em /home/nobre/Notebooks/RQAR_2025_book/data/DADOS_BRUTOS/PR/2001/STC2001
CIC2001
17520
CIC2002
8736
BOQ2002
Não há nada em /home/nobre/Notebooks/RQAR_2025_book/data/DADOS_BRUTOS/PR/2002/BOQ2002
ASS2002
8760

2003
CIC2003
['CIC1h-2003.xls']
8760
IAP2003
CSN2003

8771
UEG2003

6608
PAR2003

8771
RPR2003

3676
BOQ2003

8771

2004
UEG2004

8795
CIC2004

5142
RPR2004

8795
PAR2004

8795
BOQ2004

8795
CSN2004

8795
ASS2004

5142
IAP2004
STC2004

5887

2005
PAR2005

8771
STC2005

8771
CIC2005

8771
CSN2005

8771
RPR2005

8770
UEG2005

8770
ASS2005

8771
BOQ2005

8771
IAP2005

2006
PAR2006

8771
ASS2006

8771
CSN2006

8771
CIC2006

4349
BOQ2006

8771
STC2006

8771
UEG2006

8771
IAP2006
RPR2006

8771

2007
ASS2007

8771
BOQ2007

7305
IAP2007
PAR2007

8771
RPR2007

8771
STC2007

8771
CSN2007

8771
UEG2007

8771

2008
PAR2008

8795
UEG2008

8795
CSN2008

8795
ASS2008

8795
IAP2008
RPR2008

8795
STC2008

8795

2009
ASS2009

8771
IAP2009
BOQ2009

3676
PAR2009

8771
RPR2009

8771
UEG2009

8771
CSN2009

8770
STC2009

8771

2010
IAP2010
CIC2010

2979
PAR2010

8771
ASS2010

8771
BOQ2010

8771
UEG2010

8770
RPR2010

8771
CSN2010

8771
STC2010

8771

2011
ASS2011

8771
CIC2011

8829
BOQ2011

8771
STC2011

8770
UEG2011

8771
SIX2011

5142
RPR2011

8771
CSN2011

8771
PAR2011

8771
IAP2011

2012
SIX2012

8795
IAP2012
CSN2012

8795
RPR2012

8795
UEG2012

8795
ASS2012

8795
PAR2012

8795
CIC2012

8867
STC2012

8795
BOQ2012

8795

2013
RPR2013

8770
ASS2013

8771
IAP2013
UEG2013

8771
BOQ2013

8771
CIC2013

8918
PAR2013

8771
SIX2013

8771
CSN2013

8771
STC2013

8771

2014
STC2014

8778
CIC2014

8860
UEG2014

8771
SIX2014

8770
CSN2014

8771
RPR2014

8771
IAP2014
PAR2014

8771
ASS2014

8771
BOQ2014

8771

2015
UEG2015

8771
ASS2015

8771
CSN2015

8771
CIC2015

8771
IAP2015
RPR2015

8771
PAR2015

8771
STC2015

8770
SIX2015

8771
BOQ2015

8771

2016
MRGA2016

10511
ASS2016

8795
CSN2016

8795
PGA2016

5893
UEG2016

8794
CVEL

A seguinte pasta não existe: /home/nobre/Notebooks/RQAR_2025_book/data/DADOS_BRUTOS/PR/2016/CVEL
CIC2016

8798
LON2016

1487
IAP2016
CAS2016
/home/nobre/Notebooks/RQAR_2025_book/data/DADOS_BRUTOS/PR/2016/CAS2016/
Empty DataFrame
Columns: []
Index: []

/home/nobre/Notebooks/RQAR_2025_book/data/DADOS_BRUTOS/PR/2016/CAS2016/
Empty DataFrame
Columns: []
Index: []

/home/nobre/Notebooks/RQAR_2025_book/data/DADOS_BRUTOS/PR/2016/CAS2016/
Empty DataFrame
Columns: []
Index: []

/home/nobre/Notebooks/RQAR_2025_book/data/DADOS_BRUTOS/PR/2016/CAS2016/
Empty DataFrame
Columns: []
Index: []

/home/nobre/Notebooks/RQAR_2025_book/data/DADOS_BRUTOS/PR/2016/CAS2016/
Empty DataFrame
Columns: []
Index: []

/home/nobre/Notebooks/RQAR_2025_book/data/DADOS_BRUTOS/PR/2016/CAS2016/
Empty DataFrame
Columns: []
Index: []

/home/nobre/Notebooks/RQAR_2025_book/data/DADOS_BRUTOS/PR/2016/CAS2016/
Empty DataFrame
Columns: []
Index: []

/home/nobre/Notebooks/RQAR_2025_book/data/DADOS_BRUTOS/PR/2016/CAS2016/
Empty DataFrame
Columns: []
Index: []

/home/nobre/Notebooks/RQAR_2025_book/data/DADOS_BRUTOS/PR/2016/CAS2016/
Empty DataFrame
Columns: []
Index: []

/home/nobre/Notebooks/RQAR_2025_book/data/DADOS_BRUTOS/PR/2016/CAS2016/
Empty DataFrame
Columns: []
Index: []


1440
SIX2016

8794
STC2016

8795
BOQ2016

8795
PAR2016

8795
RPR2016

8795

2017
LON2017

17519
RPR2017
['RPR1H_2017.xls']
8784
FOZ2017
['2017.xls']
Tentando ler como texto: FOZ2017
4657
STC2017

A seguinte pasta não existe: /home/nobre/Notebooks/RQAR_2025_book/data/DADOS_BRUTOS/PR/2017/STC2017
MRGA2017

17519
CIC2017

A seguinte pasta não existe: /home/nobre/Notebooks/RQAR_2025_book/data/DADOS_BRUTOS/PR/2017/CIC2017
BOQ2017
['BOQ1H_2017.xlsx']

/tmp/ipykernel_175285/3697526426.py:173: UserWarning: Parsing dates in %d/%m/%Y %H:%M format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  pd.to_datetime(data)

8760
PGA2017

8129
PAR2017
['PAR1H_2017.xls']
8760
CSN2017
['CSN1H_2017.xls']
8760
SIX2017
['SIX1H_2017.xls']
5832
ASS2017

A seguinte pasta não existe: /home/nobre/Notebooks/RQAR_2025_book/data/DADOS_BRUTOS/PR/2017/ASS2017
UEG

A seguinte pasta não existe: /home/nobre/Notebooks/RQAR_2025_book/data/DADOS_BRUTOS/PR/2017/UEG

2018
PGA2018

8841
LON2018

17517
CIC2018
['CIC2018.xls']
Tentando ler como texto: CIC2018
8761
ASS2018
['.ipynb_checkpoints', 'ASS18.xls']
Tentando ler como texto: ASS2018
8761
CVEL2018
/home/nobre/Notebooks/RQAR_2025_book/data/DADOS_BRUTOS/PR/2018/CVEL2018/
Empty DataFrame
Columns: [Report, Date/Time, 1:Temp, 2:O3, 3:CO, 4:NO, 5:NO2, 6:NOx, 7:SO2, 8:CH4 , 9:NMHC, 10:THC, 11:PM10, 12:PTS, 13:AT , 14:RH , 15:BP, 16:SR , 17:WS, 18:WD, 19:RAIN]
Index: []

[0 rows x 21 columns]


14295
CSN2018
['CSN2018.xls']
Tentando ler como texto: CSN2018

/tmp/ipykernel_175285/3697526426.py:119: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, df_mes], ignore_index=True)
/tmp/ipykernel_175285/3697526426.py:153: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, df_mes], ignore_index=True)

8761
UEG2018
['UEG2018.xls']
Tentando ler como texto: UEG2018
898
FOZ2018

15177
MRGA2018

17519
SIX2018
['.ipynb_checkpoints', 'SIX2018.xls']
Tentando ler como texto: SIX2018
8737

2019
CSN2019
['CSN2019.xls']
Tentando ler como texto: CSN2019
8761
CVEL2019

6783
RPR2019
['RPR2019.xls']
Tentando ler como texto: RPR2019
8761
FOZ2019
/home/nobre/Notebooks/RQAR_2025_book/data/DADOS_BRUTOS/PR/2019/FOZ2019/
Empty DataFrame
Columns: [Report, Date/Time, 1:Temp, 2:O3, 3:CO, 4:NO, 5:NO2, 6:NOx, 7:SO2, 8:CH4 , 9:NMHC, 10:THC, 11:PM10, 12:PTS, 13:AT , 14:RH , 15:BP, 16:SR , 17:WS, 18:WD, 19:RAIN]
Index: []

[0 rows x 21 columns]


9057
LON2019

/tmp/ipykernel_175285/3697526426.py:119: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, df_mes], ignore_index=True)
/tmp/ipykernel_175285/3697526426.py:153: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, df_mes], ignore_index=True)

14457
PGA2019

13341
MRGA2019

17517
ASS2019
['.ipynb_checkpoints', 'ASS2019.xls']
Tentando ler como texto: ASS2019
8761
SIX2019
['SIX2019.xls']
Tentando ler como texto: SIX2019
8737
CIC2019
['CIC2019.xls', 'CIC2019.xlsx']
8761
Tentando ler como texto: JDA2024.xls
JDA
384
Tentando ler como texto: BOQ_5MIN_2024.xls

/tmp/ipykernel_175285/3697526426.py:37: UserWarning: Parsing dates in %d/%m/%Y %H:%M format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df = df[pd.to_datetime(df[col_data], errors='coerce').notna()]

BOQ
10368
Tentando ler como texto: MVA_5MIN_2024.xls
MVA
6425
Tentando ler como texto: MVB_5MIN_2024.xls
MVB
10368
266
Tentando ler como texto: ECV_5MIN_2024.xls

/tmp/ipykernel_175285/3697526426.py:22: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace('-', np.nan)

ECV

/tmp/ipykernel_175285/3697526426.py:37: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df = df[pd.to_datetime(df[col_data], errors='coerce').notna()]

26485
Tentando ler como texto: MRGA_5MIN_2024.xls
MRGA
17280
Tentando ler como texto: MGA_5MIN_2024.xls
MGA
10368
Tentando ler como texto: RPR2024.xls
366
Tentando ler como texto: JDA_5MIN_2024.xls
JDA
10368
Tentando ler como texto: CLB_5MIN_2024.xls
CLB
10370
Tentando ler como texto: CVEL_5MIN_2024.xls
CVEL
10368
Tentando ler como texto: LDA_5MIN_2024.xls
LDA
10368
Tentando ler como texto: PARP2024.xls
366
Tentando ler como texto: PGA2024.xls
366
Tentando ler como texto: FNB_5MIN_2024.xls
FNB
10387
Tentando ler como texto: LON_5MIN_2024.xls
LON
10368
Tentando ler como texto: CIC2024.xls
CIC
3456
Tentando ler como texto: DCA_5MIN_2024.xls
DCA

/tmp/ipykernel_175285/3697526426.py:37: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df = df[pd.to_datetime(df[col_data], errors='coerce').notna()]

26485
Tentando ler como texto: FOZ_5MIN_2024.xls
FOZ
10371
Tentando ler como texto: FOSPAR_5MIN_2024.xls
FOSPAR
10368
Tentando ler como texto: SIX2024.xls
366
Tentando ler como texto: CLB2024.xls
79

In [262]:
lista = []

def parse_datetime(x):
    for fmt in ('%Y-%m-%d %H:%M:%S', '%d/%m/%Y %H:%M', '%m/%d/%Y %I:%M:%S %p'):
        try:
            return pd.to_datetime(x, format=fmt)
        except:
            continue
    return pd.to_datetime(x, errors='coerce')
                
def criar_datetime(df,tipo):

    if tipo == 'D':

        df['A'] = pd.to_numeric(df['A'], errors='coerce')

        if df['A'].iloc[0] < 2000:

            df['A'] = df['A'] + 2000
                
        df['H'] = df['H'].astype(str).str.split(':').str[0]
        
        df[['A', 'M', 'D', 'H']] = df[['A', 'M', 'D', 'H']].apply(pd.to_numeric, errors='coerce')
        
        df['datetime'] = pd.to_datetime(
            dict(year=df['A'], month=df['M'], day=df['D'], hour=df['H'].clip(upper=23)),
            errors='coerce'
        )
        
        df.loc[df['H'] == 24, 'datetime'] = df.loc[df['H'] == 24, 'datetime'] + pd.Timedelta(hours=1)
    
    elif tipo == 'DATA':

        df['datetime'] = pd.to_datetime(df['DATA']) + pd.to_timedelta(df['HORA'] + ':00')

        df = df.drop(columns=[c for c in ['ANO', 'MES', 'DIA', 'HORA'] if c in df.columns])
    
    elif tipo == 'Data':

        try:
            df['Data'] = pd.to_datetime(df['Data']).dt.date
        except:
            print(1)

        print(df.loc[df['Data'].astype(str).str.contains('--', na=False)])

        df['datetime'] = pd.to_datetime(df['Data']) + pd.to_timedelta(df['Hora'] + ':00')

    elif tipo == 'Data/Hora':
        
        df['Data/Hora'] = df['Data/Hora'].apply(parse_datetime)
        
        df['Data/Hora'] = df['Data/Hora'].dt.strftime('%Y-%m-%d %H:%M:%S')

        df['datetime'] = pd.to_datetime(df['Data/Hora'])

    elif tipo == 'Date/Time':
        
        df['Date/Time'] = df['Date/Time'].apply(parse_datetime)
        
        df['Date/Time'] = df['Date/Time'].dt.strftime('%Y-%m-%d %H:%M:%S')

        df['datetime'] = pd.to_datetime(df['Date/Time'])
        
    df = df.set_index("datetime")

    df = df.sort_index()
    
    df.insert(0, 'DATETIME', df.index)
    df.insert(1, 'ANO', df.index.year)
    df.insert(2, 'MES', df.index.month)
    df.insert(3, 'DIA', df.index.day)
    df.insert(4, 'HORA', df.index.hour)

    return df

lista_colunas = []

for ano in estacoes_por_ano.keys():
    
    print(ano)

    for estacao in estacoes_por_ano[ano].keys():

        #print(estacao)
        
        lista.append(estacao)

        lista_colunas = lista_colunas + list(estacoes_por_ano[ano][estacao].columns)
        
        if any(item in ['D','DATA','Data','Date/Time','Data/Hora'] for item in estacoes_por_ano[ano][estacao].columns):

            if 'D' in estacoes_por_ano[ano][estacao].columns:
                print('D')
                #estacoes_por_ano[ano][estacao] = criar_datetime(estacoes_por_ano[ano][estacao], 'D')
                #print(estacoes_por_ano[ano][estacao])
            elif 'DATA' in estacoes_por_ano[ano][estacao].columns:
                print('DATA')
                #estacoes_por_ano[ano][estacao] = criar_datetime(estacoes_por_ano[ano][estacao], 'DATA')
                #print(estacoes_por_ano[ano][estacao])
            elif 'Data' in estacoes_por_ano[ano][estacao].columns:
                print('Data')
                #estacoes_por_ano[ano][estacao] = criar_datetime(estacoes_por_ano[ano][estacao], 'Data')
                #print(estacoes_por_ano[ano][estacao])
            elif 'Date/Time' in estacoes_por_ano[ano][estacao].columns:
                print('Date/Time')
                #estacoes_por_ano[ano][estacao] = criar_datetime(estacoes_por_ano[ano][estacao], 'Date/Time')
                #print(estacoes_por_ano[ano][estacao])
            elif 'Data/Hora' in estacoes_por_ano[ano][estacao].columns:
                print('Data/Hora')
                #estacoes_por_ano[ano][estacao] = criar_datetime(estacoes_por_ano[ano][estacao], 'Data/Hora')
                #print(estacoes_por_ano[ano][estacao])
            else:
                print('ERRO')
    print('')

'''
lista1 = sorted(set(lista))

lista_pr = pd.read_csv(os.getcwd() + '/data/DADOS_ESTACOES/PR_estacoes.csv')

lista2 = sorted(lista_pr['ID_OEMA'])

iguais = sorted(set(lista1) & set(lista2))

so_lista1 = [x for x in lista1 if x not in iguais]
so_lista2 = [x for x in lista2 if x not in iguais]

col1 = iguais + so_lista1 + [np.nan] * len(so_lista2)
col2 = iguais + [np.nan] * len(so_lista1) + so_lista2

df = pd.DataFrame({'PR_dados': col1, 'PR_estacao': col2})

df'''

print(lista_colunas)
print(len(list(set(lista_colunas))))

1998
Data
Data

1999
Data

2000

2001
Data

2002
DATA
D

2003
D
D
D
D
D
D

2004
D
D
D
D
D
D
D
D

2005
D
D
D
D
D
D
D
D

2006
D
D
D
D
D
D
D
D

2007
D
D
D
D
D
D
D

2008
D
D
D
D
D
D

2009
D
D
D
D
D
D
D

2010
D
D
D
D
D
D
D
D

2011
D
D
D
D
D
D
D
D
D

2012
D
D
D
D
D
D
D
D
D

2013
D
D
D
D
D
D
D
D
D

2014
D
D
D
D
D
D
D
D
D

2015
D
D
D
D
D
D
D
D
D

2016
Date/Time
D
D
Date/Time
D
D
Date/Time
Data/Hora
D
D
D
D
D

2017
Date/Time
D
Data/Hora
Date/Time
D
Date/Time
D
D
D

2018
Date/Time
Date/Time
Data/Hora
Data/Hora
Date/Time
Data/Hora
Data/Hora
Date/Time
Date/Time
Data/Hora

2019
Data/Hora
Date/Time
Data/Hora
Date/Time
Date/Time
Date/Time
Date/Time
Data/Hora
Data/Hora
Data/Hora

2020

2021

2022

2023

2024
Data/Hora
Data/Hora
Data/Hora
Data/Hora
Data/Hora
Data/Hora
Data/Hora
Data/Hora
Data/Hora
Data/Hora
Data/Hora
Data/Hora
Data/Hora
Data/Hora
Data/Hora
Data/Hora


In [30]:
estacoes_dicionario.keys()

for chave in estacoes_dicionario.keys():

    print(chave)
    print(len(estacoes_dicionario[chave]))
    print(estacoes_dicionario[chave].columns[0])
    print(estacoes_dicionario[chave].iloc[0, 0])
    print(estacoes_dicionario[chave].iloc[-1, 0])
    print("")

    estacoes_por_ano

,D,M,A,H,SO2,NO,NO2,O3,CO,PTS,...,THC,CH4,NMHC,TEMP,UMID,PRESS,VV,DV,RADG,CHUVA
0,NaN,NaN,NaN,NaN,ppb,ppb,ppb,ppb,ppm,µg/m³,...,ppm,ppm,ppm,°C,%,mBar,m/s,graus,W/m2,mm
1,1.0,1.0,17.0,1.0,0,NaN,NaN,7.8,0.46,NaN,...,1.39,1.33,NaN,23.2,99.9,923.3,1.2,232.4,7.7,NaN
2,1.0,1.0,17.0,2.0,0.2,NaN,NaN,15,0.38,NaN,...,1.38,1.26,NaN,22,99.9,922.2,1.2,189.2,6,NaN
3,1.0,1.0,17.0,3.0,0.6,NaN,NaN,10.7,0.37,NaN,...,1.35,1.26,NaN,21.9,99.9,921.5,0.9,274.3,5.3,NaN
4,1.0,1.0,17.0,4.0,0.4,NaN,NaN,11.1,0.41,NaN,...,1.35,1.26,NaN,21.7,99.9,921.1,1.2,275,4,NaN

In [254]:
list(estacoes_por_ano[ano][estacao].columns)

['DATETIME',
 'ANO',
 'MES',
 'DIA',
 'HORA',
 'Data/Hora',
 'CHUVA(mm)',
 'DV(º)',
 'PRESS(hPa)',
 'RADG(W/m²)',
 'TEMP(°C)',
 'UMID(%)',
 'VV(m/s)',
 'CO(ppm)',
 'MP10(µg/m³)',
 'PM_2_5(µg/m³)',
 'SO2(ppb)',
 'TRS(ppb)',
 'Unnamed: 13']

In [2]:
def rep_temp(df,agrupamento,criterio,periodo_ref):

    resultados = []
    
    for chave, dados in df.groupby(agrupamento):
        qntd_valor = dados['VALOR'].notna().sum()  

        if criterio == 'HORA':
            qntd_tempo = 24
        elif criterio == 'DIA':
            if chave[1] in [4,6,9,11]:
                qntd_tempo = 30
            elif chave[1] in [1,3,5,7,8,10,12]:
                qntd_tempo = 31
            else:
                if (chave[0] % 4 == 0 and chave[0] % 100 != 0) or (chave[0] % 400 == 0):
                    qntd_tempo = 29
                else:
                    qntd_tempo = 28
        
        if qntd_valor >= (2/3) * qntd_tempo:
            if periodo_ref == "8horas":
                media = dados["VALOR"].rolling(window=8, min_periods=1).mean().max()
            else:
                media = periodo_ref(dados["VALOR"])
            rep = True
        else:
            media = np.nan   
            rep = False

        prcnt = 100*qntd_valor/qntd_tempo

        resultados.append((*chave, media, rep, prcnt))

    return resultados

def conta_dias_quadrimestre(ano,quadrimestre):

    if quadrimestre == 1:
        if (ano % 4 == 0 and ano % 100 != 0) or (ano % 400 == 0):
            dias = 121
        else:
            dias = 120
    elif quadrimestre == 2:
        dias = 123
    else:
        dias = 122

    return dias

def rep_temp_ano(df,agrupamento,criterio):

    resultados = []
    
    for chave, dados in df.groupby(agrupamento):
        qntd_valor = dados['VALOR'].notna().sum()
        qntd_tempo = conta_dias_quadrimestre(chave[0],chave[1])         
        
        if qntd_valor >= (1/2) * qntd_tempo:
            rep = True
        else:
            rep = False
    
        resultados.append((*chave, rep))

    return resultados
    
df_estacoes_rep_temporal = pd.DataFrame({
                    'ID_MMA_COMPLETO':[],
                    'PRCNT_REP_DIA':[],
                    'PRCNT_REP_MES':[],
                    'PRCNT_REP_ANO':[]
                })
                
for pol in df_rep_temporal.index:
    
    path = os.getcwd()+'/data/MQAr/' + pol + '/'

    print(pol)
    
    if os.path.isdir(path) and os.listdir(path):
        
        arquivos = os.listdir(path)
    
        for estacao in arquivos:

            if estacao.endswith('.csv'):

                print(estacao)

                df = pd.read_csv(path+estacao)

                df["VALOR"] = pd.to_numeric(df["VALOR"], errors="coerce")

                resultados_24 = rep_temp(df,['ANO','MES','DIA'],'HORA',np.mean)

                df_24 = pd.DataFrame(resultados_24, columns=['ANO', 'MES', 'DIA', 'VALOR', 'REP_DIA','PRCNT_REP'])

                df_24['DATETIME'] = pd.to_datetime(
                        dict(year=df_24["ANO"], month=df_24["MES"], day=df_24["DIA"])
                    )
            
                df_24 = df_24[['DATETIME','ANO','MES','DIA','VALOR','REP_DIA','PRCNT_REP']]

                if df_rep_temporal['DIA'][pol] == 'dia':
                    df_dia = df_24
                elif df_rep_temporal['DIA'][pol] == '8horas':
                    resultados_dia = rep_temp(df,['ANO','MES','DIA'],'HORA','8horas')

                    df_dia = pd.DataFrame(resultados_dia, columns=['ANO', 'MES', 'DIA', 'VALOR', 'REP_DIA','PRCNT_REP'])

                    df_dia['DATETIME'] = pd.to_datetime(dict(year=df_dia["ANO"], month=df_dia["MES"], day=df_dia["DIA"]))

                    df_dia = df_dia[['DATETIME','ANO','MES','DIA','VALOR','REP_DIA','PRCNT_REP']]
                        
                else:
                    resultados_dia = rep_temp(df,['ANO','MES','DIA'],'HORA',np.max)

                    df_dia = pd.DataFrame(resultados_dia, columns=['ANO', 'MES', 'DIA', 'VALOR', 'REP_DIA','PRCNT_REP'])

                    df_dia['DATETIME'] = pd.to_datetime(dict(year=df_dia["ANO"], month=df_dia["MES"], day=df_dia["DIA"]))

                    df_dia = df_dia[['DATETIME','ANO','MES','DIA','VALOR','REP_DIA','PRCNT_REP']]

                df_dia.to_csv(os.getcwd()+'/data/MQAr_averages/'+df_rep_temporal['DIA'][pol]+'/'+pol+'/'+estacao,index=False)

                resultados_mes = rep_temp(df_24,['ANO','MES'],'DIA',np.mean)

                df_mes = pd.DataFrame(resultados_mes, columns=['ANO', 'MES', 'VALOR', 'REP_MES','PRCNT_REP'])

                df_mes['DATETIME'] = pd.to_datetime(dict(year=df_mes["ANO"], month=df_mes["MES"], day=1))
            
                df_mes = df_mes[['DATETIME','ANO','MES','VALOR','REP_MES','PRCNT_REP']]

                df_mes.to_csv(os.getcwd()+'/data/MQAr_averages/'+df_rep_temporal['MES'][pol][:6]+'/'+pol+'/'+estacao,index=False)

                condicoes = [
                    (df_dia['MES'] <= 4),
                    (df_dia['MES'] >= 5) & (df_dia['MES'] <= 8),
                    (df_dia['MES'] >= 9)
                ]
                
                quadrimestre = [1, 2, 3]
                
                df_dia['QUADRIMESTRE'] = np.select(condicoes, quadrimestre)

                resultados_quad = rep_temp_ano(df_dia,['ANO','QUADRIMESTRE'],'QUADRIMESTRE')

                df_quad = pd.DataFrame(resultados_quad, columns=['ANO', 'QUADRIMESTRE', 'REP_QUAD'])
                
                df_ano_quad = df_quad.groupby("ANO", as_index=False).agg({"REP_QUAD": lambda x: x.sum() == 3})

                resultados = []
                
                for ano, dados in df_dia.groupby(['ANO']):
                    qntd_valor = dados['VALOR'].notna().sum()
                    if (ano[0] % 4 == 0 and ano[0] % 100 != 0) or (ano[0] % 400 == 0):
                        dias = 366
                    else:
                        dias = 365
                    prcnt_rep = (100*qntd_valor/dias)
                    if df_ano_quad.loc[df_ano_quad["ANO"] == ano[0], "REP_QUAD"].values[0] == True:
                        media = dados['VALOR'].mean()
                        rep = True
                    else:
                        media = np.nan
                        rep = False
                    resultados.append((*ano, media, rep, prcnt_rep))
                
                df_ano = pd.DataFrame(resultados, columns=['ANO', 'VALOR','REP_ANO','PRCNT_REP'])
                
                df_ano['DATETIME'] = pd.to_datetime(dict(year=df_ano["ANO"], month=1, day=1))
            
                df_ano = df_ano[['DATETIME','ANO','VALOR','REP_ANO','PRCNT_REP']]

                df_ano.to_csv(os.getcwd()+'/data/MQAr_averages/'+df_rep_temporal['ANO'][pol][:5]+'/'+pol+'/'+estacao, index=False)

                prcnt_dia = 100 * df_dia['VALOR'].notna().sum() / len(df_dia)
                prcnt_mes = 100 * df_mes['VALOR'].notna().sum() / len(df_mes)
                prcnt_ano = 100 * df_ano['VALOR'].notna().sum() / len(df_ano)

                prcnt_estacao = {'ID_MMA_COMPLETO': estacao[:-4], 'PRCNT_REP_DIA': prcnt_dia, 'PRCNT_REP_MES': prcnt_mes, 'PRCNT_REP_ANO': prcnt_ano}

                df_estacoes_rep_temporal = pd.concat([df_estacoes_rep_temporal, pd.DataFrame([prcnt_estacao])], ignore_index=True)

df_estacoes_rep_temporal.to_csv(os.getcwd()+'/data/MQAr_averages/REP_TEMPORAL.csv', index=False)

MP10
SP0248RA001.csv
RJ0031RA001.csv

KeyboardInterrupt:

In [70]:
df_estacoes_rep_temporal

  ID_MMA_COMPLETO  PRCNT_REP_DIA  PRCNT_REP_MES  PRCNT_REP_ANO
0     SP0248RA001      96.243112      95.959596      88.235294
1     RJ0031RA001      88.713704      90.800000      80.952381
2     RJ0282RA001      84.054054      76.923077       0.000000

In [71]:
estacao

'SP0085RA001.csv'

In [74]:
condicoes = [
    (df_dia['MES'] <= 4),
    (df_dia['MES'] >= 5) & (df_dia['MES'] <= 8),
    (df_dia['MES'] >= 9)
]

quadrimestre = [1, 2, 3]

df_dia['QUADRIMESTRE'] = np.select(condicoes, quadrimestre)

resultados_quad = rep_temp_ano(df_dia,['ANO','QUADRIMESTRE'],'QUADRIMESTRE')

df_quad = pd.DataFrame(resultados_quad, columns=['ANO', 'QUADRIMESTRE', 'REP_QUAD'])

df_ano_quad = df_quad.groupby("ANO", as_index=False).agg({"REP_QUAD": lambda x: x.sum() == 3})

In [83]:
df_ano

        ANO      VALOR  REP_ANO
0   (2009,)        NaN    False
1   (2010,)  76.227778     True
2   (2011,)  75.494915     True
3   (2012,)  77.752161     True
4   (2013,)  69.000000     True
5   (2014,)  89.419890     True
6   (2015,)  67.670360     True
7   (2016,)  73.575385     True
8   (2017,)  72.285714     True
9   (2018,)  67.177465     True
10  (2019,)  61.461078     True
11  (2020,)  70.846575     True
12  (2021,)  74.279778     True
13  (2022,)  64.519231     True
14  (2023,)  71.071233     True
15  (2024,)  92.608939     True
16  (2025,)        NaN    False

In [41]:
df_pivot = df_mes.pivot(index='ANO', columns='MES', values='PRCNT_REP')

df_pivot = df_pivot.reindex(sorted(df_pivot.columns), axis=1)

df_pivot = df_pivot.reset_index()

df_pivot

MES,ANO,1,2,3,4,5,6,7,8,9,10,11,12
0,2009,NaN,NaN,NaN,53.333333,100.000000,100.000000,100.000000,87.096774,86.666667,100.000000,96.666667,100.000000
1,2010,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,96.666667,87.096774,100.000000,100.000000
2,2011,100.000000,100.000000,100.000000,100.000000,80.645161,0.000000,41.935484,100.000000,100.000000,96.774194,83.333333,67.741935
3,2012,58.064516,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,80.645161
4,2013,96.774194,96.428571,80.645161,100.000000,100.000000,93.333333,93.548387,100.000000,100.000000,93.548387,100.000000,100.000000
5,2014,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,90.322581,100.000000,100.000000,100.000000,100.000000
6,2015,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,90.000000,96.774194
7,2016,77.419355,100.000000,100.000000,100.000000,100.000000,86.666667,54.838710,100.000000,100.000000,100.000000,93.333333,54.838710
8,2017,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,96.774194,100.000000,100.000000
9,2018,100.000000,100.000000,100.000000,66.666667,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000
10,2019,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,93.548387,20.000000,100.000000,83.333333,100.000000
11,2020,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,96.774194,100.000000,100.000000,100.000000,100.000000
12,2021,96.774194,100.000000,100.000000,100.000000,100.000000,100.000000,96.774194,100.000000,96.666667,100.000000,96.666667,100.000000
13,2022,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,96.774194
14,2023,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000
15,2024,93.548387,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,87.096774,100.000000,100.000000,93.333333,100.000000
16,2025,100.000000,100.000000,100.000000,100.000000,93.548387,96.666667,100.000000,100.000000,16.666667,NaN,NaN,NaN

In [9]:
df = pd.read_csv(os.getcwd()+'/data/MQAr/MP10/ES0001RA001.csv')

def create_QAQCMMA_VALOR(df,pol):

    df = df.rename(columns={'VALOR':'VALOR_ORIGINAL'})

    flags_invalidos = ['!', 'IF', 'IO', 'IC', 'I%', 'IL', 'IE', 'IS', 'IU', 'IM', 'IP', 'ID', 'IT', 'IR', 
                       'Fora da Faixa de Medição', 'Disabilitada Temporariamente', 'Inválido', 
                       'Insuficientes', 'Inexistente']

    df['QAQC_INTERNO'] = ~df['QAQC_INTERNO'].isin(flags_invalidos)
    
    DEFAULT_RANGE_LIMITS = {
        "O3": (0, 500),
        "CO": (0, 50),
        "NO2": (0, 1000),
        "NOX": (0, 2000),
        "SO2": (0, 1000),
        "MP25": (0, 1000),
        "MP10": (0, 2000),
    }

    df['QAQC_MMA'] = df['QAQC_INTERNO']

    if pol in list(DEFAULT_RANGE_LIMITS.keys()):
        lim_min = DEFAULT_RANGE_LIMITS[pol][0]
        lim_max = DEFAULT_RANGE_LIMITS[pol][1]
    else:
        lim_min = 0
        lim_max = np.inf

    df['VALOR'] = df['VALOR_ORIGINAL']

    df['VALOR'] = pd.to_numeric(df['VALOR'], errors='coerce')
    
    df.loc[df['QAQC_MMA'] & (df['VALOR'].isna() | (df['VALOR'] < lim_min) | (df['VALOR'] > lim_max)), 'QAQC_MMA'] = False
    
    df.loc[~df['QAQC_MMA'], 'VALOR'] = np.nan
    
    df = df[['DATETIME', 'ANO', 'MES', 'DIA', 'HORA', 'VALOR', 'VALOR_ORIGINAL', 'UNIDADE', 'QAQC_INTERNO', 'QAQC_MMA']]

    return df

In [15]:
DEFAULT_RANGE_LIMITS = {
        "O3": (0, 500),
        "CO": (0, 50),
        "NO2": (0, 1000),
        "NOX": (0, 2000),
        "SO2": (0, 1000),
        "MP25": (0, 1000),
        "MP10": (0, 2000),
    }

DEFAULT_RANGE_LIMITS['MP10'][1]

2000

In [17]:
list(DEFAULT_RANGE_LIMITS.keys())

['O3', 'CO', 'NO2', 'NOX', 'SO2', 'MP25', 'MP10']

In [29]:
pol = 'CCCC'

df['QAQC_MMA'] = df['QAQC_INTERNO']

if pol in list(DEFAULT_RANGE_LIMITS.keys()):
    lim_min = DEFAULT_RANGE_LIMITS[pol][0]
    lim_max = DEFAULT_RANGE_LIMITS[pol][1]
else:
    lim_min = 0
    lim_max = np.inf

In [30]:
df['VALOR'] = df['VALOR_ORIGINAL']

df['VALOR'] = pd.to_numeric(df['VALOR'], errors='coerce')

df.loc[df['QAQC_MMA'] & (df['VALOR'].isna() | (df['VALOR'] < lim_min) | (df['VALOR'] > lim_max)), 'QAQC_MMA'] = False

df.loc[~df['QAQC_MMA'], 'VALOR'] = np.nan

df = df[['DATETIME', 'ANO', 'MES', 'DIA', 'HORA', 'VALOR', 'VALOR_ORIGINAL', 'UNIDADE', 'QAQC_INTERNO', 'QAQC_MMA']]

In [32]:
df.columns

Index(['DATETIME', 'ANO', 'MES', 'DIA', 'HORA', 'VALOR_ORIGINAL', 'UNIDADE',
       'QAQC_INTERNO', 'QAQC_MMA', 'VALOR'],
      dtype='object')

In [36]:
import pandas as pd
import os
from collections import defaultdict
from datetime import datetime, timedelta
import re
import numpy as np
from pathlib import Path

def ppb_to_ug(df,pol):

    if pol == 'so2':

        df.loc[df["Unidade"] != "ug/m3", "Valor"] *= 2661260.49/10**6        

    elif pol == 'no2':

        df.loc[df["Unidade"] != "ug/m3", "Valor"] *= 1911038.92/10**6        

    elif pol == 'o3':

        df.loc[df["Unidade"] != "ug/m3", "Valor"] *= 1993889.17/10**6        
    
    df.loc[:, "Unidade"] = "ug/m3"

    return df

def rectify_MT(path):

    dict_pols_stat = defaultdict(list)

    files = os.listdir(path)
    
    print(files)
    
    for item in files:
        
        estacao = " ".join(item.split('-')[1].split('.')[0].split('_')[0:2])
    
        print(estacao)
    
        df = pd.read_excel(path+item)
    
        df = df.drop(columns=['Nome da estação'])
    
        lista_pols = set(df['Poluente'])
    
        for pol in lista_pols:
    
            df_pol = df[df["Poluente"] == pol]
            
            if pol in ['no2','so2','o3']:
    
                df_pol = ppb_to_ug(df_pol,pol)
    
            df_pol_hora = df_pol.groupby(["Ano", "Mes", "Dia", "Hora", "Unidade"])
            
            df_pol_hora = df_pol_hora.filter(lambda g: len(g) >= 9)
            
            df_pol = (
                df_pol_hora.groupby(["Ano", "Mes", "Dia", "Hora", "Unidade"], as_index=False)
                      .agg({"Valor": "mean"})
            )
    
            df_pol['QAQC_INTERNO'] = None
    
            df_pol = df_pol.rename(columns={'Ano':'ANO',
                                            'Mes':'MES',
                                            'Dia':'DIA',
                                            'Hora':'HORA',
                                            'Unidade':'UNIDADE',
                                            'Valor':'VALOR'})
    
            for col in ["ANO", "MES", "DIA", "HORA"]:
                df_pol[col] = pd.to_numeric(df_pol[col], errors="coerce").astype("Int64")
            
            dict_pols_stat[estacao+'_'+pol].append(df_pol)

    dict_pols_MT = {
        'co':'CO',
        'no2': 'NO2',
        'so2': 'SO2',
        'o3': 'O3',
        'pm2p5':'MP25',
        'pm10': 'MP10'
    }

    dict_formatado = {}
    
    for chave in dict_pols_stat.keys():
        
        lista_dfs = dict_pols_stat[chave]
        
        df = pd.concat(lista_dfs, ignore_index=True)
    
        df["DATETIME"] = pd.to_datetime(
            df.apply(lambda r: f"{r.ANO}-{r.MES}-{r.DIA} {r.HORA}:00:00", axis=1)
        )
        df = df.set_index("DATETIME")
    
        df = df.sort_index()
        
        lista_horas = pd.date_range(
            start=df.index.min(), 
            end=df.index.max(), 
            freq='H').strftime('%Y-%m-%d %H:%M:%S').tolist()
        
        if len(lista_horas) != len(df):
            df = df.reindex(pd.DatetimeIndex(lista_horas))
    
        df['DATETIME'] = df.index
    
        df = df[['DATETIME','ANO','MES','DIA','HORA','VALOR','UNIDADE','QAQC_INTERNO']]
        
        dict_formatado[chave] = df
        
        primeiros_valores = {}
    
    for chave, df in dict_formatado.items():
        
        if ~df['VALOR'].isna().all() and (df['VALOR'] > 0).any(): 
            
            linha_valida = df[df["VALOR"].notna() & (df["VALOR"] > 0)].iloc[0]
            primeiros_valores[chave] = linha_valida["DATETIME"]
    
    codigo_estacao_MT = {}
    
    for chave in primeiros_valores.keys():
        
        station = chave.split('_')[0]
        data = primeiros_valores[chave]
        
        if station in codigo_estacao_MT:
            if data <= codigo_estacao_MT[station]:
                codigo_estacao_MT[station] = data
        else:
            codigo_estacao_MT[station] = data
    
    sorted_items = sorted(
        codigo_estacao_MT.items(),
        key=lambda x: (x[1], x[0])
    )
    
    codigo_estacao_MT = {}
    for i, (nome, ts) in enumerate(sorted_items, start=1):
        codigo = f"MT{i:04d}"
        codigo_estacao_MT[nome] = codigo
        
    for chave, df in dict_formatado.items():
        
        estacao = codigo_estacao_MT[chave.split('_')[0]]
        
        cod_pol = tabela_pols.loc[tabela_pols['POLUENTE'] == dict_pols_MT[chave.split('_')[-1]], 'COD_POLUENTE'].values[0]
        
        nome_pasta = tabela_pols.loc[tabela_pols['COD_POLUENTE'] == int(cod_pol), 'NOME_PASTA'].values[0]

        df = create_QAQCMMA_VALOR(df,nome_pasta)
        
        df.to_csv('/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/'+nome_pasta+'/'+estacao+'IA'+str(cod_pol).zfill(3)+'.csv',index=False)

    dict_stations_MT = {
        'Sema':'CPA - SEMA - CBA',
        'BEA CBA': 'Dom Aquino - BEA - CBA',
        'CBM VG': 'Água Limpa - CBM - VG',
        'Mae Bonifacia': 'Duque de Caxias - Pq Mãe Bonifácia - CBA',
        'UFMT':'Boa Esperança - UFMT - CBA'
    }
    
    df_ids = pd.DataFrame({
        'ID_OEMA': codigo_estacao_MT.keys(),
        'ID_MMA':list(codigo_estacao_MT.values())})
    
    df_ids["ID_OEMA"] = df_ids["ID_OEMA"].replace(dict_stations_MT)

    print(df_ids)
    
    return df_ids

funcoes = {
    'MT': rectify_MT
}

#lista_estados = ['SC','RS','MT','DF','MA','BA','ES','MG','SP','RJ']
lista_estados = ['MT']

tabela_ids = pd.read_csv('/home/nobre/Notebooks/RQAR_2025_book/data/Monitoramento_QAr_BR.csv')
tabela_pols = pd.read_csv('/home/nobre/Notebooks/RQAR_2025_book/data/dicionarios/CODIGO_POLUENTES.csv')

for estado in lista_estados:
    
    path = os.getcwd()+'/data/DADOS_BRUTOS/' + estado + '/'

    df_ids = funcoes[estado](path)
    
    create_df_estacao(estado,df_ids)

['dados_monitoramento-Sema.xlsx', 'dados_monitoramento-BEA_CBA_24-25.xlsx', 'dados_monitoramento-BEA_CBA_22-23.xlsx', 'dados_monitoramento-CBM_VG_22-23.xlsx', 'dados_monitoramento-CBM_VG_24-25.xlsx', 'dados_monitoramento-Mae_Bonifacia_22-23.xlsx', 'dados_monitoramento-Mae_Bonifacia_24-25.xlsx', 'dados_monitoramento-UFMT.xlsx']
Sema
BEA CBA

KeyboardInterrupt:

In [38]:
df = df_dia.groupby(['ANO'])

NameError: name 'df_dia' is not defined

In [72]:

tabela_pols = pd.read_csv('/home/nobre/Notebooks/RQAR_2025_book/data/dicionarios/CODIGO_POLUENTES.csv')

In [73]:
for pol in tabela_pols['NOME_PASTA'].unique():
    print(pol)

MP10
MP25
SO2
NO2
O3
FMC
CO
PTS
CHUMBO
BENZENO
CH4
ERT
ETILBENZENO
H2S
NH3
HCNM
NO
NOX
MP1
ACETAL
FORMAL
TOLUENO
XILENO
VOC
OXILENO
HCT
MPXILENO

In [2]:
import pandas as pd
import os
from collections import defaultdict
from datetime import datetime, timedelta
import re
import numpy as np
from pathlib import Path

os.chdir('/home/nobre/Notebooks/RQAR_2025_book/')

In [18]:
funcoes = {
    
    'MT': rectify_MT,
}

lista_estados = ['MT']

tabela_ids = pd.read_csv('/home/nobre/Notebooks/RQAR_2025_book/data/Monitoramento_QAr_BR.csv')
tabela_pols = pd.read_csv('/home/nobre/Notebooks/RQAR_2025_book/data/dicionarios/CODIGO_POLUENTES.csv')

In [72]:

estado = 'DF'
  
path = os.getcwd()+'/data/DADOS_BRUTOS/' + estado + '/'

#df_ids = funcoes[estado](path)
    
#create_df_estacao(estado,df_ids)

In [52]:
dict_pols_stat = defaultdict(list)

files = os.listdir(path)

print(files)

for item in files:
    
    estacao = " ".join(item.split('-')[1].split('.')[0].split('_')[0:2])

    print(estacao)

    df = pd.read_excel(path+item)

    df = df.drop(columns=['Nome da estação'])

    lista_pols = set(df['Poluente'])

    for pol in lista_pols:

        df_pol = df[df["Poluente"] == pol]
        
        if pol in ['no2','so2','o3']:

            df_pol = ppb_to_ug(df_pol,pol)

        df_pol_hora = df_pol.groupby(["Ano", "Mes", "Dia", "Hora", "Unidade"])
        
        df_pol_hora = df_pol_hora.filter(lambda g: len(g) >= 9)
        
        df_pol = (
            df_pol_hora.groupby(["Ano", "Mes", "Dia", "Hora", "Unidade"], as_index=False)
                  .agg({"Valor": "mean"})
        )

        df_pol['QAQC_INTERNO'] = None

        df_pol = df_pol.rename(columns={'Ano':'ANO',
                                        'Mes':'MES',
                                        'Dia':'DIA',
                                        'Hora':'HORA',
                                        'Unidade':'UNIDADE',
                                        'Valor':'VALOR'})

        for col in ["ANO", "MES", "DIA", "HORA"]:
            df_pol[col] = pd.to_numeric(df_pol[col], errors="coerce").astype("Int64")
        
        dict_pols_stat[estacao+'_'+pol].append(df_pol)

['dados_monitoramento-Sema.xlsx', 'dados_monitoramento-BEA_CBA_24-25.xlsx', 'dados_monitoramento-BEA_CBA_22-23.xlsx', 'dados_monitoramento-CBM_VG_22-23.xlsx', 'dados_monitoramento-CBM_VG_24-25.xlsx', 'dados_monitoramento-Mae_Bonifacia_22-23.xlsx', 'dados_monitoramento-Mae_Bonifacia_24-25.xlsx', 'dados_monitoramento-UFMT.xlsx']
Sema
BEA CBA
BEA CBA
CBM VG
CBM VG
Mae Bonifacia
Mae Bonifacia
UFMT

In [46]:
def ppb_to_ug(df,pol):

    if pol == 'so2':

        df.loc[df["Unidade"] != "ug/m3", "Valor"] *= 2661260.49/10**6        

    elif pol == 'no2':

        df.loc[df["Unidade"] != "ug/m3", "Valor"] *= 1911038.92/10**6        

    elif pol == 'o3':

        df.loc[df["Unidade"] != "ug/m3", "Valor"] *= 1993889.17/10**6        
    
    df.loc[:, "Unidade"] = "ug/m3"

    return df

In [60]:
dict_pols_MT = {
    'co':'CO',
    'no2': 'NO2',
    'so2': 'SO2',
    'o3': 'O3',
    'pm2p5':'MP25',
    'pm10': 'MP10'
}

dict_formatado = {}

for chave in dict_pols_stat.keys():
    
    lista_dfs = dict_pols_stat[chave]
    
    df = pd.concat(lista_dfs, ignore_index=True)

    df["DATETIME"] = pd.to_datetime(
        df.apply(lambda r: f"{r.ANO}-{r.MES}-{r.DIA} {r.HORA}:00:00", axis=1)
    )
    df = df.set_index("DATETIME")

    df = df.sort_index()
    
    lista_horas = pd.date_range(
        start=df.index.min(), 
        end=df.index.max(), 
        freq='H').strftime('%Y-%m-%d %H:%M:%S').tolist()
    
    if len(lista_horas) != len(df):
        df = df.reindex(pd.DatetimeIndex(lista_horas))

    df['DATETIME'] = df.index

    df = df[['DATETIME','ANO','MES','DIA','HORA','VALOR','UNIDADE','QAQC_INTERNO']]
    
    dict_formatado[chave] = df

primeiros_valores = {}

for chave, df in dict_formatado.items():
    
    if ~df['VALOR'].isna().all() and (df['VALOR'] > 0).any(): 
        
        linha_valida = df[df["VALOR"].notna() & (df["VALOR"] > 0)].iloc[0]
        primeiros_valores[chave] = linha_valida["DATETIME"]

codigo_estacao_MT = {}

for chave in primeiros_valores.keys():
    
    station = chave.split('_')[0]
    data = primeiros_valores[chave]
    
    if station in codigo_estacao_MT:
        if data <= codigo_estacao_MT[station]:
            codigo_estacao_MT[station] = data
    else:
        codigo_estacao_MT[station] = data

sorted_items = sorted(
    codigo_estacao_MT.items(),
    key=lambda x: (x[1], x[0])
)

codigo_estacao_MT = {}
for i, (nome, ts) in enumerate(sorted_items, start=1):
    codigo = f"MT{i:04d}"
    codigo_estacao_MT[nome] = codigo
    
for chave, df in dict_formatado.items():
    
    estacao = codigo_estacao_MT[chave.split('_')[0]]
    
    cod_pol = tabela_pols.loc[tabela_pols['POLUENTE'] == dict_pols_MT[chave.split('_')[-1]], 'COD_POLUENTE'].values[0]
    
    nome_pasta = tabela_pols.loc[tabela_pols['COD_POLUENTE'] == int(cod_pol), 'NOME_PASTA'].values[0]
    
    df.to_csv('/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/'+nome_pasta+'/'+estacao+'RA'+str(cod_pol).zfill(3)+'.csv',index=False)

df_ids = pd.DataFrame({
    'ID_OEMA': codigo_estacao_MT.keys(),
    'ID_MMA':list(codigo_estacao_MT.values())})

return df_ids

/tmp/ipykernel_564959/2479180702.py:25: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_564959/2479180702.py:25: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_564959/2479180702.py:25: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_564959/2479180702.py:25: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_564959/2479180702.py:25: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_564959/2479180702.py:25: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_564959/2479180702.py:25: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_564959/2479180702.py:25: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_564959/2479180702.py:25: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_564959/2479180702.py:25: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_564959/2479180702.py:25: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_564959/2479180702.py:25: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_564959/2479180702.py:25: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_564959/2479180702.py:25: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_564959/2479180702.py:25: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_564959/2479180702.py:25: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_564959/2479180702.py:25: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_564959/2479180702.py:25: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_564959/2479180702.py:25: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_564959/2479180702.py:25: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_564959/2479180702.py:25: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_564959/2479180702.py:25: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_564959/2479180702.py:25: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_564959/2479180702.py:25: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_564959/2479180702.py:25: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_564959/2479180702.py:25: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_564959/2479180702.py:25: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_564959/2479180702.py:25: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_564959/2479180702.py:25: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_564959/2479180702.py:25: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(

SyntaxError: 'return' outside function (2479180702.py, line 85)

In [61]:
df_ids

         ID_OEMA  ID_MMA
0  Mae Bonifacia  MT0001
1        BEA CBA  MT0002
2         CBM VG  MT0003
3           Sema  MT0004
4           UFMT  MT0005

In [185]:
from datetime import timedelta

def fix_24h(row):
    if isinstance(row, str) and row.startswith("24:"):
        # substitui 24: por 00:
        new_str = row.replace("24:", "00:", 1)
        # converte para datetime
        dt = pd.to_datetime(new_str, errors="coerce")
        # adiciona 1 dia
        if pd.notna(dt):
            dt += timedelta(days=1)
        return dt
    else:
        return pd.to_datetime(row, errors="coerce")

In [70]:
dict_stations_MT = {
        'Sema':'CPA - SEMA - CBA',
        'BEA CBA': 'Dom Aquino - BEA - CBA',
        'CBM VG': 'Água Limpa - CBM - VG',
        'Mae Bonifacia': 'Duque de Caxias - Pq Mãe Bonifácia - CBA',
        'UFMT':'Boa Esperança - UFMT - CBA'
    }
    
df_ids = pd.DataFrame({
    'ID_OEMA': codigo_estacao_MT.keys(),
    'ID_MMA':list(codigo_estacao_MT.values())})


df_ids["ID_OEMA"] = df_ids["ID_OEMA"].replace(dict_stations_MT)


df_ids['ID_OEMA']

0    Duque de Caxias - Pq Mãe Bonifácia - CBA
1                      Dom Aquino - BEA - CBA
2                       Água Limpa - CBM - VG
3                            CPA - SEMA - CBA
4                  Boa Esperança - UFMT - CBA
Name: ID_OEMA, dtype: object

In [71]:
df_ids

                                    ID_OEMA  ID_MMA
0  Duque de Caxias - Pq Mãe Bonifácia - CBA  MT0001
1                    Dom Aquino - BEA - CBA  MT0002
2                     Água Limpa - CBM - VG  MT0003
3                          CPA - SEMA - CBA  MT0004
4                Boa Esperança - UFMT - CBA  MT0005

In [120]:
estado = 'DF'

In [249]:
path = os.getcwd()+'/data/DADOS_BRUTOS/' + estado + '/'

path = path + 'Monitor Report 2024_FINAL.xlsx'

df = pd.read_excel(path)

df.iloc[1] = df.iloc[1].ffill()

poluentes = ['CO_ppm','NO2_ug/m3','NO_ug/m3','NOx_ug/m3','O3_ug/m3','PM10','PM25','PTS','SO2_ug/m3']

dict_pols = {'CO_ppm':'CO',
             'NO2_ug/m3':'NO2',
             'NO_ug/m3':'NO',
             'NOx_ug/m3':'NOX',
             'O3_ug/m3':'O3',
             'PM10':'MP10',
             'PM25':'MP25',
             'PTS':'PTS',
             'SO2_ug/m3':'SO2'}

df.columns = df.iloc[1]

df = df.drop(index=[0, 1]).reset_index(drop=True)

df = df.rename(columns={'Date Time':'DATETIME'})

estacoes = set(df.columns[1:])

dict_pols_stat = defaultdict(list)

for estacao in estacoes:

    df_estacao = df[["DATETIME",estacao]]

    df_estacao.columns = [df_estacao.columns.tolist()[0]] + df_estacao.iloc[0, 1:].tolist()

    df_estacao = df_estacao.drop(index=[0]).reset_index(drop=True)

    for pol in poluentes:

        if pol in df_estacao.columns:
            
            df_pol = df_estacao[["DATETIME",pol]]

            df_pol['UNIDADE'] = df_pol[pol][0]

            df_pol = df_pol.drop(index=[0]).reset_index(drop=True)

            df_pol = df_pol[df_pol["DATETIME"].astype(str).str.contains(r"\d", na=False)].reset_index(drop=True)

            df_pol['DATETIME'] = df_pol['DATETIME'].apply(fix_24h)

            df_pol = df_pol.rename(columns={pol:'VALOR'})

            df_pol.index = df_pol['DATETIME']

            lista_horas = pd.date_range(
                start=df_pol.index.min(), 
                end=df_pol.index.max(), 
                freq='H').strftime('%Y-%m-%d %H:%M:%S').tolist()
            
            if len(lista_horas) != len(df_pol):
                df_pol = df_pol.reindex(pd.DatetimeIndex(lista_horas))
            
            df_pol['QAQC_INTERNO'] = None
            
            df_pol.insert(1, 'ANO', df_pol.index.year)
            df_pol.insert(2, 'MES', df_pol.index.month)
            df_pol.insert(3, 'DIA', df_pol.index.day)
            df_pol.insert(4, 'HORA', df_pol.index.hour)

            pol = dict_pols[pol]

            df_pol['VALOR'] = pd.to_numeric(df_pol['VALOR'], errors='coerce')

            df_pol = df_pol[['DATETIME','ANO','MES','DIA','HORA','VALOR','UNIDADE','QAQC_INTERNO']] 

            dict_pols_stat[estacao+'_'+pol] = df_pol

/tmp/ipykernel_564959/901552261.py:45: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_pol['UNIDADE'] = df_pol[pol][0]
/tmp/ipykernel_564959/1508039512.py:14: UserWarning: Parsing dates in %d:%M %m/%H/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  return pd.to_datetime(row, errors="coerce")
/tmp/ipykernel_564959/901552261.py:57: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_564959/901552261.py:45: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_pol['UNIDADE'] = df_pol[pol][0]
/tmp/ipykernel_564959/1508039512.py:14: UserWarning: Parsing dates in %d:%M %m/%H/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  return pd.to_datetime(row, errors="coerce")
/tmp/ipykernel_564959/901552261.py:57: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_564959/901552261.py:45: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_pol['UNIDADE'] = df_pol[pol][0]
/tmp/ipykernel_564959/1508039512.py:14: UserWarning: Parsing dates in %d:%M %m/%H/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  return pd.to_datetime(row, errors="coerce")
/tmp/ipykernel_564959/901552261.py:57: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_564959/901552261.py:45: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_pol['UNIDADE'] = df_pol[pol][0]
/tmp/ipykernel_564959/1508039512.py:14: UserWarning: Parsing dates in %d:%M %m/%H/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  return pd.to_datetime(row, errors="coerce")
/tmp/ipykernel_564959/901552261.py:57: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_564959/901552261.py:45: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_pol['UNIDADE'] = df_pol[pol][0]
/tmp/ipykernel_564959/1508039512.py:14: UserWarning: Parsing dates in %d:%M %m/%H/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  return pd.to_datetime(row, errors="coerce")
/tmp/ipykernel_564959/901552261.py:57: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_564959/901552261.py:45: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_pol['UNIDADE'] = df_pol[pol][0]
/tmp/ipykernel_564959/1508039512.py:14: UserWarning: Parsing dates in %d:%M %m/%H/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  return pd.to_datetime(row, errors="coerce")
/tmp/ipykernel_564959/901552261.py:57: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_564959/901552261.py:45: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_pol['UNIDADE'] = df_pol[pol][0]
/tmp/ipykernel_564959/1508039512.py:14: UserWarning: Parsing dates in %d:%M %m/%H/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  return pd.to_datetime(row, errors="coerce")
/tmp/ipykernel_564959/901552261.py:57: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_564959/901552261.py:45: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_pol['UNIDADE'] = df_pol[pol][0]
/tmp/ipykernel_564959/1508039512.py:14: UserWarning: Parsing dates in %d:%M %m/%H/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  return pd.to_datetime(row, errors="coerce")
/tmp/ipykernel_564959/901552261.py:57: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_564959/901552261.py:45: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_pol['UNIDADE'] = df_pol[pol][0]
/tmp/ipykernel_564959/1508039512.py:14: UserWarning: Parsing dates in %d:%M %m/%H/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  return pd.to_datetime(row, errors="coerce")
/tmp/ipykernel_564959/901552261.py:57: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_564959/901552261.py:45: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_pol['UNIDADE'] = df_pol[pol][0]
/tmp/ipykernel_564959/1508039512.py:14: UserWarning: Parsing dates in %d:%M %m/%H/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  return pd.to_datetime(row, errors="coerce")
/tmp/ipykernel_564959/901552261.py:57: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(
/tmp/ipykernel_564959/901552261.py:45: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_pol['UNIDADE'] = df_pol[pol][0]
/tmp/ipykernel_564959/1508039512.py:14: UserWarning: Parsing dates in %d:%M %m/%H/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  return pd.to_datetime(row, errors="coerce")
/tmp/ipykernel_564959/901552261.py:57: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lista_horas = pd.date_range(

In [258]:
primeiros_valores = {}

for chave, df in dict_pols_stat.items():  
    
    if ~df['VALOR'].isna().all() and (df['VALOR'] > 0).any(): 
        
        linha_valida = df[df["VALOR"].notna() & (df["VALOR"] > 0)].iloc[0]
        primeiros_valores[chave] = linha_valida["DATETIME"]

codigo_estacao_DF = {}

for chave in primeiros_valores.keys():
    
    station = chave.split('_')[0]
    data = primeiros_valores[chave]
    
    if station in codigo_estacao_DF:
        if data <= codigo_estacao_DF[station]:
            codigo_estacao_DF[station] = data
    else:
        codigo_estacao_DF[station] = data

sorted_items = sorted(
    codigo_estacao_DF.items(),
    key=lambda x: (x[1], x[0])
)

codigo_estacao_DF = {}
for i, (nome, ts) in enumerate(sorted_items, start=1):
    codigo = f"DF{i:04d}"
    codigo_estacao_DF[nome] = codigo
    
for chave, df in dict_pols_stat.items():
    
    estacao = codigo_estacao_DF[chave.split('_')[0]]
    
    cod_pol = tabela_pols.loc[tabela_pols['POLUENTE'] == chave.split('_')[-1], 'COD_POLUENTE'].values[0]
    
    nome_pasta = tabela_pols.loc[tabela_pols['COD_POLUENTE'] == int(cod_pol), 'NOME_PASTA'].values[0]
    
    df.to_csv('/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/'+nome_pasta+'/'+estacao+'RA'+str(cod_pol).zfill(3)+'.csv',index=False)

dict_oemas = {
    'Estação CRAS FERCAL': 'Fercal CRAS',
    'Estação Escola':	   'Fercal Escola'}

df_ids = pd.DataFrame({
    'ID_OEMA': codigo_estacao_DF.keys(),
    'ID_MMA':list(codigo_estacao_DF.values())})

df_ids['ID_OEMA'] = df_ids['ID_OEMA'].replace(dict_oema)

return df_ids

In [275]:
df_ufs = pd.read_csv('/home/nobre/Notebooks/RQAR_2025_book/data/dicionarios/IBGE_UFS_CODIGOS.csv')
    
cod_uf =  df_ufs.loc[df_ufs['UF'] == uf, 'CODIGOS'].values[0]

print(cod_uf)

if os.path.exists('/home/nobre/Notebooks/RQAR_2025_book/data/DADOS_ESTACOES/'+uf+'_estacoes.csv'):

    df_estacao = pd.read_csv('/home/nobre/Notebooks/RQAR_2025_book/data/DADOS_ESTACOES/'+uf+'_estacoes.csv')

    df_estacao['ID_MMA'] = df_estacao['ID_OEMA'].map(df_ids.set_index('ID_OEMA')['ID_MMA'])

else:

    colunas = ['ID_OEMA', 'UF', 'ID_MMA', 'COD_UF_IBGE', 'CIDADE', 'CD_MUN',
               'PROPRIETARIO', 'PROP_ENTIDADE', 'OPERADOR', 'OP_ENTIDADE', 'LATITUDE',
               'LONGITUDE', 'MOBILIDADE', 'REALOCACAO', 'MARCA', 'CATEGORIA',
               'FUNCIONAMENTO', 'METODO', 'FINALIDADE', 'POLUENTE',
               'INICIO', 'STATUS', 'FIM', 'CALIBRACAO', 'OBS_CALIBRACAO', 'MONITORAR',
               'FONTE', 'OBS_GERAIS','DADOS_MONITORAMENTO','RECONHECIDA','REP_ESPACIAL_DECLARADA']
    
    df_estacao = pd.DataFrame(columns=colunas)

df_ids = pol_to_station(df_ids)

mapa = dict(zip(df_ids['ID_MMA'], df_ids['POLUENTE']))

df_estacao['POLUENTE'] = df_estacao['ID_MMA'].map(mapa).fillna(df_estacao['POLUENTE'])

#df_estacao = df_estacao.reindex(df_ids.index)

#df_estacao[["ID_MMA", "ID_OEMA", "POLUENTE"]] = df_ids[["ID_MMA", "ID_OEMA", "POLUENTE"]].values

df_estacao.loc[:, "COD_UF_IBGE"] = cod_uf
df_estacao.loc[:, "UF"] = uf
    
#df_estacao.to_csv('/home/nobre/Notebooks/RQAR_2025_book/data/DADOS_ESTACOES/'+uf+'_estacoes_teste.csv', index=False)

53

In [276]:
df_estacao['POLUENTE']

0                                 PM2,5
1                                  PM10
2                             MP10,MP25
3                                  PM10
4                                  PM10
5                           MP2,5, MP10
6                           MP2,5, MP10
7                           MP2,5, MP10
8    MP10,NO,CO,PTS,O3,SO2,NO2,NOX,MP25
Name: POLUENTE, dtype: object

In [262]:
def pol_to_station(df_ids):

    base_path = Path('/home/nobre/Notebooks/RQAR_2025_book/data/MQAr/')

    id_to_poluentes = {}
    
    for poluente_dir in base_path.iterdir():
        if poluente_dir.is_dir():
            poluente = poluente_dir.name
    
            arquivos = [arq.stem for arq in poluente_dir.glob("*")]
    
            for id_mma in df_ids["ID_MMA"]:
                if any(str(arq).startswith(id_mma) for arq in arquivos):
                    id_to_poluentes.setdefault(id_mma, []).append(poluente)
    
    df_ids["POLUENTE"] = df_ids["ID_MMA"].map(id_to_poluentes).fillna("").apply(lambda x: ",".join(x) if isinstance(x, list) else "")
    
    return(df_ids)

# Varrer MQAr

In [283]:
caminho_MQAr = os.getcwd() + '/data/MQAr/'

lista_pols = os.listdir(caminho_MQAr)

arquivos_MQAr = pd.DataFrame({'ID_MMA_COMPLETO':[]})

for pol in lista_pols:

    if '.ipynb' not in pol and pol != 'METEREOLOGICO':

        caminho_pol = caminho_MQAr+pol

        estacoes_pols = os.listdir(caminho_pol)

        print(pol)

        for estacao in estacoes_pols:

            if estacao != '.ipynb_checkpoints':

                arquivos_MQAr.loc[len(arquivos_MQAr)] = estacao[:-4]

arquivos_MQAr['ID_MMA'] = arquivos_MQAr['ID_MMA_COMPLETO'].str[:6]

MP10
NO
FORMAL
HCT
BENZENO
CO
H2S
ACETAL
PTS
CH4
MP1
O3
ETILBENZENO
SO2
NO2
TOLUENO
VOC
CHUMBO
NH3
OXILENO
HCNM
NOX
ERT
MPXILENO
MP25
XILENO

In [284]:
Monitoramento_MQAr = pd.read_csv(os.getcwd()+'/data/Monitoramento_QAr_BR.csv')

df_monitoramento = pd.DataFrame({'ID_MMA_COMPLETO':Monitoramento_MQAr['ID_MMA_COMPLETO']})

df_monitoramento['ID_MMA'] = df_monitoramento['ID_MMA_COMPLETO'].str[:6]

arquivos_MQAr['BANCO_DADOS'] = arquivos_MQAr['ID_MMA'].isin(df_monitoramento['ID_MMA']).map({True: 'Sim', False: 'Nao'})

print(arquivos_MQAr)

     ID_MMA_COMPLETO  ID_MMA BANCO_DADOS
0        SP0248RA001  SP0248         Sim
1        RJ0031RA001  RJ0031         Sim
2        RJ0282RA001  RJ0282         Sim
3        SP0085RA001  SP0085         Sim
4        RJ0048RA001  RJ0048         Sim
...              ...     ...         ...
2403     RJ0218RA023  RJ0218         Sim
2404     RJ0012RA023  RJ0012         Sim
2405     RJ0036RA023  RJ0036         Sim
2406     RJ0071RA023  RJ0071         Sim
2407     RJ0216RA023  RJ0216         Sim

[2408 rows x 3 columns]

In [285]:
df_monitoramento

     ID_MMA_COMPLETO  ID_MMA
0        AC0030RA002  AC0030
1        AC0001RA002  AC0001
2        AC0002RA002  AC0002
3        AC0003RA002  AC0003
4        AC0004RA002  AC0004
...              ...     ...
2361     SP0323RA002  SP0323
2362     TO0003RA002  TO0003
2363     TO0001RA002  TO0001
2364     TO0002RA002  TO0002
2365             NaN     NaN

[2366 rows x 2 columns]

In [286]:
num_sim = (arquivos_MQAr['BANCO_DADOS'] == 'Sim').sum()
print(num_sim)

2311

In [288]:
df_nao = arquivos_MQAr[arquivos_MQAr['BANCO_DADOS'] == 'Nao']
print(df_nao)

for id_mma_comp in df_nao['ID_MMA_COMPLETO']:
    if 'SP' in id_mma_comp:
        print(id_mma_comp)

     ID_MMA_COMPLETO  ID_MMA BANCO_DADOS
10       MA1002ND001  MA1002         Nao
13       RJ1014ND001  RJ1014         Nao
16       MA1006ND001  MA1006         Nao
20       RJ1004ND001  RJ1004         Nao
38       SP0084RA001  SP0084         Nao
...              ...     ...         ...
2324     RJ1004ND002  RJ1004         Nao
2331     PA1003ND002  PA1003         Nao
2343     PA1002ND002  PA1002         Nao
2349     MA1004ND002  MA1004         Nao
2351     RN1001ND002  RN1001         Nao

[97 rows x 3 columns]
SP0084RA001
SP0236RA001
SP0084RA017
SP0084RA007
SP0084RA005
SP0236RA005
SP0084RA004
SP0084RA018